package com.ccit.mmwlan.phone; class CertApplyInfo { void a() { int a;
a=0;// .class public Lcom/ccit/mmwlan/phone/CertApplyInfo;
a=0;// .super Ljava/lang/Object;
a=0;// .source "CertApplyInfo.java"
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field private cert:Ljava/lang/String;
a=0;// 
a=0;// .field private encKey:Ljava/lang/String;
a=0;// 
a=0;// .field private errormsg:Ljava/lang/String;
a=0;// 
a=0;// .field private mobilePhone:Ljava/lang/String;
a=0;// 
a=0;// .field private randNum:Ljava/lang/String;
a=0;// 
a=0;// .field private result:Ljava/lang/String;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 3
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcom/ccit/mmwlan/phone/CertApplyInfo;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public getCert()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 29
a=0;//     iget-object v0, p0, Lcom/ccit/mmwlan/phone/CertApplyInfo;->cert:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getEncKey()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 45
a=0;//     iget-object v0, p0, Lcom/ccit/mmwlan/phone/CertApplyInfo;->encKey:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getErrormsg()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 21
a=0;//     iget-object v0, p0, Lcom/ccit/mmwlan/phone/CertApplyInfo;->errormsg:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getMobilePhone()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 37
a=0;//     iget-object v0, p0, Lcom/ccit/mmwlan/phone/CertApplyInfo;->mobilePhone:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getRandNum()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 53
a=0;//     iget-object v0, p0, Lcom/ccit/mmwlan/phone/CertApplyInfo;->randNum:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getResult()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 13
a=0;//     iget-object v0, p0, Lcom/ccit/mmwlan/phone/CertApplyInfo;->result:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public setCert(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "cert"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 33
a=0;//     iput-object p1, p0, Lcom/ccit/mmwlan/phone/CertApplyInfo;->cert:Ljava/lang/String;
a=0;// 
a=0;//     .line 34
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setEncKey(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "encKey"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 49
a=0;//     iput-object p1, p0, Lcom/ccit/mmwlan/phone/CertApplyInfo;->encKey:Ljava/lang/String;
a=0;// 
a=0;//     .line 50
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setErrormsg(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "errormsg"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 25
a=0;//     iput-object p1, p0, Lcom/ccit/mmwlan/phone/CertApplyInfo;->errormsg:Ljava/lang/String;
a=0;// 
a=0;//     .line 26
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setMobilePhone(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "mobilePhone"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 41
a=0;//     iput-object p1, p0, Lcom/ccit/mmwlan/phone/CertApplyInfo;->mobilePhone:Ljava/lang/String;
a=0;// 
a=0;//     .line 42
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setRandNum(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "randNum"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 57
a=0;//     iput-object p1, p0, Lcom/ccit/mmwlan/phone/CertApplyInfo;->randNum:Ljava/lang/String;
a=0;// 
a=0;//     .line 58
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setResult(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "result"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 17
a=0;//     iput-object p1, p0, Lcom/ccit/mmwlan/phone/CertApplyInfo;->result:Ljava/lang/String;
a=0;// 
a=0;//     .line 18
a=0;//     return-void
a=0;// .end method
}}
