package com.tencent.stat; class StatAppMonitor { void a() { int a;
a=0;// .class public Lcom/tencent/stat/StatAppMonitor;
a=0;// .super Ljava/lang/Object;
a=0;// 
a=0;// # interfaces
a=0;// .implements Ljava/lang/Cloneable;
a=0;// 
a=0;// 
a=0;// # static fields
a=0;// .field public static final FAILURE_RESULT_TYPE:I = 0x1
a=0;// 
a=0;// .field public static final LOGIC_FAILURE_RESULT_TYPE:I = 0x2
a=0;// 
a=0;// .field public static final SUCCESS_RESULT_TYPE:I
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field private a:Ljava/lang/String;
a=0;// 
a=0;// .field private b:J
a=0;// 
a=0;// .field private c:J
a=0;// 
a=0;// .field private d:I
a=0;// 
a=0;// .field private e:J
a=0;// 
a=0;// .field private f:I
a=0;// 
a=0;// .field private g:I
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>(Ljava/lang/String;)V
a=0;//     .locals 4
a=0;// 
a=0;//     const/4 v3, 0x0
a=0;// 
a=0;//     #v3=(Null);
a=0;//     const-wide/16 v1, 0x0
a=0;// 
a=0;//     #v1=(LongLo);v2=(LongHi);
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcom/tencent/stat/StatAppMonitor;);
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     iput-object v0, p0, Lcom/tencent/stat/StatAppMonitor;->a:Ljava/lang/String;
a=0;// 
a=0;//     iput-wide v1, p0, Lcom/tencent/stat/StatAppMonitor;->b:J
a=0;// 
a=0;//     iput-wide v1, p0, Lcom/tencent/stat/StatAppMonitor;->c:J
a=0;// 
a=0;//     iput v3, p0, Lcom/tencent/stat/StatAppMonitor;->d:I
a=0;// 
a=0;//     iput-wide v1, p0, Lcom/tencent/stat/StatAppMonitor;->e:J
a=0;// 
a=0;//     iput v3, p0, Lcom/tencent/stat/StatAppMonitor;->f:I
a=0;// 
a=0;//     const/4 v0, 0x1
a=0;// 
a=0;//     #v0=(One);
a=0;//     iput v0, p0, Lcom/tencent/stat/StatAppMonitor;->g:I
a=0;// 
a=0;//     iput-object p1, p0, Lcom/tencent/stat/StatAppMonitor;->a:Ljava/lang/String;
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public constructor <init>(Ljava/lang/String;IIJJJI)V
a=0;//     .locals 4
a=0;// 
a=0;//     const/4 v3, 0x0
a=0;// 
a=0;//     #v3=(Null);
a=0;//     const-wide/16 v1, 0x0
a=0;// 
a=0;//     #v1=(LongLo);v2=(LongHi);
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcom/tencent/stat/StatAppMonitor;);
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     iput-object v0, p0, Lcom/tencent/stat/StatAppMonitor;->a:Ljava/lang/String;
a=0;// 
a=0;//     iput-wide v1, p0, Lcom/tencent/stat/StatAppMonitor;->b:J
a=0;// 
a=0;//     iput-wide v1, p0, Lcom/tencent/stat/StatAppMonitor;->c:J
a=0;// 
a=0;//     iput v3, p0, Lcom/tencent/stat/StatAppMonitor;->d:I
a=0;// 
a=0;//     iput-wide v1, p0, Lcom/tencent/stat/StatAppMonitor;->e:J
a=0;// 
a=0;//     iput v3, p0, Lcom/tencent/stat/StatAppMonitor;->f:I
a=0;// 
a=0;//     const/4 v0, 0x1
a=0;// 
a=0;//     #v0=(One);
a=0;//     iput v0, p0, Lcom/tencent/stat/StatAppMonitor;->g:I
a=0;// 
a=0;//     iput-object p1, p0, Lcom/tencent/stat/StatAppMonitor;->a:Ljava/lang/String;
a=0;// 
a=0;//     iput-wide p4, p0, Lcom/tencent/stat/StatAppMonitor;->b:J
a=0;// 
a=0;//     iput-wide p6, p0, Lcom/tencent/stat/StatAppMonitor;->c:J
a=0;// 
a=0;//     iput p2, p0, Lcom/tencent/stat/StatAppMonitor;->d:I
a=0;// 
a=0;//     iput-wide p8, p0, Lcom/tencent/stat/StatAppMonitor;->e:J
a=0;// 
a=0;//     iput p3, p0, Lcom/tencent/stat/StatAppMonitor;->f:I
a=0;// 
a=0;//     iput p10, p0, Lcom/tencent/stat/StatAppMonitor;->g:I
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public clone()Lcom/tencent/stat/StatAppMonitor;
a=0;//     .locals 1
a=0;// 
a=0;//     :try_start_0
a=0;//     invoke-super {p0}, Ljava/lang/Object;->clone()Ljava/lang/Object;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/Object;);
a=0;//     check-cast v0, Lcom/tencent/stat/StatAppMonitor;
a=0;//     :try_end_0
a=0;//     .catch Ljava/lang/CloneNotSupportedException; {:try_start_0 .. :try_end_0} :catch_0
a=0;// 
a=0;//     :goto_0
a=0;//     return-object v0
a=0;// 
a=0;//     :catch_0
a=0;//     move-exception v0
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/CloneNotSupportedException;);
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     goto :goto_0
a=0;// .end method
a=0;// 
a=0;// .method public bridge synthetic clone()Ljava/lang/Object;
a=0;//     .locals 1
a=0;// 
a=0;//     invoke-virtual {p0}, Lcom/tencent/stat/StatAppMonitor;->clone()Lcom/tencent/stat/StatAppMonitor;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Lcom/tencent/stat/StatAppMonitor;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getInterfaceName()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     iget-object v0, p0, Lcom/tencent/stat/StatAppMonitor;->a:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getMillisecondsConsume()J
a=0;//     .locals 2
a=0;// 
a=0;//     iget-wide v0, p0, Lcom/tencent/stat/StatAppMonitor;->e:J
a=0;// 
a=0;//     #v0=(LongLo);v1=(LongHi);
a=0;//     return-wide v0
a=0;// .end method
a=0;// 
a=0;// .method public getReqSize()J
a=0;//     .locals 2
a=0;// 
a=0;//     iget-wide v0, p0, Lcom/tencent/stat/StatAppMonitor;->b:J
a=0;// 
a=0;//     #v0=(LongLo);v1=(LongHi);
a=0;//     return-wide v0
a=0;// .end method
a=0;// 
a=0;// .method public getRespSize()J
a=0;//     .locals 2
a=0;// 
a=0;//     iget-wide v0, p0, Lcom/tencent/stat/StatAppMonitor;->c:J
a=0;// 
a=0;//     #v0=(LongLo);v1=(LongHi);
a=0;//     return-wide v0
a=0;// .end method
a=0;// 
a=0;// .method public getResultType()I
a=0;//     .locals 1
a=0;// 
a=0;//     iget v0, p0, Lcom/tencent/stat/StatAppMonitor;->d:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getReturnCode()I
a=0;//     .locals 1
a=0;// 
a=0;//     iget v0, p0, Lcom/tencent/stat/StatAppMonitor;->f:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getSampling()I
a=0;//     .locals 1
a=0;// 
a=0;//     iget v0, p0, Lcom/tencent/stat/StatAppMonitor;->g:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public setInterfaceName(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-object p1, p0, Lcom/tencent/stat/StatAppMonitor;->a:Ljava/lang/String;
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setMillisecondsConsume(J)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-wide p1, p0, Lcom/tencent/stat/StatAppMonitor;->e:J
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setReqSize(J)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-wide p1, p0, Lcom/tencent/stat/StatAppMonitor;->b:J
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setRespSize(J)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-wide p1, p0, Lcom/tencent/stat/StatAppMonitor;->c:J
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setResultType(I)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput p1, p0, Lcom/tencent/stat/StatAppMonitor;->d:I
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setReturnCode(I)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput p1, p0, Lcom/tencent/stat/StatAppMonitor;->f:I
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setSampling(I)V
a=0;//     .locals 0
a=0;// 
a=0;//     if-gtz p1, :cond_0
a=0;// 
a=0;//     const/4 p1, 0x1
a=0;// 
a=0;//     :cond_0
a=0;//     iput p1, p0, Lcom/tencent/stat/StatAppMonitor;->g:I
a=0;// 
a=0;//     return-void
a=0;// .end method
}}
