package com.twocloo.base.http; class HttpResult { void a() { int a;
a=0;// .class public Lcom/twocloo/base/http/HttpResult;
a=0;// .super Ljava/lang/Object;
a=0;// .source "HttpResult.java"
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field private cookie:Ljava/lang/String;
a=0;// 
a=0;// .field private cookieMap:Ljava/util/Map;
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "Ljava/util/Map",
a=0;//             "<",
a=0;//             "Ljava/lang/String;",
a=0;//             "Ljava/lang/String;",
a=0;//             ">;"
a=0;//         }
a=0;//     .end annotation
a=0;// .end field
a=0;// 
a=0;// .field private headerAll:Ljava/util/HashMap;
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "Ljava/util/HashMap",
a=0;//             "<",
a=0;//             "Ljava/lang/String;",
a=0;//             "Lorg/apache/http/Header;",
a=0;//             ">;"
a=0;//         }
a=0;//     .end annotation
a=0;// .end field
a=0;// 
a=0;// .field private httpEntity:Lorg/apache/http/HttpEntity;
a=0;// 
a=0;// .field private request:Lorg/apache/http/client/methods/HttpUriRequest;
a=0;// 
a=0;// .field private statusCode:I
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 21
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcom/twocloo/base/http/HttpResult;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public getCookie()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 47
a=0;//     iget-object v0, p0, Lcom/twocloo/base/http/HttpResult;->cookie:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getCookieMap()Ljava/util/Map;
a=0;//     .locals 1
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "()",
a=0;//             "Ljava/util/Map",
a=0;//             "<",
a=0;//             "Ljava/lang/String;",
a=0;//             "Ljava/lang/String;",
a=0;//             ">;"
a=0;//         }
a=0;//     .end annotation
a=0;// 
a=0;//     .prologue
a=0;//     .line 39
a=0;//     iget-object v0, p0, Lcom/twocloo/base/http/HttpResult;->cookieMap:Ljava/util/Map;
a=0;// 
a=0;//     #v0=(Reference,Ljava/util/Map;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getHeaders()Ljava/util/HashMap;
a=0;//     .locals 1
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "()",
a=0;//             "Ljava/util/HashMap",
a=0;//             "<",
a=0;//             "Ljava/lang/String;",
a=0;//             "Lorg/apache/http/Header;",
a=0;//             ">;"
a=0;//         }
a=0;//     .end annotation
a=0;// 
a=0;//     .prologue
a=0;//     .line 63
a=0;//     iget-object v0, p0, Lcom/twocloo/base/http/HttpResult;->headerAll:Ljava/util/HashMap;
a=0;// 
a=0;//     #v0=(Reference,Ljava/util/HashMap;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getHttpEntity()Lorg/apache/http/HttpEntity;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 74
a=0;//     iget-object v0, p0, Lcom/twocloo/base/http/HttpResult;->httpEntity:Lorg/apache/http/HttpEntity;
a=0;// 
a=0;//     #v0=(Reference,Lorg/apache/http/HttpEntity;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getRequest()Lorg/apache/http/client/methods/HttpUriRequest;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 31
a=0;//     iget-object v0, p0, Lcom/twocloo/base/http/HttpResult;->request:Lorg/apache/http/client/methods/HttpUriRequest;
a=0;// 
a=0;//     #v0=(Reference,Lorg/apache/http/client/methods/HttpUriRequest;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getStatusCode()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 55
a=0;//     iget v0, p0, Lcom/twocloo/base/http/HttpResult;->statusCode:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public httpEntityContent()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 83
a=0;//     const-string v0, "UTF-8"
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {p0, v0}, Lcom/twocloo/base/http/HttpResult;->httpEntityContent(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public httpEntityContent(Ljava/lang/String;)Ljava/lang/String;
a=0;//     .locals 2
a=0;//     .param p1, "encode"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 89
a=0;//     :try_start_0
a=0;//     iget-object v1, p0, Lcom/twocloo/base/http/HttpResult;->httpEntity:Lorg/apache/http/HttpEntity;
a=0;// 
a=0;//     #v1=(Reference,Lorg/apache/http/HttpEntity;);
a=0;//     invoke-static {v1, p1}, Lorg/apache/http/util/EntityUtils;->toString(Lorg/apache/http/HttpEntity;Ljava/lang/String;)Ljava/lang/String;
a=0;//     :try_end_0
a=0;//     .catch Ljava/lang/Throwable; {:try_start_0 .. :try_end_0} :catch_0
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     .line 94
a=0;//     :goto_0
a=0;//     #v0=(Conflicted);
a=0;//     return-object v1
a=0;// 
a=0;//     .line 90
a=0;//     :catch_0
a=0;//     move-exception v0
a=0;// 
a=0;//     .line 91
a=0;//     .local v0, "e":Ljava/lang/Throwable;
a=0;//     #v0=(Reference,Ljava/lang/Throwable;);
a=0;//     invoke-virtual {v0}, Ljava/lang/Throwable;->getMessage()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-static {v1, v0}, Lcom/twocloo/base/util/LogUtils;->error(Ljava/lang/String;Ljava/lang/Throwable;)V
a=0;// 
a=0;//     .line 94
a=0;//     const/4 v1, 0x0
a=0;// 
a=0;//     #v1=(Null);
a=0;//     goto :goto_0
a=0;// .end method
a=0;// 
a=0;// .method public setCookie(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "cookie"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 51
a=0;//     iput-object p1, p0, Lcom/twocloo/base/http/HttpResult;->cookie:Ljava/lang/String;
a=0;// 
a=0;//     .line 52
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setCookieMap(Ljava/util/Map;)V
a=0;//     .locals 0
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "(",
a=0;//             "Ljava/util/Map",
a=0;//             "<",
a=0;//             "Ljava/lang/String;",
a=0;//             "Ljava/lang/String;",
a=0;//             ">;)V"
a=0;//         }
a=0;//     .end annotation
a=0;// 
a=0;//     .prologue
a=0;//     .line 43
a=0;//     .local p1, "cookieMap":Ljava/util/Map;, "Ljava/util/Map<Ljava/lang/String;Ljava/lang/String;>;"
a=0;//     iput-object p1, p0, Lcom/twocloo/base/http/HttpResult;->cookieMap:Ljava/util/Map;
a=0;// 
a=0;//     .line 44
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setHeaders([Lorg/apache/http/Header;)V
a=0;//     .locals 5
a=0;//     .param p1, "headers"    # [Lorg/apache/http/Header;
a=0;// 
a=0;//     .prologue
a=0;//     .line 67
a=0;//     new-instance v1, Ljava/util/HashMap;
a=0;// 
a=0;//     #v1=(UninitRef,Ljava/util/HashMap;);
a=0;//     invoke-direct {v1}, Ljava/util/HashMap;-><init>()V
a=0;// 
a=0;//     #v1=(Reference,Ljava/util/HashMap;);
a=0;//     iput-object v1, p0, Lcom/twocloo/base/http/HttpResult;->headerAll:Ljava/util/HashMap;
a=0;// 
a=0;//     .line 68
a=0;//     array-length v2, p1
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     const/4 v1, 0x0
a=0;// 
a=0;//     :goto_0
a=0;//     #v0=(Conflicted);v1=(Integer);v3=(Conflicted);v4=(Conflicted);
a=0;//     if-lt v1, v2, :cond_0
a=0;// 
a=0;//     .line 71
a=0;//     return-void
a=0;// 
a=0;//     .line 68
a=0;//     :cond_0
a=0;//     aget-object v0, p1, v1
a=0;// 
a=0;//     .line 69
a=0;//     .local v0, "header":Lorg/apache/http/Header;
a=0;//     #v0=(Null);
a=0;//     iget-object v3, p0, Lcom/twocloo/base/http/HttpResult;->headerAll:Ljava/util/HashMap;
a=0;// 
a=0;//     #v3=(Reference,Ljava/util/HashMap;);
a=0;//     invoke-interface {v0}, Lorg/apache/http/Header;->getName()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     #v4=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v3, v4, v0}, Ljava/util/HashMap;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
a=0;// 
a=0;//     .line 68
a=0;//     add-int/lit8 v1, v1, 0x1
a=0;// 
a=0;//     goto :goto_0
a=0;// .end method
a=0;// 
a=0;// .method public setHttpEntity(Lorg/apache/http/HttpEntity;)V
a=0;//     .locals 0
a=0;//     .param p1, "httpEntity"    # Lorg/apache/http/HttpEntity;
a=0;// 
a=0;//     .prologue
a=0;//     .line 78
a=0;//     iput-object p1, p0, Lcom/twocloo/base/http/HttpResult;->httpEntity:Lorg/apache/http/HttpEntity;
a=0;// 
a=0;//     .line 79
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setRequest(Lorg/apache/http/client/methods/HttpUriRequest;)V
a=0;//     .locals 0
a=0;//     .param p1, "request"    # Lorg/apache/http/client/methods/HttpUriRequest;
a=0;// 
a=0;//     .prologue
a=0;//     .line 35
a=0;//     iput-object p1, p0, Lcom/twocloo/base/http/HttpResult;->request:Lorg/apache/http/client/methods/HttpUriRequest;
a=0;// 
a=0;//     .line 36
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setStatusCode(I)V
a=0;//     .locals 0
a=0;//     .param p1, "statusCode"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 59
a=0;//     iput p1, p0, Lcom/twocloo/base/http/HttpResult;->statusCode:I
a=0;// 
a=0;//     .line 60
a=0;//     return-void
a=0;// .end method
}}
