package com.twocloo.com.cn.utils; class MySharedPreferences { void a() { int a;
a=0;// .class public final Lcom/twocloo/com/cn/utils/MySharedPreferences;
a=0;// .super Ljava/lang/Object;
a=0;// .source "MySharedPreferences.java"
a=0;// 
a=0;// 
a=0;// # static fields
a=0;// .field private static mMySharedPreferences:Lcom/twocloo/com/cn/utils/MySharedPreferences;
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field private context:Landroid/content/Context;
a=0;// 
a=0;// .field private isSaveLog:Z
a=0;// 
a=0;// .field private mSharedPreferences:Landroid/content/SharedPreferences;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method static constructor <clinit>()V
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 14
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     sput-object v0, Lcom/twocloo/com/cn/utils/MySharedPreferences;->mMySharedPreferences:Lcom/twocloo/com/cn/utils/MySharedPreferences;
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method private constructor <init>(Landroid/content/Context;)V
a=0;//     .locals 2
a=0;//     .param p1, "context"    # Landroid/content/Context;
a=0;// 
a=0;//     .prologue
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     const/4 v1, 0x0
a=0;// 
a=0;//     .line 18
a=0;//     #v1=(Null);
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     .line 12
a=0;//     #p0=(Reference,Lcom/twocloo/com/cn/utils/MySharedPreferences;);
a=0;//     iput-object v0, p0, Lcom/twocloo/com/cn/utils/MySharedPreferences;->context:Landroid/content/Context;
a=0;// 
a=0;//     .line 13
a=0;//     iput-object v0, p0, Lcom/twocloo/com/cn/utils/MySharedPreferences;->mSharedPreferences:Landroid/content/SharedPreferences;
a=0;// 
a=0;//     .line 15
a=0;//     iput-boolean v1, p0, Lcom/twocloo/com/cn/utils/MySharedPreferences;->isSaveLog:Z
a=0;// 
a=0;//     .line 19
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/utils/MySharedPreferences;->context:Landroid/content/Context;
a=0;// 
a=0;//     .line 21
a=0;//     invoke-virtual {p1}, Landroid/content/Context;->getPackageName()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 20
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {p1, v0, v1}, Landroid/content/Context;->getSharedPreferences(Ljava/lang/String;I)Landroid/content/SharedPreferences;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, p0, Lcom/twocloo/com/cn/utils/MySharedPreferences;->mSharedPreferences:Landroid/content/SharedPreferences;
a=0;// 
a=0;//     .line 22
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static getMySharedPreferences(Landroid/content/Context;)Lcom/twocloo/com/cn/utils/MySharedPreferences;
a=0;//     .locals 1
a=0;//     .param p0, "context"    # Landroid/content/Context;
a=0;// 
a=0;//     .prologue
a=0;//     .line 25
a=0;//     sget-object v0, Lcom/twocloo/com/cn/utils/MySharedPreferences;->mMySharedPreferences:Lcom/twocloo/com/cn/utils/MySharedPreferences;
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/utils/MySharedPreferences;);
a=0;//     if-nez v0, :cond_0
a=0;// 
a=0;//     .line 26
a=0;//     new-instance v0, Lcom/twocloo/com/cn/utils/MySharedPreferences;
a=0;// 
a=0;//     #v0=(UninitRef,Lcom/twocloo/com/cn/utils/MySharedPreferences;);
a=0;//     invoke-direct {v0, p0}, Lcom/twocloo/com/cn/utils/MySharedPreferences;-><init>(Landroid/content/Context;)V
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/utils/MySharedPreferences;);
a=0;//     sput-object v0, Lcom/twocloo/com/cn/utils/MySharedPreferences;->mMySharedPreferences:Lcom/twocloo/com/cn/utils/MySharedPreferences;
a=0;// 
a=0;//     .line 28
a=0;//     :cond_0
a=0;//     sget-object v0, Lcom/twocloo/com/cn/utils/MySharedPreferences;->mMySharedPreferences:Lcom/twocloo/com/cn/utils/MySharedPreferences;
a=0;// 
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public deleteAll()V
a=0;//     .locals 6
a=0;// 
a=0;//     .prologue
a=0;//     .line 54
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/utils/MySharedPreferences;->mSharedPreferences:Landroid/content/SharedPreferences;
a=0;// 
a=0;//     #v3=(Reference,Landroid/content/SharedPreferences;);
a=0;//     invoke-interface {v3}, Landroid/content/SharedPreferences;->getAll()Ljava/util/Map;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 55
a=0;//     .local v0, "map":Ljava/util/Map;, "Ljava/util/Map<Ljava/lang/String;*>;"
a=0;//     #v0=(Reference,Ljava/util/Map;);
a=0;//     invoke-interface {v0}, Ljava/util/Map;->keySet()Ljava/util/Set;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     .line 57
a=0;//     .local v1, "set":Ljava/util/Set;, "Ljava/util/Set<Ljava/lang/String;>;"
a=0;//     #v1=(Reference,Ljava/util/Set;);
a=0;//     invoke-interface {v1}, Ljava/util/Set;->iterator()Ljava/util/Iterator;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     :goto_0
a=0;//     #v2=(Conflicted);v4=(Conflicted);v5=(Conflicted);
a=0;//     invoke-interface {v3}, Ljava/util/Iterator;->hasNext()Z
a=0;// 
a=0;//     move-result v4
a=0;// 
a=0;//     #v4=(Boolean);
a=0;//     if-nez v4, :cond_0
a=0;// 
a=0;//     .line 61
a=0;//     return-void
a=0;// 
a=0;//     .line 57
a=0;//     :cond_0
a=0;//     invoke-interface {v3}, Ljava/util/Iterator;->next()Ljava/lang/Object;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     #v2=(Reference,Ljava/lang/Object;);
a=0;//     check-cast v2, Ljava/lang/String;
a=0;// 
a=0;//     .line 58
a=0;//     .local v2, "string":Ljava/lang/String;
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/utils/MySharedPreferences;->mSharedPreferences:Landroid/content/SharedPreferences;
a=0;// 
a=0;//     #v4=(Reference,Landroid/content/SharedPreferences;);
a=0;//     invoke-interface {v4}, Landroid/content/SharedPreferences;->edit()Landroid/content/SharedPreferences$Editor;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     const-string v5, ""
a=0;// 
a=0;//     #v5=(Reference,Ljava/lang/String;);
a=0;//     invoke-interface {v4, v2, v5}, Landroid/content/SharedPreferences$Editor;->putString(Ljava/lang/String;Ljava/lang/String;)Landroid/content/SharedPreferences$Editor;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-interface {v4}, Landroid/content/SharedPreferences$Editor;->commit()Z
a=0;// 
a=0;//     goto :goto_0
a=0;// .end method
a=0;// 
a=0;// .method public deleteValue(Ljava/lang/String;)V
a=0;//     .locals 1
a=0;//     .param p1, "name"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 50
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/utils/MySharedPreferences;->mSharedPreferences:Landroid/content/SharedPreferences;
a=0;// 
a=0;//     #v0=(Reference,Landroid/content/SharedPreferences;);
a=0;//     invoke-interface {v0}, Landroid/content/SharedPreferences;->edit()Landroid/content/SharedPreferences$Editor;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-interface {v0, p1}, Landroid/content/SharedPreferences$Editor;->remove(Ljava/lang/String;)Landroid/content/SharedPreferences$Editor;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-interface {v0}, Landroid/content/SharedPreferences$Editor;->commit()Z
a=0;// 
a=0;//     .line 51
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public getContext()Landroid/content/Context;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 32
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/utils/MySharedPreferences;->context:Landroid/content/Context;
a=0;// 
a=0;//     #v0=(Reference,Landroid/content/Context;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getValue(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
a=0;//     .locals 2
a=0;//     .param p1, "name"    # Ljava/lang/String;
a=0;//     .param p2, "defValue"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 40
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/utils/MySharedPreferences;->mSharedPreferences:Landroid/content/SharedPreferences;
a=0;// 
a=0;//     #v1=(Reference,Landroid/content/SharedPreferences;);
a=0;//     invoke-interface {v1, p1, p2}, Landroid/content/SharedPreferences;->getString(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 41
a=0;//     .local v0, "value":Ljava/lang/String;
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public saveLog(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
a=0;//     .locals 1
a=0;//     .param p1, "name"    # Ljava/lang/String;
a=0;//     .param p2, "value"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 65
a=0;//     iget-boolean v0, p0, Lcom/twocloo/com/cn/utils/MySharedPreferences;->isSaveLog:Z
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     if-eqz v0, :cond_0
a=0;// 
a=0;//     .line 66
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/utils/MySharedPreferences;->mSharedPreferences:Landroid/content/SharedPreferences;
a=0;// 
a=0;//     #v0=(Reference,Landroid/content/SharedPreferences;);
a=0;//     invoke-interface {v0}, Landroid/content/SharedPreferences;->edit()Landroid/content/SharedPreferences$Editor;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-interface {v0, p1, p2}, Landroid/content/SharedPreferences$Editor;->putString(Ljava/lang/String;Ljava/lang/String;)Landroid/content/SharedPreferences$Editor;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-interface {v0}, Landroid/content/SharedPreferences$Editor;->commit()Z
a=0;// 
a=0;//     .line 68
a=0;//     :cond_0
a=0;//     #v0=(Conflicted);
a=0;//     return-object p2
a=0;// .end method
a=0;// 
a=0;// .method public setContext(Landroid/content/Context;)V
a=0;//     .locals 0
a=0;//     .param p1, "context"    # Landroid/content/Context;
a=0;// 
a=0;//     .prologue
a=0;//     .line 36
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/utils/MySharedPreferences;->context:Landroid/content/Context;
a=0;// 
a=0;//     .line 37
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setValue(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
a=0;//     .locals 1
a=0;//     .param p1, "name"    # Ljava/lang/String;
a=0;//     .param p2, "value"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 45
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/utils/MySharedPreferences;->mSharedPreferences:Landroid/content/SharedPreferences;
a=0;// 
a=0;//     #v0=(Reference,Landroid/content/SharedPreferences;);
a=0;//     invoke-interface {v0}, Landroid/content/SharedPreferences;->edit()Landroid/content/SharedPreferences$Editor;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-interface {v0, p1, p2}, Landroid/content/SharedPreferences$Editor;->putString(Ljava/lang/String;Ljava/lang/String;)Landroid/content/SharedPreferences$Editor;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-interface {v0}, Landroid/content/SharedPreferences$Editor;->commit()Z
a=0;// 
a=0;//     .line 46
a=0;//     return-object p2
a=0;// .end method
}}
