package com.slidingmenu.lib.app; class SlidingActivityBase { void a() { int a;
a=0;// .class public interface abstract Lcom/slidingmenu/lib/app/SlidingActivityBase;
a=0;// .super Ljava/lang/Object;
a=0;// .source "SlidingActivityBase.java"
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public abstract getSlidingMenu()Lcom/slidingmenu/lib/SlidingMenu;
a=0;// .end method
a=0;// 
a=0;// .method public abstract setBehindContentView(I)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setBehindContentView(Landroid/view/View;)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setBehindContentView(Landroid/view/View;Landroid/view/ViewGroup$LayoutParams;)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setSlidingActionBarEnabled(Z)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract showContent()V
a=0;// .end method
a=0;// 
a=0;// .method public abstract showMenu()V
a=0;// .end method
a=0;// 
a=0;// .method public abstract showSecondaryMenu()V
a=0;// .end method
a=0;// 
a=0;// .method public abstract toggle()V
a=0;// .end method
}}
