package safiap.framework.sdk; class SAFFramework$3 { void a() { int a;
a=0;// .class Lsafiap/framework/sdk/SAFFramework$3;
a=0;// .super Lsafiap/framework/sdk/ISAFFrameworkCallback$Stub;
a=0;// .source "SourceFile"
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field private synthetic a:Lsafiap/framework/sdk/SAFFramework;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>(Lsafiap/framework/sdk/SAFFramework;)V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 155
a=0;//     iput-object p1, p0, Lsafiap/framework/sdk/SAFFramework$3;->a:Lsafiap/framework/sdk/SAFFramework;
a=0;// 
a=0;//     invoke-direct {p0}, Lsafiap/framework/sdk/ISAFFrameworkCallback$Stub;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lsafiap/framework/sdk/SAFFramework$3;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public onDownloadProgress(Ljava/lang/String;II)V
a=0;//     .locals 1
a=0;//     .annotation system Ldalvik/annotation/Throws;
a=0;//         value = {
a=0;//             Landroid/os/RemoteException;
a=0;//         }
a=0;//     .end annotation
a=0;// 
a=0;//     .prologue
a=0;//     .line 168
a=0;//     iget-object v0, p0, Lsafiap/framework/sdk/SAFFramework$3;->a:Lsafiap/framework/sdk/SAFFramework;
a=0;// 
a=0;//     #v0=(Reference,Lsafiap/framework/sdk/SAFFramework;);
a=0;//     invoke-static {v0}, Lsafiap/framework/sdk/SAFFramework;->c(Lsafiap/framework/sdk/SAFFramework;)Lsafiap/framework/sdk/PluginInstallListener;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     if-eqz v0, :cond_0
a=0;// 
a=0;//     .line 169
a=0;//     iget-object v0, p0, Lsafiap/framework/sdk/SAFFramework$3;->a:Lsafiap/framework/sdk/SAFFramework;
a=0;// 
a=0;//     invoke-static {v0}, Lsafiap/framework/sdk/SAFFramework;->c(Lsafiap/framework/sdk/SAFFramework;)Lsafiap/framework/sdk/PluginInstallListener;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-interface {v0, p1, p2, p3}, Lsafiap/framework/sdk/PluginInstallListener;->onDownloadProgress(Ljava/lang/String;II)V
a=0;// 
a=0;//     .line 171
a=0;//     :cond_0
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public onFinishDownload(Ljava/lang/String;I)V
a=0;//     .locals 1
a=0;//     .annotation system Ldalvik/annotation/Throws;
a=0;//         value = {
a=0;//             Landroid/os/RemoteException;
a=0;//         }
a=0;//     .end annotation
a=0;// 
a=0;//     .prologue
a=0;//     .line 160
a=0;//     iget-object v0, p0, Lsafiap/framework/sdk/SAFFramework$3;->a:Lsafiap/framework/sdk/SAFFramework;
a=0;// 
a=0;//     #v0=(Reference,Lsafiap/framework/sdk/SAFFramework;);
a=0;//     invoke-static {v0}, Lsafiap/framework/sdk/SAFFramework;->c(Lsafiap/framework/sdk/SAFFramework;)Lsafiap/framework/sdk/PluginInstallListener;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     if-eqz v0, :cond_0
a=0;// 
a=0;//     .line 161
a=0;//     iget-object v0, p0, Lsafiap/framework/sdk/SAFFramework$3;->a:Lsafiap/framework/sdk/SAFFramework;
a=0;// 
a=0;//     invoke-static {v0}, Lsafiap/framework/sdk/SAFFramework;->c(Lsafiap/framework/sdk/SAFFramework;)Lsafiap/framework/sdk/PluginInstallListener;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-interface {v0, p1, p2}, Lsafiap/framework/sdk/PluginInstallListener;->onFinishDownload(Ljava/lang/String;I)V
a=0;// 
a=0;//     .line 163
a=0;//     :cond_0
a=0;//     return-void
a=0;// .end method
}}
