package cn.dm.android.ui.interaction; class Call4JavaScript$a { void a() { int a;
a=0;// .class Lcn/dm/android/ui/interaction/Call4JavaScript$a;
a=0;// .super Ljava/lang/Object;
a=0;// .source "SourceFile"
a=0;// 
a=0;// # interfaces
a=0;// .implements Lcn/dm/android/listener/c;
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation system Ldalvik/annotation/EnclosingClass;
a=0;//     value = Lcn/dm/android/ui/interaction/Call4JavaScript;
a=0;// .end annotation
a=0;// 
a=0;// .annotation system Ldalvik/annotation/InnerClass;
a=0;//     accessFlags = 0x2
a=0;//     name = "a"
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field final synthetic a:Lcn/dm/android/ui/interaction/Call4JavaScript;
a=0;// 
a=0;// .field private b:Ljava/lang/String;
a=0;// 
a=0;// .field private c:Lcn/dm/android/ui/interaction/Call4JavaScript$b;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>(Lcn/dm/android/ui/interaction/Call4JavaScript;Ljava/lang/String;Lcn/dm/android/ui/interaction/Call4JavaScript$b;)V
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 290
a=0;//     iput-object p1, p0, Lcn/dm/android/ui/interaction/Call4JavaScript$a;->a:Lcn/dm/android/ui/interaction/Call4JavaScript;
a=0;// 
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     .line 288
a=0;//     #p0=(Reference,Lcn/dm/android/ui/interaction/Call4JavaScript$a;);
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     iput-object v0, p0, Lcn/dm/android/ui/interaction/Call4JavaScript$a;->b:Ljava/lang/String;
a=0;// 
a=0;//     .line 291
a=0;//     iput-object p2, p0, Lcn/dm/android/ui/interaction/Call4JavaScript$a;->b:Ljava/lang/String;
a=0;// 
a=0;//     .line 292
a=0;//     iput-object p3, p0, Lcn/dm/android/ui/interaction/Call4JavaScript$a;->c:Lcn/dm/android/ui/interaction/Call4JavaScript$b;
a=0;// 
a=0;//     .line 293
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public a(Lcn/dm/android/model/a;)V
a=0;//     .locals 3
a=0;// 
a=0;//     .prologue
a=0;//     .line 304
a=0;//     iget-object v0, p0, Lcn/dm/android/ui/interaction/Call4JavaScript$a;->a:Lcn/dm/android/ui/interaction/Call4JavaScript;
a=0;// 
a=0;//     #v0=(Reference,Lcn/dm/android/ui/interaction/Call4JavaScript;);
a=0;//     invoke-static {v0}, Lcn/dm/android/ui/interaction/Call4JavaScript;->a(Lcn/dm/android/ui/interaction/Call4JavaScript;)Landroid/content/Context;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     new-instance v1, Ljava/lang/StringBuilder;
a=0;// 
a=0;//     #v1=(UninitRef,Ljava/lang/StringBuilder;);
a=0;//     invoke-direct {v1}, Ljava/lang/StringBuilder;-><init>()V
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/StringBuilder;);
a=0;//     iget-object v2, p0, Lcn/dm/android/ui/interaction/Call4JavaScript$a;->c:Lcn/dm/android/ui/interaction/Call4JavaScript$b;
a=0;// 
a=0;//     #v2=(Reference,Lcn/dm/android/ui/interaction/Call4JavaScript$b;);
a=0;//     invoke-virtual {v2}, Lcn/dm/android/ui/interaction/Call4JavaScript$b;->a()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     const-string v2, "_success"
a=0;// 
a=0;//     invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v1}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-static {v0, v1}, Lcn/dm/android/f/i;->a(Landroid/content/Context;Ljava/lang/String;)V
a=0;// 
a=0;//     .line 305
a=0;//     iget-object v0, p0, Lcn/dm/android/ui/interaction/Call4JavaScript$a;->a:Lcn/dm/android/ui/interaction/Call4JavaScript;
a=0;// 
a=0;//     invoke-static {v0}, Lcn/dm/android/ui/interaction/Call4JavaScript;->c(Lcn/dm/android/ui/interaction/Call4JavaScript;)Lcn/dm/android/g/b;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     new-instance v1, Ljava/lang/StringBuilder;
a=0;// 
a=0;//     #v1=(UninitRef,Ljava/lang/StringBuilder;);
a=0;//     invoke-direct {v1}, Ljava/lang/StringBuilder;-><init>()V
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/StringBuilder;);
a=0;//     iget-object v2, p0, Lcn/dm/android/ui/interaction/Call4JavaScript$a;->b:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     const-string v2, "("
a=0;// 
a=0;//     invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     iget-object v2, p1, Lcn/dm/android/model/a;->b:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     const-string v2, ")"
a=0;// 
a=0;//     invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v1}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Lcn/dm/android/g/b;->b(Ljava/lang/String;)V
a=0;// 
a=0;//     .line 307
a=0;//     iget-object v0, p0, Lcn/dm/android/ui/interaction/Call4JavaScript$a;->c:Lcn/dm/android/ui/interaction/Call4JavaScript$b;
a=0;// 
a=0;//     sget-object v1, Lcn/dm/android/ui/interaction/Call4JavaScript$b;->e:Lcn/dm/android/ui/interaction/Call4JavaScript$b;
a=0;// 
a=0;//     if-ne v0, v1, :cond_0
a=0;// 
a=0;//     .line 308
a=0;//     iget-object v0, p0, Lcn/dm/android/ui/interaction/Call4JavaScript$a;->a:Lcn/dm/android/ui/interaction/Call4JavaScript;
a=0;// 
a=0;//     invoke-static {v0}, Lcn/dm/android/ui/interaction/Call4JavaScript;->a(Lcn/dm/android/ui/interaction/Call4JavaScript;)Landroid/content/Context;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-static {v0}, Lcn/dm/android/a/b;->a(Landroid/content/Context;)Lcn/dm/android/a/b;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p1, Lcn/dm/android/model/a;->b:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Lcn/dm/android/a/b;->a(Ljava/lang/String;)V
a=0;// 
a=0;//     .line 310
a=0;//     :cond_0
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public onError(Lcn/dm/android/model/ErrorInfo;)V
a=0;//     .locals 3
a=0;//     .param p1, "errorInfo"    # Lcn/dm/android/model/ErrorInfo;
a=0;// 
a=0;//     .prologue
a=0;//     .line 297
a=0;//     iget-object v0, p0, Lcn/dm/android/ui/interaction/Call4JavaScript$a;->a:Lcn/dm/android/ui/interaction/Call4JavaScript;
a=0;// 
a=0;//     #v0=(Reference,Lcn/dm/android/ui/interaction/Call4JavaScript;);
a=0;//     invoke-static {v0}, Lcn/dm/android/ui/interaction/Call4JavaScript;->a(Lcn/dm/android/ui/interaction/Call4JavaScript;)Landroid/content/Context;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     new-instance v1, Ljava/lang/StringBuilder;
a=0;// 
a=0;//     #v1=(UninitRef,Ljava/lang/StringBuilder;);
a=0;//     invoke-direct {v1}, Ljava/lang/StringBuilder;-><init>()V
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/StringBuilder;);
a=0;//     iget-object v2, p0, Lcn/dm/android/ui/interaction/Call4JavaScript$a;->c:Lcn/dm/android/ui/interaction/Call4JavaScript$b;
a=0;// 
a=0;//     #v2=(Reference,Lcn/dm/android/ui/interaction/Call4JavaScript$b;);
a=0;//     invoke-virtual {v2}, Lcn/dm/android/ui/interaction/Call4JavaScript$b;->a()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     const-string v2, "_fail"
a=0;// 
a=0;//     invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v1}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-static {v0, v1}, Lcn/dm/android/f/i;->a(Landroid/content/Context;Ljava/lang/String;)V
a=0;// 
a=0;//     .line 298
a=0;//     iget-object v0, p0, Lcn/dm/android/ui/interaction/Call4JavaScript$a;->a:Lcn/dm/android/ui/interaction/Call4JavaScript;
a=0;// 
a=0;//     invoke-static {v0}, Lcn/dm/android/ui/interaction/Call4JavaScript;->b(Lcn/dm/android/ui/interaction/Call4JavaScript;)Lcn/dm/android/f/e;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     new-instance v1, Ljava/lang/StringBuilder;
a=0;// 
a=0;//     #v1=(UninitRef,Ljava/lang/StringBuilder;);
a=0;//     invoke-direct {v1}, Ljava/lang/StringBuilder;-><init>()V
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/StringBuilder;);
a=0;//     const-string v2, "\u51fa\u73b0\u5f02\u5e38-> code:["
a=0;// 
a=0;//     invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {p1}, Lcn/dm/android/model/ErrorInfo;->getCode()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     const-string v2, "] text:["
a=0;// 
a=0;//     invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {p1}, Lcn/dm/android/model/ErrorInfo;->getText()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     const-string v2, "]"
a=0;// 
a=0;//     invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v1}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Lcn/dm/android/f/e;->e(Ljava/lang/String;)V
a=0;// 
a=0;//     .line 300
a=0;//     return-void
a=0;// .end method
}}
