package com.actionbarsherlock.view; class ActionMode { void a() { int a;
a=0;// .class public abstract Lcom/actionbarsherlock/view/ActionMode;
a=0;// .super Ljava/lang/Object;
a=0;// .source "ActionMode.java"
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation system Ldalvik/annotation/MemberClasses;
a=0;//     value = {
a=0;//         Lcom/actionbarsherlock/view/ActionMode$Callback;
a=0;//     }
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field private mTag:Ljava/lang/Object;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 27
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcom/actionbarsherlock/view/ActionMode;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public abstract finish()V
a=0;// .end method
a=0;// 
a=0;// .method public abstract getCustomView()Landroid/view/View;
a=0;// .end method
a=0;// 
a=0;// .method public abstract getMenu()Lcom/actionbarsherlock/view/Menu;
a=0;// .end method
a=0;// 
a=0;// .method public abstract getMenuInflater()Lcom/actionbarsherlock/view/MenuInflater;
a=0;// .end method
a=0;// 
a=0;// .method public abstract getSubtitle()Ljava/lang/CharSequence;
a=0;// .end method
a=0;// 
a=0;// .method public getTag()Ljava/lang/Object;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 55
a=0;//     iget-object v0, p0, Lcom/actionbarsherlock/view/ActionMode;->mTag:Ljava/lang/Object;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/Object;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public abstract getTitle()Ljava/lang/CharSequence;
a=0;// .end method
a=0;// 
a=0;// .method public abstract invalidate()V
a=0;// .end method
a=0;// 
a=0;// .method public isUiFocusable()Z
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 166
a=0;//     const/4 v0, 0x1
a=0;// 
a=0;//     #v0=(One);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public abstract setCustomView(Landroid/view/View;)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setSubtitle(I)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setSubtitle(Ljava/lang/CharSequence;)V
a=0;// .end method
a=0;// 
a=0;// .method public setTag(Ljava/lang/Object;)V
a=0;//     .locals 0
a=0;//     .param p1, "tag"    # Ljava/lang/Object;
a=0;// 
a=0;//     .prologue
a=0;//     .line 41
a=0;//     iput-object p1, p0, Lcom/actionbarsherlock/view/ActionMode;->mTag:Ljava/lang/Object;
a=0;// 
a=0;//     .line 42
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public abstract setTitle(I)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract setTitle(Ljava/lang/CharSequence;)V
a=0;// .end method
}}
