package com.actionbarsherlock.view; class ActionProvider { void a() { int a;
a=0;// .class public abstract Lcom/actionbarsherlock/view/ActionProvider;
a=0;// .super Ljava/lang/Object;
a=0;// .source "ActionProvider.java"
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation system Ldalvik/annotation/MemberClasses;
a=0;//     value = {
a=0;//         Lcom/actionbarsherlock/view/ActionProvider$SubUiVisibilityListener;
a=0;//     }
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field private mSubUiVisibilityListener:Lcom/actionbarsherlock/view/ActionProvider$SubUiVisibilityListener;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>(Landroid/content/Context;)V
a=0;//     .locals 0
a=0;//     .param p1, "context"    # Landroid/content/Context;
a=0;// 
a=0;//     .prologue
a=0;//     .line 69
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     .line 70
a=0;//     #p0=(Reference,Lcom/actionbarsherlock/view/ActionProvider;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public hasSubMenu()Z
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 129
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public abstract onCreateActionView()Landroid/view/View;
a=0;// .end method
a=0;// 
a=0;// .method public onPerformDefaultAction()Z
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 115
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public onPrepareSubMenu(Lcom/actionbarsherlock/view/SubMenu;)V
a=0;//     .locals 0
a=0;//     .param p1, "subMenu"    # Lcom/actionbarsherlock/view/SubMenu;
a=0;// 
a=0;//     .prologue
a=0;//     .line 142
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setSubUiVisibilityListener(Lcom/actionbarsherlock/view/ActionProvider$SubUiVisibilityListener;)V
a=0;//     .locals 0
a=0;//     .param p1, "listener"    # Lcom/actionbarsherlock/view/ActionProvider$SubUiVisibilityListener;
a=0;// 
a=0;//     .prologue
a=0;//     .line 161
a=0;//     iput-object p1, p0, Lcom/actionbarsherlock/view/ActionProvider;->mSubUiVisibilityListener:Lcom/actionbarsherlock/view/ActionProvider$SubUiVisibilityListener;
a=0;// 
a=0;//     .line 162
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public subUiVisibilityChanged(Z)V
a=0;//     .locals 1
a=0;//     .param p1, "isVisible"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 152
a=0;//     iget-object v0, p0, Lcom/actionbarsherlock/view/ActionProvider;->mSubUiVisibilityListener:Lcom/actionbarsherlock/view/ActionProvider$SubUiVisibilityListener;
a=0;// 
a=0;//     #v0=(Reference,Lcom/actionbarsherlock/view/ActionProvider$SubUiVisibilityListener;);
a=0;//     if-eqz v0, :cond_0
a=0;// 
a=0;//     .line 153
a=0;//     iget-object v0, p0, Lcom/actionbarsherlock/view/ActionProvider;->mSubUiVisibilityListener:Lcom/actionbarsherlock/view/ActionProvider$SubUiVisibilityListener;
a=0;// 
a=0;//     invoke-interface {v0, p1}, Lcom/actionbarsherlock/view/ActionProvider$SubUiVisibilityListener;->onSubUiVisibilityChanged(Z)V
a=0;// 
a=0;//     .line 155
a=0;//     :cond_0
a=0;//     return-void
a=0;// .end method
}}
