package com.umeng.analytics.game; class b { void a() { int a;
a=0;// .class public Lcom/umeng/analytics/game/b;
a=0;// .super Ljava/lang/Object;
a=0;// .source "GameState.java"
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation system Ldalvik/annotation/MemberClasses;
a=0;//     value = {
a=0;//         Lcom/umeng/analytics/game/b$a;
a=0;//     }
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field public a:Ljava/lang/String;
a=0;// 
a=0;// .field public b:Ljava/lang/String;
a=0;// 
a=0;// .field private c:Landroid/content/Context;
a=0;// 
a=0;// .field private final d:Ljava/lang/String;
a=0;// 
a=0;// .field private final e:Ljava/lang/String;
a=0;// 
a=0;// .field private final f:Ljava/lang/String;
a=0;// 
a=0;// .field private final g:Ljava/lang/String;
a=0;// 
a=0;// .field private h:Lcom/umeng/analytics/game/b$a;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>(Landroid/content/Context;)V
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 23
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     .line 27
a=0;//     #p0=(Reference,Lcom/umeng/analytics/game/b;);
a=0;//     const-string v0, "um_g_cache"
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     iput-object v0, p0, Lcom/umeng/analytics/game/b;->d:Ljava/lang/String;
a=0;// 
a=0;//     .line 28
a=0;//     const-string v0, "single_level"
a=0;// 
a=0;//     iput-object v0, p0, Lcom/umeng/analytics/game/b;->e:Ljava/lang/String;
a=0;// 
a=0;//     .line 29
a=0;//     const-string v0, "stat_player_level"
a=0;// 
a=0;//     iput-object v0, p0, Lcom/umeng/analytics/game/b;->f:Ljava/lang/String;
a=0;// 
a=0;//     .line 30
a=0;//     const-string v0, "stat_game_level"
a=0;// 
a=0;//     iput-object v0, p0, Lcom/umeng/analytics/game/b;->g:Ljava/lang/String;
a=0;// 
a=0;//     .line 35
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     iput-object v0, p0, Lcom/umeng/analytics/game/b;->h:Lcom/umeng/analytics/game/b$a;
a=0;// 
a=0;//     .line 24
a=0;//     iput-object p1, p0, Lcom/umeng/analytics/game/b;->c:Landroid/content/Context;
a=0;// 
a=0;//     .line 25
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public a(Ljava/lang/String;)Lcom/umeng/analytics/game/b$a;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 38
a=0;//     new-instance v0, Lcom/umeng/analytics/game/b$a;
a=0;// 
a=0;//     #v0=(UninitRef,Lcom/umeng/analytics/game/b$a;);
a=0;//     invoke-direct {v0, p1}, Lcom/umeng/analytics/game/b$a;-><init>(Ljava/lang/String;)V
a=0;// 
a=0;//     #v0=(Reference,Lcom/umeng/analytics/game/b$a;);
a=0;//     iput-object v0, p0, Lcom/umeng/analytics/game/b;->h:Lcom/umeng/analytics/game/b$a;
a=0;// 
a=0;//     .line 39
a=0;//     iget-object v0, p0, Lcom/umeng/analytics/game/b;->h:Lcom/umeng/analytics/game/b$a;
a=0;// 
a=0;//     invoke-virtual {v0}, Lcom/umeng/analytics/game/b$a;->a()V
a=0;// 
a=0;//     .line 41
a=0;//     iget-object v0, p0, Lcom/umeng/analytics/game/b;->h:Lcom/umeng/analytics/game/b$a;
a=0;// 
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public a()V
a=0;//     .locals 3
a=0;// 
a=0;//     .prologue
a=0;//     .line 45
a=0;//     iget-object v0, p0, Lcom/umeng/analytics/game/b;->h:Lcom/umeng/analytics/game/b$a;
a=0;// 
a=0;//     #v0=(Reference,Lcom/umeng/analytics/game/b$a;);
a=0;//     if-eqz v0, :cond_0
a=0;// 
a=0;//     .line 46
a=0;//     iget-object v0, p0, Lcom/umeng/analytics/game/b;->h:Lcom/umeng/analytics/game/b$a;
a=0;// 
a=0;//     invoke-virtual {v0}, Lcom/umeng/analytics/game/b$a;->b()V
a=0;// 
a=0;//     .line 48
a=0;//     iget-object v0, p0, Lcom/umeng/analytics/game/b;->c:Landroid/content/Context;
a=0;// 
a=0;//     const-string v1, "um_g_cache"
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     const/4 v2, 0x0
a=0;// 
a=0;//     #v2=(Null);
a=0;//     invoke-virtual {v0, v1, v2}, Landroid/content/Context;->getSharedPreferences(Ljava/lang/String;I)Landroid/content/SharedPreferences;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-interface {v0}, Landroid/content/SharedPreferences;->edit()Landroid/content/SharedPreferences$Editor;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 49
a=0;//     const-string v1, "single_level"
a=0;// 
a=0;//     iget-object v2, p0, Lcom/umeng/analytics/game/b;->h:Lcom/umeng/analytics/game/b$a;
a=0;// 
a=0;//     #v2=(Reference,Lcom/umeng/analytics/game/b$a;);
a=0;//     invoke-static {v2}, Lu/aly/s;->a(Ljava/io/Serializable;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-interface {v0, v1, v2}, Landroid/content/SharedPreferences$Editor;->putString(Ljava/lang/String;Ljava/lang/String;)Landroid/content/SharedPreferences$Editor;
a=0;// 
a=0;//     .line 50
a=0;//     const-string v1, "stat_player_level"
a=0;// 
a=0;//     iget-object v2, p0, Lcom/umeng/analytics/game/b;->b:Ljava/lang/String;
a=0;// 
a=0;//     invoke-interface {v0, v1, v2}, Landroid/content/SharedPreferences$Editor;->putString(Ljava/lang/String;Ljava/lang/String;)Landroid/content/SharedPreferences$Editor;
a=0;// 
a=0;//     .line 51
a=0;//     const-string v1, "stat_game_level"
a=0;// 
a=0;//     iget-object v2, p0, Lcom/umeng/analytics/game/b;->a:Ljava/lang/String;
a=0;// 
a=0;//     invoke-interface {v0, v1, v2}, Landroid/content/SharedPreferences$Editor;->putString(Ljava/lang/String;Ljava/lang/String;)Landroid/content/SharedPreferences$Editor;
a=0;// 
a=0;//     .line 52
a=0;//     invoke-interface {v0}, Landroid/content/SharedPreferences$Editor;->commit()Z
a=0;// 
a=0;//     .line 54
a=0;//     :cond_0
a=0;//     #v1=(Conflicted);v2=(Conflicted);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public b(Ljava/lang/String;)Lcom/umeng/analytics/game/b$a;
a=0;//     .locals 2
a=0;// 
a=0;//     .prologue
a=0;//     const/4 v1, 0x0
a=0;// 
a=0;//     .line 70
a=0;//     .line 72
a=0;//     #v1=(Null);
a=0;//     iget-object v0, p0, Lcom/umeng/analytics/game/b;->h:Lcom/umeng/analytics/game/b$a;
a=0;// 
a=0;//     #v0=(Reference,Lcom/umeng/analytics/game/b$a;);
a=0;//     if-eqz v0, :cond_0
a=0;// 
a=0;//     .line 73
a=0;//     iget-object v0, p0, Lcom/umeng/analytics/game/b;->h:Lcom/umeng/analytics/game/b$a;
a=0;// 
a=0;//     invoke-virtual {v0}, Lcom/umeng/analytics/game/b$a;->d()V
a=0;// 
a=0;//     .line 74
a=0;//     iget-object v0, p0, Lcom/umeng/analytics/game/b;->h:Lcom/umeng/analytics/game/b$a;
a=0;// 
a=0;//     invoke-virtual {v0, p1}, Lcom/umeng/analytics/game/b$a;->a(Ljava/lang/String;)Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     if-eqz v0, :cond_0
a=0;// 
a=0;//     .line 75
a=0;//     iget-object v0, p0, Lcom/umeng/analytics/game/b;->h:Lcom/umeng/analytics/game/b$a;
a=0;// 
a=0;//     .line 76
a=0;//     #v0=(Reference,Lcom/umeng/analytics/game/b$a;);
a=0;//     iput-object v1, p0, Lcom/umeng/analytics/game/b;->h:Lcom/umeng/analytics/game/b$a;
a=0;// 
a=0;//     .line 80
a=0;//     :goto_0
a=0;//     return-object v0
a=0;// 
a=0;//     :cond_0
a=0;//     #v0=(Conflicted);
a=0;//     move-object v0, v1
a=0;// 
a=0;//     #v0=(Null);
a=0;//     goto :goto_0
a=0;// .end method
a=0;// 
a=0;// .method public b()V
a=0;//     .locals 3
a=0;// 
a=0;//     .prologue
a=0;//     const/4 v2, 0x0
a=0;// 
a=0;//     .line 57
a=0;//     #v2=(Null);
a=0;//     iget-object v0, p0, Lcom/umeng/analytics/game/b;->c:Landroid/content/Context;
a=0;// 
a=0;//     #v0=(Reference,Landroid/content/Context;);
a=0;//     const-string v1, "um_g_cache"
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-static {v0, v1}, Lu/aly/u;->a(Landroid/content/Context;Ljava/lang/String;)Landroid/content/SharedPreferences;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     .line 58
a=0;//     const-string v0, "single_level"
a=0;// 
a=0;//     invoke-interface {v1, v0, v2}, Landroid/content/SharedPreferences;->getString(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 60
a=0;//     if-eqz v0, :cond_0
a=0;// 
a=0;//     .line 61
a=0;//     invoke-static {v0}, Lu/aly/s;->a(Ljava/lang/String;)Ljava/lang/Object;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     check-cast v0, Lcom/umeng/analytics/game/b$a;
a=0;// 
a=0;//     iput-object v0, p0, Lcom/umeng/analytics/game/b;->h:Lcom/umeng/analytics/game/b$a;
a=0;// 
a=0;//     .line 62
a=0;//     iget-object v0, p0, Lcom/umeng/analytics/game/b;->h:Lcom/umeng/analytics/game/b$a;
a=0;// 
a=0;//     if-eqz v0, :cond_0
a=0;// 
a=0;//     iget-object v0, p0, Lcom/umeng/analytics/game/b;->h:Lcom/umeng/analytics/game/b$a;
a=0;// 
a=0;//     invoke-virtual {v0}, Lcom/umeng/analytics/game/b$a;->c()V
a=0;// 
a=0;//     .line 65
a=0;//     :cond_0
a=0;//     iget-object v0, p0, Lcom/umeng/analytics/game/b;->b:Ljava/lang/String;
a=0;// 
a=0;//     if-nez v0, :cond_1
a=0;// 
a=0;//     const-string v0, "stat_player_level"
a=0;// 
a=0;//     invoke-interface {v1, v0, v2}, Landroid/content/SharedPreferences;->getString(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, p0, Lcom/umeng/analytics/game/b;->b:Ljava/lang/String;
a=0;// 
a=0;//     .line 66
a=0;//     :cond_1
a=0;//     iget-object v0, p0, Lcom/umeng/analytics/game/b;->a:Ljava/lang/String;
a=0;// 
a=0;//     if-nez v0, :cond_2
a=0;// 
a=0;//     const-string v0, "stat_game_level"
a=0;// 
a=0;//     invoke-interface {v1, v0, v2}, Landroid/content/SharedPreferences;->getString(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, p0, Lcom/umeng/analytics/game/b;->a:Ljava/lang/String;
a=0;// 
a=0;//     .line 67
a=0;//     :cond_2
a=0;//     return-void
a=0;// .end method
}}
