package com.twocloo.com.cn.activitys; class BaseReadBook$17 { void a() { int a;
a=0;// .class Lcom/twocloo/com/cn/activitys/BaseReadBook$17;
a=0;// .super Ljava/lang/Object;
a=0;// .source "BaseReadBook.java"
a=0;// 
a=0;// # interfaces
a=0;// .implements Landroid/widget/RadioGroup$OnCheckedChangeListener;
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation system Ldalvik/annotation/EnclosingMethod;
a=0;//     value = Lcom/twocloo/com/cn/activitys/BaseReadBook;->setRadioInit()V
a=0;// .end annotation
a=0;// 
a=0;// .annotation system Ldalvik/annotation/InnerClass;
a=0;//     accessFlags = 0x0
a=0;//     name = null
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field final synthetic this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>(Lcom/twocloo/com/cn/activitys/BaseReadBook;)V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 1
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     .line 851
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook$17;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public onCheckedChanged(Landroid/widget/RadioGroup;I)V
a=0;//     .locals 10
a=0;//     .param p1, "group"    # Landroid/widget/RadioGroup;
a=0;//     .param p2, "checkedId"    # I
a=0;// 
a=0;//     .prologue
a=0;//     const/4 v9, 0x0
a=0;// 
a=0;//     #v9=(Null);
a=0;//     const/4 v8, 0x6
a=0;// 
a=0;//     #v8=(PosByte);
a=0;//     const/4 v7, 0x1
a=0;// 
a=0;//     #v7=(One);
a=0;//     const/16 v6, 0x8
a=0;// 
a=0;//     #v6=(PosByte);
a=0;//     const/4 v5, 0x0
a=0;// 
a=0;//     .line 853
a=0;//     #v5=(Null);
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     #v2=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     new-instance v3, Lcom/twocloo/com/cn/common/ReadBookShareListener;
a=0;// 
a=0;//     #v3=(UninitRef,Lcom/twocloo/com/cn/common/ReadBookShareListener;);
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     #v4=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     invoke-direct {v3, v4}, Lcom/twocloo/com/cn/common/ReadBookShareListener;-><init>(Lcom/twocloo/base/openapi/QZoneAble;)V
a=0;// 
a=0;//     #v3=(Reference,Lcom/twocloo/com/cn/common/ReadBookShareListener;);
a=0;//     iput-object v3, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->readBookShareListener:Lcom/twocloo/com/cn/common/ReadBookShareListener;
a=0;// 
a=0;//     .line 854
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->readBookShareListener:Lcom/twocloo/com/cn/common/ReadBookShareListener;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v3, v3, Lcom/twocloo/com/cn/activitys/BaseReadBook;->aid:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v2, v3}, Lcom/twocloo/com/cn/common/ReadBookShareListener;->setAId(Ljava/lang/String;)V
a=0;// 
a=0;//     .line 856
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->settingsBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     invoke-virtual {v2}, Landroid/widget/RadioButton;->getId()I
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     if-ne p2, v2, :cond_3
a=0;// 
a=0;//     .line 857
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     #v2=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->settingsBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     invoke-virtual {v2}, Landroid/widget/RadioButton;->isChecked()Z
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Boolean);
a=0;//     if-eqz v2, :cond_2
a=0;// 
a=0;//     .line 859
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     #v2=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->settingsBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     invoke-virtual {v3}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     sget v4, Lcom/twocloo/com/cn/R$drawable;->menu_read_settings_pressed:I
a=0;// 
a=0;//     #v4=(Integer);
a=0;//     invoke-virtual {v3, v4}, Landroid/content/res/Resources;->getDrawable(I)Landroid/graphics/drawable/Drawable;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-virtual {v2, v5, v3, v5, v5}, Landroid/widget/RadioButton;->setCompoundDrawablesWithIntrinsicBounds(Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;)V
a=0;// 
a=0;//     .line 861
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->dashangBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     invoke-virtual {v3}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     sget v4, Lcom/twocloo/com/cn/R$drawable;->menu_read_dashang_normal:I
a=0;// 
a=0;//     invoke-virtual {v3, v4}, Landroid/content/res/Resources;->getDrawable(I)Landroid/graphics/drawable/Drawable;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-virtual {v2, v5, v3, v5, v5}, Landroid/widget/RadioButton;->setCompoundDrawablesWithIntrinsicBounds(Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;)V
a=0;// 
a=0;//     .line 863
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->moreBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     invoke-virtual {v3}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     sget v4, Lcom/twocloo/com/cn/R$drawable;->menu_read_more_normal:I
a=0;// 
a=0;//     invoke-virtual {v3, v4}, Landroid/content/res/Resources;->getDrawable(I)Landroid/graphics/drawable/Drawable;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-virtual {v2, v5, v3, v5, v5}, Landroid/widget/RadioButton;->setCompoundDrawablesWithIntrinsicBounds(Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;)V
a=0;// 
a=0;//     .line 865
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     invoke-static {v2}, Lcom/twocloo/com/cn/common/LocalStore;->getMrnt(Landroid/content/Context;)I
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     if-ne v2, v7, :cond_1
a=0;// 
a=0;//     .line 866
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     #v2=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->dayOrNightBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     invoke-virtual {v3}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     sget v4, Lcom/twocloo/com/cn/R$drawable;->menu_read_day_normal:I
a=0;// 
a=0;//     invoke-virtual {v3, v4}, Landroid/content/res/Resources;->getDrawable(I)Landroid/graphics/drawable/Drawable;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-virtual {v2, v5, v3, v5, v5}, Landroid/widget/RadioButton;->setCompoundDrawablesWithIntrinsicBounds(Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;)V
a=0;// 
a=0;//     .line 868
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     invoke-virtual {v2}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getPagefactory()Lcom/twocloo/com/cn/view/BookPageFactory;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-virtual {v2, v8}, Lcom/twocloo/com/cn/view/BookPageFactory;->cgbg(I)V
a=0;// 
a=0;//     .line 869
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->mPageWidget:Lcom/twocloo/com/cn/view/PageWidget;
a=0;// 
a=0;//     invoke-virtual {v2, v8}, Lcom/twocloo/com/cn/view/PageWidget;->cgbg(I)V
a=0;// 
a=0;//     .line 878
a=0;//     :goto_0
a=0;//     #v1=(Conflicted);v3=(Conflicted);
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->settingsBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     #v3=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     invoke-virtual {v3}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     sget v4, Lcom/twocloo/com/cn/R$color;->red_text:I
a=0;// 
a=0;//     invoke-virtual {v3, v4}, Landroid/content/res/Resources;->getColor(I)I
a=0;// 
a=0;//     move-result v3
a=0;// 
a=0;//     #v3=(Integer);
a=0;//     invoke-virtual {v2, v3}, Landroid/widget/RadioButton;->setTextColor(I)V
a=0;// 
a=0;//     .line 879
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->dayOrNightBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     #v3=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     invoke-virtual {v3}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     sget v4, Lcom/twocloo/com/cn/R$color;->light_gray_text:I
a=0;// 
a=0;//     invoke-virtual {v3, v4}, Landroid/content/res/Resources;->getColor(I)I
a=0;// 
a=0;//     move-result v3
a=0;// 
a=0;//     #v3=(Integer);
a=0;//     invoke-virtual {v2, v3}, Landroid/widget/RadioButton;->setTextColor(I)V
a=0;// 
a=0;//     .line 880
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->dashangBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     #v3=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     invoke-virtual {v3}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     sget v4, Lcom/twocloo/com/cn/R$color;->light_gray_text:I
a=0;// 
a=0;//     invoke-virtual {v3, v4}, Landroid/content/res/Resources;->getColor(I)I
a=0;// 
a=0;//     move-result v3
a=0;// 
a=0;//     #v3=(Integer);
a=0;//     invoke-virtual {v2, v3}, Landroid/widget/RadioButton;->setTextColor(I)V
a=0;// 
a=0;//     .line 881
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->moreBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     #v3=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     invoke-virtual {v3}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     sget v4, Lcom/twocloo/com/cn/R$color;->light_gray_text:I
a=0;// 
a=0;//     invoke-virtual {v3, v4}, Landroid/content/res/Resources;->getColor(I)I
a=0;// 
a=0;//     move-result v3
a=0;// 
a=0;//     #v3=(Integer);
a=0;//     invoke-virtual {v2, v3}, Landroid/widget/RadioButton;->setTextColor(I)V
a=0;// 
a=0;//     .line 882
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->nowly:Landroid/widget/LinearLayout;
a=0;// 
a=0;//     invoke-virtual {v2, v6}, Landroid/widget/LinearLayout;->setVisibility(I)V
a=0;// 
a=0;//     .line 883
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->dashangLayout:Landroid/widget/LinearLayout;
a=0;// 
a=0;//     invoke-virtual {v2, v6}, Landroid/widget/LinearLayout;->setVisibility(I)V
a=0;// 
a=0;//     .line 884
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->readSettingLayout:Landroid/widget/LinearLayout;
a=0;// 
a=0;//     invoke-virtual {v2, v9}, Landroid/widget/LinearLayout;->setVisibility(I)V
a=0;// 
a=0;//     .line 885
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->readSettingLayout:Landroid/widget/LinearLayout;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     #v3=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     invoke-virtual {v3}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getAnimationin2()Landroid/view/animation/Animation;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-virtual {v2, v3}, Landroid/widget/LinearLayout;->startAnimation(Landroid/view/animation/Animation;)V
a=0;// 
a=0;//     .line 886
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v3, v3, Lcom/twocloo/com/cn/activitys/BaseReadBook;->readSettingLayout:Landroid/widget/LinearLayout;
a=0;// 
a=0;//     iput-object v3, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->nowly:Landroid/widget/LinearLayout;
a=0;// 
a=0;//     .line 887
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     invoke-virtual {v2}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->refresh()V
a=0;// 
a=0;//     .line 1038
a=0;//     :cond_0
a=0;//     :goto_1
a=0;//     #v0=(Conflicted);v2=(Conflicted);v3=(Conflicted);v4=(Conflicted);
a=0;//     return-void
a=0;// 
a=0;//     .line 871
a=0;//     :cond_1
a=0;//     #v0=(Uninit);v1=(Uninit);v2=(Integer);v3=(Reference,Landroid/graphics/drawable/Drawable;);v4=(Integer);
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     #v2=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->dayOrNightBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     .line 872
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     invoke-virtual {v3}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     sget v4, Lcom/twocloo/com/cn/R$drawable;->menu_read_night_normal:I
a=0;// 
a=0;//     invoke-virtual {v3, v4}, Landroid/content/res/Resources;->getDrawable(I)Landroid/graphics/drawable/Drawable;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     .line 871
a=0;//     invoke-virtual {v2, v5, v3, v5, v5}, Landroid/widget/RadioButton;->setCompoundDrawablesWithIntrinsicBounds(Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;)V
a=0;// 
a=0;//     .line 873
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     invoke-virtual {v2}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getPagefactory()Lcom/twocloo/com/cn/view/BookPageFactory;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     invoke-static {v3}, Lcom/twocloo/com/cn/common/LocalStore;->getMrbg(Landroid/content/Context;)I
a=0;// 
a=0;//     move-result v3
a=0;// 
a=0;//     #v3=(Integer);
a=0;//     invoke-virtual {v2, v3}, Lcom/twocloo/com/cn/view/BookPageFactory;->cgbg(I)V
a=0;// 
a=0;//     .line 874
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->mPageWidget:Lcom/twocloo/com/cn/view/PageWidget;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     #v3=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     invoke-static {v3}, Lcom/twocloo/com/cn/common/LocalStore;->getMrbg(Landroid/content/Context;)I
a=0;// 
a=0;//     move-result v3
a=0;// 
a=0;//     #v3=(Integer);
a=0;//     invoke-virtual {v2, v3}, Lcom/twocloo/com/cn/view/PageWidget;->cgbg(I)V
a=0;// 
a=0;//     .line 875
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->rdbgRG:Landroid/widget/RadioGroup;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     #v3=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     invoke-static {v3}, Lcom/twocloo/com/cn/common/LocalStore;->getMrbg(Landroid/content/Context;)I
a=0;// 
a=0;//     move-result v3
a=0;// 
a=0;//     #v3=(Integer);
a=0;//     invoke-virtual {v2, v3}, Landroid/widget/RadioGroup;->getChildAt(I)Landroid/view/View;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     #v1=(Reference,Landroid/view/View;);
a=0;//     check-cast v1, Landroid/widget/RadioButton;
a=0;// 
a=0;//     .line 876
a=0;//     .local v1, "childAt":Landroid/widget/RadioButton;
a=0;//     invoke-virtual {v1, v7}, Landroid/widget/RadioButton;->setChecked(Z)V
a=0;// 
a=0;//     goto/16 :goto_0
a=0;// 
a=0;//     .line 889
a=0;//     .end local v1    # "childAt":Landroid/widget/RadioButton;
a=0;//     :cond_2
a=0;//     #v1=(Uninit);v2=(Boolean);v3=(Reference,Ljava/lang/String;);v4=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     #v2=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->settingsBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     invoke-virtual {v3}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     sget v4, Lcom/twocloo/com/cn/R$drawable;->menu_read_settings_normal:I
a=0;// 
a=0;//     #v4=(Integer);
a=0;//     invoke-virtual {v3, v4}, Landroid/content/res/Resources;->getDrawable(I)Landroid/graphics/drawable/Drawable;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-virtual {v2, v5, v3, v5, v5}, Landroid/widget/RadioButton;->setCompoundDrawablesWithIntrinsicBounds(Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;)V
a=0;// 
a=0;//     goto :goto_1
a=0;// 
a=0;//     .line 893
a=0;//     :cond_3
a=0;//     #v2=(Integer);v4=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     #v2=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->dayOrNightBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     invoke-virtual {v2}, Landroid/widget/RadioButton;->getId()I
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     if-ne p2, v2, :cond_5
a=0;// 
a=0;//     .line 895
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     #v2=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     invoke-virtual {v2}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     sget v3, Lcom/twocloo/com/cn/R$string;->read_night:I
a=0;// 
a=0;//     #v3=(Integer);
a=0;//     invoke-virtual {v2, v3}, Landroid/content/res/Resources;->getString(I)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     #v3=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     iget-object v3, v3, Lcom/twocloo/com/cn/activitys/BaseReadBook;->dayOrNightBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     invoke-virtual {v3}, Landroid/widget/RadioButton;->getText()Ljava/lang/CharSequence;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-interface {v3}, Ljava/lang/CharSequence;->toString()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-virtual {v2, v3}, Ljava/lang/String;->equals(Ljava/lang/Object;)Z
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Boolean);
a=0;//     if-eqz v2, :cond_4
a=0;// 
a=0;//     .line 896
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     #v2=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->dayOrNightBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     invoke-virtual {v3}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     sget v4, Lcom/twocloo/com/cn/R$drawable;->menu_read_day_pressed:I
a=0;// 
a=0;//     #v4=(Integer);
a=0;//     invoke-virtual {v3, v4}, Landroid/content/res/Resources;->getDrawable(I)Landroid/graphics/drawable/Drawable;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-virtual {v2, v5, v3, v5, v5}, Landroid/widget/RadioButton;->setCompoundDrawablesWithIntrinsicBounds(Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;)V
a=0;// 
a=0;//     .line 898
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->settingsBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     invoke-virtual {v3}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     sget v4, Lcom/twocloo/com/cn/R$drawable;->menu_read_settings_normal:I
a=0;// 
a=0;//     invoke-virtual {v3, v4}, Landroid/content/res/Resources;->getDrawable(I)Landroid/graphics/drawable/Drawable;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-virtual {v2, v5, v3, v5, v5}, Landroid/widget/RadioButton;->setCompoundDrawablesWithIntrinsicBounds(Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;)V
a=0;// 
a=0;//     .line 900
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->dashangBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     invoke-virtual {v3}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     sget v4, Lcom/twocloo/com/cn/R$drawable;->menu_read_dashang_normal:I
a=0;// 
a=0;//     invoke-virtual {v3, v4}, Landroid/content/res/Resources;->getDrawable(I)Landroid/graphics/drawable/Drawable;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-virtual {v2, v5, v3, v5, v5}, Landroid/widget/RadioButton;->setCompoundDrawablesWithIntrinsicBounds(Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;)V
a=0;// 
a=0;//     .line 902
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->moreBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     invoke-virtual {v3}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     sget v4, Lcom/twocloo/com/cn/R$drawable;->menu_read_more_normal:I
a=0;// 
a=0;//     invoke-virtual {v3, v4}, Landroid/content/res/Resources;->getDrawable(I)Landroid/graphics/drawable/Drawable;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-virtual {v2, v5, v3, v5, v5}, Landroid/widget/RadioButton;->setCompoundDrawablesWithIntrinsicBounds(Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;)V
a=0;// 
a=0;//     .line 905
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->dayOrNightBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     invoke-virtual {v3}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     sget v4, Lcom/twocloo/com/cn/R$string;->read_day:I
a=0;// 
a=0;//     invoke-virtual {v3, v4}, Landroid/content/res/Resources;->getString(I)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-virtual {v2, v3}, Landroid/widget/RadioButton;->setText(Ljava/lang/CharSequence;)V
a=0;// 
a=0;//     .line 906
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->settingsBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     invoke-virtual {v3}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     sget v4, Lcom/twocloo/com/cn/R$drawable;->menu_button_settings:I
a=0;// 
a=0;//     invoke-virtual {v3, v4}, Landroid/content/res/Resources;->getDrawable(I)Landroid/graphics/drawable/Drawable;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-virtual {v2, v5, v3, v5, v5}, Landroid/widget/RadioButton;->setCompoundDrawablesWithIntrinsicBounds(Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;)V
a=0;// 
a=0;//     .line 908
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->themebackgroudlayout:Landroid/widget/LinearLayout;
a=0;// 
a=0;//     invoke-virtual {v2, v6}, Landroid/widget/LinearLayout;->setVisibility(I)V
a=0;// 
a=0;//     .line 909
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->dayOrNightBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     invoke-virtual {v3}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     sget v4, Lcom/twocloo/com/cn/R$color;->red_text:I
a=0;// 
a=0;//     invoke-virtual {v3, v4}, Landroid/content/res/Resources;->getColor(I)I
a=0;// 
a=0;//     move-result v3
a=0;// 
a=0;//     #v3=(Integer);
a=0;//     invoke-virtual {v2, v3}, Landroid/widget/RadioButton;->setTextColor(I)V
a=0;// 
a=0;//     .line 910
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->settingsBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     #v3=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     invoke-virtual {v3}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     sget v4, Lcom/twocloo/com/cn/R$color;->light_gray_text:I
a=0;// 
a=0;//     invoke-virtual {v3, v4}, Landroid/content/res/Resources;->getColor(I)I
a=0;// 
a=0;//     move-result v3
a=0;// 
a=0;//     #v3=(Integer);
a=0;//     invoke-virtual {v2, v3}, Landroid/widget/RadioButton;->setTextColor(I)V
a=0;// 
a=0;//     .line 911
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->dashangBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     #v3=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     invoke-virtual {v3}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     sget v4, Lcom/twocloo/com/cn/R$color;->light_gray_text:I
a=0;// 
a=0;//     invoke-virtual {v3, v4}, Landroid/content/res/Resources;->getColor(I)I
a=0;// 
a=0;//     move-result v3
a=0;// 
a=0;//     #v3=(Integer);
a=0;//     invoke-virtual {v2, v3}, Landroid/widget/RadioButton;->setTextColor(I)V
a=0;// 
a=0;//     .line 912
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->moreBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     #v3=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     invoke-virtual {v3}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     sget v4, Lcom/twocloo/com/cn/R$color;->light_gray_text:I
a=0;// 
a=0;//     invoke-virtual {v3, v4}, Landroid/content/res/Resources;->getColor(I)I
a=0;// 
a=0;//     move-result v3
a=0;// 
a=0;//     #v3=(Integer);
a=0;//     invoke-virtual {v2, v3}, Landroid/widget/RadioButton;->setTextColor(I)V
a=0;// 
a=0;//     .line 913
a=0;//     invoke-static {v7}, Lcom/twocloo/com/cn/common/ChangeDayOrNight;->SettingStyle(I)V
a=0;// 
a=0;//     .line 914
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     invoke-static {v2, v7}, Lcom/twocloo/com/cn/common/LocalStore;->setMrnt(Landroid/content/Context;I)V
a=0;// 
a=0;//     .line 915
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     invoke-virtual {v2}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getPagefactory()Lcom/twocloo/com/cn/view/BookPageFactory;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-virtual {v2, v8}, Lcom/twocloo/com/cn/view/BookPageFactory;->cgbg(I)V
a=0;// 
a=0;//     .line 916
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->mPageWidget:Lcom/twocloo/com/cn/view/PageWidget;
a=0;// 
a=0;//     invoke-virtual {v2, v8}, Lcom/twocloo/com/cn/view/PageWidget;->cgbg(I)V
a=0;// 
a=0;//     .line 917
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     invoke-virtual {v2}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->refresh()V
a=0;// 
a=0;//     .line 941
a=0;//     :goto_2
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->nowly:Landroid/widget/LinearLayout;
a=0;// 
a=0;//     invoke-virtual {v2, v6}, Landroid/widget/LinearLayout;->setVisibility(I)V
a=0;// 
a=0;//     .line 942
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->readSettingLayout:Landroid/widget/LinearLayout;
a=0;// 
a=0;//     invoke-virtual {v2, v6}, Landroid/widget/LinearLayout;->setVisibility(I)V
a=0;// 
a=0;//     .line 943
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->dashangLayout:Landroid/widget/LinearLayout;
a=0;// 
a=0;//     invoke-virtual {v2, v6}, Landroid/widget/LinearLayout;->setVisibility(I)V
a=0;// 
a=0;//     .line 944
a=0;//     invoke-virtual {p1}, Landroid/widget/RadioGroup;->clearCheck()V
a=0;// 
a=0;//     goto/16 :goto_1
a=0;// 
a=0;//     .line 919
a=0;//     :cond_4
a=0;//     #v2=(Boolean);v3=(Reference,Ljava/lang/String;);v4=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     #v2=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->dayOrNightBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     invoke-virtual {v3}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     sget v4, Lcom/twocloo/com/cn/R$drawable;->menu_read_night_pressed:I
a=0;// 
a=0;//     #v4=(Integer);
a=0;//     invoke-virtual {v3, v4}, Landroid/content/res/Resources;->getDrawable(I)Landroid/graphics/drawable/Drawable;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-virtual {v2, v5, v3, v5, v5}, Landroid/widget/RadioButton;->setCompoundDrawablesWithIntrinsicBounds(Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;)V
a=0;// 
a=0;//     .line 921
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->settingsBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     invoke-virtual {v3}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     sget v4, Lcom/twocloo/com/cn/R$drawable;->menu_read_settings_normal:I
a=0;// 
a=0;//     invoke-virtual {v3, v4}, Landroid/content/res/Resources;->getDrawable(I)Landroid/graphics/drawable/Drawable;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-virtual {v2, v5, v3, v5, v5}, Landroid/widget/RadioButton;->setCompoundDrawablesWithIntrinsicBounds(Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;)V
a=0;// 
a=0;//     .line 923
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->dashangBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     invoke-virtual {v3}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     sget v4, Lcom/twocloo/com/cn/R$drawable;->menu_read_dashang_normal:I
a=0;// 
a=0;//     invoke-virtual {v3, v4}, Landroid/content/res/Resources;->getDrawable(I)Landroid/graphics/drawable/Drawable;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-virtual {v2, v5, v3, v5, v5}, Landroid/widget/RadioButton;->setCompoundDrawablesWithIntrinsicBounds(Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;)V
a=0;// 
a=0;//     .line 925
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->moreBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     invoke-virtual {v3}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     sget v4, Lcom/twocloo/com/cn/R$drawable;->menu_read_more_normal:I
a=0;// 
a=0;//     invoke-virtual {v3, v4}, Landroid/content/res/Resources;->getDrawable(I)Landroid/graphics/drawable/Drawable;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-virtual {v2, v5, v3, v5, v5}, Landroid/widget/RadioButton;->setCompoundDrawablesWithIntrinsicBounds(Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;)V
a=0;// 
a=0;//     .line 928
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->themebackgroudlayout:Landroid/widget/LinearLayout;
a=0;// 
a=0;//     invoke-virtual {v2, v9}, Landroid/widget/LinearLayout;->setVisibility(I)V
a=0;// 
a=0;//     .line 929
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->dayOrNightBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     invoke-virtual {v3}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     sget v4, Lcom/twocloo/com/cn/R$string;->read_night:I
a=0;// 
a=0;//     invoke-virtual {v3, v4}, Landroid/content/res/Resources;->getString(I)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-virtual {v2, v3}, Landroid/widget/RadioButton;->setText(Ljava/lang/CharSequence;)V
a=0;// 
a=0;//     .line 930
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->dayOrNightBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     invoke-virtual {v3}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     sget v4, Lcom/twocloo/com/cn/R$color;->red_text:I
a=0;// 
a=0;//     invoke-virtual {v3, v4}, Landroid/content/res/Resources;->getColor(I)I
a=0;// 
a=0;//     move-result v3
a=0;// 
a=0;//     #v3=(Integer);
a=0;//     invoke-virtual {v2, v3}, Landroid/widget/RadioButton;->setTextColor(I)V
a=0;// 
a=0;//     .line 931
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->settingsBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     #v3=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     invoke-virtual {v3}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     sget v4, Lcom/twocloo/com/cn/R$color;->light_gray_text:I
a=0;// 
a=0;//     invoke-virtual {v3, v4}, Landroid/content/res/Resources;->getColor(I)I
a=0;// 
a=0;//     move-result v3
a=0;// 
a=0;//     #v3=(Integer);
a=0;//     invoke-virtual {v2, v3}, Landroid/widget/RadioButton;->setTextColor(I)V
a=0;// 
a=0;//     .line 932
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->dashangBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     #v3=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     invoke-virtual {v3}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     sget v4, Lcom/twocloo/com/cn/R$color;->light_gray_text:I
a=0;// 
a=0;//     invoke-virtual {v3, v4}, Landroid/content/res/Resources;->getColor(I)I
a=0;// 
a=0;//     move-result v3
a=0;// 
a=0;//     #v3=(Integer);
a=0;//     invoke-virtual {v2, v3}, Landroid/widget/RadioButton;->setTextColor(I)V
a=0;// 
a=0;//     .line 933
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->moreBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     #v3=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     invoke-virtual {v3}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     sget v4, Lcom/twocloo/com/cn/R$color;->light_gray_text:I
a=0;// 
a=0;//     invoke-virtual {v3, v4}, Landroid/content/res/Resources;->getColor(I)I
a=0;// 
a=0;//     move-result v3
a=0;// 
a=0;//     #v3=(Integer);
a=0;//     invoke-virtual {v2, v3}, Landroid/widget/RadioButton;->setTextColor(I)V
a=0;// 
a=0;//     .line 934
a=0;//     invoke-static {v9}, Lcom/twocloo/com/cn/common/ChangeDayOrNight;->SettingStyle(I)V
a=0;// 
a=0;//     .line 935
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     invoke-static {v2, v9}, Lcom/twocloo/com/cn/common/LocalStore;->setMrnt(Landroid/content/Context;I)V
a=0;// 
a=0;//     .line 936
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     invoke-virtual {v2}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getPagefactory()Lcom/twocloo/com/cn/view/BookPageFactory;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     #v3=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     iget v3, v3, Lcom/twocloo/com/cn/activitys/BaseReadBook;->nowbgid:I
a=0;// 
a=0;//     #v3=(Integer);
a=0;//     invoke-virtual {v2, v3}, Lcom/twocloo/com/cn/view/BookPageFactory;->cgbg(I)V
a=0;// 
a=0;//     .line 937
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->mPageWidget:Lcom/twocloo/com/cn/view/PageWidget;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     #v3=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     iget v3, v3, Lcom/twocloo/com/cn/activitys/BaseReadBook;->nowbgid:I
a=0;// 
a=0;//     #v3=(Integer);
a=0;//     invoke-virtual {v2, v3}, Lcom/twocloo/com/cn/view/PageWidget;->cgbg(I)V
a=0;// 
a=0;//     .line 938
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     invoke-virtual {v2}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->refresh()V
a=0;// 
a=0;//     goto/16 :goto_2
a=0;// 
a=0;//     .line 946
a=0;//     :cond_5
a=0;//     #v2=(Integer);v3=(Reference,Ljava/lang/String;);v4=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     #v2=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->dashangBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     invoke-virtual {v2}, Landroid/widget/RadioButton;->getId()I
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     if-ne p2, v2, :cond_8
a=0;// 
a=0;//     .line 947
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     #v2=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->dashangBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     invoke-virtual {v2}, Landroid/widget/RadioButton;->isChecked()Z
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Boolean);
a=0;//     if-eqz v2, :cond_7
a=0;// 
a=0;//     .line 948
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     #v2=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->dashangBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     invoke-virtual {v3}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     sget v4, Lcom/twocloo/com/cn/R$drawable;->menu_read_dashang_pressed:I
a=0;// 
a=0;//     #v4=(Integer);
a=0;//     invoke-virtual {v3, v4}, Landroid/content/res/Resources;->getDrawable(I)Landroid/graphics/drawable/Drawable;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-virtual {v2, v5, v3, v5, v5}, Landroid/widget/RadioButton;->setCompoundDrawablesWithIntrinsicBounds(Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;)V
a=0;// 
a=0;//     .line 951
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->settingsBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     invoke-virtual {v3}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     sget v4, Lcom/twocloo/com/cn/R$drawable;->menu_read_settings_normal:I
a=0;// 
a=0;//     invoke-virtual {v3, v4}, Landroid/content/res/Resources;->getDrawable(I)Landroid/graphics/drawable/Drawable;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-virtual {v2, v5, v3, v5, v5}, Landroid/widget/RadioButton;->setCompoundDrawablesWithIntrinsicBounds(Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;)V
a=0;// 
a=0;//     .line 953
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->moreBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     invoke-virtual {v3}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     sget v4, Lcom/twocloo/com/cn/R$drawable;->menu_read_more_normal:I
a=0;// 
a=0;//     invoke-virtual {v3, v4}, Landroid/content/res/Resources;->getDrawable(I)Landroid/graphics/drawable/Drawable;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-virtual {v2, v5, v3, v5, v5}, Landroid/widget/RadioButton;->setCompoundDrawablesWithIntrinsicBounds(Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;)V
a=0;// 
a=0;//     .line 956
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     invoke-static {v2}, Lcom/twocloo/com/cn/common/LocalStore;->getMrnt(Landroid/content/Context;)I
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     if-ne v2, v7, :cond_6
a=0;// 
a=0;//     .line 957
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     #v2=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->dayOrNightBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     invoke-virtual {v3}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     sget v4, Lcom/twocloo/com/cn/R$drawable;->menu_read_day_normal:I
a=0;// 
a=0;//     invoke-virtual {v3, v4}, Landroid/content/res/Resources;->getDrawable(I)Landroid/graphics/drawable/Drawable;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-virtual {v2, v5, v3, v5, v5}, Landroid/widget/RadioButton;->setCompoundDrawablesWithIntrinsicBounds(Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;)V
a=0;// 
a=0;//     .line 959
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     invoke-virtual {v2}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getPagefactory()Lcom/twocloo/com/cn/view/BookPageFactory;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-virtual {v2, v8}, Lcom/twocloo/com/cn/view/BookPageFactory;->cgbg(I)V
a=0;// 
a=0;//     .line 960
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->mPageWidget:Lcom/twocloo/com/cn/view/PageWidget;
a=0;// 
a=0;//     invoke-virtual {v2, v8}, Lcom/twocloo/com/cn/view/PageWidget;->cgbg(I)V
a=0;// 
a=0;//     .line 970
a=0;//     :goto_3
a=0;//     #v1=(Conflicted);v3=(Conflicted);
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->dashangBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     #v3=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     invoke-virtual {v3}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     sget v4, Lcom/twocloo/com/cn/R$color;->red_text:I
a=0;// 
a=0;//     invoke-virtual {v3, v4}, Landroid/content/res/Resources;->getColor(I)I
a=0;// 
a=0;//     move-result v3
a=0;// 
a=0;//     #v3=(Integer);
a=0;//     invoke-virtual {v2, v3}, Landroid/widget/RadioButton;->setTextColor(I)V
a=0;// 
a=0;//     .line 971
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->dayOrNightBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     #v3=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     invoke-virtual {v3}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     sget v4, Lcom/twocloo/com/cn/R$color;->light_gray_text:I
a=0;// 
a=0;//     invoke-virtual {v3, v4}, Landroid/content/res/Resources;->getColor(I)I
a=0;// 
a=0;//     move-result v3
a=0;// 
a=0;//     #v3=(Integer);
a=0;//     invoke-virtual {v2, v3}, Landroid/widget/RadioButton;->setTextColor(I)V
a=0;// 
a=0;//     .line 972
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->settingsBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     #v3=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     invoke-virtual {v3}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     sget v4, Lcom/twocloo/com/cn/R$color;->light_gray_text:I
a=0;// 
a=0;//     invoke-virtual {v3, v4}, Landroid/content/res/Resources;->getColor(I)I
a=0;// 
a=0;//     move-result v3
a=0;// 
a=0;//     #v3=(Integer);
a=0;//     invoke-virtual {v2, v3}, Landroid/widget/RadioButton;->setTextColor(I)V
a=0;// 
a=0;//     .line 973
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->moreBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     #v3=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     invoke-virtual {v3}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     sget v4, Lcom/twocloo/com/cn/R$color;->light_gray_text:I
a=0;// 
a=0;//     invoke-virtual {v3, v4}, Landroid/content/res/Resources;->getColor(I)I
a=0;// 
a=0;//     move-result v3
a=0;// 
a=0;//     #v3=(Integer);
a=0;//     invoke-virtual {v2, v3}, Landroid/widget/RadioButton;->setTextColor(I)V
a=0;// 
a=0;//     .line 974
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->nowly:Landroid/widget/LinearLayout;
a=0;// 
a=0;//     invoke-virtual {v2, v6}, Landroid/widget/LinearLayout;->setVisibility(I)V
a=0;// 
a=0;//     .line 975
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     #v3=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     iget-object v3, v3, Lcom/twocloo/com/cn/activitys/BaseReadBook;->dashangLayout:Landroid/widget/LinearLayout;
a=0;// 
a=0;//     iput-object v3, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->nowly:Landroid/widget/LinearLayout;
a=0;// 
a=0;//     .line 976
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->readSettingLayout:Landroid/widget/LinearLayout;
a=0;// 
a=0;//     invoke-virtual {v2, v6}, Landroid/widget/LinearLayout;->setVisibility(I)V
a=0;// 
a=0;//     .line 977
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->dashangLayout:Landroid/widget/LinearLayout;
a=0;// 
a=0;//     invoke-virtual {v2, v9}, Landroid/widget/LinearLayout;->setVisibility(I)V
a=0;// 
a=0;//     .line 978
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->dashangLayout:Landroid/widget/LinearLayout;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     invoke-virtual {v3}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getAnimationin2()Landroid/view/animation/Animation;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-virtual {v2, v3}, Landroid/widget/LinearLayout;->startAnimation(Landroid/view/animation/Animation;)V
a=0;// 
a=0;//     .line 979
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     invoke-virtual {v2}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->refresh()V
a=0;// 
a=0;//     goto/16 :goto_1
a=0;// 
a=0;//     .line 962
a=0;//     :cond_6
a=0;//     #v1=(Uninit);v2=(Integer);
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     #v2=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->dayOrNightBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     .line 963
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     invoke-virtual {v3}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     sget v4, Lcom/twocloo/com/cn/R$drawable;->menu_read_night_normal:I
a=0;// 
a=0;//     invoke-virtual {v3, v4}, Landroid/content/res/Resources;->getDrawable(I)Landroid/graphics/drawable/Drawable;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     .line 962
a=0;//     invoke-virtual {v2, v5, v3, v5, v5}, Landroid/widget/RadioButton;->setCompoundDrawablesWithIntrinsicBounds(Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;)V
a=0;// 
a=0;//     .line 964
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     invoke-virtual {v2}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getPagefactory()Lcom/twocloo/com/cn/view/BookPageFactory;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget v3, v3, Lcom/twocloo/com/cn/activitys/BaseReadBook;->nowbgid:I
a=0;// 
a=0;//     #v3=(Integer);
a=0;//     invoke-virtual {v2, v3}, Lcom/twocloo/com/cn/view/BookPageFactory;->cgbg(I)V
a=0;// 
a=0;//     .line 965
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->mPageWidget:Lcom/twocloo/com/cn/view/PageWidget;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     #v3=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     iget v3, v3, Lcom/twocloo/com/cn/activitys/BaseReadBook;->nowbgid:I
a=0;// 
a=0;//     #v3=(Integer);
a=0;//     invoke-virtual {v2, v3}, Lcom/twocloo/com/cn/view/PageWidget;->cgbg(I)V
a=0;// 
a=0;//     .line 966
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->rdbgRG:Landroid/widget/RadioGroup;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     #v3=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     invoke-static {v3}, Lcom/twocloo/com/cn/common/LocalStore;->getMrbg(Landroid/content/Context;)I
a=0;// 
a=0;//     move-result v3
a=0;// 
a=0;//     #v3=(Integer);
a=0;//     invoke-virtual {v2, v3}, Landroid/widget/RadioGroup;->getChildAt(I)Landroid/view/View;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     #v1=(Reference,Landroid/view/View;);
a=0;//     check-cast v1, Landroid/widget/RadioButton;
a=0;// 
a=0;//     .line 967
a=0;//     .restart local v1    # "childAt":Landroid/widget/RadioButton;
a=0;//     invoke-virtual {v1, v7}, Landroid/widget/RadioButton;->setChecked(Z)V
a=0;// 
a=0;//     goto/16 :goto_3
a=0;// 
a=0;//     .line 981
a=0;//     .end local v1    # "childAt":Landroid/widget/RadioButton;
a=0;//     :cond_7
a=0;//     #v1=(Uninit);v2=(Boolean);v3=(Reference,Ljava/lang/String;);v4=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     #v2=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->dashangBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     invoke-virtual {v3}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     sget v4, Lcom/twocloo/com/cn/R$drawable;->menu_read_dashang_normal:I
a=0;// 
a=0;//     #v4=(Integer);
a=0;//     invoke-virtual {v3, v4}, Landroid/content/res/Resources;->getDrawable(I)Landroid/graphics/drawable/Drawable;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-virtual {v2, v5, v3, v5, v5}, Landroid/widget/RadioButton;->setCompoundDrawablesWithIntrinsicBounds(Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;)V
a=0;// 
a=0;//     goto/16 :goto_1
a=0;// 
a=0;//     .line 985
a=0;//     :cond_8
a=0;//     #v2=(Integer);v4=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     #v2=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->moreBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     invoke-virtual {v2}, Landroid/widget/RadioButton;->getId()I
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     if-ne p2, v2, :cond_0
a=0;// 
a=0;//     .line 987
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     #v2=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->moreBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     invoke-virtual {v2}, Landroid/widget/RadioButton;->isChecked()Z
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Boolean);
a=0;//     if-eqz v2, :cond_d
a=0;// 
a=0;//     .line 989
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     #v2=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->user:Lcom/twocloo/com/cn/beans/User;
a=0;// 
a=0;//     if-eqz v2, :cond_9
a=0;// 
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->user:Lcom/twocloo/com/cn/beans/User;
a=0;// 
a=0;//     invoke-virtual {v2}, Lcom/twocloo/com/cn/beans/User;->getUid()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     if-eqz v2, :cond_9
a=0;// 
a=0;//     .line 990
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v3, v3, Lcom/twocloo/com/cn/activitys/BaseReadBook;->user:Lcom/twocloo/com/cn/beans/User;
a=0;// 
a=0;//     invoke-virtual {v3}, Lcom/twocloo/com/cn/beans/User;->getUid()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-static {v2, v3}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->access$3(Lcom/twocloo/com/cn/activitys/BaseReadBook;Ljava/lang/String;)V
a=0;// 
a=0;//     .line 992
a=0;//     :cond_9
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     invoke-static {v3}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->access$4(Lcom/twocloo/com/cn/activitys/BaseReadBook;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v4, v4, Lcom/twocloo/com/cn/activitys/BaseReadBook;->aid:Ljava/lang/String;
a=0;// 
a=0;//     invoke-static {v2, v3, v4}, Lcom/twocloo/com/cn/common/LocalStore;->getAuto(Landroid/content/Context;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 993
a=0;//     .local v0, "auto":Ljava/lang/String;
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     invoke-static {v0}, Landroid/text/TextUtils;->isEmpty(Ljava/lang/CharSequence;)Z
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Boolean);
a=0;//     if-nez v2, :cond_a
a=0;// 
a=0;//     const-string v2, "0"
a=0;// 
a=0;//     #v2=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v2}, Ljava/lang/String;->equals(Ljava/lang/Object;)Z
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Boolean);
a=0;//     if-eqz v2, :cond_b
a=0;// 
a=0;//     .line 994
a=0;//     :cond_a
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     #v2=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->autoOrderImg:Landroid/widget/ImageView;
a=0;// 
a=0;//     sget v3, Lcom/twocloo/com/cn/R$drawable;->auto_order_closed:I
a=0;// 
a=0;//     #v3=(Integer);
a=0;//     invoke-virtual {v2, v3}, Landroid/widget/ImageView;->setImageResource(I)V
a=0;// 
a=0;//     .line 999
a=0;//     :goto_4
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->moreBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     #v3=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     invoke-virtual {v3}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     sget v4, Lcom/twocloo/com/cn/R$drawable;->menu_read_more_pressed:I
a=0;// 
a=0;//     #v4=(Integer);
a=0;//     invoke-virtual {v3, v4}, Landroid/content/res/Resources;->getDrawable(I)Landroid/graphics/drawable/Drawable;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-virtual {v2, v5, v3, v5, v5}, Landroid/widget/RadioButton;->setCompoundDrawablesWithIntrinsicBounds(Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;)V
a=0;// 
a=0;//     .line 1002
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->settingsBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     invoke-virtual {v3}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     sget v4, Lcom/twocloo/com/cn/R$drawable;->menu_read_settings_normal:I
a=0;// 
a=0;//     invoke-virtual {v3, v4}, Landroid/content/res/Resources;->getDrawable(I)Landroid/graphics/drawable/Drawable;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-virtual {v2, v5, v3, v5, v5}, Landroid/widget/RadioButton;->setCompoundDrawablesWithIntrinsicBounds(Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;)V
a=0;// 
a=0;//     .line 1004
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->dashangBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     invoke-virtual {v3}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     sget v4, Lcom/twocloo/com/cn/R$drawable;->menu_read_dashang_normal:I
a=0;// 
a=0;//     invoke-virtual {v3, v4}, Landroid/content/res/Resources;->getDrawable(I)Landroid/graphics/drawable/Drawable;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-virtual {v2, v5, v3, v5, v5}, Landroid/widget/RadioButton;->setCompoundDrawablesWithIntrinsicBounds(Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;)V
a=0;// 
a=0;//     .line 1007
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     invoke-static {v2}, Lcom/twocloo/com/cn/common/LocalStore;->getMrnt(Landroid/content/Context;)I
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     if-ne v2, v7, :cond_c
a=0;// 
a=0;//     .line 1008
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     #v2=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->dayOrNightBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     invoke-virtual {v3}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     sget v4, Lcom/twocloo/com/cn/R$drawable;->menu_read_day_normal:I
a=0;// 
a=0;//     invoke-virtual {v3, v4}, Landroid/content/res/Resources;->getDrawable(I)Landroid/graphics/drawable/Drawable;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-virtual {v2, v5, v3, v5, v5}, Landroid/widget/RadioButton;->setCompoundDrawablesWithIntrinsicBounds(Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;)V
a=0;// 
a=0;//     .line 1010
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     invoke-virtual {v2}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getPagefactory()Lcom/twocloo/com/cn/view/BookPageFactory;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-virtual {v2, v8}, Lcom/twocloo/com/cn/view/BookPageFactory;->cgbg(I)V
a=0;// 
a=0;//     .line 1011
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->mPageWidget:Lcom/twocloo/com/cn/view/PageWidget;
a=0;// 
a=0;//     invoke-virtual {v2, v8}, Lcom/twocloo/com/cn/view/PageWidget;->cgbg(I)V
a=0;// 
a=0;//     .line 1022
a=0;//     :goto_5
a=0;//     #v1=(Conflicted);v3=(Conflicted);
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->moreBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     #v3=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     invoke-virtual {v3}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     sget v4, Lcom/twocloo/com/cn/R$color;->red_text:I
a=0;// 
a=0;//     invoke-virtual {v3, v4}, Landroid/content/res/Resources;->getColor(I)I
a=0;// 
a=0;//     move-result v3
a=0;// 
a=0;//     #v3=(Integer);
a=0;//     invoke-virtual {v2, v3}, Landroid/widget/RadioButton;->setTextColor(I)V
a=0;// 
a=0;//     .line 1023
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->dayOrNightBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     #v3=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     invoke-virtual {v3}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     sget v4, Lcom/twocloo/com/cn/R$color;->light_gray_text:I
a=0;// 
a=0;//     invoke-virtual {v3, v4}, Landroid/content/res/Resources;->getColor(I)I
a=0;// 
a=0;//     move-result v3
a=0;// 
a=0;//     #v3=(Integer);
a=0;//     invoke-virtual {v2, v3}, Landroid/widget/RadioButton;->setTextColor(I)V
a=0;// 
a=0;//     .line 1024
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->settingsBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     #v3=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     invoke-virtual {v3}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     sget v4, Lcom/twocloo/com/cn/R$color;->light_gray_text:I
a=0;// 
a=0;//     invoke-virtual {v3, v4}, Landroid/content/res/Resources;->getColor(I)I
a=0;// 
a=0;//     move-result v3
a=0;// 
a=0;//     #v3=(Integer);
a=0;//     invoke-virtual {v2, v3}, Landroid/widget/RadioButton;->setTextColor(I)V
a=0;// 
a=0;//     .line 1025
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->dashangBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     #v3=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     invoke-virtual {v3}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     sget v4, Lcom/twocloo/com/cn/R$color;->light_gray_text:I
a=0;// 
a=0;//     invoke-virtual {v3, v4}, Landroid/content/res/Resources;->getColor(I)I
a=0;// 
a=0;//     move-result v3
a=0;// 
a=0;//     #v3=(Integer);
a=0;//     invoke-virtual {v2, v3}, Landroid/widget/RadioButton;->setTextColor(I)V
a=0;// 
a=0;//     .line 1026
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->nowly:Landroid/widget/LinearLayout;
a=0;// 
a=0;//     invoke-virtual {v2, v6}, Landroid/widget/LinearLayout;->setVisibility(I)V
a=0;// 
a=0;//     .line 1027
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     #v3=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     iget-object v3, v3, Lcom/twocloo/com/cn/activitys/BaseReadBook;->moreLayout:Landroid/widget/LinearLayout;
a=0;// 
a=0;//     iput-object v3, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->nowly:Landroid/widget/LinearLayout;
a=0;// 
a=0;//     .line 1028
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->readSettingLayout:Landroid/widget/LinearLayout;
a=0;// 
a=0;//     invoke-virtual {v2, v6}, Landroid/widget/LinearLayout;->setVisibility(I)V
a=0;// 
a=0;//     .line 1029
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->dashangLayout:Landroid/widget/LinearLayout;
a=0;// 
a=0;//     invoke-virtual {v2, v6}, Landroid/widget/LinearLayout;->setVisibility(I)V
a=0;// 
a=0;//     .line 1030
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->moreLayout:Landroid/widget/LinearLayout;
a=0;// 
a=0;//     invoke-virtual {v2, v9}, Landroid/widget/LinearLayout;->setVisibility(I)V
a=0;// 
a=0;//     .line 1031
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->moreLayout:Landroid/widget/LinearLayout;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     invoke-virtual {v3}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getAnimationin2()Landroid/view/animation/Animation;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-virtual {v2, v3}, Landroid/widget/LinearLayout;->startAnimation(Landroid/view/animation/Animation;)V
a=0;// 
a=0;//     .line 1032
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     invoke-virtual {v2}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->refresh()V
a=0;// 
a=0;//     goto/16 :goto_1
a=0;// 
a=0;//     .line 996
a=0;//     :cond_b
a=0;//     #v1=(Uninit);v2=(Boolean);v4=(Reference,Ljava/lang/String;);
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     #v2=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->autoOrderImg:Landroid/widget/ImageView;
a=0;// 
a=0;//     sget v3, Lcom/twocloo/com/cn/R$drawable;->auto_order_open:I
a=0;// 
a=0;//     #v3=(Integer);
a=0;//     invoke-virtual {v2, v3}, Landroid/widget/ImageView;->setImageResource(I)V
a=0;// 
a=0;//     goto/16 :goto_4
a=0;// 
a=0;//     .line 1013
a=0;//     :cond_c
a=0;//     #v2=(Integer);v3=(Reference,Landroid/graphics/drawable/Drawable;);v4=(Integer);
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     #v2=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->dayOrNightBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     .line 1014
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     invoke-virtual {v3}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     sget v4, Lcom/twocloo/com/cn/R$drawable;->menu_read_night_normal:I
a=0;// 
a=0;//     invoke-virtual {v3, v4}, Landroid/content/res/Resources;->getDrawable(I)Landroid/graphics/drawable/Drawable;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     .line 1013
a=0;//     invoke-virtual {v2, v5, v3, v5, v5}, Landroid/widget/RadioButton;->setCompoundDrawablesWithIntrinsicBounds(Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;)V
a=0;// 
a=0;//     .line 1015
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     invoke-virtual {v2}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getPagefactory()Lcom/twocloo/com/cn/view/BookPageFactory;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget v3, v3, Lcom/twocloo/com/cn/activitys/BaseReadBook;->nowbgid:I
a=0;// 
a=0;//     #v3=(Integer);
a=0;//     invoke-virtual {v2, v3}, Lcom/twocloo/com/cn/view/BookPageFactory;->cgbg(I)V
a=0;// 
a=0;//     .line 1016
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->mPageWidget:Lcom/twocloo/com/cn/view/PageWidget;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     #v3=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     iget v3, v3, Lcom/twocloo/com/cn/activitys/BaseReadBook;->nowbgid:I
a=0;// 
a=0;//     #v3=(Integer);
a=0;//     invoke-virtual {v2, v3}, Lcom/twocloo/com/cn/view/PageWidget;->cgbg(I)V
a=0;// 
a=0;//     .line 1018
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->rdbgRG:Landroid/widget/RadioGroup;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     #v3=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     invoke-static {v3}, Lcom/twocloo/com/cn/common/LocalStore;->getMrbg(Landroid/content/Context;)I
a=0;// 
a=0;//     move-result v3
a=0;// 
a=0;//     #v3=(Integer);
a=0;//     invoke-virtual {v2, v3}, Landroid/widget/RadioGroup;->getChildAt(I)Landroid/view/View;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     #v1=(Reference,Landroid/view/View;);
a=0;//     check-cast v1, Landroid/widget/RadioButton;
a=0;// 
a=0;//     .line 1019
a=0;//     .restart local v1    # "childAt":Landroid/widget/RadioButton;
a=0;//     invoke-virtual {v1, v7}, Landroid/widget/RadioButton;->setChecked(Z)V
a=0;// 
a=0;//     goto/16 :goto_5
a=0;// 
a=0;//     .line 1034
a=0;//     .end local v0    # "auto":Ljava/lang/String;
a=0;//     .end local v1    # "childAt":Landroid/widget/RadioButton;
a=0;//     :cond_d
a=0;//     #v0=(Uninit);v1=(Uninit);v2=(Boolean);v3=(Reference,Ljava/lang/String;);v4=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     #v2=(Reference,Lcom/twocloo/com/cn/activitys/BaseReadBook;);
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/activitys/BaseReadBook;->moreBtn:Landroid/widget/RadioButton;
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/BaseReadBook$17;->this$0:Lcom/twocloo/com/cn/activitys/BaseReadBook;
a=0;// 
a=0;//     invoke-virtual {v3}, Lcom/twocloo/com/cn/activitys/BaseReadBook;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     sget v4, Lcom/twocloo/com/cn/R$drawable;->menu_read_more_normal:I
a=0;// 
a=0;//     #v4=(Integer);
a=0;//     invoke-virtual {v3, v4}, Landroid/content/res/Resources;->getDrawable(I)Landroid/graphics/drawable/Drawable;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-virtual {v2, v5, v3, v5, v5}, Landroid/widget/RadioButton;->setCompoundDrawablesWithIntrinsicBounds(Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;Landroid/graphics/drawable/Drawable;)V
a=0;// 
a=0;//     goto/16 :goto_1
a=0;// .end method
}}
