package com.twocloo.com.cn.activitys; class EditProfileActivity$1 { void a() { int a;
a=0;// .class Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;
a=0;// .super Landroid/os/Handler;
a=0;// .source "EditProfileActivity.java"
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation system Ldalvik/annotation/EnclosingClass;
a=0;//     value = Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// .end annotation
a=0;// 
a=0;// .annotation system Ldalvik/annotation/InnerClass;
a=0;//     accessFlags = 0x0
a=0;//     name = null
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field final synthetic this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 1
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     .line 97
a=0;//     invoke-direct {p0}, Landroid/os/Handler;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public handleMessage(Landroid/os/Message;)V
a=0;//     .locals 13
a=0;//     .param p1, "msg"    # Landroid/os/Message;
a=0;// 
a=0;//     .prologue
a=0;//     const/4 v12, 0x3
a=0;// 
a=0;//     #v12=(PosByte);
a=0;//     const/4 v11, 0x2
a=0;// 
a=0;//     #v11=(PosByte);
a=0;//     const/4 v10, 0x1
a=0;// 
a=0;//     #v10=(One);
a=0;//     const/16 v9, 0x8
a=0;// 
a=0;//     #v9=(PosByte);
a=0;//     const/4 v8, 0x0
a=0;// 
a=0;//     .line 100
a=0;//     #v8=(Null);
a=0;//     iget v0, p1, Landroid/os/Message;->what:I
a=0;// 
a=0;//     .line 101
a=0;//     .local v0, "code":I
a=0;//     #v0=(Integer);
a=0;//     if-nez v0, :cond_1
a=0;// 
a=0;//     .line 102
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     #v4=(Reference,Lcom/twocloo/com/cn/activitys/EditProfileActivity;);
a=0;//     invoke-virtual {v4}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->getApplicationContext()Landroid/content/Context;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     const-string v5, "\u83b7\u53d6\u7528\u6237\u8d44\u6599\u5931\u8d25"
a=0;// 
a=0;//     #v5=(Reference,Ljava/lang/String;);
a=0;//     invoke-static {v4, v5, v8}, Landroid/widget/Toast;->makeText(Landroid/content/Context;Ljava/lang/CharSequence;I)Landroid/widget/Toast;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-virtual {v4}, Landroid/widget/Toast;->show()V
a=0;// 
a=0;//     .line 181
a=0;//     :cond_0
a=0;//     :goto_0
a=0;//     #v1=(Conflicted);v2=(Conflicted);v3=(Conflicted);v4=(Conflicted);v5=(Conflicted);v6=(Conflicted);v7=(Conflicted);
a=0;//     return-void
a=0;// 
a=0;//     .line 103
a=0;//     :cond_1
a=0;//     #v1=(Uninit);v2=(Uninit);v3=(Uninit);v4=(Uninit);v5=(Uninit);v6=(Uninit);v7=(Uninit);
a=0;//     const/16 v4, 0xa
a=0;// 
a=0;//     #v4=(PosByte);
a=0;//     if-ne v0, v4, :cond_c
a=0;// 
a=0;//     .line 104
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     #v4=(Reference,Lcom/twocloo/com/cn/activitys/EditProfileActivity;);
a=0;//     iget-object v5, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     #v5=(Reference,Lcom/twocloo/com/cn/activitys/EditProfileActivity;);
a=0;//     invoke-static {v5}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$0(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Lcom/twocloo/com/cn/threads/UserInfoNewThread;
a=0;// 
a=0;//     move-result-object v5
a=0;// 
a=0;//     iget-object v5, v5, Lcom/twocloo/com/cn/threads/UserInfoNewThread;->userinfo:Lcom/twocloo/com/cn/beans/UserCenterNewbean;
a=0;// 
a=0;//     invoke-static {v4, v5}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$1(Lcom/twocloo/com/cn/activitys/EditProfileActivity;Lcom/twocloo/com/cn/beans/UserCenterNewbean;)V
a=0;// 
a=0;//     .line 105
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     invoke-static {v4}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$2(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Lcom/twocloo/com/cn/beans/UserCenterNewbean;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     if-nez v4, :cond_2
a=0;// 
a=0;//     .line 106
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     invoke-static {v4}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$3(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Landroid/os/Handler;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-virtual {v4, v8}, Landroid/os/Handler;->sendEmptyMessage(I)Z
a=0;// 
a=0;//     goto :goto_0
a=0;// 
a=0;//     .line 109
a=0;//     :cond_2
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     iget-object v5, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     invoke-static {v5}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$2(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Lcom/twocloo/com/cn/beans/UserCenterNewbean;
a=0;// 
a=0;//     move-result-object v5
a=0;// 
a=0;//     invoke-virtual {v5}, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->getNickname()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v5
a=0;// 
a=0;//     invoke-static {v4, v5}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$4(Lcom/twocloo/com/cn/activitys/EditProfileActivity;Ljava/lang/String;)V
a=0;// 
a=0;//     .line 110
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     invoke-static {v4}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$5(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Landroid/widget/TextView;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     iget-object v5, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     invoke-static {v5}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$6(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v5
a=0;// 
a=0;//     invoke-virtual {v4, v5}, Landroid/widget/TextView;->setText(Ljava/lang/CharSequence;)V
a=0;// 
a=0;//     .line 111
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     iget-object v5, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     invoke-static {v5}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$2(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Lcom/twocloo/com/cn/beans/UserCenterNewbean;
a=0;// 
a=0;//     move-result-object v5
a=0;// 
a=0;//     invoke-virtual {v5}, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->getSign()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v5
a=0;// 
a=0;//     invoke-static {v4, v5}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$7(Lcom/twocloo/com/cn/activitys/EditProfileActivity;Ljava/lang/String;)V
a=0;// 
a=0;//     .line 112
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     invoke-static {v4}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$8(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-virtual {v4}, Ljava/lang/String;->length()I
a=0;// 
a=0;//     move-result v4
a=0;// 
a=0;//     #v4=(Integer);
a=0;//     const/16 v5, 0xa
a=0;// 
a=0;//     #v5=(PosByte);
a=0;//     if-le v4, v5, :cond_7
a=0;// 
a=0;//     .line 113
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     #v4=(Reference,Lcom/twocloo/com/cn/activitys/EditProfileActivity;);
a=0;//     invoke-static {v4}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$9(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Landroid/widget/TextView;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     new-instance v5, Ljava/lang/StringBuilder;
a=0;// 
a=0;//     #v5=(UninitRef,Ljava/lang/StringBuilder;);
a=0;//     iget-object v6, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     #v6=(Reference,Lcom/twocloo/com/cn/activitys/EditProfileActivity;);
a=0;//     invoke-static {v6}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$8(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v6
a=0;// 
a=0;//     const/16 v7, 0xa
a=0;// 
a=0;//     #v7=(PosByte);
a=0;//     invoke-virtual {v6, v8, v7}, Ljava/lang/String;->substring(II)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v6
a=0;// 
a=0;//     invoke-static {v6}, Ljava/lang/String;->valueOf(Ljava/lang/Object;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v6
a=0;// 
a=0;//     invoke-direct {v5, v6}, Ljava/lang/StringBuilder;-><init>(Ljava/lang/String;)V
a=0;// 
a=0;//     #v5=(Reference,Ljava/lang/StringBuilder;);
a=0;//     const-string v6, "..."
a=0;// 
a=0;//     invoke-virtual {v5, v6}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v5
a=0;// 
a=0;//     invoke-virtual {v5}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v5
a=0;// 
a=0;//     invoke-virtual {v4, v5}, Landroid/widget/TextView;->setText(Ljava/lang/CharSequence;)V
a=0;// 
a=0;//     .line 117
a=0;//     :goto_1
a=0;//     #v6=(Conflicted);v7=(Conflicted);
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     invoke-static {v4}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$2(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Lcom/twocloo/com/cn/beans/UserCenterNewbean;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-virtual {v4}, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->getBirth_year()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-static {v4}, Landroid/text/TextUtils;->isEmpty(Ljava/lang/CharSequence;)Z
a=0;// 
a=0;//     move-result v4
a=0;// 
a=0;//     #v4=(Boolean);
a=0;//     if-nez v4, :cond_3
a=0;// 
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     #v4=(Reference,Lcom/twocloo/com/cn/activitys/EditProfileActivity;);
a=0;//     invoke-static {v4}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$2(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Lcom/twocloo/com/cn/beans/UserCenterNewbean;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-virtual {v4}, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->getBirth_month()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-static {v4}, Landroid/text/TextUtils;->isEmpty(Ljava/lang/CharSequence;)Z
a=0;// 
a=0;//     move-result v4
a=0;// 
a=0;//     #v4=(Boolean);
a=0;//     if-nez v4, :cond_3
a=0;// 
a=0;//     .line 118
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     #v4=(Reference,Lcom/twocloo/com/cn/activitys/EditProfileActivity;);
a=0;//     invoke-static {v4}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$2(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Lcom/twocloo/com/cn/beans/UserCenterNewbean;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-virtual {v4}, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->getBirth_day()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-static {v4}, Landroid/text/TextUtils;->isEmpty(Ljava/lang/CharSequence;)Z
a=0;// 
a=0;//     move-result v4
a=0;// 
a=0;//     #v4=(Boolean);
a=0;//     if-nez v4, :cond_3
a=0;// 
a=0;//     .line 119
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     #v4=(Reference,Lcom/twocloo/com/cn/activitys/EditProfileActivity;);
a=0;//     iget-object v5, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     invoke-static {v5}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$2(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Lcom/twocloo/com/cn/beans/UserCenterNewbean;
a=0;// 
a=0;//     move-result-object v5
a=0;// 
a=0;//     invoke-virtual {v5}, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->getBirth_year()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v5
a=0;// 
a=0;//     invoke-static {v5}, Ljava/lang/Integer;->parseInt(Ljava/lang/String;)I
a=0;// 
a=0;//     move-result v5
a=0;// 
a=0;//     #v5=(Integer);
a=0;//     invoke-static {v4, v5}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$10(Lcom/twocloo/com/cn/activitys/EditProfileActivity;I)V
a=0;// 
a=0;//     .line 120
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     iget-object v5, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     #v5=(Reference,Lcom/twocloo/com/cn/activitys/EditProfileActivity;);
a=0;//     invoke-static {v5}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$2(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Lcom/twocloo/com/cn/beans/UserCenterNewbean;
a=0;// 
a=0;//     move-result-object v5
a=0;// 
a=0;//     invoke-virtual {v5}, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->getBirth_month()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v5
a=0;// 
a=0;//     invoke-static {v5}, Ljava/lang/Integer;->parseInt(Ljava/lang/String;)I
a=0;// 
a=0;//     move-result v5
a=0;// 
a=0;//     #v5=(Integer);
a=0;//     invoke-static {v4, v5}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$11(Lcom/twocloo/com/cn/activitys/EditProfileActivity;I)V
a=0;// 
a=0;//     .line 121
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     iget-object v5, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     #v5=(Reference,Lcom/twocloo/com/cn/activitys/EditProfileActivity;);
a=0;//     invoke-static {v5}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$2(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Lcom/twocloo/com/cn/beans/UserCenterNewbean;
a=0;// 
a=0;//     move-result-object v5
a=0;// 
a=0;//     invoke-virtual {v5}, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->getBirth_day()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v5
a=0;// 
a=0;//     invoke-static {v5}, Ljava/lang/Integer;->parseInt(Ljava/lang/String;)I
a=0;// 
a=0;//     move-result v5
a=0;// 
a=0;//     #v5=(Integer);
a=0;//     invoke-static {v4, v5}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$12(Lcom/twocloo/com/cn/activitys/EditProfileActivity;I)V
a=0;// 
a=0;//     .line 123
a=0;//     :cond_3
a=0;//     #v4=(Conflicted);v5=(Conflicted);
a=0;//     const-string v4, "1"
a=0;// 
a=0;//     #v4=(Reference,Ljava/lang/String;);
a=0;//     iget-object v5, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     #v5=(Reference,Lcom/twocloo/com/cn/activitys/EditProfileActivity;);
a=0;//     invoke-static {v5}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$2(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Lcom/twocloo/com/cn/beans/UserCenterNewbean;
a=0;// 
a=0;//     move-result-object v5
a=0;// 
a=0;//     invoke-virtual {v5}, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->getGender()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v5
a=0;// 
a=0;//     invoke-virtual {v4, v5}, Ljava/lang/String;->equals(Ljava/lang/Object;)Z
a=0;// 
a=0;//     move-result v4
a=0;// 
a=0;//     #v4=(Boolean);
a=0;//     if-eqz v4, :cond_8
a=0;// 
a=0;//     .line 124
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     #v4=(Reference,Lcom/twocloo/com/cn/activitys/EditProfileActivity;);
a=0;//     invoke-static {v4}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$13(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Landroid/widget/TextView;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     const-string v5, "\u7537"
a=0;// 
a=0;//     invoke-virtual {v4, v5}, Landroid/widget/TextView;->setText(Ljava/lang/CharSequence;)V
a=0;// 
a=0;//     .line 129
a=0;//     :cond_4
a=0;//     :goto_2
a=0;//     #v4=(Conflicted);
a=0;//     const-string v4, "0"
a=0;// 
a=0;//     #v4=(Reference,Ljava/lang/String;);
a=0;//     iget-object v5, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     invoke-static {v5}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$2(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Lcom/twocloo/com/cn/beans/UserCenterNewbean;
a=0;// 
a=0;//     move-result-object v5
a=0;// 
a=0;//     invoke-virtual {v5}, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->getAge()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v5
a=0;// 
a=0;//     invoke-virtual {v4, v5}, Ljava/lang/String;->equals(Ljava/lang/Object;)Z
a=0;// 
a=0;//     move-result v4
a=0;// 
a=0;//     #v4=(Boolean);
a=0;//     if-nez v4, :cond_5
a=0;// 
a=0;//     .line 130
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     #v4=(Reference,Lcom/twocloo/com/cn/activitys/EditProfileActivity;);
a=0;//     invoke-static {v4}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$14(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Landroid/widget/TextView;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     iget-object v5, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     invoke-static {v5}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$2(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Lcom/twocloo/com/cn/beans/UserCenterNewbean;
a=0;// 
a=0;//     move-result-object v5
a=0;// 
a=0;//     invoke-virtual {v5}, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->getAge()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v5
a=0;// 
a=0;//     invoke-virtual {v4, v5}, Landroid/widget/TextView;->setText(Ljava/lang/CharSequence;)V
a=0;// 
a=0;//     .line 133
a=0;//     :cond_5
a=0;//     #v4=(Conflicted);
a=0;//     const-string v4, "0"
a=0;// 
a=0;//     #v4=(Reference,Ljava/lang/String;);
a=0;//     iget-object v5, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     invoke-static {v5}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$2(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Lcom/twocloo/com/cn/beans/UserCenterNewbean;
a=0;// 
a=0;//     move-result-object v5
a=0;// 
a=0;//     invoke-virtual {v5}, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->getStar()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v5
a=0;// 
a=0;//     invoke-virtual {v4, v5}, Ljava/lang/String;->equals(Ljava/lang/Object;)Z
a=0;// 
a=0;//     move-result v4
a=0;// 
a=0;//     #v4=(Boolean);
a=0;//     if-nez v4, :cond_6
a=0;// 
a=0;//     const-string v4, ""
a=0;// 
a=0;//     #v4=(Reference,Ljava/lang/String;);
a=0;//     iget-object v5, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     invoke-static {v5}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$2(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Lcom/twocloo/com/cn/beans/UserCenterNewbean;
a=0;// 
a=0;//     move-result-object v5
a=0;// 
a=0;//     invoke-virtual {v5}, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->getStar()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v5
a=0;// 
a=0;//     invoke-virtual {v4, v5}, Ljava/lang/String;->equals(Ljava/lang/Object;)Z
a=0;// 
a=0;//     move-result v4
a=0;// 
a=0;//     #v4=(Boolean);
a=0;//     if-nez v4, :cond_6
a=0;// 
a=0;//     .line 134
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     #v4=(Reference,Lcom/twocloo/com/cn/activitys/EditProfileActivity;);
a=0;//     invoke-static {v4}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$2(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Lcom/twocloo/com/cn/beans/UserCenterNewbean;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-virtual {v4}, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->getStar()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-static {v4}, Ljava/lang/Integer;->parseInt(Ljava/lang/String;)I
a=0;// 
a=0;//     move-result v3
a=0;// 
a=0;//     .line 135
a=0;//     .local v3, "star":I
a=0;//     #v3=(Integer);
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     invoke-static {v4}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$15(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Landroid/widget/TextView;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     iget-object v5, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     invoke-static {v5}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$16(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)[Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v5
a=0;// 
a=0;//     add-int/lit8 v6, v3, -0x1
a=0;// 
a=0;//     #v6=(Integer);
a=0;//     aget-object v5, v5, v6
a=0;// 
a=0;//     #v5=(Null);
a=0;//     invoke-virtual {v4, v5}, Landroid/widget/TextView;->setText(Ljava/lang/CharSequence;)V
a=0;// 
a=0;//     .line 138
a=0;//     .end local v3    # "star":I
a=0;//     :cond_6
a=0;//     #v3=(Conflicted);v4=(Conflicted);v5=(Reference,Ljava/lang/String;);v6=(Conflicted);
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     #v4=(Reference,Lcom/twocloo/com/cn/activitys/EditProfileActivity;);
a=0;//     iget-object v5, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     invoke-static {v5}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$2(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Lcom/twocloo/com/cn/beans/UserCenterNewbean;
a=0;// 
a=0;//     move-result-object v5
a=0;// 
a=0;//     invoke-virtual {v5}, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->getMark()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v5
a=0;// 
a=0;//     invoke-static {v4, v5}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$17(Lcom/twocloo/com/cn/activitys/EditProfileActivity;Ljava/lang/String;)V
a=0;// 
a=0;//     .line 139
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     invoke-static {v4}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$18(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     if-eqz v4, :cond_0
a=0;// 
a=0;//     const-string v4, ""
a=0;// 
a=0;//     iget-object v5, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     invoke-static {v5}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$18(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v5
a=0;// 
a=0;//     invoke-virtual {v4, v5}, Ljava/lang/String;->equals(Ljava/lang/Object;)Z
a=0;// 
a=0;//     move-result v4
a=0;// 
a=0;//     #v4=(Boolean);
a=0;//     if-nez v4, :cond_0
a=0;// 
a=0;//     .line 140
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     #v4=(Reference,Lcom/twocloo/com/cn/activitys/EditProfileActivity;);
a=0;//     invoke-static {v4}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$18(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     const-string v5, ","
a=0;// 
a=0;//     invoke-virtual {v4, v5}, Ljava/lang/String;->split(Ljava/lang/String;)[Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     .line 141
a=0;//     .local v2, "marks":[Ljava/lang/String;
a=0;//     #v2=(Reference,[Ljava/lang/String;);
a=0;//     array-length v1, v2
a=0;// 
a=0;//     .line 142
a=0;//     .local v1, "length":I
a=0;//     #v1=(Integer);
a=0;//     if-ne v1, v10, :cond_9
a=0;// 
a=0;//     .line 143
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     invoke-static {v4}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$19(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Landroid/widget/Button;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-virtual {v4, v8}, Landroid/widget/Button;->setVisibility(I)V
a=0;// 
a=0;//     .line 144
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     invoke-static {v4}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$19(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Landroid/widget/Button;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     aget-object v5, v2, v8
a=0;// 
a=0;//     #v5=(Null);
a=0;//     invoke-virtual {v4, v5}, Landroid/widget/Button;->setText(Ljava/lang/CharSequence;)V
a=0;// 
a=0;//     .line 145
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     invoke-static {v4}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$20(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Landroid/widget/Button;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-virtual {v4, v9}, Landroid/widget/Button;->setVisibility(I)V
a=0;// 
a=0;//     .line 146
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     invoke-static {v4}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$21(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Landroid/widget/Button;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-virtual {v4, v9}, Landroid/widget/Button;->setVisibility(I)V
a=0;// 
a=0;//     .line 147
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     invoke-static {v4}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$22(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Landroid/widget/Button;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-virtual {v4, v9}, Landroid/widget/Button;->setVisibility(I)V
a=0;// 
a=0;//     goto/16 :goto_0
a=0;// 
a=0;//     .line 115
a=0;//     .end local v1    # "length":I
a=0;//     .end local v2    # "marks":[Ljava/lang/String;
a=0;//     :cond_7
a=0;//     #v1=(Uninit);v2=(Uninit);v3=(Uninit);v4=(Integer);v5=(PosByte);v6=(Uninit);v7=(Uninit);
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     #v4=(Reference,Lcom/twocloo/com/cn/activitys/EditProfileActivity;);
a=0;//     invoke-static {v4}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$9(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Landroid/widget/TextView;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     iget-object v5, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     #v5=(Reference,Lcom/twocloo/com/cn/activitys/EditProfileActivity;);
a=0;//     invoke-static {v5}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$8(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v5
a=0;// 
a=0;//     invoke-virtual {v4, v5}, Landroid/widget/TextView;->setText(Ljava/lang/CharSequence;)V
a=0;// 
a=0;//     goto/16 :goto_1
a=0;// 
a=0;//     .line 125
a=0;//     :cond_8
a=0;//     #v4=(Boolean);v6=(Conflicted);v7=(Conflicted);
a=0;//     const-string v4, "2"
a=0;// 
a=0;//     #v4=(Reference,Ljava/lang/String;);
a=0;//     iget-object v5, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     invoke-static {v5}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$2(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Lcom/twocloo/com/cn/beans/UserCenterNewbean;
a=0;// 
a=0;//     move-result-object v5
a=0;// 
a=0;//     invoke-virtual {v5}, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->getGender()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v5
a=0;// 
a=0;//     invoke-virtual {v4, v5}, Ljava/lang/String;->equals(Ljava/lang/Object;)Z
a=0;// 
a=0;//     move-result v4
a=0;// 
a=0;//     #v4=(Boolean);
a=0;//     if-eqz v4, :cond_4
a=0;// 
a=0;//     .line 126
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     #v4=(Reference,Lcom/twocloo/com/cn/activitys/EditProfileActivity;);
a=0;//     invoke-static {v4}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$13(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Landroid/widget/TextView;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     const-string v5, "\u5973"
a=0;// 
a=0;//     invoke-virtual {v4, v5}, Landroid/widget/TextView;->setText(Ljava/lang/CharSequence;)V
a=0;// 
a=0;//     goto/16 :goto_2
a=0;// 
a=0;//     .line 148
a=0;//     .restart local v1    # "length":I
a=0;//     .restart local v2    # "marks":[Ljava/lang/String;
a=0;//     :cond_9
a=0;//     #v1=(Integer);v2=(Reference,[Ljava/lang/String;);v3=(Conflicted);
a=0;//     if-ne v1, v11, :cond_a
a=0;// 
a=0;//     .line 149
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     invoke-static {v4}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$19(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Landroid/widget/Button;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-virtual {v4, v8}, Landroid/widget/Button;->setVisibility(I)V
a=0;// 
a=0;//     .line 150
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     invoke-static {v4}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$19(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Landroid/widget/Button;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     aget-object v5, v2, v8
a=0;// 
a=0;//     #v5=(Null);
a=0;//     invoke-virtual {v4, v5}, Landroid/widget/Button;->setText(Ljava/lang/CharSequence;)V
a=0;// 
a=0;//     .line 151
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     invoke-static {v4}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$20(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Landroid/widget/Button;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-virtual {v4, v8}, Landroid/widget/Button;->setVisibility(I)V
a=0;// 
a=0;//     .line 152
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     invoke-static {v4}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$20(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Landroid/widget/Button;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     aget-object v5, v2, v10
a=0;// 
a=0;//     invoke-virtual {v4, v5}, Landroid/widget/Button;->setText(Ljava/lang/CharSequence;)V
a=0;// 
a=0;//     .line 153
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     invoke-static {v4}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$21(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Landroid/widget/Button;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-virtual {v4, v9}, Landroid/widget/Button;->setVisibility(I)V
a=0;// 
a=0;//     .line 154
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     invoke-static {v4}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$22(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Landroid/widget/Button;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-virtual {v4, v9}, Landroid/widget/Button;->setVisibility(I)V
a=0;// 
a=0;//     goto/16 :goto_0
a=0;// 
a=0;//     .line 155
a=0;//     :cond_a
a=0;//     #v5=(Reference,Ljava/lang/String;);
a=0;//     if-ne v1, v12, :cond_b
a=0;// 
a=0;//     .line 156
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     invoke-static {v4}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$19(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Landroid/widget/Button;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-virtual {v4, v8}, Landroid/widget/Button;->setVisibility(I)V
a=0;// 
a=0;//     .line 157
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     invoke-static {v4}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$19(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Landroid/widget/Button;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     aget-object v5, v2, v8
a=0;// 
a=0;//     #v5=(Null);
a=0;//     invoke-virtual {v4, v5}, Landroid/widget/Button;->setText(Ljava/lang/CharSequence;)V
a=0;// 
a=0;//     .line 158
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     invoke-static {v4}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$20(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Landroid/widget/Button;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-virtual {v4, v8}, Landroid/widget/Button;->setVisibility(I)V
a=0;// 
a=0;//     .line 159
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     invoke-static {v4}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$20(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Landroid/widget/Button;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     aget-object v5, v2, v10
a=0;// 
a=0;//     invoke-virtual {v4, v5}, Landroid/widget/Button;->setText(Ljava/lang/CharSequence;)V
a=0;// 
a=0;//     .line 160
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     invoke-static {v4}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$21(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Landroid/widget/Button;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-virtual {v4, v8}, Landroid/widget/Button;->setVisibility(I)V
a=0;// 
a=0;//     .line 161
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     invoke-static {v4}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$21(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Landroid/widget/Button;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     aget-object v5, v2, v11
a=0;// 
a=0;//     invoke-virtual {v4, v5}, Landroid/widget/Button;->setText(Ljava/lang/CharSequence;)V
a=0;// 
a=0;//     .line 162
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     invoke-static {v4}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$22(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Landroid/widget/Button;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-virtual {v4, v9}, Landroid/widget/Button;->setVisibility(I)V
a=0;// 
a=0;//     goto/16 :goto_0
a=0;// 
a=0;//     .line 163
a=0;//     :cond_b
a=0;//     #v5=(Reference,Ljava/lang/String;);
a=0;//     const/4 v4, 0x4
a=0;// 
a=0;//     #v4=(PosByte);
a=0;//     if-ne v1, v4, :cond_0
a=0;// 
a=0;//     .line 164
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     #v4=(Reference,Lcom/twocloo/com/cn/activitys/EditProfileActivity;);
a=0;//     invoke-static {v4}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$19(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Landroid/widget/Button;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-virtual {v4, v8}, Landroid/widget/Button;->setVisibility(I)V
a=0;// 
a=0;//     .line 165
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     invoke-static {v4}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$19(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Landroid/widget/Button;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     aget-object v5, v2, v8
a=0;// 
a=0;//     #v5=(Null);
a=0;//     invoke-virtual {v4, v5}, Landroid/widget/Button;->setText(Ljava/lang/CharSequence;)V
a=0;// 
a=0;//     .line 166
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     invoke-static {v4}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$20(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Landroid/widget/Button;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-virtual {v4, v8}, Landroid/widget/Button;->setVisibility(I)V
a=0;// 
a=0;//     .line 167
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     invoke-static {v4}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$20(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Landroid/widget/Button;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     aget-object v5, v2, v10
a=0;// 
a=0;//     invoke-virtual {v4, v5}, Landroid/widget/Button;->setText(Ljava/lang/CharSequence;)V
a=0;// 
a=0;//     .line 168
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     invoke-static {v4}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$21(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Landroid/widget/Button;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-virtual {v4, v8}, Landroid/widget/Button;->setVisibility(I)V
a=0;// 
a=0;//     .line 169
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     invoke-static {v4}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$21(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Landroid/widget/Button;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     aget-object v5, v2, v11
a=0;// 
a=0;//     invoke-virtual {v4, v5}, Landroid/widget/Button;->setText(Ljava/lang/CharSequence;)V
a=0;// 
a=0;//     .line 170
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     invoke-static {v4}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$22(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Landroid/widget/Button;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-virtual {v4, v8}, Landroid/widget/Button;->setVisibility(I)V
a=0;// 
a=0;//     .line 171
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     invoke-static {v4}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->access$22(Lcom/twocloo/com/cn/activitys/EditProfileActivity;)Landroid/widget/Button;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     aget-object v5, v2, v12
a=0;// 
a=0;//     invoke-virtual {v4, v5}, Landroid/widget/Button;->setText(Ljava/lang/CharSequence;)V
a=0;// 
a=0;//     goto/16 :goto_0
a=0;// 
a=0;//     .line 175
a=0;//     .end local v1    # "length":I
a=0;//     .end local v2    # "marks":[Ljava/lang/String;
a=0;//     :cond_c
a=0;//     #v1=(Uninit);v2=(Uninit);v3=(Uninit);v4=(PosByte);v5=(Uninit);v6=(Uninit);v7=(Uninit);
a=0;//     if-ne v0, v11, :cond_d
a=0;// 
a=0;//     .line 176
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     #v4=(Reference,Lcom/twocloo/com/cn/activitys/EditProfileActivity;);
a=0;//     invoke-virtual {v4}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->getApplicationContext()Landroid/content/Context;
a=0;// 
a=0;//     move-result-object v5
a=0;// 
a=0;//     #v5=(Reference,Landroid/content/Context;);
a=0;//     iget-object v4, p1, Landroid/os/Message;->obj:Ljava/lang/Object;
a=0;// 
a=0;//     check-cast v4, Ljava/lang/String;
a=0;// 
a=0;//     invoke-static {v5, v4, v8}, Landroid/widget/Toast;->makeText(Landroid/content/Context;Ljava/lang/CharSequence;I)Landroid/widget/Toast;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-virtual {v4}, Landroid/widget/Toast;->show()V
a=0;// 
a=0;//     goto/16 :goto_0
a=0;// 
a=0;//     .line 177
a=0;//     :cond_d
a=0;//     #v4=(PosByte);v5=(Uninit);
a=0;//     if-ne v0, v12, :cond_0
a=0;// 
a=0;//     .line 178
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     #v4=(Reference,Lcom/twocloo/com/cn/activitys/EditProfileActivity;);
a=0;//     invoke-virtual {v4}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->getApplicationContext()Landroid/content/Context;
a=0;// 
a=0;//     move-result-object v5
a=0;// 
a=0;//     #v5=(Reference,Landroid/content/Context;);
a=0;//     iget-object v4, p1, Landroid/os/Message;->obj:Ljava/lang/Object;
a=0;// 
a=0;//     check-cast v4, Ljava/lang/String;
a=0;// 
a=0;//     invoke-static {v5, v4, v8}, Landroid/widget/Toast;->makeText(Landroid/content/Context;Ljava/lang/CharSequence;I)Landroid/widget/Toast;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-virtual {v4}, Landroid/widget/Toast;->show()V
a=0;// 
a=0;//     .line 179
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/EditProfileActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/EditProfileActivity;
a=0;// 
a=0;//     invoke-virtual {v4}, Lcom/twocloo/com/cn/activitys/EditProfileActivity;->finish()V
a=0;// 
a=0;//     goto/16 :goto_0
a=0;// .end method
}}
