package com.twocloo.com.cn.activitys; class InstallationWizardActivity$1 { void a() { int a;
a=0;// .class Lcom/twocloo/com/cn/activitys/InstallationWizardActivity$1;
a=0;// .super Ljava/lang/Object;
a=0;// .source "InstallationWizardActivity.java"
a=0;// 
a=0;// # interfaces
a=0;// .implements Landroid/support/v4/view/ViewPager$OnPageChangeListener;
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation system Ldalvik/annotation/EnclosingMethod;
a=0;//     value = Lcom/twocloo/com/cn/activitys/InstallationWizardActivity;->onCreate(Landroid/os/Bundle;)V
a=0;// .end annotation
a=0;// 
a=0;// .annotation system Ldalvik/annotation/InnerClass;
a=0;//     accessFlags = 0x0
a=0;//     name = null
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field final synthetic this$0:Lcom/twocloo/com/cn/activitys/InstallationWizardActivity;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>(Lcom/twocloo/com/cn/activitys/InstallationWizardActivity;)V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 1
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/activitys/InstallationWizardActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/InstallationWizardActivity;
a=0;// 
a=0;//     .line 44
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcom/twocloo/com/cn/activitys/InstallationWizardActivity$1;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public onPageScrollStateChanged(I)V
a=0;//     .locals 0
a=0;//     .param p1, "arg0"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 61
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public onPageScrolled(IFI)V
a=0;//     .locals 0
a=0;//     .param p1, "arg0"    # I
a=0;//     .param p2, "arg1"    # F
a=0;//     .param p3, "arg2"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 56
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public onPageSelected(I)V
a=0;//     .locals 0
a=0;//     .param p1, "arg0"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 51
a=0;//     return-void
a=0;// .end method
}}
