package com.twocloo.com.cn.activitys; class LastPageGuide$1 { void a() { int a;
a=0;// .class Lcom/twocloo/com/cn/activitys/LastPageGuide$1;
a=0;// .super Landroid/webkit/WebViewClient;
a=0;// .source "LastPageGuide.java"
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation system Ldalvik/annotation/EnclosingMethod;
a=0;//     value = Lcom/twocloo/com/cn/activitys/LastPageGuide;->onCreate(Landroid/os/Bundle;)V
a=0;// .end annotation
a=0;// 
a=0;// .annotation system Ldalvik/annotation/InnerClass;
a=0;//     accessFlags = 0x0
a=0;//     name = null
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field final synthetic this$0:Lcom/twocloo/com/cn/activitys/LastPageGuide;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>(Lcom/twocloo/com/cn/activitys/LastPageGuide;)V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 1
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/activitys/LastPageGuide$1;->this$0:Lcom/twocloo/com/cn/activitys/LastPageGuide;
a=0;// 
a=0;//     .line 81
a=0;//     invoke-direct {p0}, Landroid/webkit/WebViewClient;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcom/twocloo/com/cn/activitys/LastPageGuide$1;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method static synthetic access$0(Lcom/twocloo/com/cn/activitys/LastPageGuide$1;)Lcom/twocloo/com/cn/activitys/LastPageGuide;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 81
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/LastPageGuide$1;->this$0:Lcom/twocloo/com/cn/activitys/LastPageGuide;
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/activitys/LastPageGuide;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public onPageFinished(Landroid/webkit/WebView;Ljava/lang/String;)V
a=0;//     .locals 2
a=0;//     .param p1, "view"    # Landroid/webkit/WebView;
a=0;//     .param p2, "url"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 93
a=0;//     invoke-super {p0, p1, p2}, Landroid/webkit/WebViewClient;->onPageFinished(Landroid/webkit/WebView;Ljava/lang/String;)V
a=0;// 
a=0;//     .line 95
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/LastPageGuide$1;->this$0:Lcom/twocloo/com/cn/activitys/LastPageGuide;
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/activitys/LastPageGuide;);
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/LastPageGuide;->access$0(Lcom/twocloo/com/cn/activitys/LastPageGuide;)Landroid/app/ProgressDialog;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     if-eqz v0, :cond_0
a=0;// 
a=0;//     .line 96
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/LastPageGuide$1;->this$0:Lcom/twocloo/com/cn/activitys/LastPageGuide;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/LastPageGuide;->access$0(Lcom/twocloo/com/cn/activitys/LastPageGuide;)Landroid/app/ProgressDialog;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Landroid/app/ProgressDialog;->cancel()V
a=0;// 
a=0;//     .line 97
a=0;//     :cond_0
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/LastPageGuide$1;->this$0:Lcom/twocloo/com/cn/activitys/LastPageGuide;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/LastPageGuide;->access$2(Lcom/twocloo/com/cn/activitys/LastPageGuide;)Landroid/webkit/WebView;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, "javascript:$(\"[href=\'#\']\").attr(\"href\",\"####\");"
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v1}, Landroid/webkit/WebView;->loadUrl(Ljava/lang/String;)V
a=0;// 
a=0;//     .line 98
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public onPageStarted(Landroid/webkit/WebView;Ljava/lang/String;Landroid/graphics/Bitmap;)V
a=0;//     .locals 2
a=0;//     .param p1, "view"    # Landroid/webkit/WebView;
a=0;//     .param p2, "url"    # Ljava/lang/String;
a=0;//     .param p3, "favicon"    # Landroid/graphics/Bitmap;
a=0;// 
a=0;//     .prologue
a=0;//     .line 84
a=0;//     invoke-super {p0, p1, p2, p3}, Landroid/webkit/WebViewClient;->onPageStarted(Landroid/webkit/WebView;Ljava/lang/String;Landroid/graphics/Bitmap;)V
a=0;// 
a=0;//     .line 86
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/LastPageGuide$1;->this$0:Lcom/twocloo/com/cn/activitys/LastPageGuide;
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/activitys/LastPageGuide;);
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/LastPageGuide;->access$0(Lcom/twocloo/com/cn/activitys/LastPageGuide;)Landroid/app/ProgressDialog;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     if-eqz v0, :cond_0
a=0;// 
a=0;//     .line 87
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/LastPageGuide$1;->this$0:Lcom/twocloo/com/cn/activitys/LastPageGuide;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/LastPageGuide;->access$0(Lcom/twocloo/com/cn/activitys/LastPageGuide;)Landroid/app/ProgressDialog;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Landroid/app/ProgressDialog;->cancel()V
a=0;// 
a=0;//     .line 88
a=0;//     :cond_0
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/LastPageGuide$1;->this$0:Lcom/twocloo/com/cn/activitys/LastPageGuide;
a=0;// 
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/LastPageGuide$1;->this$0:Lcom/twocloo/com/cn/activitys/LastPageGuide;
a=0;// 
a=0;//     #v1=(Reference,Lcom/twocloo/com/cn/activitys/LastPageGuide;);
a=0;//     invoke-static {v1}, Lcom/twocloo/base/util/ViewUtils;->progressLoading(Landroid/content/Context;)Landroid/app/ProgressDialog;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-static {v0, v1}, Lcom/twocloo/com/cn/activitys/LastPageGuide;->access$1(Lcom/twocloo/com/cn/activitys/LastPageGuide;Landroid/app/ProgressDialog;)V
a=0;// 
a=0;//     .line 89
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public onReceivedError(Landroid/webkit/WebView;ILjava/lang/String;Ljava/lang/String;)V
a=0;//     .locals 2
a=0;//     .param p1, "view"    # Landroid/webkit/WebView;
a=0;//     .param p2, "errorCode"    # I
a=0;//     .param p3, "description"    # Ljava/lang/String;
a=0;//     .param p4, "failingUrl"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 108
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/LastPageGuide$1;->this$0:Lcom/twocloo/com/cn/activitys/LastPageGuide;
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/activitys/LastPageGuide;);
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/LastPageGuide;->access$3(Lcom/twocloo/com/cn/activitys/LastPageGuide;)Landroid/widget/RelativeLayout;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const/4 v1, 0x0
a=0;// 
a=0;//     #v1=(Null);
a=0;//     invoke-virtual {v0, v1}, Landroid/widget/RelativeLayout;->setVisibility(I)V
a=0;// 
a=0;//     .line 109
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/LastPageGuide$1;->this$0:Lcom/twocloo/com/cn/activitys/LastPageGuide;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/LastPageGuide;->access$2(Lcom/twocloo/com/cn/activitys/LastPageGuide;)Landroid/webkit/WebView;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const/16 v1, 0x8
a=0;// 
a=0;//     #v1=(PosByte);
a=0;//     invoke-virtual {v0, v1}, Landroid/webkit/WebView;->setVisibility(I)V
a=0;// 
a=0;//     .line 110
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/LastPageGuide$1;->this$0:Lcom/twocloo/com/cn/activitys/LastPageGuide;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/LastPageGuide;->access$4(Lcom/twocloo/com/cn/activitys/LastPageGuide;)Landroid/widget/Button;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     new-instance v1, Lcom/twocloo/com/cn/activitys/LastPageGuide$1$1;
a=0;// 
a=0;//     #v1=(UninitRef,Lcom/twocloo/com/cn/activitys/LastPageGuide$1$1;);
a=0;//     invoke-direct {v1, p0}, Lcom/twocloo/com/cn/activitys/LastPageGuide$1$1;-><init>(Lcom/twocloo/com/cn/activitys/LastPageGuide$1;)V
a=0;// 
a=0;//     #v1=(Reference,Lcom/twocloo/com/cn/activitys/LastPageGuide$1$1;);
a=0;//     invoke-virtual {v0, v1}, Landroid/widget/Button;->setOnClickListener(Landroid/view/View$OnClickListener;)V
a=0;// 
a=0;//     .line 117
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public shouldOverrideUrlLoading(Landroid/webkit/WebView;Ljava/lang/String;)Z
a=0;//     .locals 1
a=0;//     .param p1, "view"    # Landroid/webkit/WebView;
a=0;//     .param p2, "url"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 102
a=0;//     invoke-virtual {p1, p2}, Landroid/webkit/WebView;->loadUrl(Ljava/lang/String;)V
a=0;// 
a=0;//     .line 103
a=0;//     const/4 v0, 0x1
a=0;// 
a=0;//     #v0=(One);
a=0;//     return v0
a=0;// .end method
}}
