package com.twocloo.com.cn.activitys; class MainActivity { void a() { int a;
a=0;// .class public Lcom/twocloo/com/cn/activitys/MainActivity;
a=0;// .super Lcom/slidingmenu/lib/app/SlidingFragmentActivity;
a=0;// .source "MainActivity.java"
a=0;// 
a=0;// # interfaces
a=0;// .implements Landroid/widget/CompoundButton$OnCheckedChangeListener;
a=0;// .implements Lcom/slidingmenu/lib/SlidingMenu$OnClosedListener;
a=0;// .implements Lcom/slidingmenu/lib/SlidingMenu$OnOpenedListener;
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field public bottom_menu_layout:Landroid/widget/LinearLayout;
a=0;// 
a=0;// .field private curFragment:Landroid/support/v4/app/Fragment;
a=0;// 
a=0;// .field private fontColor:I
a=0;// 
a=0;// .field private mainSlidingMenu:Lcom/twocloo/com/cn/fragment/MainSlidingMenu;
a=0;// 
a=0;// .field private rb_bookcity:Landroid/widget/RadioButton;
a=0;// 
a=0;// .field private rb_bookshelf:Landroid/widget/RadioButton;
a=0;// 
a=0;// .field private rb_discover:Landroid/widget/RadioButton;
a=0;// 
a=0;// .field private rb_search:Landroid/widget/RadioButton;
a=0;// 
a=0;// .field private rb_usercenter:Landroid/widget/RadioButton;
a=0;// 
a=0;// .field private sm:Lcom/slidingmenu/lib/SlidingMenu;
a=0;// 
a=0;// .field public tabs:Landroid/widget/RadioGroup;
a=0;// 
a=0;// .field private tag:Ljava/lang/String;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 38
a=0;//     invoke-direct {p0}, Lcom/slidingmenu/lib/app/SlidingFragmentActivity;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcom/twocloo/com/cn/activitys/MainActivity;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method private doOnCheckedChanged(Landroid/support/v4/app/Fragment;)V
a=0;//     .locals 2
a=0;//     .param p1, "fragment"    # Landroid/support/v4/app/Fragment;
a=0;// 
a=0;//     .prologue
a=0;//     .line 325
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/activitys/MainActivity;->getSupportFragmentManager()Landroid/support/v4/app/FragmentManager;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 326
a=0;//     #v0=(Reference,Landroid/support/v4/app/FragmentManager;);
a=0;//     invoke-virtual {v0}, Landroid/support/v4/app/FragmentManager;->beginTransaction()Landroid/support/v4/app/FragmentTransaction;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 330
a=0;//     sget v1, Lcom/twocloo/com/cn/R$id;->main_content:I
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     invoke-virtual {v0, v1, p1}, Landroid/support/v4/app/FragmentTransaction;->replace(ILandroid/support/v4/app/Fragment;)Landroid/support/v4/app/FragmentTransaction;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Landroid/support/v4/app/FragmentTransaction;->commitAllowingStateLoss()I
a=0;// 
a=0;//     .line 332
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method private initDrawerMenu()V
a=0;//     .locals 5
a=0;// 
a=0;//     .prologue
a=0;//     .line 311
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->sm:Lcom/slidingmenu/lib/SlidingMenu;
a=0;// 
a=0;//     #v0=(Reference,Lcom/slidingmenu/lib/SlidingMenu;);
a=0;//     invoke-static {p0}, Lcom/twocloo/base/util/PhoneUtils;->getScreenPix(Landroid/app/Activity;)[I
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     #v1=(Reference,[I);
a=0;//     const/4 v2, 0x0
a=0;// 
a=0;//     #v2=(Null);
a=0;//     aget v1, v1, v2
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     int-to-double v1, v1
a=0;// 
a=0;//     #v1=(DoubleLo);v2=(DoubleHi);
a=0;//     const-wide v3, 0x3fc3333333333333L    # 0.15
a=0;// 
a=0;//     #v3=(LongLo);v4=(LongHi);
a=0;//     mul-double/2addr v1, v3
a=0;// 
a=0;//     double-to-int v1, v1
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     invoke-virtual {v0, v1}, Lcom/slidingmenu/lib/SlidingMenu;->setBehindOffset(I)V
a=0;// 
a=0;//     .line 312
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->sm:Lcom/slidingmenu/lib/SlidingMenu;
a=0;// 
a=0;//     sget v1, Lcom/twocloo/com/cn/R$dimen;->shadow_width:I
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Lcom/slidingmenu/lib/SlidingMenu;->setShadowWidthRes(I)V
a=0;// 
a=0;//     .line 313
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->sm:Lcom/slidingmenu/lib/SlidingMenu;
a=0;// 
a=0;//     sget v1, Lcom/twocloo/com/cn/R$drawable;->shadow:I
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Lcom/slidingmenu/lib/SlidingMenu;->setShadowDrawable(I)V
a=0;// 
a=0;//     .line 314
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->sm:Lcom/slidingmenu/lib/SlidingMenu;
a=0;// 
a=0;//     const/4 v1, 0x2
a=0;// 
a=0;//     #v1=(PosByte);
a=0;//     invoke-virtual {v0, v1}, Lcom/slidingmenu/lib/SlidingMenu;->setTouchModeAbove(I)V
a=0;// 
a=0;//     .line 315
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->sm:Lcom/slidingmenu/lib/SlidingMenu;
a=0;// 
a=0;//     invoke-virtual {v0, p0}, Lcom/slidingmenu/lib/SlidingMenu;->setOnOpenedListener(Lcom/slidingmenu/lib/SlidingMenu$OnOpenedListener;)V
a=0;// 
a=0;//     .line 316
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->sm:Lcom/slidingmenu/lib/SlidingMenu;
a=0;// 
a=0;//     invoke-virtual {v0, p0}, Lcom/slidingmenu/lib/SlidingMenu;->setOnClosedListener(Lcom/slidingmenu/lib/SlidingMenu$OnClosedListener;)V
a=0;// 
a=0;//     .line 317
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method private initTabs()V
a=0;//     .locals 5
a=0;// 
a=0;//     .prologue
a=0;//     .line 288
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     .local v0, "i":I
a=0;//     :goto_0
a=0;//     #v0=(Integer);v2=(Conflicted);
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->tabs:Landroid/widget/RadioGroup;
a=0;// 
a=0;//     #v2=(Reference,Landroid/widget/RadioGroup;);
a=0;//     invoke-virtual {v2}, Landroid/widget/RadioGroup;->getChildCount()I
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     if-lt v0, v2, :cond_1
a=0;// 
a=0;//     .line 292
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/activitys/MainActivity;->getIntent()Landroid/content/Intent;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     #v2=(Reference,Landroid/content/Intent;);
a=0;//     const-string v3, "id"
a=0;// 
a=0;//     #v3=(Reference,Ljava/lang/String;);
a=0;//     const/4 v4, 0x0
a=0;// 
a=0;//     #v4=(Null);
a=0;//     invoke-virtual {v2, v3, v4}, Landroid/content/Intent;->getIntExtra(Ljava/lang/String;I)I
a=0;// 
a=0;//     move-result v1
a=0;// 
a=0;//     .line 294
a=0;//     .local v1, "id":I
a=0;//     #v1=(Integer);
a=0;//     sget v2, Lcom/twocloo/com/cn/R$id;->main_bookcity:I
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     if-ne v2, v1, :cond_2
a=0;// 
a=0;//     .line 295
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/activitys/MainActivity;->goToBookCity()V
a=0;// 
a=0;//     .line 305
a=0;//     :cond_0
a=0;//     :goto_1
a=0;//     return-void
a=0;// 
a=0;//     .line 289
a=0;//     .end local v1    # "id":I
a=0;//     :cond_1
a=0;//     #v1=(Uninit);v3=(Uninit);v4=(Uninit);
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->tabs:Landroid/widget/RadioGroup;
a=0;// 
a=0;//     #v2=(Reference,Landroid/widget/RadioGroup;);
a=0;//     invoke-virtual {v2, v0}, Landroid/widget/RadioGroup;->getChildAt(I)Landroid/view/View;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     check-cast v2, Landroid/widget/RadioButton;
a=0;// 
a=0;//     invoke-virtual {v2, p0}, Landroid/widget/RadioButton;->setOnCheckedChangeListener(Landroid/widget/CompoundButton$OnCheckedChangeListener;)V
a=0;// 
a=0;//     .line 288
a=0;//     add-int/lit8 v0, v0, 0x1
a=0;// 
a=0;//     goto :goto_0
a=0;// 
a=0;//     .line 296
a=0;//     .restart local v1    # "id":I
a=0;//     :cond_2
a=0;//     #v1=(Integer);v2=(Integer);v3=(Reference,Ljava/lang/String;);v4=(Null);
a=0;//     sget v2, Lcom/twocloo/com/cn/R$id;->main_usercenter:I
a=0;// 
a=0;//     if-ne v2, v1, :cond_3
a=0;// 
a=0;//     .line 297
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/activitys/MainActivity;->goToUserCenter()V
a=0;// 
a=0;//     goto :goto_1
a=0;// 
a=0;//     .line 298
a=0;//     :cond_3
a=0;//     sget v2, Lcom/twocloo/com/cn/R$id;->main_bookshelf:I
a=0;// 
a=0;//     if-ne v2, v1, :cond_4
a=0;// 
a=0;//     .line 299
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/activitys/MainActivity;->goToBookShelf()V
a=0;// 
a=0;//     goto :goto_1
a=0;// 
a=0;//     .line 300
a=0;//     :cond_4
a=0;//     sget v2, Lcom/twocloo/com/cn/R$id;->main_discover:I
a=0;// 
a=0;//     if-ne v2, v1, :cond_5
a=0;// 
a=0;//     .line 301
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/activitys/MainActivity;->goToDiscover()V
a=0;// 
a=0;//     goto :goto_1
a=0;// 
a=0;//     .line 302
a=0;//     :cond_5
a=0;//     sget v2, Lcom/twocloo/com/cn/R$id;->main_search:I
a=0;// 
a=0;//     if-ne v2, v1, :cond_0
a=0;// 
a=0;//     .line 303
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/activitys/MainActivity;->goToSearch()V
a=0;// 
a=0;//     goto :goto_1
a=0;// .end method
a=0;// 
a=0;// .method private initView()V
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 274
a=0;//     sget v0, Lcom/twocloo/com/cn/R$id;->grouplayout:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     invoke-virtual {p0, v0}, Lcom/twocloo/com/cn/activitys/MainActivity;->findViewById(I)Landroid/view/View;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Landroid/view/View;);
a=0;//     check-cast v0, Landroid/widget/LinearLayout;
a=0;// 
a=0;//     iput-object v0, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->bottom_menu_layout:Landroid/widget/LinearLayout;
a=0;// 
a=0;//     .line 275
a=0;//     sget v0, Lcom/twocloo/com/cn/R$id;->main_tools:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     invoke-virtual {p0, v0}, Lcom/twocloo/com/cn/activitys/MainActivity;->findViewById(I)Landroid/view/View;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Landroid/view/View;);
a=0;//     check-cast v0, Landroid/widget/RadioGroup;
a=0;// 
a=0;//     iput-object v0, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->tabs:Landroid/widget/RadioGroup;
a=0;// 
a=0;//     .line 276
a=0;//     sget v0, Lcom/twocloo/com/cn/R$id;->main_bookshelf:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     invoke-virtual {p0, v0}, Lcom/twocloo/com/cn/activitys/MainActivity;->findViewById(I)Landroid/view/View;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Landroid/view/View;);
a=0;//     check-cast v0, Landroid/widget/RadioButton;
a=0;// 
a=0;//     iput-object v0, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->rb_bookshelf:Landroid/widget/RadioButton;
a=0;// 
a=0;//     .line 277
a=0;//     sget v0, Lcom/twocloo/com/cn/R$id;->main_bookcity:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     invoke-virtual {p0, v0}, Lcom/twocloo/com/cn/activitys/MainActivity;->findViewById(I)Landroid/view/View;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Landroid/view/View;);
a=0;//     check-cast v0, Landroid/widget/RadioButton;
a=0;// 
a=0;//     iput-object v0, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->rb_bookcity:Landroid/widget/RadioButton;
a=0;// 
a=0;//     .line 278
a=0;//     sget v0, Lcom/twocloo/com/cn/R$id;->main_usercenter:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     invoke-virtual {p0, v0}, Lcom/twocloo/com/cn/activitys/MainActivity;->findViewById(I)Landroid/view/View;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Landroid/view/View;);
a=0;//     check-cast v0, Landroid/widget/RadioButton;
a=0;// 
a=0;//     iput-object v0, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->rb_usercenter:Landroid/widget/RadioButton;
a=0;// 
a=0;//     .line 279
a=0;//     sget v0, Lcom/twocloo/com/cn/R$id;->main_discover:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     invoke-virtual {p0, v0}, Lcom/twocloo/com/cn/activitys/MainActivity;->findViewById(I)Landroid/view/View;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Landroid/view/View;);
a=0;//     check-cast v0, Landroid/widget/RadioButton;
a=0;// 
a=0;//     iput-object v0, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->rb_discover:Landroid/widget/RadioButton;
a=0;// 
a=0;//     .line 280
a=0;//     sget v0, Lcom/twocloo/com/cn/R$id;->main_search:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     invoke-virtual {p0, v0}, Lcom/twocloo/com/cn/activitys/MainActivity;->findViewById(I)Landroid/view/View;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Landroid/view/View;);
a=0;//     check-cast v0, Landroid/widget/RadioButton;
a=0;// 
a=0;//     iput-object v0, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->rb_search:Landroid/widget/RadioButton;
a=0;// 
a=0;//     .line 281
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method private loadSecondData()V
a=0;//     .locals 3
a=0;// 
a=0;//     .prologue
a=0;//     .line 389
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->mainSlidingMenu:Lcom/twocloo/com/cn/fragment/MainSlidingMenu;
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/fragment/MainSlidingMenu;);
a=0;//     if-nez v0, :cond_0
a=0;// 
a=0;//     .line 390
a=0;//     new-instance v0, Lcom/twocloo/com/cn/fragment/MainSlidingMenu;
a=0;// 
a=0;//     #v0=(UninitRef,Lcom/twocloo/com/cn/fragment/MainSlidingMenu;);
a=0;//     invoke-direct {v0}, Lcom/twocloo/com/cn/fragment/MainSlidingMenu;-><init>()V
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/fragment/MainSlidingMenu;);
a=0;//     iput-object v0, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->mainSlidingMenu:Lcom/twocloo/com/cn/fragment/MainSlidingMenu;
a=0;// 
a=0;//     .line 392
a=0;//     :cond_0
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->mainSlidingMenu:Lcom/twocloo/com/cn/fragment/MainSlidingMenu;
a=0;// 
a=0;//     invoke-virtual {v0}, Lcom/twocloo/com/cn/fragment/MainSlidingMenu;->isAdded()Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     if-nez v0, :cond_2
a=0;// 
a=0;//     .line 393
a=0;//     const-string v0, "loadSecondData|add"
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     invoke-static {v0}, Lcom/twocloo/base/util/LogUtils;->info(Ljava/lang/String;)V
a=0;// 
a=0;//     .line 395
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/activitys/MainActivity;->getSupportFragmentManager()Landroid/support/v4/app/FragmentManager;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 396
a=0;//     invoke-virtual {v0}, Landroid/support/v4/app/FragmentManager;->beginTransaction()Landroid/support/v4/app/FragmentTransaction;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 397
a=0;//     sget v1, Lcom/twocloo/com/cn/R$id;->main_sliding_menu_content:I
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->mainSlidingMenu:Lcom/twocloo/com/cn/fragment/MainSlidingMenu;
a=0;// 
a=0;//     #v2=(Reference,Lcom/twocloo/com/cn/fragment/MainSlidingMenu;);
a=0;//     invoke-virtual {v0, v1, v2}, Landroid/support/v4/app/FragmentTransaction;->add(ILandroid/support/v4/app/Fragment;)Landroid/support/v4/app/FragmentTransaction;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 398
a=0;//     invoke-virtual {v0}, Landroid/support/v4/app/FragmentTransaction;->commit()I
a=0;// 
a=0;//     .line 410
a=0;//     :cond_1
a=0;//     :goto_0
a=0;//     #v0=(Conflicted);v1=(Conflicted);v2=(Conflicted);
a=0;//     return-void
a=0;// 
a=0;//     .line 400
a=0;//     :cond_2
a=0;//     #v0=(Boolean);v1=(Uninit);v2=(Uninit);
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->mainSlidingMenu:Lcom/twocloo/com/cn/fragment/MainSlidingMenu;
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/fragment/MainSlidingMenu;);
a=0;//     invoke-virtual {v0}, Lcom/twocloo/com/cn/fragment/MainSlidingMenu;->isVisible()Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     if-nez v0, :cond_1
a=0;// 
a=0;//     .line 402
a=0;//     const-string v0, "loadSecondData|show"
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     invoke-static {v0}, Lcom/twocloo/base/util/LogUtils;->info(Ljava/lang/String;)V
a=0;// 
a=0;//     .line 404
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/activitys/MainActivity;->getSupportFragmentManager()Landroid/support/v4/app/FragmentManager;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 405
a=0;//     invoke-virtual {v0}, Landroid/support/v4/app/FragmentManager;->beginTransaction()Landroid/support/v4/app/FragmentTransaction;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 406
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->mainSlidingMenu:Lcom/twocloo/com/cn/fragment/MainSlidingMenu;
a=0;// 
a=0;//     #v1=(Reference,Lcom/twocloo/com/cn/fragment/MainSlidingMenu;);
a=0;//     invoke-virtual {v0, v1}, Landroid/support/v4/app/FragmentTransaction;->show(Landroid/support/v4/app/Fragment;)Landroid/support/v4/app/FragmentTransaction;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 407
a=0;//     invoke-virtual {v0}, Landroid/support/v4/app/FragmentTransaction;->commit()I
a=0;// 
a=0;//     goto :goto_0
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public goToBookCity()V
a=0;//     .locals 2
a=0;// 
a=0;//     .prologue
a=0;//     .line 338
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->tabs:Landroid/widget/RadioGroup;
a=0;// 
a=0;//     #v0=(Reference,Landroid/widget/RadioGroup;);
a=0;//     const/4 v1, 0x0
a=0;// 
a=0;//     #v1=(Null);
a=0;//     invoke-virtual {v0, v1}, Landroid/widget/RadioGroup;->getChildAt(I)Landroid/view/View;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Landroid/view/View;->performClick()Z
a=0;// 
a=0;//     .line 339
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public goToBookShelf()V
a=0;//     .locals 2
a=0;// 
a=0;//     .prologue
a=0;//     .line 345
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->tabs:Landroid/widget/RadioGroup;
a=0;// 
a=0;//     #v0=(Reference,Landroid/widget/RadioGroup;);
a=0;//     const/4 v1, 0x1
a=0;// 
a=0;//     #v1=(One);
a=0;//     invoke-virtual {v0, v1}, Landroid/widget/RadioGroup;->getChildAt(I)Landroid/view/View;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Landroid/view/View;->performClick()Z
a=0;// 
a=0;//     .line 346
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public goToDiscover()V
a=0;//     .locals 2
a=0;// 
a=0;//     .prologue
a=0;//     .line 352
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->tabs:Landroid/widget/RadioGroup;
a=0;// 
a=0;//     #v0=(Reference,Landroid/widget/RadioGroup;);
a=0;//     const/4 v1, 0x2
a=0;// 
a=0;//     #v1=(PosByte);
a=0;//     invoke-virtual {v0, v1}, Landroid/widget/RadioGroup;->getChildAt(I)Landroid/view/View;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Landroid/view/View;->performClick()Z
a=0;// 
a=0;//     .line 353
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public goToSearch()V
a=0;//     .locals 2
a=0;// 
a=0;//     .prologue
a=0;//     .line 359
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->tabs:Landroid/widget/RadioGroup;
a=0;// 
a=0;//     #v0=(Reference,Landroid/widget/RadioGroup;);
a=0;//     const/4 v1, 0x3
a=0;// 
a=0;//     #v1=(PosByte);
a=0;//     invoke-virtual {v0, v1}, Landroid/widget/RadioGroup;->getChildAt(I)Landroid/view/View;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Landroid/view/View;->performClick()Z
a=0;// 
a=0;//     .line 360
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public goToUserCenter()V
a=0;//     .locals 2
a=0;// 
a=0;//     .prologue
a=0;//     .line 366
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->tabs:Landroid/widget/RadioGroup;
a=0;// 
a=0;//     #v0=(Reference,Landroid/widget/RadioGroup;);
a=0;//     const/4 v1, 0x4
a=0;// 
a=0;//     #v1=(PosByte);
a=0;//     invoke-virtual {v0, v1}, Landroid/widget/RadioGroup;->getChildAt(I)Landroid/view/View;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Landroid/view/View;->performClick()Z
a=0;// 
a=0;//     .line 367
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public onBackPressed()V
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 263
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/activitys/MainActivity;->getSlidingMenu()Lcom/slidingmenu/lib/SlidingMenu;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Lcom/slidingmenu/lib/SlidingMenu;);
a=0;//     invoke-virtual {v0}, Lcom/slidingmenu/lib/SlidingMenu;->isMenuShowing()Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     if-eqz v0, :cond_0
a=0;// 
a=0;//     .line 264
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/activitys/MainActivity;->getSlidingMenu()Lcom/slidingmenu/lib/SlidingMenu;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Lcom/slidingmenu/lib/SlidingMenu;);
a=0;//     invoke-virtual {v0}, Lcom/slidingmenu/lib/SlidingMenu;->showContent()V
a=0;// 
a=0;//     .line 268
a=0;//     :goto_0
a=0;//     #v0=(Conflicted);
a=0;//     return-void
a=0;// 
a=0;//     .line 266
a=0;//     :cond_0
a=0;//     #v0=(Boolean);
a=0;//     invoke-static {p0}, Lcom/twocloo/com/cn/activitys/BookApp;->exitApp(Landroid/app/Activity;)V
a=0;// 
a=0;//     goto :goto_0
a=0;// .end method
a=0;// 
a=0;// .method public onCheckedChanged(Landroid/widget/CompoundButton;Z)V
a=0;//     .locals 5
a=0;//     .param p1, "buttonView"    # Landroid/widget/CompoundButton;
a=0;//     .param p2, "isChecked"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     const/4 v4, 0x2
a=0;// 
a=0;//     #v4=(PosByte);
a=0;//     const/4 v3, 0x1
a=0;// 
a=0;//     #v3=(One);
a=0;//     const/4 v2, 0x0
a=0;// 
a=0;//     .line 112
a=0;//     #v2=(Null);
a=0;//     invoke-virtual {p1}, Landroid/widget/CompoundButton;->getId()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     .line 113
a=0;//     .local v0, "id":I
a=0;//     #v0=(Integer);
a=0;//     sget v1, Lcom/twocloo/com/cn/R$id;->main_bookshelf:I
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     if-ne v0, v1, :cond_6
a=0;// 
a=0;//     .line 114
a=0;//     if-eqz p2, :cond_5
a=0;// 
a=0;//     .line 115
a=0;//     new-instance v1, Lcom/twocloo/com/cn/fragment/BookShelfFragment;
a=0;// 
a=0;//     #v1=(UninitRef,Lcom/twocloo/com/cn/fragment/BookShelfFragment;);
a=0;//     invoke-direct {v1}, Lcom/twocloo/com/cn/fragment/BookShelfFragment;-><init>()V
a=0;// 
a=0;//     #v1=(Reference,Lcom/twocloo/com/cn/fragment/BookShelfFragment;);
a=0;//     iput-object v1, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->curFragment:Landroid/support/v4/app/Fragment;
a=0;// 
a=0;//     .line 116
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->curFragment:Landroid/support/v4/app/Fragment;
a=0;// 
a=0;//     invoke-direct {p0, v1}, Lcom/twocloo/com/cn/activitys/MainActivity;->doOnCheckedChanged(Landroid/support/v4/app/Fragment;)V
a=0;// 
a=0;//     .line 117
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/activitys/MainActivity;->getApplicationContext()Landroid/content/Context;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-static {v1}, Lcom/twocloo/com/cn/common/LocalStore;->getFristInstall2(Landroid/content/Context;)I
a=0;// 
a=0;//     move-result v1
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     if-nez v1, :cond_3
a=0;// 
a=0;//     .line 118
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/activitys/MainActivity;->getApplicationContext()Landroid/content/Context;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     #v1=(Reference,Landroid/content/Context;);
a=0;//     invoke-static {v1}, Lcom/twocloo/com/cn/common/LocalStore;->getUserSex(Landroid/content/Context;)I
a=0;// 
a=0;//     move-result v1
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     if-ne v1, v3, :cond_2
a=0;// 
a=0;//     .line 119
a=0;//     sget v1, Lcom/twocloo/com/cn/R$drawable;->main_navigation_bookshelf_new_green:I
a=0;// 
a=0;//     invoke-virtual {p1, v2, v1, v2, v2}, Landroid/widget/CompoundButton;->setCompoundDrawablesWithIntrinsicBounds(IIII)V
a=0;// 
a=0;//     .line 131
a=0;//     :cond_0
a=0;//     :goto_0
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->rb_bookshelf:Landroid/widget/RadioButton;
a=0;// 
a=0;//     #v1=(Reference,Landroid/widget/RadioButton;);
a=0;//     iget v2, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->fontColor:I
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     invoke-virtual {v1, v2}, Landroid/widget/RadioButton;->setTextColor(I)V
a=0;// 
a=0;//     .line 132
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->rb_bookcity:Landroid/widget/RadioButton;
a=0;// 
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/activitys/MainActivity;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     #v2=(Reference,Landroid/content/res/Resources;);
a=0;//     sget v3, Lcom/twocloo/com/cn/R$color;->usercenter_text:I
a=0;// 
a=0;//     #v3=(Integer);
a=0;//     invoke-virtual {v2, v3}, Landroid/content/res/Resources;->getColor(I)I
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     invoke-virtual {v1, v2}, Landroid/widget/RadioButton;->setTextColor(I)V
a=0;// 
a=0;//     .line 133
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->rb_discover:Landroid/widget/RadioButton;
a=0;// 
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/activitys/MainActivity;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     #v2=(Reference,Landroid/content/res/Resources;);
a=0;//     sget v3, Lcom/twocloo/com/cn/R$color;->usercenter_text:I
a=0;// 
a=0;//     invoke-virtual {v2, v3}, Landroid/content/res/Resources;->getColor(I)I
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     invoke-virtual {v1, v2}, Landroid/widget/RadioButton;->setTextColor(I)V
a=0;// 
a=0;//     .line 134
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->rb_usercenter:Landroid/widget/RadioButton;
a=0;// 
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/activitys/MainActivity;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     #v2=(Reference,Landroid/content/res/Resources;);
a=0;//     sget v3, Lcom/twocloo/com/cn/R$color;->usercenter_text:I
a=0;// 
a=0;//     invoke-virtual {v2, v3}, Landroid/content/res/Resources;->getColor(I)I
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     invoke-virtual {v1, v2}, Landroid/widget/RadioButton;->setTextColor(I)V
a=0;// 
a=0;//     .line 135
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->rb_search:Landroid/widget/RadioButton;
a=0;// 
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/activitys/MainActivity;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     #v2=(Reference,Landroid/content/res/Resources;);
a=0;//     sget v3, Lcom/twocloo/com/cn/R$color;->usercenter_text:I
a=0;// 
a=0;//     invoke-virtual {v2, v3}, Landroid/content/res/Resources;->getColor(I)I
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     invoke-virtual {v1, v2}, Landroid/widget/RadioButton;->setTextColor(I)V
a=0;// 
a=0;//     .line 136
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->sm:Lcom/slidingmenu/lib/SlidingMenu;
a=0;// 
a=0;//     invoke-virtual {v1, v4}, Lcom/slidingmenu/lib/SlidingMenu;->setTouchModeAbove(I)V
a=0;// 
a=0;//     .line 259
a=0;//     :cond_1
a=0;//     :goto_1
a=0;//     #v1=(Conflicted);
a=0;//     return-void
a=0;// 
a=0;//     .line 121
a=0;//     :cond_2
a=0;//     #v1=(Integer);v2=(Null);v3=(One);
a=0;//     sget v1, Lcom/twocloo/com/cn/R$drawable;->main_navigation_bookshelf_new_g_red:I
a=0;// 
a=0;//     invoke-virtual {p1, v2, v1, v2, v2}, Landroid/widget/CompoundButton;->setCompoundDrawablesWithIntrinsicBounds(IIII)V
a=0;// 
a=0;//     goto :goto_0
a=0;// 
a=0;//     .line 124
a=0;//     :cond_3
a=0;//     invoke-static {p0}, Lcom/twocloo/com/cn/common/LocalStore;->getMianTopBackgroundColor(Landroid/content/Context;)I
a=0;// 
a=0;//     move-result v1
a=0;// 
a=0;//     if-ne v1, v3, :cond_4
a=0;// 
a=0;//     .line 125
a=0;//     sget v1, Lcom/twocloo/com/cn/R$drawable;->main_navigation_bookshelf_new_green:I
a=0;// 
a=0;//     invoke-virtual {p1, v2, v1, v2, v2}, Landroid/widget/CompoundButton;->setCompoundDrawablesWithIntrinsicBounds(IIII)V
a=0;// 
a=0;//     goto :goto_0
a=0;// 
a=0;//     .line 126
a=0;//     :cond_4
a=0;//     invoke-static {p0}, Lcom/twocloo/com/cn/common/LocalStore;->getMianTopBackgroundColor(Landroid/content/Context;)I
a=0;// 
a=0;//     move-result v1
a=0;// 
a=0;//     if-ne v1, v4, :cond_0
a=0;// 
a=0;//     .line 127
a=0;//     sget v1, Lcom/twocloo/com/cn/R$drawable;->main_navigation_bookshelf_new_g_red:I
a=0;// 
a=0;//     invoke-virtual {p1, v2, v1, v2, v2}, Landroid/widget/CompoundButton;->setCompoundDrawablesWithIntrinsicBounds(IIII)V
a=0;// 
a=0;//     goto :goto_0
a=0;// 
a=0;//     .line 139
a=0;//     :cond_5
a=0;//     sget v1, Lcom/twocloo/com/cn/R$drawable;->main_navigation_bookshelf_new:I
a=0;// 
a=0;//     invoke-virtual {p1, v2, v1, v2, v2}, Landroid/widget/CompoundButton;->setCompoundDrawablesWithIntrinsicBounds(IIII)V
a=0;// 
a=0;//     goto :goto_1
a=0;// 
a=0;//     .line 142
a=0;//     :cond_6
a=0;//     sget v1, Lcom/twocloo/com/cn/R$id;->main_bookcity:I
a=0;// 
a=0;//     if-ne v0, v1, :cond_c
a=0;// 
a=0;//     .line 144
a=0;//     if-eqz p2, :cond_b
a=0;// 
a=0;//     .line 145
a=0;//     new-instance v1, Lcom/twocloo/com/cn/fragment/BookCityFragment;
a=0;// 
a=0;//     #v1=(UninitRef,Lcom/twocloo/com/cn/fragment/BookCityFragment;);
a=0;//     invoke-direct {v1}, Lcom/twocloo/com/cn/fragment/BookCityFragment;-><init>()V
a=0;// 
a=0;//     #v1=(Reference,Lcom/twocloo/com/cn/fragment/BookCityFragment;);
a=0;//     iput-object v1, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->curFragment:Landroid/support/v4/app/Fragment;
a=0;// 
a=0;//     .line 147
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->curFragment:Landroid/support/v4/app/Fragment;
a=0;// 
a=0;//     invoke-direct {p0, v1}, Lcom/twocloo/com/cn/activitys/MainActivity;->doOnCheckedChanged(Landroid/support/v4/app/Fragment;)V
a=0;// 
a=0;//     .line 148
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/activitys/MainActivity;->getApplicationContext()Landroid/content/Context;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-static {v1}, Lcom/twocloo/com/cn/common/LocalStore;->getFristInstall2(Landroid/content/Context;)I
a=0;// 
a=0;//     move-result v1
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     if-nez v1, :cond_9
a=0;// 
a=0;//     .line 149
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/activitys/MainActivity;->getApplicationContext()Landroid/content/Context;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     #v1=(Reference,Landroid/content/Context;);
a=0;//     invoke-static {v1}, Lcom/twocloo/com/cn/common/LocalStore;->getUserSex(Landroid/content/Context;)I
a=0;// 
a=0;//     move-result v1
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     if-ne v1, v3, :cond_8
a=0;// 
a=0;//     .line 150
a=0;//     sget v1, Lcom/twocloo/com/cn/R$drawable;->main_navigation_bookcity_new_green:I
a=0;// 
a=0;//     invoke-virtual {p1, v2, v1, v2, v2}, Landroid/widget/CompoundButton;->setCompoundDrawablesWithIntrinsicBounds(IIII)V
a=0;// 
a=0;//     .line 162
a=0;//     :cond_7
a=0;//     :goto_2
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->rb_bookcity:Landroid/widget/RadioButton;
a=0;// 
a=0;//     #v1=(Reference,Landroid/widget/RadioButton;);
a=0;//     iget v2, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->fontColor:I
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     invoke-virtual {v1, v2}, Landroid/widget/RadioButton;->setTextColor(I)V
a=0;// 
a=0;//     .line 163
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->rb_bookshelf:Landroid/widget/RadioButton;
a=0;// 
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/activitys/MainActivity;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     #v2=(Reference,Landroid/content/res/Resources;);
a=0;//     sget v3, Lcom/twocloo/com/cn/R$color;->usercenter_text:I
a=0;// 
a=0;//     #v3=(Integer);
a=0;//     invoke-virtual {v2, v3}, Landroid/content/res/Resources;->getColor(I)I
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     invoke-virtual {v1, v2}, Landroid/widget/RadioButton;->setTextColor(I)V
a=0;// 
a=0;//     .line 164
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->rb_usercenter:Landroid/widget/RadioButton;
a=0;// 
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/activitys/MainActivity;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     #v2=(Reference,Landroid/content/res/Resources;);
a=0;//     sget v3, Lcom/twocloo/com/cn/R$color;->usercenter_text:I
a=0;// 
a=0;//     invoke-virtual {v2, v3}, Landroid/content/res/Resources;->getColor(I)I
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     invoke-virtual {v1, v2}, Landroid/widget/RadioButton;->setTextColor(I)V
a=0;// 
a=0;//     .line 165
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->rb_discover:Landroid/widget/RadioButton;
a=0;// 
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/activitys/MainActivity;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     #v2=(Reference,Landroid/content/res/Resources;);
a=0;//     sget v3, Lcom/twocloo/com/cn/R$color;->usercenter_text:I
a=0;// 
a=0;//     invoke-virtual {v2, v3}, Landroid/content/res/Resources;->getColor(I)I
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     invoke-virtual {v1, v2}, Landroid/widget/RadioButton;->setTextColor(I)V
a=0;// 
a=0;//     .line 166
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->rb_search:Landroid/widget/RadioButton;
a=0;// 
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/activitys/MainActivity;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     #v2=(Reference,Landroid/content/res/Resources;);
a=0;//     sget v3, Lcom/twocloo/com/cn/R$color;->usercenter_text:I
a=0;// 
a=0;//     invoke-virtual {v2, v3}, Landroid/content/res/Resources;->getColor(I)I
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     invoke-virtual {v1, v2}, Landroid/widget/RadioButton;->setTextColor(I)V
a=0;// 
a=0;//     .line 167
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->sm:Lcom/slidingmenu/lib/SlidingMenu;
a=0;// 
a=0;//     invoke-virtual {v1, v4}, Lcom/slidingmenu/lib/SlidingMenu;->setTouchModeAbove(I)V
a=0;// 
a=0;//     goto/16 :goto_1
a=0;// 
a=0;//     .line 152
a=0;//     :cond_8
a=0;//     #v1=(Integer);v2=(Null);v3=(One);
a=0;//     sget v1, Lcom/twocloo/com/cn/R$drawable;->main_navigation_bookcity_new_red:I
a=0;// 
a=0;//     invoke-virtual {p1, v2, v1, v2, v2}, Landroid/widget/CompoundButton;->setCompoundDrawablesWithIntrinsicBounds(IIII)V
a=0;// 
a=0;//     goto :goto_2
a=0;// 
a=0;//     .line 155
a=0;//     :cond_9
a=0;//     invoke-static {p0}, Lcom/twocloo/com/cn/common/LocalStore;->getMianTopBackgroundColor(Landroid/content/Context;)I
a=0;// 
a=0;//     move-result v1
a=0;// 
a=0;//     if-ne v1, v3, :cond_a
a=0;// 
a=0;//     .line 156
a=0;//     sget v1, Lcom/twocloo/com/cn/R$drawable;->main_navigation_bookcity_new_green:I
a=0;// 
a=0;//     invoke-virtual {p1, v2, v1, v2, v2}, Landroid/widget/CompoundButton;->setCompoundDrawablesWithIntrinsicBounds(IIII)V
a=0;// 
a=0;//     goto :goto_2
a=0;// 
a=0;//     .line 157
a=0;//     :cond_a
a=0;//     invoke-static {p0}, Lcom/twocloo/com/cn/common/LocalStore;->getMianTopBackgroundColor(Landroid/content/Context;)I
a=0;// 
a=0;//     move-result v1
a=0;// 
a=0;//     if-ne v1, v4, :cond_7
a=0;// 
a=0;//     .line 158
a=0;//     sget v1, Lcom/twocloo/com/cn/R$drawable;->main_navigation_bookcity_new_red:I
a=0;// 
a=0;//     invoke-virtual {p1, v2, v1, v2, v2}, Landroid/widget/CompoundButton;->setCompoundDrawablesWithIntrinsicBounds(IIII)V
a=0;// 
a=0;//     goto :goto_2
a=0;// 
a=0;//     .line 170
a=0;//     :cond_b
a=0;//     sget v1, Lcom/twocloo/com/cn/R$drawable;->main_navigation_bookcity_new:I
a=0;// 
a=0;//     invoke-virtual {p1, v2, v1, v2, v2}, Landroid/widget/CompoundButton;->setCompoundDrawablesWithIntrinsicBounds(IIII)V
a=0;// 
a=0;//     goto/16 :goto_1
a=0;// 
a=0;//     .line 173
a=0;//     :cond_c
a=0;//     sget v1, Lcom/twocloo/com/cn/R$id;->main_usercenter:I
a=0;// 
a=0;//     if-ne v0, v1, :cond_12
a=0;// 
a=0;//     .line 175
a=0;//     if-eqz p2, :cond_11
a=0;// 
a=0;//     .line 176
a=0;//     new-instance v1, Lcom/twocloo/com/cn/fragment/LoginFragment;
a=0;// 
a=0;//     #v1=(UninitRef,Lcom/twocloo/com/cn/fragment/LoginFragment;);
a=0;//     invoke-direct {v1}, Lcom/twocloo/com/cn/fragment/LoginFragment;-><init>()V
a=0;// 
a=0;//     #v1=(Reference,Lcom/twocloo/com/cn/fragment/LoginFragment;);
a=0;//     iput-object v1, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->curFragment:Landroid/support/v4/app/Fragment;
a=0;// 
a=0;//     .line 177
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->curFragment:Landroid/support/v4/app/Fragment;
a=0;// 
a=0;//     invoke-direct {p0, v1}, Lcom/twocloo/com/cn/activitys/MainActivity;->doOnCheckedChanged(Landroid/support/v4/app/Fragment;)V
a=0;// 
a=0;//     .line 178
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/activitys/MainActivity;->getApplicationContext()Landroid/content/Context;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-static {v1}, Lcom/twocloo/com/cn/common/LocalStore;->getFristInstall2(Landroid/content/Context;)I
a=0;// 
a=0;//     move-result v1
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     if-nez v1, :cond_f
a=0;// 
a=0;//     .line 179
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/activitys/MainActivity;->getApplicationContext()Landroid/content/Context;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     #v1=(Reference,Landroid/content/Context;);
a=0;//     invoke-static {v1}, Lcom/twocloo/com/cn/common/LocalStore;->getUserSex(Landroid/content/Context;)I
a=0;// 
a=0;//     move-result v1
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     if-ne v1, v3, :cond_e
a=0;// 
a=0;//     .line 180
a=0;//     sget v1, Lcom/twocloo/com/cn/R$drawable;->newbookshelf_zhanghu_new_green:I
a=0;// 
a=0;//     invoke-virtual {p1, v2, v1, v2, v2}, Landroid/widget/CompoundButton;->setCompoundDrawablesWithIntrinsicBounds(IIII)V
a=0;// 
a=0;//     .line 191
a=0;//     :cond_d
a=0;//     :goto_3
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->rb_usercenter:Landroid/widget/RadioButton;
a=0;// 
a=0;//     #v1=(Reference,Landroid/widget/RadioButton;);
a=0;//     iget v2, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->fontColor:I
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     invoke-virtual {v1, v2}, Landroid/widget/RadioButton;->setTextColor(I)V
a=0;// 
a=0;//     .line 192
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->rb_bookcity:Landroid/widget/RadioButton;
a=0;// 
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/activitys/MainActivity;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     #v2=(Reference,Landroid/content/res/Resources;);
a=0;//     sget v3, Lcom/twocloo/com/cn/R$color;->usercenter_text:I
a=0;// 
a=0;//     #v3=(Integer);
a=0;//     invoke-virtual {v2, v3}, Landroid/content/res/Resources;->getColor(I)I
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     invoke-virtual {v1, v2}, Landroid/widget/RadioButton;->setTextColor(I)V
a=0;// 
a=0;//     .line 193
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->rb_bookshelf:Landroid/widget/RadioButton;
a=0;// 
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/activitys/MainActivity;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     #v2=(Reference,Landroid/content/res/Resources;);
a=0;//     sget v3, Lcom/twocloo/com/cn/R$color;->usercenter_text:I
a=0;// 
a=0;//     invoke-virtual {v2, v3}, Landroid/content/res/Resources;->getColor(I)I
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     invoke-virtual {v1, v2}, Landroid/widget/RadioButton;->setTextColor(I)V
a=0;// 
a=0;//     .line 194
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->rb_discover:Landroid/widget/RadioButton;
a=0;// 
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/activitys/MainActivity;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     #v2=(Reference,Landroid/content/res/Resources;);
a=0;//     sget v3, Lcom/twocloo/com/cn/R$color;->usercenter_text:I
a=0;// 
a=0;//     invoke-virtual {v2, v3}, Landroid/content/res/Resources;->getColor(I)I
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     invoke-virtual {v1, v2}, Landroid/widget/RadioButton;->setTextColor(I)V
a=0;// 
a=0;//     .line 195
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->rb_search:Landroid/widget/RadioButton;
a=0;// 
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/activitys/MainActivity;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     #v2=(Reference,Landroid/content/res/Resources;);
a=0;//     sget v3, Lcom/twocloo/com/cn/R$color;->usercenter_text:I
a=0;// 
a=0;//     invoke-virtual {v2, v3}, Landroid/content/res/Resources;->getColor(I)I
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     invoke-virtual {v1, v2}, Landroid/widget/RadioButton;->setTextColor(I)V
a=0;// 
a=0;//     .line 196
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->sm:Lcom/slidingmenu/lib/SlidingMenu;
a=0;// 
a=0;//     invoke-virtual {v1, v4}, Lcom/slidingmenu/lib/SlidingMenu;->setTouchModeAbove(I)V
a=0;// 
a=0;//     goto/16 :goto_1
a=0;// 
a=0;//     .line 182
a=0;//     :cond_e
a=0;//     #v1=(Integer);v2=(Null);v3=(One);
a=0;//     sget v1, Lcom/twocloo/com/cn/R$drawable;->newbookshelf_zhanghu_new_red:I
a=0;// 
a=0;//     invoke-virtual {p1, v2, v1, v2, v2}, Landroid/widget/CompoundButton;->setCompoundDrawablesWithIntrinsicBounds(IIII)V
a=0;// 
a=0;//     goto :goto_3
a=0;// 
a=0;//     .line 185
a=0;//     :cond_f
a=0;//     invoke-static {p0}, Lcom/twocloo/com/cn/common/LocalStore;->getMianTopBackgroundColor(Landroid/content/Context;)I
a=0;// 
a=0;//     move-result v1
a=0;// 
a=0;//     if-ne v1, v3, :cond_10
a=0;// 
a=0;//     .line 186
a=0;//     sget v1, Lcom/twocloo/com/cn/R$drawable;->newbookshelf_zhanghu_new_green:I
a=0;// 
a=0;//     invoke-virtual {p1, v2, v1, v2, v2}, Landroid/widget/CompoundButton;->setCompoundDrawablesWithIntrinsicBounds(IIII)V
a=0;// 
a=0;//     goto :goto_3
a=0;// 
a=0;//     .line 187
a=0;//     :cond_10
a=0;//     invoke-static {p0}, Lcom/twocloo/com/cn/common/LocalStore;->getMianTopBackgroundColor(Landroid/content/Context;)I
a=0;// 
a=0;//     move-result v1
a=0;// 
a=0;//     if-ne v1, v4, :cond_d
a=0;// 
a=0;//     .line 188
a=0;//     sget v1, Lcom/twocloo/com/cn/R$drawable;->newbookshelf_zhanghu_new_red:I
a=0;// 
a=0;//     invoke-virtual {p1, v2, v1, v2, v2}, Landroid/widget/CompoundButton;->setCompoundDrawablesWithIntrinsicBounds(IIII)V
a=0;// 
a=0;//     goto :goto_3
a=0;// 
a=0;//     .line 199
a=0;//     :cond_11
a=0;//     sget v1, Lcom/twocloo/com/cn/R$drawable;->newbookshelf_zhanghu_new:I
a=0;// 
a=0;//     invoke-virtual {p1, v2, v1, v2, v2}, Landroid/widget/CompoundButton;->setCompoundDrawablesWithIntrinsicBounds(IIII)V
a=0;// 
a=0;//     goto/16 :goto_1
a=0;// 
a=0;//     .line 202
a=0;//     :cond_12
a=0;//     sget v1, Lcom/twocloo/com/cn/R$id;->main_discover:I
a=0;// 
a=0;//     if-ne v0, v1, :cond_18
a=0;// 
a=0;//     .line 204
a=0;//     if-eqz p2, :cond_17
a=0;// 
a=0;//     .line 205
a=0;//     new-instance v1, Lcom/twocloo/com/cn/fragment/DiscoverFragment;
a=0;// 
a=0;//     #v1=(UninitRef,Lcom/twocloo/com/cn/fragment/DiscoverFragment;);
a=0;//     invoke-direct {v1}, Lcom/twocloo/com/cn/fragment/DiscoverFragment;-><init>()V
a=0;// 
a=0;//     #v1=(Reference,Lcom/twocloo/com/cn/fragment/DiscoverFragment;);
a=0;//     iput-object v1, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->curFragment:Landroid/support/v4/app/Fragment;
a=0;// 
a=0;//     .line 206
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->curFragment:Landroid/support/v4/app/Fragment;
a=0;// 
a=0;//     invoke-direct {p0, v1}, Lcom/twocloo/com/cn/activitys/MainActivity;->doOnCheckedChanged(Landroid/support/v4/app/Fragment;)V
a=0;// 
a=0;//     .line 207
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/activitys/MainActivity;->getApplicationContext()Landroid/content/Context;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-static {v1}, Lcom/twocloo/com/cn/common/LocalStore;->getFristInstall2(Landroid/content/Context;)I
a=0;// 
a=0;//     move-result v1
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     if-nez v1, :cond_15
a=0;// 
a=0;//     .line 208
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/activitys/MainActivity;->getApplicationContext()Landroid/content/Context;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     #v1=(Reference,Landroid/content/Context;);
a=0;//     invoke-static {v1}, Lcom/twocloo/com/cn/common/LocalStore;->getUserSex(Landroid/content/Context;)I
a=0;// 
a=0;//     move-result v1
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     if-ne v1, v3, :cond_14
a=0;// 
a=0;//     .line 209
a=0;//     sget v1, Lcom/twocloo/com/cn/R$drawable;->main_navigation_discover_green:I
a=0;// 
a=0;//     invoke-virtual {p1, v2, v1, v2, v2}, Landroid/widget/CompoundButton;->setCompoundDrawablesWithIntrinsicBounds(IIII)V
a=0;// 
a=0;//     .line 220
a=0;//     :cond_13
a=0;//     :goto_4
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->rb_discover:Landroid/widget/RadioButton;
a=0;// 
a=0;//     #v1=(Reference,Landroid/widget/RadioButton;);
a=0;//     iget v2, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->fontColor:I
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     invoke-virtual {v1, v2}, Landroid/widget/RadioButton;->setTextColor(I)V
a=0;// 
a=0;//     .line 221
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->rb_bookcity:Landroid/widget/RadioButton;
a=0;// 
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/activitys/MainActivity;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     #v2=(Reference,Landroid/content/res/Resources;);
a=0;//     sget v3, Lcom/twocloo/com/cn/R$color;->usercenter_text:I
a=0;// 
a=0;//     #v3=(Integer);
a=0;//     invoke-virtual {v2, v3}, Landroid/content/res/Resources;->getColor(I)I
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     invoke-virtual {v1, v2}, Landroid/widget/RadioButton;->setTextColor(I)V
a=0;// 
a=0;//     .line 222
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->rb_bookshelf:Landroid/widget/RadioButton;
a=0;// 
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/activitys/MainActivity;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     #v2=(Reference,Landroid/content/res/Resources;);
a=0;//     sget v3, Lcom/twocloo/com/cn/R$color;->usercenter_text:I
a=0;// 
a=0;//     invoke-virtual {v2, v3}, Landroid/content/res/Resources;->getColor(I)I
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     invoke-virtual {v1, v2}, Landroid/widget/RadioButton;->setTextColor(I)V
a=0;// 
a=0;//     .line 223
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->rb_usercenter:Landroid/widget/RadioButton;
a=0;// 
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/activitys/MainActivity;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     #v2=(Reference,Landroid/content/res/Resources;);
a=0;//     sget v3, Lcom/twocloo/com/cn/R$color;->usercenter_text:I
a=0;// 
a=0;//     invoke-virtual {v2, v3}, Landroid/content/res/Resources;->getColor(I)I
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     invoke-virtual {v1, v2}, Landroid/widget/RadioButton;->setTextColor(I)V
a=0;// 
a=0;//     .line 224
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->rb_search:Landroid/widget/RadioButton;
a=0;// 
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/activitys/MainActivity;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     #v2=(Reference,Landroid/content/res/Resources;);
a=0;//     sget v3, Lcom/twocloo/com/cn/R$color;->usercenter_text:I
a=0;// 
a=0;//     invoke-virtual {v2, v3}, Landroid/content/res/Resources;->getColor(I)I
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     invoke-virtual {v1, v2}, Landroid/widget/RadioButton;->setTextColor(I)V
a=0;// 
a=0;//     .line 225
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->sm:Lcom/slidingmenu/lib/SlidingMenu;
a=0;// 
a=0;//     invoke-virtual {v1, v4}, Lcom/slidingmenu/lib/SlidingMenu;->setTouchModeAbove(I)V
a=0;// 
a=0;//     goto/16 :goto_1
a=0;// 
a=0;//     .line 211
a=0;//     :cond_14
a=0;//     #v1=(Integer);v2=(Null);v3=(One);
a=0;//     sget v1, Lcom/twocloo/com/cn/R$drawable;->main_navigation_discover_red:I
a=0;// 
a=0;//     invoke-virtual {p1, v2, v1, v2, v2}, Landroid/widget/CompoundButton;->setCompoundDrawablesWithIntrinsicBounds(IIII)V
a=0;// 
a=0;//     goto :goto_4
a=0;// 
a=0;//     .line 214
a=0;//     :cond_15
a=0;//     invoke-static {p0}, Lcom/twocloo/com/cn/common/LocalStore;->getMianTopBackgroundColor(Landroid/content/Context;)I
a=0;// 
a=0;//     move-result v1
a=0;// 
a=0;//     if-ne v1, v3, :cond_16
a=0;// 
a=0;//     .line 215
a=0;//     sget v1, Lcom/twocloo/com/cn/R$drawable;->main_navigation_discover_green:I
a=0;// 
a=0;//     invoke-virtual {p1, v2, v1, v2, v2}, Landroid/widget/CompoundButton;->setCompoundDrawablesWithIntrinsicBounds(IIII)V
a=0;// 
a=0;//     goto :goto_4
a=0;// 
a=0;//     .line 216
a=0;//     :cond_16
a=0;//     invoke-static {p0}, Lcom/twocloo/com/cn/common/LocalStore;->getMianTopBackgroundColor(Landroid/content/Context;)I
a=0;// 
a=0;//     move-result v1
a=0;// 
a=0;//     if-ne v1, v4, :cond_13
a=0;// 
a=0;//     .line 217
a=0;//     sget v1, Lcom/twocloo/com/cn/R$drawable;->main_navigation_discover_red:I
a=0;// 
a=0;//     invoke-virtual {p1, v2, v1, v2, v2}, Landroid/widget/CompoundButton;->setCompoundDrawablesWithIntrinsicBounds(IIII)V
a=0;// 
a=0;//     goto :goto_4
a=0;// 
a=0;//     .line 228
a=0;//     :cond_17
a=0;//     sget v1, Lcom/twocloo/com/cn/R$drawable;->main_navigation_discover:I
a=0;// 
a=0;//     invoke-virtual {p1, v2, v1, v2, v2}, Landroid/widget/CompoundButton;->setCompoundDrawablesWithIntrinsicBounds(IIII)V
a=0;// 
a=0;//     goto/16 :goto_1
a=0;// 
a=0;//     .line 230
a=0;//     :cond_18
a=0;//     sget v1, Lcom/twocloo/com/cn/R$id;->main_search:I
a=0;// 
a=0;//     if-ne v0, v1, :cond_1
a=0;// 
a=0;//     .line 231
a=0;//     if-eqz p2, :cond_1d
a=0;// 
a=0;//     .line 232
a=0;//     new-instance v1, Lcom/twocloo/com/cn/fragment/SearchFragment;
a=0;// 
a=0;//     #v1=(UninitRef,Lcom/twocloo/com/cn/fragment/SearchFragment;);
a=0;//     invoke-direct {v1}, Lcom/twocloo/com/cn/fragment/SearchFragment;-><init>()V
a=0;// 
a=0;//     #v1=(Reference,Lcom/twocloo/com/cn/fragment/SearchFragment;);
a=0;//     iput-object v1, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->curFragment:Landroid/support/v4/app/Fragment;
a=0;// 
a=0;//     .line 233
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->curFragment:Landroid/support/v4/app/Fragment;
a=0;// 
a=0;//     invoke-direct {p0, v1}, Lcom/twocloo/com/cn/activitys/MainActivity;->doOnCheckedChanged(Landroid/support/v4/app/Fragment;)V
a=0;// 
a=0;//     .line 234
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/activitys/MainActivity;->getApplicationContext()Landroid/content/Context;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-static {v1}, Lcom/twocloo/com/cn/common/LocalStore;->getFristInstall2(Landroid/content/Context;)I
a=0;// 
a=0;//     move-result v1
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     if-nez v1, :cond_1b
a=0;// 
a=0;//     .line 235
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/activitys/MainActivity;->getApplicationContext()Landroid/content/Context;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     #v1=(Reference,Landroid/content/Context;);
a=0;//     invoke-static {v1}, Lcom/twocloo/com/cn/common/LocalStore;->getUserSex(Landroid/content/Context;)I
a=0;// 
a=0;//     move-result v1
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     if-ne v1, v3, :cond_1a
a=0;// 
a=0;//     .line 236
a=0;//     sget v1, Lcom/twocloo/com/cn/R$drawable;->main_navigation_search_normal_green:I
a=0;// 
a=0;//     invoke-virtual {p1, v2, v1, v2, v2}, Landroid/widget/CompoundButton;->setCompoundDrawablesWithIntrinsicBounds(IIII)V
a=0;// 
a=0;//     .line 248
a=0;//     :cond_19
a=0;//     :goto_5
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->rb_search:Landroid/widget/RadioButton;
a=0;// 
a=0;//     #v1=(Reference,Landroid/widget/RadioButton;);
a=0;//     iget v2, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->fontColor:I
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     invoke-virtual {v1, v2}, Landroid/widget/RadioButton;->setTextColor(I)V
a=0;// 
a=0;//     .line 249
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->rb_discover:Landroid/widget/RadioButton;
a=0;// 
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/activitys/MainActivity;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     #v2=(Reference,Landroid/content/res/Resources;);
a=0;//     sget v3, Lcom/twocloo/com/cn/R$color;->usercenter_text:I
a=0;// 
a=0;//     #v3=(Integer);
a=0;//     invoke-virtual {v2, v3}, Landroid/content/res/Resources;->getColor(I)I
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     invoke-virtual {v1, v2}, Landroid/widget/RadioButton;->setTextColor(I)V
a=0;// 
a=0;//     .line 250
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->rb_bookcity:Landroid/widget/RadioButton;
a=0;// 
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/activitys/MainActivity;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     #v2=(Reference,Landroid/content/res/Resources;);
a=0;//     sget v3, Lcom/twocloo/com/cn/R$color;->usercenter_text:I
a=0;// 
a=0;//     invoke-virtual {v2, v3}, Landroid/content/res/Resources;->getColor(I)I
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     invoke-virtual {v1, v2}, Landroid/widget/RadioButton;->setTextColor(I)V
a=0;// 
a=0;//     .line 251
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->rb_bookshelf:Landroid/widget/RadioButton;
a=0;// 
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/activitys/MainActivity;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     #v2=(Reference,Landroid/content/res/Resources;);
a=0;//     sget v3, Lcom/twocloo/com/cn/R$color;->usercenter_text:I
a=0;// 
a=0;//     invoke-virtual {v2, v3}, Landroid/content/res/Resources;->getColor(I)I
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     invoke-virtual {v1, v2}, Landroid/widget/RadioButton;->setTextColor(I)V
a=0;// 
a=0;//     .line 252
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->rb_usercenter:Landroid/widget/RadioButton;
a=0;// 
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/activitys/MainActivity;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     #v2=(Reference,Landroid/content/res/Resources;);
a=0;//     sget v3, Lcom/twocloo/com/cn/R$color;->usercenter_text:I
a=0;// 
a=0;//     invoke-virtual {v2, v3}, Landroid/content/res/Resources;->getColor(I)I
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     invoke-virtual {v1, v2}, Landroid/widget/RadioButton;->setTextColor(I)V
a=0;// 
a=0;//     .line 253
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->sm:Lcom/slidingmenu/lib/SlidingMenu;
a=0;// 
a=0;//     invoke-virtual {v1, v4}, Lcom/slidingmenu/lib/SlidingMenu;->setTouchModeAbove(I)V
a=0;// 
a=0;//     goto/16 :goto_1
a=0;// 
a=0;//     .line 238
a=0;//     :cond_1a
a=0;//     #v1=(Integer);v2=(Null);v3=(One);
a=0;//     sget v1, Lcom/twocloo/com/cn/R$drawable;->main_navigation_search_normal_red:I
a=0;// 
a=0;//     invoke-virtual {p1, v2, v1, v2, v2}, Landroid/widget/CompoundButton;->setCompoundDrawablesWithIntrinsicBounds(IIII)V
a=0;// 
a=0;//     goto :goto_5
a=0;// 
a=0;//     .line 241
a=0;//     :cond_1b
a=0;//     invoke-static {p0}, Lcom/twocloo/com/cn/common/LocalStore;->getMianTopBackgroundColor(Landroid/content/Context;)I
a=0;// 
a=0;//     move-result v1
a=0;// 
a=0;//     if-ne v1, v3, :cond_1c
a=0;// 
a=0;//     .line 242
a=0;//     sget v1, Lcom/twocloo/com/cn/R$drawable;->main_navigation_search_normal_green:I
a=0;// 
a=0;//     invoke-virtual {p1, v2, v1, v2, v2}, Landroid/widget/CompoundButton;->setCompoundDrawablesWithIntrinsicBounds(IIII)V
a=0;// 
a=0;//     goto :goto_5
a=0;// 
a=0;//     .line 243
a=0;//     :cond_1c
a=0;//     invoke-static {p0}, Lcom/twocloo/com/cn/common/LocalStore;->getMianTopBackgroundColor(Landroid/content/Context;)I
a=0;// 
a=0;//     move-result v1
a=0;// 
a=0;//     if-ne v1, v4, :cond_19
a=0;// 
a=0;//     .line 244
a=0;//     sget v1, Lcom/twocloo/com/cn/R$drawable;->main_navigation_search_normal_red:I
a=0;// 
a=0;//     invoke-virtual {p1, v2, v1, v2, v2}, Landroid/widget/CompoundButton;->setCompoundDrawablesWithIntrinsicBounds(IIII)V
a=0;// 
a=0;//     goto :goto_5
a=0;// 
a=0;//     .line 256
a=0;//     :cond_1d
a=0;//     sget v1, Lcom/twocloo/com/cn/R$drawable;->main_navigation_search_normal:I
a=0;// 
a=0;//     invoke-virtual {p1, v2, v1, v2, v2}, Landroid/widget/CompoundButton;->setCompoundDrawablesWithIntrinsicBounds(IIII)V
a=0;// 
a=0;//     goto/16 :goto_1
a=0;// .end method
a=0;// 
a=0;// .method public onClosed()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 385
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public onCreate(Landroid/os/Bundle;)V
a=0;//     .locals 2
a=0;//     .param p1, "savedInstanceState"    # Landroid/os/Bundle;
a=0;// 
a=0;//     .prologue
a=0;//     .line 55
a=0;//     invoke-super {p0, p1}, Lcom/slidingmenu/lib/app/SlidingFragmentActivity;->onCreate(Landroid/os/Bundle;)V
a=0;// 
a=0;//     .line 57
a=0;//     const/4 v1, 0x1
a=0;// 
a=0;//     #v1=(One);
a=0;//     invoke-virtual {p0, v1}, Lcom/twocloo/com/cn/activitys/MainActivity;->requestWindowFeature(I)Z
a=0;// 
a=0;//     .line 58
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/activitys/MainActivity;->setFontColor()V
a=0;// 
a=0;//     .line 59
a=0;//     sget v1, Lcom/twocloo/com/cn/R$style;->Theme_Sherlock:I
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     invoke-virtual {p0, v1}, Lcom/twocloo/com/cn/activitys/MainActivity;->setTheme(I)V
a=0;// 
a=0;//     .line 60
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/activitys/MainActivity;->getSupportActionBar()Lcom/actionbarsherlock/app/ActionBar;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 61
a=0;//     .local v0, "actionBar":Lcom/actionbarsherlock/app/ActionBar;
a=0;//     #v0=(Reference,Lcom/actionbarsherlock/app/ActionBar;);
a=0;//     if-eqz v0, :cond_0
a=0;// 
a=0;//     .line 62
a=0;//     invoke-virtual {v0}, Lcom/actionbarsherlock/app/ActionBar;->hide()V
a=0;// 
a=0;//     .line 64
a=0;//     :cond_0
a=0;//     sget v1, Lcom/twocloo/com/cn/R$layout;->main:I
a=0;// 
a=0;//     invoke-virtual {p0, v1}, Lcom/twocloo/com/cn/activitys/MainActivity;->setContentView(I)V
a=0;// 
a=0;//     .line 66
a=0;//     sget v1, Lcom/twocloo/com/cn/R$layout;->main_sliding_menu:I
a=0;// 
a=0;//     invoke-virtual {p0, v1}, Lcom/twocloo/com/cn/activitys/MainActivity;->setBehindContentView(I)V
a=0;// 
a=0;//     .line 67
a=0;//     invoke-static {p0}, Lcom/twocloo/com/cn/common/CloseActivity;->add(Landroid/app/Activity;)V
a=0;// 
a=0;//     .line 69
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/activitys/MainActivity;->getSlidingMenu()Lcom/slidingmenu/lib/SlidingMenu;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     #v1=(Reference,Lcom/slidingmenu/lib/SlidingMenu;);
a=0;//     iput-object v1, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->sm:Lcom/slidingmenu/lib/SlidingMenu;
a=0;// 
a=0;//     .line 71
a=0;//     invoke-direct {p0}, Lcom/twocloo/com/cn/activitys/MainActivity;->initView()V
a=0;// 
a=0;//     .line 73
a=0;//     invoke-direct {p0}, Lcom/twocloo/com/cn/activitys/MainActivity;->initTabs()V
a=0;// 
a=0;//     .line 75
a=0;//     invoke-direct {p0}, Lcom/twocloo/com/cn/activitys/MainActivity;->initDrawerMenu()V
a=0;// 
a=0;//     .line 85
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method protected onDestroy()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 102
a=0;//     invoke-static {p0}, Lcom/twocloo/com/cn/common/CloseActivity;->remove(Landroid/app/Activity;)V
a=0;// 
a=0;//     .line 104
a=0;//     invoke-super {p0}, Lcom/slidingmenu/lib/app/SlidingFragmentActivity;->onDestroy()V
a=0;// 
a=0;//     .line 105
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public onOpened()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 379
a=0;//     invoke-direct {p0}, Lcom/twocloo/com/cn/activitys/MainActivity;->loadSecondData()V
a=0;// 
a=0;//     .line 381
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method protected onPause()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 96
a=0;//     invoke-static {p0}, Lcom/umeng/analytics/MobclickAgent;->onPause(Landroid/content/Context;)V
a=0;// 
a=0;//     .line 97
a=0;//     invoke-super {p0}, Lcom/slidingmenu/lib/app/SlidingFragmentActivity;->onPause()V
a=0;// 
a=0;//     .line 98
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method protected onResume()V
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 88
a=0;//     invoke-static {p0}, Lcom/umeng/analytics/MobclickAgent;->onResume(Landroid/content/Context;)V
a=0;// 
a=0;//     .line 89
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->bottom_menu_layout:Landroid/widget/LinearLayout;
a=0;// 
a=0;//     #v0=(Reference,Landroid/widget/LinearLayout;);
a=0;//     invoke-static {p0, v0}, Lcom/twocloo/com/cn/utils/CommonUtils;->setBackgroundByDayOrNightWithDrawable(Landroid/app/Activity;Landroid/view/View;)V
a=0;// 
a=0;//     .line 90
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/activitys/MainActivity;->setFontColor()V
a=0;// 
a=0;//     .line 91
a=0;//     invoke-super {p0}, Lcom/slidingmenu/lib/app/SlidingFragmentActivity;->onResume()V
a=0;// 
a=0;//     .line 92
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public openSlidingMenu(Landroid/view/View;)V
a=0;//     .locals 0
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 373
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/activitys/MainActivity;->toggle()V
a=0;// 
a=0;//     .line 374
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setFontColor()V
a=0;//     .locals 5
a=0;// 
a=0;//     .prologue
a=0;//     const/4 v4, 0x1
a=0;// 
a=0;//     #v4=(One);
a=0;//     const v3, -0x178e74
a=0;// 
a=0;//     #v3=(Integer);
a=0;//     const v2, -0xc44d6a
a=0;// 
a=0;//     .line 414
a=0;//     #v2=(Integer);
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/activitys/MainActivity;->getApplicationContext()Landroid/content/Context;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     #v1=(Reference,Landroid/content/Context;);
a=0;//     invoke-static {v1}, Lcom/twocloo/com/cn/common/LocalStore;->getFristInstall2(Landroid/content/Context;)I
a=0;// 
a=0;//     move-result v1
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     if-nez v1, :cond_2
a=0;// 
a=0;//     .line 415
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/activitys/MainActivity;->getApplicationContext()Landroid/content/Context;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     #v1=(Reference,Landroid/content/Context;);
a=0;//     invoke-static {v1}, Lcom/twocloo/com/cn/common/LocalStore;->getUserSex(Landroid/content/Context;)I
a=0;// 
a=0;//     move-result v1
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     if-ne v1, v4, :cond_1
a=0;// 
a=0;//     .line 416
a=0;//     iput v2, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->fontColor:I
a=0;// 
a=0;//     .line 429
a=0;//     :cond_0
a=0;//     :goto_0
a=0;//     #v0=(Conflicted);v1=(Conflicted);
a=0;//     return-void
a=0;// 
a=0;//     .line 418
a=0;//     :cond_1
a=0;//     #v0=(Uninit);v1=(Integer);
a=0;//     iput v3, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->fontColor:I
a=0;// 
a=0;//     goto :goto_0
a=0;// 
a=0;//     .line 421
a=0;//     :cond_2
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/activitys/MainActivity;->getApplicationContext()Landroid/content/Context;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     #v1=(Reference,Landroid/content/Context;);
a=0;//     invoke-static {v1}, Lcom/twocloo/com/cn/common/LocalStore;->getMianTopBackgroundColor(Landroid/content/Context;)I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     .line 422
a=0;//     .local v0, "color":I
a=0;//     #v0=(Integer);
a=0;//     if-ne v0, v4, :cond_3
a=0;// 
a=0;//     .line 423
a=0;//     iput v2, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->fontColor:I
a=0;// 
a=0;//     goto :goto_0
a=0;// 
a=0;//     .line 424
a=0;//     :cond_3
a=0;//     const/4 v1, 0x2
a=0;// 
a=0;//     #v1=(PosByte);
a=0;//     if-ne v0, v1, :cond_0
a=0;// 
a=0;//     .line 425
a=0;//     iput v3, p0, Lcom/twocloo/com/cn/activitys/MainActivity;->fontColor:I
a=0;// 
a=0;//     goto :goto_0
a=0;// .end method
}}
