package com.twocloo.com.cn.activitys; class MuLuActivity$4 { void a() { int a;
a=0;// .class Lcom/twocloo/com/cn/activitys/MuLuActivity$4;
a=0;// .super Ljava/lang/Object;
a=0;// .source "MuLuActivity.java"
a=0;// 
a=0;// # interfaces
a=0;// .implements Landroid/widget/AdapterView$OnItemClickListener;
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation system Ldalvik/annotation/EnclosingMethod;
a=0;//     value = Lcom/twocloo/com/cn/activitys/MuLuActivity;->onCreate(Landroid/os/Bundle;)V
a=0;// .end annotation
a=0;// 
a=0;// .annotation system Ldalvik/annotation/InnerClass;
a=0;//     accessFlags = 0x0
a=0;//     name = null
a=0;// .end annotation
a=0;// 
a=0;// .annotation system Ldalvik/annotation/Signature;
a=0;//     value = {
a=0;//         "Ljava/lang/Object;",
a=0;//         "Landroid/widget/AdapterView$OnItemClickListener;"
a=0;//     }
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field final synthetic this$0:Lcom/twocloo/com/cn/activitys/MuLuActivity;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>(Lcom/twocloo/com/cn/activitys/MuLuActivity;)V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 1
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/activitys/MuLuActivity$4;->this$0:Lcom/twocloo/com/cn/activitys/MuLuActivity;
a=0;// 
a=0;//     .line 106
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcom/twocloo/com/cn/activitys/MuLuActivity$4;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public onItemClick(Landroid/widget/AdapterView;Landroid/view/View;IJ)V
a=0;//     .locals 9
a=0;//     .param p2, "arg1"    # Landroid/view/View;
a=0;//     .param p3, "arg2"    # I
a=0;//     .param p4, "arg3"    # J
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "(",
a=0;//             "Landroid/widget/AdapterView",
a=0;//             "<*>;",
a=0;//             "Landroid/view/View;",
a=0;//             "IJ)V"
a=0;//         }
a=0;//     .end annotation
a=0;// 
a=0;//     .prologue
a=0;//     .local p1, "arg0":Landroid/widget/AdapterView;, "Landroid/widget/AdapterView<*>;"
a=0;//     const/high16 v4, 0x4000000
a=0;// 
a=0;//     #v4=(Integer);
a=0;//     const/4 v2, 0x1
a=0;// 
a=0;//     #v2=(One);
a=0;//     const/4 v3, 0x0
a=0;// 
a=0;//     .line 109
a=0;//     #v3=(Null);
a=0;//     invoke-static {}, Lcom/twocloo/com/cn/activitys/BookApp;->getUser()Lcom/twocloo/com/cn/beans/User;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/beans/User;);
a=0;//     if-eqz v0, :cond_0
a=0;// 
a=0;//     invoke-static {}, Lcom/twocloo/com/cn/activitys/BookApp;->getUser()Lcom/twocloo/com/cn/beans/User;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Lcom/twocloo/com/cn/beans/User;->getUid()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-static {v0}, Landroid/text/TextUtils;->isEmpty(Ljava/lang/CharSequence;)Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     if-nez v0, :cond_0
a=0;// 
a=0;//     .line 110
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/MuLuActivity$4;->this$0:Lcom/twocloo/com/cn/activitys/MuLuActivity;
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/activitys/MuLuActivity;);
a=0;//     invoke-static {}, Lcom/twocloo/com/cn/activitys/BookApp;->getUser()Lcom/twocloo/com/cn/beans/User;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     #v1=(Reference,Lcom/twocloo/com/cn/beans/User;);
a=0;//     invoke-virtual {v1}, Lcom/twocloo/com/cn/beans/User;->getUid()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-static {v0, v1}, Lcom/twocloo/com/cn/activitys/MuLuActivity;->access$8(Lcom/twocloo/com/cn/activitys/MuLuActivity;Ljava/lang/String;)V
a=0;// 
a=0;//     .line 112
a=0;//     :cond_0
a=0;//     #v0=(Conflicted);v1=(Conflicted);
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/MuLuActivity$4;->this$0:Lcom/twocloo/com/cn/activitys/MuLuActivity;
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/activitys/MuLuActivity;);
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/MuLuActivity;->access$3(Lcom/twocloo/com/cn/activitys/MuLuActivity;)Ljava/util/ArrayList;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0, p3}, Ljava/util/ArrayList;->get(I)Ljava/lang/Object;
a=0;// 
a=0;//     move-result-object v7
a=0;// 
a=0;//     #v7=(Reference,Ljava/lang/Object;);
a=0;//     check-cast v7, Lcom/twocloo/com/cn/beans/Chapterinfo;
a=0;// 
a=0;//     .line 114
a=0;//     .local v7, "cp":Lcom/twocloo/com/cn/beans/Chapterinfo;
a=0;//     if-eqz v7, :cond_2
a=0;// 
a=0;//     invoke-virtual {v7}, Lcom/twocloo/com/cn/beans/Chapterinfo;->getIs_vip()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     if-ne v0, v2, :cond_2
a=0;// 
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/MuLuActivity$4;->this$0:Lcom/twocloo/com/cn/activitys/MuLuActivity;
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/activitys/MuLuActivity;);
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/MuLuActivity;->access$1(Lcom/twocloo/com/cn/activitys/MuLuActivity;)Lcom/twocloo/com/cn/threads/SubedchaptersinfoThread;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     if-nez v0, :cond_2
a=0;// 
a=0;//     .line 115
a=0;//     invoke-static {}, Lcom/twocloo/com/cn/activitys/BookApp;->getUser()Lcom/twocloo/com/cn/beans/User;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     if-nez v0, :cond_1
a=0;// 
a=0;//     .line 117
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/MuLuActivity$4;->this$0:Lcom/twocloo/com/cn/activitys/MuLuActivity;
a=0;// 
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/MuLuActivity$4;->this$0:Lcom/twocloo/com/cn/activitys/MuLuActivity;
a=0;// 
a=0;//     #v1=(Reference,Lcom/twocloo/com/cn/activitys/MuLuActivity;);
a=0;//     invoke-static {v1}, Lcom/twocloo/com/cn/activitys/MuLuActivity;->access$15(Lcom/twocloo/com/cn/activitys/MuLuActivity;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-static {v0, v1}, Lcom/twocloo/com/cn/utils/CommonUtils;->goToLogin(Landroid/app/Activity;Ljava/lang/String;)V
a=0;// 
a=0;//     .line 118
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/MuLuActivity$4;->this$0:Lcom/twocloo/com/cn/activitys/MuLuActivity;
a=0;// 
a=0;//     const-string v1, "\u8bf7\u5148\u767b\u5f55"
a=0;// 
a=0;//     invoke-static {v0, v1, v3}, Lcom/twocloo/base/util/ViewUtils;->toastOnUI(Landroid/app/Activity;Ljava/lang/String;I)V
a=0;// 
a=0;//     .line 159
a=0;//     :cond_1
a=0;//     :goto_0
a=0;//     #v1=(Conflicted);v2=(Conflicted);v3=(Reference,Ljava/lang/String;);v5=(Conflicted);v6=(Conflicted);v8=(Conflicted);
a=0;//     return-void
a=0;// 
a=0;//     .line 121
a=0;//     :cond_2
a=0;//     #v0=(Conflicted);v2=(One);v3=(Null);v5=(Uninit);v6=(Uninit);v8=(Uninit);
a=0;//     if-eqz v7, :cond_4
a=0;// 
a=0;//     invoke-virtual {v7}, Lcom/twocloo/com/cn/beans/Chapterinfo;->getIs_vip()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     if-ne v0, v2, :cond_4
a=0;// 
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/MuLuActivity$4;->this$0:Lcom/twocloo/com/cn/activitys/MuLuActivity;
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/activitys/MuLuActivity;);
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/MuLuActivity;->access$1(Lcom/twocloo/com/cn/activitys/MuLuActivity;)Lcom/twocloo/com/cn/threads/SubedchaptersinfoThread;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     if-eqz v0, :cond_4
a=0;// 
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/MuLuActivity$4;->this$0:Lcom/twocloo/com/cn/activitys/MuLuActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/MuLuActivity;->access$1(Lcom/twocloo/com/cn/activitys/MuLuActivity;)Lcom/twocloo/com/cn/threads/SubedchaptersinfoThread;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v0, v0, Lcom/twocloo/com/cn/threads/SubedchaptersinfoThread;->scif:Lcom/twocloo/com/cn/beans/Subed_chapters_info;
a=0;// 
a=0;//     if-eqz v0, :cond_4
a=0;// 
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/MuLuActivity$4;->this$0:Lcom/twocloo/com/cn/activitys/MuLuActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/MuLuActivity;->access$1(Lcom/twocloo/com/cn/activitys/MuLuActivity;)Lcom/twocloo/com/cn/threads/SubedchaptersinfoThread;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v0, v0, Lcom/twocloo/com/cn/threads/SubedchaptersinfoThread;->scif:Lcom/twocloo/com/cn/beans/Subed_chapters_info;
a=0;// 
a=0;//     invoke-virtual {v0}, Lcom/twocloo/com/cn/beans/Subed_chapters_info;->getSubed_textid_list()Ljava/util/HashSet;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v7}, Lcom/twocloo/com/cn/beans/Chapterinfo;->getId()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v1}, Ljava/util/HashSet;->contains(Ljava/lang/Object;)Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     if-nez v0, :cond_4
a=0;// 
a=0;//     .line 122
a=0;//     invoke-static {}, Lcom/twocloo/com/cn/activitys/BookApp;->getUser()Lcom/twocloo/com/cn/beans/User;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/beans/User;);
a=0;//     if-nez v0, :cond_3
a=0;// 
a=0;//     .line 124
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/MuLuActivity$4;->this$0:Lcom/twocloo/com/cn/activitys/MuLuActivity;
a=0;// 
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/MuLuActivity$4;->this$0:Lcom/twocloo/com/cn/activitys/MuLuActivity;
a=0;// 
a=0;//     invoke-static {v1}, Lcom/twocloo/com/cn/activitys/MuLuActivity;->access$15(Lcom/twocloo/com/cn/activitys/MuLuActivity;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-static {v0, v1}, Lcom/twocloo/com/cn/utils/CommonUtils;->goToLogin(Landroid/app/Activity;Ljava/lang/String;)V
a=0;// 
a=0;//     goto :goto_0
a=0;// 
a=0;//     .line 127
a=0;//     :cond_3
a=0;//     new-instance v0, Lcom/twocloo/com/cn/view/VipChapterOrder;
a=0;// 
a=0;//     #v0=(UninitRef,Lcom/twocloo/com/cn/view/VipChapterOrder;);
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/MuLuActivity$4;->this$0:Lcom/twocloo/com/cn/activitys/MuLuActivity;
a=0;// 
a=0;//     invoke-static {v1}, Lcom/twocloo/com/cn/activitys/MuLuActivity;->access$12(Lcom/twocloo/com/cn/activitys/MuLuActivity;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/MuLuActivity$4;->this$0:Lcom/twocloo/com/cn/activitys/MuLuActivity;
a=0;// 
a=0;//     #v2=(Reference,Lcom/twocloo/com/cn/activitys/MuLuActivity;);
a=0;//     invoke-static {v2}, Lcom/twocloo/com/cn/activitys/MuLuActivity;->access$11(Lcom/twocloo/com/cn/activitys/MuLuActivity;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-virtual {v7}, Lcom/twocloo/com/cn/beans/Chapterinfo;->getId()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     #v3=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v7}, Lcom/twocloo/com/cn/beans/Chapterinfo;->getIs_vip()I
a=0;// 
a=0;//     move-result v4
a=0;// 
a=0;//     iget-object v5, p0, Lcom/twocloo/com/cn/activitys/MuLuActivity$4;->this$0:Lcom/twocloo/com/cn/activitys/MuLuActivity;
a=0;// 
a=0;//     #v5=(Reference,Lcom/twocloo/com/cn/activitys/MuLuActivity;);
a=0;//     iget-object v6, p0, Lcom/twocloo/com/cn/activitys/MuLuActivity$4;->this$0:Lcom/twocloo/com/cn/activitys/MuLuActivity;
a=0;// 
a=0;//     #v6=(Reference,Lcom/twocloo/com/cn/activitys/MuLuActivity;);
a=0;//     invoke-static {v6}, Lcom/twocloo/com/cn/activitys/MuLuActivity;->access$10(Lcom/twocloo/com/cn/activitys/MuLuActivity;)Landroid/os/Handler;
a=0;// 
a=0;//     move-result-object v6
a=0;// 
a=0;//     invoke-direct/range {v0 .. v6}, Lcom/twocloo/com/cn/view/VipChapterOrder;-><init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILandroid/app/Activity;Landroid/os/Handler;)V
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/view/VipChapterOrder;);
a=0;//     goto :goto_0
a=0;// 
a=0;//     .line 130
a=0;//     :cond_4
a=0;//     #v0=(Conflicted);v1=(Conflicted);v2=(One);v3=(Null);v5=(Uninit);v6=(Uninit);
a=0;//     const-string v0, "single"
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/MuLuActivity$4;->this$0:Lcom/twocloo/com/cn/activitys/MuLuActivity;
a=0;// 
a=0;//     #v1=(Reference,Lcom/twocloo/com/cn/activitys/MuLuActivity;);
a=0;//     invoke-virtual {v1}, Lcom/twocloo/com/cn/activitys/MuLuActivity;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     sget v2, Lcom/twocloo/com/cn/R$string;->apptype:I
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     invoke-virtual {v1, v2}, Landroid/content/res/Resources;->getString(I)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/String;->equals(Ljava/lang/Object;)Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     if-eqz v0, :cond_5
a=0;// 
a=0;//     invoke-virtual {v7}, Lcom/twocloo/com/cn/beans/Chapterinfo;->getIs_vip()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     if-nez v0, :cond_5
a=0;// 
a=0;//     invoke-virtual {v7}, Lcom/twocloo/com/cn/beans/Chapterinfo;->getLen()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     if-nez v0, :cond_6
a=0;// 
a=0;//     .line 131
a=0;//     :cond_5
a=0;//     const-string v0, "client"
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/MuLuActivity$4;->this$0:Lcom/twocloo/com/cn/activitys/MuLuActivity;
a=0;// 
a=0;//     invoke-virtual {v1}, Lcom/twocloo/com/cn/activitys/MuLuActivity;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     sget v2, Lcom/twocloo/com/cn/R$string;->apptype:I
a=0;// 
a=0;//     invoke-virtual {v1, v2}, Landroid/content/res/Resources;->getString(I)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/String;->equals(Ljava/lang/Object;)Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     if-eqz v0, :cond_7
a=0;// 
a=0;//     invoke-virtual {v7}, Lcom/twocloo/com/cn/beans/Chapterinfo;->getIs_vip()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     if-nez v0, :cond_7
a=0;// 
a=0;//     invoke-virtual {v7}, Lcom/twocloo/com/cn/beans/Chapterinfo;->getLen()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     if-eqz v0, :cond_7
a=0;// 
a=0;//     .line 134
a=0;//     :cond_6
a=0;//     new-instance v8, Landroid/content/Intent;
a=0;// 
a=0;//     #v8=(UninitRef,Landroid/content/Intent;);
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/MuLuActivity$4;->this$0:Lcom/twocloo/com/cn/activitys/MuLuActivity;
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/activitys/MuLuActivity;);
a=0;//     const-class v1, Lcom/twocloo/com/cn/activitys/ReadbookDown;
a=0;// 
a=0;//     invoke-direct {v8, v0, v1}, Landroid/content/Intent;-><init>(Landroid/content/Context;Ljava/lang/Class;)V
a=0;// 
a=0;//     .line 135
a=0;//     .local v8, "intent":Landroid/content/Intent;
a=0;//     #v8=(Reference,Landroid/content/Intent;);
a=0;//     const-string v0, "bookFile"
a=0;// 
a=0;//     new-instance v1, Ljava/lang/StringBuilder;
a=0;// 
a=0;//     #v1=(UninitRef,Ljava/lang/StringBuilder;);
a=0;//     invoke-static {}, Landroid/os/Environment;->getExternalStorageDirectory()Ljava/io/File;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     #v2=(Reference,Ljava/io/File;);
a=0;//     invoke-virtual {v2}, Ljava/io/File;->getAbsolutePath()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-static {v2}, Ljava/lang/String;->valueOf(Ljava/lang/Object;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-direct {v1, v2}, Ljava/lang/StringBuilder;-><init>(Ljava/lang/String;)V
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/StringBuilder;);
a=0;//     const-string v2, "/2cloo/downBook/"
a=0;// 
a=0;//     invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/MuLuActivity$4;->this$0:Lcom/twocloo/com/cn/activitys/MuLuActivity;
a=0;// 
a=0;//     invoke-static {v2}, Lcom/twocloo/com/cn/activitys/MuLuActivity;->access$11(Lcom/twocloo/com/cn/activitys/MuLuActivity;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     .line 136
a=0;//     const-string v2, "/"
a=0;// 
a=0;//     invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     const-string v2, "book_text_"
a=0;// 
a=0;//     invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/MuLuActivity$4;->this$0:Lcom/twocloo/com/cn/activitys/MuLuActivity;
a=0;// 
a=0;//     invoke-static {v2}, Lcom/twocloo/com/cn/activitys/MuLuActivity;->access$11(Lcom/twocloo/com/cn/activitys/MuLuActivity;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     const-string v2, ".txt"
a=0;// 
a=0;//     invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v1}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     .line 135
a=0;//     invoke-virtual {v8, v0, v1}, Landroid/content/Intent;->putExtra(Ljava/lang/String;Ljava/lang/String;)Landroid/content/Intent;
a=0;// 
a=0;//     .line 137
a=0;//     const-string v0, "finishFlag"
a=0;// 
a=0;//     invoke-virtual {v8, v0, v3}, Landroid/content/Intent;->putExtra(Ljava/lang/String;I)Landroid/content/Intent;
a=0;// 
a=0;//     .line 138
a=0;//     const-string v0, "aid"
a=0;// 
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/MuLuActivity$4;->this$0:Lcom/twocloo/com/cn/activitys/MuLuActivity;
a=0;// 
a=0;//     invoke-static {v1}, Lcom/twocloo/com/cn/activitys/MuLuActivity;->access$11(Lcom/twocloo/com/cn/activitys/MuLuActivity;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v8, v0, v1}, Landroid/content/Intent;->putExtra(Ljava/lang/String;Ljava/lang/String;)Landroid/content/Intent;
a=0;// 
a=0;//     .line 139
a=0;//     const-string v0, "textid"
a=0;// 
a=0;//     invoke-virtual {v7}, Lcom/twocloo/com/cn/beans/Chapterinfo;->getId()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v8, v0, v1}, Landroid/content/Intent;->putExtra(Ljava/lang/String;Ljava/lang/String;)Landroid/content/Intent;
a=0;// 
a=0;//     .line 143
a=0;//     invoke-virtual {v8, v4}, Landroid/content/Intent;->setFlags(I)Landroid/content/Intent;
a=0;// 
a=0;//     .line 144
a=0;//     invoke-static {}, Lcom/twocloo/com/cn/common/CloseActivity;->closeRd()V
a=0;// 
a=0;//     .line 145
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/MuLuActivity$4;->this$0:Lcom/twocloo/com/cn/activitys/MuLuActivity;
a=0;// 
a=0;//     invoke-virtual {v0, v8}, Lcom/twocloo/com/cn/activitys/MuLuActivity;->startActivity(Landroid/content/Intent;)V
a=0;// 
a=0;//     .line 146
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/MuLuActivity$4;->this$0:Lcom/twocloo/com/cn/activitys/MuLuActivity;
a=0;// 
a=0;//     invoke-virtual {v0}, Lcom/twocloo/com/cn/activitys/MuLuActivity;->finish()V
a=0;// 
a=0;//     goto/16 :goto_0
a=0;// 
a=0;//     .line 148
a=0;//     .end local v8    # "intent":Landroid/content/Intent;
a=0;//     :cond_7
a=0;//     #v0=(Integer);v2=(Integer);v8=(Uninit);
a=0;//     new-instance v8, Landroid/content/Intent;
a=0;// 
a=0;//     #v8=(UninitRef,Landroid/content/Intent;);
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/MuLuActivity$4;->this$0:Lcom/twocloo/com/cn/activitys/MuLuActivity;
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/activitys/MuLuActivity;);
a=0;//     const-class v1, Lcom/twocloo/com/cn/activitys/Readbook;
a=0;// 
a=0;//     invoke-direct {v8, v0, v1}, Landroid/content/Intent;-><init>(Landroid/content/Context;Ljava/lang/Class;)V
a=0;// 
a=0;//     .line 149
a=0;//     .restart local v8    # "intent":Landroid/content/Intent;
a=0;//     #v8=(Reference,Landroid/content/Intent;);
a=0;//     const-string v0, "textid"
a=0;// 
a=0;//     invoke-virtual {v7}, Lcom/twocloo/com/cn/beans/Chapterinfo;->getId()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v8, v0, v1}, Landroid/content/Intent;->putExtra(Ljava/lang/String;Ljava/lang/String;)Landroid/content/Intent;
a=0;// 
a=0;//     .line 150
a=0;//     const-string v0, "aid"
a=0;// 
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/MuLuActivity$4;->this$0:Lcom/twocloo/com/cn/activitys/MuLuActivity;
a=0;// 
a=0;//     invoke-static {v1}, Lcom/twocloo/com/cn/activitys/MuLuActivity;->access$11(Lcom/twocloo/com/cn/activitys/MuLuActivity;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v8, v0, v1}, Landroid/content/Intent;->putExtra(Ljava/lang/String;Ljava/lang/String;)Landroid/content/Intent;
a=0;// 
a=0;//     .line 151
a=0;//     const-string v0, "isVip"
a=0;// 
a=0;//     invoke-virtual {v7}, Lcom/twocloo/com/cn/beans/Chapterinfo;->getIs_vip()I
a=0;// 
a=0;//     move-result v1
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     invoke-virtual {v8, v0, v1}, Landroid/content/Intent;->putExtra(Ljava/lang/String;I)Landroid/content/Intent;
a=0;// 
a=0;//     .line 152
a=0;//     invoke-virtual {v8, v4}, Landroid/content/Intent;->setFlags(I)Landroid/content/Intent;
a=0;// 
a=0;//     .line 153
a=0;//     invoke-static {}, Lcom/twocloo/com/cn/common/CloseActivity;->closeReadBookDown()V
a=0;// 
a=0;//     .line 154
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/MuLuActivity$4;->this$0:Lcom/twocloo/com/cn/activitys/MuLuActivity;
a=0;// 
a=0;//     invoke-virtual {v0, v8}, Lcom/twocloo/com/cn/activitys/MuLuActivity;->startActivity(Landroid/content/Intent;)V
a=0;// 
a=0;//     .line 155
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/MuLuActivity$4;->this$0:Lcom/twocloo/com/cn/activitys/MuLuActivity;
a=0;// 
a=0;//     invoke-virtual {v0}, Lcom/twocloo/com/cn/activitys/MuLuActivity;->finish()V
a=0;// 
a=0;//     goto/16 :goto_0
a=0;// .end method
}}
