package com.twocloo.com.cn.activitys; class NovelDetailedActivity$1 { void a() { int a;
a=0;// .class Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;
a=0;// .super Landroid/os/Handler;
a=0;// .source "NovelDetailedActivity.java"
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation system Ldalvik/annotation/EnclosingClass;
a=0;//     value = Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// .end annotation
a=0;// 
a=0;// .annotation system Ldalvik/annotation/InnerClass;
a=0;//     accessFlags = 0x0
a=0;//     name = null
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field final synthetic this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 1
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     .line 223
a=0;//     invoke-direct {p0}, Landroid/os/Handler;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method static synthetic access$0(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;)Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 223
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public handleMessage(Landroid/os/Message;)V
a=0;//     .locals 9
a=0;//     .param p1, "msg"    # Landroid/os/Message;
a=0;// 
a=0;//     .prologue
a=0;//     const/4 v8, 0x3
a=0;// 
a=0;//     #v8=(PosByte);
a=0;//     const/4 v2, 0x2
a=0;// 
a=0;//     #v2=(PosByte);
a=0;//     const/4 v5, 0x1
a=0;// 
a=0;//     #v5=(One);
a=0;//     const/16 v3, 0x8
a=0;// 
a=0;//     #v3=(PosByte);
a=0;//     const/4 v4, 0x0
a=0;// 
a=0;//     .line 226
a=0;//     #v4=(Null);
a=0;//     iget v0, p1, Landroid/os/Message;->what:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     sparse-switch v0, :sswitch_data_0
a=0;// 
a=0;//     .line 425
a=0;//     :cond_0
a=0;//     :goto_0
a=0;//     #v0=(Conflicted);v1=(Conflicted);v2=(Conflicted);v3=(Conflicted);v4=(Reference,Ljava/lang/String;);v5=(Conflicted);v6=(Conflicted);v7=(Conflicted);v8=(Conflicted);
a=0;//     return-void
a=0;// 
a=0;//     .line 228
a=0;//     :sswitch_0
a=0;//     #v0=(Integer);v1=(Uninit);v2=(PosByte);v3=(PosByte);v4=(Null);v5=(One);v6=(Uninit);v7=(Uninit);v8=(PosByte);
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;);
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$0(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/app/ProgressDialog;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     if-eqz v0, :cond_0
a=0;// 
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$0(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/app/ProgressDialog;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Landroid/app/ProgressDialog;->isShowing()Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     if-eqz v0, :cond_0
a=0;// 
a=0;//     .line 229
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;);
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$0(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/app/ProgressDialog;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Landroid/app/ProgressDialog;->cancel()V
a=0;// 
a=0;//     goto :goto_0
a=0;// 
a=0;//     .line 232
a=0;//     :sswitch_1
a=0;//     #v0=(Integer);
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;);
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$1(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Ljava/util/HashSet;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Ljava/util/HashSet;->clear()V
a=0;// 
a=0;//     .line 233
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$2(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Lcom/twocloo/com/cn/threads/SubedchaptersinfoThread;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     if-eqz v0, :cond_1
a=0;// 
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$2(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Lcom/twocloo/com/cn/threads/SubedchaptersinfoThread;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v0, v0, Lcom/twocloo/com/cn/threads/SubedchaptersinfoThread;->scif:Lcom/twocloo/com/cn/beans/Subed_chapters_info;
a=0;// 
a=0;//     if-eqz v0, :cond_1
a=0;// 
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$2(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Lcom/twocloo/com/cn/threads/SubedchaptersinfoThread;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v0, v0, Lcom/twocloo/com/cn/threads/SubedchaptersinfoThread;->scif:Lcom/twocloo/com/cn/beans/Subed_chapters_info;
a=0;// 
a=0;//     invoke-virtual {v0}, Lcom/twocloo/com/cn/beans/Subed_chapters_info;->getSubed_textid_list()Ljava/util/HashSet;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     if-eqz v0, :cond_1
a=0;// 
a=0;//     .line 234
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$1(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Ljava/util/HashSet;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     #v1=(Reference,Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;);
a=0;//     invoke-static {v1}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$2(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Lcom/twocloo/com/cn/threads/SubedchaptersinfoThread;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     iget-object v1, v1, Lcom/twocloo/com/cn/threads/SubedchaptersinfoThread;->scif:Lcom/twocloo/com/cn/beans/Subed_chapters_info;
a=0;// 
a=0;//     invoke-virtual {v1}, Lcom/twocloo/com/cn/beans/Subed_chapters_info;->getSubed_textid_list()Ljava/util/HashSet;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/util/HashSet;->addAll(Ljava/util/Collection;)Z
a=0;// 
a=0;//     .line 236
a=0;//     :cond_1
a=0;//     #v1=(Conflicted);
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$3(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Lcom/twocloo/com/cn/adapters/AdapterForLinearLayout;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     if-eqz v0, :cond_0
a=0;// 
a=0;//     .line 237
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$3(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Lcom/twocloo/com/cn/adapters/AdapterForLinearLayout;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Lcom/twocloo/com/cn/adapters/AdapterForLinearLayout;->notifyDataSetChanged()V
a=0;// 
a=0;//     goto :goto_0
a=0;// 
a=0;//     .line 243
a=0;//     :sswitch_2
a=0;//     #v0=(Integer);v1=(Uninit);
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;);
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$4(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Lcom/twocloo/com/cn/threads/ShubenxinxiyeThread;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     if-eqz v0, :cond_0
a=0;// 
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$4(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Lcom/twocloo/com/cn/threads/ShubenxinxiyeThread;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v0, v0, Lcom/twocloo/com/cn/threads/ShubenxinxiyeThread;->sbxxy:Lcom/twocloo/com/cn/beans/Shubenxinxiye;
a=0;// 
a=0;//     if-eqz v0, :cond_0
a=0;// 
a=0;//     .line 246
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     #v1=(Reference,Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;);
a=0;//     invoke-static {v1}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$4(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Lcom/twocloo/com/cn/threads/ShubenxinxiyeThread;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     iget-object v1, v1, Lcom/twocloo/com/cn/threads/ShubenxinxiyeThread;->sbxxy:Lcom/twocloo/com/cn/beans/Shubenxinxiye;
a=0;// 
a=0;//     invoke-virtual {v1}, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->getTitle()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-static {v0, v1}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$5(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;Ljava/lang/String;)V
a=0;// 
a=0;//     .line 247
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$6(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/TextView;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v1}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$7(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Landroid/widget/TextView;->setText(Ljava/lang/CharSequence;)V
a=0;// 
a=0;//     .line 248
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$6(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/TextView;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-virtual {v1}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     sget v2, Lcom/twocloo/com/cn/R$color;->white:I
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     invoke-virtual {v1, v2}, Landroid/content/res/Resources;->getColor(I)I
a=0;// 
a=0;//     move-result v1
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     invoke-virtual {v0, v1}, Landroid/widget/TextView;->setTextColor(I)V
a=0;// 
a=0;//     .line 249
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$8(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/TextView;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     #v1=(Reference,Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;);
a=0;//     invoke-static {v1}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$4(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Lcom/twocloo/com/cn/threads/ShubenxinxiyeThread;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     iget-object v1, v1, Lcom/twocloo/com/cn/threads/ShubenxinxiyeThread;->sbxxy:Lcom/twocloo/com/cn/beans/Shubenxinxiye;
a=0;// 
a=0;//     invoke-virtual {v1}, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->getAuthor()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Landroid/widget/TextView;->setText(Ljava/lang/CharSequence;)V
a=0;// 
a=0;//     .line 250
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$9(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/TextView;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v1}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$4(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Lcom/twocloo/com/cn/threads/ShubenxinxiyeThread;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     iget-object v1, v1, Lcom/twocloo/com/cn/threads/ShubenxinxiyeThread;->sbxxy:Lcom/twocloo/com/cn/beans/Shubenxinxiye;
a=0;// 
a=0;//     invoke-virtual {v1}, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->getSortname()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Landroid/widget/TextView;->setText(Ljava/lang/CharSequence;)V
a=0;// 
a=0;//     .line 251
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$10(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/TextView;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v1}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$4(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Lcom/twocloo/com/cn/threads/ShubenxinxiyeThread;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     iget-object v1, v1, Lcom/twocloo/com/cn/threads/ShubenxinxiyeThread;->sbxxy:Lcom/twocloo/com/cn/beans/Shubenxinxiye;
a=0;// 
a=0;//     invoke-virtual {v1}, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->getWordtotal()I
a=0;// 
a=0;//     move-result v1
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     invoke-static {v1}, Lcom/twocloo/com/cn/utils/OtherUtils;->transferCount(I)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v1}, Landroid/widget/TextView;->setText(Ljava/lang/CharSequence;)V
a=0;// 
a=0;//     .line 252
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$11(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/TextView;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v1}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$4(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Lcom/twocloo/com/cn/threads/ShubenxinxiyeThread;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     iget-object v1, v1, Lcom/twocloo/com/cn/threads/ShubenxinxiyeThread;->sbxxy:Lcom/twocloo/com/cn/beans/Shubenxinxiye;
a=0;// 
a=0;//     invoke-virtual {v1}, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->getChapter_title()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Landroid/widget/TextView;->setText(Ljava/lang/CharSequence;)V
a=0;// 
a=0;//     .line 253
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$12(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/TextView;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v1}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$4(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Lcom/twocloo/com/cn/threads/ShubenxinxiyeThread;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     iget-object v1, v1, Lcom/twocloo/com/cn/threads/ShubenxinxiyeThread;->sbxxy:Lcom/twocloo/com/cn/beans/Shubenxinxiye;
a=0;// 
a=0;//     invoke-virtual {v1}, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->getUpdate_time()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Landroid/widget/TextView;->setText(Ljava/lang/CharSequence;)V
a=0;// 
a=0;//     .line 254
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$13(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/TextView;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$4(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Lcom/twocloo/com/cn/threads/ShubenxinxiyeThread;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v0, v0, Lcom/twocloo/com/cn/threads/ShubenxinxiyeThread;->sbxxy:Lcom/twocloo/com/cn/beans/Shubenxinxiye;
a=0;// 
a=0;//     invoke-virtual {v0}, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->getBaoyueStatue()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     if-ne v0, v5, :cond_5
a=0;// 
a=0;//     const-string v0, "\u5305\u6708\u4f5c\u54c1"
a=0;// 
a=0;//     :goto_1
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v1, v0}, Landroid/widget/TextView;->setText(Ljava/lang/CharSequence;)V
a=0;// 
a=0;//     .line 255
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v1}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$4(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Lcom/twocloo/com/cn/threads/ShubenxinxiyeThread;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     iget-object v1, v1, Lcom/twocloo/com/cn/threads/ShubenxinxiyeThread;->sbxxy:Lcom/twocloo/com/cn/beans/Shubenxinxiye;
a=0;// 
a=0;//     invoke-virtual {v1}, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->getUpdate_time()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-static {v0, v1}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$14(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v7
a=0;// 
a=0;//     .line 256
a=0;//     .local v7, "updateTime":Ljava/lang/String;
a=0;//     #v7=(Reference,Ljava/lang/String;);
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$4(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Lcom/twocloo/com/cn/threads/ShubenxinxiyeThread;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v0, v0, Lcom/twocloo/com/cn/threads/ShubenxinxiyeThread;->sbxxy:Lcom/twocloo/com/cn/beans/Shubenxinxiye;
a=0;// 
a=0;//     invoke-virtual {v0}, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->getUpdate_str()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v6
a=0;// 
a=0;//     .line 258
a=0;//     .local v6, "updateStr":Ljava/lang/String;
a=0;//     #v6=(Reference,Ljava/lang/String;);
a=0;//     invoke-static {v7}, Landroid/text/TextUtils;->isEmpty(Ljava/lang/CharSequence;)Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     if-eqz v0, :cond_6
a=0;// 
a=0;//     .line 259
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;);
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$12(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/TextView;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0, v3}, Landroid/widget/TextView;->setVisibility(I)V
a=0;// 
a=0;//     .line 260
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$15(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/TextView;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0, v3}, Landroid/widget/TextView;->setVisibility(I)V
a=0;// 
a=0;//     .line 266
a=0;//     :goto_2
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v1}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$4(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Lcom/twocloo/com/cn/threads/ShubenxinxiyeThread;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     iget-object v1, v1, Lcom/twocloo/com/cn/threads/ShubenxinxiyeThread;->sbxxy:Lcom/twocloo/com/cn/beans/Shubenxinxiye;
a=0;// 
a=0;//     invoke-virtual {v1}, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->getHasfavor()I
a=0;// 
a=0;//     move-result v1
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     invoke-static {v0, v1}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$16(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;I)V
a=0;// 
a=0;//     .line 267
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     #v1=(Reference,Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;);
a=0;//     invoke-static {v1}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$4(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Lcom/twocloo/com/cn/threads/ShubenxinxiyeThread;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     iget-object v1, v1, Lcom/twocloo/com/cn/threads/ShubenxinxiyeThread;->sbxxy:Lcom/twocloo/com/cn/beans/Shubenxinxiye;
a=0;// 
a=0;//     invoke-virtual {v1}, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->getHasrecommend()I
a=0;// 
a=0;//     move-result v1
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     invoke-static {v0, v1}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$17(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;I)V
a=0;// 
a=0;//     .line 268
a=0;//     new-instance v0, Ljava/lang/StringBuilder;
a=0;// 
a=0;//     #v0=(UninitRef,Ljava/lang/StringBuilder;);
a=0;//     invoke-direct {v0}, Ljava/lang/StringBuilder;-><init>()V
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/StringBuilder;);
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     #v1=(Reference,Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;);
a=0;//     invoke-static {v1}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$18(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)I
a=0;// 
a=0;//     move-result v1
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-static {v0}, Landroid/text/TextUtils;->isEmpty(Ljava/lang/CharSequence;)Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     if-nez v0, :cond_2
a=0;// 
a=0;//     .line 275
a=0;//     :cond_2
a=0;//     new-instance v0, Ljava/lang/StringBuilder;
a=0;// 
a=0;//     #v0=(UninitRef,Ljava/lang/StringBuilder;);
a=0;//     invoke-direct {v0}, Ljava/lang/StringBuilder;-><init>()V
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/StringBuilder;);
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     #v1=(Reference,Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;);
a=0;//     invoke-static {v1}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$19(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)I
a=0;// 
a=0;//     move-result v1
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-static {v0}, Landroid/text/TextUtils;->isEmpty(Ljava/lang/CharSequence;)Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     if-nez v0, :cond_3
a=0;// 
a=0;//     .line 282
a=0;//     :cond_3
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;);
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     #v1=(Reference,Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;);
a=0;//     invoke-static {v1}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$4(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Lcom/twocloo/com/cn/threads/ShubenxinxiyeThread;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     iget-object v1, v1, Lcom/twocloo/com/cn/threads/ShubenxinxiyeThread;->sbxxy:Lcom/twocloo/com/cn/beans/Shubenxinxiye;
a=0;// 
a=0;//     invoke-virtual {v1}, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->getAuthorid()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-static {v0, v1}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$20(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;Ljava/lang/String;)V
a=0;// 
a=0;//     .line 283
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v1}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$4(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Lcom/twocloo/com/cn/threads/ShubenxinxiyeThread;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     iget-object v1, v1, Lcom/twocloo/com/cn/threads/ShubenxinxiyeThread;->sbxxy:Lcom/twocloo/com/cn/beans/Shubenxinxiye;
a=0;// 
a=0;//     invoke-virtual {v1}, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->getAuthor()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-static {v0, v1}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$21(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;Ljava/lang/String;)V
a=0;// 
a=0;//     .line 284
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$22(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/TextView;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v1}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$4(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Lcom/twocloo/com/cn/threads/ShubenxinxiyeThread;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     iget-object v1, v1, Lcom/twocloo/com/cn/threads/ShubenxinxiyeThread;->sbxxy:Lcom/twocloo/com/cn/beans/Shubenxinxiye;
a=0;// 
a=0;//     invoke-virtual {v1}, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->getTotalviews()I
a=0;// 
a=0;//     move-result v1
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     invoke-static {v1}, Lcom/twocloo/com/cn/utils/OtherUtils;->transferCount(I)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v1}, Landroid/widget/TextView;->setText(Ljava/lang/CharSequence;)V
a=0;// 
a=0;//     .line 285
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$23(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/TextView;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     new-instance v1, Ljava/lang/StringBuilder;
a=0;// 
a=0;//     #v1=(UninitRef,Ljava/lang/StringBuilder;);
a=0;//     const-string v2, "("
a=0;// 
a=0;//     #v2=(Reference,Ljava/lang/String;);
a=0;//     invoke-direct {v1, v2}, Ljava/lang/StringBuilder;-><init>(Ljava/lang/String;)V
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/StringBuilder;);
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v2}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$4(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Lcom/twocloo/com/cn/threads/ShubenxinxiyeThread;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/threads/ShubenxinxiyeThread;->sbxxy:Lcom/twocloo/com/cn/beans/Shubenxinxiye;
a=0;// 
a=0;//     invoke-virtual {v2}, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->getVoters()I
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     invoke-static {v2}, Lcom/twocloo/com/cn/utils/OtherUtils;->transferCount(I)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     #v2=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     const-string v2, ")"
a=0;// 
a=0;//     invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v1}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Landroid/widget/TextView;->setText(Ljava/lang/CharSequence;)V
a=0;// 
a=0;//     .line 286
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$24(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/TextView;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     new-instance v1, Ljava/lang/StringBuilder;
a=0;// 
a=0;//     #v1=(UninitRef,Ljava/lang/StringBuilder;);
a=0;//     const-string v2, "("
a=0;// 
a=0;//     invoke-direct {v1, v2}, Ljava/lang/StringBuilder;-><init>(Ljava/lang/String;)V
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/StringBuilder;);
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v2}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$4(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Lcom/twocloo/com/cn/threads/ShubenxinxiyeThread;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/threads/ShubenxinxiyeThread;->sbxxy:Lcom/twocloo/com/cn/beans/Shubenxinxiye;
a=0;// 
a=0;//     invoke-virtual {v2}, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->getDashang()I
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     invoke-static {v2}, Lcom/twocloo/com/cn/utils/OtherUtils;->transferCount(I)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     #v2=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     const-string v2, ")"
a=0;// 
a=0;//     invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v1}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Landroid/widget/TextView;->setText(Ljava/lang/CharSequence;)V
a=0;// 
a=0;//     .line 287
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$4(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Lcom/twocloo/com/cn/threads/ShubenxinxiyeThread;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v0, v0, Lcom/twocloo/com/cn/threads/ShubenxinxiyeThread;->sbxxy:Lcom/twocloo/com/cn/beans/Shubenxinxiye;
a=0;// 
a=0;//     invoke-virtual {v0}, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->getDescription()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     if-eqz v0, :cond_4
a=0;// 
a=0;//     .line 288
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$4(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Lcom/twocloo/com/cn/threads/ShubenxinxiyeThread;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v0, v0, Lcom/twocloo/com/cn/threads/ShubenxinxiyeThread;->sbxxy:Lcom/twocloo/com/cn/beans/Shubenxinxiye;
a=0;// 
a=0;//     invoke-virtual {v0}, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->getDescription()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Ljava/lang/String;->length()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     const/16 v1, 0x64
a=0;// 
a=0;//     #v1=(PosByte);
a=0;//     if-le v0, v1, :cond_7
a=0;// 
a=0;//     .line 289
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;);
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$25(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/Button;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0, v4}, Landroid/widget/Button;->setVisibility(I)V
a=0;// 
a=0;//     .line 290
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$26(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/TextView;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     new-instance v1, Ljava/lang/StringBuilder;
a=0;// 
a=0;//     #v1=(UninitRef,Ljava/lang/StringBuilder;);
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v2}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$4(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Lcom/twocloo/com/cn/threads/ShubenxinxiyeThread;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     iget-object v2, v2, Lcom/twocloo/com/cn/threads/ShubenxinxiyeThread;->sbxxy:Lcom/twocloo/com/cn/beans/Shubenxinxiye;
a=0;// 
a=0;//     invoke-virtual {v2}, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->getDescription()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     const/16 v3, 0x64
a=0;// 
a=0;//     invoke-virtual {v2, v4, v3}, Ljava/lang/String;->substring(II)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-static {v2}, Ljava/lang/String;->valueOf(Ljava/lang/Object;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-direct {v1, v2}, Ljava/lang/StringBuilder;-><init>(Ljava/lang/String;)V
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/StringBuilder;);
a=0;//     const-string v2, "..."
a=0;// 
a=0;//     invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v1}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Landroid/widget/TextView;->setText(Ljava/lang/CharSequence;)V
a=0;// 
a=0;//     .line 296
a=0;//     :cond_4
a=0;//     :goto_3
a=0;//     new-instance v0, Ljava/lang/Thread;
a=0;// 
a=0;//     #v0=(UninitRef,Ljava/lang/Thread;);
a=0;//     new-instance v1, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1$1;
a=0;// 
a=0;//     #v1=(UninitRef,Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1$1;);
a=0;//     invoke-direct {v1, p0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1$1;-><init>(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;)V
a=0;// 
a=0;//     #v1=(Reference,Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1$1;);
a=0;//     invoke-direct {v0, v1}, Ljava/lang/Thread;-><init>(Ljava/lang/Runnable;)V
a=0;// 
a=0;//     .line 322
a=0;//     #v0=(Reference,Ljava/lang/Thread;);
a=0;//     invoke-virtual {v0}, Ljava/lang/Thread;->start()V
a=0;// 
a=0;//     .line 323
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$27(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/os/Handler;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0, v4}, Landroid/os/Handler;->sendEmptyMessage(I)Z
a=0;// 
a=0;//     goto/16 :goto_0
a=0;// 
a=0;//     .line 254
a=0;//     .end local v6    # "updateStr":Ljava/lang/String;
a=0;//     .end local v7    # "updateTime":Ljava/lang/String;
a=0;//     :cond_5
a=0;//     #v0=(Integer);v2=(Integer);v6=(Uninit);v7=(Uninit);
a=0;//     const-string v0, "\u975e\u5305\u6708\u4f5c\u54c1"
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     goto/16 :goto_1
a=0;// 
a=0;//     .line 262
a=0;//     .restart local v6    # "updateStr":Ljava/lang/String;
a=0;//     .restart local v7    # "updateTime":Ljava/lang/String;
a=0;//     :cond_6
a=0;//     #v0=(Boolean);v6=(Reference,Ljava/lang/String;);v7=(Reference,Ljava/lang/String;);
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;);
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$12(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/TextView;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0, v4}, Landroid/widget/TextView;->setVisibility(I)V
a=0;// 
a=0;//     .line 263
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$15(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/TextView;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0, v4}, Landroid/widget/TextView;->setVisibility(I)V
a=0;// 
a=0;//     .line 264
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$12(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/TextView;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0, v7}, Landroid/widget/TextView;->setText(Ljava/lang/CharSequence;)V
a=0;// 
a=0;//     goto/16 :goto_2
a=0;// 
a=0;//     .line 292
a=0;//     :cond_7
a=0;//     #v0=(Integer);v1=(PosByte);v2=(Reference,Ljava/lang/String;);
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;);
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$26(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/TextView;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     #v1=(Reference,Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;);
a=0;//     invoke-static {v1}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$4(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Lcom/twocloo/com/cn/threads/ShubenxinxiyeThread;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     iget-object v1, v1, Lcom/twocloo/com/cn/threads/ShubenxinxiyeThread;->sbxxy:Lcom/twocloo/com/cn/beans/Shubenxinxiye;
a=0;// 
a=0;//     invoke-virtual {v1}, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->getDescription()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Landroid/widget/TextView;->setText(Ljava/lang/CharSequence;)V
a=0;// 
a=0;//     .line 293
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$25(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/Button;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0, v3}, Landroid/widget/Button;->setVisibility(I)V
a=0;// 
a=0;//     goto :goto_3
a=0;// 
a=0;//     .line 326
a=0;//     .end local v6    # "updateStr":Ljava/lang/String;
a=0;//     .end local v7    # "updateTime":Ljava/lang/String;
a=0;//     :sswitch_3
a=0;//     #v0=(Integer);v1=(Uninit);v2=(PosByte);v6=(Uninit);v7=(Uninit);
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;);
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$29(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Lcom/twocloo/com/cn/threads/ShupingThread;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v0, v0, Lcom/twocloo/com/cn/threads/ShupingThread;->spif:Lcom/twocloo/com/cn/beans/Shupinginfo;
a=0;// 
a=0;//     if-eqz v0, :cond_0
a=0;// 
a=0;//     .line 328
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     #v1=(Reference,Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;);
a=0;//     invoke-static {v1}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$29(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Lcom/twocloo/com/cn/threads/ShupingThread;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     iget-object v1, v1, Lcom/twocloo/com/cn/threads/ShupingThread;->spif:Lcom/twocloo/com/cn/beans/Shupinginfo;
a=0;// 
a=0;//     invoke-virtual {v1}, Lcom/twocloo/com/cn/beans/Shupinginfo;->getSPlist()Ljava/util/ArrayList;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-static {v0, v1}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$30(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;Ljava/util/ArrayList;)V
a=0;// 
a=0;//     .line 329
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$31(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Ljava/util/ArrayList;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Ljava/util/ArrayList;->size()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     if-nez v0, :cond_8
a=0;// 
a=0;//     .line 330
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;);
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$32(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/RelativeLayout;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0, v4}, Landroid/widget/RelativeLayout;->setVisibility(I)V
a=0;// 
a=0;//     .line 331
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$33(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/LinearLayout;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0, v3}, Landroid/widget/LinearLayout;->setVisibility(I)V
a=0;// 
a=0;//     goto/16 :goto_0
a=0;// 
a=0;//     .line 334
a=0;//     :cond_8
a=0;//     #v0=(Integer);
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;);
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$32(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/RelativeLayout;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0, v3}, Landroid/widget/RelativeLayout;->setVisibility(I)V
a=0;// 
a=0;//     .line 335
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$33(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/LinearLayout;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0, v4}, Landroid/widget/LinearLayout;->setVisibility(I)V
a=0;// 
a=0;//     .line 336
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-virtual {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->initPinglun()V
a=0;// 
a=0;//     goto/16 :goto_0
a=0;// 
a=0;//     .line 341
a=0;//     :sswitch_4
a=0;//     #v0=(Integer);v1=(Uninit);
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;);
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$29(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Lcom/twocloo/com/cn/threads/ShupingThread;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v0, v0, Lcom/twocloo/com/cn/threads/ShupingThread;->spif:Lcom/twocloo/com/cn/beans/Shupinginfo;
a=0;// 
a=0;//     if-eqz v0, :cond_0
a=0;// 
a=0;//     .line 343
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     #v1=(Reference,Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;);
a=0;//     invoke-static {v1}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$29(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Lcom/twocloo/com/cn/threads/ShupingThread;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     iget-object v1, v1, Lcom/twocloo/com/cn/threads/ShupingThread;->spif:Lcom/twocloo/com/cn/beans/Shupinginfo;
a=0;// 
a=0;//     invoke-virtual {v1}, Lcom/twocloo/com/cn/beans/Shupinginfo;->getSPlist()Ljava/util/ArrayList;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-static {v0, v1}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$30(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;Ljava/util/ArrayList;)V
a=0;// 
a=0;//     .line 344
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$31(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Ljava/util/ArrayList;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Ljava/util/ArrayList;->size()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     if-nez v0, :cond_9
a=0;// 
a=0;//     .line 345
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;);
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$32(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/RelativeLayout;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0, v4}, Landroid/widget/RelativeLayout;->setVisibility(I)V
a=0;// 
a=0;//     .line 346
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$33(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/LinearLayout;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0, v3}, Landroid/widget/LinearLayout;->setVisibility(I)V
a=0;// 
a=0;//     goto/16 :goto_0
a=0;// 
a=0;//     .line 349
a=0;//     :cond_9
a=0;//     #v0=(Integer);
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;);
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$32(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/RelativeLayout;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0, v3}, Landroid/widget/RelativeLayout;->setVisibility(I)V
a=0;// 
a=0;//     .line 350
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$33(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/LinearLayout;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0, v4}, Landroid/widget/LinearLayout;->setVisibility(I)V
a=0;// 
a=0;//     .line 351
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-virtual {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->initPinglun()V
a=0;// 
a=0;//     goto/16 :goto_0
a=0;// 
a=0;//     .line 356
a=0;//     :sswitch_5
a=0;//     #v0=(Integer);v1=(Uninit);
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     #v1=(Reference,Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;);
a=0;//     iget-object v0, p1, Landroid/os/Message;->obj:Ljava/lang/Object;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/Object;);
a=0;//     check-cast v0, Ljava/util/ArrayList;
a=0;// 
a=0;//     invoke-static {v1, v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$34(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;Ljava/util/ArrayList;)V
a=0;// 
a=0;//     .line 357
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$35(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Ljava/util/ArrayList;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Ljava/util/ArrayList;->size()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     if-lez v0, :cond_a
a=0;// 
a=0;//     .line 358
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;);
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$36(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)V
a=0;// 
a=0;//     goto/16 :goto_0
a=0;// 
a=0;//     .line 360
a=0;//     :cond_a
a=0;//     #v0=(Integer);
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;);
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$37(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/HorizontalScrollView;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0, v3}, Landroid/widget/HorizontalScrollView;->setVisibility(I)V
a=0;// 
a=0;//     .line 361
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$38(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/Button;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0, v3}, Landroid/widget/Button;->setVisibility(I)V
a=0;// 
a=0;//     goto/16 :goto_0
a=0;// 
a=0;//     .line 366
a=0;//     :sswitch_6
a=0;//     #v0=(Integer);v1=(Uninit);
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     #v1=(Reference,Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;);
a=0;//     iget-object v0, p1, Landroid/os/Message;->obj:Ljava/lang/Object;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/Object;);
a=0;//     check-cast v0, Ljava/util/ArrayList;
a=0;// 
a=0;//     invoke-static {v1, v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$39(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;Ljava/util/ArrayList;)V
a=0;// 
a=0;//     .line 367
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$40(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Ljava/util/ArrayList;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Ljava/util/ArrayList;->size()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     if-lez v0, :cond_b
a=0;// 
a=0;//     .line 368
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;);
a=0;//     new-instance v1, Lcom/twocloo/com/cn/adapters/AdapterForMulu;
a=0;// 
a=0;//     #v1=(UninitRef,Lcom/twocloo/com/cn/adapters/AdapterForMulu;);
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     #v2=(Reference,Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;);
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     #v3=(Reference,Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;);
a=0;//     invoke-static {v3}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$40(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Ljava/util/ArrayList;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     #v4=(Reference,Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;);
a=0;//     invoke-static {v4}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$41(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     iget-object v5, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     #v5=(Reference,Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;);
a=0;//     invoke-static {v5}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$1(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Ljava/util/HashSet;
a=0;// 
a=0;//     move-result-object v5
a=0;// 
a=0;//     invoke-direct {v1, v2, v3, v4, v5}, Lcom/twocloo/com/cn/adapters/AdapterForMulu;-><init>(Landroid/app/Activity;Ljava/util/ArrayList;Ljava/lang/String;Ljava/util/HashSet;)V
a=0;// 
a=0;//     #v1=(Reference,Lcom/twocloo/com/cn/adapters/AdapterForMulu;);
a=0;//     invoke-static {v0, v1}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$42(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;Lcom/twocloo/com/cn/adapters/AdapterForMulu;)V
a=0;// 
a=0;//     .line 369
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$43(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Lcom/twocloo/com/cn/view/MyListView;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v1}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$44(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Lcom/twocloo/com/cn/adapters/AdapterForMulu;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Lcom/twocloo/com/cn/view/MyListView;->setAdapter(Landroid/widget/BaseAdapter;)V
a=0;// 
a=0;//     .line 370
a=0;//     invoke-static {}, Lcom/twocloo/com/cn/activitys/BookApp;->getUser()Lcom/twocloo/com/cn/beans/User;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     if-eqz v0, :cond_0
a=0;// 
a=0;//     .line 371
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {}, Lcom/twocloo/com/cn/activitys/BookApp;->getUser()Lcom/twocloo/com/cn/beans/User;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v1}, Lcom/twocloo/com/cn/beans/User;->getUid()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-static {v0, v1}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$45(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;Ljava/lang/String;)V
a=0;// 
a=0;//     .line 372
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {}, Lcom/twocloo/com/cn/activitys/BookApp;->getUser()Lcom/twocloo/com/cn/beans/User;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v1}, Lcom/twocloo/com/cn/beans/User;->getToken()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-static {v0, v1}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$46(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;Ljava/lang/String;)V
a=0;// 
a=0;//     .line 373
a=0;//     iget-object v8, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     #v8=(Reference,Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;);
a=0;//     new-instance v0, Lcom/twocloo/com/cn/threads/SubedchaptersinfoThread;
a=0;// 
a=0;//     #v0=(UninitRef,Lcom/twocloo/com/cn/threads/SubedchaptersinfoThread;);
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v2}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$27(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/os/Handler;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v3}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$47(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     iget-object v4, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v4}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$48(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     iget-object v5, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v5}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$49(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v5
a=0;// 
a=0;//     invoke-direct/range {v0 .. v5}, Lcom/twocloo/com/cn/threads/SubedchaptersinfoThread;-><init>(Landroid/content/Context;Landroid/os/Handler;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/threads/SubedchaptersinfoThread;);
a=0;//     invoke-static {v8, v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$50(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;Lcom/twocloo/com/cn/threads/SubedchaptersinfoThread;)V
a=0;// 
a=0;//     .line 374
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$2(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Lcom/twocloo/com/cn/threads/SubedchaptersinfoThread;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Lcom/twocloo/com/cn/threads/SubedchaptersinfoThread;->start()V
a=0;// 
a=0;//     goto/16 :goto_0
a=0;// 
a=0;//     .line 377
a=0;//     :cond_b
a=0;//     #v0=(Integer);v2=(PosByte);v3=(PosByte);v4=(Null);v5=(One);v8=(PosByte);
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;);
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$51(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/RelativeLayout;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0, v3}, Landroid/widget/RelativeLayout;->setVisibility(I)V
a=0;// 
a=0;//     goto/16 :goto_0
a=0;// 
a=0;//     .line 380
a=0;//     :sswitch_7
a=0;//     #v0=(Integer);v1=(Uninit);
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;);
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$0(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/app/ProgressDialog;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     if-eqz v0, :cond_c
a=0;// 
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$0(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/app/ProgressDialog;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Landroid/app/ProgressDialog;->isShowing()Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     if-eqz v0, :cond_c
a=0;// 
a=0;//     .line 381
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;);
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$0(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/app/ProgressDialog;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Landroid/app/ProgressDialog;->dismiss()V
a=0;// 
a=0;//     .line 383
a=0;//     :cond_c
a=0;//     #v0=(Conflicted);
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;);
a=0;//     const-string v1, "\u52a0\u8f7d\u5931\u8d25\uff0c\u8bf7\u91cd\u8bd5"
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-static {v0, v1, v4}, Landroid/widget/Toast;->makeText(Landroid/content/Context;Ljava/lang/CharSequence;I)Landroid/widget/Toast;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Landroid/widget/Toast;->show()V
a=0;// 
a=0;//     goto/16 :goto_0
a=0;// 
a=0;//     .line 386
a=0;//     :sswitch_8
a=0;//     #v0=(Integer);v1=(Uninit);
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     #v1=(Reference,Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;);
a=0;//     iget-object v0, p1, Landroid/os/Message;->obj:Ljava/lang/Object;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/Object;);
a=0;//     check-cast v0, Ljava/lang/String;
a=0;// 
a=0;//     invoke-static {v1, v0, v4}, Landroid/widget/Toast;->makeText(Landroid/content/Context;Ljava/lang/CharSequence;I)Landroid/widget/Toast;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Landroid/widget/Toast;->show()V
a=0;// 
a=0;//     .line 388
a=0;//     :sswitch_9
a=0;//     #v0=(Conflicted);v1=(Conflicted);
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     #v1=(Reference,Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;);
a=0;//     iget-object v0, p1, Landroid/os/Message;->obj:Ljava/lang/Object;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/Object;);
a=0;//     check-cast v0, Ljava/util/ArrayList;
a=0;// 
a=0;//     invoke-static {v1, v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$52(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;Ljava/util/ArrayList;)V
a=0;// 
a=0;//     .line 389
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$53(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Ljava/util/ArrayList;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Ljava/util/ArrayList;->size()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     if-ne v0, v5, :cond_d
a=0;// 
a=0;//     .line 390
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;);
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$54(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/Button;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$53(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Ljava/util/ArrayList;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0, v4}, Ljava/util/ArrayList;->get(I)Ljava/lang/Object;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     check-cast v0, Lcom/twocloo/com/cn/beans/BookMarkBean;
a=0;// 
a=0;//     invoke-virtual {v0}, Lcom/twocloo/com/cn/beans/BookMarkBean;->getTitle()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v1, v0}, Landroid/widget/Button;->setText(Ljava/lang/CharSequence;)V
a=0;// 
a=0;//     .line 391
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$54(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/Button;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0, v4}, Landroid/widget/Button;->setVisibility(I)V
a=0;// 
a=0;//     .line 392
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$55(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/Button;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0, v3}, Landroid/widget/Button;->setVisibility(I)V
a=0;// 
a=0;//     .line 393
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$56(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/Button;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0, v3}, Landroid/widget/Button;->setVisibility(I)V
a=0;// 
a=0;//     .line 394
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$57(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/Button;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0, v3}, Landroid/widget/Button;->setVisibility(I)V
a=0;// 
a=0;//     goto/16 :goto_0
a=0;// 
a=0;//     .line 395
a=0;//     :cond_d
a=0;//     #v0=(Integer);
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;);
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$53(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Ljava/util/ArrayList;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Ljava/util/ArrayList;->size()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     if-ne v0, v2, :cond_e
a=0;// 
a=0;//     .line 396
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;);
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$54(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/Button;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$53(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Ljava/util/ArrayList;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0, v4}, Ljava/util/ArrayList;->get(I)Ljava/lang/Object;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     check-cast v0, Lcom/twocloo/com/cn/beans/BookMarkBean;
a=0;// 
a=0;//     invoke-virtual {v0}, Lcom/twocloo/com/cn/beans/BookMarkBean;->getTitle()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v1, v0}, Landroid/widget/Button;->setText(Ljava/lang/CharSequence;)V
a=0;// 
a=0;//     .line 397
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$55(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/Button;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$53(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Ljava/util/ArrayList;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0, v5}, Ljava/util/ArrayList;->get(I)Ljava/lang/Object;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     check-cast v0, Lcom/twocloo/com/cn/beans/BookMarkBean;
a=0;// 
a=0;//     invoke-virtual {v0}, Lcom/twocloo/com/cn/beans/BookMarkBean;->getTitle()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v1, v0}, Landroid/widget/Button;->setText(Ljava/lang/CharSequence;)V
a=0;// 
a=0;//     .line 398
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$54(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/Button;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0, v4}, Landroid/widget/Button;->setVisibility(I)V
a=0;// 
a=0;//     .line 399
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$55(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/Button;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0, v4}, Landroid/widget/Button;->setVisibility(I)V
a=0;// 
a=0;//     .line 400
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$56(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/Button;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0, v3}, Landroid/widget/Button;->setVisibility(I)V
a=0;// 
a=0;//     .line 401
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$57(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/Button;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0, v3}, Landroid/widget/Button;->setVisibility(I)V
a=0;// 
a=0;//     goto/16 :goto_0
a=0;// 
a=0;//     .line 402
a=0;//     :cond_e
a=0;//     #v0=(Integer);
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;);
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$53(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Ljava/util/ArrayList;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Ljava/util/ArrayList;->size()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     if-ne v0, v8, :cond_f
a=0;// 
a=0;//     .line 403
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;);
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$54(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/Button;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$53(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Ljava/util/ArrayList;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0, v4}, Ljava/util/ArrayList;->get(I)Ljava/lang/Object;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     check-cast v0, Lcom/twocloo/com/cn/beans/BookMarkBean;
a=0;// 
a=0;//     invoke-virtual {v0}, Lcom/twocloo/com/cn/beans/BookMarkBean;->getTitle()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v1, v0}, Landroid/widget/Button;->setText(Ljava/lang/CharSequence;)V
a=0;// 
a=0;//     .line 404
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$55(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/Button;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$53(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Ljava/util/ArrayList;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0, v5}, Ljava/util/ArrayList;->get(I)Ljava/lang/Object;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     check-cast v0, Lcom/twocloo/com/cn/beans/BookMarkBean;
a=0;// 
a=0;//     invoke-virtual {v0}, Lcom/twocloo/com/cn/beans/BookMarkBean;->getTitle()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v1, v0}, Landroid/widget/Button;->setText(Ljava/lang/CharSequence;)V
a=0;// 
a=0;//     .line 405
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$56(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/Button;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$53(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Ljava/util/ArrayList;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0, v2}, Ljava/util/ArrayList;->get(I)Ljava/lang/Object;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     check-cast v0, Lcom/twocloo/com/cn/beans/BookMarkBean;
a=0;// 
a=0;//     invoke-virtual {v0}, Lcom/twocloo/com/cn/beans/BookMarkBean;->getTitle()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v1, v0}, Landroid/widget/Button;->setText(Ljava/lang/CharSequence;)V
a=0;// 
a=0;//     .line 406
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$54(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/Button;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0, v4}, Landroid/widget/Button;->setVisibility(I)V
a=0;// 
a=0;//     .line 407
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$55(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/Button;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0, v4}, Landroid/widget/Button;->setVisibility(I)V
a=0;// 
a=0;//     .line 408
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$56(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/Button;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0, v4}, Landroid/widget/Button;->setVisibility(I)V
a=0;// 
a=0;//     .line 409
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$57(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/Button;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0, v3}, Landroid/widget/Button;->setVisibility(I)V
a=0;// 
a=0;//     goto/16 :goto_0
a=0;// 
a=0;//     .line 410
a=0;//     :cond_f
a=0;//     #v0=(Integer);
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;);
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$53(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Ljava/util/ArrayList;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Ljava/util/ArrayList;->size()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     const/4 v1, 0x4
a=0;// 
a=0;//     #v1=(PosByte);
a=0;//     if-lt v0, v1, :cond_0
a=0;// 
a=0;//     .line 411
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;);
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$54(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/Button;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     #v1=(Reference,Landroid/widget/Button;);
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$53(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Ljava/util/ArrayList;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0, v4}, Ljava/util/ArrayList;->get(I)Ljava/lang/Object;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     check-cast v0, Lcom/twocloo/com/cn/beans/BookMarkBean;
a=0;// 
a=0;//     invoke-virtual {v0}, Lcom/twocloo/com/cn/beans/BookMarkBean;->getTitle()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v1, v0}, Landroid/widget/Button;->setText(Ljava/lang/CharSequence;)V
a=0;// 
a=0;//     .line 412
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$55(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/Button;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$53(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Ljava/util/ArrayList;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0, v5}, Ljava/util/ArrayList;->get(I)Ljava/lang/Object;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     check-cast v0, Lcom/twocloo/com/cn/beans/BookMarkBean;
a=0;// 
a=0;//     invoke-virtual {v0}, Lcom/twocloo/com/cn/beans/BookMarkBean;->getTitle()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v1, v0}, Landroid/widget/Button;->setText(Ljava/lang/CharSequence;)V
a=0;// 
a=0;//     .line 413
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$56(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/Button;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$53(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Ljava/util/ArrayList;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0, v2}, Ljava/util/ArrayList;->get(I)Ljava/lang/Object;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     check-cast v0, Lcom/twocloo/com/cn/beans/BookMarkBean;
a=0;// 
a=0;//     invoke-virtual {v0}, Lcom/twocloo/com/cn/beans/BookMarkBean;->getTitle()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v1, v0}, Landroid/widget/Button;->setText(Ljava/lang/CharSequence;)V
a=0;// 
a=0;//     .line 414
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$57(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/Button;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$53(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Ljava/util/ArrayList;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0, v8}, Ljava/util/ArrayList;->get(I)Ljava/lang/Object;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     check-cast v0, Lcom/twocloo/com/cn/beans/BookMarkBean;
a=0;// 
a=0;//     invoke-virtual {v0}, Lcom/twocloo/com/cn/beans/BookMarkBean;->getTitle()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v1, v0}, Landroid/widget/Button;->setText(Ljava/lang/CharSequence;)V
a=0;// 
a=0;//     .line 415
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$54(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/Button;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0, v4}, Landroid/widget/Button;->setVisibility(I)V
a=0;// 
a=0;//     .line 416
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$55(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/Button;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0, v4}, Landroid/widget/Button;->setVisibility(I)V
a=0;// 
a=0;//     .line 417
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$56(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/Button;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0, v4}, Landroid/widget/Button;->setVisibility(I)V
a=0;// 
a=0;//     .line 418
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity$1;->this$0:Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;->access$57(Lcom/twocloo/com/cn/activitys/NovelDetailedActivity;)Landroid/widget/Button;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0, v4}, Landroid/widget/Button;->setVisibility(I)V
a=0;// 
a=0;//     goto/16 :goto_0
a=0;// 
a=0;//     .line 226
a=0;//     :sswitch_data_0
a=0;//     .sparse-switch
a=0;//         0x0 -> :sswitch_0
a=0;//         0x1 -> :sswitch_1
a=0;//         0x2 -> :sswitch_3
a=0;//         0x3 -> :sswitch_4
a=0;//         0x6f -> :sswitch_2
a=0;//         0x7b -> :sswitch_6
a=0;//         0x14d -> :sswitch_8
a=0;//         0x1bc -> :sswitch_9
a=0;//         0x3e7 -> :sswitch_7
a=0;//         0x7d1 -> :sswitch_5
a=0;//     .end sparse-switch
a=0;// .end method
}}
