package com.twocloo.com.cn.activitys; class RechargeActivity { void a() { int a;
a=0;// .class public Lcom/twocloo/com/cn/activitys/RechargeActivity;
a=0;// .super Landroid/app/Activity;
a=0;// .source "RechargeActivity.java"
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field private TAG:Ljava/lang/String;
a=0;// 
a=0;// .field private articleid:Ljava/lang/String;
a=0;// 
a=0;// .field private beg:Ljava/lang/String;
a=0;// 
a=0;// .field callback:Lcom/twocloo/com/cn/singlebook/DataCallBack;
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "Lcom/twocloo/com/cn/singlebook/DataCallBack",
a=0;//             "<",
a=0;//             "Lcom/twocloo/com/cn/beans/SubResultBean;",
a=0;//             ">;"
a=0;//         }
a=0;//     .end annotation
a=0;// .end field
a=0;// 
a=0;// .field private fcdVip:I
a=0;// 
a=0;// .field private from:Ljava/lang/String;
a=0;// 
a=0;// .field private fromWeb:Ljava/lang/String;
a=0;// 
a=0;// .field private imgFile:Ljava/lang/String;
a=0;// 
a=0;// .field private imgUrl:Ljava/lang/String;
a=0;// 
a=0;// .field private isVip:I
a=0;// 
a=0;// .field public mWebView:Lcom/twocloo/com/cn/beans/WebView;
a=0;// 
a=0;// .field private ordertype:Ljava/lang/String;
a=0;// 
a=0;// .field private p:I
a=0;// 
a=0;// .field private pd:Landroid/app/ProgressDialog;
a=0;// 
a=0;// .field private shadowlayout:Landroid/widget/RelativeLayout;
a=0;// 
a=0;// .field private tag:Ljava/lang/String;
a=0;// 
a=0;// .field private textid:Ljava/lang/String;
a=0;// 
a=0;// .field private title:Ljava/lang/String;
a=0;// 
a=0;// .field private token:Ljava/lang/String;
a=0;// 
a=0;// .field private uid:Ljava/lang/String;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>()V
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 41
a=0;//     invoke-direct {p0}, Landroid/app/Activity;-><init>()V
a=0;// 
a=0;//     .line 42
a=0;//     #p0=(Reference,Lcom/twocloo/com/cn/activitys/RechargeActivity;);
a=0;//     const-string v0, "RechargeActivity"
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     iput-object v0, p0, Lcom/twocloo/com/cn/activitys/RechargeActivity;->TAG:Ljava/lang/String;
a=0;// 
a=0;//     .line 116
a=0;//     new-instance v0, Lcom/twocloo/com/cn/activitys/RechargeActivity$1;
a=0;// 
a=0;//     #v0=(UninitRef,Lcom/twocloo/com/cn/activitys/RechargeActivity$1;);
a=0;//     invoke-direct {v0, p0}, Lcom/twocloo/com/cn/activitys/RechargeActivity$1;-><init>(Lcom/twocloo/com/cn/activitys/RechargeActivity;)V
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/activitys/RechargeActivity$1;);
a=0;//     iput-object v0, p0, Lcom/twocloo/com/cn/activitys/RechargeActivity;->callback:Lcom/twocloo/com/cn/singlebook/DataCallBack;
a=0;// 
a=0;//     .line 41
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method static synthetic access$0(Lcom/twocloo/com/cn/activitys/RechargeActivity;)Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 45
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/RechargeActivity;->articleid:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method static synthetic access$1(Lcom/twocloo/com/cn/activitys/RechargeActivity;)Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 47
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/RechargeActivity;->uid:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method static synthetic access$10(Lcom/twocloo/com/cn/activitys/RechargeActivity;)I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 52
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/activitys/RechargeActivity;->p:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method static synthetic access$11(Lcom/twocloo/com/cn/activitys/RechargeActivity;)Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 50
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/RechargeActivity;->imgUrl:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method static synthetic access$12(Lcom/twocloo/com/cn/activitys/RechargeActivity;)Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 50
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/RechargeActivity;->imgFile:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method static synthetic access$2(Lcom/twocloo/com/cn/activitys/RechargeActivity;)Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 48
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/RechargeActivity;->token:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method static synthetic access$3(Lcom/twocloo/com/cn/activitys/RechargeActivity;)Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 45
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/RechargeActivity;->textid:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method static synthetic access$4(Lcom/twocloo/com/cn/activitys/RechargeActivity;)I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 52
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/activitys/RechargeActivity;->isVip:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method static synthetic access$5(Lcom/twocloo/com/cn/activitys/RechargeActivity;)Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 50
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/RechargeActivity;->title:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method static synthetic access$6(Lcom/twocloo/com/cn/activitys/RechargeActivity;)Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 50
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/RechargeActivity;->tag:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method static synthetic access$7(Lcom/twocloo/com/cn/activitys/RechargeActivity;)Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 50
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/RechargeActivity;->fromWeb:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method static synthetic access$8(Lcom/twocloo/com/cn/activitys/RechargeActivity;)Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 50
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/RechargeActivity;->beg:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method static synthetic access$9(Lcom/twocloo/com/cn/activitys/RechargeActivity;)I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 52
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/activitys/RechargeActivity;->fcdVip:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public getHeight()I
a=0;//     .locals 3
a=0;// 
a=0;//     .prologue
a=0;//     .line 208
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/activitys/RechargeActivity;->getWindowManager()Landroid/view/WindowManager;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     .line 209
a=0;//     .local v1, "windowManager":Landroid/view/WindowManager;
a=0;//     #v1=(Reference,Landroid/view/WindowManager;);
a=0;//     invoke-interface {v1}, Landroid/view/WindowManager;->getDefaultDisplay()Landroid/view/Display;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 210
a=0;//     .local v0, "display":Landroid/view/Display;
a=0;//     #v0=(Reference,Landroid/view/Display;);
a=0;//     invoke-virtual {v0}, Landroid/view/Display;->getHeight()I
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     return v2
a=0;// .end method
a=0;// 
a=0;// .method protected onCreate(Landroid/os/Bundle;)V
a=0;//     .locals 21
a=0;//     .param p1, "savedInstanceState"    # Landroid/os/Bundle;
a=0;// 
a=0;//     .prologue
a=0;//     .line 56
a=0;//     invoke-super/range {p0 .. p1}, Landroid/app/Activity;->onCreate(Landroid/os/Bundle;)V
a=0;// 
a=0;//     .line 57
a=0;//     const/4 v3, 0x1
a=0;// 
a=0;//     #v3=(One);
a=0;//     move-object/from16 v0, p0
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/activitys/RechargeActivity;);
a=0;//     invoke-virtual {v0, v3}, Lcom/twocloo/com/cn/activitys/RechargeActivity;->requestWindowFeature(I)Z
a=0;// 
a=0;//     .line 60
a=0;//     sget v3, Lcom/twocloo/com/cn/R$layout;->readbook_select_recharge:I
a=0;// 
a=0;//     #v3=(Integer);
a=0;//     move-object/from16 v0, p0
a=0;// 
a=0;//     invoke-virtual {v0, v3}, Lcom/twocloo/com/cn/activitys/RechargeActivity;->setContentView(I)V
a=0;//     invoke-direct {v0}, Lcom/twocloo/com/cn/activitys/RechargeActivity;->addAd()V
a=0;// 		# invoke-virtual {v0}, Lcom/twocloo/com/cn/activitys/RechargeActivity;->addChaping()V
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method protected onDestroy()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 203
a=0;//     invoke-super {p0}, Landroid/app/Activity;->onDestroy()V
a=0;// 
a=0;//     .line 204
a=0;//     invoke-static {p0}, Lcom/twocloo/com/cn/common/CloseActivity;->remove(Landroid/app/Activity;)V
a=0;// 
a=0;//     .line 205
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public onKeyDown(ILandroid/view/KeyEvent;)Z
a=0;//     .locals 1
a=0;//     .param p1, "keyCode"    # I
a=0;//     .param p2, "event"    # Landroid/view/KeyEvent;
a=0;// 
a=0;//     .prologue
a=0;//     .line 183
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/activitys/RechargeActivity;->finish()V
a=0;// 
a=0;//     .line 184
a=0;//     invoke-super {p0, p1, p2}, Landroid/app/Activity;->onKeyDown(ILandroid/view/KeyEvent;)Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method protected onPause()V
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 196
a=0;//     invoke-super {p0}, Landroid/app/Activity;->onPause()V
a=0;// 
a=0;//     .line 197
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/RechargeActivity;->TAG:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     invoke-static {v0}, Lcom/umeng/analytics/MobclickAgent;->onPageEnd(Ljava/lang/String;)V
a=0;// 
a=0;//     .line 198
a=0;//     invoke-static {p0}, Lcom/umeng/analytics/MobclickAgent;->onPause(Landroid/content/Context;)V
a=0;// 
a=0;//     .line 199
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method protected onResume()V
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 188
a=0;//     invoke-super {p0}, Landroid/app/Activity;->onResume()V
a=0;// 
a=0;//     .line 189
a=0;//     sput-object p0, Lcom/twocloo/com/cn/common/CloseActivity;->curActivity:Landroid/app/Activity;
a=0;// 
a=0;//     .line 190
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/activitys/RechargeActivity;->TAG:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     invoke-static {v0}, Lcom/umeng/analytics/MobclickAgent;->onPageStart(Ljava/lang/String;)V
a=0;// 
a=0;//     .line 191
a=0;//     invoke-static {p0}, Lcom/umeng/analytics/MobclickAgent;->onResume(Landroid/content/Context;)V
a=0;// 
a=0;//     .line 192
a=0;//     return-void
a=0;// .end method
a=0;//
a=0;// .method private addAd()V
a=0;//     .registers 13
a=0;// 
 a=0;//    .prologue
a=0;//     const/4 v5, 0x2
a=0;// 
a=0;//     const/4 v1, 0x1
a=0;// 
a=0;//     const/4 v2, 0x0
a=0;// 
a=0;//     .line 36
 a=0;//    new-instance v10, Lnet/youmi/android/banner/AdView;
a=0;// 
a=0;//     sget-object v3, Lnet/youmi/android/banner/AdSize;->FIT_SCREEN:Lnet/youmi/android/banner/AdSize;
a=0;// 
a=0;//     invoke-direct {v10, p0, v3}, Lnet/youmi/android/banner/AdView;-><init>(Landroid/content/Context;Lnet/youmi/android/banner/AdSize;)V
a=0;// 
 a=0;//    .line 38
a=0;//     .local v10, "adView":Lnet/youmi/android/banner/AdView;
a=0;//     const v3, 0x7f05000a
a=0;// 
a=0;//     invoke-virtual {p0, v3}, Lcom/twocloo/com/cn/activitys/RechargeActivity;->findViewById(I)Landroid/view/View;
a=0;// 
a=0;//     move-result-object v9
a=0;// 
a=0;//     check-cast v9, Landroid/widget/RelativeLayout;
a=0;// 
a=0;//     .line 40
a=0;//     .local v9, "adLayout":Landroid/widget/RelativeLayout;
a=0;//     invoke-virtual {v9, v10}, Landroid/widget/RelativeLayout;->addView(Landroid/view/View;)V
a=0;// 
a=0;//     .line 42
 a=0;//    const v3, 0x7f050311
a=0;// 
a=0;//     invoke-virtual {p0, v3}, Lcom/twocloo/com/cn/activitys/RechargeActivity;->findViewById(I)Landroid/view/View;
a=0;// 
a=0;//     move-result-object v11
a=0;// 
a=0;//     check-cast v11, Landroid/widget/RelativeLayout;
a=0;// 
a=0;//     .line 43
a=0;//     .local v11, "shadowlayout":Landroid/widget/RelativeLayout;
a=0;//     const/4 v3, 0x0
a=0;// 
a=0;//     invoke-virtual {v11, v3}, Landroid/widget/RelativeLayout;->setVisibility(I)V
a=0;// 
a=0;//     .line 44
a=0;//     new-instance v0, Landroid/view/animation/TranslateAnimation;
a=0;// 
a=0;//     const/high16 v6, 0x3f800000
a=0;// 
a=0;//     move v3, v1
a=0;// 
a=0;//     move v4, v2
a=0;// 
a=0;//     move v7, v5
a=0;// 
a=0;//     move v8, v2
a=0;// 
a=0;//     invoke-direct/range {v0 .. v8}, Landroid/view/animation/TranslateAnimation;-><init>(IFIFIFIF)V
a=0;// 
a=0;//     .line 45
a=0;//     .local v0, "localTranslateAnimation":Landroid/view/animation/TranslateAnimation;
a=0;//     const-wide/16 v1, 0x1f4
a=0;// 
a=0;//     invoke-virtual {v0, v1, v2}, Landroid/view/animation/TranslateAnimation;->setDuration(J)V
a=0;// 
a=0;//     .line 46
a=0;//     invoke-virtual {v9, v0}, Landroid/widget/RelativeLayout;->setAnimation(Landroid/view/animation/Animation;)V
a=0;// 
a=0;//     .line 47
a=0;//    return-void
a=0;//  .end method
a=0;// 
a=0;// .method public addChaping()V
a=0;//    .registers 3
a=0;//    .prologue
a=0;//
a=0;//    .line 44
a=0;//    invoke-static {p0}, Lnet/youmi/android/spot/SpotManager;->getInstance(Landroid/content/Context;)Lnet/youmi/android/spot/SpotManager;
a=0;//
a=0;//    move-result-object v0
a=0;//
a=0;//    const/4 v1, 0x1
a=0;//
a=0;//    invoke-virtual {v0, v1}, Lnet/youmi/android/spot/SpotManager;->setSpotOrientation(I)V
a=0;//
a=0;//    .line 46
a=0;//    invoke-static {p0}, Lnet/youmi/android/spot/SpotManager;->getInstance(Landroid/content/Context;)Lnet/youmi/android/spot/SpotManager;
a=0;//
a=0;//    move-result-object v0
a=0;//
a=0;//    invoke-virtual {v0, p0}, Lnet/youmi/android/spot/SpotManager;->showSpotAds(Landroid/content/Context;)V
a=0;//
a=0;//    .line 47
a=0;//    return-void
a=0;//.end method
}}
