package com.twocloo.com.cn.fragment; class LoginFragment$1$1$2 { void a() { int a;
a=0;// .class Lcom/twocloo/com/cn/fragment/LoginFragment$1$1$2;
a=0;// .super Ljava/lang/Object;
a=0;// .source "LoginFragment.java"
a=0;// 
a=0;// # interfaces
a=0;// .implements Ljava/lang/Runnable;
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation system Ldalvik/annotation/EnclosingMethod;
a=0;//     value = Lcom/twocloo/com/cn/fragment/LoginFragment$1$1;->run()V
a=0;// .end annotation
a=0;// 
a=0;// .annotation system Ldalvik/annotation/InnerClass;
a=0;//     accessFlags = 0x0
a=0;//     name = null
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field final synthetic this$2:Lcom/twocloo/com/cn/fragment/LoginFragment$1$1;
a=0;// 
a=0;// .field private final synthetic val$d:Landroid/graphics/drawable/Drawable;
a=0;// 
a=0;// .field private final synthetic val$fileName:Ljava/lang/String;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>(Lcom/twocloo/com/cn/fragment/LoginFragment$1$1;Landroid/graphics/drawable/Drawable;Ljava/lang/String;)V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 1
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/fragment/LoginFragment$1$1$2;->this$2:Lcom/twocloo/com/cn/fragment/LoginFragment$1$1;
a=0;// 
a=0;//     iput-object p2, p0, Lcom/twocloo/com/cn/fragment/LoginFragment$1$1$2;->val$d:Landroid/graphics/drawable/Drawable;
a=0;// 
a=0;//     iput-object p3, p0, Lcom/twocloo/com/cn/fragment/LoginFragment$1$1$2;->val$fileName:Ljava/lang/String;
a=0;// 
a=0;//     .line 156
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcom/twocloo/com/cn/fragment/LoginFragment$1$1$2;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public run()V
a=0;//     .locals 3
a=0;// 
a=0;//     .prologue
a=0;//     .line 159
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/fragment/LoginFragment$1$1$2;->this$2:Lcom/twocloo/com/cn/fragment/LoginFragment$1$1;
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/fragment/LoginFragment$1$1;);
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/fragment/LoginFragment$1$1;->access$0(Lcom/twocloo/com/cn/fragment/LoginFragment$1$1;)Lcom/twocloo/com/cn/fragment/LoginFragment$1;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/fragment/LoginFragment$1;->access$0(Lcom/twocloo/com/cn/fragment/LoginFragment$1;)Lcom/twocloo/com/cn/fragment/LoginFragment;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/fragment/LoginFragment;->access$11(Lcom/twocloo/com/cn/fragment/LoginFragment;)Lcom/twocloo/com/cn/view/CircleImageView;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/fragment/LoginFragment$1$1$2;->val$d:Landroid/graphics/drawable/Drawable;
a=0;// 
a=0;//     #v1=(Reference,Landroid/graphics/drawable/Drawable;);
a=0;//     invoke-virtual {v0, v1}, Lcom/twocloo/com/cn/view/CircleImageView;->setImageDrawable(Landroid/graphics/drawable/Drawable;)V
a=0;// 
a=0;//     .line 161
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/fragment/LoginFragment$1$1$2;->this$2:Lcom/twocloo/com/cn/fragment/LoginFragment$1$1;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/fragment/LoginFragment$1$1;->access$0(Lcom/twocloo/com/cn/fragment/LoginFragment$1$1;)Lcom/twocloo/com/cn/fragment/LoginFragment$1;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/fragment/LoginFragment$1;->access$0(Lcom/twocloo/com/cn/fragment/LoginFragment$1;)Lcom/twocloo/com/cn/fragment/LoginFragment;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/fragment/LoginFragment$1$1$2;->val$d:Landroid/graphics/drawable/Drawable;
a=0;// 
a=0;//     invoke-static {v1}, Lcom/twocloo/com/cn/common/Util;->DrawableToBitmap(Landroid/graphics/drawable/Drawable;)Landroid/graphics/Bitmap;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-static {v0, v1}, Lcom/twocloo/com/cn/fragment/LoginFragment;->access$13(Lcom/twocloo/com/cn/fragment/LoginFragment;Landroid/graphics/Bitmap;)V
a=0;// 
a=0;//     .line 162
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/fragment/LoginFragment$1$1$2;->this$2:Lcom/twocloo/com/cn/fragment/LoginFragment$1$1;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/fragment/LoginFragment$1$1;->access$0(Lcom/twocloo/com/cn/fragment/LoginFragment$1$1;)Lcom/twocloo/com/cn/fragment/LoginFragment$1;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/fragment/LoginFragment$1;->access$0(Lcom/twocloo/com/cn/fragment/LoginFragment$1;)Lcom/twocloo/com/cn/fragment/LoginFragment;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/com/cn/fragment/LoginFragment;->access$14(Lcom/twocloo/com/cn/fragment/LoginFragment;)Landroid/graphics/Bitmap;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     sget-object v1, Lcom/twocloo/com/cn/common/Constants;->TWOCLOO_USER_ICON_IMGCACHE:Ljava/lang/String;
a=0;// 
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/fragment/LoginFragment$1$1$2;->val$fileName:Ljava/lang/String;
a=0;// 
a=0;//     #v2=(Reference,Ljava/lang/String;);
a=0;//     invoke-static {v0, v1, v2}, Lcom/twocloo/com/cn/common/Util;->savePhotoToSd(Landroid/graphics/Bitmap;Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     .line 167
a=0;//     return-void
a=0;// .end method
}}
