package com.twocloo.com.cn.fragment; class MainGroupFragment { void a() { int a;
a=0;// .class public Lcom/twocloo/com/cn/fragment/MainGroupFragment;
a=0;// .super Landroid/support/v4/app/Fragment;
a=0;// .source "MainGroupFragment.java"
a=0;// 
a=0;// 
a=0;// # static fields
a=0;// .field private static instance:Lcom/twocloo/com/cn/fragment/MainGroupFragment;
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field public btn1:Landroid/widget/RadioButton;
a=0;// 
a=0;// .field public btn2:Landroid/widget/RadioButton;
a=0;// 
a=0;// .field public btn3:Landroid/widget/RadioButton;
a=0;// 
a=0;// .field public btn4:Landroid/widget/RadioButton;
a=0;// 
a=0;// .field public btn5:Landroid/widget/RadioButton;
a=0;// 
a=0;// .field private mRadioGroup:Landroid/widget/RadioGroup;
a=0;// 
a=0;// .field private mRadioGroupListener:Landroid/widget/RadioGroup$OnCheckedChangeListener;
a=0;// 
a=0;// .field private refreshSearch:Z
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>()V
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 22
a=0;//     invoke-direct {p0}, Landroid/support/v4/app/Fragment;-><init>()V
a=0;// 
a=0;//     .line 82
a=0;//     #p0=(Reference,Lcom/twocloo/com/cn/fragment/MainGroupFragment;);
a=0;//     new-instance v0, Lcom/twocloo/com/cn/fragment/MainGroupFragment$1;
a=0;// 
a=0;//     #v0=(UninitRef,Lcom/twocloo/com/cn/fragment/MainGroupFragment$1;);
a=0;//     invoke-direct {v0, p0}, Lcom/twocloo/com/cn/fragment/MainGroupFragment$1;-><init>(Lcom/twocloo/com/cn/fragment/MainGroupFragment;)V
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/fragment/MainGroupFragment$1;);
a=0;//     iput-object v0, p0, Lcom/twocloo/com/cn/fragment/MainGroupFragment;->mRadioGroupListener:Landroid/widget/RadioGroup$OnCheckedChangeListener;
a=0;// 
a=0;//     .line 22
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method static synthetic access$0(Lcom/twocloo/com/cn/fragment/MainGroupFragment;)V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 104
a=0;//     invoke-direct {p0}, Lcom/twocloo/com/cn/fragment/MainGroupFragment;->doBtn1()V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method private doBtn1()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 107
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method private doOnCheckedChanged(Landroid/support/v4/app/Fragment;)V
a=0;//     .locals 3
a=0;//     .param p1, "fragment"    # Landroid/support/v4/app/Fragment;
a=0;// 
a=0;//     .prologue
a=0;//     .line 123
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/fragment/MainGroupFragment;->getActivity()Landroid/support/v4/app/FragmentActivity;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     #v2=(Reference,Landroid/support/v4/app/FragmentActivity;);
a=0;//     invoke-virtual {v2}, Landroid/support/v4/app/FragmentActivity;->getSupportFragmentManager()Landroid/support/v4/app/FragmentManager;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 124
a=0;//     .local v0, "fManager":Landroid/support/v4/app/FragmentManager;
a=0;//     #v0=(Reference,Landroid/support/v4/app/FragmentManager;);
a=0;//     invoke-virtual {v0}, Landroid/support/v4/app/FragmentManager;->beginTransaction()Landroid/support/v4/app/FragmentTransaction;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     .line 125
a=0;//     .local v1, "fTransaction":Landroid/support/v4/app/FragmentTransaction;
a=0;//     #v1=(Reference,Landroid/support/v4/app/FragmentTransaction;);
a=0;//     sget v2, Lcom/twocloo/com/cn/R$id;->mainLinear:I
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     invoke-virtual {v1, v2, p1}, Landroid/support/v4/app/FragmentTransaction;->replace(ILandroid/support/v4/app/Fragment;)Landroid/support/v4/app/FragmentTransaction;
a=0;// 
a=0;//     .line 127
a=0;//     invoke-virtual {v1}, Landroid/support/v4/app/FragmentTransaction;->commit()I
a=0;// 
a=0;//     .line 128
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static getInstance()Lcom/twocloo/com/cn/fragment/MainGroupFragment;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 27
a=0;//     sget-object v0, Lcom/twocloo/com/cn/fragment/MainGroupFragment;->instance:Lcom/twocloo/com/cn/fragment/MainGroupFragment;
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/fragment/MainGroupFragment;);
a=0;//     if-nez v0, :cond_0
a=0;// 
a=0;//     .line 28
a=0;//     new-instance v0, Lcom/twocloo/com/cn/fragment/MainGroupFragment;
a=0;// 
a=0;//     #v0=(UninitRef,Lcom/twocloo/com/cn/fragment/MainGroupFragment;);
a=0;//     invoke-direct {v0}, Lcom/twocloo/com/cn/fragment/MainGroupFragment;-><init>()V
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/fragment/MainGroupFragment;);
a=0;//     sput-object v0, Lcom/twocloo/com/cn/fragment/MainGroupFragment;->instance:Lcom/twocloo/com/cn/fragment/MainGroupFragment;
a=0;// 
a=0;//     .line 30
a=0;//     :cond_0
a=0;//     sget-object v0, Lcom/twocloo/com/cn/fragment/MainGroupFragment;->instance:Lcom/twocloo/com/cn/fragment/MainGroupFragment;
a=0;// 
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public doBtn5()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 102
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public isRefreshSearch()Z
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 110
a=0;//     iget-boolean v0, p0, Lcom/twocloo/com/cn/fragment/MainGroupFragment;->refreshSearch:Z
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public onActivityCreated(Landroid/os/Bundle;)V
a=0;//     .locals 4
a=0;//     .param p1, "savedInstanceState"    # Landroid/os/Bundle;
a=0;// 
a=0;//     .prologue
a=0;//     .line 50
a=0;//     invoke-super {p0, p1}, Landroid/support/v4/app/Fragment;->onActivityCreated(Landroid/os/Bundle;)V
a=0;// 
a=0;//     .line 52
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/fragment/MainGroupFragment;->getActivity()Landroid/support/v4/app/FragmentActivity;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     #v1=(Reference,Landroid/support/v4/app/FragmentActivity;);
a=0;//     const-string v2, "1"
a=0;// 
a=0;//     #v2=(Reference,Ljava/lang/String;);
a=0;//     invoke-static {v1, v2}, Lcom/twocloo/com/cn/common/LocalStore;->setfirstload(Landroid/content/Context;Ljava/lang/String;)V
a=0;// 
a=0;//     .line 54
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/fragment/MainGroupFragment;->getActivity()Landroid/support/v4/app/FragmentActivity;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     sget v2, Lcom/twocloo/com/cn/R$id;->radioGroup:I
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     invoke-virtual {v1, v2}, Landroid/support/v4/app/FragmentActivity;->findViewById(I)Landroid/view/View;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     check-cast v1, Landroid/widget/RadioGroup;
a=0;// 
a=0;//     iput-object v1, p0, Lcom/twocloo/com/cn/fragment/MainGroupFragment;->mRadioGroup:Landroid/widget/RadioGroup;
a=0;// 
a=0;//     .line 55
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/fragment/MainGroupFragment;->mRadioGroup:Landroid/widget/RadioGroup;
a=0;// 
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/fragment/MainGroupFragment;->mRadioGroupListener:Landroid/widget/RadioGroup$OnCheckedChangeListener;
a=0;// 
a=0;//     #v2=(Reference,Landroid/widget/RadioGroup$OnCheckedChangeListener;);
a=0;//     invoke-virtual {v1, v2}, Landroid/widget/RadioGroup;->setOnCheckedChangeListener(Landroid/widget/RadioGroup$OnCheckedChangeListener;)V
a=0;// 
a=0;//     .line 56
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/fragment/MainGroupFragment;->getActivity()Landroid/support/v4/app/FragmentActivity;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     sget v2, Lcom/twocloo/com/cn/R$id;->menu_btn1:I
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     invoke-virtual {v1, v2}, Landroid/support/v4/app/FragmentActivity;->findViewById(I)Landroid/view/View;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     check-cast v1, Landroid/widget/RadioButton;
a=0;// 
a=0;//     iput-object v1, p0, Lcom/twocloo/com/cn/fragment/MainGroupFragment;->btn1:Landroid/widget/RadioButton;
a=0;// 
a=0;//     .line 57
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/fragment/MainGroupFragment;->getActivity()Landroid/support/v4/app/FragmentActivity;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     sget v2, Lcom/twocloo/com/cn/R$id;->menu_btn2:I
a=0;// 
a=0;//     invoke-virtual {v1, v2}, Landroid/support/v4/app/FragmentActivity;->findViewById(I)Landroid/view/View;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     check-cast v1, Landroid/widget/RadioButton;
a=0;// 
a=0;//     iput-object v1, p0, Lcom/twocloo/com/cn/fragment/MainGroupFragment;->btn2:Landroid/widget/RadioButton;
a=0;// 
a=0;//     .line 58
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/fragment/MainGroupFragment;->getActivity()Landroid/support/v4/app/FragmentActivity;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     sget v2, Lcom/twocloo/com/cn/R$id;->menu_btn3:I
a=0;// 
a=0;//     invoke-virtual {v1, v2}, Landroid/support/v4/app/FragmentActivity;->findViewById(I)Landroid/view/View;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     check-cast v1, Landroid/widget/RadioButton;
a=0;// 
a=0;//     iput-object v1, p0, Lcom/twocloo/com/cn/fragment/MainGroupFragment;->btn3:Landroid/widget/RadioButton;
a=0;// 
a=0;//     .line 59
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/fragment/MainGroupFragment;->getActivity()Landroid/support/v4/app/FragmentActivity;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     sget v2, Lcom/twocloo/com/cn/R$id;->menu_btn4:I
a=0;// 
a=0;//     invoke-virtual {v1, v2}, Landroid/support/v4/app/FragmentActivity;->findViewById(I)Landroid/view/View;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     check-cast v1, Landroid/widget/RadioButton;
a=0;// 
a=0;//     iput-object v1, p0, Lcom/twocloo/com/cn/fragment/MainGroupFragment;->btn4:Landroid/widget/RadioButton;
a=0;// 
a=0;//     .line 60
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/fragment/MainGroupFragment;->getActivity()Landroid/support/v4/app/FragmentActivity;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     sget v2, Lcom/twocloo/com/cn/R$id;->menu_btn5:I
a=0;// 
a=0;//     invoke-virtual {v1, v2}, Landroid/support/v4/app/FragmentActivity;->findViewById(I)Landroid/view/View;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     check-cast v1, Landroid/widget/RadioButton;
a=0;// 
a=0;//     iput-object v1, p0, Lcom/twocloo/com/cn/fragment/MainGroupFragment;->btn5:Landroid/widget/RadioButton;
a=0;// 
a=0;//     .line 62
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/fragment/MainGroupFragment;->getActivity()Landroid/support/v4/app/FragmentActivity;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v1}, Landroid/support/v4/app/FragmentActivity;->getIntent()Landroid/content/Intent;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     const-string v2, "index"
a=0;// 
a=0;//     #v2=(Reference,Ljava/lang/String;);
a=0;//     const/4 v3, 0x1
a=0;// 
a=0;//     #v3=(One);
a=0;//     invoke-virtual {v1, v2, v3}, Landroid/content/Intent;->getIntExtra(Ljava/lang/String;I)I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     .line 63
a=0;//     .local v0, "index":I
a=0;//     #v0=(Integer);
a=0;//     packed-switch v0, :pswitch_data_0
a=0;// 
a=0;//     .line 80
a=0;//     :goto_0
a=0;//     return-void
a=0;// 
a=0;//     .line 65
a=0;//     :pswitch_0
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/fragment/MainGroupFragment;->btn1:Landroid/widget/RadioButton;
a=0;// 
a=0;//     invoke-virtual {v1}, Landroid/widget/RadioButton;->performClick()Z
a=0;// 
a=0;//     goto :goto_0
a=0;// 
a=0;//     .line 68
a=0;//     :pswitch_1
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/fragment/MainGroupFragment;->btn2:Landroid/widget/RadioButton;
a=0;// 
a=0;//     invoke-virtual {v1}, Landroid/widget/RadioButton;->performClick()Z
a=0;// 
a=0;//     goto :goto_0
a=0;// 
a=0;//     .line 71
a=0;//     :pswitch_2
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/fragment/MainGroupFragment;->btn3:Landroid/widget/RadioButton;
a=0;// 
a=0;//     invoke-virtual {v1}, Landroid/widget/RadioButton;->performClick()Z
a=0;// 
a=0;//     goto :goto_0
a=0;// 
a=0;//     .line 74
a=0;//     :pswitch_3
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/fragment/MainGroupFragment;->btn4:Landroid/widget/RadioButton;
a=0;// 
a=0;//     invoke-virtual {v1}, Landroid/widget/RadioButton;->performClick()Z
a=0;// 
a=0;//     goto :goto_0
a=0;// 
a=0;//     .line 77
a=0;//     :pswitch_4
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/fragment/MainGroupFragment;->btn5:Landroid/widget/RadioButton;
a=0;// 
a=0;//     invoke-virtual {v1}, Landroid/widget/RadioButton;->performClick()Z
a=0;// 
a=0;//     goto :goto_0
a=0;// 
a=0;//     .line 63
a=0;//     :pswitch_data_0
a=0;//     .packed-switch 0x1
a=0;//         :pswitch_0
a=0;//         :pswitch_1
a=0;//         :pswitch_2
a=0;//         :pswitch_3
a=0;//         :pswitch_4
a=0;//     .end packed-switch
a=0;// .end method
a=0;// 
a=0;// .method public onCreateAnimation(IZI)Landroid/view/animation/Animation;
a=0;//     .locals 1
a=0;//     .param p1, "transit"    # I
a=0;//     .param p2, "enter"    # Z
a=0;//     .param p3, "nextAnim"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 45
a=0;//     invoke-super {p0, p1, p2, p3}, Landroid/support/v4/app/Fragment;->onCreateAnimation(IZI)Landroid/view/animation/Animation;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Landroid/view/animation/Animation;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public onCreateView(Landroid/view/LayoutInflater;Landroid/view/ViewGroup;Landroid/os/Bundle;)Landroid/view/View;
a=0;//     .locals 2
a=0;//     .param p1, "inflater"    # Landroid/view/LayoutInflater;
a=0;//     .param p2, "container"    # Landroid/view/ViewGroup;
a=0;//     .param p3, "savedInstanceState"    # Landroid/os/Bundle;
a=0;// 
a=0;//     .prologue
a=0;//     .line 39
a=0;//     sget v0, Lcom/twocloo/com/cn/R$layout;->main_group:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     const/4 v1, 0x0
a=0;// 
a=0;//     #v1=(Null);
a=0;//     invoke-virtual {p1, v0, p2, v1}, Landroid/view/LayoutInflater;->inflate(ILandroid/view/ViewGroup;Z)Landroid/view/View;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Landroid/view/View;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public setRefreshSearch(Z)V
a=0;//     .locals 0
a=0;//     .param p1, "refreshSearch"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 114
a=0;//     iput-boolean p1, p0, Lcom/twocloo/com/cn/fragment/MainGroupFragment;->refreshSearch:Z
a=0;// 
a=0;//     .line 115
a=0;//     return-void
a=0;// .end method
}}
