package com.twocloo.com.cn.fragment; class SelectSexFragment { void a() { int a;
a=0;// .class public Lcom/twocloo/com/cn/fragment/SelectSexFragment;
a=0;// .super Landroid/support/v4/app/Fragment;
a=0;// .source "SelectSexFragment.java"
a=0;// 
a=0;// # interfaces
a=0;// .implements Landroid/view/View$OnClickListener;
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation build Landroid/annotation/SuppressLint;
a=0;//     value = {
a=0;//         "ValidFragment"
a=0;//     }
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field private nan:Landroid/widget/ImageView;
a=0;// 
a=0;// .field private nanshen:Landroid/widget/ImageView;
a=0;// 
a=0;// .field private next:Landroid/widget/Button;
a=0;// 
a=0;// .field private nv:Landroid/widget/ImageView;
a=0;// 
a=0;// .field private nvshen:Landroid/widget/ImageView;
a=0;// 
a=0;// .field private tiaoguo:Landroid/widget/ImageView;
a=0;// 
a=0;// .field private viewPager:Landroid/support/v4/view/ViewPager;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>(Landroid/support/v4/view/ViewPager;)V
a=0;//     .locals 0
a=0;//     .param p1, "viewPager"    # Landroid/support/v4/view/ViewPager;
a=0;//     .annotation build Landroid/annotation/SuppressLint;
a=0;//         value = {
a=0;//             "ValidFragment"
a=0;//         }
a=0;//     .end annotation
a=0;// 
a=0;//     .prologue
a=0;//     .line 39
a=0;//     invoke-direct {p0}, Landroid/support/v4/app/Fragment;-><init>()V
a=0;// 
a=0;//     .line 41
a=0;//     #p0=(Reference,Lcom/twocloo/com/cn/fragment/SelectSexFragment;);
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/fragment/SelectSexFragment;->viewPager:Landroid/support/v4/view/ViewPager;
a=0;// 
a=0;//     .line 42
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method private initview(Landroid/view/View;)V
a=0;//     .locals 1
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 52
a=0;//     sget v0, Lcom/twocloo/com/cn/R$id;->nanshen:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     invoke-virtual {p1, v0}, Landroid/view/View;->findViewById(I)Landroid/view/View;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Landroid/view/View;);
a=0;//     check-cast v0, Landroid/widget/ImageView;
a=0;// 
a=0;//     iput-object v0, p0, Lcom/twocloo/com/cn/fragment/SelectSexFragment;->nanshen:Landroid/widget/ImageView;
a=0;// 
a=0;//     .line 53
a=0;//     sget v0, Lcom/twocloo/com/cn/R$id;->nvshen:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     invoke-virtual {p1, v0}, Landroid/view/View;->findViewById(I)Landroid/view/View;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Landroid/view/View;);
a=0;//     check-cast v0, Landroid/widget/ImageView;
a=0;// 
a=0;//     iput-object v0, p0, Lcom/twocloo/com/cn/fragment/SelectSexFragment;->nvshen:Landroid/widget/ImageView;
a=0;// 
a=0;//     .line 54
a=0;//     sget v0, Lcom/twocloo/com/cn/R$id;->view:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     invoke-virtual {p1, v0}, Landroid/view/View;->findViewById(I)Landroid/view/View;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Landroid/view/View;);
a=0;//     check-cast v0, Landroid/widget/Button;
a=0;// 
a=0;//     iput-object v0, p0, Lcom/twocloo/com/cn/fragment/SelectSexFragment;->next:Landroid/widget/Button;
a=0;// 
a=0;//     .line 55
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/fragment/SelectSexFragment;->nanshen:Landroid/widget/ImageView;
a=0;// 
a=0;//     invoke-virtual {v0, p0}, Landroid/widget/ImageView;->setOnClickListener(Landroid/view/View$OnClickListener;)V
a=0;// 
a=0;//     .line 56
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/fragment/SelectSexFragment;->nvshen:Landroid/widget/ImageView;
a=0;// 
a=0;//     invoke-virtual {v0, p0}, Landroid/widget/ImageView;->setOnClickListener(Landroid/view/View$OnClickListener;)V
a=0;// 
a=0;//     .line 57
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/fragment/SelectSexFragment;->next:Landroid/widget/Button;
a=0;// 
a=0;//     invoke-virtual {v0, p0}, Landroid/widget/Button;->setOnClickListener(Landroid/view/View$OnClickListener;)V
a=0;// 
a=0;//     .line 58
a=0;//     sget v0, Lcom/twocloo/com/cn/R$id;->tiaoguo:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     invoke-virtual {p1, v0}, Landroid/view/View;->findViewById(I)Landroid/view/View;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Landroid/view/View;);
a=0;//     check-cast v0, Landroid/widget/ImageView;
a=0;// 
a=0;//     iput-object v0, p0, Lcom/twocloo/com/cn/fragment/SelectSexFragment;->tiaoguo:Landroid/widget/ImageView;
a=0;// 
a=0;//     .line 59
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/fragment/SelectSexFragment;->tiaoguo:Landroid/widget/ImageView;
a=0;// 
a=0;//     invoke-virtual {v0, p0}, Landroid/widget/ImageView;->setOnClickListener(Landroid/view/View$OnClickListener;)V
a=0;// 
a=0;//     .line 60
a=0;//     sget v0, Lcom/twocloo/com/cn/R$id;->nan_sel:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     invoke-virtual {p1, v0}, Landroid/view/View;->findViewById(I)Landroid/view/View;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Landroid/view/View;);
a=0;//     check-cast v0, Landroid/widget/ImageView;
a=0;// 
a=0;//     iput-object v0, p0, Lcom/twocloo/com/cn/fragment/SelectSexFragment;->nan:Landroid/widget/ImageView;
a=0;// 
a=0;//     .line 61
a=0;//     sget v0, Lcom/twocloo/com/cn/R$id;->nv_sel:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     invoke-virtual {p1, v0}, Landroid/view/View;->findViewById(I)Landroid/view/View;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Landroid/view/View;);
a=0;//     check-cast v0, Landroid/widget/ImageView;
a=0;// 
a=0;//     iput-object v0, p0, Lcom/twocloo/com/cn/fragment/SelectSexFragment;->nv:Landroid/widget/ImageView;
a=0;// 
a=0;//     .line 62
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public onClick(Landroid/view/View;)V
a=0;//     .locals 6
a=0;//     .param p1, "v"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     const/16 v5, 0x8
a=0;// 
a=0;//     #v5=(PosByte);
a=0;//     const/4 v4, 0x2
a=0;// 
a=0;//     #v4=(PosByte);
a=0;//     const/4 v3, 0x0
a=0;// 
a=0;//     #v3=(Null);
a=0;//     const/4 v2, 0x1
a=0;// 
a=0;//     .line 66
a=0;//     #v2=(One);
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/fragment/SelectSexFragment;->nanshen:Landroid/widget/ImageView;
a=0;// 
a=0;//     #v1=(Reference,Landroid/widget/ImageView;);
a=0;//     if-ne p1, v1, :cond_1
a=0;// 
a=0;//     .line 67
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/fragment/SelectSexFragment;->getActivity()Landroid/support/v4/app/FragmentActivity;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-static {v1, v2}, Lcom/twocloo/com/cn/common/LocalStore;->setUserSex(Landroid/content/Context;I)V
a=0;// 
a=0;//     .line 68
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/fragment/SelectSexFragment;->nan:Landroid/widget/ImageView;
a=0;// 
a=0;//     invoke-virtual {v1, v3}, Landroid/widget/ImageView;->setVisibility(I)V
a=0;// 
a=0;//     .line 69
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/fragment/SelectSexFragment;->nv:Landroid/widget/ImageView;
a=0;// 
a=0;//     invoke-virtual {v1, v5}, Landroid/widget/ImageView;->setVisibility(I)V
a=0;// 
a=0;//     .line 70
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/fragment/SelectSexFragment;->viewPager:Landroid/support/v4/view/ViewPager;
a=0;// 
a=0;//     invoke-virtual {v1, v2}, Landroid/support/v4/view/ViewPager;->setCurrentItem(I)V
a=0;// 
a=0;//     .line 85
a=0;//     :cond_0
a=0;//     :goto_0
a=0;//     #v0=(Conflicted);v2=(Integer);
a=0;//     return-void
a=0;// 
a=0;//     .line 71
a=0;//     :cond_1
a=0;//     #v0=(Uninit);v2=(One);
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/fragment/SelectSexFragment;->nvshen:Landroid/widget/ImageView;
a=0;// 
a=0;//     if-ne p1, v1, :cond_2
a=0;// 
a=0;//     .line 72
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/fragment/SelectSexFragment;->nan:Landroid/widget/ImageView;
a=0;// 
a=0;//     invoke-virtual {v1, v5}, Landroid/widget/ImageView;->setVisibility(I)V
a=0;// 
a=0;//     .line 73
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/fragment/SelectSexFragment;->nv:Landroid/widget/ImageView;
a=0;// 
a=0;//     invoke-virtual {v1, v3}, Landroid/widget/ImageView;->setVisibility(I)V
a=0;// 
a=0;//     .line 74
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/fragment/SelectSexFragment;->getActivity()Landroid/support/v4/app/FragmentActivity;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-static {v1, v4}, Lcom/twocloo/com/cn/common/LocalStore;->setUserSex(Landroid/content/Context;I)V
a=0;// 
a=0;//     .line 75
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/fragment/SelectSexFragment;->viewPager:Landroid/support/v4/view/ViewPager;
a=0;// 
a=0;//     invoke-virtual {v1, v2}, Landroid/support/v4/view/ViewPager;->setCurrentItem(I)V
a=0;// 
a=0;//     goto :goto_0
a=0;// 
a=0;//     .line 76
a=0;//     :cond_2
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/fragment/SelectSexFragment;->next:Landroid/widget/Button;
a=0;// 
a=0;//     if-ne p1, v1, :cond_3
a=0;// 
a=0;//     .line 77
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/fragment/SelectSexFragment;->getActivity()Landroid/support/v4/app/FragmentActivity;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-static {v1, v4}, Lcom/twocloo/com/cn/common/LocalStore;->setUserSex(Landroid/content/Context;I)V
a=0;// 
a=0;//     .line 78
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/fragment/SelectSexFragment;->viewPager:Landroid/support/v4/view/ViewPager;
a=0;// 
a=0;//     invoke-virtual {v1, v2}, Landroid/support/v4/view/ViewPager;->setCurrentItem(I)V
a=0;// 
a=0;//     goto :goto_0
a=0;// 
a=0;//     .line 79
a=0;//     :cond_3
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/fragment/SelectSexFragment;->tiaoguo:Landroid/widget/ImageView;
a=0;// 
a=0;//     if-ne p1, v1, :cond_0
a=0;// 
a=0;//     .line 80
a=0;//     new-instance v0, Landroid/content/Intent;
a=0;// 
a=0;//     #v0=(UninitRef,Landroid/content/Intent;);
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/fragment/SelectSexFragment;->getActivity()Landroid/support/v4/app/FragmentActivity;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     const-class v2, Lcom/twocloo/com/cn/activitys/MainActivity;
a=0;// 
a=0;//     #v2=(Reference,Ljava/lang/Class;);
a=0;//     invoke-direct {v0, v1, v2}, Landroid/content/Intent;-><init>(Landroid/content/Context;Ljava/lang/Class;)V
a=0;// 
a=0;//     .line 81
a=0;//     .local v0, "intent":Landroid/content/Intent;
a=0;//     #v0=(Reference,Landroid/content/Intent;);
a=0;//     const-string v1, "id"
a=0;// 
a=0;//     sget v2, Lcom/twocloo/com/cn/R$id;->main_bookshelf:I
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     invoke-virtual {v0, v1, v2}, Landroid/content/Intent;->putExtra(Ljava/lang/String;I)Landroid/content/Intent;
a=0;// 
a=0;//     .line 82
a=0;//     invoke-virtual {p0, v0}, Lcom/twocloo/com/cn/fragment/SelectSexFragment;->startActivity(Landroid/content/Intent;)V
a=0;// 
a=0;//     goto :goto_0
a=0;// .end method
a=0;// 
a=0;// .method public onCreateView(Landroid/view/LayoutInflater;Landroid/view/ViewGroup;Landroid/os/Bundle;)Landroid/view/View;
a=0;//     .locals 3
a=0;//     .param p1, "inflater"    # Landroid/view/LayoutInflater;
a=0;//     .param p2, "container"    # Landroid/view/ViewGroup;
a=0;//     .param p3, "savedInstanceState"    # Landroid/os/Bundle;
a=0;// 
a=0;//     .prologue
a=0;//     .line 46
a=0;//     sget v1, Lcom/twocloo/com/cn/R$layout;->select_sex_fragment:I
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     const/4 v2, 0x0
a=0;// 
a=0;//     #v2=(Null);
a=0;//     invoke-virtual {p1, v1, p2, v2}, Landroid/view/LayoutInflater;->inflate(ILandroid/view/ViewGroup;Z)Landroid/view/View;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 47
a=0;//     .local v0, "view":Landroid/view/View;
a=0;//     #v0=(Reference,Landroid/view/View;);
a=0;//     invoke-direct {p0, v0}, Lcom/twocloo/com/cn/fragment/SelectSexFragment;->initview(Landroid/view/View;)V
a=0;// 
a=0;//     .line 48
a=0;//     return-object v0
a=0;// .end method
}}
