package com.ffcs.inapppaylib.bean.response; class QueryResponse { void a() { int a;
a=0;// .class public Lcom/ffcs/inapppaylib/bean/response/QueryResponse;
a=0;// .super Lcom/ffcs/inapppaylib/bean/response/BaseResponse;
a=0;// .source "QueryResponse.java"
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field private app_name:Ljava/lang/String;
a=0;// 
a=0;// .field private pay_code:Ljava/lang/String;
a=0;// 
a=0;// .field private pay_code_name:Ljava/lang/String;
a=0;// 
a=0;// .field private phone:Ljava/lang/String;
a=0;// 
a=0;// .field private sp_name:Ljava/lang/String;
a=0;// 
a=0;// .field private status:Ljava/lang/String;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 3
a=0;//     invoke-direct {p0}, Lcom/ffcs/inapppaylib/bean/response/BaseResponse;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcom/ffcs/inapppaylib/bean/response/QueryResponse;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public getApp_name()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 13
a=0;//     iget-object v0, p0, Lcom/ffcs/inapppaylib/bean/response/QueryResponse;->app_name:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getPay_code()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 25
a=0;//     iget-object v0, p0, Lcom/ffcs/inapppaylib/bean/response/QueryResponse;->pay_code:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getPay_code_name()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 31
a=0;//     iget-object v0, p0, Lcom/ffcs/inapppaylib/bean/response/QueryResponse;->pay_code_name:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getPhone()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 37
a=0;//     iget-object v0, p0, Lcom/ffcs/inapppaylib/bean/response/QueryResponse;->phone:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getSp_name()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 19
a=0;//     iget-object v0, p0, Lcom/ffcs/inapppaylib/bean/response/QueryResponse;->sp_name:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getStatus()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 43
a=0;//     iget-object v0, p0, Lcom/ffcs/inapppaylib/bean/response/QueryResponse;->status:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public setApp_name(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "app_name"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 16
a=0;//     iput-object p1, p0, Lcom/ffcs/inapppaylib/bean/response/QueryResponse;->app_name:Ljava/lang/String;
a=0;// 
a=0;//     .line 17
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setPay_code(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "pay_code"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 28
a=0;//     iput-object p1, p0, Lcom/ffcs/inapppaylib/bean/response/QueryResponse;->pay_code:Ljava/lang/String;
a=0;// 
a=0;//     .line 29
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setPay_code_name(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "pay_code_name"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 34
a=0;//     iput-object p1, p0, Lcom/ffcs/inapppaylib/bean/response/QueryResponse;->pay_code_name:Ljava/lang/String;
a=0;// 
a=0;//     .line 35
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setPhone(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "phone"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 40
a=0;//     iput-object p1, p0, Lcom/ffcs/inapppaylib/bean/response/QueryResponse;->phone:Ljava/lang/String;
a=0;// 
a=0;//     .line 41
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setSp_name(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "sp_name"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 22
a=0;//     iput-object p1, p0, Lcom/ffcs/inapppaylib/bean/response/QueryResponse;->sp_name:Ljava/lang/String;
a=0;// 
a=0;//     .line 23
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setStatus(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "status"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 46
a=0;//     iput-object p1, p0, Lcom/ffcs/inapppaylib/bean/response/QueryResponse;->status:Ljava/lang/String;
a=0;// 
a=0;//     .line 47
a=0;//     return-void
a=0;// .end method
}}
