package com.tencent.weiyun; class FileManager$UploadFileImp$2 { void a() { int a;
a=0;// .class Lcom/tencent/weiyun/FileManager$UploadFileImp$2;
a=0;// .super Ljava/lang/Thread;
a=0;// .source "ProGuard"
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation system Ldalvik/annotation/EnclosingMethod;
a=0;//     value = Lcom/tencent/weiyun/FileManager$UploadFileImp;->getUploadPermission()V
a=0;// .end annotation
a=0;// 
a=0;// .annotation system Ldalvik/annotation/InnerClass;
a=0;//     accessFlags = 0x0
a=0;//     name = null
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field final synthetic this$1:Lcom/tencent/weiyun/FileManager$UploadFileImp;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>(Lcom/tencent/weiyun/FileManager$UploadFileImp;)V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 297
a=0;//     iput-object p1, p0, Lcom/tencent/weiyun/FileManager$UploadFileImp$2;->this$1:Lcom/tencent/weiyun/FileManager$UploadFileImp;
a=0;// 
a=0;//     invoke-direct {p0}, Ljava/lang/Thread;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcom/tencent/weiyun/FileManager$UploadFileImp$2;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public run()V
a=0;//     .locals 7
a=0;// 
a=0;//     .prologue
a=0;//     .line 300
a=0;//     iget-object v0, p0, Lcom/tencent/weiyun/FileManager$UploadFileImp$2;->this$1:Lcom/tencent/weiyun/FileManager$UploadFileImp;
a=0;// 
a=0;//     #v0=(Reference,Lcom/tencent/weiyun/FileManager$UploadFileImp;);
a=0;//     invoke-static {v0}, Lcom/tencent/weiyun/FileManager$UploadFileImp;->access$400(Lcom/tencent/weiyun/FileManager$UploadFileImp;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-static {v0}, Landroid/net/Uri;->parse(Ljava/lang/String;)Landroid/net/Uri;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 301
a=0;//     new-instance v1, Ljava/lang/StringBuilder;
a=0;// 
a=0;//     #v1=(UninitRef,Ljava/lang/StringBuilder;);
a=0;//     invoke-direct {v1}, Ljava/lang/StringBuilder;-><init>()V
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/StringBuilder;);
a=0;//     invoke-static {}, Landroid/os/SystemClock;->elapsedRealtime()J
a=0;// 
a=0;//     move-result-wide v2
a=0;// 
a=0;//     #v2=(LongLo);v3=(LongHi);
a=0;//     invoke-virtual {v1, v2, v3}, Ljava/lang/StringBuilder;->append(J)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     const-string v2, "__"
a=0;// 
a=0;//     #v2=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v0}, Landroid/net/Uri;->getLastPathSegment()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v1, v0}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 304
a=0;//     const-string v1, "control"
a=0;// 
a=0;//     .line 306
a=0;//     iget-object v2, p0, Lcom/tencent/weiyun/FileManager$UploadFileImp$2;->this$1:Lcom/tencent/weiyun/FileManager$UploadFileImp;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/tencent/weiyun/FileManager$UploadFileImp;->this$0:Lcom/tencent/weiyun/FileManager;
a=0;// 
a=0;//     invoke-static {v2}, Lcom/tencent/weiyun/FileManager;->a(Lcom/tencent/weiyun/FileManager;)Landroid/os/Bundle;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     .line 307
a=0;//     const-string v3, "sha"
a=0;// 
a=0;//     #v3=(Reference,Ljava/lang/String;);
a=0;//     iget-object v4, p0, Lcom/tencent/weiyun/FileManager$UploadFileImp$2;->this$1:Lcom/tencent/weiyun/FileManager$UploadFileImp;
a=0;// 
a=0;//     #v4=(Reference,Lcom/tencent/weiyun/FileManager$UploadFileImp;);
a=0;//     invoke-static {v4}, Lcom/tencent/weiyun/FileManager$UploadFileImp;->access$600(Lcom/tencent/weiyun/FileManager$UploadFileImp;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-virtual {v2, v3, v4}, Landroid/os/Bundle;->putString(Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     .line 308
a=0;//     const-string v3, "md5"
a=0;// 
a=0;//     iget-object v4, p0, Lcom/tencent/weiyun/FileManager$UploadFileImp$2;->this$1:Lcom/tencent/weiyun/FileManager$UploadFileImp;
a=0;// 
a=0;//     invoke-static {v4}, Lcom/tencent/weiyun/FileManager$UploadFileImp;->access$700(Lcom/tencent/weiyun/FileManager$UploadFileImp;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-virtual {v2, v3, v4}, Landroid/os/Bundle;->putString(Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     .line 309
a=0;//     const-string v3, "size"
a=0;// 
a=0;//     new-instance v4, Ljava/lang/StringBuilder;
a=0;// 
a=0;//     #v4=(UninitRef,Ljava/lang/StringBuilder;);
a=0;//     invoke-direct {v4}, Ljava/lang/StringBuilder;-><init>()V
a=0;// 
a=0;//     #v4=(Reference,Ljava/lang/StringBuilder;);
a=0;//     iget-object v5, p0, Lcom/tencent/weiyun/FileManager$UploadFileImp$2;->this$1:Lcom/tencent/weiyun/FileManager$UploadFileImp;
a=0;// 
a=0;//     #v5=(Reference,Lcom/tencent/weiyun/FileManager$UploadFileImp;);
a=0;//     invoke-static {v5}, Lcom/tencent/weiyun/FileManager$UploadFileImp;->access$800(Lcom/tencent/weiyun/FileManager$UploadFileImp;)J
a=0;// 
a=0;//     move-result-wide v5
a=0;// 
a=0;//     #v5=(LongLo);v6=(LongHi);
a=0;//     invoke-virtual {v4, v5, v6}, Ljava/lang/StringBuilder;->append(J)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     const-string v5, ""
a=0;// 
a=0;//     #v5=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v4, v5}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-virtual {v4}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-virtual {v2, v3, v4}, Landroid/os/Bundle;->putString(Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     .line 310
a=0;//     const-string v3, "name"
a=0;// 
a=0;//     invoke-virtual {v2, v3, v0}, Landroid/os/Bundle;->putString(Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     .line 311
a=0;//     const-string v0, "upload_type"
a=0;// 
a=0;//     invoke-virtual {v2, v0, v1}, Landroid/os/Bundle;->putString(Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     .line 315
a=0;//     :try_start_0
a=0;//     iget-object v0, p0, Lcom/tencent/weiyun/FileManager$UploadFileImp$2;->this$1:Lcom/tencent/weiyun/FileManager$UploadFileImp;
a=0;// 
a=0;//     iget-object v0, v0, Lcom/tencent/weiyun/FileManager$UploadFileImp;->this$0:Lcom/tencent/weiyun/FileManager;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/tencent/weiyun/FileManager;->b(Lcom/tencent/weiyun/FileManager;)Lcom/tencent/connect/auth/QQToken;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lcom/tencent/weiyun/FileManager$UploadFileImp$2;->this$1:Lcom/tencent/weiyun/FileManager$UploadFileImp;
a=0;// 
a=0;//     invoke-static {v1}, Lcom/tencent/weiyun/FileManager$UploadFileImp;->access$1000(Lcom/tencent/weiyun/FileManager$UploadFileImp;)Landroid/content/Context;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     iget-object v3, p0, Lcom/tencent/weiyun/FileManager$UploadFileImp$2;->this$1:Lcom/tencent/weiyun/FileManager$UploadFileImp;
a=0;// 
a=0;//     iget-object v4, p0, Lcom/tencent/weiyun/FileManager$UploadFileImp$2;->this$1:Lcom/tencent/weiyun/FileManager$UploadFileImp;
a=0;// 
a=0;//     invoke-static {v4}, Lcom/tencent/weiyun/FileManager$UploadFileImp;->access$1100(Lcom/tencent/weiyun/FileManager$UploadFileImp;)Lcom/tencent/weiyun/FileManager$WeiyunFileType;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-static {v3, v4}, Lcom/tencent/weiyun/FileManager$UploadFileImp;->access$1200(Lcom/tencent/weiyun/FileManager$UploadFileImp;Lcom/tencent/weiyun/FileManager$WeiyunFileType;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     const-string v4, "GET"
a=0;// 
a=0;//     invoke-static {v0, v1, v3, v2, v4}, Lcom/tencent/utils/HttpUtils;->request(Lcom/tencent/connect/auth/QQToken;Landroid/content/Context;Ljava/lang/String;Landroid/os/Bundle;Ljava/lang/String;)Lorg/json/JSONObject;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 316
a=0;//     iget-object v1, p0, Lcom/tencent/weiyun/FileManager$UploadFileImp$2;->this$1:Lcom/tencent/weiyun/FileManager$UploadFileImp;
a=0;// 
a=0;//     invoke-static {v1}, Lcom/tencent/weiyun/FileManager$UploadFileImp;->access$1300(Lcom/tencent/weiyun/FileManager$UploadFileImp;)Landroid/os/Handler;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v1}, Landroid/os/Handler;->obtainMessage()Landroid/os/Message;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     .line 317
a=0;//     const/4 v2, 0x0
a=0;// 
a=0;//     #v2=(Null);
a=0;//     iput v2, v1, Landroid/os/Message;->what:I
a=0;// 
a=0;//     .line 318
a=0;//     iput-object v0, v1, Landroid/os/Message;->obj:Ljava/lang/Object;
a=0;// 
a=0;//     .line 319
a=0;//     iget-object v0, p0, Lcom/tencent/weiyun/FileManager$UploadFileImp$2;->this$1:Lcom/tencent/weiyun/FileManager$UploadFileImp;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/tencent/weiyun/FileManager$UploadFileImp;->access$1300(Lcom/tencent/weiyun/FileManager$UploadFileImp;)Landroid/os/Handler;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Landroid/os/Handler;->sendMessage(Landroid/os/Message;)Z
a=0;//     :try_end_0
a=0;//     .catch Ljava/net/MalformedURLException; {:try_start_0 .. :try_end_0} :catch_0
a=0;//     .catch Ljava/io/IOException; {:try_start_0 .. :try_end_0} :catch_1
a=0;//     .catch Lorg/json/JSONException; {:try_start_0 .. :try_end_0} :catch_2
a=0;//     .catch Lcom/tencent/utils/HttpUtils$NetworkUnavailableException; {:try_start_0 .. :try_end_0} :catch_3
a=0;//     .catch Lcom/tencent/utils/HttpUtils$HttpStatusException; {:try_start_0 .. :try_end_0} :catch_4
a=0;// 
a=0;//     .line 346
a=0;//     :goto_0
a=0;//     #v2=(Conflicted);
a=0;//     return-void
a=0;// 
a=0;//     .line 320
a=0;//     :catch_0
a=0;//     #v2=(Reference,Landroid/os/Bundle;);
a=0;//     move-exception v0
a=0;// 
a=0;//     .line 321
a=0;//     iget-object v1, p0, Lcom/tencent/weiyun/FileManager$UploadFileImp$2;->this$1:Lcom/tencent/weiyun/FileManager$UploadFileImp;
a=0;// 
a=0;//     invoke-static {v1}, Lcom/tencent/weiyun/FileManager$UploadFileImp;->access$1300(Lcom/tencent/weiyun/FileManager$UploadFileImp;)Landroid/os/Handler;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v1}, Landroid/os/Handler;->obtainMessage()Landroid/os/Message;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     .line 322
a=0;//     const/4 v2, -0x3
a=0;// 
a=0;//     #v2=(Byte);
a=0;//     iput v2, v1, Landroid/os/Message;->what:I
a=0;// 
a=0;//     .line 323
a=0;//     invoke-virtual {v0}, Ljava/net/MalformedURLException;->getMessage()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, v1, Landroid/os/Message;->obj:Ljava/lang/Object;
a=0;// 
a=0;//     .line 324
a=0;//     iget-object v0, p0, Lcom/tencent/weiyun/FileManager$UploadFileImp$2;->this$1:Lcom/tencent/weiyun/FileManager$UploadFileImp;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/tencent/weiyun/FileManager$UploadFileImp;->access$1300(Lcom/tencent/weiyun/FileManager$UploadFileImp;)Landroid/os/Handler;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Landroid/os/Handler;->sendMessage(Landroid/os/Message;)Z
a=0;// 
a=0;//     goto :goto_0
a=0;// 
a=0;//     .line 325
a=0;//     :catch_1
a=0;//     #v2=(Reference,Landroid/os/Bundle;);
a=0;//     move-exception v0
a=0;// 
a=0;//     .line 326
a=0;//     iget-object v1, p0, Lcom/tencent/weiyun/FileManager$UploadFileImp$2;->this$1:Lcom/tencent/weiyun/FileManager$UploadFileImp;
a=0;// 
a=0;//     invoke-static {v1}, Lcom/tencent/weiyun/FileManager$UploadFileImp;->access$1300(Lcom/tencent/weiyun/FileManager$UploadFileImp;)Landroid/os/Handler;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v1}, Landroid/os/Handler;->obtainMessage()Landroid/os/Message;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     .line 327
a=0;//     invoke-virtual {v0}, Ljava/io/IOException;->getMessage()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, v1, Landroid/os/Message;->obj:Ljava/lang/Object;
a=0;// 
a=0;//     .line 328
a=0;//     const/4 v0, -0x2
a=0;// 
a=0;//     #v0=(Byte);
a=0;//     iput v0, v1, Landroid/os/Message;->what:I
a=0;// 
a=0;//     .line 329
a=0;//     iget-object v0, p0, Lcom/tencent/weiyun/FileManager$UploadFileImp$2;->this$1:Lcom/tencent/weiyun/FileManager$UploadFileImp;
a=0;// 
a=0;//     #v0=(Reference,Lcom/tencent/weiyun/FileManager$UploadFileImp;);
a=0;//     invoke-static {v0}, Lcom/tencent/weiyun/FileManager$UploadFileImp;->access$1300(Lcom/tencent/weiyun/FileManager$UploadFileImp;)Landroid/os/Handler;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Landroid/os/Handler;->sendMessage(Landroid/os/Message;)Z
a=0;// 
a=0;//     goto :goto_0
a=0;// 
a=0;//     .line 330
a=0;//     :catch_2
a=0;//     move-exception v0
a=0;// 
a=0;//     .line 331
a=0;//     iget-object v1, p0, Lcom/tencent/weiyun/FileManager$UploadFileImp$2;->this$1:Lcom/tencent/weiyun/FileManager$UploadFileImp;
a=0;// 
a=0;//     invoke-static {v1}, Lcom/tencent/weiyun/FileManager$UploadFileImp;->access$1300(Lcom/tencent/weiyun/FileManager$UploadFileImp;)Landroid/os/Handler;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v1}, Landroid/os/Handler;->obtainMessage()Landroid/os/Message;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     .line 332
a=0;//     invoke-virtual {v0}, Lorg/json/JSONException;->getMessage()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, v1, Landroid/os/Message;->obj:Ljava/lang/Object;
a=0;// 
a=0;//     .line 333
a=0;//     const/4 v0, -0x4
a=0;// 
a=0;//     #v0=(Byte);
a=0;//     iput v0, v1, Landroid/os/Message;->what:I
a=0;// 
a=0;//     .line 334
a=0;//     iget-object v0, p0, Lcom/tencent/weiyun/FileManager$UploadFileImp$2;->this$1:Lcom/tencent/weiyun/FileManager$UploadFileImp;
a=0;// 
a=0;//     #v0=(Reference,Lcom/tencent/weiyun/FileManager$UploadFileImp;);
a=0;//     invoke-static {v0}, Lcom/tencent/weiyun/FileManager$UploadFileImp;->access$1300(Lcom/tencent/weiyun/FileManager$UploadFileImp;)Landroid/os/Handler;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Landroid/os/Handler;->sendMessage(Landroid/os/Message;)Z
a=0;// 
a=0;//     goto :goto_0
a=0;// 
a=0;//     .line 335
a=0;//     :catch_3
a=0;//     move-exception v0
a=0;// 
a=0;//     .line 336
a=0;//     iget-object v1, p0, Lcom/tencent/weiyun/FileManager$UploadFileImp$2;->this$1:Lcom/tencent/weiyun/FileManager$UploadFileImp;
a=0;// 
a=0;//     invoke-static {v1}, Lcom/tencent/weiyun/FileManager$UploadFileImp;->access$1300(Lcom/tencent/weiyun/FileManager$UploadFileImp;)Landroid/os/Handler;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v1}, Landroid/os/Handler;->obtainMessage()Landroid/os/Message;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     .line 337
a=0;//     invoke-virtual {v0}, Lcom/tencent/utils/HttpUtils$NetworkUnavailableException;->getMessage()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, v1, Landroid/os/Message;->obj:Ljava/lang/Object;
a=0;// 
a=0;//     .line 338
a=0;//     const/16 v0, -0xa
a=0;// 
a=0;//     #v0=(Byte);
a=0;//     iput v0, v1, Landroid/os/Message;->what:I
a=0;// 
a=0;//     .line 339
a=0;//     iget-object v0, p0, Lcom/tencent/weiyun/FileManager$UploadFileImp$2;->this$1:Lcom/tencent/weiyun/FileManager$UploadFileImp;
a=0;// 
a=0;//     #v0=(Reference,Lcom/tencent/weiyun/FileManager$UploadFileImp;);
a=0;//     invoke-static {v0}, Lcom/tencent/weiyun/FileManager$UploadFileImp;->access$1300(Lcom/tencent/weiyun/FileManager$UploadFileImp;)Landroid/os/Handler;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Landroid/os/Handler;->sendMessage(Landroid/os/Message;)Z
a=0;// 
a=0;//     goto :goto_0
a=0;// 
a=0;//     .line 340
a=0;//     :catch_4
a=0;//     move-exception v0
a=0;// 
a=0;//     .line 341
a=0;//     iget-object v1, p0, Lcom/tencent/weiyun/FileManager$UploadFileImp$2;->this$1:Lcom/tencent/weiyun/FileManager$UploadFileImp;
a=0;// 
a=0;//     invoke-static {v1}, Lcom/tencent/weiyun/FileManager$UploadFileImp;->access$1300(Lcom/tencent/weiyun/FileManager$UploadFileImp;)Landroid/os/Handler;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v1}, Landroid/os/Handler;->obtainMessage()Landroid/os/Message;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     .line 342
a=0;//     invoke-virtual {v0}, Lcom/tencent/utils/HttpUtils$HttpStatusException;->getMessage()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, v1, Landroid/os/Message;->obj:Ljava/lang/Object;
a=0;// 
a=0;//     .line 343
a=0;//     const/16 v0, -0x9
a=0;// 
a=0;//     #v0=(Byte);
a=0;//     iput v0, v1, Landroid/os/Message;->what:I
a=0;// 
a=0;//     .line 344
a=0;//     iget-object v0, p0, Lcom/tencent/weiyun/FileManager$UploadFileImp$2;->this$1:Lcom/tencent/weiyun/FileManager$UploadFileImp;
a=0;// 
a=0;//     #v0=(Reference,Lcom/tencent/weiyun/FileManager$UploadFileImp;);
a=0;//     invoke-static {v0}, Lcom/tencent/weiyun/FileManager$UploadFileImp;->access$1300(Lcom/tencent/weiyun/FileManager$UploadFileImp;)Landroid/os/Handler;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Landroid/os/Handler;->sendMessage(Landroid/os/Message;)Z
a=0;// 
a=0;//     goto/16 :goto_0
a=0;// .end method
}}
