package com.tencent.weiyun; class WeiyunFile { void a() { int a;
a=0;// .class public Lcom/tencent/weiyun/WeiyunFile;
a=0;// .super Ljava/lang/Object;
a=0;// .source "ProGuard"
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field private a:Ljava/lang/String;
a=0;// 
a=0;// .field private b:Ljava/lang/String;
a=0;// 
a=0;// .field private c:Ljava/lang/String;
a=0;// 
a=0;// .field private d:J
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;J)V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 8
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     .line 9
a=0;//     #p0=(Reference,Lcom/tencent/weiyun/WeiyunFile;);
a=0;//     iput-object p1, p0, Lcom/tencent/weiyun/WeiyunFile;->a:Ljava/lang/String;
a=0;// 
a=0;//     .line 10
a=0;//     iput-object p2, p0, Lcom/tencent/weiyun/WeiyunFile;->b:Ljava/lang/String;
a=0;// 
a=0;//     .line 11
a=0;//     iput-object p3, p0, Lcom/tencent/weiyun/WeiyunFile;->c:Ljava/lang/String;
a=0;// 
a=0;//     .line 12
a=0;//     iput-wide p4, p0, Lcom/tencent/weiyun/WeiyunFile;->d:J
a=0;// 
a=0;//     .line 13
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public getCreateTime()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 24
a=0;//     iget-object v0, p0, Lcom/tencent/weiyun/WeiyunFile;->c:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getFileId()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 16
a=0;//     iget-object v0, p0, Lcom/tencent/weiyun/WeiyunFile;->a:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getFileName()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     iget-object v0, p0, Lcom/tencent/weiyun/WeiyunFile;->b:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getFileSize()J
a=0;//     .locals 2
a=0;// 
a=0;//     .prologue
a=0;//     .line 28
a=0;//     iget-wide v0, p0, Lcom/tencent/weiyun/WeiyunFile;->d:J
a=0;// 
a=0;//     #v0=(LongLo);v1=(LongHi);
a=0;//     return-wide v0
a=0;// .end method
a=0;// 
a=0;// .method public setCreateTime(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 40
a=0;//     iput-object p1, p0, Lcom/tencent/weiyun/WeiyunFile;->c:Ljava/lang/String;
a=0;// 
a=0;//     .line 41
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setFileId(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 32
a=0;//     iput-object p1, p0, Lcom/tencent/weiyun/WeiyunFile;->a:Ljava/lang/String;
a=0;// 
a=0;//     .line 33
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setFileName(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 36
a=0;//     iput-object p1, p0, Lcom/tencent/weiyun/WeiyunFile;->b:Ljava/lang/String;
a=0;// 
a=0;//     .line 37
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setFileSize(J)V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 44
a=0;//     iput-wide p1, p0, Lcom/tencent/weiyun/WeiyunFile;->d:J
a=0;// 
a=0;//     .line 45
a=0;//     return-void
a=0;// .end method
}}
