package com.google.gson.internal; class Primitives { void a() { int a;
a=0;// .class public final Lcom/google/gson/internal/Primitives;
a=0;// .super Ljava/lang/Object;
a=0;// .source "Primitives.java"
a=0;// 
a=0;// 
a=0;// # static fields
a=0;// .field private static final PRIMITIVE_TO_WRAPPER_TYPE:Ljava/util/Map;
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "Ljava/util/Map",
a=0;//             "<",
a=0;//             "Ljava/lang/Class",
a=0;//             "<*>;",
a=0;//             "Ljava/lang/Class",
a=0;//             "<*>;>;"
a=0;//         }
a=0;//     .end annotation
a=0;// .end field
a=0;// 
a=0;// .field private static final WRAPPER_TO_PRIMITIVE_TYPE:Ljava/util/Map;
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "Ljava/util/Map",
a=0;//             "<",
a=0;//             "Ljava/lang/Class",
a=0;//             "<*>;",
a=0;//             "Ljava/lang/Class",
a=0;//             "<*>;>;"
a=0;//         }
a=0;//     .end annotation
a=0;// .end field
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method static constructor <clinit>()V
a=0;//     .locals 4
a=0;// 
a=0;//     .prologue
a=0;//     const/16 v2, 0x10
a=0;// 
a=0;//     .line 43
a=0;//     #v2=(PosByte);
a=0;//     new-instance v0, Ljava/util/HashMap;
a=0;// 
a=0;//     #v0=(UninitRef,Ljava/util/HashMap;);
a=0;//     invoke-direct {v0, v2}, Ljava/util/HashMap;-><init>(I)V
a=0;// 
a=0;//     .line 44
a=0;//     .local v0, "primToWrap":Ljava/util/Map;, "Ljava/util/Map<Ljava/lang/Class<*>;Ljava/lang/Class<*>;>;"
a=0;//     #v0=(Reference,Ljava/util/HashMap;);
a=0;//     new-instance v1, Ljava/util/HashMap;
a=0;// 
a=0;//     #v1=(UninitRef,Ljava/util/HashMap;);
a=0;//     invoke-direct {v1, v2}, Ljava/util/HashMap;-><init>(I)V
a=0;// 
a=0;//     .line 46
a=0;//     .local v1, "wrapToPrim":Ljava/util/Map;, "Ljava/util/Map<Ljava/lang/Class<*>;Ljava/lang/Class<*>;>;"
a=0;//     #v1=(Reference,Ljava/util/HashMap;);
a=0;//     sget-object v2, Ljava/lang/Boolean;->TYPE:Ljava/lang/Class;
a=0;// 
a=0;//     #v2=(Reference,Ljava/lang/Class;);
a=0;//     const-class v3, Ljava/lang/Boolean;
a=0;// 
a=0;//     #v3=(Reference,Ljava/lang/Class;);
a=0;//     invoke-static {v0, v1, v2, v3}, Lcom/google/gson/internal/Primitives;->add(Ljava/util/Map;Ljava/util/Map;Ljava/lang/Class;Ljava/lang/Class;)V
a=0;// 
a=0;//     .line 47
a=0;//     sget-object v2, Ljava/lang/Byte;->TYPE:Ljava/lang/Class;
a=0;// 
a=0;//     const-class v3, Ljava/lang/Byte;
a=0;// 
a=0;//     invoke-static {v0, v1, v2, v3}, Lcom/google/gson/internal/Primitives;->add(Ljava/util/Map;Ljava/util/Map;Ljava/lang/Class;Ljava/lang/Class;)V
a=0;// 
a=0;//     .line 48
a=0;//     sget-object v2, Ljava/lang/Character;->TYPE:Ljava/lang/Class;
a=0;// 
a=0;//     const-class v3, Ljava/lang/Character;
a=0;// 
a=0;//     invoke-static {v0, v1, v2, v3}, Lcom/google/gson/internal/Primitives;->add(Ljava/util/Map;Ljava/util/Map;Ljava/lang/Class;Ljava/lang/Class;)V
a=0;// 
a=0;//     .line 49
a=0;//     sget-object v2, Ljava/lang/Double;->TYPE:Ljava/lang/Class;
a=0;// 
a=0;//     const-class v3, Ljava/lang/Double;
a=0;// 
a=0;//     invoke-static {v0, v1, v2, v3}, Lcom/google/gson/internal/Primitives;->add(Ljava/util/Map;Ljava/util/Map;Ljava/lang/Class;Ljava/lang/Class;)V
a=0;// 
a=0;//     .line 50
a=0;//     sget-object v2, Ljava/lang/Float;->TYPE:Ljava/lang/Class;
a=0;// 
a=0;//     const-class v3, Ljava/lang/Float;
a=0;// 
a=0;//     invoke-static {v0, v1, v2, v3}, Lcom/google/gson/internal/Primitives;->add(Ljava/util/Map;Ljava/util/Map;Ljava/lang/Class;Ljava/lang/Class;)V
a=0;// 
a=0;//     .line 51
a=0;//     sget-object v2, Ljava/lang/Integer;->TYPE:Ljava/lang/Class;
a=0;// 
a=0;//     const-class v3, Ljava/lang/Integer;
a=0;// 
a=0;//     invoke-static {v0, v1, v2, v3}, Lcom/google/gson/internal/Primitives;->add(Ljava/util/Map;Ljava/util/Map;Ljava/lang/Class;Ljava/lang/Class;)V
a=0;// 
a=0;//     .line 52
a=0;//     sget-object v2, Ljava/lang/Long;->TYPE:Ljava/lang/Class;
a=0;// 
a=0;//     const-class v3, Ljava/lang/Long;
a=0;// 
a=0;//     invoke-static {v0, v1, v2, v3}, Lcom/google/gson/internal/Primitives;->add(Ljava/util/Map;Ljava/util/Map;Ljava/lang/Class;Ljava/lang/Class;)V
a=0;// 
a=0;//     .line 53
a=0;//     sget-object v2, Ljava/lang/Short;->TYPE:Ljava/lang/Class;
a=0;// 
a=0;//     const-class v3, Ljava/lang/Short;
a=0;// 
a=0;//     invoke-static {v0, v1, v2, v3}, Lcom/google/gson/internal/Primitives;->add(Ljava/util/Map;Ljava/util/Map;Ljava/lang/Class;Ljava/lang/Class;)V
a=0;// 
a=0;//     .line 54
a=0;//     sget-object v2, Ljava/lang/Void;->TYPE:Ljava/lang/Class;
a=0;// 
a=0;//     const-class v3, Ljava/lang/Void;
a=0;// 
a=0;//     invoke-static {v0, v1, v2, v3}, Lcom/google/gson/internal/Primitives;->add(Ljava/util/Map;Ljava/util/Map;Ljava/lang/Class;Ljava/lang/Class;)V
a=0;// 
a=0;//     .line 56
a=0;//     invoke-static {v0}, Ljava/util/Collections;->unmodifiableMap(Ljava/util/Map;)Ljava/util/Map;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     sput-object v2, Lcom/google/gson/internal/Primitives;->PRIMITIVE_TO_WRAPPER_TYPE:Ljava/util/Map;
a=0;// 
a=0;//     .line 57
a=0;//     invoke-static {v1}, Ljava/util/Collections;->unmodifiableMap(Ljava/util/Map;)Ljava/util/Map;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     sput-object v2, Lcom/google/gson/internal/Primitives;->WRAPPER_TO_PRIMITIVE_TYPE:Ljava/util/Map;
a=0;// 
a=0;//     .line 58
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method private constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 32
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcom/google/gson/internal/Primitives;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method private static add(Ljava/util/Map;Ljava/util/Map;Ljava/lang/Class;Ljava/lang/Class;)V
a=0;//     .locals 0
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "(",
a=0;//             "Ljava/util/Map",
a=0;//             "<",
a=0;//             "Ljava/lang/Class",
a=0;//             "<*>;",
a=0;//             "Ljava/lang/Class",
a=0;//             "<*>;>;",
a=0;//             "Ljava/util/Map",
a=0;//             "<",
a=0;//             "Ljava/lang/Class",
a=0;//             "<*>;",
a=0;//             "Ljava/lang/Class",
a=0;//             "<*>;>;",
a=0;//             "Ljava/lang/Class",
a=0;//             "<*>;",
a=0;//             "Ljava/lang/Class",
a=0;//             "<*>;)V"
a=0;//         }
a=0;//     .end annotation
a=0;// 
a=0;//     .prologue
a=0;//     .line 62
a=0;//     .local p0, "forward":Ljava/util/Map;, "Ljava/util/Map<Ljava/lang/Class<*>;Ljava/lang/Class<*>;>;"
a=0;//     .local p1, "backward":Ljava/util/Map;, "Ljava/util/Map<Ljava/lang/Class<*>;Ljava/lang/Class<*>;>;"
a=0;//     .local p2, "key":Ljava/lang/Class;, "Ljava/lang/Class<*>;"
a=0;//     .local p3, "value":Ljava/lang/Class;, "Ljava/lang/Class<*>;"
a=0;//     invoke-interface {p0, p2, p3}, Ljava/util/Map;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
a=0;// 
a=0;//     .line 63
a=0;//     invoke-interface {p1, p3, p2}, Ljava/util/Map;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
a=0;// 
a=0;//     .line 64
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static isPrimitive(Ljava/lang/reflect/Type;)Z
a=0;//     .locals 1
a=0;//     .param p0, "type"    # Ljava/lang/reflect/Type;
a=0;// 
a=0;//     .prologue
a=0;//     .line 70
a=0;//     sget-object v0, Lcom/google/gson/internal/Primitives;->PRIMITIVE_TO_WRAPPER_TYPE:Ljava/util/Map;
a=0;// 
a=0;//     #v0=(Reference,Ljava/util/Map;);
a=0;//     invoke-interface {v0, p0}, Ljava/util/Map;->containsKey(Ljava/lang/Object;)Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static isWrapperType(Ljava/lang/reflect/Type;)Z
a=0;//     .locals 2
a=0;//     .param p0, "type"    # Ljava/lang/reflect/Type;
a=0;// 
a=0;//     .prologue
a=0;//     .line 80
a=0;//     sget-object v0, Lcom/google/gson/internal/Primitives;->WRAPPER_TO_PRIMITIVE_TYPE:Ljava/util/Map;
a=0;// 
a=0;//     #v0=(Reference,Ljava/util/Map;);
a=0;//     invoke-static {p0}, Lcom/google/gson/internal/$Gson$Preconditions;->checkNotNull(Ljava/lang/Object;)Ljava/lang/Object;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/Object;);
a=0;//     invoke-interface {v0, v1}, Ljava/util/Map;->containsKey(Ljava/lang/Object;)Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static unwrap(Ljava/lang/Class;)Ljava/lang/Class;
a=0;//     .locals 3
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "<T:",
a=0;//             "Ljava/lang/Object;",
a=0;//             ">(",
a=0;//             "Ljava/lang/Class",
a=0;//             "<TT;>;)",
a=0;//             "Ljava/lang/Class",
a=0;//             "<TT;>;"
a=0;//         }
a=0;//     .end annotation
a=0;// 
a=0;//     .prologue
a=0;//     .line 113
a=0;//     .local p0, "type":Ljava/lang/Class;, "Ljava/lang/Class<TT;>;"
a=0;//     sget-object v1, Lcom/google/gson/internal/Primitives;->WRAPPER_TO_PRIMITIVE_TYPE:Ljava/util/Map;
a=0;// 
a=0;//     #v1=(Reference,Ljava/util/Map;);
a=0;//     invoke-static {p0}, Lcom/google/gson/internal/$Gson$Preconditions;->checkNotNull(Ljava/lang/Object;)Ljava/lang/Object;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     #v2=(Reference,Ljava/lang/Object;);
a=0;//     invoke-interface {v1, v2}, Ljava/util/Map;->get(Ljava/lang/Object;)Ljava/lang/Object;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/Object;);
a=0;//     check-cast v0, Ljava/lang/Class;
a=0;// 
a=0;//     .line 115
a=0;//     .local v0, "unwrapped":Ljava/lang/Class;, "Ljava/lang/Class<TT;>;"
a=0;//     if-nez v0, :cond_0
a=0;// 
a=0;//     .end local p0    # "type":Ljava/lang/Class;, "Ljava/lang/Class<TT;>;"
a=0;//     :goto_0
a=0;//     return-object p0
a=0;// 
a=0;//     .restart local p0    # "type":Ljava/lang/Class;, "Ljava/lang/Class<TT;>;"
a=0;//     :cond_0
a=0;//     move-object p0, v0
a=0;// 
a=0;//     goto :goto_0
a=0;// .end method
a=0;// 
a=0;// .method public static wrap(Ljava/lang/Class;)Ljava/lang/Class;
a=0;//     .locals 3
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "<T:",
a=0;//             "Ljava/lang/Object;",
a=0;//             ">(",
a=0;//             "Ljava/lang/Class",
a=0;//             "<TT;>;)",
a=0;//             "Ljava/lang/Class",
a=0;//             "<TT;>;"
a=0;//         }
a=0;//     .end annotation
a=0;// 
a=0;//     .prologue
a=0;//     .line 96
a=0;//     .local p0, "type":Ljava/lang/Class;, "Ljava/lang/Class<TT;>;"
a=0;//     sget-object v1, Lcom/google/gson/internal/Primitives;->PRIMITIVE_TO_WRAPPER_TYPE:Ljava/util/Map;
a=0;// 
a=0;//     #v1=(Reference,Ljava/util/Map;);
a=0;//     invoke-static {p0}, Lcom/google/gson/internal/$Gson$Preconditions;->checkNotNull(Ljava/lang/Object;)Ljava/lang/Object;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     #v2=(Reference,Ljava/lang/Object;);
a=0;//     invoke-interface {v1, v2}, Ljava/util/Map;->get(Ljava/lang/Object;)Ljava/lang/Object;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/Object;);
a=0;//     check-cast v0, Ljava/lang/Class;
a=0;// 
a=0;//     .line 98
a=0;//     .local v0, "wrapped":Ljava/lang/Class;, "Ljava/lang/Class<TT;>;"
a=0;//     if-nez v0, :cond_0
a=0;// 
a=0;//     .end local p0    # "type":Ljava/lang/Class;, "Ljava/lang/Class<TT;>;"
a=0;//     :goto_0
a=0;//     return-object p0
a=0;// 
a=0;//     .restart local p0    # "type":Ljava/lang/Class;, "Ljava/lang/Class<TT;>;"
a=0;//     :cond_0
a=0;//     move-object p0, v0
a=0;// 
a=0;//     goto :goto_0
a=0;// .end method
}}
