package cn.waps; class cn { void a() { int a;
a=0;// .class Lcn/waps/cn;
a=0;// .super Ljava/lang/Thread;
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field final synthetic a:Lcn/waps/cm;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>(Lcn/waps/cm;)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-object p1, p0, Lcn/waps/cn;->a:Lcn/waps/cm;
a=0;// 
a=0;//     invoke-direct {p0}, Ljava/lang/Thread;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcn/waps/cn;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public run()V
a=0;//     .locals 3
a=0;// 
a=0;//     new-instance v0, Ljava/lang/StringBuilder;
a=0;// 
a=0;//     #v0=(UninitRef,Ljava/lang/StringBuilder;);
a=0;//     invoke-direct {v0}, Ljava/lang/StringBuilder;-><init>()V
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/StringBuilder;);
a=0;//     const-string v1, "&publisher_app_id="
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lcn/waps/cn;->a:Lcn/waps/cm;
a=0;// 
a=0;//     iget-object v1, v1, Lcn/waps/cm;->b:Lcn/waps/bw;
a=0;// 
a=0;//     invoke-static {v1}, Lcn/waps/bw;->i(Lcn/waps/bw;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, "&publisher_user_id="
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lcn/waps/cn;->a:Lcn/waps/cm;
a=0;// 
a=0;//     iget-object v1, v1, Lcn/waps/cm;->b:Lcn/waps/bw;
a=0;// 
a=0;//     invoke-static {v1}, Lcn/waps/bw;->j(Lcn/waps/bw;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, "&"
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lcn/waps/cn;->a:Lcn/waps/cm;
a=0;// 
a=0;//     iget-object v1, v1, Lcn/waps/cm;->b:Lcn/waps/bw;
a=0;// 
a=0;//     invoke-static {v1}, Lcn/waps/bw;->e(Lcn/waps/bw;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lcn/waps/cn;->a:Lcn/waps/cm;
a=0;// 
a=0;//     iget-object v1, v1, Lcn/waps/cm;->b:Lcn/waps/bw;
a=0;// 
a=0;//     invoke-static {v1}, Lcn/waps/bw;->f(Lcn/waps/bw;)Lcn/waps/ag;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     iget-object v2, p0, Lcn/waps/cn;->a:Lcn/waps/cm;
a=0;// 
a=0;//     #v2=(Reference,Lcn/waps/cm;);
a=0;//     iget-object v2, v2, Lcn/waps/cm;->a:Lcn/waps/AdInfo;
a=0;// 
a=0;//     invoke-virtual {v2}, Lcn/waps/AdInfo;->f()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-virtual {v1, v2, v0}, Lcn/waps/ag;->a(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     return-void
a=0;// .end method
}}
