package com.slidingmenu.lib; class MenuInterface { void a() { int a;
a=0;// .class public interface abstract Lcom/slidingmenu/lib/MenuInterface;
a=0;// .super Ljava/lang/Object;
a=0;// .source "MenuInterface.java"
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public abstract drawFade(Landroid/graphics/Canvas;ILcom/slidingmenu/lib/CustomViewBehind;Landroid/view/View;)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract drawSelector(Landroid/view/View;Landroid/graphics/Canvas;F)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract drawShadow(Landroid/graphics/Canvas;Landroid/graphics/drawable/Drawable;I)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract getAbsLeftBound(Lcom/slidingmenu/lib/CustomViewBehind;Landroid/view/View;)I
a=0;// .end method
a=0;// 
a=0;// .method public abstract getAbsRightBound(Lcom/slidingmenu/lib/CustomViewBehind;Landroid/view/View;)I
a=0;// .end method
a=0;// 
a=0;// .method public abstract getMenuLeft(Lcom/slidingmenu/lib/CustomViewBehind;Landroid/view/View;)I
a=0;// .end method
a=0;// 
a=0;// .method public abstract marginTouchAllowed(Landroid/view/View;II)Z
a=0;// .end method
a=0;// 
a=0;// .method public abstract menuClosedSlideAllowed(I)Z
a=0;// .end method
a=0;// 
a=0;// .method public abstract menuOpenSlideAllowed(I)Z
a=0;// .end method
a=0;// 
a=0;// .method public abstract menuOpenTouchAllowed(Landroid/view/View;II)Z
a=0;// .end method
a=0;// 
a=0;// .method public abstract menuTouchInQuickReturn(Landroid/view/View;II)Z
a=0;// .end method
a=0;// 
a=0;// .method public abstract scrollBehindTo(IILcom/slidingmenu/lib/CustomViewBehind;F)V
a=0;// .end method
}}
