package mm.purchasesdk.core.protocol; class MessengerInfo { void a() { int a;
a=0;// .class public Lmm/purchasesdk/core/protocol/MessengerInfo;
a=0;// .super Ljava/lang/Object;
a=0;// 
a=0;// 
a=0;// # static fields
a=0;// .field private static final APKSIGNTURE:Ljava/lang/String; = "APKSIGNTURE"
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field private final APKPATH:Ljava/lang/String;
a=0;// 
a=0;// .field private final APKPKI:Ljava/lang/String;
a=0;// 
a=0;// .field private final APKSHA:Ljava/lang/String;
a=0;// 
a=0;// .field private final APPID:Ljava/lang/String;
a=0;// 
a=0;// .field private final APPKEY:Ljava/lang/String;
a=0;// 
a=0;// .field private final APPTYPE:Ljava/lang/String;
a=0;// 
a=0;// .field private final APPURL:Ljava/lang/String;
a=0;// 
a=0;// .field private final AUTHSTR:Ljava/lang/String;
a=0;// 
a=0;// .field private final CERTCONTENT:Ljava/lang/String;
a=0;// 
a=0;// .field private final CHANNELID:Ljava/lang/String;
a=0;// 
a=0;// .field private final CLASSESHA1:Ljava/lang/String;
a=0;// 
a=0;// .field private final COPYRIGHTCERT:Ljava/lang/String;
a=0;// 
a=0;// .field private final DYANSWER:Ljava/lang/String;
a=0;// 
a=0;// .field private final DYQUESTION:Ljava/lang/String;
a=0;// 
a=0;// .field private final IDTOKEN:Ljava/lang/String;
a=0;// 
a=0;// .field private final IDTOKEN_VERF:Ljava/lang/String;
a=0;// 
a=0;// .field private final LEFTDAY:Ljava/lang/String;
a=0;// 
a=0;// .field private final MARKSTATUS:Ljava/lang/String;
a=0;// 
a=0;// .field private final MESSAGE:Ljava/lang/String;
a=0;// 
a=0;// .field private final MMQRYURL:Ljava/lang/String;
a=0;// 
a=0;// .field private MMQry_URL:Ljava/lang/String;
a=0;// 
a=0;// .field private final MSISDNTYPE:Ljava/lang/String;
a=0;// 
a=0;// .field private MSISDNType:Ljava/lang/String;
a=0;// 
a=0;// .field private final NEXTCYCLE:Ljava/lang/String;
a=0;// 
a=0;// .field private final ORDERCOUNT:Ljava/lang/String;
a=0;// 
a=0;// .field private final ORDERID:Ljava/lang/String;
a=0;// 
a=0;// .field private final ORDERTYPE:Ljava/lang/String;
a=0;// 
a=0;// .field private final PACKAGE:Ljava/lang/String;
a=0;// 
a=0;// .field private final PAYCODE:Ljava/lang/String;
a=0;// 
a=0;// .field private final PAYCODESTYLE:Ljava/lang/String;
a=0;// 
a=0;// .field private final PAYCODEWTOS:Ljava/lang/String;
a=0;// 
a=0;// .field private final PHONENUM:Ljava/lang/String;
a=0;// 
a=0;// .field private final PRODUCTINFO:Ljava/lang/String;
a=0;// 
a=0;// .field private final PRODUCTKEYS:Ljava/lang/String;
a=0;// 
a=0;// .field private final PROGRAMID:Ljava/lang/String;
a=0;// 
a=0;// .field private final PROMPTMSG:Ljava/lang/String;
a=0;// 
a=0;// .field private final PROMPTURL:Ljava/lang/String;
a=0;// 
a=0;// .field private final PURCHASECODE:Ljava/lang/String;
a=0;// 
a=0;// .field private final RANNUM:Ljava/lang/String;
a=0;// 
a=0;// .field private final REFERERURL:Ljava/lang/String;
a=0;// 
a=0;// .field private final SESSESIONID:Ljava/lang/String;
a=0;// 
a=0;// .field private final STACKMARK:Ljava/lang/String;
a=0;// 
a=0;// .field private final TASKID:Ljava/lang/String;
a=0;// 
a=0;// .field private final TIMESTAMP:Ljava/lang/String;
a=0;// 
a=0;// .field private final TRADEID:Ljava/lang/String;
a=0;// 
a=0;// .field private final TRADEIDQUERY:Ljava/lang/String;
a=0;// 
a=0;// .field private final USERDATA:Ljava/lang/String;
a=0;// 
a=0;// .field private final VERSION:Ljava/lang/String;
a=0;// 
a=0;// .field private final WAPQRYURL:Ljava/lang/String;
a=0;// 
a=0;// .field private WAPQry_URL:Ljava/lang/String;
a=0;// 
a=0;// .field private mApkPKI:Ljava/lang/String;
a=0;// 
a=0;// .field private mApkPath:Ljava/lang/String;
a=0;// 
a=0;// .field private mApkSHA:Ljava/lang/String;
a=0;// 
a=0;// .field private mApksignture:Ljava/lang/String;
a=0;// 
a=0;// .field private mAppID:Ljava/lang/String;
a=0;// 
a=0;// .field private mAppKey:Ljava/lang/String;
a=0;// 
a=0;// .field private mAppType:Ljava/lang/String;
a=0;// 
a=0;// .field private mAppUrl:Ljava/lang/String;
a=0;// 
a=0;// .field private mAuthstr:Ljava/lang/String;
a=0;// 
a=0;// .field private mChannelID:Ljava/lang/String;
a=0;// 
a=0;// .field private mClasseSha1:Ljava/lang/String;
a=0;// 
a=0;// .field private mCopyrightCert:Ljava/lang/String;
a=0;// 
a=0;// .field private mDyAnswer:Ljava/lang/String;
a=0;// 
a=0;// .field private mDyQuestion:Ljava/lang/String;
a=0;// 
a=0;// .field private mHandler:Landroid/os/Handler;
a=0;// 
a=0;// .field private mIDToken:Ljava/lang/String;
a=0;// 
a=0;// .field private mIdtoken_verf:Ljava/lang/String;
a=0;// 
a=0;// .field private mLeftDay:Ljava/lang/String;
a=0;// 
a=0;// .field private mMarkStatus:I
a=0;// 
a=0;// .field private mMessage:Ljava/lang/String;
a=0;// 
a=0;// .field private mNextCycle:Z
a=0;// 
a=0;// .field private mOrderCount:I
a=0;// 
a=0;// .field private mOrderID:Ljava/lang/String;
a=0;// 
a=0;// .field private mOrderType:Ljava/lang/String;
a=0;// 
a=0;// .field private mPackageName:Ljava/lang/String;
a=0;// 
a=0;// .field private mPaycode:Ljava/lang/String;
a=0;// 
a=0;// .field private mPaycodeStyle:I
a=0;// 
a=0;// .field private mPhone:Ljava/lang/String;
a=0;// 
a=0;// .field private mProductInfo:Landroid/os/Bundle;
a=0;// 
a=0;// .field private mProductKey:Ljava/util/ArrayList;
a=0;// 
a=0;// .field private mProgramID:Ljava/lang/String;
a=0;// 
a=0;// .field private mPromptMsg:Ljava/lang/String;
a=0;// 
a=0;// .field private mPromptUrl:Ljava/lang/String;
a=0;// 
a=0;// .field private mPurchasecode:I
a=0;// 
a=0;// .field private mRannum:Ljava/lang/String;
a=0;// 
a=0;// .field private mRefleshUrl:Ljava/lang/String;
a=0;// 
a=0;// .field private mResult:I
a=0;// 
a=0;// .field private mSessionID:Ljava/lang/String;
a=0;// 
a=0;// .field private mStackMark:Ljava/lang/String;
a=0;// 
a=0;// .field private mTaskID:Ljava/lang/String;
a=0;// 
a=0;// .field private mTimeStamp:Ljava/lang/String;
a=0;// 
a=0;// .field private mTradeID:Ljava/lang/String;
a=0;// 
a=0;// .field private mTradeIDQuery:Z
a=0;// 
a=0;// .field private mUserData:Ljava/lang/String;
a=0;// 
a=0;// .field private mVersion:Ljava/lang/String;
a=0;// 
a=0;// .field private mpaycodewtos:I
a=0;// 
a=0;// .field private paycodeSaved:Z
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>()V
a=0;//     .locals 2
a=0;// 
a=0;//     const/4 v1, 0x0
a=0;// 
a=0;//     #v1=(Null);
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lmm/purchasesdk/core/protocol/MessengerInfo;);
a=0;//     const-string v0, "APPID"
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->APPID:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "APPKEY"
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->APPKEY:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "PAYCODE"
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->PAYCODE:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "PROGRAMID"
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->PROGRAMID:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "STACKMARK"
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->STACKMARK:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "ORDERCOUNT"
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->ORDERCOUNT:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "NEXTCYCLE"
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->NEXTCYCLE:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "TRADEID"
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->TRADEID:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "TIMESTAMP"
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->TIMESTAMP:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "TRADEIDQUERY"
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->TRADEIDQUERY:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "PURCHASECODE"
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->PURCHASECODE:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "COPYRIGHTCERT"
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->COPYRIGHTCERT:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "CHANNELID"
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->CHANNELID:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "LEFTDAY"
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->LEFTDAY:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "ORDERID"
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->ORDERID:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "ORDERTYPE"
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->ORDERTYPE:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "SESSESIONID"
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->SESSESIONID:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "CERTCONTENT"
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->CERTCONTENT:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "APKPATH"
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->APKPATH:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "VERSION"
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->VERSION:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "CLASSESHA1"
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->CLASSESHA1:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "USERDATA"
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->USERDATA:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "MESSAGE"
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->MESSAGE:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "PACKAGE"
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->PACKAGE:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "TASKID"
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->TASKID:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "RANNUM"
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->RANNUM:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "IDTOKEN"
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->IDTOKEN:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "IDTOKEN_VERF"
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->IDTOKEN_VERF:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "AUTHSTR"
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->AUTHSTR:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "MARKSTATUS"
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->MARKSTATUS:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "DYQUESTION"
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->DYQUESTION:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "DYANSWER"
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->DYANSWER:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "PAYCODESTYLE"
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->PAYCODESTYLE:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "PAYCODEWTOS"
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->PAYCODEWTOS:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "PRODUCTINFO"
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->PRODUCTINFO:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "PRODUCTKEYS"
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->PRODUCTKEYS:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "PHONENUM"
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->PHONENUM:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "PROMPTMSG"
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->PROMPTMSG:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "PROMPTURL"
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->PROMPTURL:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "APKSHA"
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->APKSHA:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "APKPKI"
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->APKPKI:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "MSISDNTYPE"
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->MSISDNTYPE:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "WAPQRYURL"
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->WAPQRYURL:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "MMQRYURL"
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->MMQRYURL:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "APPTYPE"
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->APPTYPE:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "APPURL"
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->APPURL:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "REFERERURL"
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->REFERERURL:Ljava/lang/String;
a=0;// 
a=0;//     iput-boolean v1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mNextCycle:Z
a=0;// 
a=0;//     iput-boolean v1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mTradeIDQuery:Z
a=0;// 
a=0;//     const/4 v0, -0x1
a=0;// 
a=0;//     #v0=(Byte);
a=0;//     iput v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mPaycodeStyle:I
a=0;// 
a=0;//     iput v1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mpaycodewtos:I
a=0;// 
a=0;//     iput v1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mResult:I
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public getApkPKI()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     iget-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mApkPKI:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getApkPath()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     iget-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mApkPath:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getApkSHA()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     iget-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mApkSHA:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0}, Ljava/lang/String;->trim()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getApksignture()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     iget-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mApksignture:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getAppID()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     iget-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mAppID:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getAppKey()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     iget-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mAppKey:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getAppType()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     iget-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mAppType:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getAppUrl()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     iget-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mAppUrl:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getAuthstr()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     iget-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mAuthstr:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getChannelID()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     iget-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mChannelID:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getClasseSha1()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     iget-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mClasseSha1:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getCopyrightCert()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     iget-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mCopyrightCert:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getDyAnswer()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     iget-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mDyAnswer:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getDyQuestion()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     iget-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mDyQuestion:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getHandler()Landroid/os/Handler;
a=0;//     .locals 1
a=0;// 
a=0;//     iget-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mHandler:Landroid/os/Handler;
a=0;// 
a=0;//     #v0=(Reference,Landroid/os/Handler;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getIDToken()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     iget-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mIDToken:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getIdtoken_verf()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     iget-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mIdtoken_verf:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getLeftDay()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     iget-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mLeftDay:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getMMQry_URL()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     iget-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->MMQry_URL:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getMSISDNType()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     iget-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->MSISDNType:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getMarkStatus()I
a=0;//     .locals 1
a=0;// 
a=0;//     iget v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mMarkStatus:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getMessage()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     iget-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mMessage:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getOrderCount()I
a=0;//     .locals 1
a=0;// 
a=0;//     iget v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mOrderCount:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getOrderID()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     iget-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mOrderID:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getOrderType()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     iget-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mOrderType:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getPackageName()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     iget-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mPackageName:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getPaycode()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     iget-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mPaycode:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getProductInfo()Lmm/purchasesdk/core/billing/ProductInfo;
a=0;//     .locals 2
a=0;// 
a=0;//     new-instance v0, Lmm/purchasesdk/core/billing/ProductInfo;
a=0;// 
a=0;//     #v0=(UninitRef,Lmm/purchasesdk/core/billing/ProductInfo;);
a=0;//     invoke-direct {v0}, Lmm/purchasesdk/core/billing/ProductInfo;-><init>()V
a=0;// 
a=0;//     #v0=(Reference,Lmm/purchasesdk/core/billing/ProductInfo;);
a=0;//     iget-object v1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mProductInfo:Landroid/os/Bundle;
a=0;// 
a=0;//     #v1=(Reference,Landroid/os/Bundle;);
a=0;//     invoke-virtual {v0, v1}, Lmm/purchasesdk/core/billing/ProductInfo;->setInfo(Landroid/os/Bundle;)V
a=0;// 
a=0;//     iget-object v1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mProductKey:Ljava/util/ArrayList;
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Lmm/purchasesdk/core/billing/ProductInfo;->setmInfoKey(Ljava/util/ArrayList;)V
a=0;// 
a=0;//     iget-object v1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mPhone:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Lmm/purchasesdk/core/billing/ProductInfo;->setMobilePhone(Ljava/lang/String;)V
a=0;// 
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getProgramID()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     iget-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mProgramID:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getPromptMsg()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     iget-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mPromptMsg:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getPromptUrl()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     iget-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mPromptUrl:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getPurchasecode()I
a=0;//     .locals 3
a=0;// 
a=0;//     const-string v0, "setpurchasecode"
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     new-instance v1, Ljava/lang/StringBuilder;
a=0;// 
a=0;//     #v1=(UninitRef,Ljava/lang/StringBuilder;);
a=0;//     invoke-direct {v1}, Ljava/lang/StringBuilder;-><init>()V
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/StringBuilder;);
a=0;//     const-string v2, "mpurchasecode ="
a=0;// 
a=0;//     #v2=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     iget v2, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mPurchasecode:I
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v1}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-static {v0, v1}, Lmm/purchasesdk/core/utils/LogUtil;->d(Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     iget v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mPurchasecode:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getRannum()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     iget-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mRannum:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getRefleshUrl()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     iget-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mRefleshUrl:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getResult()I
a=0;//     .locals 1
a=0;// 
a=0;//     iget v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mResult:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getSessionID()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     iget-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mSessionID:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getStackMark()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     iget-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mStackMark:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getTaskID()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     iget-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mTaskID:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getTimeStamp()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     iget-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mTimeStamp:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getTradeID()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     iget-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mTradeID:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getUserData()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     iget-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mUserData:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getVersion()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     iget-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mVersion:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getWAPQry_URL()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     iget-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->WAPQry_URL:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public isPaycodeSaved()Z
a=0;//     .locals 1
a=0;// 
a=0;//     iget-boolean v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->paycodeSaved:Z
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public isPaycodeStyle()I
a=0;//     .locals 1
a=0;// 
a=0;//     iget v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mPaycodeStyle:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public isPaycodewtos()I
a=0;//     .locals 1
a=0;// 
a=0;//     iget v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mpaycodewtos:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public isTradeIDQuery()Z
a=0;//     .locals 1
a=0;// 
a=0;//     iget-boolean v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mTradeIDQuery:Z
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public ismNextCycle()Z
a=0;//     .locals 1
a=0;// 
a=0;//     iget-boolean v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mNextCycle:Z
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public readBundle(Landroid/os/Bundle;)V
a=0;//     .locals 1
a=0;// 
a=0;//     const-string v0, "APPID"
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {p1, v0}, Landroid/os/Bundle;->getString(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mAppID:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "APPKEY"
a=0;// 
a=0;//     invoke-virtual {p1, v0}, Landroid/os/Bundle;->getString(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mAppKey:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "PAYCODE"
a=0;// 
a=0;//     invoke-virtual {p1, v0}, Landroid/os/Bundle;->getString(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mPaycode:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "PROGRAMID"
a=0;// 
a=0;//     invoke-virtual {p1, v0}, Landroid/os/Bundle;->getString(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mProgramID:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "STACKMARK"
a=0;// 
a=0;//     invoke-virtual {p1, v0}, Landroid/os/Bundle;->getString(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mStackMark:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "ORDERCOUNT"
a=0;// 
a=0;//     invoke-virtual {p1, v0}, Landroid/os/Bundle;->getInt(Ljava/lang/String;)I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     iput v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mOrderCount:I
a=0;// 
a=0;//     const-string v0, "NEXTCYCLE"
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {p1, v0}, Landroid/os/Bundle;->getBoolean(Ljava/lang/String;)Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     iput-boolean v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mNextCycle:Z
a=0;// 
a=0;//     const-string v0, "TRADEIDQUERY"
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {p1, v0}, Landroid/os/Bundle;->getBoolean(Ljava/lang/String;)Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     iput-boolean v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mTradeIDQuery:Z
a=0;// 
a=0;//     const-string v0, "PURCHASECODE"
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {p1, v0}, Landroid/os/Bundle;->getInt(Ljava/lang/String;)I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     iput v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mPurchasecode:I
a=0;// 
a=0;//     const-string v0, "TRADEID"
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {p1, v0}, Landroid/os/Bundle;->getString(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mTradeID:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "TIMESTAMP"
a=0;// 
a=0;//     invoke-virtual {p1, v0}, Landroid/os/Bundle;->getString(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mTimeStamp:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "CHANNELID"
a=0;// 
a=0;//     invoke-virtual {p1, v0}, Landroid/os/Bundle;->getString(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mChannelID:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "COPYRIGHTCERT"
a=0;// 
a=0;//     invoke-virtual {p1, v0}, Landroid/os/Bundle;->getString(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mCopyrightCert:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "ORDERID"
a=0;// 
a=0;//     invoke-virtual {p1, v0}, Landroid/os/Bundle;->getString(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mOrderID:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "LEFTDAY"
a=0;// 
a=0;//     invoke-virtual {p1, v0}, Landroid/os/Bundle;->getString(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mLeftDay:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "ORDERTYPE"
a=0;// 
a=0;//     invoke-virtual {p1, v0}, Landroid/os/Bundle;->getString(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mOrderType:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "CERTCONTENT"
a=0;// 
a=0;//     invoke-virtual {p1, v0}, Landroid/os/Bundle;->getString(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mCopyrightCert:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "APKPATH"
a=0;// 
a=0;//     invoke-virtual {p1, v0}, Landroid/os/Bundle;->getString(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mApkPath:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "VERSION"
a=0;// 
a=0;//     invoke-virtual {p1, v0}, Landroid/os/Bundle;->getString(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mVersion:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "CLASSESHA1"
a=0;// 
a=0;//     invoke-virtual {p1, v0}, Landroid/os/Bundle;->getString(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mClasseSha1:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "USERDATA"
a=0;// 
a=0;//     invoke-virtual {p1, v0}, Landroid/os/Bundle;->getString(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mUserData:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "MESSAGE"
a=0;// 
a=0;//     invoke-virtual {p1, v0}, Landroid/os/Bundle;->getString(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mMessage:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "PACKAGE"
a=0;// 
a=0;//     invoke-virtual {p1, v0}, Landroid/os/Bundle;->getString(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mPackageName:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "TASKID"
a=0;// 
a=0;//     invoke-virtual {p1, v0}, Landroid/os/Bundle;->getString(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mTaskID:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "IDTOKEN"
a=0;// 
a=0;//     invoke-virtual {p1, v0}, Landroid/os/Bundle;->getString(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mIDToken:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "RANNUM"
a=0;// 
a=0;//     invoke-virtual {p1, v0}, Landroid/os/Bundle;->getString(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mRannum:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "IDTOKEN_VERF"
a=0;// 
a=0;//     invoke-virtual {p1, v0}, Landroid/os/Bundle;->getString(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mIdtoken_verf:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "AUTHSTR"
a=0;// 
a=0;//     invoke-virtual {p1, v0}, Landroid/os/Bundle;->getString(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mAuthstr:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "MARKSTATUS"
a=0;// 
a=0;//     invoke-virtual {p1, v0}, Landroid/os/Bundle;->getInt(Ljava/lang/String;)I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     iput v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mMarkStatus:I
a=0;// 
a=0;//     const-string v0, "DYQUESTION"
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {p1, v0}, Landroid/os/Bundle;->getString(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mDyQuestion:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "DYANSWER"
a=0;// 
a=0;//     invoke-virtual {p1, v0}, Landroid/os/Bundle;->getString(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mDyAnswer:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "SESSESIONID"
a=0;// 
a=0;//     invoke-virtual {p1, v0}, Landroid/os/Bundle;->getString(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mSessionID:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "PRODUCTINFO"
a=0;// 
a=0;//     invoke-virtual {p1, v0}, Landroid/os/Bundle;->getBundle(Ljava/lang/String;)Landroid/os/Bundle;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mProductInfo:Landroid/os/Bundle;
a=0;// 
a=0;//     const-string v0, "PRODUCTKEYS"
a=0;// 
a=0;//     invoke-virtual {p1, v0}, Landroid/os/Bundle;->getStringArrayList(Ljava/lang/String;)Ljava/util/ArrayList;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mProductKey:Ljava/util/ArrayList;
a=0;// 
a=0;//     const-string v0, "PHONENUM"
a=0;// 
a=0;//     invoke-virtual {p1, v0}, Landroid/os/Bundle;->getString(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mPhone:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "PAYCODESTYLE"
a=0;// 
a=0;//     invoke-virtual {p1, v0}, Landroid/os/Bundle;->getInt(Ljava/lang/String;)I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     iput v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mPaycodeStyle:I
a=0;// 
a=0;//     const-string v0, "PAYCODEWTOS"
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {p1, v0}, Landroid/os/Bundle;->getInt(Ljava/lang/String;)I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     iput v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mpaycodewtos:I
a=0;// 
a=0;//     const-string v0, "PROMPTMSG"
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {p1, v0}, Landroid/os/Bundle;->getString(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mPromptMsg:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "PROMPTURL"
a=0;// 
a=0;//     invoke-virtual {p1, v0}, Landroid/os/Bundle;->getString(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mPromptUrl:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "APKSIGNTURE"
a=0;// 
a=0;//     invoke-virtual {p1, v0}, Landroid/os/Bundle;->getString(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mApksignture:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "APKSHA"
a=0;// 
a=0;//     invoke-virtual {p1, v0}, Landroid/os/Bundle;->getString(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mApkSHA:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "APKPKI"
a=0;// 
a=0;//     invoke-virtual {p1, v0}, Landroid/os/Bundle;->getString(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mApkPKI:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "PROMPTURL"
a=0;// 
a=0;//     invoke-virtual {p1, v0}, Landroid/os/Bundle;->getString(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->MSISDNType:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "WAPQRYURL"
a=0;// 
a=0;//     invoke-virtual {p1, v0}, Landroid/os/Bundle;->getString(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->WAPQry_URL:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "MMQRYURL"
a=0;// 
a=0;//     invoke-virtual {p1, v0}, Landroid/os/Bundle;->getString(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->MMQry_URL:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "APPTYPE"
a=0;// 
a=0;//     invoke-virtual {p1, v0}, Landroid/os/Bundle;->getString(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mAppType:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "APPURL"
a=0;// 
a=0;//     invoke-virtual {p1, v0}, Landroid/os/Bundle;->getString(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mAppUrl:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "REFERERURL"
a=0;// 
a=0;//     invoke-virtual {p1, v0}, Landroid/os/Bundle;->getString(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mRefleshUrl:Ljava/lang/String;
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public reset()V
a=0;//     .locals 2
a=0;// 
a=0;//     const/4 v1, 0x0
a=0;// 
a=0;//     #v1=(Null);
a=0;//     iput v1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mPurchasecode:I
a=0;// 
a=0;//     const/4 v0, -0x1
a=0;// 
a=0;//     #v0=(Byte);
a=0;//     iput v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mPaycodeStyle:I
a=0;// 
a=0;//     iput v1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mpaycodewtos:I
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setApkPKI(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-object p1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mApkPKI:Ljava/lang/String;
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setApkPath(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-object p1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mApkPath:Ljava/lang/String;
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setApkSHA(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-object p1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mApkSHA:Ljava/lang/String;
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setApksignture(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-object p1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mApksignture:Ljava/lang/String;
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setAppID(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-object p1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mAppID:Ljava/lang/String;
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setAppKey(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-object p1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mAppKey:Ljava/lang/String;
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setAppType(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-object p1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mAppType:Ljava/lang/String;
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setAppUrl(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-object p1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mAppUrl:Ljava/lang/String;
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setAuthstr(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-object p1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mAuthstr:Ljava/lang/String;
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setChannelID(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-object p1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mChannelID:Ljava/lang/String;
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setClasseSha1(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-object p1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mClasseSha1:Ljava/lang/String;
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setCopyrightCert(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-object p1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mCopyrightCert:Ljava/lang/String;
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setDyAnswer(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-object p1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mDyAnswer:Ljava/lang/String;
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setDyQuestion(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-object p1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mDyQuestion:Ljava/lang/String;
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setHandler(Landroid/os/Handler;)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-object p1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mHandler:Landroid/os/Handler;
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setIDToken(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-object p1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mIDToken:Ljava/lang/String;
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setIdtoken_verf(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-object p1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mIdtoken_verf:Ljava/lang/String;
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setLeftDay(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-object p1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mLeftDay:Ljava/lang/String;
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setMMQry_URL(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-object p1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->MMQry_URL:Ljava/lang/String;
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setMSISDNType(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-object p1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->MSISDNType:Ljava/lang/String;
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setMarkStatus(I)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput p1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mMarkStatus:I
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setMessage(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-object p1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mMessage:Ljava/lang/String;
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setNextCycle(Z)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-boolean p1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mNextCycle:Z
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setOrderCount(I)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput p1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mOrderCount:I
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setOrderID(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-object p1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mOrderID:Ljava/lang/String;
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setOrderType(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-object p1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mOrderType:Ljava/lang/String;
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setPackageName(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-object p1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mPackageName:Ljava/lang/String;
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setPaycode(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-object p1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mPaycode:Ljava/lang/String;
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setPaycodeSaved(Z)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-boolean p1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->paycodeSaved:Z
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setPaycodeStyle(I)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput p1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mPaycodeStyle:I
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setPaycodewtos(I)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput p1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mpaycodewtos:I
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setProductInfo(Lmm/purchasesdk/core/billing/ProductInfo;)V
a=0;//     .locals 2
a=0;// 
a=0;//     const-string v0, "setProductInfo"
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     const-string v1, "ProductInfo info"
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-static {v0, v1}, Lmm/purchasesdk/core/utils/LogUtil;->d(Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     invoke-virtual {p1}, Lmm/purchasesdk/core/billing/ProductInfo;->getInfo()Landroid/os/Bundle;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mProductInfo:Landroid/os/Bundle;
a=0;// 
a=0;//     invoke-virtual {p1}, Lmm/purchasesdk/core/billing/ProductInfo;->getInfoKey()Ljava/util/ArrayList;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mProductKey:Ljava/util/ArrayList;
a=0;// 
a=0;//     invoke-virtual {p1}, Lmm/purchasesdk/core/billing/ProductInfo;->getMobilePhone()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mPhone:Ljava/lang/String;
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setProgramID(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-object p1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mProgramID:Ljava/lang/String;
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setPromptMsg(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-object p1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mPromptMsg:Ljava/lang/String;
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setPromptUrl(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-object p1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mPromptUrl:Ljava/lang/String;
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setPurchasecode(I)V
a=0;//     .locals 3
a=0;// 
a=0;//     iput p1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mPurchasecode:I
a=0;// 
a=0;//     const-string v0, "setpurchasecode"
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     new-instance v1, Ljava/lang/StringBuilder;
a=0;// 
a=0;//     #v1=(UninitRef,Ljava/lang/StringBuilder;);
a=0;//     invoke-direct {v1}, Ljava/lang/StringBuilder;-><init>()V
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/StringBuilder;);
a=0;//     const-string v2, "mpurchasecode ="
a=0;// 
a=0;//     #v2=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v1, p1}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v1}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-static {v0, v1}, Lmm/purchasesdk/core/utils/LogUtil;->d(Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setRannum(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-object p1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mRannum:Ljava/lang/String;
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setRefleshUrl(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-object p1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mRefleshUrl:Ljava/lang/String;
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setResult(I)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput p1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mResult:I
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setSessionID(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-object p1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mSessionID:Ljava/lang/String;
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setStackMark(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-object p1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mStackMark:Ljava/lang/String;
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setTaskID(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-object p1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mTaskID:Ljava/lang/String;
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setTimeStamp(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-object p1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mTimeStamp:Ljava/lang/String;
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setTradeID(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-object p1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mTradeID:Ljava/lang/String;
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setTradeIDQuery(Z)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-boolean p1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mTradeIDQuery:Z
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setUserData(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-object p1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mUserData:Ljava/lang/String;
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setVersion(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-object p1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mVersion:Ljava/lang/String;
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setWAPQry_URL(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-object p1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->WAPQry_URL:Ljava/lang/String;
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public toString()Ljava/lang/String;
a=0;//     .locals 2
a=0;// 
a=0;//     new-instance v0, Ljava/lang/StringBuilder;
a=0;// 
a=0;//     #v0=(UninitRef,Ljava/lang/StringBuilder;);
a=0;//     invoke-direct {v0}, Ljava/lang/StringBuilder;-><init>()V
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/StringBuilder;);
a=0;//     const-string v1, "mAuthstr : "
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mAuthstr:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, "mCopyrightCert : "
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mCopyrightCert:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, "mClasseSha1 : "
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mClasseSha1:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, "mDyQuestion : "
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mDyQuestion:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, "mDyAnswer : "
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mDyAnswer:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public writeToBundle()Landroid/os/Bundle;
a=0;//     .locals 3
a=0;// 
a=0;//     new-instance v0, Landroid/os/Bundle;
a=0;// 
a=0;//     #v0=(UninitRef,Landroid/os/Bundle;);
a=0;//     invoke-direct {v0}, Landroid/os/Bundle;-><init>()V
a=0;// 
a=0;//     #v0=(Reference,Landroid/os/Bundle;);
a=0;//     const-string v1, "APPID"
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     iget-object v2, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mAppID:Ljava/lang/String;
a=0;// 
a=0;//     #v2=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v1, v2}, Landroid/os/Bundle;->putString(Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     const-string v1, "APPKEY"
a=0;// 
a=0;//     iget-object v2, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mAppKey:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1, v2}, Landroid/os/Bundle;->putString(Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     const-string v1, "PAYCODE"
a=0;// 
a=0;//     iget-object v2, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mPaycode:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1, v2}, Landroid/os/Bundle;->putString(Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     const-string v1, "PROGRAMID"
a=0;// 
a=0;//     iget-object v2, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mProgramID:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1, v2}, Landroid/os/Bundle;->putString(Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     const-string v1, "STACKMARK"
a=0;// 
a=0;//     iget-object v2, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mStackMark:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1, v2}, Landroid/os/Bundle;->putString(Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     const-string v1, "ORDERCOUNT"
a=0;// 
a=0;//     iget v2, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mOrderCount:I
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     invoke-virtual {v0, v1, v2}, Landroid/os/Bundle;->putInt(Ljava/lang/String;I)V
a=0;// 
a=0;//     const-string v1, "NEXTCYCLE"
a=0;// 
a=0;//     iget-boolean v2, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mNextCycle:Z
a=0;// 
a=0;//     #v2=(Boolean);
a=0;//     invoke-virtual {v0, v1, v2}, Landroid/os/Bundle;->putBoolean(Ljava/lang/String;Z)V
a=0;// 
a=0;//     const-string v1, "TRADEID"
a=0;// 
a=0;//     iget-object v2, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mTradeID:Ljava/lang/String;
a=0;// 
a=0;//     #v2=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v1, v2}, Landroid/os/Bundle;->putString(Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     const-string v1, "TIMESTAMP"
a=0;// 
a=0;//     iget-object v2, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mTimeStamp:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1, v2}, Landroid/os/Bundle;->putString(Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     const-string v1, "TRADEIDQUERY"
a=0;// 
a=0;//     iget-boolean v2, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mTradeIDQuery:Z
a=0;// 
a=0;//     #v2=(Boolean);
a=0;//     invoke-virtual {v0, v1, v2}, Landroid/os/Bundle;->putBoolean(Ljava/lang/String;Z)V
a=0;// 
a=0;//     const-string v1, "PURCHASECODE"
a=0;// 
a=0;//     iget v2, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mPurchasecode:I
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     invoke-virtual {v0, v1, v2}, Landroid/os/Bundle;->putInt(Ljava/lang/String;I)V
a=0;// 
a=0;//     const-string v1, "COPYRIGHTCERT"
a=0;// 
a=0;//     iget-object v2, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mCopyrightCert:Ljava/lang/String;
a=0;// 
a=0;//     #v2=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v1, v2}, Landroid/os/Bundle;->putString(Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     const-string v1, "CHANNELID"
a=0;// 
a=0;//     iget-object v2, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mChannelID:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1, v2}, Landroid/os/Bundle;->putString(Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     const-string v1, "LEFTDAY"
a=0;// 
a=0;//     iget-object v2, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mLeftDay:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1, v2}, Landroid/os/Bundle;->putString(Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     const-string v1, "ORDERID"
a=0;// 
a=0;//     iget-object v2, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mOrderID:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1, v2}, Landroid/os/Bundle;->putString(Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     const-string v1, "ORDERTYPE"
a=0;// 
a=0;//     iget-object v2, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mOrderType:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1, v2}, Landroid/os/Bundle;->putString(Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     const-string v1, "CERTCONTENT"
a=0;// 
a=0;//     iget-object v2, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mCopyrightCert:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1, v2}, Landroid/os/Bundle;->putString(Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     const-string v1, "APKPATH"
a=0;// 
a=0;//     iget-object v2, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mApkPath:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1, v2}, Landroid/os/Bundle;->putString(Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     const-string v1, "VERSION"
a=0;// 
a=0;//     iget-object v2, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mVersion:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1, v2}, Landroid/os/Bundle;->putString(Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     const-string v1, "CLASSESHA1"
a=0;// 
a=0;//     iget-object v2, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mClasseSha1:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1, v2}, Landroid/os/Bundle;->putString(Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     const-string v1, "USERDATA"
a=0;// 
a=0;//     iget-object v2, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mUserData:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1, v2}, Landroid/os/Bundle;->putString(Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     const-string v1, "MESSAGE"
a=0;// 
a=0;//     iget-object v2, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mMessage:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1, v2}, Landroid/os/Bundle;->putString(Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     const-string v1, "PACKAGE"
a=0;// 
a=0;//     iget-object v2, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mPackageName:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1, v2}, Landroid/os/Bundle;->putString(Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     const-string v1, "TASKID"
a=0;// 
a=0;//     iget-object v2, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mTaskID:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1, v2}, Landroid/os/Bundle;->putString(Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     const-string v1, "IDTOKEN"
a=0;// 
a=0;//     iget-object v2, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mIDToken:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1, v2}, Landroid/os/Bundle;->putString(Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     const-string v1, "RANNUM"
a=0;// 
a=0;//     iget-object v2, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mRannum:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1, v2}, Landroid/os/Bundle;->putString(Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     const-string v1, "IDTOKEN_VERF"
a=0;// 
a=0;//     iget-object v2, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mIdtoken_verf:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1, v2}, Landroid/os/Bundle;->putString(Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     const-string v1, "AUTHSTR"
a=0;// 
a=0;//     iget-object v2, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mAuthstr:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1, v2}, Landroid/os/Bundle;->putString(Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     const-string v1, "MARKSTATUS"
a=0;// 
a=0;//     iget v2, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mMarkStatus:I
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     invoke-virtual {v0, v1, v2}, Landroid/os/Bundle;->putInt(Ljava/lang/String;I)V
a=0;// 
a=0;//     const-string v1, "DYQUESTION"
a=0;// 
a=0;//     iget-object v2, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mDyQuestion:Ljava/lang/String;
a=0;// 
a=0;//     #v2=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v1, v2}, Landroid/os/Bundle;->putString(Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     const-string v1, "DYANSWER"
a=0;// 
a=0;//     iget-object v2, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mDyAnswer:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1, v2}, Landroid/os/Bundle;->putString(Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     const-string v1, "SESSESIONID"
a=0;// 
a=0;//     iget-object v2, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mSessionID:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1, v2}, Landroid/os/Bundle;->putString(Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     const-string v1, "PRODUCTINFO"
a=0;// 
a=0;//     iget-object v2, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mProductInfo:Landroid/os/Bundle;
a=0;// 
a=0;//     invoke-virtual {v0, v1, v2}, Landroid/os/Bundle;->putBundle(Ljava/lang/String;Landroid/os/Bundle;)V
a=0;// 
a=0;//     const-string v1, "PRODUCTKEYS"
a=0;// 
a=0;//     iget-object v2, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mProductKey:Ljava/util/ArrayList;
a=0;// 
a=0;//     invoke-virtual {v0, v1, v2}, Landroid/os/Bundle;->putStringArrayList(Ljava/lang/String;Ljava/util/ArrayList;)V
a=0;// 
a=0;//     const-string v1, "PHONENUM"
a=0;// 
a=0;//     iget-object v2, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mPhone:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1, v2}, Landroid/os/Bundle;->putString(Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     const-string v1, "PAYCODESTYLE"
a=0;// 
a=0;//     iget v2, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mPaycodeStyle:I
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     invoke-virtual {v0, v1, v2}, Landroid/os/Bundle;->putInt(Ljava/lang/String;I)V
a=0;// 
a=0;//     const-string v1, "PAYCODEWTOS"
a=0;// 
a=0;//     iget v2, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mpaycodewtos:I
a=0;// 
a=0;//     invoke-virtual {v0, v1, v2}, Landroid/os/Bundle;->putInt(Ljava/lang/String;I)V
a=0;// 
a=0;//     const-string v1, "PROMPTMSG"
a=0;// 
a=0;//     iget-object v2, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mPromptMsg:Ljava/lang/String;
a=0;// 
a=0;//     #v2=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v1, v2}, Landroid/os/Bundle;->putString(Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     const-string v1, "PROMPTURL"
a=0;// 
a=0;//     iget-object v2, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mPromptUrl:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1, v2}, Landroid/os/Bundle;->putString(Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     const-string v1, "APKSIGNTURE"
a=0;// 
a=0;//     iget-object v2, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mApksignture:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1, v2}, Landroid/os/Bundle;->putString(Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     const-string v1, "APKSHA"
a=0;// 
a=0;//     iget-object v2, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mApkSHA:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1, v2}, Landroid/os/Bundle;->putString(Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     const-string v1, "APKPKI"
a=0;// 
a=0;//     iget-object v2, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mApkPKI:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1, v2}, Landroid/os/Bundle;->putString(Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     const-string v1, "MSISDNTYPE"
a=0;// 
a=0;//     iget-object v2, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->MSISDNType:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1, v2}, Landroid/os/Bundle;->putString(Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     const-string v1, "WAPQRYURL"
a=0;// 
a=0;//     iget-object v2, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->WAPQry_URL:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1, v2}, Landroid/os/Bundle;->putString(Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     const-string v1, "MMQRYURL"
a=0;// 
a=0;//     iget-object v2, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->MMQry_URL:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1, v2}, Landroid/os/Bundle;->putString(Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     const-string v1, "APPTYPE"
a=0;// 
a=0;//     iget-object v2, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mAppType:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1, v2}, Landroid/os/Bundle;->putString(Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     const-string v1, "APPURL"
a=0;// 
a=0;//     iget-object v2, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mAppUrl:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1, v2}, Landroid/os/Bundle;->putString(Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     const-string v1, "REFERERURL"
a=0;// 
a=0;//     iget-object v2, p0, Lmm/purchasesdk/core/protocol/MessengerInfo;->mRefleshUrl:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1, v2}, Landroid/os/Bundle;->putString(Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     return-object v0
a=0;// .end method
}}
