package mm.purchasesdk.iapservice; class BillingLayoutActivity$a { void a() { int a;
a=0;// .class Lmm/purchasesdk/iapservice/BillingLayoutActivity$a;
a=0;// .super Landroid/os/Handler;
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation system Ldalvik/annotation/EnclosingClass;
a=0;//     value = Lmm/purchasesdk/iapservice/BillingLayoutActivity;
a=0;// .end annotation
a=0;// 
a=0;// .annotation system Ldalvik/annotation/InnerClass;
a=0;//     accessFlags = 0x0
a=0;//     name = "a"
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field final synthetic b:Lmm/purchasesdk/iapservice/BillingLayoutActivity;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>(Lmm/purchasesdk/iapservice/BillingLayoutActivity;)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-object p1, p0, Lmm/purchasesdk/iapservice/BillingLayoutActivity$a;->b:Lmm/purchasesdk/iapservice/BillingLayoutActivity;
a=0;// 
a=0;//     invoke-direct {p0}, Landroid/os/Handler;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lmm/purchasesdk/iapservice/BillingLayoutActivity$a;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public handleMessage(Landroid/os/Message;)V
a=0;//     .locals 4
a=0;// 
a=0;//     invoke-static {}, Lmm/purchasesdk/iapservice/BillingLayoutActivity;->c()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     new-instance v1, Ljava/lang/StringBuilder;
a=0;// 
a=0;//     #v1=(UninitRef,Ljava/lang/StringBuilder;);
a=0;//     invoke-direct {v1}, Ljava/lang/StringBuilder;-><init>()V
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/StringBuilder;);
a=0;//     const-string v2, "handleMessage what:"
a=0;// 
a=0;//     #v2=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     iget v2, p1, Landroid/os/Message;->what:I
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     const-string v2, " "
a=0;// 
a=0;//     #v2=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {p1}, Landroid/os/Message;->toString()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v1}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-static {v0, v1}, Lmm/purchasesdk/core/utils/LogUtil;->e(Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     invoke-super {p0, p1}, Landroid/os/Handler;->handleMessage(Landroid/os/Message;)V
a=0;// 
a=0;//     iget-object v0, p0, Lmm/purchasesdk/iapservice/BillingLayoutActivity$a;->b:Lmm/purchasesdk/iapservice/BillingLayoutActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lmm/purchasesdk/iapservice/BillingLayoutActivity;->a(Lmm/purchasesdk/iapservice/BillingLayoutActivity;)Lmm/purchasesdk/core/IPurchase;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-interface {v0, p1}, Lmm/purchasesdk/core/IPurchase;->setMessage(Landroid/os/Message;)V
a=0;// 
a=0;//     iget-object v0, p0, Lmm/purchasesdk/iapservice/BillingLayoutActivity$a;->b:Lmm/purchasesdk/iapservice/BillingLayoutActivity;
a=0;// 
a=0;//     iget-object v1, p1, Landroid/os/Message;->replyTo:Landroid/os/Messenger;
a=0;// 
a=0;//     invoke-static {v0, v1}, Lmm/purchasesdk/iapservice/BillingLayoutActivity;->a(Lmm/purchasesdk/iapservice/BillingLayoutActivity;Landroid/os/Messenger;)Landroid/os/Messenger;
a=0;// 
a=0;//     new-instance v1, Lmm/purchasesdk/core/protocol/MessengerInfo;
a=0;// 
a=0;//     #v1=(UninitRef,Lmm/purchasesdk/core/protocol/MessengerInfo;);
a=0;//     invoke-direct {v1}, Lmm/purchasesdk/core/protocol/MessengerInfo;-><init>()V
a=0;// 
a=0;//     #v1=(Reference,Lmm/purchasesdk/core/protocol/MessengerInfo;);
a=0;//     invoke-virtual {p1}, Landroid/os/Message;->getData()Landroid/os/Bundle;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v1, v0}, Lmm/purchasesdk/core/protocol/MessengerInfo;->readBundle(Landroid/os/Bundle;)V
a=0;// 
a=0;//     iget-object v2, p0, Lmm/purchasesdk/iapservice/BillingLayoutActivity$a;->b:Lmm/purchasesdk/iapservice/BillingLayoutActivity;
a=0;// 
a=0;//     invoke-static {v2}, Lmm/purchasesdk/iapservice/BillingLayoutActivity;->a(Lmm/purchasesdk/iapservice/BillingLayoutActivity;)Lmm/purchasesdk/core/IPurchase;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-virtual {v1}, Lmm/purchasesdk/core/protocol/MessengerInfo;->getClasseSha1()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     #v3=(Reference,Ljava/lang/String;);
a=0;//     invoke-interface {v2, v3}, Lmm/purchasesdk/core/IPurchase;->setClasseSha1(Ljava/lang/String;)V
a=0;// 
a=0;//     const-string v2, "PAYCODE"
a=0;// 
a=0;//     invoke-virtual {v0, v2}, Landroid/os/Bundle;->getString(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     const-string v2, "TIMESTAMP"
a=0;// 
a=0;//     invoke-virtual {v0, v2}, Landroid/os/Bundle;->getString(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     iget v0, p1, Landroid/os/Message;->what:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     sparse-switch v0, :sswitch_data_0
a=0;// 
a=0;//     :goto_0
a=0;//     #v0=(Conflicted);
a=0;//     return-void
a=0;// 
a=0;//     :sswitch_0
a=0;//     #v0=(Integer);
a=0;//     iget-object v0, p0, Lmm/purchasesdk/iapservice/BillingLayoutActivity$a;->b:Lmm/purchasesdk/iapservice/BillingLayoutActivity;
a=0;// 
a=0;//     #v0=(Reference,Lmm/purchasesdk/iapservice/BillingLayoutActivity;);
a=0;//     invoke-static {v0}, Lmm/purchasesdk/iapservice/BillingLayoutActivity;->a(Lmm/purchasesdk/iapservice/BillingLayoutActivity;)Lmm/purchasesdk/core/IPurchase;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     if-nez v0, :cond_0
a=0;// 
a=0;//     iget-object v2, p0, Lmm/purchasesdk/iapservice/BillingLayoutActivity$a;->b:Lmm/purchasesdk/iapservice/BillingLayoutActivity;
a=0;// 
a=0;//     const-string v0, ""
a=0;// 
a=0;//     invoke-static {p0, v0}, Lmm/purchasesdk/fingerprint/IdentifyApp;->load(Ljava/lang/Object;Ljava/lang/String;)Ljava/lang/Object;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     check-cast v0, Lmm/purchasesdk/core/IPurchase;
a=0;// 
a=0;//     invoke-static {v2, v0}, Lmm/purchasesdk/iapservice/BillingLayoutActivity;->a(Lmm/purchasesdk/iapservice/BillingLayoutActivity;Lmm/purchasesdk/core/IPurchase;)Lmm/purchasesdk/core/IPurchase;
a=0;// 
a=0;//     :cond_0
a=0;//     :try_start_0
a=0;//     iget-object v0, p0, Lmm/purchasesdk/iapservice/BillingLayoutActivity$a;->b:Lmm/purchasesdk/iapservice/BillingLayoutActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lmm/purchasesdk/iapservice/BillingLayoutActivity;->a(Lmm/purchasesdk/iapservice/BillingLayoutActivity;)Landroid/os/Messenger;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     if-nez v0, :cond_1
a=0;// 
a=0;//     invoke-static {}, Lmm/purchasesdk/iapservice/BillingLayoutActivity;->c()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v2, "mMessengerFromService == null"
a=0;// 
a=0;//     invoke-static {v0, v2}, Lmm/purchasesdk/core/utils/LogUtil;->d(Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     :cond_1
a=0;//     iget-object v0, p0, Lmm/purchasesdk/iapservice/BillingLayoutActivity$a;->b:Lmm/purchasesdk/iapservice/BillingLayoutActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lmm/purchasesdk/iapservice/BillingLayoutActivity;->b(Lmm/purchasesdk/iapservice/BillingLayoutActivity;)Landroid/os/Messenger;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     if-nez v0, :cond_2
a=0;// 
a=0;//     invoke-static {}, Lmm/purchasesdk/iapservice/BillingLayoutActivity;->c()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v2, "mMessengerToService == null"
a=0;// 
a=0;//     invoke-static {v0, v2}, Lmm/purchasesdk/core/utils/LogUtil;->d(Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     :cond_2
a=0;//     iget-object v0, p0, Lmm/purchasesdk/iapservice/BillingLayoutActivity$a;->b:Lmm/purchasesdk/iapservice/BillingLayoutActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lmm/purchasesdk/iapservice/BillingLayoutActivity;->a(Lmm/purchasesdk/iapservice/BillingLayoutActivity;)Lmm/purchasesdk/core/IPurchase;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-interface {v0, p1, v1}, Lmm/purchasesdk/core/IPurchase;->service_bill(Landroid/os/Message;Lmm/purchasesdk/core/protocol/MessengerInfo;)V
a=0;//     :try_end_0
a=0;//     .catch Ljava/lang/Exception; {:try_start_0 .. :try_end_0} :catch_0
a=0;// 
a=0;//     goto :goto_0
a=0;// 
a=0;//     :catch_0
a=0;//     move-exception v0
a=0;// 
a=0;//     invoke-virtual {v0}, Ljava/lang/Exception;->printStackTrace()V
a=0;// 
a=0;//     goto :goto_0
a=0;// 
a=0;//     :sswitch_1
a=0;//     #v0=(Integer);
a=0;//     iget-object v0, p0, Lmm/purchasesdk/iapservice/BillingLayoutActivity$a;->b:Lmm/purchasesdk/iapservice/BillingLayoutActivity;
a=0;// 
a=0;//     #v0=(Reference,Lmm/purchasesdk/iapservice/BillingLayoutActivity;);
a=0;//     invoke-static {v0}, Lmm/purchasesdk/iapservice/BillingLayoutActivity;->a(Lmm/purchasesdk/iapservice/BillingLayoutActivity;)Lmm/purchasesdk/core/IPurchase;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     if-nez v0, :cond_3
a=0;// 
a=0;//     iget-object v2, p0, Lmm/purchasesdk/iapservice/BillingLayoutActivity$a;->b:Lmm/purchasesdk/iapservice/BillingLayoutActivity;
a=0;// 
a=0;//     const-string v0, ""
a=0;// 
a=0;//     invoke-static {p0, v0}, Lmm/purchasesdk/fingerprint/IdentifyApp;->load(Ljava/lang/Object;Ljava/lang/String;)Ljava/lang/Object;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     check-cast v0, Lmm/purchasesdk/core/IPurchase;
a=0;// 
a=0;//     invoke-static {v2, v0}, Lmm/purchasesdk/iapservice/BillingLayoutActivity;->a(Lmm/purchasesdk/iapservice/BillingLayoutActivity;Lmm/purchasesdk/core/IPurchase;)Lmm/purchasesdk/core/IPurchase;
a=0;// 
a=0;//     :cond_3
a=0;//     :try_start_1
a=0;//     iget-object v0, p0, Lmm/purchasesdk/iapservice/BillingLayoutActivity$a;->b:Lmm/purchasesdk/iapservice/BillingLayoutActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lmm/purchasesdk/iapservice/BillingLayoutActivity;->a(Lmm/purchasesdk/iapservice/BillingLayoutActivity;)Landroid/os/Messenger;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     if-nez v0, :cond_4
a=0;// 
a=0;//     invoke-static {}, Lmm/purchasesdk/iapservice/BillingLayoutActivity;->c()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v2, "mMessengerFromService == null"
a=0;// 
a=0;//     invoke-static {v0, v2}, Lmm/purchasesdk/core/utils/LogUtil;->d(Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     :cond_4
a=0;//     iget-object v0, p0, Lmm/purchasesdk/iapservice/BillingLayoutActivity$a;->b:Lmm/purchasesdk/iapservice/BillingLayoutActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lmm/purchasesdk/iapservice/BillingLayoutActivity;->b(Lmm/purchasesdk/iapservice/BillingLayoutActivity;)Landroid/os/Messenger;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     if-nez v0, :cond_5
a=0;// 
a=0;//     invoke-static {}, Lmm/purchasesdk/iapservice/BillingLayoutActivity;->c()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v2, "mMessengerToService == null"
a=0;// 
a=0;//     invoke-static {v0, v2}, Lmm/purchasesdk/core/utils/LogUtil;->d(Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     :cond_5
a=0;//     iget-object v0, p0, Lmm/purchasesdk/iapservice/BillingLayoutActivity$a;->b:Lmm/purchasesdk/iapservice/BillingLayoutActivity;
a=0;// 
a=0;//     invoke-static {v0}, Lmm/purchasesdk/iapservice/BillingLayoutActivity;->a(Lmm/purchasesdk/iapservice/BillingLayoutActivity;)Lmm/purchasesdk/core/IPurchase;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v2, p0, Lmm/purchasesdk/iapservice/BillingLayoutActivity$a;->b:Lmm/purchasesdk/iapservice/BillingLayoutActivity;
a=0;// 
a=0;//     invoke-static {v2}, Lmm/purchasesdk/iapservice/BillingLayoutActivity;->a(Lmm/purchasesdk/iapservice/BillingLayoutActivity;)Landroid/os/Messenger;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     iget-object v3, p0, Lmm/purchasesdk/iapservice/BillingLayoutActivity$a;->b:Lmm/purchasesdk/iapservice/BillingLayoutActivity;
a=0;// 
a=0;//     invoke-static {v3}, Lmm/purchasesdk/iapservice/BillingLayoutActivity;->b(Lmm/purchasesdk/iapservice/BillingLayoutActivity;)Landroid/os/Messenger;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-interface {v0, p1, v1, v2, v3}, Lmm/purchasesdk/core/IPurchase;->service_weak_bill(Landroid/os/Message;Lmm/purchasesdk/core/protocol/MessengerInfo;Landroid/os/Messenger;Landroid/os/Messenger;)V
a=0;//     :try_end_1
a=0;//     .catch Ljava/lang/Exception; {:try_start_1 .. :try_end_1} :catch_1
a=0;// 
a=0;//     goto/16 :goto_0
a=0;// 
a=0;//     :catch_1
a=0;//     move-exception v0
a=0;// 
a=0;//     invoke-virtual {v0}, Ljava/lang/Exception;->printStackTrace()V
a=0;// 
a=0;//     goto/16 :goto_0
a=0;// 
a=0;//     :sswitch_data_0
a=0;//     .sparse-switch
a=0;//         0x3 -> :sswitch_0
a=0;//         0xb -> :sswitch_1
a=0;//     .end sparse-switch
a=0;// .end method
}}
