package cn.dm.android.a; class b$4 { void a() { int a;
a=0;// .class Lcn/dm/android/a/b$4;
a=0;// .super Ljava/lang/Object;
a=0;// .source "SourceFile"
a=0;// 
a=0;// # interfaces
a=0;// .implements Lcn/dm/android/listener/c;
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation system Ldalvik/annotation/EnclosingMethod;
a=0;//     value = Lcn/dm/android/a/b;->a(Lcn/dm/android/listener/OfferListListener;I)V
a=0;// .end annotation
a=0;// 
a=0;// .annotation system Ldalvik/annotation/InnerClass;
a=0;//     accessFlags = 0x0
a=0;//     name = null
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field final synthetic a:Lcn/dm/android/listener/OfferListListener;
a=0;// 
a=0;// .field final synthetic b:I
a=0;// 
a=0;// .field final synthetic c:Lcn/dm/android/a/b;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>(Lcn/dm/android/a/b;Lcn/dm/android/listener/OfferListListener;I)V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 199
a=0;//     iput-object p1, p0, Lcn/dm/android/a/b$4;->c:Lcn/dm/android/a/b;
a=0;// 
a=0;//     iput-object p2, p0, Lcn/dm/android/a/b$4;->a:Lcn/dm/android/listener/OfferListListener;
a=0;// 
a=0;//     iput p3, p0, Lcn/dm/android/a/b$4;->b:I
a=0;// 
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcn/dm/android/a/b$4;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public a(Lcn/dm/android/model/a;)V
a=0;//     .locals 5
a=0;// 
a=0;//     .prologue
a=0;//     .line 210
a=0;//     iget-object v0, p0, Lcn/dm/android/a/b$4;->c:Lcn/dm/android/a/b;
a=0;// 
a=0;//     #v0=(Reference,Lcn/dm/android/a/b;);
a=0;//     invoke-static {v0}, Lcn/dm/android/a/b;->a(Lcn/dm/android/a/b;)Landroid/content/Context;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     new-instance v1, Ljava/lang/StringBuilder;
a=0;// 
a=0;//     #v1=(UninitRef,Ljava/lang/StringBuilder;);
a=0;//     invoke-direct {v1}, Ljava/lang/StringBuilder;-><init>()V
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/StringBuilder;);
a=0;//     sget-object v2, Lcn/dm/android/a/b$a;->c:Lcn/dm/android/a/b$a;
a=0;// 
a=0;//     #v2=(Reference,Lcn/dm/android/a/b$a;);
a=0;//     invoke-virtual {v2}, Lcn/dm/android/a/b$a;->a()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     iget-object v2, p0, Lcn/dm/android/a/b$4;->c:Lcn/dm/android/a/b;
a=0;// 
a=0;//     invoke-static {v2}, Lcn/dm/android/a/b;->d(Lcn/dm/android/a/b;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v1}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-static {v0, v1}, Lcn/dm/android/f/i;->a(Landroid/content/Context;Ljava/lang/String;)V
a=0;// 
a=0;//     .line 211
a=0;//     iget-object v0, p1, Lcn/dm/android/model/a;->b:Ljava/lang/String;
a=0;// 
a=0;//     invoke-static {v0}, Lcn/dm/android/model/AOWObject;->parser_list(Ljava/lang/String;)Ljava/util/List;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 212
a=0;//     iget-object v1, p1, Lcn/dm/android/model/a;->b:Ljava/lang/String;
a=0;// 
a=0;//     iget-object v2, p0, Lcn/dm/android/a/b$4;->c:Lcn/dm/android/a/b;
a=0;// 
a=0;//     invoke-static {v2}, Lcn/dm/android/a/b;->e(Lcn/dm/android/a/b;)Ljava/util/List;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-static {v1, v2}, Lcn/dm/android/f/d;->a(Ljava/lang/String;Ljava/util/List;)V
a=0;// 
a=0;//     .line 213
a=0;//     iget-object v1, p0, Lcn/dm/android/a/b$4;->a:Lcn/dm/android/listener/OfferListListener;
a=0;// 
a=0;//     iget-object v2, p0, Lcn/dm/android/a/b$4;->c:Lcn/dm/android/a/b;
a=0;// 
a=0;//     iget v3, p0, Lcn/dm/android/a/b$4;->b:I
a=0;// 
a=0;//     #v3=(Integer);
a=0;//     invoke-interface {v0}, Ljava/util/List;->size()I
a=0;// 
a=0;//     move-result v4
a=0;// 
a=0;//     #v4=(Integer);
a=0;//     add-int/2addr v3, v4
a=0;// 
a=0;//     iget-object v4, p0, Lcn/dm/android/a/b$4;->c:Lcn/dm/android/a/b;
a=0;// 
a=0;//     #v4=(Reference,Lcn/dm/android/a/b;);
a=0;//     invoke-static {v4}, Lcn/dm/android/a/b;->e(Lcn/dm/android/a/b;)Ljava/util/List;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-static {v2, v3, v4}, Lcn/dm/android/a/b;->a(Lcn/dm/android/a/b;ILjava/util/List;)Z
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Boolean);
a=0;//     iget-object v3, p1, Lcn/dm/android/model/a;->b:Ljava/lang/String;
a=0;// 
a=0;//     #v3=(Reference,Ljava/lang/String;);
a=0;//     const-string v4, "tr"
a=0;// 
a=0;//     invoke-static {v3, v4}, Lcn/dm/android/f/d;->b(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-interface {v1, v0, v2, v3}, Lcn/dm/android/listener/OfferListListener;->onResponse(Ljava/util/List;ZLjava/lang/String;)V
a=0;// 
a=0;//     .line 216
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public onError(Lcn/dm/android/model/ErrorInfo;)V
a=0;//     .locals 3
a=0;//     .param p1, "errorInfo"    # Lcn/dm/android/model/ErrorInfo;
a=0;// 
a=0;//     .prologue
a=0;//     .line 202
a=0;//     iget-object v0, p0, Lcn/dm/android/a/b$4;->c:Lcn/dm/android/a/b;
a=0;// 
a=0;//     #v0=(Reference,Lcn/dm/android/a/b;);
a=0;//     invoke-static {v0}, Lcn/dm/android/a/b;->a(Lcn/dm/android/a/b;)Landroid/content/Context;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     new-instance v1, Ljava/lang/StringBuilder;
a=0;// 
a=0;//     #v1=(UninitRef,Ljava/lang/StringBuilder;);
a=0;//     invoke-direct {v1}, Ljava/lang/StringBuilder;-><init>()V
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/StringBuilder;);
a=0;//     sget-object v2, Lcn/dm/android/a/b$a;->c:Lcn/dm/android/a/b$a;
a=0;// 
a=0;//     #v2=(Reference,Lcn/dm/android/a/b$a;);
a=0;//     invoke-virtual {v2}, Lcn/dm/android/a/b$a;->a()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     iget-object v2, p0, Lcn/dm/android/a/b$4;->c:Lcn/dm/android/a/b;
a=0;// 
a=0;//     invoke-static {v2}, Lcn/dm/android/a/b;->b(Lcn/dm/android/a/b;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v1}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-static {v0, v1}, Lcn/dm/android/f/i;->a(Landroid/content/Context;Ljava/lang/String;)V
a=0;// 
a=0;//     .line 203
a=0;//     iget-object v0, p0, Lcn/dm/android/a/b$4;->a:Lcn/dm/android/listener/OfferListListener;
a=0;// 
a=0;//     if-eqz v0, :cond_0
a=0;// 
a=0;//     .line 204
a=0;//     iget-object v0, p0, Lcn/dm/android/a/b$4;->a:Lcn/dm/android/listener/OfferListListener;
a=0;// 
a=0;//     invoke-interface {v0, p1}, Lcn/dm/android/listener/OfferListListener;->onError(Lcn/dm/android/model/ErrorInfo;)V
a=0;// 
a=0;//     .line 206
a=0;//     :cond_0
a=0;//     return-void
a=0;// .end method
}}
