package safiap.framework.ui.res; class c { void a() { int a;
a=0;// .class final Lsafiap/framework/ui/res/c;
a=0;// .super Ljava/lang/Object;
a=0;// .source "SourceFile"
a=0;// 
a=0;// # interfaces
a=0;// .implements Landroid/view/View$OnClickListener;
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field private synthetic a:Lsafiap/framework/ui/res/LayoutDialog;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>(Lsafiap/framework/ui/res/LayoutDialog;)V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 379
a=0;//     iput-object p1, p0, Lsafiap/framework/ui/res/c;->a:Lsafiap/framework/ui/res/LayoutDialog;
a=0;// 
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lsafiap/framework/ui/res/c;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public final onClick(Landroid/view/View;)V
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 383
a=0;//     iget-object v0, p0, Lsafiap/framework/ui/res/c;->a:Lsafiap/framework/ui/res/LayoutDialog;
a=0;// 
a=0;//     #v0=(Reference,Lsafiap/framework/ui/res/LayoutDialog;);
a=0;//     invoke-static {v0}, Lsafiap/framework/ui/res/LayoutDialog;->b(Lsafiap/framework/ui/res/LayoutDialog;)Lsafiap/framework/ui/res/LayoutDialog$a;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     if-eqz v0, :cond_0
a=0;// 
a=0;//     .line 384
a=0;//     iget-object v0, p0, Lsafiap/framework/ui/res/c;->a:Lsafiap/framework/ui/res/LayoutDialog;
a=0;// 
a=0;//     invoke-static {v0}, Lsafiap/framework/ui/res/LayoutDialog;->b(Lsafiap/framework/ui/res/LayoutDialog;)Lsafiap/framework/ui/res/LayoutDialog$a;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-interface {v0}, Lsafiap/framework/ui/res/LayoutDialog$a;->a()V
a=0;// 
a=0;//     .line 386
a=0;//     :cond_0
a=0;//     return-void
a=0;// .end method
}}
