package cn.dm.android.c; class b { void a() { int a;
a=0;// .class public Lcn/dm/android/c/b;
a=0;// .super Lcn/dm/android/c/e;
a=0;// .source "SourceFile"
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>(Landroid/content/Context;Lcn/dm/android/listener/c;Ljava/util/HashMap;Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "(",
a=0;//             "Landroid/content/Context;",
a=0;//             "Lcn/dm/android/listener/c;",
a=0;//             "Ljava/util/HashMap",
a=0;//             "<",
a=0;//             "Ljava/lang/String;",
a=0;//             "Ljava/lang/String;",
a=0;//             ">;",
a=0;//             "Ljava/lang/String;",
a=0;//             ")V"
a=0;//         }
a=0;//     .end annotation
a=0;// 
a=0;//     .prologue
a=0;//     .line 22
a=0;//     invoke-direct {p0, p1, p2, p3, p4}, Lcn/dm/android/c/e;-><init>(Landroid/content/Context;Lcn/dm/android/listener/c;Ljava/util/HashMap;Ljava/lang/String;)V
a=0;// 
a=0;//     .line 23
a=0;//     #p0=(Reference,Lcn/dm/android/c/b;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method protected a(Ljava/util/HashMap;)Ljava/util/HashMap;
a=0;//     .locals 5
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "(",
a=0;//             "Ljava/util/HashMap",
a=0;//             "<",
a=0;//             "Ljava/lang/String;",
a=0;//             "Ljava/lang/String;",
a=0;//             ">;)",
a=0;//             "Ljava/util/HashMap",
a=0;//             "<",
a=0;//             "Ljava/lang/String;",
a=0;//             "Ljava/lang/String;",
a=0;//             ">;"
a=0;//         }
a=0;//     .end annotation
a=0;// 
a=0;//     .prologue
a=0;//     .line 32
a=0;//     invoke-super {p0, p1}, Lcn/dm/android/c/e;->a(Ljava/util/HashMap;)Ljava/util/HashMap;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     .line 35
a=0;//     #v1=(Reference,Ljava/util/HashMap;);
a=0;//     const-string v0, "hwmodal"
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     iget-object v2, p0, Lcn/dm/android/c/b;->a:Landroid/content/Context;
a=0;// 
a=0;//     #v2=(Reference,Landroid/content/Context;);
a=0;//     invoke-static {v2}, Lcn/dm/android/f/a;->k(Landroid/content/Context;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-virtual {v1, v0, v2}, Ljava/util/HashMap;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
a=0;// 
a=0;//     .line 38
a=0;//     const-string v0, "carrier"
a=0;// 
a=0;//     iget-object v2, p0, Lcn/dm/android/c/b;->a:Landroid/content/Context;
a=0;// 
a=0;//     invoke-static {v2}, Lcn/dm/android/f/a;->l(Landroid/content/Context;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-virtual {v1, v0, v2}, Ljava/util/HashMap;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
a=0;// 
a=0;//     .line 42
a=0;//     const-string v0, "so"
a=0;// 
a=0;//     iget-object v2, p0, Lcn/dm/android/c/b;->a:Landroid/content/Context;
a=0;// 
a=0;//     invoke-static {v2}, Lcn/dm/android/f/a;->m(Landroid/content/Context;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-virtual {v1, v0, v2}, Ljava/util/HashMap;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
a=0;// 
a=0;//     .line 45
a=0;//     const-string v0, "sw"
a=0;// 
a=0;//     iget-object v2, p0, Lcn/dm/android/c/b;->a:Landroid/content/Context;
a=0;// 
a=0;//     invoke-static {v2}, Lcn/dm/android/f/a;->n(Landroid/content/Context;)I
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     invoke-static {v2}, Ljava/lang/String;->valueOf(I)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     #v2=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v1, v0, v2}, Ljava/util/HashMap;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
a=0;// 
a=0;//     .line 48
a=0;//     const-string v0, "sh"
a=0;// 
a=0;//     iget-object v2, p0, Lcn/dm/android/c/b;->a:Landroid/content/Context;
a=0;// 
a=0;//     invoke-static {v2}, Lcn/dm/android/f/a;->o(Landroid/content/Context;)I
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     invoke-static {v2}, Ljava/lang/String;->valueOf(I)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     #v2=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v1, v0, v2}, Ljava/util/HashMap;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
a=0;// 
a=0;//     .line 51
a=0;//     const-string v0, "sd"
a=0;// 
a=0;//     iget-object v2, p0, Lcn/dm/android/c/b;->a:Landroid/content/Context;
a=0;// 
a=0;//     invoke-static {v2}, Lcn/dm/android/f/a;->p(Landroid/content/Context;)F
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Float);
a=0;//     invoke-static {v2}, Ljava/lang/String;->valueOf(F)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     #v2=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v1, v0, v2}, Ljava/util/HashMap;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
a=0;// 
a=0;//     .line 55
a=0;//     const-string v0, "pkg_name"
a=0;// 
a=0;//     iget-object v2, p0, Lcn/dm/android/c/b;->a:Landroid/content/Context;
a=0;// 
a=0;//     invoke-static {v2}, Lcn/dm/android/f/a;->a(Landroid/content/Context;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-virtual {v1, v0, v2}, Ljava/util/HashMap;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
a=0;// 
a=0;//     .line 58
a=0;//     const-string v0, "pkg_vc"
a=0;// 
a=0;//     iget-object v2, p0, Lcn/dm/android/c/b;->a:Landroid/content/Context;
a=0;// 
a=0;//     invoke-static {v2}, Lcn/dm/android/f/a;->b(Landroid/content/Context;)I
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     invoke-static {v2}, Ljava/lang/String;->valueOf(I)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     #v2=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v1, v0, v2}, Ljava/util/HashMap;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
a=0;// 
a=0;//     .line 61
a=0;//     const-string v0, "pkg_vn"
a=0;// 
a=0;//     iget-object v2, p0, Lcn/dm/android/c/b;->a:Landroid/content/Context;
a=0;// 
a=0;//     invoke-static {v2}, Lcn/dm/android/f/a;->c(Landroid/content/Context;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-virtual {v1, v0, v2}, Ljava/util/HashMap;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
a=0;// 
a=0;//     .line 64
a=0;//     const-string v0, "app_name"
a=0;// 
a=0;//     iget-object v2, p0, Lcn/dm/android/c/b;->a:Landroid/content/Context;
a=0;// 
a=0;//     invoke-static {v2}, Lcn/dm/android/f/a;->d(Landroid/content/Context;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-virtual {v1, v0, v2}, Ljava/util/HashMap;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
a=0;// 
a=0;//     .line 67
a=0;//     invoke-static {}, Lcn/dm/android/c/f;->a()Lcn/dm/android/model/b;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Lcn/dm/android/model/b;->e()Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     const/4 v2, 0x1
a=0;// 
a=0;//     #v2=(One);
a=0;//     if-ne v0, v2, :cond_0
a=0;// 
a=0;//     .line 69
a=0;//     iget-object v0, p0, Lcn/dm/android/c/b;->a:Landroid/content/Context;
a=0;// 
a=0;//     #v0=(Reference,Landroid/content/Context;);
a=0;//     invoke-static {v0}, Lcn/dm/android/f/a;->q(Landroid/content/Context;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 70
a=0;//     if-eqz v0, :cond_3
a=0;// 
a=0;//     .line 71
a=0;//     const-string v2, "coord"
a=0;// 
a=0;//     #v2=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v1, v2, v0}, Ljava/util/HashMap;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
a=0;// 
a=0;//     .line 73
a=0;//     const-string v0, "coord_ts"
a=0;// 
a=0;//     invoke-static {}, Lcn/dm/android/f/a;->b()J
a=0;// 
a=0;//     move-result-wide v2
a=0;// 
a=0;//     #v2=(LongLo);v3=(LongHi);
a=0;//     invoke-static {v2, v3}, Ljava/lang/String;->valueOf(J)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     #v2=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v1, v0, v2}, Ljava/util/HashMap;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
a=0;// 
a=0;//     .line 81
a=0;//     :goto_0
a=0;//     #v3=(Conflicted);
a=0;//     const-string v0, "coord_acc"
a=0;// 
a=0;//     invoke-static {}, Lcn/dm/android/f/a;->c()I
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     invoke-static {v2}, Ljava/lang/String;->valueOf(I)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     #v2=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v1, v0, v2}, Ljava/util/HashMap;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
a=0;// 
a=0;//     .line 85
a=0;//     :cond_0
a=0;//     #v0=(Conflicted);v2=(Conflicted);
a=0;//     iget-object v0, p0, Lcn/dm/android/c/b;->a:Landroid/content/Context;
a=0;// 
a=0;//     #v0=(Reference,Landroid/content/Context;);
a=0;//     invoke-static {v0}, Lcn/dm/android/f/a;->r(Landroid/content/Context;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 86
a=0;//     if-eqz v0, :cond_1
a=0;// 
a=0;//     .line 87
a=0;//     const-string v2, "network"
a=0;// 
a=0;//     #v2=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v1, v2, v0}, Ljava/util/HashMap;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
a=0;// 
a=0;//     .line 90
a=0;//     :cond_1
a=0;//     #v2=(Conflicted);
a=0;//     const-string v0, "ma"
a=0;// 
a=0;//     iget-object v2, p0, Lcn/dm/android/c/b;->a:Landroid/content/Context;
a=0;// 
a=0;//     #v2=(Reference,Landroid/content/Context;);
a=0;//     invoke-static {v2}, Lcn/dm/android/f/a;->s(Landroid/content/Context;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-virtual {v1, v0, v2}, Ljava/util/HashMap;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
a=0;// 
a=0;//     .line 93
a=0;//     const-string v0, "ama"
a=0;// 
a=0;//     iget-object v2, p0, Lcn/dm/android/c/b;->a:Landroid/content/Context;
a=0;// 
a=0;//     invoke-static {v2}, Lcn/dm/android/f/a;->t(Landroid/content/Context;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-virtual {v1, v0, v2}, Ljava/util/HashMap;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
a=0;// 
a=0;//     .line 96
a=0;//     const-string v0, "an"
a=0;// 
a=0;//     iget-object v2, p0, Lcn/dm/android/c/b;->a:Landroid/content/Context;
a=0;// 
a=0;//     invoke-static {v2}, Lcn/dm/android/f/a;->u(Landroid/content/Context;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-virtual {v1, v0, v2}, Ljava/util/HashMap;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
a=0;// 
a=0;//     .line 98
a=0;//     const-string v0, "c"
a=0;// 
a=0;//     const-string v2, "DOWNLOAD,NOTR,TASKS"
a=0;// 
a=0;//     invoke-virtual {v1, v0, v2}, Ljava/util/HashMap;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
a=0;// 
a=0;//     .line 100
a=0;//     iget-object v0, p0, Lcn/dm/android/c/b;->a:Landroid/content/Context;
a=0;// 
a=0;//     invoke-static {v0}, Lcn/dm/android/f/a;->v(Landroid/content/Context;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 101
a=0;//     if-nez v0, :cond_2
a=0;// 
a=0;//     .line 102
a=0;//     const-string v0, ""
a=0;// 
a=0;//     .line 104
a=0;//     :cond_2
a=0;//     const-string v2, "odin1"
a=0;// 
a=0;//     invoke-virtual {v1, v2, v0}, Ljava/util/HashMap;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
a=0;// 
a=0;//     .line 106
a=0;//     const-string v0, "is_root"
a=0;// 
a=0;//     invoke-static {}, Lcn/dm/android/f/a;->e()Z
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Boolean);
a=0;//     invoke-static {v2}, Ljava/lang/String;->valueOf(Z)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     #v2=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v1, v0, v2}, Ljava/util/HashMap;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
a=0;// 
a=0;//     .line 108
a=0;//     const-string v0, "memoryinfo"
a=0;// 
a=0;//     iget-object v2, p0, Lcn/dm/android/c/b;->a:Landroid/content/Context;
a=0;// 
a=0;//     invoke-static {v2}, Lcn/dm/android/f/a;->y(Landroid/content/Context;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-virtual {v1, v0, v2}, Ljava/util/HashMap;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
a=0;// 
a=0;//     .line 110
a=0;//     const-string v0, "siminfo"
a=0;// 
a=0;//     iget-object v2, p0, Lcn/dm/android/c/b;->a:Landroid/content/Context;
a=0;// 
a=0;//     invoke-static {v2}, Lcn/dm/android/f/a;->w(Landroid/content/Context;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-virtual {v1, v0, v2}, Ljava/util/HashMap;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
a=0;// 
a=0;//     .line 112
a=0;//     const-string v0, "cpuinfo"
a=0;// 
a=0;//     iget-object v2, p0, Lcn/dm/android/c/b;->a:Landroid/content/Context;
a=0;// 
a=0;//     invoke-static {v2}, Lcn/dm/android/f/a;->x(Landroid/content/Context;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-virtual {v1, v0, v2}, Ljava/util/HashMap;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
a=0;// 
a=0;//     .line 114
a=0;//     const-string v0, "cis"
a=0;// 
a=0;//     iget-object v2, p0, Lcn/dm/android/c/b;->a:Landroid/content/Context;
a=0;// 
a=0;//     invoke-static {v2}, Lcn/dm/android/b/b;->b(Landroid/content/Context;)Lcn/dm/android/b/b;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     const-string v3, "imei_storage"
a=0;// 
a=0;//     #v3=(Reference,Ljava/lang/String;);
a=0;//     const/4 v4, 0x0
a=0;// 
a=0;//     #v4=(Null);
a=0;//     invoke-virtual {v2, v3, v4}, Lcn/dm/android/b/b;->a(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-virtual {v1, v0, v2}, Ljava/util/HashMap;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
a=0;// 
a=0;//     .line 117
a=0;//     return-object v1
a=0;// 
a=0;//     .line 77
a=0;//     :cond_3
a=0;//     #v2=(One);v3=(Uninit);v4=(Uninit);
a=0;//     const-string v0, "coord_status"
a=0;// 
a=0;//     invoke-static {}, Lcn/dm/android/f/a;->d()I
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     invoke-static {v2}, Ljava/lang/String;->valueOf(I)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     #v2=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v1, v0, v2}, Ljava/util/HashMap;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
a=0;// 
a=0;//     goto/16 :goto_0
a=0;// .end method
}}
