package cn.dm.android.c; class c$2 { void a() { int a;
a=0;// .class Lcn/dm/android/c/c$2;
a=0;// .super Ljava/lang/Object;
a=0;// .source "SourceFile"
a=0;// 
a=0;// # interfaces
a=0;// .implements Lcn/dm/android/listener/c;
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation system Ldalvik/annotation/EnclosingMethod;
a=0;//     value = Lcn/dm/android/c/c;->a(Lcn/dm/android/c/e;)V
a=0;// .end annotation
a=0;// 
a=0;// .annotation system Ldalvik/annotation/InnerClass;
a=0;//     accessFlags = 0x0
a=0;//     name = null
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field final synthetic a:Lcn/dm/android/c/c;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>(Lcn/dm/android/c/c;)V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 196
a=0;//     iput-object p1, p0, Lcn/dm/android/c/c$2;->a:Lcn/dm/android/c/c;
a=0;// 
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcn/dm/android/c/c$2;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public a(Lcn/dm/android/model/a;)V
a=0;//     .locals 2
a=0;// 
a=0;//     .prologue
a=0;//     .line 200
a=0;//     iget-object v0, p0, Lcn/dm/android/c/c$2;->a:Lcn/dm/android/c/c;
a=0;// 
a=0;//     #v0=(Reference,Lcn/dm/android/c/c;);
a=0;//     invoke-static {v0}, Lcn/dm/android/c/c;->a(Lcn/dm/android/c/c;)Lcn/dm/android/f/e;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, "Receive config response"
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v1}, Lcn/dm/android/f/e;->b(Ljava/lang/String;)V
a=0;// 
a=0;//     .line 201
a=0;//     if-eqz p1, :cond_0
a=0;// 
a=0;//     iget-object v0, p1, Lcn/dm/android/model/a;->b:Ljava/lang/String;
a=0;// 
a=0;//     invoke-static {v0}, Landroid/text/TextUtils;->isEmpty(Ljava/lang/CharSequence;)Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     if-nez v0, :cond_0
a=0;// 
a=0;//     .line 202
a=0;//     iget-object v0, p1, Lcn/dm/android/model/a;->b:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     invoke-static {v0}, Lcn/dm/android/model/b;->a(Ljava/lang/String;)Lcn/dm/android/model/b;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 203
a=0;//     if-eqz v0, :cond_1
a=0;// 
a=0;//     .line 204
a=0;//     invoke-static {v0}, Lcn/dm/android/c/f;->a(Lcn/dm/android/model/b;)V
a=0;// 
a=0;//     .line 211
a=0;//     :cond_0
a=0;//     :goto_0
a=0;//     #v0=(Conflicted);
a=0;//     iget-object v0, p0, Lcn/dm/android/c/c$2;->a:Lcn/dm/android/c/c;
a=0;// 
a=0;//     #v0=(Reference,Lcn/dm/android/c/c;);
a=0;//     invoke-static {v0}, Lcn/dm/android/c/c;->c(Lcn/dm/android/c/c;)V
a=0;// 
a=0;//     .line 212
a=0;//     return-void
a=0;// 
a=0;//     .line 208
a=0;//     :cond_1
a=0;//     iget-object v0, p0, Lcn/dm/android/c/c$2;->a:Lcn/dm/android/c/c;
a=0;// 
a=0;//     invoke-static {v0}, Lcn/dm/android/c/c;->b(Lcn/dm/android/c/c;)Landroid/content/Context;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, "resp_configparseerr"
a=0;// 
a=0;//     invoke-static {v0, v1}, Lcn/dm/android/f/i;->a(Landroid/content/Context;Ljava/lang/String;)V
a=0;// 
a=0;//     goto :goto_0
a=0;// .end method
a=0;// 
a=0;// .method public onError(Lcn/dm/android/model/ErrorInfo;)V
a=0;//     .locals 3
a=0;//     .param p1, "errorInfo"    # Lcn/dm/android/model/ErrorInfo;
a=0;// 
a=0;//     .prologue
a=0;//     .line 216
a=0;//     iget-object v0, p0, Lcn/dm/android/c/c$2;->a:Lcn/dm/android/c/c;
a=0;// 
a=0;//     #v0=(Reference,Lcn/dm/android/c/c;);
a=0;//     invoke-static {v0}, Lcn/dm/android/c/c;->a(Lcn/dm/android/c/c;)Lcn/dm/android/f/e;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     new-instance v1, Ljava/lang/StringBuilder;
a=0;// 
a=0;//     #v1=(UninitRef,Ljava/lang/StringBuilder;);
a=0;//     invoke-direct {v1}, Ljava/lang/StringBuilder;-><init>()V
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/StringBuilder;);
a=0;//     const-string v2, "\u51fa\u73b0\u5f02\u5e38-> code:["
a=0;// 
a=0;//     #v2=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {p1}, Lcn/dm/android/model/ErrorInfo;->getCode()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     const-string v2, "] text:["
a=0;// 
a=0;//     invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {p1}, Lcn/dm/android/model/ErrorInfo;->getText()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     const-string v2, "]"
a=0;// 
a=0;//     invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v1}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Lcn/dm/android/f/e;->e(Ljava/lang/String;)V
a=0;// 
a=0;//     .line 218
a=0;//     iget-object v0, p0, Lcn/dm/android/c/c$2;->a:Lcn/dm/android/c/c;
a=0;// 
a=0;//     invoke-static {v0}, Lcn/dm/android/c/c;->b(Lcn/dm/android/c/c;)Landroid/content/Context;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, "resp_configerr"
a=0;// 
a=0;//     invoke-static {v0, v1}, Lcn/dm/android/f/i;->a(Landroid/content/Context;Ljava/lang/String;)V
a=0;// 
a=0;//     .line 219
a=0;//     iget-object v0, p0, Lcn/dm/android/c/c$2;->a:Lcn/dm/android/c/c;
a=0;// 
a=0;//     invoke-static {v0}, Lcn/dm/android/c/c;->c(Lcn/dm/android/c/c;)V
a=0;// 
a=0;//     .line 220
a=0;//     return-void
a=0;// .end method
}}
