package com.lidroid.xutils.http; class ResponseInfo { void a() { int a;
a=0;// .class public final Lcom/lidroid/xutils/http/ResponseInfo;
a=0;// .super Ljava/lang/Object;
a=0;// .source "ResponseInfo.java"
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation system Ldalvik/annotation/Signature;
a=0;//     value = {
a=0;//         "<T:",
a=0;//         "Ljava/lang/Object;",
a=0;//         ">",
a=0;//         "Ljava/lang/Object;"
a=0;//     }
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field public final contentEncoding:Lorg/apache/http/Header;
a=0;// 
a=0;// .field public final contentLength:J
a=0;// 
a=0;// .field public final contentType:Lorg/apache/http/Header;
a=0;// 
a=0;// .field public final locale:Ljava/util/Locale;
a=0;// 
a=0;// .field public final protocolVersion:Lorg/apache/http/ProtocolVersion;
a=0;// 
a=0;// .field public final reasonPhrase:Ljava/lang/String;
a=0;// 
a=0;// .field private final response:Lorg/apache/http/HttpResponse;
a=0;// 
a=0;// .field public result:Ljava/lang/Object;
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "TT;"
a=0;//         }
a=0;//     .end annotation
a=0;// .end field
a=0;// 
a=0;// .field public final resultFormCache:Z
a=0;// 
a=0;// .field public final statusCode:I
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>(Lorg/apache/http/HttpResponse;Ljava/lang/Object;Z)V
a=0;//     .locals 7
a=0;//     .param p1, "response"    # Lorg/apache/http/HttpResponse;
a=0;//     .param p3, "resultFormCache"    # Z
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "(",
a=0;//             "Lorg/apache/http/HttpResponse;",
a=0;//             "TT;Z)V"
a=0;//         }
a=0;//     .end annotation
a=0;// 
a=0;//     .prologue
a=0;//     .local p0, "this":Lcom/lidroid/xutils/http/ResponseInfo;, "Lcom/lidroid/xutils/http/ResponseInfo<TT;>;"
a=0;//     .local p2, "result":Ljava/lang/Object;, "TT;"
a=0;//     const-wide/16 v5, 0x0
a=0;// 
a=0;//     #v5=(LongLo);v6=(LongHi);
a=0;//     const/4 v4, 0x0
a=0;// 
a=0;//     #v4=(Null);
a=0;//     const/4 v3, 0x0
a=0;// 
a=0;//     .line 50
a=0;//     #v3=(Null);
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     .line 51
a=0;//     #p0=(Reference,Lcom/lidroid/xutils/http/ResponseInfo;);
a=0;//     iput-object p1, p0, Lcom/lidroid/xutils/http/ResponseInfo;->response:Lorg/apache/http/HttpResponse;
a=0;// 
a=0;//     .line 52
a=0;//     iput-object p2, p0, Lcom/lidroid/xutils/http/ResponseInfo;->result:Ljava/lang/Object;
a=0;// 
a=0;//     .line 53
a=0;//     iput-boolean p3, p0, Lcom/lidroid/xutils/http/ResponseInfo;->resultFormCache:Z
a=0;// 
a=0;//     .line 55
a=0;//     if-eqz p1, :cond_2
a=0;// 
a=0;//     .line 56
a=0;//     invoke-interface {p1}, Lorg/apache/http/HttpResponse;->getLocale()Ljava/util/Locale;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     #v2=(Reference,Ljava/util/Locale;);
a=0;//     iput-object v2, p0, Lcom/lidroid/xutils/http/ResponseInfo;->locale:Ljava/util/Locale;
a=0;// 
a=0;//     .line 59
a=0;//     invoke-interface {p1}, Lorg/apache/http/HttpResponse;->getStatusLine()Lorg/apache/http/StatusLine;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     .line 60
a=0;//     .local v1, "statusLine":Lorg/apache/http/StatusLine;
a=0;//     #v1=(Reference,Lorg/apache/http/StatusLine;);
a=0;//     if-eqz v1, :cond_0
a=0;// 
a=0;//     .line 61
a=0;//     invoke-interface {v1}, Lorg/apache/http/StatusLine;->getStatusCode()I
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     iput v2, p0, Lcom/lidroid/xutils/http/ResponseInfo;->statusCode:I
a=0;// 
a=0;//     .line 62
a=0;//     invoke-interface {v1}, Lorg/apache/http/StatusLine;->getProtocolVersion()Lorg/apache/http/ProtocolVersion;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     #v2=(Reference,Lorg/apache/http/ProtocolVersion;);
a=0;//     iput-object v2, p0, Lcom/lidroid/xutils/http/ResponseInfo;->protocolVersion:Lorg/apache/http/ProtocolVersion;
a=0;// 
a=0;//     .line 63
a=0;//     invoke-interface {v1}, Lorg/apache/http/StatusLine;->getReasonPhrase()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     iput-object v2, p0, Lcom/lidroid/xutils/http/ResponseInfo;->reasonPhrase:Ljava/lang/String;
a=0;// 
a=0;//     .line 71
a=0;//     :goto_0
a=0;//     invoke-interface {p1}, Lorg/apache/http/HttpResponse;->getEntity()Lorg/apache/http/HttpEntity;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 72
a=0;//     .local v0, "entity":Lorg/apache/http/HttpEntity;
a=0;//     #v0=(Reference,Lorg/apache/http/HttpEntity;);
a=0;//     if-eqz v0, :cond_1
a=0;// 
a=0;//     .line 73
a=0;//     invoke-interface {v0}, Lorg/apache/http/HttpEntity;->getContentLength()J
a=0;// 
a=0;//     move-result-wide v2
a=0;// 
a=0;//     #v2=(LongLo);v3=(LongHi);
a=0;//     iput-wide v2, p0, Lcom/lidroid/xutils/http/ResponseInfo;->contentLength:J
a=0;// 
a=0;//     .line 74
a=0;//     invoke-interface {v0}, Lorg/apache/http/HttpEntity;->getContentType()Lorg/apache/http/Header;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     #v2=(Reference,Lorg/apache/http/Header;);
a=0;//     iput-object v2, p0, Lcom/lidroid/xutils/http/ResponseInfo;->contentType:Lorg/apache/http/Header;
a=0;// 
a=0;//     .line 75
a=0;//     invoke-interface {v0}, Lorg/apache/http/HttpEntity;->getContentEncoding()Lorg/apache/http/Header;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     iput-object v2, p0, Lcom/lidroid/xutils/http/ResponseInfo;->contentEncoding:Lorg/apache/http/Header;
a=0;// 
a=0;//     .line 94
a=0;//     .end local v0    # "entity":Lorg/apache/http/HttpEntity;
a=0;//     .end local v1    # "statusLine":Lorg/apache/http/StatusLine;
a=0;//     :goto_1
a=0;//     #v0=(Conflicted);v1=(Conflicted);v2=(Conflicted);v3=(Conflicted);
a=0;//     return-void
a=0;// 
a=0;//     .line 65
a=0;//     .restart local v1    # "statusLine":Lorg/apache/http/StatusLine;
a=0;//     :cond_0
a=0;//     #v0=(Uninit);v1=(Reference,Lorg/apache/http/StatusLine;);v2=(Reference,Ljava/util/Locale;);v3=(Null);
a=0;//     iput v4, p0, Lcom/lidroid/xutils/http/ResponseInfo;->statusCode:I
a=0;// 
a=0;//     .line 66
a=0;//     iput-object v3, p0, Lcom/lidroid/xutils/http/ResponseInfo;->protocolVersion:Lorg/apache/http/ProtocolVersion;
a=0;// 
a=0;//     .line 67
a=0;//     iput-object v3, p0, Lcom/lidroid/xutils/http/ResponseInfo;->reasonPhrase:Ljava/lang/String;
a=0;// 
a=0;//     goto :goto_0
a=0;// 
a=0;//     .line 77
a=0;//     .restart local v0    # "entity":Lorg/apache/http/HttpEntity;
a=0;//     :cond_1
a=0;//     #v0=(Reference,Lorg/apache/http/HttpEntity;);
a=0;//     iput-wide v5, p0, Lcom/lidroid/xutils/http/ResponseInfo;->contentLength:J
a=0;// 
a=0;//     .line 78
a=0;//     iput-object v3, p0, Lcom/lidroid/xutils/http/ResponseInfo;->contentType:Lorg/apache/http/Header;
a=0;// 
a=0;//     .line 79
a=0;//     iput-object v3, p0, Lcom/lidroid/xutils/http/ResponseInfo;->contentEncoding:Lorg/apache/http/Header;
a=0;// 
a=0;//     goto :goto_1
a=0;// 
a=0;//     .line 82
a=0;//     .end local v0    # "entity":Lorg/apache/http/HttpEntity;
a=0;//     .end local v1    # "statusLine":Lorg/apache/http/StatusLine;
a=0;//     :cond_2
a=0;//     #v0=(Uninit);v1=(Uninit);v2=(Uninit);
a=0;//     iput-object v3, p0, Lcom/lidroid/xutils/http/ResponseInfo;->locale:Ljava/util/Locale;
a=0;// 
a=0;//     .line 85
a=0;//     iput v4, p0, Lcom/lidroid/xutils/http/ResponseInfo;->statusCode:I
a=0;// 
a=0;//     .line 86
a=0;//     iput-object v3, p0, Lcom/lidroid/xutils/http/ResponseInfo;->protocolVersion:Lorg/apache/http/ProtocolVersion;
a=0;// 
a=0;//     .line 87
a=0;//     iput-object v3, p0, Lcom/lidroid/xutils/http/ResponseInfo;->reasonPhrase:Ljava/lang/String;
a=0;// 
a=0;//     .line 90
a=0;//     iput-wide v5, p0, Lcom/lidroid/xutils/http/ResponseInfo;->contentLength:J
a=0;// 
a=0;//     .line 91
a=0;//     iput-object v3, p0, Lcom/lidroid/xutils/http/ResponseInfo;->contentType:Lorg/apache/http/Header;
a=0;// 
a=0;//     .line 92
a=0;//     iput-object v3, p0, Lcom/lidroid/xutils/http/ResponseInfo;->contentEncoding:Lorg/apache/http/Header;
a=0;// 
a=0;//     goto :goto_1
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public getAllHeaders()[Lorg/apache/http/Header;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 31
a=0;//     .local p0, "this":Lcom/lidroid/xutils/http/ResponseInfo;, "Lcom/lidroid/xutils/http/ResponseInfo<TT;>;"
a=0;//     iget-object v0, p0, Lcom/lidroid/xutils/http/ResponseInfo;->response:Lorg/apache/http/HttpResponse;
a=0;// 
a=0;//     #v0=(Reference,Lorg/apache/http/HttpResponse;);
a=0;//     if-nez v0, :cond_0
a=0;// 
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     .line 32
a=0;//     :goto_0
a=0;//     return-object v0
a=0;// 
a=0;//     :cond_0
a=0;//     iget-object v0, p0, Lcom/lidroid/xutils/http/ResponseInfo;->response:Lorg/apache/http/HttpResponse;
a=0;// 
a=0;//     invoke-interface {v0}, Lorg/apache/http/HttpResponse;->getAllHeaders()[Lorg/apache/http/Header;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     goto :goto_0
a=0;// .end method
a=0;// 
a=0;// .method public getFirstHeader(Ljava/lang/String;)Lorg/apache/http/Header;
a=0;//     .locals 1
a=0;//     .param p1, "name"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 41
a=0;//     .local p0, "this":Lcom/lidroid/xutils/http/ResponseInfo;, "Lcom/lidroid/xutils/http/ResponseInfo<TT;>;"
a=0;//     iget-object v0, p0, Lcom/lidroid/xutils/http/ResponseInfo;->response:Lorg/apache/http/HttpResponse;
a=0;// 
a=0;//     #v0=(Reference,Lorg/apache/http/HttpResponse;);
a=0;//     if-nez v0, :cond_0
a=0;// 
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     .line 42
a=0;//     :goto_0
a=0;//     return-object v0
a=0;// 
a=0;//     :cond_0
a=0;//     iget-object v0, p0, Lcom/lidroid/xutils/http/ResponseInfo;->response:Lorg/apache/http/HttpResponse;
a=0;// 
a=0;//     invoke-interface {v0, p1}, Lorg/apache/http/HttpResponse;->getFirstHeader(Ljava/lang/String;)Lorg/apache/http/Header;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     goto :goto_0
a=0;// .end method
a=0;// 
a=0;// .method public getHeaders(Ljava/lang/String;)[Lorg/apache/http/Header;
a=0;//     .locals 1
a=0;//     .param p1, "name"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 36
a=0;//     .local p0, "this":Lcom/lidroid/xutils/http/ResponseInfo;, "Lcom/lidroid/xutils/http/ResponseInfo<TT;>;"
a=0;//     iget-object v0, p0, Lcom/lidroid/xutils/http/ResponseInfo;->response:Lorg/apache/http/HttpResponse;
a=0;// 
a=0;//     #v0=(Reference,Lorg/apache/http/HttpResponse;);
a=0;//     if-nez v0, :cond_0
a=0;// 
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     .line 37
a=0;//     :goto_0
a=0;//     return-object v0
a=0;// 
a=0;//     :cond_0
a=0;//     iget-object v0, p0, Lcom/lidroid/xutils/http/ResponseInfo;->response:Lorg/apache/http/HttpResponse;
a=0;// 
a=0;//     invoke-interface {v0, p1}, Lorg/apache/http/HttpResponse;->getHeaders(Ljava/lang/String;)[Lorg/apache/http/Header;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     goto :goto_0
a=0;// .end method
a=0;// 
a=0;// .method public getLastHeader(Ljava/lang/String;)Lorg/apache/http/Header;
a=0;//     .locals 1
a=0;//     .param p1, "name"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 46
a=0;//     .local p0, "this":Lcom/lidroid/xutils/http/ResponseInfo;, "Lcom/lidroid/xutils/http/ResponseInfo<TT;>;"
a=0;//     iget-object v0, p0, Lcom/lidroid/xutils/http/ResponseInfo;->response:Lorg/apache/http/HttpResponse;
a=0;// 
a=0;//     #v0=(Reference,Lorg/apache/http/HttpResponse;);
a=0;//     if-nez v0, :cond_0
a=0;// 
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     .line 47
a=0;//     :goto_0
a=0;//     return-object v0
a=0;// 
a=0;//     :cond_0
a=0;//     iget-object v0, p0, Lcom/lidroid/xutils/http/ResponseInfo;->response:Lorg/apache/http/HttpResponse;
a=0;// 
a=0;//     invoke-interface {v0, p1}, Lorg/apache/http/HttpResponse;->getLastHeader(Ljava/lang/String;)Lorg/apache/http/Header;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     goto :goto_0
a=0;// .end method
}}
