package com.twocloo.com.cn.task; class ReadBookInitTask { void a() { int a;
a=0;// .class public Lcom/twocloo/com/cn/task/ReadBookInitTask;
a=0;// .super Lcom/twocloo/base/sync/EasyTask;
a=0;// .source "ReadBookInitTask.java"
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation system Ldalvik/annotation/Signature;
a=0;//     value = {
a=0;//         "Lcom/twocloo/base/sync/EasyTask",
a=0;//         "<",
a=0;//         "Lcom/twocloo/com/cn/activitys/ReadbookDown;",
a=0;//         "Ljava/lang/Void;",
a=0;//         "Ljava/lang/Void;",
a=0;//         "Ljava/lang/Void;",
a=0;//         ">;"
a=0;//     }
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field private pd:Landroid/app/ProgressDialog;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>(Lcom/twocloo/com/cn/activitys/ReadbookDown;)V
a=0;//     .locals 0
a=0;//     .param p1, "caller"    # Lcom/twocloo/com/cn/activitys/ReadbookDown;
a=0;// 
a=0;//     .prologue
a=0;//     .line 28
a=0;//     invoke-direct {p0, p1}, Lcom/twocloo/base/sync/EasyTask;-><init>(Ljava/lang/Object;)V
a=0;// 
a=0;//     .line 29
a=0;//     #p0=(Reference,Lcom/twocloo/com/cn/task/ReadBookInitTask;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method static synthetic access$2(Lcom/twocloo/com/cn/task/ReadBookInitTask;)Ljava/lang/Object;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 24
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/task/ReadBookInitTask;->caller:Ljava/lang/Object;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/Object;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public bridge varargs synthetic doInBackground([Ljava/lang/Object;)Ljava/lang/Object;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 1
a=0;//     check-cast p1, [Ljava/lang/Void;
a=0;// 
a=0;//     invoke-virtual {p0, p1}, Lcom/twocloo/com/cn/task/ReadBookInitTask;->doInBackground([Ljava/lang/Void;)Ljava/lang/Void;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/Void;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public varargs doInBackground([Ljava/lang/Void;)Ljava/lang/Void;
a=0;//     .locals 6
a=0;//     .param p1, "params"    # [Ljava/lang/Void;
a=0;// 
a=0;//     .prologue
a=0;//     .line 45
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/task/ReadBookInitTask;->caller:Ljava/lang/Object;
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/Object;);
a=0;//     check-cast v1, Lcom/twocloo/com/cn/activitys/ReadbookDown;
a=0;// 
a=0;//     new-instance v3, Lcom/twocloo/com/cn/db/DBAdapter;
a=0;// 
a=0;//     #v3=(UninitRef,Lcom/twocloo/com/cn/db/DBAdapter;);
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/task/ReadBookInitTask;->caller:Ljava/lang/Object;
a=0;// 
a=0;//     #v2=(Reference,Ljava/lang/Object;);
a=0;//     check-cast v2, Landroid/content/Context;
a=0;// 
a=0;//     invoke-direct {v3, v2}, Lcom/twocloo/com/cn/db/DBAdapter;-><init>(Landroid/content/Context;)V
a=0;// 
a=0;//     #v3=(Reference,Lcom/twocloo/com/cn/db/DBAdapter;);
a=0;//     invoke-virtual {v1, v3}, Lcom/twocloo/com/cn/activitys/ReadbookDown;->setDbAdapter(Lcom/twocloo/com/cn/db/DBAdapter;)V
a=0;// 
a=0;//     .line 46
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/task/ReadBookInitTask;->caller:Ljava/lang/Object;
a=0;// 
a=0;//     check-cast v1, Lcom/twocloo/com/cn/activitys/ReadbookDown;
a=0;// 
a=0;//     invoke-virtual {v1}, Lcom/twocloo/com/cn/activitys/ReadbookDown;->getDbAdapter()Lcom/twocloo/com/cn/db/DBAdapter;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v1}, Lcom/twocloo/com/cn/db/DBAdapter;->open()V
a=0;// 
a=0;//     .line 47
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/task/ReadBookInitTask;->caller:Ljava/lang/Object;
a=0;// 
a=0;//     check-cast v1, Lcom/twocloo/com/cn/activitys/ReadbookDown;
a=0;// 
a=0;//     invoke-virtual {v1}, Lcom/twocloo/com/cn/activitys/ReadbookDown;->getBookFile()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-static {v1}, Landroid/text/TextUtils;->isEmpty(Ljava/lang/CharSequence;)Z
a=0;// 
a=0;//     move-result v1
a=0;// 
a=0;//     #v1=(Boolean);
a=0;//     if-eqz v1, :cond_0
a=0;// 
a=0;//     .line 48
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/task/ReadBookInitTask;->caller:Ljava/lang/Object;
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/Object;);
a=0;//     check-cast v1, Lcom/twocloo/com/cn/activitys/ReadbookDown;
a=0;// 
a=0;//     invoke-virtual {v1}, Lcom/twocloo/com/cn/activitys/ReadbookDown;->getAid()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-static {v1}, Landroid/text/TextUtils;->isEmpty(Ljava/lang/CharSequence;)Z
a=0;// 
a=0;//     move-result v1
a=0;// 
a=0;//     #v1=(Boolean);
a=0;//     if-nez v1, :cond_0
a=0;// 
a=0;//     .line 50
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/task/ReadBookInitTask;->caller:Ljava/lang/Object;
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/Object;);
a=0;//     check-cast v1, Lcom/twocloo/com/cn/activitys/ReadbookDown;
a=0;// 
a=0;//     new-instance v3, Ljava/io/File;
a=0;// 
a=0;//     #v3=(UninitRef,Ljava/io/File;);
a=0;//     new-instance v2, Ljava/lang/StringBuilder;
a=0;// 
a=0;//     #v2=(UninitRef,Ljava/lang/StringBuilder;);
a=0;//     sget-object v4, Lcom/twocloo/com/cn/common/Constants;->TWOCLOO_BOOK:Ljava/lang/String;
a=0;// 
a=0;//     #v4=(Reference,Ljava/lang/String;);
a=0;//     invoke-static {v4}, Ljava/lang/String;->valueOf(Ljava/lang/Object;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-direct {v2, v4}, Ljava/lang/StringBuilder;-><init>(Ljava/lang/String;)V
a=0;// 
a=0;//     #v2=(Reference,Ljava/lang/StringBuilder;);
a=0;//     const-string v4, "/"
a=0;// 
a=0;//     invoke-virtual {v2, v4}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/task/ReadBookInitTask;->caller:Ljava/lang/Object;
a=0;// 
a=0;//     check-cast v2, Lcom/twocloo/com/cn/activitys/ReadbookDown;
a=0;// 
a=0;//     invoke-virtual {v2}, Lcom/twocloo/com/cn/activitys/ReadbookDown;->getAid()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-virtual {v4, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-virtual {v2}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     new-instance v5, Ljava/lang/StringBuilder;
a=0;// 
a=0;//     #v5=(UninitRef,Ljava/lang/StringBuilder;);
a=0;//     const-string v2, "book_text_"
a=0;// 
a=0;//     invoke-direct {v5, v2}, Ljava/lang/StringBuilder;-><init>(Ljava/lang/String;)V
a=0;// 
a=0;//     #v5=(Reference,Ljava/lang/StringBuilder;);
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/task/ReadBookInitTask;->caller:Ljava/lang/Object;
a=0;// 
a=0;//     check-cast v2, Lcom/twocloo/com/cn/activitys/ReadbookDown;
a=0;// 
a=0;//     invoke-virtual {v2}, Lcom/twocloo/com/cn/activitys/ReadbookDown;->getAid()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-virtual {v5, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     const-string v5, ".txt"
a=0;// 
a=0;//     invoke-virtual {v2, v5}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-virtual {v2}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-direct {v3, v4, v2}, Ljava/io/File;-><init>(Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     .line 51
a=0;//     #v3=(Reference,Ljava/io/File;);
a=0;//     invoke-virtual {v3}, Ljava/io/File;->getPath()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     .line 50
a=0;//     invoke-virtual {v1, v2}, Lcom/twocloo/com/cn/activitys/ReadbookDown;->setBookFile(Ljava/lang/String;)V
a=0;// 
a=0;//     .line 55
a=0;//     :cond_0
a=0;//     #v1=(Conflicted);v4=(Conflicted);v5=(Conflicted);
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/task/ReadBookInitTask;->caller:Ljava/lang/Object;
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/Object;);
a=0;//     check-cast v1, Lcom/twocloo/com/cn/activitys/ReadbookDown;
a=0;// 
a=0;//     invoke-virtual {v1}, Lcom/twocloo/com/cn/activitys/ReadbookDown;->getBookFile()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-static {v1}, Landroid/text/TextUtils;->isEmpty(Ljava/lang/CharSequence;)Z
a=0;// 
a=0;//     move-result v1
a=0;// 
a=0;//     #v1=(Boolean);
a=0;//     if-nez v1, :cond_1
a=0;// 
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/task/ReadBookInitTask;->caller:Ljava/lang/Object;
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/Object;);
a=0;//     check-cast v1, Lcom/twocloo/com/cn/activitys/ReadbookDown;
a=0;// 
a=0;//     invoke-virtual {v1}, Lcom/twocloo/com/cn/activitys/ReadbookDown;->getAid()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-static {v1}, Landroid/text/TextUtils;->isEmpty(Ljava/lang/CharSequence;)Z
a=0;// 
a=0;//     move-result v1
a=0;// 
a=0;//     #v1=(Boolean);
a=0;//     if-nez v1, :cond_1
a=0;// 
a=0;//     .line 56
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/task/ReadBookInitTask;->caller:Ljava/lang/Object;
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/Object;);
a=0;//     check-cast v1, Lcom/twocloo/com/cn/activitys/ReadbookDown;
a=0;// 
a=0;//     invoke-virtual {v1}, Lcom/twocloo/com/cn/activitys/ReadbookDown;->getAid()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-static {v1}, Lcom/twocloo/com/cn/common/Util;->read(Ljava/lang/String;)Lcom/twocloo/com/cn/beans/Shubenmulu;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 57
a=0;//     .local v0, "mulu":Lcom/twocloo/com/cn/beans/Shubenmulu;
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/beans/Shubenmulu;);
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/task/ReadBookInitTask;->caller:Ljava/lang/Object;
a=0;// 
a=0;//     check-cast v1, Lcom/twocloo/com/cn/activitys/ReadbookDown;
a=0;// 
a=0;//     new-instance v3, Ljava/io/File;
a=0;// 
a=0;//     #v3=(UninitRef,Ljava/io/File;);
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/task/ReadBookInitTask;->caller:Ljava/lang/Object;
a=0;// 
a=0;//     check-cast v2, Lcom/twocloo/com/cn/activitys/ReadbookDown;
a=0;// 
a=0;//     invoke-virtual {v2}, Lcom/twocloo/com/cn/activitys/ReadbookDown;->getBookFile()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-direct {v3, v2}, Ljava/io/File;-><init>(Ljava/lang/String;)V
a=0;// 
a=0;//     #v3=(Reference,Ljava/io/File;);
a=0;//     invoke-virtual {v1, v3}, Lcom/twocloo/com/cn/activitys/ReadbookDown;->setFile(Ljava/io/File;)V
a=0;// 
a=0;//     .line 58
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/task/ReadBookInitTask;->caller:Ljava/lang/Object;
a=0;// 
a=0;//     check-cast v1, Lcom/twocloo/com/cn/activitys/ReadbookDown;
a=0;// 
a=0;//     invoke-virtual {v1, v0}, Lcom/twocloo/com/cn/activitys/ReadbookDown;->setMul(Lcom/twocloo/com/cn/beans/Shubenmulu;)V
a=0;// 
a=0;//     .line 59
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/task/ReadBookInitTask;->caller:Ljava/lang/Object;
a=0;// 
a=0;//     check-cast v1, Lcom/twocloo/com/cn/activitys/ReadbookDown;
a=0;// 
a=0;//     invoke-virtual {v1}, Lcom/twocloo/com/cn/activitys/ReadbookDown;->getDbAdapter()Lcom/twocloo/com/cn/db/DBAdapter;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/task/ReadBookInitTask;->caller:Ljava/lang/Object;
a=0;// 
a=0;//     check-cast v1, Lcom/twocloo/com/cn/activitys/ReadbookDown;
a=0;// 
a=0;//     invoke-virtual {v1}, Lcom/twocloo/com/cn/activitys/ReadbookDown;->getAid()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/task/ReadBookInitTask;->caller:Ljava/lang/Object;
a=0;// 
a=0;//     check-cast v1, Landroid/app/Activity;
a=0;// 
a=0;//     invoke-virtual {v2, v3, v1}, Lcom/twocloo/com/cn/db/DBAdapter;->updateSetBookLT(Ljava/lang/String;Landroid/app/Activity;)J
a=0;// 
a=0;//     .line 60
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/task/ReadBookInitTask;->caller:Ljava/lang/Object;
a=0;// 
a=0;//     check-cast v1, Lcom/twocloo/com/cn/activitys/ReadbookDown;
a=0;// 
a=0;//     invoke-virtual {v1}, Lcom/twocloo/com/cn/activitys/ReadbookDown;->getMul()Lcom/twocloo/com/cn/beans/Shubenmulu;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     if-nez v1, :cond_3
a=0;// 
a=0;//     if-nez v0, :cond_3
a=0;// 
a=0;//     .line 61
a=0;//     sget-object v1, Lcom/twocloo/com/cn/task/ReadBookInitTask;->HANDLER:Landroid/os/Handler;
a=0;// 
a=0;//     new-instance v2, Lcom/twocloo/com/cn/task/ReadBookInitTask$1;
a=0;// 
a=0;//     #v2=(UninitRef,Lcom/twocloo/com/cn/task/ReadBookInitTask$1;);
a=0;//     invoke-direct {v2, p0}, Lcom/twocloo/com/cn/task/ReadBookInitTask$1;-><init>(Lcom/twocloo/com/cn/task/ReadBookInitTask;)V
a=0;// 
a=0;//     #v2=(Reference,Lcom/twocloo/com/cn/task/ReadBookInitTask$1;);
a=0;//     invoke-virtual {v1, v2}, Landroid/os/Handler;->post(Ljava/lang/Runnable;)Z
a=0;// 
a=0;//     .line 80
a=0;//     .end local v0    # "mulu":Lcom/twocloo/com/cn/beans/Shubenmulu;
a=0;//     :cond_1
a=0;//     :goto_0
a=0;//     #v0=(Conflicted);v1=(Conflicted);
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/task/ReadBookInitTask;->caller:Ljava/lang/Object;
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/Object;);
a=0;//     check-cast v1, Lcom/twocloo/com/cn/activitys/ReadbookDown;
a=0;// 
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/task/ReadBookInitTask;->caller:Ljava/lang/Object;
a=0;// 
a=0;//     check-cast v2, Lcom/twocloo/com/cn/activitys/ReadbookDown;
a=0;// 
a=0;//     invoke-virtual {v2}, Lcom/twocloo/com/cn/activitys/ReadbookDown;->getDbAdapter()Lcom/twocloo/com/cn/db/DBAdapter;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/task/ReadBookInitTask;->caller:Ljava/lang/Object;
a=0;// 
a=0;//     check-cast v2, Lcom/twocloo/com/cn/activitys/ReadbookDown;
a=0;// 
a=0;//     invoke-virtual {v2}, Lcom/twocloo/com/cn/activitys/ReadbookDown;->getAid()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     #v4=(Reference,Ljava/lang/String;);
a=0;//     const/4 v5, 0x0
a=0;// 
a=0;//     #v5=(Null);
a=0;//     iget-object v2, p0, Lcom/twocloo/com/cn/task/ReadBookInitTask;->caller:Ljava/lang/Object;
a=0;// 
a=0;//     check-cast v2, Landroid/app/Activity;
a=0;// 
a=0;//     invoke-virtual {v3, v4, v5, v2}, Lcom/twocloo/com/cn/db/DBAdapter;->queryAllBookP(Ljava/lang/String;ILandroid/app/Activity;)Ljava/util/HashMap;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-virtual {v1, v2}, Lcom/twocloo/com/cn/activitys/ReadbookDown;->setSqmap(Ljava/util/HashMap;)V
a=0;// 
a=0;//     .line 81
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/task/ReadBookInitTask;->caller:Ljava/lang/Object;
a=0;// 
a=0;//     check-cast v1, Lcom/twocloo/com/cn/activitys/ReadbookDown;
a=0;// 
a=0;//     invoke-virtual {v1}, Lcom/twocloo/com/cn/activitys/ReadbookDown;->getCurChapterinfo()Lcom/twocloo/com/cn/beans/Chapterinfo;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     if-eqz v1, :cond_4
a=0;// 
a=0;//     .line 82
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/task/ReadBookInitTask;->caller:Ljava/lang/Object;
a=0;// 
a=0;//     check-cast v1, Lcom/twocloo/com/cn/activitys/ReadbookDown;
a=0;// 
a=0;//     invoke-virtual {v1}, Lcom/twocloo/com/cn/activitys/ReadbookDown;->getSqmap()Ljava/util/HashMap;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     new-instance v3, Ljava/lang/StringBuilder;
a=0;// 
a=0;//     #v3=(UninitRef,Ljava/lang/StringBuilder;);
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/task/ReadBookInitTask;->caller:Ljava/lang/Object;
a=0;// 
a=0;//     check-cast v1, Lcom/twocloo/com/cn/activitys/ReadbookDown;
a=0;// 
a=0;//     invoke-virtual {v1}, Lcom/twocloo/com/cn/activitys/ReadbookDown;->getCurChapterinfo()Lcom/twocloo/com/cn/beans/Chapterinfo;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v1}, Lcom/twocloo/com/cn/beans/Chapterinfo;->getId()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-static {v1}, Ljava/lang/String;->valueOf(Ljava/lang/Object;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-direct {v3, v1}, Ljava/lang/StringBuilder;-><init>(Ljava/lang/String;)V
a=0;// 
a=0;//     #v3=(Reference,Ljava/lang/StringBuilder;);
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/task/ReadBookInitTask;->caller:Ljava/lang/Object;
a=0;// 
a=0;//     check-cast v1, Lcom/twocloo/com/cn/activitys/ReadbookDown;
a=0;// 
a=0;//     invoke-virtual {v1}, Lcom/twocloo/com/cn/activitys/ReadbookDown;->getPagefactory()Lcom/twocloo/com/cn/view/BookPageFactory;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     iget v1, v1, Lcom/twocloo/com/cn/view/BookPageFactory;->m_mbBufBegin:I
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     invoke-virtual {v3, v1}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/StringBuilder;);
a=0;//     invoke-virtual {v1}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v2, v1}, Ljava/util/HashMap;->containsKey(Ljava/lang/Object;)Z
a=0;// 
a=0;//     move-result v1
a=0;// 
a=0;//     #v1=(Boolean);
a=0;//     if-eqz v1, :cond_4
a=0;// 
a=0;//     .line 83
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/task/ReadBookInitTask;->caller:Ljava/lang/Object;
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/Object;);
a=0;//     check-cast v1, Lcom/twocloo/com/cn/activitys/ReadbookDown;
a=0;// 
a=0;//     invoke-virtual {v1}, Lcom/twocloo/com/cn/activitys/ReadbookDown;->getAddMark()Landroid/widget/ImageView;
a=0;// 
a=0;//     .line 100
a=0;//     :cond_2
a=0;//     :goto_1
a=0;//     invoke-static {}, Lcom/twocloo/com/cn/common/PageFlipController;->getInstance()Lcom/twocloo/com/cn/common/PageFlipController;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/task/ReadBookInitTask;->caller:Ljava/lang/Object;
a=0;// 
a=0;//     check-cast v1, Lcom/twocloo/com/cn/activitys/ReadbookDown;
a=0;// 
a=0;//     invoke-virtual {v2, v1}, Lcom/twocloo/com/cn/common/PageFlipController;->handler(Lcom/twocloo/com/cn/activitys/ReadbookDown;)V
a=0;// 
a=0;//     .line 101
a=0;//     const/4 v1, 0x0
a=0;// 
a=0;//     #v1=(Null);
a=0;//     return-object v1
a=0;// 
a=0;//     .line 68
a=0;//     .restart local v0    # "mulu":Lcom/twocloo/com/cn/beans/Shubenmulu;
a=0;//     :cond_3
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/beans/Shubenmulu;);v1=(Reference,Lcom/twocloo/com/cn/beans/Shubenmulu;);v4=(Conflicted);v5=(Conflicted);
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/task/ReadBookInitTask;->caller:Ljava/lang/Object;
a=0;// 
a=0;//     check-cast v1, Lcom/twocloo/com/cn/activitys/ReadbookDown;
a=0;// 
a=0;//     invoke-virtual {v1}, Lcom/twocloo/com/cn/activitys/ReadbookDown;->setTxMap()V
a=0;// 
a=0;//     .line 69
a=0;//     sget-object v1, Lcom/twocloo/com/cn/task/ReadBookInitTask;->HANDLER:Landroid/os/Handler;
a=0;// 
a=0;//     new-instance v2, Lcom/twocloo/com/cn/task/ReadBookInitTask$2;
a=0;// 
a=0;//     #v2=(UninitRef,Lcom/twocloo/com/cn/task/ReadBookInitTask$2;);
a=0;//     invoke-direct {v2, p0}, Lcom/twocloo/com/cn/task/ReadBookInitTask$2;-><init>(Lcom/twocloo/com/cn/task/ReadBookInitTask;)V
a=0;// 
a=0;//     #v2=(Reference,Lcom/twocloo/com/cn/task/ReadBookInitTask$2;);
a=0;//     invoke-virtual {v1, v2}, Landroid/os/Handler;->post(Ljava/lang/Runnable;)Z
a=0;// 
a=0;//     goto/16 :goto_0
a=0;// 
a=0;//     .line 87
a=0;//     .end local v0    # "mulu":Lcom/twocloo/com/cn/beans/Shubenmulu;
a=0;//     :cond_4
a=0;//     #v0=(Conflicted);v1=(Conflicted);v4=(Reference,Ljava/lang/String;);v5=(Null);
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/task/ReadBookInitTask;->caller:Ljava/lang/Object;
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/Object;);
a=0;//     check-cast v1, Lcom/twocloo/com/cn/activitys/ReadbookDown;
a=0;// 
a=0;//     invoke-virtual {v1}, Lcom/twocloo/com/cn/activitys/ReadbookDown;->getAddMark()Landroid/widget/ImageView;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     if-eqz v1, :cond_2
a=0;// 
a=0;//     .line 88
a=0;//     sget-object v1, Lcom/twocloo/com/cn/task/ReadBookInitTask;->HANDLER:Landroid/os/Handler;
a=0;// 
a=0;//     new-instance v2, Lcom/twocloo/com/cn/task/ReadBookInitTask$3;
a=0;// 
a=0;//     #v2=(UninitRef,Lcom/twocloo/com/cn/task/ReadBookInitTask$3;);
a=0;//     invoke-direct {v2, p0}, Lcom/twocloo/com/cn/task/ReadBookInitTask$3;-><init>(Lcom/twocloo/com/cn/task/ReadBookInitTask;)V
a=0;// 
a=0;//     #v2=(Reference,Lcom/twocloo/com/cn/task/ReadBookInitTask$3;);
a=0;//     invoke-virtual {v1, v2}, Landroid/os/Handler;->post(Ljava/lang/Runnable;)Z
a=0;// 
a=0;//     goto :goto_1
a=0;// .end method
a=0;// 
a=0;// .method public bridge synthetic onPostExecute(Ljava/lang/Object;)V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 1
a=0;//     check-cast p1, Ljava/lang/Void;
a=0;// 
a=0;//     invoke-virtual {p0, p1}, Lcom/twocloo/com/cn/task/ReadBookInitTask;->onPostExecute(Ljava/lang/Void;)V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public onPostExecute(Ljava/lang/Void;)V
a=0;//     .locals 1
a=0;//     .param p1, "result"    # Ljava/lang/Void;
a=0;// 
a=0;//     .prologue
a=0;//     .line 40
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/task/ReadBookInitTask;->pd:Landroid/app/ProgressDialog;
a=0;// 
a=0;//     #v0=(Reference,Landroid/app/ProgressDialog;);
a=0;//     invoke-virtual {v0}, Landroid/app/ProgressDialog;->cancel()V
a=0;// 
a=0;//     .line 41
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public onPreExecute()V
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 34
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/task/ReadBookInitTask;->caller:Ljava/lang/Object;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/Object;);
a=0;//     check-cast v0, Landroid/content/Context;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/twocloo/base/util/ViewUtils;->progressLoading(Landroid/content/Context;)Landroid/app/ProgressDialog;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, p0, Lcom/twocloo/com/cn/task/ReadBookInitTask;->pd:Landroid/app/ProgressDialog;
a=0;// 
a=0;//     .line 35
a=0;//     return-void
a=0;// .end method
}}
