package com.tencent.tauth; class LocationApi$BaseRequestListener { void a() { int a;
a=0;// .class abstract Lcom/tencent/tauth/LocationApi$BaseRequestListener;
a=0;// .super Ljava/lang/Object;
a=0;// .source "ProGuard"
a=0;// 
a=0;// # interfaces
a=0;// .implements Lcom/tencent/tauth/IRequestListener;
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation system Ldalvik/annotation/EnclosingClass;
a=0;//     value = Lcom/tencent/tauth/LocationApi;
a=0;// .end annotation
a=0;// 
a=0;// .annotation system Ldalvik/annotation/InnerClass;
a=0;//     accessFlags = 0x402
a=0;//     name = "BaseRequestListener"
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field final synthetic this$0:Lcom/tencent/tauth/LocationApi;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method private constructor <init>(Lcom/tencent/tauth/LocationApi;)V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 278
a=0;//     iput-object p1, p0, Lcom/tencent/tauth/LocationApi$BaseRequestListener;->this$0:Lcom/tencent/tauth/LocationApi;
a=0;// 
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcom/tencent/tauth/LocationApi$BaseRequestListener;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method synthetic constructor <init>(Lcom/tencent/tauth/LocationApi;Lcom/tencent/tauth/LocationApi$1;)V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 278
a=0;//     invoke-direct {p0, p1}, Lcom/tencent/tauth/LocationApi$BaseRequestListener;-><init>(Lcom/tencent/tauth/LocationApi;)V
a=0;// 
a=0;//     #p0=(Reference,Lcom/tencent/tauth/LocationApi$BaseRequestListener;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method protected abstract handleException(Ljava/lang/Exception;)V
a=0;// .end method
a=0;// 
a=0;// .method public onConnectTimeoutException(Lorg/apache/http/conn/ConnectTimeoutException;)V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 298
a=0;//     invoke-virtual {p0, p1}, Lcom/tencent/tauth/LocationApi$BaseRequestListener;->handleException(Ljava/lang/Exception;)V
a=0;// 
a=0;//     .line 299
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public onHttpStatusException(Lcom/tencent/utils/HttpUtils$HttpStatusException;)V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 313
a=0;//     invoke-virtual {p0, p1}, Lcom/tencent/tauth/LocationApi$BaseRequestListener;->handleException(Ljava/lang/Exception;)V
a=0;// 
a=0;//     .line 314
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public onIOException(Ljava/io/IOException;)V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 283
a=0;//     invoke-virtual {p0, p1}, Lcom/tencent/tauth/LocationApi$BaseRequestListener;->handleException(Ljava/lang/Exception;)V
a=0;// 
a=0;//     .line 284
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public onJSONException(Lorg/json/JSONException;)V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 293
a=0;//     invoke-virtual {p0, p1}, Lcom/tencent/tauth/LocationApi$BaseRequestListener;->handleException(Ljava/lang/Exception;)V
a=0;// 
a=0;//     .line 294
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public onMalformedURLException(Ljava/net/MalformedURLException;)V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 288
a=0;//     invoke-virtual {p0, p1}, Lcom/tencent/tauth/LocationApi$BaseRequestListener;->handleException(Ljava/lang/Exception;)V
a=0;// 
a=0;//     .line 289
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public onNetworkUnavailableException(Lcom/tencent/utils/HttpUtils$NetworkUnavailableException;)V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 308
a=0;//     invoke-virtual {p0, p1}, Lcom/tencent/tauth/LocationApi$BaseRequestListener;->handleException(Ljava/lang/Exception;)V
a=0;// 
a=0;//     .line 309
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public onSocketTimeoutException(Ljava/net/SocketTimeoutException;)V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 303
a=0;//     invoke-virtual {p0, p1}, Lcom/tencent/tauth/LocationApi$BaseRequestListener;->handleException(Ljava/lang/Exception;)V
a=0;// 
a=0;//     .line 304
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public onUnknowException(Ljava/lang/Exception;)V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 318
a=0;//     invoke-virtual {p0, p1}, Lcom/tencent/tauth/LocationApi$BaseRequestListener;->handleException(Ljava/lang/Exception;)V
a=0;// 
a=0;//     .line 319
a=0;//     return-void
a=0;// .end method
}}
