package net.slidingmenu.tools.video; class h { void a() { int a;
a=0;// .class Lnet/slidingmenu/tools/video/h;
a=0;// .super Ljava/lang/Object;
a=0;// 
a=0;// # interfaces
a=0;// .implements Landroid/view/View$OnClickListener;
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field final synthetic a:Lnet/slidingmenu/tools/video/slidingcaxc;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>(Lnet/slidingmenu/tools/video/slidingcaxc;)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-object p1, p0, Lnet/slidingmenu/tools/video/h;->a:Lnet/slidingmenu/tools/video/slidingcaxc;
a=0;// 
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lnet/slidingmenu/tools/video/h;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public onClick(Landroid/view/View;)V
a=0;//     .locals 2
a=0;// 
a=0;//     iget-object v0, p0, Lnet/slidingmenu/tools/video/h;->a:Lnet/slidingmenu/tools/video/slidingcaxc;
a=0;// 
a=0;//     #v0=(Reference,Lnet/slidingmenu/tools/video/slidingcaxc;);
a=0;//     invoke-static {v0}, Lnet/slidingmenu/tools/video/slidingcaxc;->a(Lnet/slidingmenu/tools/video/slidingcaxc;)Lnet/slidingmenu/tools/video/a;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     if-eqz v0, :cond_1
a=0;// 
a=0;//     iget-object v0, p0, Lnet/slidingmenu/tools/video/h;->a:Lnet/slidingmenu/tools/video/slidingcaxc;
a=0;// 
a=0;//     invoke-static {v0}, Lnet/slidingmenu/tools/video/slidingcaxc;->a(Lnet/slidingmenu/tools/video/slidingcaxc;)Lnet/slidingmenu/tools/video/a;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Lnet/slidingmenu/tools/video/a;->isShowing()Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     if-eqz v0, :cond_1
a=0;// 
a=0;//     invoke-virtual {p1}, Landroid/view/View;->getId()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     const/16 v1, 0x3ec
a=0;// 
a=0;//     #v1=(PosShort);
a=0;//     if-eq v0, v1, :cond_0
a=0;// 
a=0;//     invoke-virtual {p1}, Landroid/view/View;->getId()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     const/16 v1, 0x3eb
a=0;// 
a=0;//     if-ne v0, v1, :cond_2
a=0;// 
a=0;//     :cond_0
a=0;//     iget-object v0, p0, Lnet/slidingmenu/tools/video/h;->a:Lnet/slidingmenu/tools/video/slidingcaxc;
a=0;// 
a=0;//     #v0=(Reference,Lnet/slidingmenu/tools/video/slidingcaxc;);
a=0;//     invoke-static {v0}, Lnet/slidingmenu/tools/video/slidingcaxc;->a(Lnet/slidingmenu/tools/video/slidingcaxc;)Lnet/slidingmenu/tools/video/a;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Lnet/slidingmenu/tools/video/a;->dismiss()V
a=0;// 
a=0;//     iget-object v0, p0, Lnet/slidingmenu/tools/video/h;->a:Lnet/slidingmenu/tools/video/slidingcaxc;
a=0;// 
a=0;//     invoke-virtual {v0}, Lnet/slidingmenu/tools/video/slidingcaxc;->finish()V
a=0;// 
a=0;//     :cond_1
a=0;//     :goto_0
a=0;//     #v0=(Conflicted);v1=(Conflicted);
a=0;//     return-void
a=0;// 
a=0;//     :cond_2
a=0;//     #v0=(Integer);v1=(PosShort);
a=0;//     invoke-virtual {p1}, Landroid/view/View;->getId()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     const/16 v1, 0x3ed
a=0;// 
a=0;//     if-ne v0, v1, :cond_3
a=0;// 
a=0;//     iget-object v0, p0, Lnet/slidingmenu/tools/video/h;->a:Lnet/slidingmenu/tools/video/slidingcaxc;
a=0;// 
a=0;//     #v0=(Reference,Lnet/slidingmenu/tools/video/slidingcaxc;);
a=0;//     invoke-static {v0}, Lnet/slidingmenu/tools/video/slidingcaxc;->a(Lnet/slidingmenu/tools/video/slidingcaxc;)Lnet/slidingmenu/tools/video/a;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Lnet/slidingmenu/tools/video/a;->dismiss()V
a=0;// 
a=0;//     iget-object v0, p0, Lnet/slidingmenu/tools/video/h;->a:Lnet/slidingmenu/tools/video/slidingcaxc;
a=0;// 
a=0;//     invoke-static {v0}, Lnet/slidingmenu/tools/video/slidingcaxc;->b(Lnet/slidingmenu/tools/video/slidingcaxc;)Lnet/slidingmenu/tools/video/a/f;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     if-eqz v0, :cond_1
a=0;// 
a=0;//     iget-object v0, p0, Lnet/slidingmenu/tools/video/h;->a:Lnet/slidingmenu/tools/video/slidingcaxc;
a=0;// 
a=0;//     invoke-static {v0}, Lnet/slidingmenu/tools/video/slidingcaxc;->b(Lnet/slidingmenu/tools/video/slidingcaxc;)Lnet/slidingmenu/tools/video/a/f;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Lnet/slidingmenu/tools/video/a/f;->b()Landroid/widget/VideoView;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     if-eqz v0, :cond_1
a=0;// 
a=0;//     iget-object v0, p0, Lnet/slidingmenu/tools/video/h;->a:Lnet/slidingmenu/tools/video/slidingcaxc;
a=0;// 
a=0;//     invoke-static {v0}, Lnet/slidingmenu/tools/video/slidingcaxc;->b(Lnet/slidingmenu/tools/video/slidingcaxc;)Lnet/slidingmenu/tools/video/a/f;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Lnet/slidingmenu/tools/video/a/f;->d()V
a=0;// 
a=0;//     goto :goto_0
a=0;// 
a=0;//     :cond_3
a=0;//     #v0=(Integer);
a=0;//     invoke-virtual {p1}, Landroid/view/View;->getId()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     const/16 v1, 0x3ee
a=0;// 
a=0;//     if-ne v0, v1, :cond_1
a=0;// 
a=0;//     iget-object v0, p0, Lnet/slidingmenu/tools/video/h;->a:Lnet/slidingmenu/tools/video/slidingcaxc;
a=0;// 
a=0;//     #v0=(Reference,Lnet/slidingmenu/tools/video/slidingcaxc;);
a=0;//     invoke-static {v0}, Lnet/slidingmenu/tools/video/slidingcaxc;->a(Lnet/slidingmenu/tools/video/slidingcaxc;)Lnet/slidingmenu/tools/video/a;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Lnet/slidingmenu/tools/video/a;->dismiss()V
a=0;// 
a=0;//     iget-object v0, p0, Lnet/slidingmenu/tools/video/h;->a:Lnet/slidingmenu/tools/video/slidingcaxc;
a=0;// 
a=0;//     invoke-static {v0}, Lnet/slidingmenu/tools/video/slidingcaxc;->b(Lnet/slidingmenu/tools/video/slidingcaxc;)Lnet/slidingmenu/tools/video/a/f;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     if-eqz v0, :cond_4
a=0;// 
a=0;//     iget-object v0, p0, Lnet/slidingmenu/tools/video/h;->a:Lnet/slidingmenu/tools/video/slidingcaxc;
a=0;// 
a=0;//     invoke-static {v0}, Lnet/slidingmenu/tools/video/slidingcaxc;->b(Lnet/slidingmenu/tools/video/slidingcaxc;)Lnet/slidingmenu/tools/video/a/f;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Lnet/slidingmenu/tools/video/a/f;->c()V
a=0;// 
a=0;//     iget-object v0, p0, Lnet/slidingmenu/tools/video/h;->a:Lnet/slidingmenu/tools/video/slidingcaxc;
a=0;// 
a=0;//     const/4 v1, 0x1
a=0;// 
a=0;//     #v1=(One);
a=0;//     invoke-static {v0, v1}, Lnet/slidingmenu/tools/video/slidingcaxc;->a(Lnet/slidingmenu/tools/video/slidingcaxc;Z)Z
a=0;// 
a=0;//     :cond_4
a=0;//     #v1=(PosShort);
a=0;//     iget-object v0, p0, Lnet/slidingmenu/tools/video/h;->a:Lnet/slidingmenu/tools/video/slidingcaxc;
a=0;// 
a=0;//     const/4 v1, 0x0
a=0;// 
a=0;//     #v1=(Null);
a=0;//     invoke-static {v0, v1}, Lnet/slidingmenu/tools/video/slidingcaxc;->a(Lnet/slidingmenu/tools/video/slidingcaxc;Lnet/slidingmenu/tools/video/a;)Lnet/slidingmenu/tools/video/a;
a=0;// 
a=0;//     goto :goto_0
a=0;// .end method
}}
