package cn.sharesdk.framework.authorize; class AuthorizeAdapter { void a() { int a;
a=0;// .class public Lcn/sharesdk/framework/authorize/AuthorizeAdapter;
a=0;// .super Ljava/lang/Object;
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field private activity:Landroid/app/Activity;
a=0;// 
a=0;// .field private noTitle:Z
a=0;// 
a=0;// .field private platform:Ljava/lang/String;
a=0;// 
a=0;// .field private popUpAnimationDisable:Z
a=0;// 
a=0;// .field private rlBody:Landroid/widget/RelativeLayout;
a=0;// 
a=0;// .field private title:Lcn/sharesdk/framework/TitleLayout;
a=0;// 
a=0;// .field private webview:Landroid/webkit/WebView;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcn/sharesdk/framework/authorize/AuthorizeAdapter;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method protected disablePopUpAnimation()V
a=0;//     .locals 1
a=0;// 
a=0;//     const/4 v0, 0x1
a=0;// 
a=0;//     #v0=(One);
a=0;//     iput-boolean v0, p0, Lcn/sharesdk/framework/authorize/AuthorizeAdapter;->popUpAnimationDisable:Z
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public getActivity()Landroid/app/Activity;
a=0;//     .locals 1
a=0;// 
a=0;//     iget-object v0, p0, Lcn/sharesdk/framework/authorize/AuthorizeAdapter;->activity:Landroid/app/Activity;
a=0;// 
a=0;//     #v0=(Reference,Landroid/app/Activity;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getBodyView()Landroid/widget/RelativeLayout;
a=0;//     .locals 1
a=0;// 
a=0;//     iget-object v0, p0, Lcn/sharesdk/framework/authorize/AuthorizeAdapter;->rlBody:Landroid/widget/RelativeLayout;
a=0;// 
a=0;//     #v0=(Reference,Landroid/widget/RelativeLayout;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getPlatformName()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     iget-object v0, p0, Lcn/sharesdk/framework/authorize/AuthorizeAdapter;->platform:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getTitleLayout()Lcn/sharesdk/framework/TitleLayout;
a=0;//     .locals 1
a=0;// 
a=0;//     iget-object v0, p0, Lcn/sharesdk/framework/authorize/AuthorizeAdapter;->title:Lcn/sharesdk/framework/TitleLayout;
a=0;// 
a=0;//     #v0=(Reference,Lcn/sharesdk/framework/TitleLayout;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getWebBody()Landroid/webkit/WebView;
a=0;//     .locals 1
a=0;// 
a=0;//     iget-object v0, p0, Lcn/sharesdk/framework/authorize/AuthorizeAdapter;->webview:Landroid/webkit/WebView;
a=0;// 
a=0;//     #v0=(Reference,Landroid/webkit/WebView;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public hideShareSDKLogo()V
a=0;//     .locals 2
a=0;// 
a=0;//     invoke-virtual {p0}, Lcn/sharesdk/framework/authorize/AuthorizeAdapter;->getTitleLayout()Lcn/sharesdk/framework/TitleLayout;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Lcn/sharesdk/framework/TitleLayout;);
a=0;//     invoke-virtual {v0}, Lcn/sharesdk/framework/TitleLayout;->getChildCount()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     invoke-virtual {p0}, Lcn/sharesdk/framework/authorize/AuthorizeAdapter;->getTitleLayout()Lcn/sharesdk/framework/TitleLayout;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     #v1=(Reference,Lcn/sharesdk/framework/TitleLayout;);
a=0;//     add-int/lit8 v0, v0, -0x1
a=0;// 
a=0;//     invoke-virtual {v1, v0}, Lcn/sharesdk/framework/TitleLayout;->getChildAt(I)Landroid/view/View;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Landroid/view/View;);
a=0;//     const/16 v1, 0x8
a=0;// 
a=0;//     #v1=(PosByte);
a=0;//     invoke-virtual {v0, v1}, Landroid/view/View;->setVisibility(I)V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method isNotitle()Z
a=0;//     .locals 1
a=0;// 
a=0;//     iget-boolean v0, p0, Lcn/sharesdk/framework/authorize/AuthorizeAdapter;->noTitle:Z
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method isPopUpAnimationDisable()Z
a=0;//     .locals 1
a=0;// 
a=0;//     iget-boolean v0, p0, Lcn/sharesdk/framework/authorize/AuthorizeAdapter;->popUpAnimationDisable:Z
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public onCreate()V
a=0;//     .locals 0
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public onDestroy()V
a=0;//     .locals 0
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public onFinish()Z
a=0;//     .locals 1
a=0;// 
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public onKeyEvent(ILandroid/view/KeyEvent;)Z
a=0;//     .locals 1
a=0;// 
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public onPause()V
a=0;//     .locals 0
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public onResize(IIII)V
a=0;//     .locals 0
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public onRestart()V
a=0;//     .locals 0
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public onResume()V
a=0;//     .locals 0
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public onStart()V
a=0;//     .locals 0
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public onStop()V
a=0;//     .locals 0
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method setActivity(Landroid/app/Activity;)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-object p1, p0, Lcn/sharesdk/framework/authorize/AuthorizeAdapter;->activity:Landroid/app/Activity;
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method setBodyView(Landroid/widget/RelativeLayout;)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-object p1, p0, Lcn/sharesdk/framework/authorize/AuthorizeAdapter;->rlBody:Landroid/widget/RelativeLayout;
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method setNotitle(Z)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-boolean p1, p0, Lcn/sharesdk/framework/authorize/AuthorizeAdapter;->noTitle:Z
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method setPlatformName(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-object p1, p0, Lcn/sharesdk/framework/authorize/AuthorizeAdapter;->platform:Ljava/lang/String;
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method setTitleView(Lcn/sharesdk/framework/TitleLayout;)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-object p1, p0, Lcn/sharesdk/framework/authorize/AuthorizeAdapter;->title:Lcn/sharesdk/framework/TitleLayout;
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method setWebView(Landroid/webkit/WebView;)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-object p1, p0, Lcn/sharesdk/framework/authorize/AuthorizeAdapter;->webview:Landroid/webkit/WebView;
a=0;// 
a=0;//     return-void
a=0;// .end method
}}
