package com.ffcs.inapppaylib.exception; class HttpException { void a() { int a;
a=0;// .class public Lcom/ffcs/inapppaylib/exception/HttpException;
a=0;// .super Lcom/ffcs/inapppaylib/exception/BaseException;
a=0;// .source "HttpException.java"
a=0;// 
a=0;// 
a=0;// # static fields
a=0;// .field private static final serialVersionUID:J = 0x1L
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field private exceptionCode:I
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 23
a=0;//     invoke-direct {p0}, Lcom/ffcs/inapppaylib/exception/BaseException;-><init>()V
a=0;// 
a=0;//     .line 24
a=0;//     #p0=(Reference,Lcom/ffcs/inapppaylib/exception/HttpException;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public constructor <init>(I)V
a=0;//     .locals 0
a=0;//     .param p1, "exceptionCode"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 41
a=0;//     invoke-direct {p0}, Lcom/ffcs/inapppaylib/exception/BaseException;-><init>()V
a=0;// 
a=0;//     .line 42
a=0;//     #p0=(Reference,Lcom/ffcs/inapppaylib/exception/HttpException;);
a=0;//     iput p1, p0, Lcom/ffcs/inapppaylib/exception/HttpException;->exceptionCode:I
a=0;// 
a=0;//     .line 43
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public constructor <init>(ILjava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "exceptionCode"    # I
a=0;//     .param p2, "detailMessage"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 50
a=0;//     invoke-direct {p0, p2}, Lcom/ffcs/inapppaylib/exception/BaseException;-><init>(Ljava/lang/String;)V
a=0;// 
a=0;//     .line 51
a=0;//     #p0=(Reference,Lcom/ffcs/inapppaylib/exception/HttpException;);
a=0;//     iput p1, p0, Lcom/ffcs/inapppaylib/exception/HttpException;->exceptionCode:I
a=0;// 
a=0;//     .line 52
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public constructor <init>(ILjava/lang/String;Ljava/lang/Throwable;)V
a=0;//     .locals 0
a=0;//     .param p1, "exceptionCode"    # I
a=0;//     .param p2, "detailMessage"    # Ljava/lang/String;
a=0;//     .param p3, "throwable"    # Ljava/lang/Throwable;
a=0;// 
a=0;//     .prologue
a=0;//     .line 60
a=0;//     invoke-direct {p0, p2, p3}, Lcom/ffcs/inapppaylib/exception/BaseException;-><init>(Ljava/lang/String;Ljava/lang/Throwable;)V
a=0;// 
a=0;//     .line 61
a=0;//     #p0=(Reference,Lcom/ffcs/inapppaylib/exception/HttpException;);
a=0;//     iput p1, p0, Lcom/ffcs/inapppaylib/exception/HttpException;->exceptionCode:I
a=0;// 
a=0;//     .line 62
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public constructor <init>(ILjava/lang/Throwable;)V
a=0;//     .locals 0
a=0;//     .param p1, "exceptionCode"    # I
a=0;//     .param p2, "throwable"    # Ljava/lang/Throwable;
a=0;// 
a=0;//     .prologue
a=0;//     .line 69
a=0;//     invoke-direct {p0, p2}, Lcom/ffcs/inapppaylib/exception/BaseException;-><init>(Ljava/lang/Throwable;)V
a=0;// 
a=0;//     .line 70
a=0;//     #p0=(Reference,Lcom/ffcs/inapppaylib/exception/HttpException;);
a=0;//     iput p1, p0, Lcom/ffcs/inapppaylib/exception/HttpException;->exceptionCode:I
a=0;// 
a=0;//     .line 71
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public constructor <init>(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "detailMessage"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 27
a=0;//     invoke-direct {p0, p1}, Lcom/ffcs/inapppaylib/exception/BaseException;-><init>(Ljava/lang/String;)V
a=0;// 
a=0;//     .line 28
a=0;//     #p0=(Reference,Lcom/ffcs/inapppaylib/exception/HttpException;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public constructor <init>(Ljava/lang/String;Ljava/lang/Throwable;)V
a=0;//     .locals 0
a=0;//     .param p1, "detailMessage"    # Ljava/lang/String;
a=0;//     .param p2, "throwable"    # Ljava/lang/Throwable;
a=0;// 
a=0;//     .prologue
a=0;//     .line 31
a=0;//     invoke-direct {p0, p1, p2}, Lcom/ffcs/inapppaylib/exception/BaseException;-><init>(Ljava/lang/String;Ljava/lang/Throwable;)V
a=0;// 
a=0;//     .line 32
a=0;//     #p0=(Reference,Lcom/ffcs/inapppaylib/exception/HttpException;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public constructor <init>(Ljava/lang/Throwable;)V
a=0;//     .locals 0
a=0;//     .param p1, "throwable"    # Ljava/lang/Throwable;
a=0;// 
a=0;//     .prologue
a=0;//     .line 35
a=0;//     invoke-direct {p0, p1}, Lcom/ffcs/inapppaylib/exception/BaseException;-><init>(Ljava/lang/Throwable;)V
a=0;// 
a=0;//     .line 36
a=0;//     #p0=(Reference,Lcom/ffcs/inapppaylib/exception/HttpException;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public getExceptionCode()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 77
a=0;//     iget v0, p0, Lcom/ffcs/inapppaylib/exception/HttpException;->exceptionCode:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
}}
