package android.support.v4.app; class NotificationCompat$BigPictureStyle { void a() { int a;
a=0;// .class public Landroid/support/v4/app/NotificationCompat$BigPictureStyle;
a=0;// .super Landroid/support/v4/app/NotificationCompat$Style;
a=0;// .source "NotificationCompat.java"
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation system Ldalvik/annotation/EnclosingClass;
a=0;//     value = Landroid/support/v4/app/NotificationCompat;
a=0;// .end annotation
a=0;// 
a=0;// .annotation system Ldalvik/annotation/InnerClass;
a=0;//     accessFlags = 0x9
a=0;//     name = "BigPictureStyle"
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field mPicture:Landroid/graphics/Bitmap;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 615
a=0;//     invoke-direct {p0}, Landroid/support/v4/app/NotificationCompat$Style;-><init>()V
a=0;// 
a=0;//     .line 616
a=0;//     #p0=(Reference,Landroid/support/v4/app/NotificationCompat$BigPictureStyle;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public constructor <init>(Landroid/support/v4/app/NotificationCompat$Builder;)V
a=0;//     .locals 0
a=0;//     .param p1, "builder"    # Landroid/support/v4/app/NotificationCompat$Builder;
a=0;// 
a=0;//     .prologue
a=0;//     .line 618
a=0;//     invoke-direct {p0}, Landroid/support/v4/app/NotificationCompat$Style;-><init>()V
a=0;// 
a=0;//     .line 619
a=0;//     #p0=(Reference,Landroid/support/v4/app/NotificationCompat$BigPictureStyle;);
a=0;//     invoke-virtual {p0, p1}, Landroid/support/v4/app/NotificationCompat$BigPictureStyle;->setBuilder(Landroid/support/v4/app/NotificationCompat$Builder;)V
a=0;// 
a=0;//     .line 620
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public bigPicture(Landroid/graphics/Bitmap;)Landroid/support/v4/app/NotificationCompat$BigPictureStyle;
a=0;//     .locals 0
a=0;//     .param p1, "b"    # Landroid/graphics/Bitmap;
a=0;// 
a=0;//     .prologue
a=0;//     .line 644
a=0;//     iput-object p1, p0, Landroid/support/v4/app/NotificationCompat$BigPictureStyle;->mPicture:Landroid/graphics/Bitmap;
a=0;// 
a=0;//     .line 645
a=0;//     return-object p0
a=0;// .end method
a=0;// 
a=0;// .method public setBigContentTitle(Ljava/lang/CharSequence;)Landroid/support/v4/app/NotificationCompat$BigPictureStyle;
a=0;//     .locals 0
a=0;//     .param p1, "title"    # Ljava/lang/CharSequence;
a=0;// 
a=0;//     .prologue
a=0;//     .line 627
a=0;//     iput-object p1, p0, Landroid/support/v4/app/NotificationCompat$BigPictureStyle;->mBigContentTitle:Ljava/lang/CharSequence;
a=0;// 
a=0;//     .line 628
a=0;//     return-object p0
a=0;// .end method
a=0;// 
a=0;// .method public setSummaryText(Ljava/lang/CharSequence;)Landroid/support/v4/app/NotificationCompat$BigPictureStyle;
a=0;//     .locals 1
a=0;//     .param p1, "cs"    # Ljava/lang/CharSequence;
a=0;// 
a=0;//     .prologue
a=0;//     .line 635
a=0;//     iput-object p1, p0, Landroid/support/v4/app/NotificationCompat$BigPictureStyle;->mSummaryText:Ljava/lang/CharSequence;
a=0;// 
a=0;//     .line 636
a=0;//     const/4 v0, 0x1
a=0;// 
a=0;//     #v0=(One);
a=0;//     iput-boolean v0, p0, Landroid/support/v4/app/NotificationCompat$BigPictureStyle;->mSummaryTextSet:Z
a=0;// 
a=0;//     .line 637
a=0;//     return-object p0
a=0;// .end method
}}
