package com.nineoldandroids.view; class ViewPropertyAnimator { void a() { int a;
a=0;// .class public abstract Lcom/nineoldandroids/view/ViewPropertyAnimator;
a=0;// .super Ljava/lang/Object;
a=0;// .source "ViewPropertyAnimator.java"
a=0;// 
a=0;// 
a=0;// # static fields
a=0;// .field private static final ANIMATORS:Ljava/util/WeakHashMap;
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "Ljava/util/WeakHashMap",
a=0;//             "<",
a=0;//             "Landroid/view/View;",
a=0;//             "Lcom/nineoldandroids/view/ViewPropertyAnimator;",
a=0;//             ">;"
a=0;//         }
a=0;//     .end annotation
a=0;// .end field
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method static constructor <clinit>()V
a=0;//     .locals 2
a=0;// 
a=0;//     .prologue
a=0;//     .line 48
a=0;//     new-instance v0, Ljava/util/WeakHashMap;
a=0;// 
a=0;//     #v0=(UninitRef,Ljava/util/WeakHashMap;);
a=0;//     const/4 v1, 0x0
a=0;// 
a=0;//     #v1=(Null);
a=0;//     invoke-direct {v0, v1}, Ljava/util/WeakHashMap;-><init>(I)V
a=0;// 
a=0;//     .line 47
a=0;//     #v0=(Reference,Ljava/util/WeakHashMap;);
a=0;//     sput-object v0, Lcom/nineoldandroids/view/ViewPropertyAnimator;->ANIMATORS:Ljava/util/WeakHashMap;
a=0;// 
a=0;//     .line 48
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 46
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcom/nineoldandroids/view/ViewPropertyAnimator;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static animate(Landroid/view/View;)Lcom/nineoldandroids/view/ViewPropertyAnimator;
a=0;//     .locals 3
a=0;//     .param p0, "view"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 58
a=0;//     sget-object v2, Lcom/nineoldandroids/view/ViewPropertyAnimator;->ANIMATORS:Ljava/util/WeakHashMap;
a=0;// 
a=0;//     #v2=(Reference,Ljava/util/WeakHashMap;);
a=0;//     invoke-virtual {v2, p0}, Ljava/util/WeakHashMap;->get(Ljava/lang/Object;)Ljava/lang/Object;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/Object;);
a=0;//     check-cast v0, Lcom/nineoldandroids/view/ViewPropertyAnimator;
a=0;// 
a=0;//     .line 59
a=0;//     .local v0, "animator":Lcom/nineoldandroids/view/ViewPropertyAnimator;
a=0;//     if-nez v0, :cond_0
a=0;// 
a=0;//     .line 60
a=0;//     sget-object v2, Landroid/os/Build$VERSION;->SDK:Ljava/lang/String;
a=0;// 
a=0;//     invoke-static {v2}, Ljava/lang/Integer;->valueOf(Ljava/lang/String;)Ljava/lang/Integer;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-virtual {v2}, Ljava/lang/Integer;->intValue()I
a=0;// 
a=0;//     move-result v1
a=0;// 
a=0;//     .line 61
a=0;//     .local v1, "version":I
a=0;//     #v1=(Integer);
a=0;//     const/16 v2, 0xe
a=0;// 
a=0;//     #v2=(PosByte);
a=0;//     if-lt v1, v2, :cond_1
a=0;// 
a=0;//     .line 62
a=0;//     new-instance v0, Lcom/nineoldandroids/view/ViewPropertyAnimatorICS;
a=0;// 
a=0;//     .end local v0    # "animator":Lcom/nineoldandroids/view/ViewPropertyAnimator;
a=0;//     #v0=(UninitRef,Lcom/nineoldandroids/view/ViewPropertyAnimatorICS;);
a=0;//     invoke-direct {v0, p0}, Lcom/nineoldandroids/view/ViewPropertyAnimatorICS;-><init>(Landroid/view/View;)V
a=0;// 
a=0;//     .line 68
a=0;//     .restart local v0    # "animator":Lcom/nineoldandroids/view/ViewPropertyAnimator;
a=0;//     :goto_0
a=0;//     #v0=(Reference,Ujava/lang/Object;);
a=0;//     sget-object v2, Lcom/nineoldandroids/view/ViewPropertyAnimator;->ANIMATORS:Ljava/util/WeakHashMap;
a=0;// 
a=0;//     #v2=(Reference,Ljava/util/WeakHashMap;);
a=0;//     invoke-virtual {v2, p0, v0}, Ljava/util/WeakHashMap;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
a=0;// 
a=0;//     .line 70
a=0;//     .end local v1    # "version":I
a=0;//     :cond_0
a=0;//     #v1=(Conflicted);
a=0;//     return-object v0
a=0;// 
a=0;//     .line 63
a=0;//     .restart local v1    # "version":I
a=0;//     :cond_1
a=0;//     #v1=(Integer);v2=(PosByte);
a=0;//     const/16 v2, 0xb
a=0;// 
a=0;//     if-lt v1, v2, :cond_2
a=0;// 
a=0;//     .line 64
a=0;//     new-instance v0, Lcom/nineoldandroids/view/ViewPropertyAnimatorHC;
a=0;// 
a=0;//     .end local v0    # "animator":Lcom/nineoldandroids/view/ViewPropertyAnimator;
a=0;//     #v0=(UninitRef,Lcom/nineoldandroids/view/ViewPropertyAnimatorHC;);
a=0;//     invoke-direct {v0, p0}, Lcom/nineoldandroids/view/ViewPropertyAnimatorHC;-><init>(Landroid/view/View;)V
a=0;// 
a=0;//     .line 65
a=0;//     .restart local v0    # "animator":Lcom/nineoldandroids/view/ViewPropertyAnimator;
a=0;//     #v0=(Reference,Lcom/nineoldandroids/view/ViewPropertyAnimatorHC;);
a=0;//     goto :goto_0
a=0;// 
a=0;//     .line 66
a=0;//     :cond_2
a=0;//     new-instance v0, Lcom/nineoldandroids/view/ViewPropertyAnimatorPreHC;
a=0;// 
a=0;//     .end local v0    # "animator":Lcom/nineoldandroids/view/ViewPropertyAnimator;
a=0;//     #v0=(UninitRef,Lcom/nineoldandroids/view/ViewPropertyAnimatorPreHC;);
a=0;//     invoke-direct {v0, p0}, Lcom/nineoldandroids/view/ViewPropertyAnimatorPreHC;-><init>(Landroid/view/View;)V
a=0;// 
a=0;//     .restart local v0    # "animator":Lcom/nineoldandroids/view/ViewPropertyAnimator;
a=0;//     #v0=(Reference,Lcom/nineoldandroids/view/ViewPropertyAnimatorPreHC;);
a=0;//     goto :goto_0
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public abstract alpha(F)Lcom/nineoldandroids/view/ViewPropertyAnimator;
a=0;// .end method
a=0;// 
a=0;// .method public abstract alphaBy(F)Lcom/nineoldandroids/view/ViewPropertyAnimator;
a=0;// .end method
a=0;// 
a=0;// .method public abstract cancel()V
a=0;// .end method
a=0;// 
a=0;// .method public abstract getDuration()J
a=0;// .end method
a=0;// 
a=0;// .method public abstract getStartDelay()J
a=0;// .end method
a=0;// 
a=0;// .method public abstract rotation(F)Lcom/nineoldandroids/view/ViewPropertyAnimator;
a=0;// .end method
a=0;// 
a=0;// .method public abstract rotationBy(F)Lcom/nineoldandroids/view/ViewPropertyAnimator;
a=0;// .end method
a=0;// 
a=0;// .method public abstract rotationX(F)Lcom/nineoldandroids/view/ViewPropertyAnimator;
a=0;// .end method
a=0;// 
a=0;// .method public abstract rotationXBy(F)Lcom/nineoldandroids/view/ViewPropertyAnimator;
a=0;// .end method
a=0;// 
a=0;// .method public abstract rotationY(F)Lcom/nineoldandroids/view/ViewPropertyAnimator;
a=0;// .end method
a=0;// 
a=0;// .method public abstract rotationYBy(F)Lcom/nineoldandroids/view/ViewPropertyAnimator;
a=0;// .end method
a=0;// 
a=0;// .method public abstract scaleX(F)Lcom/nineoldandroids/view/ViewPropertyAnimator;
a=0;// .end method
a=0;// 
a=0;// .method public abstract scaleXBy(F)Lcom/nineoldandroids/view/ViewPropertyAnimator;
a=0;// .end method
a=0;// 
a=0;// .method public abstract scaleY(F)Lcom/nineoldandroids/view/ViewPropertyAnimator;
a=0;// .end method
a=0;// 
a=0;// .method public abstract scaleYBy(F)Lcom/nineoldandroids/view/ViewPropertyAnimator;
a=0;// .end method
a=0;// 
a=0;// .method public abstract setDuration(J)Lcom/nineoldandroids/view/ViewPropertyAnimator;
a=0;// .end method
a=0;// 
a=0;// .method public abstract setInterpolator(Landroid/view/animation/Interpolator;)Lcom/nineoldandroids/view/ViewPropertyAnimator;
a=0;// .end method
a=0;// 
a=0;// .method public abstract setListener(Lcom/nineoldandroids/animation/Animator$AnimatorListener;)Lcom/nineoldandroids/view/ViewPropertyAnimator;
a=0;// .end method
a=0;// 
a=0;// .method public abstract setStartDelay(J)Lcom/nineoldandroids/view/ViewPropertyAnimator;
a=0;// .end method
a=0;// 
a=0;// .method public abstract start()V
a=0;// .end method
a=0;// 
a=0;// .method public abstract translationX(F)Lcom/nineoldandroids/view/ViewPropertyAnimator;
a=0;// .end method
a=0;// 
a=0;// .method public abstract translationXBy(F)Lcom/nineoldandroids/view/ViewPropertyAnimator;
a=0;// .end method
a=0;// 
a=0;// .method public abstract translationY(F)Lcom/nineoldandroids/view/ViewPropertyAnimator;
a=0;// .end method
a=0;// 
a=0;// .method public abstract translationYBy(F)Lcom/nineoldandroids/view/ViewPropertyAnimator;
a=0;// .end method
a=0;// 
a=0;// .method public abstract x(F)Lcom/nineoldandroids/view/ViewPropertyAnimator;
a=0;// .end method
a=0;// 
a=0;// .method public abstract xBy(F)Lcom/nineoldandroids/view/ViewPropertyAnimator;
a=0;// .end method
a=0;// 
a=0;// .method public abstract y(F)Lcom/nineoldandroids/view/ViewPropertyAnimator;
a=0;// .end method
a=0;// 
a=0;// .method public abstract yBy(F)Lcom/nineoldandroids/view/ViewPropertyAnimator;
a=0;// .end method
}}
