package safiap.framework.ui; class h { void a() { int a;
a=0;// .class final Lsafiap/framework/ui/h;
a=0;// .super Ljava/lang/Object;
a=0;// .source "SourceFile"
a=0;// 
a=0;// # interfaces
a=0;// .implements Lsafiap/framework/ui/res/LayoutDialog$a;
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field private synthetic a:Lsafiap/framework/ui/UpdateHintActivity;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>(Lsafiap/framework/ui/UpdateHintActivity;)V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 444
a=0;//     iput-object p1, p0, Lsafiap/framework/ui/h;->a:Lsafiap/framework/ui/UpdateHintActivity;
a=0;// 
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lsafiap/framework/ui/h;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public final a()V
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 449
a=0;//     iget-object v0, p0, Lsafiap/framework/ui/h;->a:Lsafiap/framework/ui/UpdateHintActivity;
a=0;// 
a=0;//     #v0=(Reference,Lsafiap/framework/ui/UpdateHintActivity;);
a=0;//     invoke-static {v0}, Lsafiap/framework/ui/UpdateHintActivity;->a(Lsafiap/framework/ui/UpdateHintActivity;)Lsafiap/framework/ui/res/d;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Lsafiap/framework/ui/res/d;->dismiss()V
a=0;// 
a=0;//     .line 450
a=0;//     iget-object v0, p0, Lsafiap/framework/ui/h;->a:Lsafiap/framework/ui/UpdateHintActivity;
a=0;// 
a=0;//     invoke-virtual {v0}, Lsafiap/framework/ui/UpdateHintActivity;->finish()V
a=0;// 
a=0;//     .line 451
a=0;//     return-void
a=0;// .end method
}}
