package cn.sharesdk.framework; class o { void a() { int a;
a=0;// .class Lcn/sharesdk/framework/o;
a=0;// .super Ljava/lang/Object;
a=0;// 
a=0;// # interfaces
a=0;// .implements Ljava/util/Comparator;
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation system Ldalvik/annotation/Signature;
a=0;//     value = {
a=0;//         "Ljava/lang/Object;",
a=0;//         "Ljava/util/Comparator",
a=0;//         "<",
a=0;//         "Lcn/sharesdk/framework/Platform;",
a=0;//         ">;"
a=0;//     }
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field final synthetic a:Lcn/sharesdk/framework/n;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>(Lcn/sharesdk/framework/n;)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-object p1, p0, Lcn/sharesdk/framework/o;->a:Lcn/sharesdk/framework/n;
a=0;// 
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcn/sharesdk/framework/o;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public a(Lcn/sharesdk/framework/Platform;Lcn/sharesdk/framework/Platform;)I
a=0;//     .locals 2
a=0;// 
a=0;//     invoke-virtual {p1}, Lcn/sharesdk/framework/Platform;->getSortId()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     invoke-virtual {p2}, Lcn/sharesdk/framework/Platform;->getSortId()I
a=0;// 
a=0;//     move-result v1
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     if-eq v0, v1, :cond_0
a=0;// 
a=0;//     invoke-virtual {p1}, Lcn/sharesdk/framework/Platform;->getSortId()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     invoke-virtual {p2}, Lcn/sharesdk/framework/Platform;->getSortId()I
a=0;// 
a=0;//     move-result v1
a=0;// 
a=0;//     sub-int/2addr v0, v1
a=0;// 
a=0;//     :goto_0
a=0;//     return v0
a=0;// 
a=0;//     :cond_0
a=0;//     invoke-virtual {p1}, Lcn/sharesdk/framework/Platform;->getPlatformId()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     invoke-virtual {p2}, Lcn/sharesdk/framework/Platform;->getPlatformId()I
a=0;// 
a=0;//     move-result v1
a=0;// 
a=0;//     sub-int/2addr v0, v1
a=0;// 
a=0;//     goto :goto_0
a=0;// .end method
a=0;// 
a=0;// .method public synthetic compare(Ljava/lang/Object;Ljava/lang/Object;)I
a=0;//     .locals 1
a=0;// 
a=0;//     check-cast p1, Lcn/sharesdk/framework/Platform;
a=0;// 
a=0;//     check-cast p2, Lcn/sharesdk/framework/Platform;
a=0;// 
a=0;//     invoke-virtual {p0, p1, p2}, Lcn/sharesdk/framework/o;->a(Lcn/sharesdk/framework/Platform;Lcn/sharesdk/framework/Platform;)I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
}}
