package cn.sharesdk.framework; class ShareSDK { void a() { int a;
a=0;// .class public Lcn/sharesdk/framework/ShareSDK;
a=0;// .super Ljava/lang/Object;
a=0;// 
a=0;// 
a=0;// # static fields
a=0;// .field private static a:Lcn/sharesdk/framework/p;
a=0;// 
a=0;// .field private static b:Z
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method static constructor <clinit>()V
a=0;//     .locals 1
a=0;// 
a=0;//     const/4 v0, 0x1
a=0;// 
a=0;//     #v0=(One);
a=0;//     sput-boolean v0, Lcn/sharesdk/framework/ShareSDK;->b:Z
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcn/sharesdk/framework/ShareSDK;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method static a(ILjava/lang/String;)Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     invoke-static {}, Lcn/sharesdk/framework/ShareSDK;->c()V
a=0;// 
a=0;//     sget-object v0, Lcn/sharesdk/framework/ShareSDK;->a:Lcn/sharesdk/framework/p;
a=0;// 
a=0;//     #v0=(Reference,Lcn/sharesdk/framework/p;);
a=0;//     invoke-virtual {v0, p0, p1}, Lcn/sharesdk/framework/p;->a(ILjava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method static a(Landroid/graphics/Bitmap;)Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     invoke-static {}, Lcn/sharesdk/framework/ShareSDK;->c()V
a=0;// 
a=0;//     sget-object v0, Lcn/sharesdk/framework/ShareSDK;->a:Lcn/sharesdk/framework/p;
a=0;// 
a=0;//     #v0=(Reference,Lcn/sharesdk/framework/p;);
a=0;//     invoke-virtual {v0, p0}, Lcn/sharesdk/framework/p;->a(Landroid/graphics/Bitmap;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method static a(Ljava/lang/String;)Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     invoke-static {}, Lcn/sharesdk/framework/ShareSDK;->c()V
a=0;// 
a=0;//     sget-object v0, Lcn/sharesdk/framework/ShareSDK;->a:Lcn/sharesdk/framework/p;
a=0;// 
a=0;//     #v0=(Reference,Lcn/sharesdk/framework/p;);
a=0;//     invoke-virtual {v0, p0}, Lcn/sharesdk/framework/p;->d(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method static a(Ljava/lang/String;ZILjava/lang/String;)Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     invoke-static {}, Lcn/sharesdk/framework/ShareSDK;->c()V
a=0;// 
a=0;//     sget-object v0, Lcn/sharesdk/framework/ShareSDK;->a:Lcn/sharesdk/framework/p;
a=0;// 
a=0;//     #v0=(Reference,Lcn/sharesdk/framework/p;);
a=0;//     invoke-virtual {v0, p0, p1, p2, p3}, Lcn/sharesdk/framework/p;->a(Ljava/lang/String;ZILjava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method static a(II)V
a=0;//     .locals 1
a=0;// 
a=0;//     invoke-static {}, Lcn/sharesdk/framework/ShareSDK;->c()V
a=0;// 
a=0;//     sget-object v0, Lcn/sharesdk/framework/ShareSDK;->a:Lcn/sharesdk/framework/p;
a=0;// 
a=0;//     #v0=(Reference,Lcn/sharesdk/framework/p;);
a=0;//     invoke-virtual {v0, p0, p1}, Lcn/sharesdk/framework/p;->a(II)V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method static a(Ljava/lang/String;Ljava/lang/String;)V
a=0;//     .locals 1
a=0;// 
a=0;//     invoke-static {}, Lcn/sharesdk/framework/ShareSDK;->c()V
a=0;// 
a=0;//     sget-object v0, Lcn/sharesdk/framework/ShareSDK;->a:Lcn/sharesdk/framework/p;
a=0;// 
a=0;//     #v0=(Reference,Lcn/sharesdk/framework/p;);
a=0;//     invoke-virtual {v0, p0, p1}, Lcn/sharesdk/framework/p;->a(Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method static a()Z
a=0;//     .locals 1
a=0;// 
a=0;//     invoke-static {}, Lcn/sharesdk/framework/ShareSDK;->c()V
a=0;// 
a=0;//     sget-object v0, Lcn/sharesdk/framework/ShareSDK;->a:Lcn/sharesdk/framework/p;
a=0;// 
a=0;//     #v0=(Reference,Lcn/sharesdk/framework/p;);
a=0;//     invoke-virtual {v0}, Lcn/sharesdk/framework/p;->g()Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method static a(Ljava/util/HashMap;)Z
a=0;//     .locals 1
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "(",
a=0;//             "Ljava/util/HashMap",
a=0;//             "<",
a=0;//             "Ljava/lang/String;",
a=0;//             "Ljava/lang/Object;",
a=0;//             ">;)Z"
a=0;//         }
a=0;//     .end annotation
a=0;// 
a=0;//     invoke-static {}, Lcn/sharesdk/framework/ShareSDK;->c()V
a=0;// 
a=0;//     sget-object v0, Lcn/sharesdk/framework/ShareSDK;->a:Lcn/sharesdk/framework/p;
a=0;// 
a=0;//     #v0=(Reference,Lcn/sharesdk/framework/p;);
a=0;//     invoke-virtual {v0, p0}, Lcn/sharesdk/framework/p;->a(Ljava/util/HashMap;)Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method static b(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     invoke-static {}, Lcn/sharesdk/framework/ShareSDK;->c()V
a=0;// 
a=0;//     sget-object v0, Lcn/sharesdk/framework/ShareSDK;->a:Lcn/sharesdk/framework/p;
a=0;// 
a=0;//     #v0=(Reference,Lcn/sharesdk/framework/p;);
a=0;//     invoke-virtual {v0, p0, p1}, Lcn/sharesdk/framework/p;->b(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method static b()Z
a=0;//     .locals 1
a=0;// 
a=0;//     invoke-static {}, Lcn/sharesdk/framework/ShareSDK;->c()V
a=0;// 
a=0;//     sget-object v0, Lcn/sharesdk/framework/ShareSDK;->a:Lcn/sharesdk/framework/p;
a=0;// 
a=0;//     #v0=(Reference,Lcn/sharesdk/framework/p;);
a=0;//     invoke-virtual {v0}, Lcn/sharesdk/framework/p;->h()Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method static b(Ljava/util/HashMap;)Z
a=0;//     .locals 1
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "(",
a=0;//             "Ljava/util/HashMap",
a=0;//             "<",
a=0;//             "Ljava/lang/String;",
a=0;//             "Ljava/lang/Object;",
a=0;//             ">;)Z"
a=0;//         }
a=0;//     .end annotation
a=0;// 
a=0;//     invoke-static {}, Lcn/sharesdk/framework/ShareSDK;->c()V
a=0;// 
a=0;//     sget-object v0, Lcn/sharesdk/framework/ShareSDK;->a:Lcn/sharesdk/framework/p;
a=0;// 
a=0;//     #v0=(Reference,Lcn/sharesdk/framework/p;);
a=0;//     invoke-virtual {v0, p0}, Lcn/sharesdk/framework/p;->b(Ljava/util/HashMap;)Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method private static c()V
a=0;//     .locals 2
a=0;// 
a=0;//     sget-object v0, Lcn/sharesdk/framework/ShareSDK;->a:Lcn/sharesdk/framework/p;
a=0;// 
a=0;//     #v0=(Reference,Lcn/sharesdk/framework/p;);
a=0;//     if-nez v0, :cond_0
a=0;// 
a=0;//     const-string v0, "Please call ShareSDK.initSDK(Context) before any action."
a=0;// 
a=0;//     new-instance v1, Ljava/lang/NullPointerException;
a=0;// 
a=0;//     #v1=(UninitRef,Ljava/lang/NullPointerException;);
a=0;//     invoke-direct {v1, v0}, Ljava/lang/NullPointerException;-><init>(Ljava/lang/String;)V
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/NullPointerException;);
a=0;//     throw v1
a=0;// 
a=0;//     :cond_0
a=0;//     #v1=(Uninit);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static closeDebug()V
a=0;//     .locals 1
a=0;// 
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     sput-boolean v0, Lcn/sharesdk/framework/ShareSDK;->b:Z
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static getPlatform(Landroid/content/Context;Ljava/lang/String;)Lcn/sharesdk/framework/Platform;
a=0;//     .locals 1
a=0;// 
a=0;//     invoke-static {}, Lcn/sharesdk/framework/ShareSDK;->c()V
a=0;// 
a=0;//     sget-object v0, Lcn/sharesdk/framework/ShareSDK;->a:Lcn/sharesdk/framework/p;
a=0;// 
a=0;//     #v0=(Reference,Lcn/sharesdk/framework/p;);
a=0;//     invoke-virtual {v0, p1}, Lcn/sharesdk/framework/p;->b(Ljava/lang/String;)Lcn/sharesdk/framework/Platform;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public static getPlatform(Ljava/lang/String;)Lcn/sharesdk/framework/Platform;
a=0;//     .locals 1
a=0;// 
a=0;//     invoke-static {}, Lcn/sharesdk/framework/ShareSDK;->c()V
a=0;// 
a=0;//     sget-object v0, Lcn/sharesdk/framework/ShareSDK;->a:Lcn/sharesdk/framework/p;
a=0;// 
a=0;//     #v0=(Reference,Lcn/sharesdk/framework/p;);
a=0;//     invoke-virtual {v0, p0}, Lcn/sharesdk/framework/p;->b(Ljava/lang/String;)Lcn/sharesdk/framework/Platform;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public static declared-synchronized getPlatformList()[Lcn/sharesdk/framework/Platform;
a=0;//     .locals 2
a=0;// 
a=0;//     const-class v1, Lcn/sharesdk/framework/ShareSDK;
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/Class;);
a=0;//     monitor-enter v1
a=0;// 
a=0;//     :try_start_0
a=0;//     invoke-static {}, Lcn/sharesdk/framework/ShareSDK;->c()V
a=0;// 
a=0;//     sget-object v0, Lcn/sharesdk/framework/ShareSDK;->a:Lcn/sharesdk/framework/p;
a=0;// 
a=0;//     #v0=(Reference,Lcn/sharesdk/framework/p;);
a=0;//     invoke-virtual {v0}, Lcn/sharesdk/framework/p;->c()[Lcn/sharesdk/framework/Platform;
a=0;//     :try_end_0
a=0;//     .catchall {:try_start_0 .. :try_end_0} :catchall_0
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     monitor-exit v1
a=0;// 
a=0;//     return-object v0
a=0;// 
a=0;//     :catchall_0
a=0;//     #v0=(Conflicted);
a=0;//     move-exception v0
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/Throwable;);
a=0;//     monitor-exit v1
a=0;// 
a=0;//     throw v0
a=0;// .end method
a=0;// 
a=0;// .method public static declared-synchronized getPlatformList(Landroid/content/Context;)[Lcn/sharesdk/framework/Platform;
a=0;//     .locals 2
a=0;// 
a=0;//     const-class v0, Lcn/sharesdk/framework/ShareSDK;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/Class;);
a=0;//     monitor-enter v0
a=0;// 
a=0;//     :try_start_0
a=0;//     invoke-static {}, Lcn/sharesdk/framework/ShareSDK;->getPlatformList()[Lcn/sharesdk/framework/Platform;
a=0;//     :try_end_0
a=0;//     .catchall {:try_start_0 .. :try_end_0} :catchall_0
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     #v1=(Reference,[Lcn/sharesdk/framework/Platform;);
a=0;//     monitor-exit v0
a=0;// 
a=0;//     return-object v1
a=0;// 
a=0;//     :catchall_0
a=0;//     #v1=(Uninit);
a=0;//     move-exception v1
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/Throwable;);
a=0;//     monitor-exit v0
a=0;// 
a=0;//     throw v1
a=0;// .end method
a=0;// 
a=0;// .method public static getSDKVersionCode()I
a=0;//     .locals 1
a=0;// 
a=0;//     invoke-static {}, Lcn/sharesdk/framework/ShareSDK;->c()V
a=0;// 
a=0;//     sget-object v0, Lcn/sharesdk/framework/ShareSDK;->a:Lcn/sharesdk/framework/p;
a=0;// 
a=0;//     #v0=(Reference,Lcn/sharesdk/framework/p;);
a=0;//     invoke-virtual {v0}, Lcn/sharesdk/framework/p;->e()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static getSDKVersionName()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     invoke-static {}, Lcn/sharesdk/framework/ShareSDK;->c()V
a=0;// 
a=0;//     sget-object v0, Lcn/sharesdk/framework/ShareSDK;->a:Lcn/sharesdk/framework/p;
a=0;// 
a=0;//     #v0=(Reference,Lcn/sharesdk/framework/p;);
a=0;//     invoke-virtual {v0}, Lcn/sharesdk/framework/p;->d()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public static getService(Ljava/lang/Class;)Lcn/sharesdk/framework/Service;
a=0;//     .locals 1
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "<T:",
a=0;//             "Lcn/sharesdk/framework/Service;",
a=0;//             ">(",
a=0;//             "Ljava/lang/Class",
a=0;//             "<TT;>;)TT;"
a=0;//         }
a=0;//     .end annotation
a=0;// 
a=0;//     invoke-static {}, Lcn/sharesdk/framework/ShareSDK;->c()V
a=0;// 
a=0;//     sget-object v0, Lcn/sharesdk/framework/ShareSDK;->a:Lcn/sharesdk/framework/p;
a=0;// 
a=0;//     #v0=(Reference,Lcn/sharesdk/framework/p;);
a=0;//     invoke-virtual {v0, p0}, Lcn/sharesdk/framework/p;->c(Ljava/lang/Class;)Lcn/sharesdk/framework/Service;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public static initSDK(Landroid/content/Context;)V
a=0;//     .locals 2
a=0;// 
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     const/4 v1, 0x1
a=0;// 
a=0;//     #v1=(One);
a=0;//     invoke-static {p0, v0, v1}, Lcn/sharesdk/framework/ShareSDK;->initSDK(Landroid/content/Context;Ljava/lang/String;Z)V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static initSDK(Landroid/content/Context;Ljava/lang/String;)V
a=0;//     .locals 1
a=0;// 
a=0;//     const/4 v0, 0x1
a=0;// 
a=0;//     #v0=(One);
a=0;//     invoke-static {p0, p1, v0}, Lcn/sharesdk/framework/ShareSDK;->initSDK(Landroid/content/Context;Ljava/lang/String;Z)V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static initSDK(Landroid/content/Context;Ljava/lang/String;Z)V
a=0;//     .locals 1
a=0;// 
a=0;//     sget-object v0, Lcn/sharesdk/framework/ShareSDK;->a:Lcn/sharesdk/framework/p;
a=0;// 
a=0;//     #v0=(Reference,Lcn/sharesdk/framework/p;);
a=0;//     if-nez v0, :cond_0
a=0;// 
a=0;//     new-instance v0, Lcn/sharesdk/framework/p;
a=0;// 
a=0;//     #v0=(UninitRef,Lcn/sharesdk/framework/p;);
a=0;//     invoke-direct {v0, p0}, Lcn/sharesdk/framework/p;-><init>(Landroid/content/Context;)V
a=0;// 
a=0;//     #v0=(Reference,Lcn/sharesdk/framework/p;);
a=0;//     invoke-virtual {v0, p1}, Lcn/sharesdk/framework/p;->a(Ljava/lang/String;)V
a=0;// 
a=0;//     invoke-virtual {v0, p2}, Lcn/sharesdk/framework/p;->a(Z)V
a=0;// 
a=0;//     invoke-virtual {v0}, Lcn/sharesdk/framework/p;->a()V
a=0;// 
a=0;//     sput-object v0, Lcn/sharesdk/framework/ShareSDK;->a:Lcn/sharesdk/framework/p;
a=0;// 
a=0;//     :cond_0
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static initSDK(Landroid/content/Context;Z)V
a=0;//     .locals 1
a=0;// 
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     invoke-static {p0, v0, p1}, Lcn/sharesdk/framework/ShareSDK;->initSDK(Landroid/content/Context;Ljava/lang/String;Z)V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static isDebug()Z
a=0;//     .locals 1
a=0;// 
a=0;//     sget-boolean v0, Lcn/sharesdk/framework/ShareSDK;->b:Z
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static isRemoveCookieOnAuthorize()Z
a=0;//     .locals 1
a=0;// 
a=0;//     invoke-static {}, Lcn/sharesdk/framework/ShareSDK;->c()V
a=0;// 
a=0;//     sget-object v0, Lcn/sharesdk/framework/ShareSDK;->a:Lcn/sharesdk/framework/p;
a=0;// 
a=0;//     #v0=(Reference,Lcn/sharesdk/framework/p;);
a=0;//     invoke-virtual {v0}, Lcn/sharesdk/framework/p;->f()Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static logApiEvent(Ljava/lang/String;I)V
a=0;//     .locals 1
a=0;// 
a=0;//     invoke-static {}, Lcn/sharesdk/framework/ShareSDK;->c()V
a=0;// 
a=0;//     sget-object v0, Lcn/sharesdk/framework/ShareSDK;->a:Lcn/sharesdk/framework/p;
a=0;// 
a=0;//     #v0=(Reference,Lcn/sharesdk/framework/p;);
a=0;//     invoke-virtual {v0, p0, p1}, Lcn/sharesdk/framework/p;->a(Ljava/lang/String;I)V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static logDemoEvent(ILcn/sharesdk/framework/Platform;)V
a=0;//     .locals 1
a=0;// 
a=0;//     invoke-static {}, Lcn/sharesdk/framework/ShareSDK;->c()V
a=0;// 
a=0;//     sget-object v0, Lcn/sharesdk/framework/ShareSDK;->a:Lcn/sharesdk/framework/p;
a=0;// 
a=0;//     #v0=(Reference,Lcn/sharesdk/framework/p;);
a=0;//     invoke-virtual {v0, p0, p1}, Lcn/sharesdk/framework/p;->a(ILcn/sharesdk/framework/Platform;)V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static platformIdToName(I)Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     invoke-static {}, Lcn/sharesdk/framework/ShareSDK;->c()V
a=0;// 
a=0;//     sget-object v0, Lcn/sharesdk/framework/ShareSDK;->a:Lcn/sharesdk/framework/p;
a=0;// 
a=0;//     #v0=(Reference,Lcn/sharesdk/framework/p;);
a=0;//     invoke-virtual {v0, p0}, Lcn/sharesdk/framework/p;->c(I)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public static platformNameToId(Ljava/lang/String;)I
a=0;//     .locals 1
a=0;// 
a=0;//     invoke-static {}, Lcn/sharesdk/framework/ShareSDK;->c()V
a=0;// 
a=0;//     sget-object v0, Lcn/sharesdk/framework/ShareSDK;->a:Lcn/sharesdk/framework/p;
a=0;// 
a=0;//     #v0=(Reference,Lcn/sharesdk/framework/p;);
a=0;//     invoke-virtual {v0, p0}, Lcn/sharesdk/framework/p;->c(Ljava/lang/String;)I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static registerPlatform(Ljava/lang/Class;)V
a=0;//     .locals 1
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "(",
a=0;//             "Ljava/lang/Class",
a=0;//             "<+",
a=0;//             "Lcn/sharesdk/framework/CustomPlatform;",
a=0;//             ">;)V"
a=0;//         }
a=0;//     .end annotation
a=0;// 
a=0;//     invoke-static {}, Lcn/sharesdk/framework/ShareSDK;->c()V
a=0;// 
a=0;//     sget-object v0, Lcn/sharesdk/framework/ShareSDK;->a:Lcn/sharesdk/framework/p;
a=0;// 
a=0;//     #v0=(Reference,Lcn/sharesdk/framework/p;);
a=0;//     invoke-virtual {v0, p0}, Lcn/sharesdk/framework/p;->d(Ljava/lang/Class;)V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static registerService(Ljava/lang/Class;)V
a=0;//     .locals 1
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "(",
a=0;//             "Ljava/lang/Class",
a=0;//             "<+",
a=0;//             "Lcn/sharesdk/framework/Service;",
a=0;//             ">;)V"
a=0;//         }
a=0;//     .end annotation
a=0;// 
a=0;//     invoke-static {}, Lcn/sharesdk/framework/ShareSDK;->c()V
a=0;// 
a=0;//     sget-object v0, Lcn/sharesdk/framework/ShareSDK;->a:Lcn/sharesdk/framework/p;
a=0;// 
a=0;//     #v0=(Reference,Lcn/sharesdk/framework/p;);
a=0;//     invoke-virtual {v0, p0}, Lcn/sharesdk/framework/p;->a(Ljava/lang/Class;)V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static removeCookieOnAuthorize(Z)V
a=0;//     .locals 1
a=0;// 
a=0;//     invoke-static {}, Lcn/sharesdk/framework/ShareSDK;->c()V
a=0;// 
a=0;//     sget-object v0, Lcn/sharesdk/framework/ShareSDK;->a:Lcn/sharesdk/framework/p;
a=0;// 
a=0;//     #v0=(Reference,Lcn/sharesdk/framework/p;);
a=0;//     invoke-virtual {v0, p0}, Lcn/sharesdk/framework/p;->b(Z)V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static setConnTimeout(I)V
a=0;//     .locals 1
a=0;// 
a=0;//     invoke-static {}, Lcn/sharesdk/framework/ShareSDK;->c()V
a=0;// 
a=0;//     sget-object v0, Lcn/sharesdk/framework/ShareSDK;->a:Lcn/sharesdk/framework/p;
a=0;// 
a=0;//     #v0=(Reference,Lcn/sharesdk/framework/p;);
a=0;//     invoke-virtual {v0, p0}, Lcn/sharesdk/framework/p;->a(I)V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static setPlatformDevInfo(Ljava/lang/String;Ljava/util/HashMap;)V
a=0;//     .locals 1
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "(",
a=0;//             "Ljava/lang/String;",
a=0;//             "Ljava/util/HashMap",
a=0;//             "<",
a=0;//             "Ljava/lang/String;",
a=0;//             "Ljava/lang/Object;",
a=0;//             ">;)V"
a=0;//         }
a=0;//     .end annotation
a=0;// 
a=0;//     invoke-static {}, Lcn/sharesdk/framework/ShareSDK;->c()V
a=0;// 
a=0;//     sget-object v0, Lcn/sharesdk/framework/ShareSDK;->a:Lcn/sharesdk/framework/p;
a=0;// 
a=0;//     #v0=(Reference,Lcn/sharesdk/framework/p;);
a=0;//     invoke-virtual {v0, p0, p1}, Lcn/sharesdk/framework/p;->a(Ljava/lang/String;Ljava/util/HashMap;)V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static setReadTimeout(I)V
a=0;//     .locals 1
a=0;// 
a=0;//     invoke-static {}, Lcn/sharesdk/framework/ShareSDK;->c()V
a=0;// 
a=0;//     sget-object v0, Lcn/sharesdk/framework/ShareSDK;->a:Lcn/sharesdk/framework/p;
a=0;// 
a=0;//     #v0=(Reference,Lcn/sharesdk/framework/p;);
a=0;//     invoke-virtual {v0, p0}, Lcn/sharesdk/framework/p;->b(I)V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static stopSDK()V
a=0;//     .locals 0
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static stopSDK(Landroid/content/Context;)V
a=0;//     .locals 0
a=0;// 
a=0;//     invoke-static {}, Lcn/sharesdk/framework/ShareSDK;->stopSDK()V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static unregisterPlatform(Ljava/lang/Class;)V
a=0;//     .locals 1
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "(",
a=0;//             "Ljava/lang/Class",
a=0;//             "<+",
a=0;//             "Lcn/sharesdk/framework/CustomPlatform;",
a=0;//             ">;)V"
a=0;//         }
a=0;//     .end annotation
a=0;// 
a=0;//     invoke-static {}, Lcn/sharesdk/framework/ShareSDK;->c()V
a=0;// 
a=0;//     sget-object v0, Lcn/sharesdk/framework/ShareSDK;->a:Lcn/sharesdk/framework/p;
a=0;// 
a=0;//     #v0=(Reference,Lcn/sharesdk/framework/p;);
a=0;//     invoke-virtual {v0, p0}, Lcn/sharesdk/framework/p;->e(Ljava/lang/Class;)V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static unregisterService(Ljava/lang/Class;)V
a=0;//     .locals 1
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "(",
a=0;//             "Ljava/lang/Class",
a=0;//             "<+",
a=0;//             "Lcn/sharesdk/framework/Service;",
a=0;//             ">;)V"
a=0;//         }
a=0;//     .end annotation
a=0;// 
a=0;//     invoke-static {}, Lcn/sharesdk/framework/ShareSDK;->c()V
a=0;// 
a=0;//     sget-object v0, Lcn/sharesdk/framework/ShareSDK;->a:Lcn/sharesdk/framework/p;
a=0;// 
a=0;//     #v0=(Reference,Lcn/sharesdk/framework/p;);
a=0;//     invoke-virtual {v0, p0}, Lcn/sharesdk/framework/p;->b(Ljava/lang/Class;)V
a=0;// 
a=0;//     return-void
a=0;// .end method
}}
