package net.slidingmenu.tools.b.a.i.a.b; class c { void a() { int a;
a=0;// .class public interface abstract Lnet/slidingmenu/tools/b/a/i/a/b/c;
a=0;// .super Ljava/lang/Object;
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public abstract c()Z
a=0;// .end method
a=0;// 
a=0;// .method public abstract canGoBack()Z
a=0;// .end method
a=0;// 
a=0;// .method public abstract canGoForward()Z
a=0;// .end method
a=0;// 
a=0;// .method public abstract clearHistory()V
a=0;// .end method
a=0;// 
a=0;// .method public abstract d()Z
a=0;// .end method
a=0;// 
a=0;// .method public abstract e()V
a=0;// .end method
a=0;// 
a=0;// .method public abstract g()V
a=0;// .end method
a=0;// 
a=0;// .method public abstract getCurrentView()Landroid/view/View;
a=0;// .end method
a=0;// 
a=0;// .method public abstract h()V
a=0;// .end method
a=0;// 
a=0;// .method public abstract loadUrl(Ljava/lang/String;)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract postUrl(Ljava/lang/String;[B)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract reload()V
a=0;// .end method
}}
