package com.android.volley.toolbox; class ImageLoader$ImageContainer { void a() { int a;
a=0;// .class public Lcom/android/volley/toolbox/ImageLoader$ImageContainer;
a=0;// .super Ljava/lang/Object;
a=0;// .source "ImageLoader.java"
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation system Ldalvik/annotation/EnclosingClass;
a=0;//     value = Lcom/android/volley/toolbox/ImageLoader;
a=0;// .end annotation
a=0;// 
a=0;// .annotation system Ldalvik/annotation/InnerClass;
a=0;//     accessFlags = 0x1
a=0;//     name = "ImageContainer"
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field private mBitmap:Landroid/graphics/Bitmap;
a=0;// 
a=0;// .field private final mCacheKey:Ljava/lang/String;
a=0;// 
a=0;// .field private final mListener:Lcom/android/volley/toolbox/ImageLoader$ImageListener;
a=0;// 
a=0;// .field private final mRequestUrl:Ljava/lang/String;
a=0;// 
a=0;// .field final synthetic this$0:Lcom/android/volley/toolbox/ImageLoader;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>(Lcom/android/volley/toolbox/ImageLoader;Landroid/graphics/Bitmap;Ljava/lang/String;Ljava/lang/String;Lcom/android/volley/toolbox/ImageLoader$ImageListener;)V
a=0;//     .locals 0
a=0;//     .param p2, "bitmap"    # Landroid/graphics/Bitmap;
a=0;//     .param p3, "requestUrl"    # Ljava/lang/String;
a=0;//     .param p4, "cacheKey"    # Ljava/lang/String;
a=0;//     .param p5, "listener"    # Lcom/android/volley/toolbox/ImageLoader$ImageListener;
a=0;// 
a=0;//     .prologue
a=0;//     .line 338
a=0;//     iput-object p1, p0, Lcom/android/volley/toolbox/ImageLoader$ImageContainer;->this$0:Lcom/android/volley/toolbox/ImageLoader;
a=0;// 
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     .line 339
a=0;//     #p0=(Reference,Lcom/android/volley/toolbox/ImageLoader$ImageContainer;);
a=0;//     iput-object p2, p0, Lcom/android/volley/toolbox/ImageLoader$ImageContainer;->mBitmap:Landroid/graphics/Bitmap;
a=0;// 
a=0;//     .line 340
a=0;//     iput-object p3, p0, Lcom/android/volley/toolbox/ImageLoader$ImageContainer;->mRequestUrl:Ljava/lang/String;
a=0;// 
a=0;//     .line 341
a=0;//     iput-object p4, p0, Lcom/android/volley/toolbox/ImageLoader$ImageContainer;->mCacheKey:Ljava/lang/String;
a=0;// 
a=0;//     .line 342
a=0;//     iput-object p5, p0, Lcom/android/volley/toolbox/ImageLoader$ImageContainer;->mListener:Lcom/android/volley/toolbox/ImageLoader$ImageListener;
a=0;// 
a=0;//     .line 343
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method static synthetic access$0(Lcom/android/volley/toolbox/ImageLoader$ImageContainer;)Lcom/android/volley/toolbox/ImageLoader$ImageListener;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 320
a=0;//     iget-object v0, p0, Lcom/android/volley/toolbox/ImageLoader$ImageContainer;->mListener:Lcom/android/volley/toolbox/ImageLoader$ImageListener;
a=0;// 
a=0;//     #v0=(Reference,Lcom/android/volley/toolbox/ImageLoader$ImageListener;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method static synthetic access$1(Lcom/android/volley/toolbox/ImageLoader$ImageContainer;Landroid/graphics/Bitmap;)V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 318
a=0;//     iput-object p1, p0, Lcom/android/volley/toolbox/ImageLoader$ImageContainer;->mBitmap:Landroid/graphics/Bitmap;
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public cancelRequest()V
a=0;//     .locals 4
a=0;// 
a=0;//     .prologue
a=0;//     .line 349
a=0;//     iget-object v2, p0, Lcom/android/volley/toolbox/ImageLoader$ImageContainer;->mListener:Lcom/android/volley/toolbox/ImageLoader$ImageListener;
a=0;// 
a=0;//     #v2=(Reference,Lcom/android/volley/toolbox/ImageLoader$ImageListener;);
a=0;//     if-nez v2, :cond_1
a=0;// 
a=0;//     .line 369
a=0;//     :cond_0
a=0;//     :goto_0
a=0;//     #v0=(Conflicted);v1=(Conflicted);v2=(Conflicted);v3=(Conflicted);
a=0;//     return-void
a=0;// 
a=0;//     .line 353
a=0;//     :cond_1
a=0;//     #v0=(Uninit);v1=(Uninit);v2=(Reference,Lcom/android/volley/toolbox/ImageLoader$ImageListener;);v3=(Uninit);
a=0;//     iget-object v2, p0, Lcom/android/volley/toolbox/ImageLoader$ImageContainer;->this$0:Lcom/android/volley/toolbox/ImageLoader;
a=0;// 
a=0;//     invoke-static {v2}, Lcom/android/volley/toolbox/ImageLoader;->access$0(Lcom/android/volley/toolbox/ImageLoader;)Ljava/util/HashMap;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     iget-object v3, p0, Lcom/android/volley/toolbox/ImageLoader$ImageContainer;->mCacheKey:Ljava/lang/String;
a=0;// 
a=0;//     #v3=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v2, v3}, Ljava/util/HashMap;->get(Ljava/lang/Object;)Ljava/lang/Object;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/Object;);
a=0;//     check-cast v1, Lcom/android/volley/toolbox/ImageLoader$BatchedImageRequest;
a=0;// 
a=0;//     .line 354
a=0;//     .local v1, "request":Lcom/android/volley/toolbox/ImageLoader$BatchedImageRequest;
a=0;//     if-eqz v1, :cond_2
a=0;// 
a=0;//     .line 355
a=0;//     invoke-virtual {v1, p0}, Lcom/android/volley/toolbox/ImageLoader$BatchedImageRequest;->removeContainerAndCancelIfNecessary(Lcom/android/volley/toolbox/ImageLoader$ImageContainer;)Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     .line 356
a=0;//     .local v0, "canceled":Z
a=0;//     #v0=(Boolean);
a=0;//     if-eqz v0, :cond_0
a=0;// 
a=0;//     .line 357
a=0;//     iget-object v2, p0, Lcom/android/volley/toolbox/ImageLoader$ImageContainer;->this$0:Lcom/android/volley/toolbox/ImageLoader;
a=0;// 
a=0;//     invoke-static {v2}, Lcom/android/volley/toolbox/ImageLoader;->access$0(Lcom/android/volley/toolbox/ImageLoader;)Ljava/util/HashMap;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     iget-object v3, p0, Lcom/android/volley/toolbox/ImageLoader$ImageContainer;->mCacheKey:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v2, v3}, Ljava/util/HashMap;->remove(Ljava/lang/Object;)Ljava/lang/Object;
a=0;// 
a=0;//     goto :goto_0
a=0;// 
a=0;//     .line 361
a=0;//     .end local v0    # "canceled":Z
a=0;//     :cond_2
a=0;//     #v0=(Uninit);
a=0;//     iget-object v2, p0, Lcom/android/volley/toolbox/ImageLoader$ImageContainer;->this$0:Lcom/android/volley/toolbox/ImageLoader;
a=0;// 
a=0;//     invoke-static {v2}, Lcom/android/volley/toolbox/ImageLoader;->access$1(Lcom/android/volley/toolbox/ImageLoader;)Ljava/util/HashMap;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     iget-object v3, p0, Lcom/android/volley/toolbox/ImageLoader$ImageContainer;->mCacheKey:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v2, v3}, Ljava/util/HashMap;->get(Ljava/lang/Object;)Ljava/lang/Object;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     .end local v1    # "request":Lcom/android/volley/toolbox/ImageLoader$BatchedImageRequest;
a=0;//     check-cast v1, Lcom/android/volley/toolbox/ImageLoader$BatchedImageRequest;
a=0;// 
a=0;//     .line 362
a=0;//     .restart local v1    # "request":Lcom/android/volley/toolbox/ImageLoader$BatchedImageRequest;
a=0;//     if-eqz v1, :cond_0
a=0;// 
a=0;//     .line 363
a=0;//     invoke-virtual {v1, p0}, Lcom/android/volley/toolbox/ImageLoader$BatchedImageRequest;->removeContainerAndCancelIfNecessary(Lcom/android/volley/toolbox/ImageLoader$ImageContainer;)Z
a=0;// 
a=0;//     .line 364
a=0;//     invoke-static {v1}, Lcom/android/volley/toolbox/ImageLoader$BatchedImageRequest;->access$0(Lcom/android/volley/toolbox/ImageLoader$BatchedImageRequest;)Ljava/util/LinkedList;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-virtual {v2}, Ljava/util/LinkedList;->size()I
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     if-nez v2, :cond_0
a=0;// 
a=0;//     .line 365
a=0;//     iget-object v2, p0, Lcom/android/volley/toolbox/ImageLoader$ImageContainer;->this$0:Lcom/android/volley/toolbox/ImageLoader;
a=0;// 
a=0;//     #v2=(Reference,Lcom/android/volley/toolbox/ImageLoader;);
a=0;//     invoke-static {v2}, Lcom/android/volley/toolbox/ImageLoader;->access$1(Lcom/android/volley/toolbox/ImageLoader;)Ljava/util/HashMap;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     iget-object v3, p0, Lcom/android/volley/toolbox/ImageLoader$ImageContainer;->mCacheKey:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v2, v3}, Ljava/util/HashMap;->remove(Ljava/lang/Object;)Ljava/lang/Object;
a=0;// 
a=0;//     goto :goto_0
a=0;// .end method
a=0;// 
a=0;// .method public getBitmap()Landroid/graphics/Bitmap;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 375
a=0;//     iget-object v0, p0, Lcom/android/volley/toolbox/ImageLoader$ImageContainer;->mBitmap:Landroid/graphics/Bitmap;
a=0;// 
a=0;//     #v0=(Reference,Landroid/graphics/Bitmap;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getRequestUrl()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 382
a=0;//     iget-object v0, p0, Lcom/android/volley/toolbox/ImageLoader$ImageContainer;->mRequestUrl:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
}}
