package com.android.volley.toolbox; class NoCache { void a() { int a;
a=0;// .class public Lcom/android/volley/toolbox/NoCache;
a=0;// .super Ljava/lang/Object;
a=0;// .source "NoCache.java"
a=0;// 
a=0;// # interfaces
a=0;// .implements Lcom/android/volley/Cache;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 24
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcom/android/volley/toolbox/NoCache;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public clear()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 27
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public get(Ljava/lang/String;)Lcom/android/volley/Cache$Entry;
a=0;//     .locals 1
a=0;//     .param p1, "key"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 31
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public initialize()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 48
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public invalidate(Ljava/lang/String;Z)V
a=0;//     .locals 0
a=0;//     .param p1, "key"    # Ljava/lang/String;
a=0;//     .param p2, "fullExpire"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 40
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public put(Ljava/lang/String;Lcom/android/volley/Cache$Entry;)V
a=0;//     .locals 0
a=0;//     .param p1, "key"    # Ljava/lang/String;
a=0;//     .param p2, "entry"    # Lcom/android/volley/Cache$Entry;
a=0;// 
a=0;//     .prologue
a=0;//     .line 36
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public remove(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "key"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 44
a=0;//     return-void
a=0;// .end method
}}
