package com.j256.ormlite.stmt.query; class ManyClause { void a() { int a;
a=0;// .class public Lcom/j256/ormlite/stmt/query/ManyClause;
a=0;// .super Ljava/lang/Object;
a=0;// .source "ManyClause.java"
a=0;// 
a=0;// # interfaces
a=0;// .implements Lcom/j256/ormlite/stmt/query/Clause;
a=0;// .implements Lcom/j256/ormlite/stmt/query/NeedsFutureClause;
a=0;// 
a=0;// 
a=0;// # static fields
a=0;// .field public static final AND_OPERATION:Ljava/lang/String; = "AND"
a=0;// 
a=0;// .field public static final OR_OPERATION:Ljava/lang/String; = "OR"
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field private final first:Lcom/j256/ormlite/stmt/query/Clause;
a=0;// 
a=0;// .field private final operation:Ljava/lang/String;
a=0;// 
a=0;// .field private final others:[Lcom/j256/ormlite/stmt/query/Clause;
a=0;// 
a=0;// .field private second:Lcom/j256/ormlite/stmt/query/Clause;
a=0;// 
a=0;// .field private final startOthersAt:I
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>(Lcom/j256/ormlite/stmt/query/Clause;Lcom/j256/ormlite/stmt/query/Clause;[Lcom/j256/ormlite/stmt/query/Clause;Ljava/lang/String;)V
a=0;//     .locals 1
a=0;//     .param p1, "first"    # Lcom/j256/ormlite/stmt/query/Clause;
a=0;//     .param p2, "second"    # Lcom/j256/ormlite/stmt/query/Clause;
a=0;//     .param p3, "others"    # [Lcom/j256/ormlite/stmt/query/Clause;
a=0;//     .param p4, "operation"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 34
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     .line 35
a=0;//     #p0=(Reference,Lcom/j256/ormlite/stmt/query/ManyClause;);
a=0;//     iput-object p1, p0, Lcom/j256/ormlite/stmt/query/ManyClause;->first:Lcom/j256/ormlite/stmt/query/Clause;
a=0;// 
a=0;//     .line 36
a=0;//     iput-object p2, p0, Lcom/j256/ormlite/stmt/query/ManyClause;->second:Lcom/j256/ormlite/stmt/query/Clause;
a=0;// 
a=0;//     .line 37
a=0;//     iput-object p3, p0, Lcom/j256/ormlite/stmt/query/ManyClause;->others:[Lcom/j256/ormlite/stmt/query/Clause;
a=0;// 
a=0;//     .line 38
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     iput v0, p0, Lcom/j256/ormlite/stmt/query/ManyClause;->startOthersAt:I
a=0;// 
a=0;//     .line 39
a=0;//     iput-object p4, p0, Lcom/j256/ormlite/stmt/query/ManyClause;->operation:Ljava/lang/String;
a=0;// 
a=0;//     .line 40
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public constructor <init>(Lcom/j256/ormlite/stmt/query/Clause;Ljava/lang/String;)V
a=0;//     .locals 1
a=0;//     .param p1, "first"    # Lcom/j256/ormlite/stmt/query/Clause;
a=0;//     .param p2, "operation"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     .line 25
a=0;//     #v0=(Null);
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     .line 26
a=0;//     #p0=(Reference,Lcom/j256/ormlite/stmt/query/ManyClause;);
a=0;//     iput-object p1, p0, Lcom/j256/ormlite/stmt/query/ManyClause;->first:Lcom/j256/ormlite/stmt/query/Clause;
a=0;// 
a=0;//     .line 28
a=0;//     iput-object v0, p0, Lcom/j256/ormlite/stmt/query/ManyClause;->second:Lcom/j256/ormlite/stmt/query/Clause;
a=0;// 
a=0;//     .line 29
a=0;//     iput-object v0, p0, Lcom/j256/ormlite/stmt/query/ManyClause;->others:[Lcom/j256/ormlite/stmt/query/Clause;
a=0;// 
a=0;//     .line 30
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     iput v0, p0, Lcom/j256/ormlite/stmt/query/ManyClause;->startOthersAt:I
a=0;// 
a=0;//     .line 31
a=0;//     iput-object p2, p0, Lcom/j256/ormlite/stmt/query/ManyClause;->operation:Ljava/lang/String;
a=0;// 
a=0;//     .line 32
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public constructor <init>([Lcom/j256/ormlite/stmt/query/Clause;Ljava/lang/String;)V
a=0;//     .locals 2
a=0;//     .param p1, "others"    # [Lcom/j256/ormlite/stmt/query/Clause;
a=0;//     .param p2, "operation"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     const/4 v1, 0x2
a=0;// 
a=0;//     .line 42
a=0;//     #v1=(PosByte);
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     .line 43
a=0;//     #p0=(Reference,Lcom/j256/ormlite/stmt/query/ManyClause;);
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     aget-object v0, p1, v0
a=0;// 
a=0;//     iput-object v0, p0, Lcom/j256/ormlite/stmt/query/ManyClause;->first:Lcom/j256/ormlite/stmt/query/Clause;
a=0;// 
a=0;//     .line 44
a=0;//     array-length v0, p1
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     if-ge v0, v1, :cond_0
a=0;// 
a=0;//     .line 45
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     iput-object v0, p0, Lcom/j256/ormlite/stmt/query/ManyClause;->second:Lcom/j256/ormlite/stmt/query/Clause;
a=0;// 
a=0;//     .line 46
a=0;//     array-length v0, p1
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     iput v0, p0, Lcom/j256/ormlite/stmt/query/ManyClause;->startOthersAt:I
a=0;// 
a=0;//     .line 51
a=0;//     :goto_0
a=0;//     iput-object p1, p0, Lcom/j256/ormlite/stmt/query/ManyClause;->others:[Lcom/j256/ormlite/stmt/query/Clause;
a=0;// 
a=0;//     .line 52
a=0;//     iput-object p2, p0, Lcom/j256/ormlite/stmt/query/ManyClause;->operation:Ljava/lang/String;
a=0;// 
a=0;//     .line 53
a=0;//     return-void
a=0;// 
a=0;//     .line 48
a=0;//     :cond_0
a=0;//     const/4 v0, 0x1
a=0;// 
a=0;//     #v0=(One);
a=0;//     aget-object v0, p1, v0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     iput-object v0, p0, Lcom/j256/ormlite/stmt/query/ManyClause;->second:Lcom/j256/ormlite/stmt/query/Clause;
a=0;// 
a=0;//     .line 49
a=0;//     iput v1, p0, Lcom/j256/ormlite/stmt/query/ManyClause;->startOthersAt:I
a=0;// 
a=0;//     goto :goto_0
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public appendSql(Lcom/j256/ormlite/db/DatabaseType;Ljava/lang/String;Ljava/lang/StringBuilder;Ljava/util/List;)V
a=0;//     .locals 3
a=0;//     .param p1, "databaseType"    # Lcom/j256/ormlite/db/DatabaseType;
a=0;//     .param p2, "tableName"    # Ljava/lang/String;
a=0;//     .param p3, "sb"    # Ljava/lang/StringBuilder;
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "(",
a=0;//             "Lcom/j256/ormlite/db/DatabaseType;",
a=0;//             "Ljava/lang/String;",
a=0;//             "Ljava/lang/StringBuilder;",
a=0;//             "Ljava/util/List",
a=0;//             "<",
a=0;//             "Lcom/j256/ormlite/stmt/ArgumentHolder;",
a=0;//             ">;)V"
a=0;//         }
a=0;//     .end annotation
a=0;// 
a=0;//     .annotation system Ldalvik/annotation/Throws;
a=0;//         value = {
a=0;//             Ljava/sql/SQLException;
a=0;//         }
a=0;//     .end annotation
a=0;// 
a=0;//     .prologue
a=0;//     .local p4, "selectArgList":Ljava/util/List;, "Ljava/util/List<Lcom/j256/ormlite/stmt/ArgumentHolder;>;"
a=0;//     const/16 v2, 0x20
a=0;// 
a=0;//     .line 57
a=0;//     #v2=(PosByte);
a=0;//     const-string v1, "("
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {p3, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     .line 58
a=0;//     iget-object v1, p0, Lcom/j256/ormlite/stmt/query/ManyClause;->first:Lcom/j256/ormlite/stmt/query/Clause;
a=0;// 
a=0;//     invoke-interface {v1, p1, p2, p3, p4}, Lcom/j256/ormlite/stmt/query/Clause;->appendSql(Lcom/j256/ormlite/db/DatabaseType;Ljava/lang/String;Ljava/lang/StringBuilder;Ljava/util/List;)V
a=0;// 
a=0;//     .line 59
a=0;//     iget-object v1, p0, Lcom/j256/ormlite/stmt/query/ManyClause;->second:Lcom/j256/ormlite/stmt/query/Clause;
a=0;// 
a=0;//     if-eqz v1, :cond_0
a=0;// 
a=0;//     .line 60
a=0;//     iget-object v1, p0, Lcom/j256/ormlite/stmt/query/ManyClause;->operation:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {p3, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     .line 61
a=0;//     invoke-virtual {p3, v2}, Ljava/lang/StringBuilder;->append(C)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     .line 62
a=0;//     iget-object v1, p0, Lcom/j256/ormlite/stmt/query/ManyClause;->second:Lcom/j256/ormlite/stmt/query/Clause;
a=0;// 
a=0;//     invoke-interface {v1, p1, p2, p3, p4}, Lcom/j256/ormlite/stmt/query/Clause;->appendSql(Lcom/j256/ormlite/db/DatabaseType;Ljava/lang/String;Ljava/lang/StringBuilder;Ljava/util/List;)V
a=0;// 
a=0;//     .line 64
a=0;//     :cond_0
a=0;//     iget-object v1, p0, Lcom/j256/ormlite/stmt/query/ManyClause;->others:[Lcom/j256/ormlite/stmt/query/Clause;
a=0;// 
a=0;//     if-eqz v1, :cond_1
a=0;// 
a=0;//     .line 65
a=0;//     iget v0, p0, Lcom/j256/ormlite/stmt/query/ManyClause;->startOthersAt:I
a=0;// 
a=0;//     .local v0, "i":I
a=0;//     :goto_0
a=0;//     #v0=(Integer);
a=0;//     iget-object v1, p0, Lcom/j256/ormlite/stmt/query/ManyClause;->others:[Lcom/j256/ormlite/stmt/query/Clause;
a=0;// 
a=0;//     array-length v1, v1
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     if-ge v0, v1, :cond_1
a=0;// 
a=0;//     .line 66
a=0;//     iget-object v1, p0, Lcom/j256/ormlite/stmt/query/ManyClause;->operation:Ljava/lang/String;
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {p3, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     .line 67
a=0;//     invoke-virtual {p3, v2}, Ljava/lang/StringBuilder;->append(C)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     .line 68
a=0;//     iget-object v1, p0, Lcom/j256/ormlite/stmt/query/ManyClause;->others:[Lcom/j256/ormlite/stmt/query/Clause;
a=0;// 
a=0;//     aget-object v1, v1, v0
a=0;// 
a=0;//     #v1=(Null);
a=0;//     invoke-interface {v1, p1, p2, p3, p4}, Lcom/j256/ormlite/stmt/query/Clause;->appendSql(Lcom/j256/ormlite/db/DatabaseType;Ljava/lang/String;Ljava/lang/StringBuilder;Ljava/util/List;)V
a=0;// 
a=0;//     .line 65
a=0;//     add-int/lit8 v0, v0, 0x1
a=0;// 
a=0;//     goto :goto_0
a=0;// 
a=0;//     .line 71
a=0;//     .end local v0    # "i":I
a=0;//     :cond_1
a=0;//     #v0=(Conflicted);v1=(Conflicted);
a=0;//     const-string v1, ") "
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {p3, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     .line 72
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setMissingClause(Lcom/j256/ormlite/stmt/query/Clause;)V
a=0;//     .locals 0
a=0;//     .param p1, "right"    # Lcom/j256/ormlite/stmt/query/Clause;
a=0;// 
a=0;//     .prologue
a=0;//     .line 75
a=0;//     iput-object p1, p0, Lcom/j256/ormlite/stmt/query/ManyClause;->second:Lcom/j256/ormlite/stmt/query/Clause;
a=0;// 
a=0;//     .line 76
a=0;//     return-void
a=0;// .end method
}}
