package com.tencent.open; class TaskGuide$a { void a() { int a;
a=0;// .class abstract Lcom/tencent/open/TaskGuide$a;
a=0;// .super Ljava/lang/Object;
a=0;// .source "ProGuard"
a=0;// 
a=0;// # interfaces
a=0;// .implements Lcom/tencent/tauth/IRequestListener;
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation system Ldalvik/annotation/EnclosingClass;
a=0;//     value = Lcom/tencent/open/TaskGuide;
a=0;// .end annotation
a=0;// 
a=0;// .annotation system Ldalvik/annotation/InnerClass;
a=0;//     accessFlags = 0x402
a=0;//     name = "a"
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field final synthetic a:Lcom/tencent/open/TaskGuide;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method private constructor <init>(Lcom/tencent/open/TaskGuide;)V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 876
a=0;//     iput-object p1, p0, Lcom/tencent/open/TaskGuide$a;->a:Lcom/tencent/open/TaskGuide;
a=0;// 
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcom/tencent/open/TaskGuide$a;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method synthetic constructor <init>(Lcom/tencent/open/TaskGuide;Lcom/tencent/open/TaskGuide$1;)V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 876
a=0;//     invoke-direct {p0, p1}, Lcom/tencent/open/TaskGuide$a;-><init>(Lcom/tencent/open/TaskGuide;)V
a=0;// 
a=0;//     #p0=(Reference,Lcom/tencent/open/TaskGuide$a;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method protected abstract a(Ljava/lang/Exception;)V
a=0;// .end method
a=0;// 
a=0;// .method public onConnectTimeoutException(Lorg/apache/http/conn/ConnectTimeoutException;)V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 896
a=0;//     invoke-virtual {p0, p1}, Lcom/tencent/open/TaskGuide$a;->a(Ljava/lang/Exception;)V
a=0;// 
a=0;//     .line 897
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public onHttpStatusException(Lcom/tencent/utils/HttpUtils$HttpStatusException;)V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 911
a=0;//     invoke-virtual {p0, p1}, Lcom/tencent/open/TaskGuide$a;->a(Ljava/lang/Exception;)V
a=0;// 
a=0;//     .line 912
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public onIOException(Ljava/io/IOException;)V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 881
a=0;//     invoke-virtual {p0, p1}, Lcom/tencent/open/TaskGuide$a;->a(Ljava/lang/Exception;)V
a=0;// 
a=0;//     .line 882
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public onJSONException(Lorg/json/JSONException;)V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 891
a=0;//     invoke-virtual {p0, p1}, Lcom/tencent/open/TaskGuide$a;->a(Ljava/lang/Exception;)V
a=0;// 
a=0;//     .line 892
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public onMalformedURLException(Ljava/net/MalformedURLException;)V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 886
a=0;//     invoke-virtual {p0, p1}, Lcom/tencent/open/TaskGuide$a;->a(Ljava/lang/Exception;)V
a=0;// 
a=0;//     .line 887
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public onNetworkUnavailableException(Lcom/tencent/utils/HttpUtils$NetworkUnavailableException;)V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 906
a=0;//     invoke-virtual {p0, p1}, Lcom/tencent/open/TaskGuide$a;->a(Ljava/lang/Exception;)V
a=0;// 
a=0;//     .line 907
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public onSocketTimeoutException(Ljava/net/SocketTimeoutException;)V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 901
a=0;//     invoke-virtual {p0, p1}, Lcom/tencent/open/TaskGuide$a;->a(Ljava/lang/Exception;)V
a=0;// 
a=0;//     .line 902
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public onUnknowException(Ljava/lang/Exception;)V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 916
a=0;//     invoke-virtual {p0, p1}, Lcom/tencent/open/TaskGuide$a;->a(Ljava/lang/Exception;)V
a=0;// 
a=0;//     .line 917
a=0;//     return-void
a=0;// .end method
}}
