package com.ccit.mmwlan.vo; class AuthFileInfo { void a() { int a;
a=0;// .class public Lcom/ccit/mmwlan/vo/AuthFileInfo;
a=0;// .super Ljava/lang/Object;
a=0;// .source "AuthFileInfo.java"
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field private strDigestAlg:Ljava/lang/String;
a=0;// 
a=0;// .field private strPlaintText:Ljava/lang/String;
a=0;// 
a=0;// .field private strPlaintTextDigestValue:Ljava/lang/String;
a=0;// 
a=0;// .field private strSignatureValue:Ljava/lang/String;
a=0;// 
a=0;// .field private strTimeStamp:Ljava/lang/String;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 3
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcom/ccit/mmwlan/vo/AuthFileInfo;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public getStrDigestAlg()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 28
a=0;//     iget-object v0, p0, Lcom/ccit/mmwlan/vo/AuthFileInfo;->strDigestAlg:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getStrPlaintText()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 12
a=0;//     iget-object v0, p0, Lcom/ccit/mmwlan/vo/AuthFileInfo;->strPlaintText:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getStrPlaintTextDigestValue()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     iget-object v0, p0, Lcom/ccit/mmwlan/vo/AuthFileInfo;->strPlaintTextDigestValue:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getStrSignatureValue()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 44
a=0;//     iget-object v0, p0, Lcom/ccit/mmwlan/vo/AuthFileInfo;->strSignatureValue:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getStrTimeStamp()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 36
a=0;//     iget-object v0, p0, Lcom/ccit/mmwlan/vo/AuthFileInfo;->strTimeStamp:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public setStrDigestAlg(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "strDigestAlg"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 32
a=0;//     iput-object p1, p0, Lcom/ccit/mmwlan/vo/AuthFileInfo;->strDigestAlg:Ljava/lang/String;
a=0;// 
a=0;//     .line 33
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setStrPlaintText(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "strPlaintText"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 16
a=0;//     iput-object p1, p0, Lcom/ccit/mmwlan/vo/AuthFileInfo;->strPlaintText:Ljava/lang/String;
a=0;// 
a=0;//     .line 17
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setStrPlaintTextDigestValue(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "strPlaintTextDigestValue"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 24
a=0;//     iput-object p1, p0, Lcom/ccit/mmwlan/vo/AuthFileInfo;->strPlaintTextDigestValue:Ljava/lang/String;
a=0;// 
a=0;//     .line 25
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setStrSignatureValue(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "strSignatureValue"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 48
a=0;//     iput-object p1, p0, Lcom/ccit/mmwlan/vo/AuthFileInfo;->strSignatureValue:Ljava/lang/String;
a=0;// 
a=0;//     .line 49
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setStrTimeStamp(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "strTimeStamp"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 40
a=0;//     iput-object p1, p0, Lcom/ccit/mmwlan/vo/AuthFileInfo;->strTimeStamp:Ljava/lang/String;
a=0;// 
a=0;//     .line 41
a=0;//     return-void
a=0;// .end method
}}
