package com.ccit.mmwlan.vo; class CertApplyInfo { void a() { int a;
a=0;// .class public Lcom/ccit/mmwlan/vo/CertApplyInfo;
a=0;// .super Ljava/lang/Object;
a=0;// .source "CertApplyInfo.java"
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field private cert:Ljava/lang/String;
a=0;// 
a=0;// .field private encData:Ljava/lang/String;
a=0;// 
a=0;// .field private errormsg:Ljava/lang/String;
a=0;// 
a=0;// .field private randNum:Ljava/lang/String;
a=0;// 
a=0;// .field private result:Ljava/lang/String;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 7
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcom/ccit/mmwlan/vo/CertApplyInfo;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public getCert()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 32
a=0;//     iget-object v0, p0, Lcom/ccit/mmwlan/vo/CertApplyInfo;->cert:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getEncData()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 48
a=0;//     iget-object v0, p0, Lcom/ccit/mmwlan/vo/CertApplyInfo;->encData:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getErrormsg()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 24
a=0;//     iget-object v0, p0, Lcom/ccit/mmwlan/vo/CertApplyInfo;->errormsg:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getRandNum()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 40
a=0;//     iget-object v0, p0, Lcom/ccit/mmwlan/vo/CertApplyInfo;->randNum:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getResult()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 16
a=0;//     iget-object v0, p0, Lcom/ccit/mmwlan/vo/CertApplyInfo;->result:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public setCert(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "cert"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 36
a=0;//     iput-object p1, p0, Lcom/ccit/mmwlan/vo/CertApplyInfo;->cert:Ljava/lang/String;
a=0;// 
a=0;//     .line 37
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setEncData(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "encData"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 52
a=0;//     iput-object p1, p0, Lcom/ccit/mmwlan/vo/CertApplyInfo;->encData:Ljava/lang/String;
a=0;// 
a=0;//     .line 53
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setErrormsg(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "errormsg"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 28
a=0;//     iput-object p1, p0, Lcom/ccit/mmwlan/vo/CertApplyInfo;->errormsg:Ljava/lang/String;
a=0;// 
a=0;//     .line 29
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setRandNum(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "randNum"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 44
a=0;//     iput-object p1, p0, Lcom/ccit/mmwlan/vo/CertApplyInfo;->randNum:Ljava/lang/String;
a=0;// 
a=0;//     .line 45
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setResult(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "result"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     iput-object p1, p0, Lcom/ccit/mmwlan/vo/CertApplyInfo;->result:Ljava/lang/String;
a=0;// 
a=0;//     .line 21
a=0;//     return-void
a=0;// .end method
}}
