package com.ccit.mmwlan.vo; class DeviceAuthInfo { void a() { int a;
a=0;// .class public Lcom/ccit/mmwlan/vo/DeviceAuthInfo;
a=0;// .super Ljava/lang/Object;
a=0;// .source "DeviceAuthInfo.java"
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field private errormsg:Ljava/lang/String;
a=0;// 
a=0;// .field private result:Ljava/lang/String;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 3
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcom/ccit/mmwlan/vo/DeviceAuthInfo;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public getErrormsg()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 17
a=0;//     iget-object v0, p0, Lcom/ccit/mmwlan/vo/DeviceAuthInfo;->errormsg:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getResult()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 9
a=0;//     iget-object v0, p0, Lcom/ccit/mmwlan/vo/DeviceAuthInfo;->result:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public setErrormsg(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "errormsg"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 21
a=0;//     iput-object p1, p0, Lcom/ccit/mmwlan/vo/DeviceAuthInfo;->errormsg:Ljava/lang/String;
a=0;// 
a=0;//     .line 22
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setResult(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "result"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 13
a=0;//     iput-object p1, p0, Lcom/ccit/mmwlan/vo/DeviceAuthInfo;->result:Ljava/lang/String;
a=0;// 
a=0;//     .line 14
a=0;//     return-void
a=0;// .end method
}}
