package com.ccit.mmwlan.vo; class IPDress_ForPad { void a() { int a;
a=0;// .class public Lcom/ccit/mmwlan/vo/IPDress_ForPad;
a=0;// .super Ljava/lang/Object;
a=0;// .source "IPDress_ForPad.java"
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field private strApplySecCertIP:Ljava/lang/String;
a=0;// 
a=0;// .field private strDeviceOuthIp:Ljava/lang/String;
a=0;// 
a=0;// .field private strGetDeviceName:Ljava/lang/String;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 3
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcom/ccit/mmwlan/vo/IPDress_ForPad;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public getStrApplySecCertIP()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 10
a=0;//     iget-object v0, p0, Lcom/ccit/mmwlan/vo/IPDress_ForPad;->strApplySecCertIP:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getStrDeviceOuthIp()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 24
a=0;//     iget-object v0, p0, Lcom/ccit/mmwlan/vo/IPDress_ForPad;->strDeviceOuthIp:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getStrGetDeviceName()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 38
a=0;//     iget-object v0, p0, Lcom/ccit/mmwlan/vo/IPDress_ForPad;->strGetDeviceName:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public setStrApplySecCertIP(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "strApplySecCertIP"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     iput-object p1, p0, Lcom/ccit/mmwlan/vo/IPDress_ForPad;->strApplySecCertIP:Ljava/lang/String;
a=0;// 
a=0;//     .line 21
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setStrDeviceOuthIp(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "strDeviceOuthIp"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 34
a=0;//     iput-object p1, p0, Lcom/ccit/mmwlan/vo/IPDress_ForPad;->strDeviceOuthIp:Ljava/lang/String;
a=0;// 
a=0;//     .line 35
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setStrGetDeviceName(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "strGetDeviceName"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 48
a=0;//     iput-object p1, p0, Lcom/ccit/mmwlan/vo/IPDress_ForPad;->strGetDeviceName:Ljava/lang/String;
a=0;// 
a=0;//     .line 49
a=0;//     return-void
a=0;// .end method
}}
