package com.ccit.mmwlan.vo; class SignView { void a() { int a;
a=0;// .class public Lcom/ccit/mmwlan/vo/SignView;
a=0;// .super Ljava/lang/Object;
a=0;// .source "SignView.java"
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field private m_strErrMsg:Ljava/lang/String;
a=0;// 
a=0;// .field private result:I
a=0;// 
a=0;// .field private userSignature:Ljava/lang/String;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>()V
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 3
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     .line 9
a=0;//     #p0=(Reference,Lcom/ccit/mmwlan/vo/SignView;);
a=0;//     const-string v0, ""
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     iput-object v0, p0, Lcom/ccit/mmwlan/vo/SignView;->m_strErrMsg:Ljava/lang/String;
a=0;// 
a=0;//     .line 3
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public getErrMsg()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 43
a=0;//     iget-object v0, p0, Lcom/ccit/mmwlan/vo/SignView;->m_strErrMsg:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getResult()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 31
a=0;//     iget v0, p0, Lcom/ccit/mmwlan/vo/SignView;->result:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getUserSignature()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 18
a=0;//     iget-object v0, p0, Lcom/ccit/mmwlan/vo/SignView;->userSignature:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public setErrMsg(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "strErrMsg"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 48
a=0;//     iput-object p1, p0, Lcom/ccit/mmwlan/vo/SignView;->m_strErrMsg:Ljava/lang/String;
a=0;// 
a=0;//     .line 49
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setResult(I)V
a=0;//     .locals 0
a=0;//     .param p1, "result"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 35
a=0;//     iput p1, p0, Lcom/ccit/mmwlan/vo/SignView;->result:I
a=0;// 
a=0;//     .line 36
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setUserSignature(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "userSignature"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 22
a=0;//     iput-object p1, p0, Lcom/ccit/mmwlan/vo/SignView;->userSignature:Ljava/lang/String;
a=0;// 
a=0;//     .line 23
a=0;//     return-void
a=0;// .end method
}}
