package com.actionbarsherlock.internal.view.menu; class MenuPresenter { void a() { int a;
a=0;// .class public interface abstract Lcom/actionbarsherlock/internal/view/menu/MenuPresenter;
a=0;// .super Ljava/lang/Object;
a=0;// .source "MenuPresenter.java"
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation system Ldalvik/annotation/MemberClasses;
a=0;//     value = {
a=0;//         Lcom/actionbarsherlock/internal/view/menu/MenuPresenter$Callback;
a=0;//     }
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public abstract collapseItemActionView(Lcom/actionbarsherlock/internal/view/menu/MenuBuilder;Lcom/actionbarsherlock/internal/view/menu/MenuItemImpl;)Z
a=0;// .end method
a=0;// 
a=0;// .method public abstract expandItemActionView(Lcom/actionbarsherlock/internal/view/menu/MenuBuilder;Lcom/actionbarsherlock/internal/view/menu/MenuItemImpl;)Z
a=0;// .end method
a=0;// 
a=0;// .method public abstract flagActionItems()Z
a=0;// .end method
a=0;// 
a=0;// .method public abstract getId()I
a=0;// .end method
a=0;// 
a=0;// .method public abstract getMenuView(Landroid/view/ViewGroup;)Lcom/actionbarsherlock/internal/view/menu/MenuView;
a=0;// .end method
a=0;// 
a=0;// .method public abstract initForMenu(Landroid/content/Context;Lcom/actionbarsherlock/internal/view/menu/MenuBuilder;)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract onCloseMenu(Lcom/actionbarsherlock/internal/view/menu/MenuBuilder;Z)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract onRestoreInstanceState(Landroid/os/Parcelable;)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract onSaveInstanceState()Landroid/os/Parcelable;
a=0;// .end method
a=0;// 
a=0;// .method public abstract onSubMenuSelected(Lcom/actionbarsherlock/internal/view/menu/SubMenuBuilder;)Z
a=0;// .end method
a=0;// 
a=0;// .method public abstract setCallback(Lcom/actionbarsherlock/internal/view/menu/MenuPresenter$Callback;)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract updateMenuView(Z)V
a=0;// .end method
}}
