package com.twocloo.base.alipay; class MobileSecurePayer$3 { void a() { int a;
a=0;// .class Lcom/twocloo/base/alipay/MobileSecurePayer$3;
a=0;// .super Ljava/lang/Object;
a=0;// .source "MobileSecurePayer.java"
a=0;// 
a=0;// # interfaces
a=0;// .implements Ljava/lang/Runnable;
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation system Ldalvik/annotation/EnclosingMethod;
a=0;//     value = Lcom/twocloo/base/alipay/MobileSecurePayer;->pay(Ljava/lang/String;Landroid/os/Handler;ILandroid/content/Context;)Z
a=0;// .end annotation
a=0;// 
a=0;// .annotation system Ldalvik/annotation/InnerClass;
a=0;//     accessFlags = 0x0
a=0;//     name = null
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field final synthetic this$0:Lcom/twocloo/base/alipay/MobileSecurePayer;
a=0;// 
a=0;// .field private final synthetic val$callback:Landroid/os/Handler;
a=0;// 
a=0;// .field private final synthetic val$context:Landroid/content/Context;
a=0;// 
a=0;// .field private final synthetic val$myWhat:I
a=0;// 
a=0;// .field private final synthetic val$strOrderInfo:Ljava/lang/String;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>(Lcom/twocloo/base/alipay/MobileSecurePayer;Ljava/lang/String;Landroid/content/Context;ILandroid/os/Handler;)V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 1
a=0;//     iput-object p1, p0, Lcom/twocloo/base/alipay/MobileSecurePayer$3;->this$0:Lcom/twocloo/base/alipay/MobileSecurePayer;
a=0;// 
a=0;//     iput-object p2, p0, Lcom/twocloo/base/alipay/MobileSecurePayer$3;->val$strOrderInfo:Ljava/lang/String;
a=0;// 
a=0;//     iput-object p3, p0, Lcom/twocloo/base/alipay/MobileSecurePayer$3;->val$context:Landroid/content/Context;
a=0;// 
a=0;//     iput p4, p0, Lcom/twocloo/base/alipay/MobileSecurePayer$3;->val$myWhat:I
a=0;// 
a=0;//     iput-object p5, p0, Lcom/twocloo/base/alipay/MobileSecurePayer$3;->val$callback:Landroid/os/Handler;
a=0;// 
a=0;//     .line 100
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcom/twocloo/base/alipay/MobileSecurePayer$3;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public run()V
a=0;//     .locals 6
a=0;// 
a=0;//     .prologue
a=0;//     .line 109
a=0;//     :try_start_0
a=0;//     iget-object v3, p0, Lcom/twocloo/base/alipay/MobileSecurePayer$3;->this$0:Lcom/twocloo/base/alipay/MobileSecurePayer;
a=0;// 
a=0;//     #v3=(Reference,Lcom/twocloo/base/alipay/MobileSecurePayer;);
a=0;//     invoke-static {v3}, Lcom/twocloo/base/alipay/MobileSecurePayer;->access$0(Lcom/twocloo/base/alipay/MobileSecurePayer;)Ljava/lang/Integer;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     #v4=(Reference,Ljava/lang/Integer;);
a=0;//     monitor-enter v4
a=0;//     :try_end_0
a=0;//     .catch Ljava/lang/Exception; {:try_start_0 .. :try_end_0} :catch_0
a=0;// 
a=0;//     .line 110
a=0;//     :try_start_1
a=0;//     iget-object v3, p0, Lcom/twocloo/base/alipay/MobileSecurePayer$3;->this$0:Lcom/twocloo/base/alipay/MobileSecurePayer;
a=0;// 
a=0;//     invoke-static {v3}, Lcom/twocloo/base/alipay/MobileSecurePayer;->access$3(Lcom/twocloo/base/alipay/MobileSecurePayer;)Lcom/alipay/android/app/IAlixPay;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     if-nez v3, :cond_0
a=0;// 
a=0;//     .line 111
a=0;//     iget-object v3, p0, Lcom/twocloo/base/alipay/MobileSecurePayer$3;->this$0:Lcom/twocloo/base/alipay/MobileSecurePayer;
a=0;// 
a=0;//     invoke-static {v3}, Lcom/twocloo/base/alipay/MobileSecurePayer;->access$0(Lcom/twocloo/base/alipay/MobileSecurePayer;)Ljava/lang/Integer;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-virtual {v3}, Ljava/lang/Object;->wait()V
a=0;// 
a=0;//     .line 109
a=0;//     :cond_0
a=0;//     monitor-exit v4
a=0;//     :try_end_1
a=0;//     .catchall {:try_start_1 .. :try_end_1} :catchall_0
a=0;// 
a=0;//     .line 116
a=0;//     :try_start_2
a=0;//     iget-object v3, p0, Lcom/twocloo/base/alipay/MobileSecurePayer$3;->this$0:Lcom/twocloo/base/alipay/MobileSecurePayer;
a=0;// 
a=0;//     invoke-static {v3}, Lcom/twocloo/base/alipay/MobileSecurePayer;->access$3(Lcom/twocloo/base/alipay/MobileSecurePayer;)Lcom/alipay/android/app/IAlixPay;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     iget-object v4, p0, Lcom/twocloo/base/alipay/MobileSecurePayer$3;->this$0:Lcom/twocloo/base/alipay/MobileSecurePayer;
a=0;// 
a=0;//     invoke-static {v4}, Lcom/twocloo/base/alipay/MobileSecurePayer;->access$4(Lcom/twocloo/base/alipay/MobileSecurePayer;)Lcom/alipay/android/app/IRemoteServiceCallback;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-interface {v3, v4}, Lcom/alipay/android/app/IAlixPay;->registerCallback(Lcom/alipay/android/app/IRemoteServiceCallback;)V
a=0;// 
a=0;//     .line 120
a=0;//     iget-object v3, p0, Lcom/twocloo/base/alipay/MobileSecurePayer$3;->this$0:Lcom/twocloo/base/alipay/MobileSecurePayer;
a=0;// 
a=0;//     invoke-static {v3}, Lcom/twocloo/base/alipay/MobileSecurePayer;->access$3(Lcom/twocloo/base/alipay/MobileSecurePayer;)Lcom/alipay/android/app/IAlixPay;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     iget-object v4, p0, Lcom/twocloo/base/alipay/MobileSecurePayer$3;->val$strOrderInfo:Ljava/lang/String;
a=0;// 
a=0;//     invoke-interface {v3, v4}, Lcom/alipay/android/app/IAlixPay;->Pay(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     .line 121
a=0;//     .local v2, "strRet":Ljava/lang/String;
a=0;//     #v2=(Reference,Ljava/lang/String;);
a=0;//     invoke-static {}, Lcom/twocloo/base/alipay/MobileSecurePayer;->access$5()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     new-instance v4, Ljava/lang/StringBuilder;
a=0;// 
a=0;//     #v4=(UninitRef,Ljava/lang/StringBuilder;);
a=0;//     const-string v5, "After Pay: "
a=0;// 
a=0;//     #v5=(Reference,Ljava/lang/String;);
a=0;//     invoke-direct {v4, v5}, Ljava/lang/StringBuilder;-><init>(Ljava/lang/String;)V
a=0;// 
a=0;//     #v4=(Reference,Ljava/lang/StringBuilder;);
a=0;//     invoke-virtual {v4, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-virtual {v4}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-static {v3, v4}, Lcom/twocloo/base/alipay/BaseHelper;->log(Ljava/lang/String;Ljava/lang/String;)V
a=0;// 
a=0;//     .line 127
a=0;//     iget-object v3, p0, Lcom/twocloo/base/alipay/MobileSecurePayer$3;->this$0:Lcom/twocloo/base/alipay/MobileSecurePayer;
a=0;// 
a=0;//     const/4 v4, 0x0
a=0;// 
a=0;//     #v4=(Null);
a=0;//     invoke-static {v3, v4}, Lcom/twocloo/base/alipay/MobileSecurePayer;->access$6(Lcom/twocloo/base/alipay/MobileSecurePayer;Z)V
a=0;// 
a=0;//     .line 128
a=0;//     iget-object v3, p0, Lcom/twocloo/base/alipay/MobileSecurePayer$3;->this$0:Lcom/twocloo/base/alipay/MobileSecurePayer;
a=0;// 
a=0;//     invoke-static {v3}, Lcom/twocloo/base/alipay/MobileSecurePayer;->access$3(Lcom/twocloo/base/alipay/MobileSecurePayer;)Lcom/alipay/android/app/IAlixPay;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     iget-object v4, p0, Lcom/twocloo/base/alipay/MobileSecurePayer$3;->this$0:Lcom/twocloo/base/alipay/MobileSecurePayer;
a=0;// 
a=0;//     #v4=(Reference,Lcom/twocloo/base/alipay/MobileSecurePayer;);
a=0;//     invoke-static {v4}, Lcom/twocloo/base/alipay/MobileSecurePayer;->access$4(Lcom/twocloo/base/alipay/MobileSecurePayer;)Lcom/alipay/android/app/IRemoteServiceCallback;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-interface {v3, v4}, Lcom/alipay/android/app/IAlixPay;->unregisterCallback(Lcom/alipay/android/app/IRemoteServiceCallback;)V
a=0;// 
a=0;//     .line 129
a=0;//     iget-object v3, p0, Lcom/twocloo/base/alipay/MobileSecurePayer$3;->val$context:Landroid/content/Context;
a=0;// 
a=0;//     invoke-virtual {v3}, Landroid/content/Context;->getApplicationContext()Landroid/content/Context;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     iget-object v4, p0, Lcom/twocloo/base/alipay/MobileSecurePayer$3;->this$0:Lcom/twocloo/base/alipay/MobileSecurePayer;
a=0;// 
a=0;//     invoke-static {v4}, Lcom/twocloo/base/alipay/MobileSecurePayer;->access$7(Lcom/twocloo/base/alipay/MobileSecurePayer;)Landroid/content/ServiceConnection;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-virtual {v3, v4}, Landroid/content/Context;->unbindService(Landroid/content/ServiceConnection;)V
a=0;// 
a=0;//     .line 133
a=0;//     new-instance v1, Landroid/os/Message;
a=0;// 
a=0;//     #v1=(UninitRef,Landroid/os/Message;);
a=0;//     invoke-direct {v1}, Landroid/os/Message;-><init>()V
a=0;// 
a=0;//     .line 134
a=0;//     .local v1, "msg":Landroid/os/Message;
a=0;//     #v1=(Reference,Landroid/os/Message;);
a=0;//     iget v3, p0, Lcom/twocloo/base/alipay/MobileSecurePayer$3;->val$myWhat:I
a=0;// 
a=0;//     #v3=(Integer);
a=0;//     iput v3, v1, Landroid/os/Message;->what:I
a=0;// 
a=0;//     .line 135
a=0;//     iput-object v2, v1, Landroid/os/Message;->obj:Ljava/lang/Object;
a=0;// 
a=0;//     .line 136
a=0;//     iget-object v3, p0, Lcom/twocloo/base/alipay/MobileSecurePayer$3;->val$callback:Landroid/os/Handler;
a=0;// 
a=0;//     #v3=(Reference,Landroid/os/Handler;);
a=0;//     invoke-virtual {v3, v1}, Landroid/os/Handler;->sendMessage(Landroid/os/Message;)Z
a=0;//     :try_end_2
a=0;//     .catch Ljava/lang/Exception; {:try_start_2 .. :try_end_2} :catch_0
a=0;// 
a=0;//     .line 147
a=0;//     .end local v2    # "strRet":Ljava/lang/String;
a=0;//     :goto_0
a=0;//     #v0=(Conflicted);v2=(Conflicted);v4=(Conflicted);v5=(Conflicted);
a=0;//     return-void
a=0;// 
a=0;//     .line 109
a=0;//     .end local v1    # "msg":Landroid/os/Message;
a=0;//     :catchall_0
a=0;//     #v0=(Uninit);v1=(Uninit);v2=(Uninit);v4=(Reference,Ljava/lang/Integer;);v5=(Uninit);
a=0;//     move-exception v3
a=0;// 
a=0;//     :try_start_3
a=0;//     monitor-exit v4
a=0;//     :try_end_3
a=0;//     .catchall {:try_start_3 .. :try_end_3} :catchall_0
a=0;// 
a=0;//     :try_start_4
a=0;//     throw v3
a=0;//     :try_end_4
a=0;//     .catch Ljava/lang/Exception; {:try_start_4 .. :try_end_4} :catch_0
a=0;// 
a=0;//     .line 137
a=0;//     :catch_0
a=0;//     move-exception v0
a=0;// 
a=0;//     .line 138
a=0;//     .local v0, "e":Ljava/lang/Exception;
a=0;//     #v0=(Reference,Ljava/lang/Exception;);
a=0;//     invoke-virtual {v0}, Ljava/lang/Exception;->printStackTrace()V
a=0;// 
a=0;//     .line 142
a=0;//     new-instance v1, Landroid/os/Message;
a=0;// 
a=0;//     #v1=(UninitRef,Landroid/os/Message;);
a=0;//     invoke-direct {v1}, Landroid/os/Message;-><init>()V
a=0;// 
a=0;//     .line 143
a=0;//     .restart local v1    # "msg":Landroid/os/Message;
a=0;//     #v1=(Reference,Landroid/os/Message;);
a=0;//     iget v3, p0, Lcom/twocloo/base/alipay/MobileSecurePayer$3;->val$myWhat:I
a=0;// 
a=0;//     #v3=(Integer);
a=0;//     iput v3, v1, Landroid/os/Message;->what:I
a=0;// 
a=0;//     .line 144
a=0;//     invoke-virtual {v0}, Ljava/lang/Exception;->toString()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     #v3=(Reference,Ljava/lang/String;);
a=0;//     iput-object v3, v1, Landroid/os/Message;->obj:Ljava/lang/Object;
a=0;// 
a=0;//     .line 145
a=0;//     iget-object v3, p0, Lcom/twocloo/base/alipay/MobileSecurePayer$3;->val$callback:Landroid/os/Handler;
a=0;// 
a=0;//     invoke-virtual {v3, v1}, Landroid/os/Handler;->sendMessage(Landroid/os/Message;)Z
a=0;// 
a=0;//     goto :goto_0
a=0;// .end method
}}
