package com.j256.ormlite.field; class DataPersister { void a() { int a;
a=0;// .class public interface abstract Lcom/j256/ormlite/field/DataPersister;
a=0;// .super Ljava/lang/Object;
a=0;// .source "DataPersister.java"
a=0;// 
a=0;// # interfaces
a=0;// .implements Lcom/j256/ormlite/field/FieldConverter;
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public abstract convertIdNumber(Ljava/lang/Number;)Ljava/lang/Object;
a=0;// .end method
a=0;// 
a=0;// .method public abstract dataIsEqual(Ljava/lang/Object;Ljava/lang/Object;)Z
a=0;// .end method
a=0;// 
a=0;// .method public abstract generateId()Ljava/lang/Object;
a=0;// .end method
a=0;// 
a=0;// .method public abstract getAssociatedClassNames()[Ljava/lang/String;
a=0;// .end method
a=0;// 
a=0;// .method public abstract getAssociatedClasses()[Ljava/lang/Class;
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "()[",
a=0;//             "Ljava/lang/Class",
a=0;//             "<*>;"
a=0;//         }
a=0;//     .end annotation
a=0;// .end method
a=0;// 
a=0;// .method public abstract getDefaultWidth()I
a=0;// .end method
a=0;// 
a=0;// .method public abstract isAppropriateId()Z
a=0;// .end method
a=0;// 
a=0;// .method public abstract isArgumentHolderRequired()Z
a=0;// .end method
a=0;// 
a=0;// .method public abstract isComparable()Z
a=0;// .end method
a=0;// 
a=0;// .method public abstract isEscapedDefaultValue()Z
a=0;// .end method
a=0;// 
a=0;// .method public abstract isEscapedValue()Z
a=0;// .end method
a=0;// 
a=0;// .method public abstract isPrimitive()Z
a=0;// .end method
a=0;// 
a=0;// .method public abstract isSelfGeneratedId()Z
a=0;// .end method
a=0;// 
a=0;// .method public abstract isValidForField(Ljava/lang/reflect/Field;)Z
a=0;// .end method
a=0;// 
a=0;// .method public abstract isValidForVersion()Z
a=0;// .end method
a=0;// 
a=0;// .method public abstract isValidGeneratedType()Z
a=0;// .end method
a=0;// 
a=0;// .method public abstract makeConfigObject(Lcom/j256/ormlite/field/FieldType;)Ljava/lang/Object;
a=0;//     .annotation system Ldalvik/annotation/Throws;
a=0;//         value = {
a=0;//             Ljava/sql/SQLException;
a=0;//         }
a=0;//     .end annotation
a=0;// .end method
a=0;// 
a=0;// .method public abstract moveToNextValue(Ljava/lang/Object;)Ljava/lang/Object;
a=0;// .end method
}}
