package com.j256.ormlite.field; class DataType { void a() { int a;
a=0;// .class public final enum Lcom/j256/ormlite/field/DataType;
a=0;// .super Ljava/lang/Enum;
a=0;// .source "DataType.java"
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation system Ldalvik/annotation/Signature;
a=0;//     value = {
a=0;//         "Ljava/lang/Enum",
a=0;//         "<",
a=0;//         "Lcom/j256/ormlite/field/DataType;",
a=0;//         ">;"
a=0;//     }
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # static fields
a=0;// .field private static final synthetic $VALUES:[Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;// .field public static final enum BIG_DECIMAL:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;// .field public static final enum BIG_DECIMAL_NUMERIC:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;// .field public static final enum BIG_INTEGER:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;// .field public static final enum BOOLEAN:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;// .field public static final enum BOOLEAN_OBJ:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;// .field public static final enum BYTE:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;// .field public static final enum BYTE_ARRAY:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;// .field public static final enum BYTE_OBJ:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;// .field public static final enum CHAR:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;// .field public static final enum CHAR_OBJ:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;// .field public static final enum DATE:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;// .field public static final enum DATE_LONG:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;// .field public static final enum DATE_STRING:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;// .field public static final enum DATE_TIME:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;// .field public static final enum DOUBLE:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;// .field public static final enum DOUBLE_OBJ:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;// .field public static final enum ENUM_INTEGER:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;// .field public static final enum ENUM_STRING:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;// .field public static final enum FLOAT:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;// .field public static final enum FLOAT_OBJ:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;// .field public static final enum INTEGER:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;// .field public static final enum INTEGER_OBJ:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;// .field public static final enum LONG:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;// .field public static final enum LONG_OBJ:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;// .field public static final enum LONG_STRING:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;// .field public static final enum SERIALIZABLE:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;// .field public static final enum SHORT:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;// .field public static final enum SHORT_OBJ:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;// .field public static final enum SQL_DATE:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;// .field public static final enum STRING:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;// .field public static final enum STRING_BYTES:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;// .field public static final enum TIME_STAMP:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;// .field public static final enum UNKNOWN:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;// .field public static final enum UUID:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field private final dataPersister:Lcom/j256/ormlite/field/DataPersister;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method static constructor <clinit>()V
a=0;//     .locals 9
a=0;// 
a=0;//     .prologue
a=0;//     const/4 v8, 0x4
a=0;// 
a=0;//     #v8=(PosByte);
a=0;//     const/4 v7, 0x3
a=0;// 
a=0;//     #v7=(PosByte);
a=0;//     const/4 v6, 0x2
a=0;// 
a=0;//     #v6=(PosByte);
a=0;//     const/4 v5, 0x1
a=0;// 
a=0;//     #v5=(One);
a=0;//     const/4 v4, 0x0
a=0;// 
a=0;//     .line 50
a=0;//     #v4=(Null);
a=0;//     new-instance v0, Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     #v0=(UninitRef,Lcom/j256/ormlite/field/DataType;);
a=0;//     const-string v1, "STRING"
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-static {}, Lcom/j256/ormlite/field/types/StringType;->getSingleton()Lcom/j256/ormlite/field/types/StringType;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     #v2=(Reference,Lcom/j256/ormlite/field/types/StringType;);
a=0;//     invoke-direct {v0, v1, v4, v2}, Lcom/j256/ormlite/field/DataType;-><init>(Ljava/lang/String;ILcom/j256/ormlite/field/DataPersister;)V
a=0;// 
a=0;//     #v0=(Reference,Lcom/j256/ormlite/field/DataType;);
a=0;//     sput-object v0, Lcom/j256/ormlite/field/DataType;->STRING:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     .line 54
a=0;//     new-instance v0, Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     #v0=(UninitRef,Lcom/j256/ormlite/field/DataType;);
a=0;//     const-string v1, "LONG_STRING"
a=0;// 
a=0;//     invoke-static {}, Lcom/j256/ormlite/field/types/LongStringType;->getSingleton()Lcom/j256/ormlite/field/types/LongStringType;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-direct {v0, v1, v5, v2}, Lcom/j256/ormlite/field/DataType;-><init>(Ljava/lang/String;ILcom/j256/ormlite/field/DataPersister;)V
a=0;// 
a=0;//     #v0=(Reference,Lcom/j256/ormlite/field/DataType;);
a=0;//     sput-object v0, Lcom/j256/ormlite/field/DataType;->LONG_STRING:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     .line 59
a=0;//     new-instance v0, Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     #v0=(UninitRef,Lcom/j256/ormlite/field/DataType;);
a=0;//     const-string v1, "STRING_BYTES"
a=0;// 
a=0;//     invoke-static {}, Lcom/j256/ormlite/field/types/StringBytesType;->getSingleton()Lcom/j256/ormlite/field/types/StringBytesType;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-direct {v0, v1, v6, v2}, Lcom/j256/ormlite/field/DataType;-><init>(Ljava/lang/String;ILcom/j256/ormlite/field/DataPersister;)V
a=0;// 
a=0;//     #v0=(Reference,Lcom/j256/ormlite/field/DataType;);
a=0;//     sput-object v0, Lcom/j256/ormlite/field/DataType;->STRING_BYTES:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     .line 63
a=0;//     new-instance v0, Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     #v0=(UninitRef,Lcom/j256/ormlite/field/DataType;);
a=0;//     const-string v1, "BOOLEAN"
a=0;// 
a=0;//     invoke-static {}, Lcom/j256/ormlite/field/types/BooleanType;->getSingleton()Lcom/j256/ormlite/field/types/BooleanType;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-direct {v0, v1, v7, v2}, Lcom/j256/ormlite/field/DataType;-><init>(Ljava/lang/String;ILcom/j256/ormlite/field/DataPersister;)V
a=0;// 
a=0;//     #v0=(Reference,Lcom/j256/ormlite/field/DataType;);
a=0;//     sput-object v0, Lcom/j256/ormlite/field/DataType;->BOOLEAN:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     .line 67
a=0;//     new-instance v0, Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     #v0=(UninitRef,Lcom/j256/ormlite/field/DataType;);
a=0;//     const-string v1, "BOOLEAN_OBJ"
a=0;// 
a=0;//     invoke-static {}, Lcom/j256/ormlite/field/types/BooleanObjectType;->getSingleton()Lcom/j256/ormlite/field/types/BooleanObjectType;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-direct {v0, v1, v8, v2}, Lcom/j256/ormlite/field/DataType;-><init>(Ljava/lang/String;ILcom/j256/ormlite/field/DataPersister;)V
a=0;// 
a=0;//     #v0=(Reference,Lcom/j256/ormlite/field/DataType;);
a=0;//     sput-object v0, Lcom/j256/ormlite/field/DataType;->BOOLEAN_OBJ:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     .line 75
a=0;//     new-instance v0, Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     #v0=(UninitRef,Lcom/j256/ormlite/field/DataType;);
a=0;//     const-string v1, "DATE"
a=0;// 
a=0;//     const/4 v2, 0x5
a=0;// 
a=0;//     #v2=(PosByte);
a=0;//     invoke-static {}, Lcom/j256/ormlite/field/types/DateType;->getSingleton()Lcom/j256/ormlite/field/types/DateType;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     #v3=(Reference,Lcom/j256/ormlite/field/types/DateType;);
a=0;//     invoke-direct {v0, v1, v2, v3}, Lcom/j256/ormlite/field/DataType;-><init>(Ljava/lang/String;ILcom/j256/ormlite/field/DataPersister;)V
a=0;// 
a=0;//     #v0=(Reference,Lcom/j256/ormlite/field/DataType;);
a=0;//     sput-object v0, Lcom/j256/ormlite/field/DataType;->DATE:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     .line 85
a=0;//     new-instance v0, Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     #v0=(UninitRef,Lcom/j256/ormlite/field/DataType;);
a=0;//     const-string v1, "DATE_LONG"
a=0;// 
a=0;//     const/4 v2, 0x6
a=0;// 
a=0;//     invoke-static {}, Lcom/j256/ormlite/field/types/DateLongType;->getSingleton()Lcom/j256/ormlite/field/types/DateLongType;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-direct {v0, v1, v2, v3}, Lcom/j256/ormlite/field/DataType;-><init>(Ljava/lang/String;ILcom/j256/ormlite/field/DataPersister;)V
a=0;// 
a=0;//     #v0=(Reference,Lcom/j256/ormlite/field/DataType;);
a=0;//     sput-object v0, Lcom/j256/ormlite/field/DataType;->DATE_LONG:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     .line 99
a=0;//     new-instance v0, Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     #v0=(UninitRef,Lcom/j256/ormlite/field/DataType;);
a=0;//     const-string v1, "DATE_STRING"
a=0;// 
a=0;//     const/4 v2, 0x7
a=0;// 
a=0;//     invoke-static {}, Lcom/j256/ormlite/field/types/DateStringType;->getSingleton()Lcom/j256/ormlite/field/types/DateStringType;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-direct {v0, v1, v2, v3}, Lcom/j256/ormlite/field/DataType;-><init>(Ljava/lang/String;ILcom/j256/ormlite/field/DataPersister;)V
a=0;// 
a=0;//     #v0=(Reference,Lcom/j256/ormlite/field/DataType;);
a=0;//     sput-object v0, Lcom/j256/ormlite/field/DataType;->DATE_STRING:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     .line 103
a=0;//     new-instance v0, Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     #v0=(UninitRef,Lcom/j256/ormlite/field/DataType;);
a=0;//     const-string v1, "CHAR"
a=0;// 
a=0;//     const/16 v2, 0x8
a=0;// 
a=0;//     invoke-static {}, Lcom/j256/ormlite/field/types/CharType;->getSingleton()Lcom/j256/ormlite/field/types/CharType;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-direct {v0, v1, v2, v3}, Lcom/j256/ormlite/field/DataType;-><init>(Ljava/lang/String;ILcom/j256/ormlite/field/DataPersister;)V
a=0;// 
a=0;//     #v0=(Reference,Lcom/j256/ormlite/field/DataType;);
a=0;//     sput-object v0, Lcom/j256/ormlite/field/DataType;->CHAR:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     .line 107
a=0;//     new-instance v0, Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     #v0=(UninitRef,Lcom/j256/ormlite/field/DataType;);
a=0;//     const-string v1, "CHAR_OBJ"
a=0;// 
a=0;//     const/16 v2, 0x9
a=0;// 
a=0;//     invoke-static {}, Lcom/j256/ormlite/field/types/CharacterObjectType;->getSingleton()Lcom/j256/ormlite/field/types/CharacterObjectType;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-direct {v0, v1, v2, v3}, Lcom/j256/ormlite/field/DataType;-><init>(Ljava/lang/String;ILcom/j256/ormlite/field/DataPersister;)V
a=0;// 
a=0;//     #v0=(Reference,Lcom/j256/ormlite/field/DataType;);
a=0;//     sput-object v0, Lcom/j256/ormlite/field/DataType;->CHAR_OBJ:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     .line 111
a=0;//     new-instance v0, Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     #v0=(UninitRef,Lcom/j256/ormlite/field/DataType;);
a=0;//     const-string v1, "BYTE"
a=0;// 
a=0;//     const/16 v2, 0xa
a=0;// 
a=0;//     invoke-static {}, Lcom/j256/ormlite/field/types/ByteType;->getSingleton()Lcom/j256/ormlite/field/types/ByteType;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-direct {v0, v1, v2, v3}, Lcom/j256/ormlite/field/DataType;-><init>(Ljava/lang/String;ILcom/j256/ormlite/field/DataPersister;)V
a=0;// 
a=0;//     #v0=(Reference,Lcom/j256/ormlite/field/DataType;);
a=0;//     sput-object v0, Lcom/j256/ormlite/field/DataType;->BYTE:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     .line 116
a=0;//     new-instance v0, Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     #v0=(UninitRef,Lcom/j256/ormlite/field/DataType;);
a=0;//     const-string v1, "BYTE_ARRAY"
a=0;// 
a=0;//     const/16 v2, 0xb
a=0;// 
a=0;//     invoke-static {}, Lcom/j256/ormlite/field/types/ByteArrayType;->getSingleton()Lcom/j256/ormlite/field/types/ByteArrayType;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-direct {v0, v1, v2, v3}, Lcom/j256/ormlite/field/DataType;-><init>(Ljava/lang/String;ILcom/j256/ormlite/field/DataPersister;)V
a=0;// 
a=0;//     #v0=(Reference,Lcom/j256/ormlite/field/DataType;);
a=0;//     sput-object v0, Lcom/j256/ormlite/field/DataType;->BYTE_ARRAY:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     .line 120
a=0;//     new-instance v0, Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     #v0=(UninitRef,Lcom/j256/ormlite/field/DataType;);
a=0;//     const-string v1, "BYTE_OBJ"
a=0;// 
a=0;//     const/16 v2, 0xc
a=0;// 
a=0;//     invoke-static {}, Lcom/j256/ormlite/field/types/ByteObjectType;->getSingleton()Lcom/j256/ormlite/field/types/ByteObjectType;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-direct {v0, v1, v2, v3}, Lcom/j256/ormlite/field/DataType;-><init>(Ljava/lang/String;ILcom/j256/ormlite/field/DataPersister;)V
a=0;// 
a=0;//     #v0=(Reference,Lcom/j256/ormlite/field/DataType;);
a=0;//     sput-object v0, Lcom/j256/ormlite/field/DataType;->BYTE_OBJ:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     .line 124
a=0;//     new-instance v0, Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     #v0=(UninitRef,Lcom/j256/ormlite/field/DataType;);
a=0;//     const-string v1, "SHORT"
a=0;// 
a=0;//     const/16 v2, 0xd
a=0;// 
a=0;//     invoke-static {}, Lcom/j256/ormlite/field/types/ShortType;->getSingleton()Lcom/j256/ormlite/field/types/ShortType;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-direct {v0, v1, v2, v3}, Lcom/j256/ormlite/field/DataType;-><init>(Ljava/lang/String;ILcom/j256/ormlite/field/DataPersister;)V
a=0;// 
a=0;//     #v0=(Reference,Lcom/j256/ormlite/field/DataType;);
a=0;//     sput-object v0, Lcom/j256/ormlite/field/DataType;->SHORT:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     .line 128
a=0;//     new-instance v0, Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     #v0=(UninitRef,Lcom/j256/ormlite/field/DataType;);
a=0;//     const-string v1, "SHORT_OBJ"
a=0;// 
a=0;//     const/16 v2, 0xe
a=0;// 
a=0;//     invoke-static {}, Lcom/j256/ormlite/field/types/ShortObjectType;->getSingleton()Lcom/j256/ormlite/field/types/ShortObjectType;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-direct {v0, v1, v2, v3}, Lcom/j256/ormlite/field/DataType;-><init>(Ljava/lang/String;ILcom/j256/ormlite/field/DataPersister;)V
a=0;// 
a=0;//     #v0=(Reference,Lcom/j256/ormlite/field/DataType;);
a=0;//     sput-object v0, Lcom/j256/ormlite/field/DataType;->SHORT_OBJ:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     .line 132
a=0;//     new-instance v0, Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     #v0=(UninitRef,Lcom/j256/ormlite/field/DataType;);
a=0;//     const-string v1, "INTEGER"
a=0;// 
a=0;//     const/16 v2, 0xf
a=0;// 
a=0;//     invoke-static {}, Lcom/j256/ormlite/field/types/IntType;->getSingleton()Lcom/j256/ormlite/field/types/IntType;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-direct {v0, v1, v2, v3}, Lcom/j256/ormlite/field/DataType;-><init>(Ljava/lang/String;ILcom/j256/ormlite/field/DataPersister;)V
a=0;// 
a=0;//     #v0=(Reference,Lcom/j256/ormlite/field/DataType;);
a=0;//     sput-object v0, Lcom/j256/ormlite/field/DataType;->INTEGER:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     .line 136
a=0;//     new-instance v0, Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     #v0=(UninitRef,Lcom/j256/ormlite/field/DataType;);
a=0;//     const-string v1, "INTEGER_OBJ"
a=0;// 
a=0;//     const/16 v2, 0x10
a=0;// 
a=0;//     invoke-static {}, Lcom/j256/ormlite/field/types/IntegerObjectType;->getSingleton()Lcom/j256/ormlite/field/types/IntegerObjectType;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-direct {v0, v1, v2, v3}, Lcom/j256/ormlite/field/DataType;-><init>(Ljava/lang/String;ILcom/j256/ormlite/field/DataPersister;)V
a=0;// 
a=0;//     #v0=(Reference,Lcom/j256/ormlite/field/DataType;);
a=0;//     sput-object v0, Lcom/j256/ormlite/field/DataType;->INTEGER_OBJ:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     .line 140
a=0;//     new-instance v0, Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     #v0=(UninitRef,Lcom/j256/ormlite/field/DataType;);
a=0;//     const-string v1, "LONG"
a=0;// 
a=0;//     const/16 v2, 0x11
a=0;// 
a=0;//     invoke-static {}, Lcom/j256/ormlite/field/types/LongType;->getSingleton()Lcom/j256/ormlite/field/types/LongType;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-direct {v0, v1, v2, v3}, Lcom/j256/ormlite/field/DataType;-><init>(Ljava/lang/String;ILcom/j256/ormlite/field/DataPersister;)V
a=0;// 
a=0;//     #v0=(Reference,Lcom/j256/ormlite/field/DataType;);
a=0;//     sput-object v0, Lcom/j256/ormlite/field/DataType;->LONG:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     .line 144
a=0;//     new-instance v0, Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     #v0=(UninitRef,Lcom/j256/ormlite/field/DataType;);
a=0;//     const-string v1, "LONG_OBJ"
a=0;// 
a=0;//     const/16 v2, 0x12
a=0;// 
a=0;//     invoke-static {}, Lcom/j256/ormlite/field/types/LongObjectType;->getSingleton()Lcom/j256/ormlite/field/types/LongObjectType;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-direct {v0, v1, v2, v3}, Lcom/j256/ormlite/field/DataType;-><init>(Ljava/lang/String;ILcom/j256/ormlite/field/DataPersister;)V
a=0;// 
a=0;//     #v0=(Reference,Lcom/j256/ormlite/field/DataType;);
a=0;//     sput-object v0, Lcom/j256/ormlite/field/DataType;->LONG_OBJ:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     .line 148
a=0;//     new-instance v0, Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     #v0=(UninitRef,Lcom/j256/ormlite/field/DataType;);
a=0;//     const-string v1, "FLOAT"
a=0;// 
a=0;//     const/16 v2, 0x13
a=0;// 
a=0;//     invoke-static {}, Lcom/j256/ormlite/field/types/FloatType;->getSingleton()Lcom/j256/ormlite/field/types/FloatType;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-direct {v0, v1, v2, v3}, Lcom/j256/ormlite/field/DataType;-><init>(Ljava/lang/String;ILcom/j256/ormlite/field/DataPersister;)V
a=0;// 
a=0;//     #v0=(Reference,Lcom/j256/ormlite/field/DataType;);
a=0;//     sput-object v0, Lcom/j256/ormlite/field/DataType;->FLOAT:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     .line 152
a=0;//     new-instance v0, Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     #v0=(UninitRef,Lcom/j256/ormlite/field/DataType;);
a=0;//     const-string v1, "FLOAT_OBJ"
a=0;// 
a=0;//     const/16 v2, 0x14
a=0;// 
a=0;//     invoke-static {}, Lcom/j256/ormlite/field/types/FloatObjectType;->getSingleton()Lcom/j256/ormlite/field/types/FloatObjectType;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-direct {v0, v1, v2, v3}, Lcom/j256/ormlite/field/DataType;-><init>(Ljava/lang/String;ILcom/j256/ormlite/field/DataPersister;)V
a=0;// 
a=0;//     #v0=(Reference,Lcom/j256/ormlite/field/DataType;);
a=0;//     sput-object v0, Lcom/j256/ormlite/field/DataType;->FLOAT_OBJ:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     .line 156
a=0;//     new-instance v0, Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     #v0=(UninitRef,Lcom/j256/ormlite/field/DataType;);
a=0;//     const-string v1, "DOUBLE"
a=0;// 
a=0;//     const/16 v2, 0x15
a=0;// 
a=0;//     invoke-static {}, Lcom/j256/ormlite/field/types/DoubleType;->getSingleton()Lcom/j256/ormlite/field/types/DoubleType;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-direct {v0, v1, v2, v3}, Lcom/j256/ormlite/field/DataType;-><init>(Ljava/lang/String;ILcom/j256/ormlite/field/DataPersister;)V
a=0;// 
a=0;//     #v0=(Reference,Lcom/j256/ormlite/field/DataType;);
a=0;//     sput-object v0, Lcom/j256/ormlite/field/DataType;->DOUBLE:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     .line 160
a=0;//     new-instance v0, Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     #v0=(UninitRef,Lcom/j256/ormlite/field/DataType;);
a=0;//     const-string v1, "DOUBLE_OBJ"
a=0;// 
a=0;//     const/16 v2, 0x16
a=0;// 
a=0;//     invoke-static {}, Lcom/j256/ormlite/field/types/DoubleObjectType;->getSingleton()Lcom/j256/ormlite/field/types/DoubleObjectType;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-direct {v0, v1, v2, v3}, Lcom/j256/ormlite/field/DataType;-><init>(Ljava/lang/String;ILcom/j256/ormlite/field/DataPersister;)V
a=0;// 
a=0;//     #v0=(Reference,Lcom/j256/ormlite/field/DataType;);
a=0;//     sput-object v0, Lcom/j256/ormlite/field/DataType;->DOUBLE_OBJ:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     .line 166
a=0;//     new-instance v0, Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     #v0=(UninitRef,Lcom/j256/ormlite/field/DataType;);
a=0;//     const-string v1, "SERIALIZABLE"
a=0;// 
a=0;//     const/16 v2, 0x17
a=0;// 
a=0;//     invoke-static {}, Lcom/j256/ormlite/field/types/SerializableType;->getSingleton()Lcom/j256/ormlite/field/types/SerializableType;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-direct {v0, v1, v2, v3}, Lcom/j256/ormlite/field/DataType;-><init>(Ljava/lang/String;ILcom/j256/ormlite/field/DataPersister;)V
a=0;// 
a=0;//     #v0=(Reference,Lcom/j256/ormlite/field/DataType;);
a=0;//     sput-object v0, Lcom/j256/ormlite/field/DataType;->SERIALIZABLE:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     .line 170
a=0;//     new-instance v0, Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     #v0=(UninitRef,Lcom/j256/ormlite/field/DataType;);
a=0;//     const-string v1, "ENUM_STRING"
a=0;// 
a=0;//     const/16 v2, 0x18
a=0;// 
a=0;//     invoke-static {}, Lcom/j256/ormlite/field/types/EnumStringType;->getSingleton()Lcom/j256/ormlite/field/types/EnumStringType;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-direct {v0, v1, v2, v3}, Lcom/j256/ormlite/field/DataType;-><init>(Ljava/lang/String;ILcom/j256/ormlite/field/DataPersister;)V
a=0;// 
a=0;//     #v0=(Reference,Lcom/j256/ormlite/field/DataType;);
a=0;//     sput-object v0, Lcom/j256/ormlite/field/DataType;->ENUM_STRING:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     .line 175
a=0;//     new-instance v0, Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     #v0=(UninitRef,Lcom/j256/ormlite/field/DataType;);
a=0;//     const-string v1, "ENUM_INTEGER"
a=0;// 
a=0;//     const/16 v2, 0x19
a=0;// 
a=0;//     invoke-static {}, Lcom/j256/ormlite/field/types/EnumIntegerType;->getSingleton()Lcom/j256/ormlite/field/types/EnumIntegerType;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-direct {v0, v1, v2, v3}, Lcom/j256/ormlite/field/DataType;-><init>(Ljava/lang/String;ILcom/j256/ormlite/field/DataPersister;)V
a=0;// 
a=0;//     #v0=(Reference,Lcom/j256/ormlite/field/DataType;);
a=0;//     sput-object v0, Lcom/j256/ormlite/field/DataType;->ENUM_INTEGER:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     .line 179
a=0;//     new-instance v0, Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     #v0=(UninitRef,Lcom/j256/ormlite/field/DataType;);
a=0;//     const-string v1, "UUID"
a=0;// 
a=0;//     const/16 v2, 0x1a
a=0;// 
a=0;//     invoke-static {}, Lcom/j256/ormlite/field/types/UuidType;->getSingleton()Lcom/j256/ormlite/field/types/UuidType;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-direct {v0, v1, v2, v3}, Lcom/j256/ormlite/field/DataType;-><init>(Ljava/lang/String;ILcom/j256/ormlite/field/DataPersister;)V
a=0;// 
a=0;//     #v0=(Reference,Lcom/j256/ormlite/field/DataType;);
a=0;//     sput-object v0, Lcom/j256/ormlite/field/DataType;->UUID:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     .line 183
a=0;//     new-instance v0, Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     #v0=(UninitRef,Lcom/j256/ormlite/field/DataType;);
a=0;//     const-string v1, "BIG_INTEGER"
a=0;// 
a=0;//     const/16 v2, 0x1b
a=0;// 
a=0;//     invoke-static {}, Lcom/j256/ormlite/field/types/BigIntegerType;->getSingleton()Lcom/j256/ormlite/field/types/BigIntegerType;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-direct {v0, v1, v2, v3}, Lcom/j256/ormlite/field/DataType;-><init>(Ljava/lang/String;ILcom/j256/ormlite/field/DataPersister;)V
a=0;// 
a=0;//     #v0=(Reference,Lcom/j256/ormlite/field/DataType;);
a=0;//     sput-object v0, Lcom/j256/ormlite/field/DataType;->BIG_INTEGER:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     .line 187
a=0;//     new-instance v0, Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     #v0=(UninitRef,Lcom/j256/ormlite/field/DataType;);
a=0;//     const-string v1, "BIG_DECIMAL"
a=0;// 
a=0;//     const/16 v2, 0x1c
a=0;// 
a=0;//     invoke-static {}, Lcom/j256/ormlite/field/types/BigDecimalStringType;->getSingleton()Lcom/j256/ormlite/field/types/BigDecimalStringType;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-direct {v0, v1, v2, v3}, Lcom/j256/ormlite/field/DataType;-><init>(Ljava/lang/String;ILcom/j256/ormlite/field/DataPersister;)V
a=0;// 
a=0;//     #v0=(Reference,Lcom/j256/ormlite/field/DataType;);
a=0;//     sput-object v0, Lcom/j256/ormlite/field/DataType;->BIG_DECIMAL:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     .line 191
a=0;//     new-instance v0, Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     #v0=(UninitRef,Lcom/j256/ormlite/field/DataType;);
a=0;//     const-string v1, "BIG_DECIMAL_NUMERIC"
a=0;// 
a=0;//     const/16 v2, 0x1d
a=0;// 
a=0;//     invoke-static {}, Lcom/j256/ormlite/field/types/BigDecimalNumericType;->getSingleton()Lcom/j256/ormlite/field/types/BigDecimalNumericType;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-direct {v0, v1, v2, v3}, Lcom/j256/ormlite/field/DataType;-><init>(Ljava/lang/String;ILcom/j256/ormlite/field/DataPersister;)V
a=0;// 
a=0;//     #v0=(Reference,Lcom/j256/ormlite/field/DataType;);
a=0;//     sput-object v0, Lcom/j256/ormlite/field/DataType;->BIG_DECIMAL_NUMERIC:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     .line 197
a=0;//     new-instance v0, Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     #v0=(UninitRef,Lcom/j256/ormlite/field/DataType;);
a=0;//     const-string v1, "DATE_TIME"
a=0;// 
a=0;//     const/16 v2, 0x1e
a=0;// 
a=0;//     invoke-static {}, Lcom/j256/ormlite/field/types/DateTimeType;->getSingleton()Lcom/j256/ormlite/field/types/DateTimeType;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-direct {v0, v1, v2, v3}, Lcom/j256/ormlite/field/DataType;-><init>(Ljava/lang/String;ILcom/j256/ormlite/field/DataPersister;)V
a=0;// 
a=0;//     #v0=(Reference,Lcom/j256/ormlite/field/DataType;);
a=0;//     sput-object v0, Lcom/j256/ormlite/field/DataType;->DATE_TIME:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     .line 205
a=0;//     new-instance v0, Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     #v0=(UninitRef,Lcom/j256/ormlite/field/DataType;);
a=0;//     const-string v1, "SQL_DATE"
a=0;// 
a=0;//     const/16 v2, 0x1f
a=0;// 
a=0;//     invoke-static {}, Lcom/j256/ormlite/field/types/SqlDateType;->getSingleton()Lcom/j256/ormlite/field/types/SqlDateType;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-direct {v0, v1, v2, v3}, Lcom/j256/ormlite/field/DataType;-><init>(Ljava/lang/String;ILcom/j256/ormlite/field/DataPersister;)V
a=0;// 
a=0;//     #v0=(Reference,Lcom/j256/ormlite/field/DataType;);
a=0;//     sput-object v0, Lcom/j256/ormlite/field/DataType;->SQL_DATE:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     .line 209
a=0;//     new-instance v0, Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     #v0=(UninitRef,Lcom/j256/ormlite/field/DataType;);
a=0;//     const-string v1, "TIME_STAMP"
a=0;// 
a=0;//     const/16 v2, 0x20
a=0;// 
a=0;//     invoke-static {}, Lcom/j256/ormlite/field/types/TimeStampType;->getSingleton()Lcom/j256/ormlite/field/types/TimeStampType;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     invoke-direct {v0, v1, v2, v3}, Lcom/j256/ormlite/field/DataType;-><init>(Ljava/lang/String;ILcom/j256/ormlite/field/DataPersister;)V
a=0;// 
a=0;//     #v0=(Reference,Lcom/j256/ormlite/field/DataType;);
a=0;//     sput-object v0, Lcom/j256/ormlite/field/DataType;->TIME_STAMP:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     .line 213
a=0;//     new-instance v0, Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     #v0=(UninitRef,Lcom/j256/ormlite/field/DataType;);
a=0;//     const-string v1, "UNKNOWN"
a=0;// 
a=0;//     const/16 v2, 0x21
a=0;// 
a=0;//     const/4 v3, 0x0
a=0;// 
a=0;//     #v3=(Null);
a=0;//     invoke-direct {v0, v1, v2, v3}, Lcom/j256/ormlite/field/DataType;-><init>(Ljava/lang/String;ILcom/j256/ormlite/field/DataPersister;)V
a=0;// 
a=0;//     #v0=(Reference,Lcom/j256/ormlite/field/DataType;);
a=0;//     sput-object v0, Lcom/j256/ormlite/field/DataType;->UNKNOWN:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     .line 45
a=0;//     const/16 v0, 0x22
a=0;// 
a=0;//     #v0=(PosByte);
a=0;//     new-array v0, v0, [Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     #v0=(Reference,[Lcom/j256/ormlite/field/DataType;);
a=0;//     sget-object v1, Lcom/j256/ormlite/field/DataType;->STRING:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     aput-object v1, v0, v4
a=0;// 
a=0;//     sget-object v1, Lcom/j256/ormlite/field/DataType;->LONG_STRING:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     aput-object v1, v0, v5
a=0;// 
a=0;//     sget-object v1, Lcom/j256/ormlite/field/DataType;->STRING_BYTES:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     aput-object v1, v0, v6
a=0;// 
a=0;//     sget-object v1, Lcom/j256/ormlite/field/DataType;->BOOLEAN:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     aput-object v1, v0, v7
a=0;// 
a=0;//     sget-object v1, Lcom/j256/ormlite/field/DataType;->BOOLEAN_OBJ:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     aput-object v1, v0, v8
a=0;// 
a=0;//     const/4 v1, 0x5
a=0;// 
a=0;//     #v1=(PosByte);
a=0;//     sget-object v2, Lcom/j256/ormlite/field/DataType;->DATE:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     #v2=(Reference,Lcom/j256/ormlite/field/DataType;);
a=0;//     aput-object v2, v0, v1
a=0;// 
a=0;//     const/4 v1, 0x6
a=0;// 
a=0;//     sget-object v2, Lcom/j256/ormlite/field/DataType;->DATE_LONG:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     aput-object v2, v0, v1
a=0;// 
a=0;//     const/4 v1, 0x7
a=0;// 
a=0;//     sget-object v2, Lcom/j256/ormlite/field/DataType;->DATE_STRING:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     aput-object v2, v0, v1
a=0;// 
a=0;//     const/16 v1, 0x8
a=0;// 
a=0;//     sget-object v2, Lcom/j256/ormlite/field/DataType;->CHAR:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     aput-object v2, v0, v1
a=0;// 
a=0;//     const/16 v1, 0x9
a=0;// 
a=0;//     sget-object v2, Lcom/j256/ormlite/field/DataType;->CHAR_OBJ:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     aput-object v2, v0, v1
a=0;// 
a=0;//     const/16 v1, 0xa
a=0;// 
a=0;//     sget-object v2, Lcom/j256/ormlite/field/DataType;->BYTE:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     aput-object v2, v0, v1
a=0;// 
a=0;//     const/16 v1, 0xb
a=0;// 
a=0;//     sget-object v2, Lcom/j256/ormlite/field/DataType;->BYTE_ARRAY:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     aput-object v2, v0, v1
a=0;// 
a=0;//     const/16 v1, 0xc
a=0;// 
a=0;//     sget-object v2, Lcom/j256/ormlite/field/DataType;->BYTE_OBJ:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     aput-object v2, v0, v1
a=0;// 
a=0;//     const/16 v1, 0xd
a=0;// 
a=0;//     sget-object v2, Lcom/j256/ormlite/field/DataType;->SHORT:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     aput-object v2, v0, v1
a=0;// 
a=0;//     const/16 v1, 0xe
a=0;// 
a=0;//     sget-object v2, Lcom/j256/ormlite/field/DataType;->SHORT_OBJ:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     aput-object v2, v0, v1
a=0;// 
a=0;//     const/16 v1, 0xf
a=0;// 
a=0;//     sget-object v2, Lcom/j256/ormlite/field/DataType;->INTEGER:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     aput-object v2, v0, v1
a=0;// 
a=0;//     const/16 v1, 0x10
a=0;// 
a=0;//     sget-object v2, Lcom/j256/ormlite/field/DataType;->INTEGER_OBJ:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     aput-object v2, v0, v1
a=0;// 
a=0;//     const/16 v1, 0x11
a=0;// 
a=0;//     sget-object v2, Lcom/j256/ormlite/field/DataType;->LONG:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     aput-object v2, v0, v1
a=0;// 
a=0;//     const/16 v1, 0x12
a=0;// 
a=0;//     sget-object v2, Lcom/j256/ormlite/field/DataType;->LONG_OBJ:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     aput-object v2, v0, v1
a=0;// 
a=0;//     const/16 v1, 0x13
a=0;// 
a=0;//     sget-object v2, Lcom/j256/ormlite/field/DataType;->FLOAT:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     aput-object v2, v0, v1
a=0;// 
a=0;//     const/16 v1, 0x14
a=0;// 
a=0;//     sget-object v2, Lcom/j256/ormlite/field/DataType;->FLOAT_OBJ:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     aput-object v2, v0, v1
a=0;// 
a=0;//     const/16 v1, 0x15
a=0;// 
a=0;//     sget-object v2, Lcom/j256/ormlite/field/DataType;->DOUBLE:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     aput-object v2, v0, v1
a=0;// 
a=0;//     const/16 v1, 0x16
a=0;// 
a=0;//     sget-object v2, Lcom/j256/ormlite/field/DataType;->DOUBLE_OBJ:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     aput-object v2, v0, v1
a=0;// 
a=0;//     const/16 v1, 0x17
a=0;// 
a=0;//     sget-object v2, Lcom/j256/ormlite/field/DataType;->SERIALIZABLE:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     aput-object v2, v0, v1
a=0;// 
a=0;//     const/16 v1, 0x18
a=0;// 
a=0;//     sget-object v2, Lcom/j256/ormlite/field/DataType;->ENUM_STRING:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     aput-object v2, v0, v1
a=0;// 
a=0;//     const/16 v1, 0x19
a=0;// 
a=0;//     sget-object v2, Lcom/j256/ormlite/field/DataType;->ENUM_INTEGER:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     aput-object v2, v0, v1
a=0;// 
a=0;//     const/16 v1, 0x1a
a=0;// 
a=0;//     sget-object v2, Lcom/j256/ormlite/field/DataType;->UUID:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     aput-object v2, v0, v1
a=0;// 
a=0;//     const/16 v1, 0x1b
a=0;// 
a=0;//     sget-object v2, Lcom/j256/ormlite/field/DataType;->BIG_INTEGER:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     aput-object v2, v0, v1
a=0;// 
a=0;//     const/16 v1, 0x1c
a=0;// 
a=0;//     sget-object v2, Lcom/j256/ormlite/field/DataType;->BIG_DECIMAL:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     aput-object v2, v0, v1
a=0;// 
a=0;//     const/16 v1, 0x1d
a=0;// 
a=0;//     sget-object v2, Lcom/j256/ormlite/field/DataType;->BIG_DECIMAL_NUMERIC:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     aput-object v2, v0, v1
a=0;// 
a=0;//     const/16 v1, 0x1e
a=0;// 
a=0;//     sget-object v2, Lcom/j256/ormlite/field/DataType;->DATE_TIME:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     aput-object v2, v0, v1
a=0;// 
a=0;//     const/16 v1, 0x1f
a=0;// 
a=0;//     sget-object v2, Lcom/j256/ormlite/field/DataType;->SQL_DATE:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     aput-object v2, v0, v1
a=0;// 
a=0;//     const/16 v1, 0x20
a=0;// 
a=0;//     sget-object v2, Lcom/j256/ormlite/field/DataType;->TIME_STAMP:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     aput-object v2, v0, v1
a=0;// 
a=0;//     const/16 v1, 0x21
a=0;// 
a=0;//     sget-object v2, Lcom/j256/ormlite/field/DataType;->UNKNOWN:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     aput-object v2, v0, v1
a=0;// 
a=0;//     sput-object v0, Lcom/j256/ormlite/field/DataType;->$VALUES:[Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method private constructor <init>(Ljava/lang/String;ILcom/j256/ormlite/field/DataPersister;)V
a=0;//     .locals 0
a=0;//     .param p3, "dataPersister"    # Lcom/j256/ormlite/field/DataPersister;
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "(",
a=0;//             "Lcom/j256/ormlite/field/DataPersister;",
a=0;//             ")V"
a=0;//         }
a=0;//     .end annotation
a=0;// 
a=0;//     .prologue
a=0;//     .line 219
a=0;//     invoke-direct {p0, p1, p2}, Ljava/lang/Enum;-><init>(Ljava/lang/String;I)V
a=0;// 
a=0;//     .line 220
a=0;//     #p0=(Reference,Lcom/j256/ormlite/field/DataType;);
a=0;//     iput-object p3, p0, Lcom/j256/ormlite/field/DataType;->dataPersister:Lcom/j256/ormlite/field/DataPersister;
a=0;// 
a=0;//     .line 221
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static valueOf(Ljava/lang/String;)Lcom/j256/ormlite/field/DataType;
a=0;//     .locals 1
a=0;//     .param p0, "name"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 45
a=0;//     const-class v0, Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/Class;);
a=0;//     invoke-static {v0, p0}, Ljava/lang/Enum;->valueOf(Ljava/lang/Class;Ljava/lang/String;)Ljava/lang/Enum;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     check-cast v0, Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public static values()[Lcom/j256/ormlite/field/DataType;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 45
a=0;//     sget-object v0, Lcom/j256/ormlite/field/DataType;->$VALUES:[Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     #v0=(Reference,[Lcom/j256/ormlite/field/DataType;);
a=0;//     invoke-virtual {v0}, [Lcom/j256/ormlite/field/DataType;->clone()Ljava/lang/Object;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     check-cast v0, [Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public getDataPersister()Lcom/j256/ormlite/field/DataPersister;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 224
a=0;//     iget-object v0, p0, Lcom/j256/ormlite/field/DataType;->dataPersister:Lcom/j256/ormlite/field/DataPersister;
a=0;// 
a=0;//     #v0=(Reference,Lcom/j256/ormlite/field/DataPersister;);
a=0;//     return-object v0
a=0;// .end method
}}
