package com.j256.ormlite.field; class DatabaseFieldConfig { void a() { int a;
a=0;// .class public Lcom/j256/ormlite/field/DatabaseFieldConfig;
a=0;// .super Ljava/lang/Object;
a=0;// .source "DatabaseFieldConfig.java"
a=0;// 
a=0;// 
a=0;// # static fields
a=0;// .field public static final DEFAULT_CAN_BE_NULL:Z = true
a=0;// 
a=0;// .field public static final DEFAULT_DATA_TYPE:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;// .field public static final DEFAULT_FOREIGN_COLLECTION_ORDER_ASCENDING:Z = true
a=0;// 
a=0;// .field private static final DEFAULT_MAX_EAGER_FOREIGN_COLLECTION_LEVEL:I = 0x1
a=0;// 
a=0;// .field public static final DEFAULT_PERSISTER_CLASS:Ljava/lang/Class;
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "Ljava/lang/Class",
a=0;//             "<+",
a=0;//             "Lcom/j256/ormlite/field/DataPersister;",
a=0;//             ">;"
a=0;//         }
a=0;//     .end annotation
a=0;// .end field
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field private allowGeneratedIdInsert:Z
a=0;// 
a=0;// .field private canBeNull:Z
a=0;// 
a=0;// .field private columnDefinition:Ljava/lang/String;
a=0;// 
a=0;// .field private columnName:Ljava/lang/String;
a=0;// 
a=0;// .field private dataPersister:Lcom/j256/ormlite/field/DataPersister;
a=0;// 
a=0;// .field private dataType:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;// .field private defaultValue:Ljava/lang/String;
a=0;// 
a=0;// .field private fieldName:Ljava/lang/String;
a=0;// 
a=0;// .field private foreign:Z
a=0;// 
a=0;// .field private foreignAutoCreate:Z
a=0;// 
a=0;// .field private foreignAutoRefresh:Z
a=0;// 
a=0;// .field private foreignCollection:Z
a=0;// 
a=0;// .field private foreignCollectionColumnName:Ljava/lang/String;
a=0;// 
a=0;// .field private foreignCollectionEager:Z
a=0;// 
a=0;// .field private foreignCollectionForeignFieldName:Ljava/lang/String;
a=0;// 
a=0;// .field private foreignCollectionMaxEagerLevel:I
a=0;// 
a=0;// .field private foreignCollectionOrderAscending:Z
a=0;// 
a=0;// .field private foreignCollectionOrderColumnName:Ljava/lang/String;
a=0;// 
a=0;// .field private foreignColumnName:Ljava/lang/String;
a=0;// 
a=0;// .field private foreignTableConfig:Lcom/j256/ormlite/table/DatabaseTableConfig;
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "Lcom/j256/ormlite/table/DatabaseTableConfig",
a=0;//             "<*>;"
a=0;//         }
a=0;//     .end annotation
a=0;// .end field
a=0;// 
a=0;// .field private format:Ljava/lang/String;
a=0;// 
a=0;// .field private generatedId:Z
a=0;// 
a=0;// .field private generatedIdSequence:Ljava/lang/String;
a=0;// 
a=0;// .field private id:Z
a=0;// 
a=0;// .field private index:Z
a=0;// 
a=0;// .field private indexName:Ljava/lang/String;
a=0;// 
a=0;// .field private maxForeignAutoRefreshLevel:I
a=0;// 
a=0;// .field private persisted:Z
a=0;// 
a=0;// .field private persisterClass:Ljava/lang/Class;
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "Ljava/lang/Class",
a=0;//             "<+",
a=0;//             "Lcom/j256/ormlite/field/DataPersister;",
a=0;//             ">;"
a=0;//         }
a=0;//     .end annotation
a=0;// .end field
a=0;// 
a=0;// .field private throwIfNull:Z
a=0;// 
a=0;// .field private unique:Z
a=0;// 
a=0;// .field private uniqueCombo:Z
a=0;// 
a=0;// .field private uniqueIndex:Z
a=0;// 
a=0;// .field private uniqueIndexName:Ljava/lang/String;
a=0;// 
a=0;// .field private unknownEnumValue:Ljava/lang/Enum;
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "Ljava/lang/Enum",
a=0;//             "<*>;"
a=0;//         }
a=0;//     .end annotation
a=0;// .end field
a=0;// 
a=0;// .field private useGetSet:Z
a=0;// 
a=0;// .field private version:Z
a=0;// 
a=0;// .field private width:I
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method static constructor <clinit>()V
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 21
a=0;//     const-class v0, Lcom/j256/ormlite/field/types/VoidType;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/Class;);
a=0;//     sput-object v0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->DEFAULT_PERSISTER_CLASS:Ljava/lang/Class;
a=0;// 
a=0;//     .line 22
a=0;//     sget-object v0, Lcom/j256/ormlite/field/DataType;->UNKNOWN:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     sput-object v0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->DEFAULT_DATA_TYPE:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public constructor <init>()V
a=0;//     .locals 2
a=0;// 
a=0;//     .prologue
a=0;//     const/4 v1, 0x1
a=0;// 
a=0;//     .line 66
a=0;//     #v1=(One);
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     .line 28
a=0;//     #p0=(Reference,Lcom/j256/ormlite/field/DatabaseFieldConfig;);
a=0;//     sget-object v0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->DEFAULT_DATA_TYPE:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     #v0=(Reference,Lcom/j256/ormlite/field/DataType;);
a=0;//     iput-object v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->dataType:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     .line 32
a=0;//     iput-boolean v1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->canBeNull:Z
a=0;// 
a=0;//     .line 41
a=0;//     iput-boolean v1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->persisted:Z
a=0;// 
a=0;//     .line 50
a=0;//     const/4 v0, -0x1
a=0;// 
a=0;//     #v0=(Byte);
a=0;//     iput v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->maxForeignAutoRefreshLevel:I
a=0;// 
a=0;//     .line 51
a=0;//     sget-object v0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->DEFAULT_PERSISTER_CLASS:Ljava/lang/Class;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/Class;);
a=0;//     iput-object v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->persisterClass:Ljava/lang/Class;
a=0;// 
a=0;//     .line 60
a=0;//     iput v1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->foreignCollectionMaxEagerLevel:I
a=0;// 
a=0;//     .line 63
a=0;//     iput-boolean v1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->foreignCollectionOrderAscending:Z
a=0;// 
a=0;//     .line 68
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public constructor <init>(Ljava/lang/String;)V
a=0;//     .locals 2
a=0;//     .param p1, "fieldName"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     const/4 v1, 0x1
a=0;// 
a=0;//     .line 70
a=0;//     #v1=(One);
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     .line 28
a=0;//     #p0=(Reference,Lcom/j256/ormlite/field/DatabaseFieldConfig;);
a=0;//     sget-object v0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->DEFAULT_DATA_TYPE:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     #v0=(Reference,Lcom/j256/ormlite/field/DataType;);
a=0;//     iput-object v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->dataType:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     .line 32
a=0;//     iput-boolean v1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->canBeNull:Z
a=0;// 
a=0;//     .line 41
a=0;//     iput-boolean v1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->persisted:Z
a=0;// 
a=0;//     .line 50
a=0;//     const/4 v0, -0x1
a=0;// 
a=0;//     #v0=(Byte);
a=0;//     iput v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->maxForeignAutoRefreshLevel:I
a=0;// 
a=0;//     .line 51
a=0;//     sget-object v0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->DEFAULT_PERSISTER_CLASS:Ljava/lang/Class;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/Class;);
a=0;//     iput-object v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->persisterClass:Ljava/lang/Class;
a=0;// 
a=0;//     .line 60
a=0;//     iput v1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->foreignCollectionMaxEagerLevel:I
a=0;// 
a=0;//     .line 63
a=0;//     iput-boolean v1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->foreignCollectionOrderAscending:Z
a=0;// 
a=0;//     .line 71
a=0;//     iput-object p1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->fieldName:Ljava/lang/String;
a=0;// 
a=0;//     .line 72
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public constructor <init>(Ljava/lang/String;Ljava/lang/String;Lcom/j256/ormlite/field/DataType;Ljava/lang/String;IZZZLjava/lang/String;ZLcom/j256/ormlite/table/DatabaseTableConfig;ZLjava/lang/Enum;ZLjava/lang/String;ZLjava/lang/String;Ljava/lang/String;ZII)V
a=0;//     .locals 2
a=0;//     .param p1, "fieldName"    # Ljava/lang/String;
a=0;//     .param p2, "columnName"    # Ljava/lang/String;
a=0;//     .param p3, "dataType"    # Lcom/j256/ormlite/field/DataType;
a=0;//     .param p4, "defaultValue"    # Ljava/lang/String;
a=0;//     .param p5, "width"    # I
a=0;//     .param p6, "canBeNull"    # Z
a=0;//     .param p7, "id"    # Z
a=0;//     .param p8, "generatedId"    # Z
a=0;//     .param p9, "generatedIdSequence"    # Ljava/lang/String;
a=0;//     .param p10, "foreign"    # Z
a=0;//     .param p12, "useGetSet"    # Z
a=0;//     .param p14, "throwIfNull"    # Z
a=0;//     .param p15, "format"    # Ljava/lang/String;
a=0;//     .param p16, "unique"    # Z
a=0;//     .param p17, "indexName"    # Ljava/lang/String;
a=0;//     .param p18, "uniqueIndexName"    # Ljava/lang/String;
a=0;//     .param p19, "autoRefresh"    # Z
a=0;//     .param p20, "maxForeignAutoRefreshLevel"    # I
a=0;//     .param p21, "maxForeignCollectionLevel"    # I
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "(",
a=0;//             "Ljava/lang/String;",
a=0;//             "Ljava/lang/String;",
a=0;//             "Lcom/j256/ormlite/field/DataType;",
a=0;//             "Ljava/lang/String;",
a=0;//             "IZZZ",
a=0;//             "Ljava/lang/String;",
a=0;//             "Z",
a=0;//             "Lcom/j256/ormlite/table/DatabaseTableConfig",
a=0;//             "<*>;Z",
a=0;//             "Ljava/lang/Enum",
a=0;//             "<*>;Z",
a=0;//             "Ljava/lang/String;",
a=0;//             "Z",
a=0;//             "Ljava/lang/String;",
a=0;//             "Ljava/lang/String;",
a=0;//             "ZII)V"
a=0;//         }
a=0;//     .end annotation
a=0;// 
a=0;//     .prologue
a=0;//     .line 78
a=0;//     .local p11, "foreignTableConfig":Lcom/j256/ormlite/table/DatabaseTableConfig;, "Lcom/j256/ormlite/table/DatabaseTableConfig<*>;"
a=0;//     .local p13, "unknownEnumValue":Ljava/lang/Enum;, "Ljava/lang/Enum<*>;"
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     .line 28
a=0;//     #p0=(Reference,Lcom/j256/ormlite/field/DatabaseFieldConfig;);
a=0;//     sget-object v1, Lcom/j256/ormlite/field/DatabaseFieldConfig;->DEFAULT_DATA_TYPE:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     #v1=(Reference,Lcom/j256/ormlite/field/DataType;);
a=0;//     iput-object v1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->dataType:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     .line 32
a=0;//     const/4 v1, 0x1
a=0;// 
a=0;//     #v1=(One);
a=0;//     iput-boolean v1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->canBeNull:Z
a=0;// 
a=0;//     .line 41
a=0;//     const/4 v1, 0x1
a=0;// 
a=0;//     iput-boolean v1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->persisted:Z
a=0;// 
a=0;//     .line 50
a=0;//     const/4 v1, -0x1
a=0;// 
a=0;//     #v1=(Byte);
a=0;//     iput v1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->maxForeignAutoRefreshLevel:I
a=0;// 
a=0;//     .line 51
a=0;//     sget-object v1, Lcom/j256/ormlite/field/DatabaseFieldConfig;->DEFAULT_PERSISTER_CLASS:Ljava/lang/Class;
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/Class;);
a=0;//     iput-object v1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->persisterClass:Ljava/lang/Class;
a=0;// 
a=0;//     .line 60
a=0;//     const/4 v1, 0x1
a=0;// 
a=0;//     #v1=(One);
a=0;//     iput v1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->foreignCollectionMaxEagerLevel:I
a=0;// 
a=0;//     .line 63
a=0;//     const/4 v1, 0x1
a=0;// 
a=0;//     iput-boolean v1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->foreignCollectionOrderAscending:Z
a=0;// 
a=0;//     .line 79
a=0;//     iput-object p1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->fieldName:Ljava/lang/String;
a=0;// 
a=0;//     .line 80
a=0;//     iput-object p2, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->columnName:Ljava/lang/String;
a=0;// 
a=0;//     .line 81
a=0;//     sget-object v1, Lcom/j256/ormlite/field/DataType;->UNKNOWN:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     #v1=(Reference,Lcom/j256/ormlite/field/DataType;);
a=0;//     iput-object v1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->dataType:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     .line 82
a=0;//     iput-object p4, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->defaultValue:Ljava/lang/String;
a=0;// 
a=0;//     .line 83
a=0;//     iput p5, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->width:I
a=0;// 
a=0;//     .line 84
a=0;//     iput-boolean p6, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->canBeNull:Z
a=0;// 
a=0;//     .line 85
a=0;//     iput-boolean p7, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->id:Z
a=0;// 
a=0;//     .line 86
a=0;//     iput-boolean p8, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->generatedId:Z
a=0;// 
a=0;//     .line 87
a=0;//     iput-object p9, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->generatedIdSequence:Ljava/lang/String;
a=0;// 
a=0;//     .line 88
a=0;//     iput-boolean p10, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->foreign:Z
a=0;// 
a=0;//     .line 89
a=0;//     iput-object p11, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->foreignTableConfig:Lcom/j256/ormlite/table/DatabaseTableConfig;
a=0;// 
a=0;//     .line 90
a=0;//     iput-boolean p12, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->useGetSet:Z
a=0;// 
a=0;//     .line 91
a=0;//     iput-object p13, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->unknownEnumValue:Ljava/lang/Enum;
a=0;// 
a=0;//     .line 92
a=0;//     move/from16 v0, p14
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     iput-boolean v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->throwIfNull:Z
a=0;// 
a=0;//     .line 93
a=0;//     move-object/from16 v0, p15
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     iput-object v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->format:Ljava/lang/String;
a=0;// 
a=0;//     .line 94
a=0;//     move/from16 v0, p16
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     iput-boolean v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->unique:Z
a=0;// 
a=0;//     .line 95
a=0;//     move-object/from16 v0, p17
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     iput-object v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->indexName:Ljava/lang/String;
a=0;// 
a=0;//     .line 96
a=0;//     move-object/from16 v0, p18
a=0;// 
a=0;//     iput-object v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->uniqueIndexName:Ljava/lang/String;
a=0;// 
a=0;//     .line 97
a=0;//     move/from16 v0, p19
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     iput-boolean v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->foreignAutoRefresh:Z
a=0;// 
a=0;//     .line 98
a=0;//     move/from16 v0, p20
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     iput v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->maxForeignAutoRefreshLevel:I
a=0;// 
a=0;//     .line 99
a=0;//     move/from16 v0, p21
a=0;// 
a=0;//     iput v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->foreignCollectionMaxEagerLevel:I
a=0;// 
a=0;//     .line 100
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static findGetMethod(Ljava/lang/reflect/Field;Z)Ljava/lang/reflect/Method;
a=0;//     .locals 6
a=0;//     .param p0, "field"    # Ljava/lang/reflect/Field;
a=0;//     .param p1, "throwExceptions"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     const/4 v3, 0x0
a=0;// 
a=0;//     .line 533
a=0;//     #v3=(Null);
a=0;//     const-string v4, "get"
a=0;// 
a=0;//     #v4=(Reference,Ljava/lang/String;);
a=0;//     invoke-static {p0, v4}, Lcom/j256/ormlite/field/DatabaseFieldConfig;->methodFromField(Ljava/lang/reflect/Field;Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     .line 536
a=0;//     .local v2, "methodName":Ljava/lang/String;
a=0;//     :try_start_0
a=0;//     #v2=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {p0}, Ljava/lang/reflect/Field;->getDeclaringClass()Ljava/lang/Class;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     const/4 v5, 0x0
a=0;// 
a=0;//     #v5=(Null);
a=0;//     new-array v5, v5, [Ljava/lang/Class;
a=0;// 
a=0;//     #v5=(Reference,[Ljava/lang/Class;);
a=0;//     invoke-virtual {v4, v2, v5}, Ljava/lang/Class;->getMethod(Ljava/lang/String;[Ljava/lang/Class;)Ljava/lang/reflect/Method;
a=0;//     :try_end_0
a=0;//     .catch Ljava/lang/Exception; {:try_start_0 .. :try_end_0} :catch_0
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     .line 544
a=0;//     .local v1, "fieldGetMethod":Ljava/lang/reflect/Method;
a=0;//     #v1=(Reference,Ljava/lang/reflect/Method;);
a=0;//     invoke-virtual {v1}, Ljava/lang/reflect/Method;->getReturnType()Ljava/lang/Class;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-virtual {p0}, Ljava/lang/reflect/Field;->getType()Ljava/lang/Class;
a=0;// 
a=0;//     move-result-object v5
a=0;// 
a=0;//     if-eq v4, v5, :cond_1
a=0;// 
a=0;//     .line 545
a=0;//     if-eqz p1, :cond_2
a=0;// 
a=0;//     .line 546
a=0;//     new-instance v3, Ljava/lang/IllegalArgumentException;
a=0;// 
a=0;//     #v3=(UninitRef,Ljava/lang/IllegalArgumentException;);
a=0;//     new-instance v4, Ljava/lang/StringBuilder;
a=0;// 
a=0;//     #v4=(UninitRef,Ljava/lang/StringBuilder;);
a=0;//     invoke-direct {v4}, Ljava/lang/StringBuilder;-><init>()V
a=0;// 
a=0;//     #v4=(Reference,Ljava/lang/StringBuilder;);
a=0;//     const-string v5, "Return type of get method "
a=0;// 
a=0;//     invoke-virtual {v4, v5}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-virtual {v4, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     const-string v5, " does not return "
a=0;// 
a=0;//     invoke-virtual {v4, v5}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-virtual {p0}, Ljava/lang/reflect/Field;->getType()Ljava/lang/Class;
a=0;// 
a=0;//     move-result-object v5
a=0;// 
a=0;//     invoke-virtual {v4, v5}, Ljava/lang/StringBuilder;->append(Ljava/lang/Object;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-virtual {v4}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-direct {v3, v4}, Ljava/lang/IllegalArgumentException;-><init>(Ljava/lang/String;)V
a=0;// 
a=0;//     #v3=(Reference,Ljava/lang/IllegalArgumentException;);
a=0;//     throw v3
a=0;// 
a=0;//     .line 537
a=0;//     .end local v1    # "fieldGetMethod":Ljava/lang/reflect/Method;
a=0;//     :catch_0
a=0;//     #v1=(Uninit);v3=(Null);v5=(Conflicted);
a=0;//     move-exception v0
a=0;// 
a=0;//     .line 538
a=0;//     .local v0, "e":Ljava/lang/Exception;
a=0;//     #v0=(Reference,Ljava/lang/Exception;);
a=0;//     if-eqz p1, :cond_0
a=0;// 
a=0;//     .line 539
a=0;//     new-instance v3, Ljava/lang/IllegalArgumentException;
a=0;// 
a=0;//     #v3=(UninitRef,Ljava/lang/IllegalArgumentException;);
a=0;//     new-instance v4, Ljava/lang/StringBuilder;
a=0;// 
a=0;//     #v4=(UninitRef,Ljava/lang/StringBuilder;);
a=0;//     invoke-direct {v4}, Ljava/lang/StringBuilder;-><init>()V
a=0;// 
a=0;//     #v4=(Reference,Ljava/lang/StringBuilder;);
a=0;//     const-string v5, "Could not find appropriate get method for "
a=0;// 
a=0;//     #v5=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v4, v5}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-virtual {v4, p0}, Ljava/lang/StringBuilder;->append(Ljava/lang/Object;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-virtual {v4}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-direct {v3, v4}, Ljava/lang/IllegalArgumentException;-><init>(Ljava/lang/String;)V
a=0;// 
a=0;//     #v3=(Reference,Ljava/lang/IllegalArgumentException;);
a=0;//     throw v3
a=0;// 
a=0;//     :cond_0
a=0;//     #v3=(Null);v5=(Conflicted);
a=0;//     move-object v1, v3
a=0;// 
a=0;//     .line 552
a=0;//     .end local v0    # "e":Ljava/lang/Exception;
a=0;//     :cond_1
a=0;//     :goto_0
a=0;//     #v0=(Conflicted);v1=(Reference,Ljava/lang/reflect/Method;);
a=0;//     return-object v1
a=0;// 
a=0;//     .restart local v1    # "fieldGetMethod":Ljava/lang/reflect/Method;
a=0;//     :cond_2
a=0;//     #v0=(Uninit);v5=(Reference,Ljava/lang/Class;);
a=0;//     move-object v1, v3
a=0;// 
a=0;//     .line 549
a=0;//     #v1=(Null);
a=0;//     goto :goto_0
a=0;// .end method
a=0;// 
a=0;// .method private findIndexName(Ljava/lang/String;)Ljava/lang/String;
a=0;//     .locals 2
a=0;//     .param p1, "tableName"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 690
a=0;//     iget-object v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->columnName:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     if-nez v0, :cond_0
a=0;// 
a=0;//     .line 691
a=0;//     new-instance v0, Ljava/lang/StringBuilder;
a=0;// 
a=0;//     #v0=(UninitRef,Ljava/lang/StringBuilder;);
a=0;//     invoke-direct {v0}, Ljava/lang/StringBuilder;-><init>()V
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/StringBuilder;);
a=0;//     invoke-virtual {v0, p1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, "_"
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->fieldName:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, "_idx"
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 693
a=0;//     :goto_0
a=0;//     return-object v0
a=0;// 
a=0;//     :cond_0
a=0;//     #v1=(Uninit);
a=0;//     new-instance v0, Ljava/lang/StringBuilder;
a=0;// 
a=0;//     #v0=(UninitRef,Ljava/lang/StringBuilder;);
a=0;//     invoke-direct {v0}, Ljava/lang/StringBuilder;-><init>()V
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/StringBuilder;);
a=0;//     invoke-virtual {v0, p1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, "_"
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->columnName:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, "_idx"
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     goto :goto_0
a=0;// .end method
a=0;// 
a=0;// .method public static findMatchingEnumVal(Ljava/lang/reflect/Field;Ljava/lang/String;)Ljava/lang/Enum;
a=0;//     .locals 7
a=0;//     .param p0, "field"    # Ljava/lang/reflect/Field;
a=0;//     .param p1, "unknownEnumName"    # Ljava/lang/String;
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "(",
a=0;//             "Ljava/lang/reflect/Field;",
a=0;//             "Ljava/lang/String;",
a=0;//             ")",
a=0;//             "Ljava/lang/Enum",
a=0;//             "<*>;"
a=0;//         }
a=0;//     .end annotation
a=0;// 
a=0;//     .prologue
a=0;//     .line 648
a=0;//     if-eqz p1, :cond_0
a=0;// 
a=0;//     invoke-virtual {p1}, Ljava/lang/String;->length()I
a=0;// 
a=0;//     move-result v4
a=0;// 
a=0;//     #v4=(Integer);
a=0;//     if-nez v4, :cond_2
a=0;// 
a=0;//     .line 649
a=0;//     :cond_0
a=0;//     #v4=(Conflicted);
a=0;//     const/4 v1, 0x0
a=0;// 
a=0;//     .line 653
a=0;//     :cond_1
a=0;//     #v0=(Conflicted);v1=(Null);v2=(Conflicted);v3=(Conflicted);
a=0;//     return-object v1
a=0;// 
a=0;//     .line 651
a=0;//     :cond_2
a=0;//     #v0=(Uninit);v1=(Uninit);v2=(Uninit);v3=(Uninit);v4=(Integer);
a=0;//     invoke-virtual {p0}, Ljava/lang/reflect/Field;->getType()Ljava/lang/Class;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     #v4=(Reference,Ljava/lang/Class;);
a=0;//     invoke-virtual {v4}, Ljava/lang/Class;->getEnumConstants()[Ljava/lang/Object;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     check-cast v4, [Ljava/lang/Enum;
a=0;// 
a=0;//     move-object v0, v4
a=0;// 
a=0;//     #v0=(Reference,[Ljava/lang/Enum;);
a=0;//     check-cast v0, [Ljava/lang/Enum;
a=0;// 
a=0;//     .local v0, "arr$":[Ljava/lang/Enum;
a=0;//     array-length v3, v0
a=0;// 
a=0;//     .local v3, "len$":I
a=0;//     #v3=(Integer);
a=0;//     const/4 v2, 0x0
a=0;// 
a=0;//     .local v2, "i$":I
a=0;//     :goto_0
a=0;//     #v1=(Conflicted);v2=(Integer);v4=(Conflicted);
a=0;//     if-ge v2, v3, :cond_3
a=0;// 
a=0;//     aget-object v1, v0, v2
a=0;// 
a=0;//     .line 652
a=0;//     .local v1, "enumVal":Ljava/lang/Enum;, "Ljava/lang/Enum<*>;"
a=0;//     #v1=(Null);
a=0;//     invoke-virtual {v1}, Ljava/lang/Enum;->name()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     #v4=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v4, p1}, Ljava/lang/String;->equals(Ljava/lang/Object;)Z
a=0;// 
a=0;//     move-result v4
a=0;// 
a=0;//     #v4=(Boolean);
a=0;//     if-nez v4, :cond_1
a=0;// 
a=0;//     .line 651
a=0;//     add-int/lit8 v2, v2, 0x1
a=0;// 
a=0;//     goto :goto_0
a=0;// 
a=0;//     .line 656
a=0;//     .end local v1    # "enumVal":Ljava/lang/Enum;, "Ljava/lang/Enum<*>;"
a=0;//     :cond_3
a=0;//     #v1=(Conflicted);v4=(Conflicted);
a=0;//     new-instance v4, Ljava/lang/IllegalArgumentException;
a=0;// 
a=0;//     #v4=(UninitRef,Ljava/lang/IllegalArgumentException;);
a=0;//     new-instance v5, Ljava/lang/StringBuilder;
a=0;// 
a=0;//     #v5=(UninitRef,Ljava/lang/StringBuilder;);
a=0;//     invoke-direct {v5}, Ljava/lang/StringBuilder;-><init>()V
a=0;// 
a=0;//     #v5=(Reference,Ljava/lang/StringBuilder;);
a=0;//     const-string v6, "Unknwown enum unknown name "
a=0;// 
a=0;//     #v6=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v5, v6}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v5
a=0;// 
a=0;//     invoke-virtual {v5, p1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v5
a=0;// 
a=0;//     const-string v6, " for field "
a=0;// 
a=0;//     invoke-virtual {v5, v6}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v5
a=0;// 
a=0;//     invoke-virtual {v5, p0}, Ljava/lang/StringBuilder;->append(Ljava/lang/Object;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v5
a=0;// 
a=0;//     invoke-virtual {v5}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v5
a=0;// 
a=0;//     invoke-direct {v4, v5}, Ljava/lang/IllegalArgumentException;-><init>(Ljava/lang/String;)V
a=0;// 
a=0;//     #v4=(Reference,Ljava/lang/IllegalArgumentException;);
a=0;//     throw v4
a=0;// .end method
a=0;// 
a=0;// .method public static findSetMethod(Ljava/lang/reflect/Field;Z)Ljava/lang/reflect/Method;
a=0;//     .locals 8
a=0;//     .param p0, "field"    # Ljava/lang/reflect/Field;
a=0;//     .param p1, "throwExceptions"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     const/4 v3, 0x0
a=0;// 
a=0;//     .line 561
a=0;//     #v3=(Null);
a=0;//     const-string v4, "set"
a=0;// 
a=0;//     #v4=(Reference,Ljava/lang/String;);
a=0;//     invoke-static {p0, v4}, Lcom/j256/ormlite/field/DatabaseFieldConfig;->methodFromField(Ljava/lang/reflect/Field;Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     .line 564
a=0;//     .local v2, "methodName":Ljava/lang/String;
a=0;//     :try_start_0
a=0;//     #v2=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {p0}, Ljava/lang/reflect/Field;->getDeclaringClass()Ljava/lang/Class;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     const/4 v5, 0x1
a=0;// 
a=0;//     #v5=(One);
a=0;//     new-array v5, v5, [Ljava/lang/Class;
a=0;// 
a=0;//     #v5=(Reference,[Ljava/lang/Class;);
a=0;//     const/4 v6, 0x0
a=0;// 
a=0;//     #v6=(Null);
a=0;//     invoke-virtual {p0}, Ljava/lang/reflect/Field;->getType()Ljava/lang/Class;
a=0;// 
a=0;//     move-result-object v7
a=0;// 
a=0;//     #v7=(Reference,Ljava/lang/Class;);
a=0;//     aput-object v7, v5, v6
a=0;// 
a=0;//     invoke-virtual {v4, v2, v5}, Ljava/lang/Class;->getMethod(Ljava/lang/String;[Ljava/lang/Class;)Ljava/lang/reflect/Method;
a=0;//     :try_end_0
a=0;//     .catch Ljava/lang/Exception; {:try_start_0 .. :try_end_0} :catch_0
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     .line 572
a=0;//     .local v1, "fieldSetMethod":Ljava/lang/reflect/Method;
a=0;//     #v1=(Reference,Ljava/lang/reflect/Method;);
a=0;//     invoke-virtual {v1}, Ljava/lang/reflect/Method;->getReturnType()Ljava/lang/Class;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     sget-object v5, Ljava/lang/Void;->TYPE:Ljava/lang/Class;
a=0;// 
a=0;//     if-eq v4, v5, :cond_1
a=0;// 
a=0;//     .line 573
a=0;//     if-eqz p1, :cond_2
a=0;// 
a=0;//     .line 574
a=0;//     new-instance v3, Ljava/lang/IllegalArgumentException;
a=0;// 
a=0;//     #v3=(UninitRef,Ljava/lang/IllegalArgumentException;);
a=0;//     new-instance v4, Ljava/lang/StringBuilder;
a=0;// 
a=0;//     #v4=(UninitRef,Ljava/lang/StringBuilder;);
a=0;//     invoke-direct {v4}, Ljava/lang/StringBuilder;-><init>()V
a=0;// 
a=0;//     #v4=(Reference,Ljava/lang/StringBuilder;);
a=0;//     const-string v5, "Return type of set method "
a=0;// 
a=0;//     invoke-virtual {v4, v5}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-virtual {v4, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     const-string v5, " returns "
a=0;// 
a=0;//     invoke-virtual {v4, v5}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-virtual {v1}, Ljava/lang/reflect/Method;->getReturnType()Ljava/lang/Class;
a=0;// 
a=0;//     move-result-object v5
a=0;// 
a=0;//     invoke-virtual {v4, v5}, Ljava/lang/StringBuilder;->append(Ljava/lang/Object;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     const-string v5, " instead of void"
a=0;// 
a=0;//     invoke-virtual {v4, v5}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-virtual {v4}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-direct {v3, v4}, Ljava/lang/IllegalArgumentException;-><init>(Ljava/lang/String;)V
a=0;// 
a=0;//     #v3=(Reference,Ljava/lang/IllegalArgumentException;);
a=0;//     throw v3
a=0;// 
a=0;//     .line 565
a=0;//     .end local v1    # "fieldSetMethod":Ljava/lang/reflect/Method;
a=0;//     :catch_0
a=0;//     #v1=(Uninit);v3=(Null);v5=(Conflicted);v6=(Conflicted);v7=(Conflicted);
a=0;//     move-exception v0
a=0;// 
a=0;//     .line 566
a=0;//     .local v0, "e":Ljava/lang/Exception;
a=0;//     #v0=(Reference,Ljava/lang/Exception;);
a=0;//     if-eqz p1, :cond_0
a=0;// 
a=0;//     .line 567
a=0;//     new-instance v3, Ljava/lang/IllegalArgumentException;
a=0;// 
a=0;//     #v3=(UninitRef,Ljava/lang/IllegalArgumentException;);
a=0;//     new-instance v4, Ljava/lang/StringBuilder;
a=0;// 
a=0;//     #v4=(UninitRef,Ljava/lang/StringBuilder;);
a=0;//     invoke-direct {v4}, Ljava/lang/StringBuilder;-><init>()V
a=0;// 
a=0;//     #v4=(Reference,Ljava/lang/StringBuilder;);
a=0;//     const-string v5, "Could not find appropriate set method for "
a=0;// 
a=0;//     #v5=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v4, v5}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-virtual {v4, p0}, Ljava/lang/StringBuilder;->append(Ljava/lang/Object;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-virtual {v4}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-direct {v3, v4}, Ljava/lang/IllegalArgumentException;-><init>(Ljava/lang/String;)V
a=0;// 
a=0;//     #v3=(Reference,Ljava/lang/IllegalArgumentException;);
a=0;//     throw v3
a=0;// 
a=0;//     :cond_0
a=0;//     #v3=(Null);v5=(Conflicted);
a=0;//     move-object v1, v3
a=0;// 
a=0;//     .line 580
a=0;//     .end local v0    # "e":Ljava/lang/Exception;
a=0;//     :cond_1
a=0;//     :goto_0
a=0;//     #v0=(Conflicted);v1=(Reference,Ljava/lang/reflect/Method;);
a=0;//     return-object v1
a=0;// 
a=0;//     .restart local v1    # "fieldSetMethod":Ljava/lang/reflect/Method;
a=0;//     :cond_2
a=0;//     #v0=(Uninit);v5=(Reference,Ljava/lang/Class;);v6=(Null);v7=(Reference,Ljava/lang/Class;);
a=0;//     move-object v1, v3
a=0;// 
a=0;//     .line 577
a=0;//     #v1=(Null);
a=0;//     goto :goto_0
a=0;// .end method
a=0;// 
a=0;// .method public static fromDatabaseField(Lcom/j256/ormlite/db/DatabaseType;Ljava/lang/String;Ljava/lang/reflect/Field;Lcom/j256/ormlite/field/DatabaseField;)Lcom/j256/ormlite/field/DatabaseFieldConfig;
a=0;//     .locals 3
a=0;//     .param p0, "databaseType"    # Lcom/j256/ormlite/db/DatabaseType;
a=0;//     .param p1, "tableName"    # Ljava/lang/String;
a=0;//     .param p2, "field"    # Ljava/lang/reflect/Field;
a=0;//     .param p3, "databaseField"    # Lcom/j256/ormlite/field/DatabaseField;
a=0;// 
a=0;//     .prologue
a=0;//     .line 585
a=0;//     new-instance v0, Lcom/j256/ormlite/field/DatabaseFieldConfig;
a=0;// 
a=0;//     #v0=(UninitRef,Lcom/j256/ormlite/field/DatabaseFieldConfig;);
a=0;//     invoke-direct {v0}, Lcom/j256/ormlite/field/DatabaseFieldConfig;-><init>()V
a=0;// 
a=0;//     .line 586
a=0;//     .local v0, "config":Lcom/j256/ormlite/field/DatabaseFieldConfig;
a=0;//     #v0=(Reference,Lcom/j256/ormlite/field/DatabaseFieldConfig;);
a=0;//     invoke-virtual {p2}, Ljava/lang/reflect/Field;->getName()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     #v2=(Reference,Ljava/lang/String;);
a=0;//     iput-object v2, v0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->fieldName:Ljava/lang/String;
a=0;// 
a=0;//     .line 587
a=0;//     invoke-interface {p0}, Lcom/j256/ormlite/db/DatabaseType;->isEntityNamesMustBeUpCase()Z
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Boolean);
a=0;//     if-eqz v2, :cond_0
a=0;// 
a=0;//     .line 588
a=0;//     iget-object v2, v0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->fieldName:Ljava/lang/String;
a=0;// 
a=0;//     #v2=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v2}, Ljava/lang/String;->toUpperCase()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     iput-object v2, v0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->fieldName:Ljava/lang/String;
a=0;// 
a=0;//     .line 590
a=0;//     :cond_0
a=0;//     #v2=(Conflicted);
a=0;//     invoke-interface {p3}, Lcom/j256/ormlite/field/DatabaseField;->columnName()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     #v2=(Reference,Ljava/lang/String;);
a=0;//     invoke-static {v2}, Lcom/j256/ormlite/field/DatabaseFieldConfig;->valueIfNotBlank(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     iput-object v2, v0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->columnName:Ljava/lang/String;
a=0;// 
a=0;//     .line 591
a=0;//     invoke-interface {p3}, Lcom/j256/ormlite/field/DatabaseField;->dataType()Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     iput-object v2, v0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->dataType:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     .line 593
a=0;//     invoke-interface {p3}, Lcom/j256/ormlite/field/DatabaseField;->defaultValue()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     .line 594
a=0;//     .local v1, "defaultValue":Ljava/lang/String;
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     const-string v2, "__ormlite__ no default value string was specified"
a=0;// 
a=0;//     invoke-virtual {v1, v2}, Ljava/lang/String;->equals(Ljava/lang/Object;)Z
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Boolean);
a=0;//     if-nez v2, :cond_1
a=0;// 
a=0;//     .line 595
a=0;//     iput-object v1, v0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->defaultValue:Ljava/lang/String;
a=0;// 
a=0;//     .line 597
a=0;//     :cond_1
a=0;//     invoke-interface {p3}, Lcom/j256/ormlite/field/DatabaseField;->width()I
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     iput v2, v0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->width:I
a=0;// 
a=0;//     .line 598
a=0;//     invoke-interface {p3}, Lcom/j256/ormlite/field/DatabaseField;->canBeNull()Z
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Boolean);
a=0;//     iput-boolean v2, v0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->canBeNull:Z
a=0;// 
a=0;//     .line 599
a=0;//     invoke-interface {p3}, Lcom/j256/ormlite/field/DatabaseField;->id()Z
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     iput-boolean v2, v0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->id:Z
a=0;// 
a=0;//     .line 600
a=0;//     invoke-interface {p3}, Lcom/j256/ormlite/field/DatabaseField;->generatedId()Z
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     iput-boolean v2, v0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->generatedId:Z
a=0;// 
a=0;//     .line 601
a=0;//     invoke-interface {p3}, Lcom/j256/ormlite/field/DatabaseField;->generatedIdSequence()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     #v2=(Reference,Ljava/lang/String;);
a=0;//     invoke-static {v2}, Lcom/j256/ormlite/field/DatabaseFieldConfig;->valueIfNotBlank(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     iput-object v2, v0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->generatedIdSequence:Ljava/lang/String;
a=0;// 
a=0;//     .line 602
a=0;//     invoke-interface {p3}, Lcom/j256/ormlite/field/DatabaseField;->foreign()Z
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Boolean);
a=0;//     iput-boolean v2, v0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->foreign:Z
a=0;// 
a=0;//     .line 603
a=0;//     invoke-interface {p3}, Lcom/j256/ormlite/field/DatabaseField;->useGetSet()Z
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     iput-boolean v2, v0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->useGetSet:Z
a=0;// 
a=0;//     .line 604
a=0;//     invoke-interface {p3}, Lcom/j256/ormlite/field/DatabaseField;->unknownEnumName()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     #v2=(Reference,Ljava/lang/String;);
a=0;//     invoke-static {p2, v2}, Lcom/j256/ormlite/field/DatabaseFieldConfig;->findMatchingEnumVal(Ljava/lang/reflect/Field;Ljava/lang/String;)Ljava/lang/Enum;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     iput-object v2, v0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->unknownEnumValue:Ljava/lang/Enum;
a=0;// 
a=0;//     .line 605
a=0;//     invoke-interface {p3}, Lcom/j256/ormlite/field/DatabaseField;->throwIfNull()Z
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Boolean);
a=0;//     iput-boolean v2, v0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->throwIfNull:Z
a=0;// 
a=0;//     .line 606
a=0;//     invoke-interface {p3}, Lcom/j256/ormlite/field/DatabaseField;->format()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     #v2=(Reference,Ljava/lang/String;);
a=0;//     invoke-static {v2}, Lcom/j256/ormlite/field/DatabaseFieldConfig;->valueIfNotBlank(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     iput-object v2, v0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->format:Ljava/lang/String;
a=0;// 
a=0;//     .line 607
a=0;//     invoke-interface {p3}, Lcom/j256/ormlite/field/DatabaseField;->unique()Z
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Boolean);
a=0;//     iput-boolean v2, v0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->unique:Z
a=0;// 
a=0;//     .line 608
a=0;//     invoke-interface {p3}, Lcom/j256/ormlite/field/DatabaseField;->uniqueCombo()Z
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     iput-boolean v2, v0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->uniqueCombo:Z
a=0;// 
a=0;//     .line 611
a=0;//     invoke-interface {p3}, Lcom/j256/ormlite/field/DatabaseField;->index()Z
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     iput-boolean v2, v0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->index:Z
a=0;// 
a=0;//     .line 612
a=0;//     invoke-interface {p3}, Lcom/j256/ormlite/field/DatabaseField;->indexName()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     #v2=(Reference,Ljava/lang/String;);
a=0;//     invoke-static {v2}, Lcom/j256/ormlite/field/DatabaseFieldConfig;->valueIfNotBlank(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     iput-object v2, v0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->indexName:Ljava/lang/String;
a=0;// 
a=0;//     .line 613
a=0;//     invoke-interface {p3}, Lcom/j256/ormlite/field/DatabaseField;->uniqueIndex()Z
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Boolean);
a=0;//     iput-boolean v2, v0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->uniqueIndex:Z
a=0;// 
a=0;//     .line 614
a=0;//     invoke-interface {p3}, Lcom/j256/ormlite/field/DatabaseField;->uniqueIndexName()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     #v2=(Reference,Ljava/lang/String;);
a=0;//     invoke-static {v2}, Lcom/j256/ormlite/field/DatabaseFieldConfig;->valueIfNotBlank(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     iput-object v2, v0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->uniqueIndexName:Ljava/lang/String;
a=0;// 
a=0;//     .line 615
a=0;//     invoke-interface {p3}, Lcom/j256/ormlite/field/DatabaseField;->foreignAutoRefresh()Z
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Boolean);
a=0;//     iput-boolean v2, v0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->foreignAutoRefresh:Z
a=0;// 
a=0;//     .line 616
a=0;//     invoke-interface {p3}, Lcom/j256/ormlite/field/DatabaseField;->maxForeignAutoRefreshLevel()I
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     iput v2, v0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->maxForeignAutoRefreshLevel:I
a=0;// 
a=0;//     .line 617
a=0;//     invoke-interface {p3}, Lcom/j256/ormlite/field/DatabaseField;->persisterClass()Ljava/lang/Class;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     #v2=(Reference,Ljava/lang/Class;);
a=0;//     iput-object v2, v0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->persisterClass:Ljava/lang/Class;
a=0;// 
a=0;//     .line 618
a=0;//     invoke-interface {p3}, Lcom/j256/ormlite/field/DatabaseField;->allowGeneratedIdInsert()Z
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Boolean);
a=0;//     iput-boolean v2, v0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->allowGeneratedIdInsert:Z
a=0;// 
a=0;//     .line 619
a=0;//     invoke-interface {p3}, Lcom/j256/ormlite/field/DatabaseField;->columnDefinition()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     #v2=(Reference,Ljava/lang/String;);
a=0;//     invoke-static {v2}, Lcom/j256/ormlite/field/DatabaseFieldConfig;->valueIfNotBlank(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     iput-object v2, v0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->columnDefinition:Ljava/lang/String;
a=0;// 
a=0;//     .line 620
a=0;//     invoke-interface {p3}, Lcom/j256/ormlite/field/DatabaseField;->foreignAutoCreate()Z
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Boolean);
a=0;//     iput-boolean v2, v0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->foreignAutoCreate:Z
a=0;// 
a=0;//     .line 621
a=0;//     invoke-interface {p3}, Lcom/j256/ormlite/field/DatabaseField;->version()Z
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     iput-boolean v2, v0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->version:Z
a=0;// 
a=0;//     .line 622
a=0;//     invoke-interface {p3}, Lcom/j256/ormlite/field/DatabaseField;->foreignColumnName()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     #v2=(Reference,Ljava/lang/String;);
a=0;//     invoke-static {v2}, Lcom/j256/ormlite/field/DatabaseFieldConfig;->valueIfNotBlank(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     iput-object v2, v0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->foreignColumnName:Ljava/lang/String;
a=0;// 
a=0;//     .line 624
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public static fromField(Lcom/j256/ormlite/db/DatabaseType;Ljava/lang/String;Ljava/lang/reflect/Field;)Lcom/j256/ormlite/field/DatabaseFieldConfig;
a=0;//     .locals 4
a=0;//     .param p0, "databaseType"    # Lcom/j256/ormlite/db/DatabaseType;
a=0;//     .param p1, "tableName"    # Ljava/lang/String;
a=0;//     .param p2, "field"    # Ljava/lang/reflect/Field;
a=0;//     .annotation system Ldalvik/annotation/Throws;
a=0;//         value = {
a=0;//             Ljava/sql/SQLException;
a=0;//         }
a=0;//     .end annotation
a=0;// 
a=0;//     .prologue
a=0;//     .line 503
a=0;//     const-class v3, Lcom/j256/ormlite/field/DatabaseField;
a=0;// 
a=0;//     #v3=(Reference,Ljava/lang/Class;);
a=0;//     invoke-virtual {p2, v3}, Ljava/lang/reflect/Field;->getAnnotation(Ljava/lang/Class;)Ljava/lang/annotation/Annotation;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/annotation/Annotation;);
a=0;//     check-cast v1, Lcom/j256/ormlite/field/DatabaseField;
a=0;// 
a=0;//     .line 504
a=0;//     .local v1, "databaseField":Lcom/j256/ormlite/field/DatabaseField;
a=0;//     if-eqz v1, :cond_1
a=0;// 
a=0;//     .line 505
a=0;//     invoke-interface {v1}, Lcom/j256/ormlite/field/DatabaseField;->persisted()Z
a=0;// 
a=0;//     move-result v3
a=0;// 
a=0;//     #v3=(Boolean);
a=0;//     if-eqz v3, :cond_0
a=0;// 
a=0;//     .line 506
a=0;//     invoke-static {p0, p1, p2, v1}, Lcom/j256/ormlite/field/DatabaseFieldConfig;->fromDatabaseField(Lcom/j256/ormlite/db/DatabaseType;Ljava/lang/String;Ljava/lang/reflect/Field;Lcom/j256/ormlite/field/DatabaseField;)Lcom/j256/ormlite/field/DatabaseFieldConfig;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 524
a=0;//     :goto_0
a=0;//     #v0=(Reference,Lcom/j256/ormlite/field/DatabaseFieldConfig;);v2=(Conflicted);v3=(Conflicted);
a=0;//     return-object v0
a=0;// 
a=0;//     .line 508
a=0;//     :cond_0
a=0;//     #v0=(Uninit);v2=(Uninit);v3=(Boolean);
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     goto :goto_0
a=0;// 
a=0;//     .line 513
a=0;//     :cond_1
a=0;//     #v0=(Uninit);v3=(Reference,Ljava/lang/Class;);
a=0;//     const-class v3, Lcom/j256/ormlite/field/ForeignCollectionField;
a=0;// 
a=0;//     invoke-virtual {p2, v3}, Ljava/lang/reflect/Field;->getAnnotation(Ljava/lang/Class;)Ljava/lang/annotation/Annotation;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     #v2=(Reference,Ljava/lang/annotation/Annotation;);
a=0;//     check-cast v2, Lcom/j256/ormlite/field/ForeignCollectionField;
a=0;// 
a=0;//     .line 514
a=0;//     .local v2, "foreignCollection":Lcom/j256/ormlite/field/ForeignCollectionField;
a=0;//     if-eqz v2, :cond_2
a=0;// 
a=0;//     .line 515
a=0;//     invoke-static {p0, p2, v2}, Lcom/j256/ormlite/field/DatabaseFieldConfig;->fromForeignCollection(Lcom/j256/ormlite/db/DatabaseType;Ljava/lang/reflect/Field;Lcom/j256/ormlite/field/ForeignCollectionField;)Lcom/j256/ormlite/field/DatabaseFieldConfig;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Lcom/j256/ormlite/field/DatabaseFieldConfig;);
a=0;//     goto :goto_0
a=0;// 
a=0;//     .line 521
a=0;//     :cond_2
a=0;//     #v0=(Uninit);
a=0;//     invoke-static {p0, p2}, Lcom/j256/ormlite/misc/JavaxPersistence;->createFieldConfig(Lcom/j256/ormlite/db/DatabaseType;Ljava/lang/reflect/Field;)Lcom/j256/ormlite/field/DatabaseFieldConfig;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 524
a=0;//     .local v0, "config":Lcom/j256/ormlite/field/DatabaseFieldConfig;
a=0;//     #v0=(Reference,Lcom/j256/ormlite/field/DatabaseFieldConfig;);
a=0;//     goto :goto_0
a=0;// .end method
a=0;// 
a=0;// .method private static fromForeignCollection(Lcom/j256/ormlite/db/DatabaseType;Ljava/lang/reflect/Field;Lcom/j256/ormlite/field/ForeignCollectionField;)Lcom/j256/ormlite/field/DatabaseFieldConfig;
a=0;//     .locals 6
a=0;//     .param p0, "databaseType"    # Lcom/j256/ormlite/db/DatabaseType;
a=0;//     .param p1, "field"    # Ljava/lang/reflect/Field;
a=0;//     .param p2, "foreignCollection"    # Lcom/j256/ormlite/field/ForeignCollectionField;
a=0;// 
a=0;//     .prologue
a=0;//     const/4 v5, 0x1
a=0;// 
a=0;//     .line 661
a=0;//     #v5=(One);
a=0;//     new-instance v0, Lcom/j256/ormlite/field/DatabaseFieldConfig;
a=0;// 
a=0;//     #v0=(UninitRef,Lcom/j256/ormlite/field/DatabaseFieldConfig;);
a=0;//     invoke-direct {v0}, Lcom/j256/ormlite/field/DatabaseFieldConfig;-><init>()V
a=0;// 
a=0;//     .line 662
a=0;//     .local v0, "config":Lcom/j256/ormlite/field/DatabaseFieldConfig;
a=0;//     #v0=(Reference,Lcom/j256/ormlite/field/DatabaseFieldConfig;);
a=0;//     invoke-virtual {p1}, Ljava/lang/reflect/Field;->getName()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     #v4=(Reference,Ljava/lang/String;);
a=0;//     iput-object v4, v0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->fieldName:Ljava/lang/String;
a=0;// 
a=0;//     .line 663
a=0;//     invoke-interface {p2}, Lcom/j256/ormlite/field/ForeignCollectionField;->columnName()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-virtual {v4}, Ljava/lang/String;->length()I
a=0;// 
a=0;//     move-result v4
a=0;// 
a=0;//     #v4=(Integer);
a=0;//     if-lez v4, :cond_0
a=0;// 
a=0;//     .line 664
a=0;//     invoke-interface {p2}, Lcom/j256/ormlite/field/ForeignCollectionField;->columnName()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     #v4=(Reference,Ljava/lang/String;);
a=0;//     iput-object v4, v0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->columnName:Ljava/lang/String;
a=0;// 
a=0;//     .line 666
a=0;//     :cond_0
a=0;//     #v4=(Conflicted);
a=0;//     iput-boolean v5, v0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->foreignCollection:Z
a=0;// 
a=0;//     .line 667
a=0;//     invoke-interface {p2}, Lcom/j256/ormlite/field/ForeignCollectionField;->eager()Z
a=0;// 
a=0;//     move-result v4
a=0;// 
a=0;//     #v4=(Boolean);
a=0;//     iput-boolean v4, v0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->foreignCollectionEager:Z
a=0;// 
a=0;//     .line 669
a=0;//     invoke-interface {p2}, Lcom/j256/ormlite/field/ForeignCollectionField;->maxEagerForeignCollectionLevel()I
a=0;// 
a=0;//     move-result v3
a=0;// 
a=0;//     .line 670
a=0;//     .local v3, "maxEagerLevel":I
a=0;//     #v3=(Integer);
a=0;//     if-eq v3, v5, :cond_1
a=0;// 
a=0;//     .line 671
a=0;//     iput v3, v0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->foreignCollectionMaxEagerLevel:I
a=0;// 
a=0;//     .line 675
a=0;//     :goto_0
a=0;//     #v4=(Integer);
a=0;//     invoke-interface {p2}, Lcom/j256/ormlite/field/ForeignCollectionField;->orderColumnName()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     #v4=(Reference,Ljava/lang/String;);
a=0;//     invoke-static {v4}, Lcom/j256/ormlite/field/DatabaseFieldConfig;->valueIfNotBlank(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     iput-object v4, v0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->foreignCollectionOrderColumnName:Ljava/lang/String;
a=0;// 
a=0;//     .line 676
a=0;//     invoke-interface {p2}, Lcom/j256/ormlite/field/ForeignCollectionField;->orderAscending()Z
a=0;// 
a=0;//     move-result v4
a=0;// 
a=0;//     #v4=(Boolean);
a=0;//     iput-boolean v4, v0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->foreignCollectionOrderAscending:Z
a=0;// 
a=0;//     .line 677
a=0;//     invoke-interface {p2}, Lcom/j256/ormlite/field/ForeignCollectionField;->columnName()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     #v4=(Reference,Ljava/lang/String;);
a=0;//     invoke-static {v4}, Lcom/j256/ormlite/field/DatabaseFieldConfig;->valueIfNotBlank(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     iput-object v4, v0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->foreignCollectionColumnName:Ljava/lang/String;
a=0;// 
a=0;//     .line 678
a=0;//     invoke-interface {p2}, Lcom/j256/ormlite/field/ForeignCollectionField;->foreignFieldName()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-static {v4}, Lcom/j256/ormlite/field/DatabaseFieldConfig;->valueIfNotBlank(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     .line 679
a=0;//     .local v2, "foreignFieldName":Ljava/lang/String;
a=0;//     #v2=(Reference,Ljava/lang/String;);
a=0;//     if-nez v2, :cond_2
a=0;// 
a=0;//     .line 681
a=0;//     invoke-interface {p2}, Lcom/j256/ormlite/field/ForeignCollectionField;->foreignColumnName()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     invoke-static {v4}, Lcom/j256/ormlite/field/DatabaseFieldConfig;->valueIfNotBlank(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     .line 682
a=0;//     .local v1, "foreignColumnName":Ljava/lang/String;
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-static {v1}, Lcom/j256/ormlite/field/DatabaseFieldConfig;->valueIfNotBlank(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     iput-object v4, v0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->foreignCollectionForeignFieldName:Ljava/lang/String;
a=0;// 
a=0;//     .line 686
a=0;//     .end local v1    # "foreignColumnName":Ljava/lang/String;
a=0;//     :goto_1
a=0;//     #v1=(Conflicted);
a=0;//     return-object v0
a=0;// 
a=0;//     .line 673
a=0;//     .end local v2    # "foreignFieldName":Ljava/lang/String;
a=0;//     :cond_1
a=0;//     #v1=(Uninit);v2=(Uninit);v4=(Boolean);
a=0;//     invoke-interface {p2}, Lcom/j256/ormlite/field/ForeignCollectionField;->maxEagerLevel()I
a=0;// 
a=0;//     move-result v4
a=0;// 
a=0;//     #v4=(Integer);
a=0;//     iput v4, v0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->foreignCollectionMaxEagerLevel:I
a=0;// 
a=0;//     goto :goto_0
a=0;// 
a=0;//     .line 684
a=0;//     .restart local v2    # "foreignFieldName":Ljava/lang/String;
a=0;//     :cond_2
a=0;//     #v2=(Reference,Ljava/lang/String;);v4=(Reference,Ljava/lang/String;);
a=0;//     iput-object v2, v0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->foreignCollectionForeignFieldName:Ljava/lang/String;
a=0;// 
a=0;//     goto :goto_1
a=0;// .end method
a=0;// 
a=0;// .method private static methodFromField(Ljava/lang/reflect/Field;Ljava/lang/String;)Ljava/lang/String;
a=0;//     .locals 4
a=0;//     .param p0, "field"    # Ljava/lang/reflect/Field;
a=0;//     .param p1, "prefix"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     const/4 v3, 0x1
a=0;// 
a=0;//     .line 706
a=0;//     #v3=(One);
a=0;//     new-instance v0, Ljava/lang/StringBuilder;
a=0;// 
a=0;//     #v0=(UninitRef,Ljava/lang/StringBuilder;);
a=0;//     invoke-direct {v0}, Ljava/lang/StringBuilder;-><init>()V
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/StringBuilder;);
a=0;//     invoke-virtual {v0, p1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {p0}, Ljava/lang/reflect/Field;->getName()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     const/4 v2, 0x0
a=0;// 
a=0;//     #v2=(Null);
a=0;//     invoke-virtual {v1, v2, v3}, Ljava/lang/String;->substring(II)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v1}, Ljava/lang/String;->toUpperCase()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {p0}, Ljava/lang/reflect/Field;->getName()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v1, v3}, Ljava/lang/String;->substring(I)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method private static valueIfNotBlank(Ljava/lang/String;)Ljava/lang/String;
a=0;//     .locals 1
a=0;//     .param p0, "newValue"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 698
a=0;//     if-eqz p0, :cond_0
a=0;// 
a=0;//     invoke-virtual {p0}, Ljava/lang/String;->length()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     if-nez v0, :cond_1
a=0;// 
a=0;//     .line 699
a=0;//     :cond_0
a=0;//     #v0=(Conflicted);
a=0;//     const/4 p0, 0x0
a=0;// 
a=0;//     .line 701
a=0;//     :cond_1
a=0;//     return-object p0
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public getColumnDefinition()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 464
a=0;//     iget-object v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->columnDefinition:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getColumnName()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 117
a=0;//     iget-object v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->columnName:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getDataPersister()Lcom/j256/ormlite/field/DataPersister;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 139
a=0;//     iget-object v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->dataPersister:Lcom/j256/ormlite/field/DataPersister;
a=0;// 
a=0;//     #v0=(Reference,Lcom/j256/ormlite/field/DataPersister;);
a=0;//     if-nez v0, :cond_0
a=0;// 
a=0;//     .line 140
a=0;//     iget-object v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->dataType:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     invoke-virtual {v0}, Lcom/j256/ormlite/field/DataType;->getDataPersister()Lcom/j256/ormlite/field/DataPersister;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 142
a=0;//     :goto_0
a=0;//     return-object v0
a=0;// 
a=0;//     :cond_0
a=0;//     iget-object v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->dataPersister:Lcom/j256/ormlite/field/DataPersister;
a=0;// 
a=0;//     goto :goto_0
a=0;// .end method
a=0;// 
a=0;// .method public getDataType()Lcom/j256/ormlite/field/DataType;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 128
a=0;//     iget-object v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->dataType:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     #v0=(Reference,Lcom/j256/ormlite/field/DataType;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getDefaultValue()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 157
a=0;//     iget-object v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->defaultValue:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getFieldName()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 106
a=0;//     iget-object v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->fieldName:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getForeignCollectionColumnName()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 400
a=0;//     iget-object v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->foreignCollectionColumnName:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getForeignCollectionForeignFieldName()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 432
a=0;//     iget-object v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->foreignCollectionForeignFieldName:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getForeignCollectionMaxEagerLevel()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 376
a=0;//     iget v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->foreignCollectionMaxEagerLevel:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getForeignCollectionOrderColumnName()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 408
a=0;//     iget-object v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->foreignCollectionOrderColumnName:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getForeignColumnName()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 488
a=0;//     iget-object v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->foreignColumnName:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getForeignTableConfig()Lcom/j256/ormlite/table/DatabaseTableConfig;
a=0;//     .locals 1
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "()",
a=0;//             "Lcom/j256/ormlite/table/DatabaseTableConfig",
a=0;//             "<*>;"
a=0;//         }
a=0;//     .end annotation
a=0;// 
a=0;//     .prologue
a=0;//     .line 235
a=0;//     iget-object v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->foreignTableConfig:Lcom/j256/ormlite/table/DatabaseTableConfig;
a=0;// 
a=0;//     #v0=(Reference,Lcom/j256/ormlite/table/DatabaseTableConfig;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getFormat()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 278
a=0;//     iget-object v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->format:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getGeneratedIdSequence()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 212
a=0;//     iget-object v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->generatedIdSequence:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getIndexName(Ljava/lang/String;)Ljava/lang/String;
a=0;//     .locals 1
a=0;//     .param p1, "tableName"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 310
a=0;//     iget-boolean v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->index:Z
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     if-eqz v0, :cond_0
a=0;// 
a=0;//     iget-object v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->indexName:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     if-nez v0, :cond_0
a=0;// 
a=0;//     .line 311
a=0;//     invoke-direct {p0, p1}, Lcom/j256/ormlite/field/DatabaseFieldConfig;->findIndexName(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->indexName:Ljava/lang/String;
a=0;// 
a=0;//     .line 313
a=0;//     :cond_0
a=0;//     #v0=(Conflicted);
a=0;//     iget-object v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->indexName:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getMaxForeignAutoRefreshLevel()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 348
a=0;//     iget v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->maxForeignAutoRefreshLevel:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getPersisterClass()Ljava/lang/Class;
a=0;//     .locals 1
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "()",
a=0;//             "Ljava/lang/Class",
a=0;//             "<+",
a=0;//             "Lcom/j256/ormlite/field/DataPersister;",
a=0;//             ">;"
a=0;//         }
a=0;//     .end annotation
a=0;// 
a=0;//     .prologue
a=0;//     .line 448
a=0;//     iget-object v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->persisterClass:Ljava/lang/Class;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/Class;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getUniqueIndexName(Ljava/lang/String;)Ljava/lang/String;
a=0;//     .locals 1
a=0;//     .param p1, "tableName"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 329
a=0;//     iget-boolean v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->uniqueIndex:Z
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     if-eqz v0, :cond_0
a=0;// 
a=0;//     iget-object v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->uniqueIndexName:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     if-nez v0, :cond_0
a=0;// 
a=0;//     .line 330
a=0;//     invoke-direct {p0, p1}, Lcom/j256/ormlite/field/DatabaseFieldConfig;->findIndexName(Ljava/lang/String;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iput-object v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->uniqueIndexName:Ljava/lang/String;
a=0;// 
a=0;//     .line 332
a=0;//     :cond_0
a=0;//     #v0=(Conflicted);
a=0;//     iget-object v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->uniqueIndexName:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getUnknownEnumValue()Ljava/lang/Enum;
a=0;//     .locals 1
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "()",
a=0;//             "Ljava/lang/Enum",
a=0;//             "<*>;"
a=0;//         }
a=0;//     .end annotation
a=0;// 
a=0;//     .prologue
a=0;//     .line 254
a=0;//     iget-object v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->unknownEnumValue:Ljava/lang/Enum;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/Enum;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getWidth()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 168
a=0;//     iget v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->width:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public isAllowGeneratedIdInsert()Z
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 456
a=0;//     iget-boolean v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->allowGeneratedIdInsert:Z
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public isCanBeNull()Z
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 179
a=0;//     iget-boolean v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->canBeNull:Z
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public isForeign()Z
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 223
a=0;//     iget-boolean v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->foreign:Z
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public isForeignAutoCreate()Z
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 472
a=0;//     iget-boolean v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->foreignAutoCreate:Z
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public isForeignAutoRefresh()Z
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 344
a=0;//     iget-boolean v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->foreignAutoRefresh:Z
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public isForeignCollection()Z
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 360
a=0;//     iget-boolean v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->foreignCollection:Z
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public isForeignCollectionEager()Z
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 368
a=0;//     iget-boolean v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->foreignCollectionEager:Z
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public isForeignCollectionOrderAscending()Z
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 424
a=0;//     iget-boolean v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->foreignCollectionOrderAscending:Z
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public isGeneratedId()Z
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 201
a=0;//     iget-boolean v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->generatedId:Z
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public isId()Z
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 190
a=0;//     iget-boolean v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->id:Z
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public isIndex()Z
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 302
a=0;//     iget-boolean v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->index:Z
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public isPersisted()Z
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 270
a=0;//     iget-boolean v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->persisted:Z
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public isThrowIfNull()Z
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 262
a=0;//     iget-boolean v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->throwIfNull:Z
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public isUnique()Z
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 286
a=0;//     iget-boolean v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->unique:Z
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public isUniqueCombo()Z
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 294
a=0;//     iget-boolean v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->uniqueCombo:Z
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public isUniqueIndex()Z
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 321
a=0;//     iget-boolean v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->uniqueIndex:Z
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public isUseGetSet()Z
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 246
a=0;//     iget-boolean v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->useGetSet:Z
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public isVersion()Z
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 480
a=0;//     iget-boolean v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->version:Z
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public postProcess()V
a=0;//     .locals 2
a=0;// 
a=0;//     .prologue
a=0;//     .line 631
a=0;//     iget-object v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->foreignColumnName:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     if-eqz v0, :cond_0
a=0;// 
a=0;//     .line 632
a=0;//     const/4 v0, 0x1
a=0;// 
a=0;//     #v0=(One);
a=0;//     iput-boolean v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->foreignAutoRefresh:Z
a=0;// 
a=0;//     .line 634
a=0;//     :cond_0
a=0;//     #v0=(Conflicted);
a=0;//     iget-boolean v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->foreignAutoRefresh:Z
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     if-eqz v0, :cond_1
a=0;// 
a=0;//     iget v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->maxForeignAutoRefreshLevel:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     const/4 v1, -0x1
a=0;// 
a=0;//     #v1=(Byte);
a=0;//     if-ne v0, v1, :cond_1
a=0;// 
a=0;//     .line 636
a=0;//     const/4 v0, 0x2
a=0;// 
a=0;//     #v0=(PosByte);
a=0;//     iput v0, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->maxForeignAutoRefreshLevel:I
a=0;// 
a=0;//     .line 638
a=0;//     :cond_1
a=0;//     #v0=(Integer);v1=(Conflicted);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setAllowGeneratedIdInsert(Z)V
a=0;//     .locals 0
a=0;//     .param p1, "allowGeneratedIdInsert"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 460
a=0;//     iput-boolean p1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->allowGeneratedIdInsert:Z
a=0;// 
a=0;//     .line 461
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setCanBeNull(Z)V
a=0;//     .locals 0
a=0;//     .param p1, "canBeNull"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 183
a=0;//     iput-boolean p1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->canBeNull:Z
a=0;// 
a=0;//     .line 184
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setColumnDefinition(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "columnDefinition"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 468
a=0;//     iput-object p1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->columnDefinition:Ljava/lang/String;
a=0;// 
a=0;//     .line 469
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setColumnName(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "columnName"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 121
a=0;//     iput-object p1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->columnName:Ljava/lang/String;
a=0;// 
a=0;//     .line 122
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setDataPersister(Lcom/j256/ormlite/field/DataPersister;)V
a=0;//     .locals 0
a=0;//     .param p1, "dataPersister"    # Lcom/j256/ormlite/field/DataPersister;
a=0;// 
a=0;//     .prologue
a=0;//     .line 150
a=0;//     iput-object p1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->dataPersister:Lcom/j256/ormlite/field/DataPersister;
a=0;// 
a=0;//     .line 151
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setDataType(Lcom/j256/ormlite/field/DataType;)V
a=0;//     .locals 0
a=0;//     .param p1, "dataType"    # Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     .prologue
a=0;//     .line 132
a=0;//     iput-object p1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->dataType:Lcom/j256/ormlite/field/DataType;
a=0;// 
a=0;//     .line 133
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setDefaultValue(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "defaultValue"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 161
a=0;//     iput-object p1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->defaultValue:Ljava/lang/String;
a=0;// 
a=0;//     .line 162
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setFieldName(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "fieldName"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 110
a=0;//     iput-object p1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->fieldName:Ljava/lang/String;
a=0;// 
a=0;//     .line 111
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setForeign(Z)V
a=0;//     .locals 0
a=0;//     .param p1, "foreign"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 227
a=0;//     iput-boolean p1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->foreign:Z
a=0;// 
a=0;//     .line 228
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setForeignAutoCreate(Z)V
a=0;//     .locals 0
a=0;//     .param p1, "foreignAutoCreate"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 476
a=0;//     iput-boolean p1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->foreignAutoCreate:Z
a=0;// 
a=0;//     .line 477
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setForeignAutoRefresh(Z)V
a=0;//     .locals 0
a=0;//     .param p1, "foreignAutoRefresh"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 340
a=0;//     iput-boolean p1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->foreignAutoRefresh:Z
a=0;// 
a=0;//     .line 341
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setForeignCollection(Z)V
a=0;//     .locals 0
a=0;//     .param p1, "foreignCollection"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 364
a=0;//     iput-boolean p1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->foreignCollection:Z
a=0;// 
a=0;//     .line 365
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setForeignCollectionColumnName(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "foreignCollectionColumn"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 404
a=0;//     iput-object p1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->foreignCollectionColumnName:Ljava/lang/String;
a=0;// 
a=0;//     .line 405
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setForeignCollectionEager(Z)V
a=0;//     .locals 0
a=0;//     .param p1, "foreignCollectionEager"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 372
a=0;//     iput-boolean p1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->foreignCollectionEager:Z
a=0;// 
a=0;//     .line 373
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setForeignCollectionForeignColumnName(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "foreignCollectionForeignColumnName"    # Ljava/lang/String;
a=0;//     .annotation runtime Ljava/lang/Deprecated;
a=0;//     .end annotation
a=0;// 
a=0;//     .prologue
a=0;//     .line 440
a=0;//     iput-object p1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->foreignCollectionForeignFieldName:Ljava/lang/String;
a=0;// 
a=0;//     .line 441
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setForeignCollectionForeignFieldName(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "foreignCollectionForeignFieldName"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 444
a=0;//     iput-object p1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->foreignCollectionForeignFieldName:Ljava/lang/String;
a=0;// 
a=0;//     .line 445
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setForeignCollectionMaxEagerForeignCollectionLevel(I)V
a=0;//     .locals 0
a=0;//     .param p1, "maxEagerForeignCollectionLevel"    # I
a=0;//     .annotation runtime Ljava/lang/Deprecated;
a=0;//     .end annotation
a=0;// 
a=0;//     .prologue
a=0;//     .line 396
a=0;//     iput p1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->foreignCollectionMaxEagerLevel:I
a=0;// 
a=0;//     .line 397
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setForeignCollectionMaxEagerLevel(I)V
a=0;//     .locals 0
a=0;//     .param p1, "foreignCollectionMaxEagerLevel"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 380
a=0;//     iput p1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->foreignCollectionMaxEagerLevel:I
a=0;// 
a=0;//     .line 381
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setForeignCollectionOrderAscending(Z)V
a=0;//     .locals 0
a=0;//     .param p1, "foreignCollectionOrderAscending"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 428
a=0;//     iput-boolean p1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->foreignCollectionOrderAscending:Z
a=0;// 
a=0;//     .line 429
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setForeignCollectionOrderColumn(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "foreignCollectionOrderColumn"    # Ljava/lang/String;
a=0;//     .annotation runtime Ljava/lang/Deprecated;
a=0;//     .end annotation
a=0;// 
a=0;//     .prologue
a=0;//     .line 416
a=0;//     iput-object p1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->foreignCollectionOrderColumnName:Ljava/lang/String;
a=0;// 
a=0;//     .line 417
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setForeignCollectionOrderColumnName(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "foreignCollectionOrderColumn"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 420
a=0;//     iput-object p1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->foreignCollectionOrderColumnName:Ljava/lang/String;
a=0;// 
a=0;//     .line 421
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setForeignColumnName(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "foreignColumnName"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 492
a=0;//     iput-object p1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->foreignColumnName:Ljava/lang/String;
a=0;// 
a=0;//     .line 493
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setForeignTableConfig(Lcom/j256/ormlite/table/DatabaseTableConfig;)V
a=0;//     .locals 0
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "(",
a=0;//             "Lcom/j256/ormlite/table/DatabaseTableConfig",
a=0;//             "<*>;)V"
a=0;//         }
a=0;//     .end annotation
a=0;// 
a=0;//     .prologue
a=0;//     .line 239
a=0;//     .local p1, "foreignTableConfig":Lcom/j256/ormlite/table/DatabaseTableConfig;, "Lcom/j256/ormlite/table/DatabaseTableConfig<*>;"
a=0;//     iput-object p1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->foreignTableConfig:Lcom/j256/ormlite/table/DatabaseTableConfig;
a=0;// 
a=0;//     .line 240
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setFormat(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "format"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 282
a=0;//     iput-object p1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->format:Ljava/lang/String;
a=0;// 
a=0;//     .line 283
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setGeneratedId(Z)V
a=0;//     .locals 0
a=0;//     .param p1, "generatedId"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 205
a=0;//     iput-boolean p1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->generatedId:Z
a=0;// 
a=0;//     .line 206
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setGeneratedIdSequence(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "generatedIdSequence"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 216
a=0;//     iput-object p1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->generatedIdSequence:Ljava/lang/String;
a=0;// 
a=0;//     .line 217
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setId(Z)V
a=0;//     .locals 0
a=0;//     .param p1, "id"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 194
a=0;//     iput-boolean p1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->id:Z
a=0;// 
a=0;//     .line 195
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setIndex(Z)V
a=0;//     .locals 0
a=0;//     .param p1, "index"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 306
a=0;//     iput-boolean p1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->index:Z
a=0;// 
a=0;//     .line 307
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setIndexName(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "indexName"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 317
a=0;//     iput-object p1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->indexName:Ljava/lang/String;
a=0;// 
a=0;//     .line 318
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setMaxEagerForeignCollectionLevel(I)V
a=0;//     .locals 0
a=0;//     .param p1, "maxEagerForeignCollectionLevel"    # I
a=0;//     .annotation runtime Ljava/lang/Deprecated;
a=0;//     .end annotation
a=0;// 
a=0;//     .prologue
a=0;//     .line 388
a=0;//     iput p1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->foreignCollectionMaxEagerLevel:I
a=0;// 
a=0;//     .line 389
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setMaxForeignAutoRefreshLevel(I)V
a=0;//     .locals 0
a=0;//     .param p1, "maxForeignLevel"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 352
a=0;//     iput p1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->maxForeignAutoRefreshLevel:I
a=0;// 
a=0;//     .line 353
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setPersisted(Z)V
a=0;//     .locals 0
a=0;//     .param p1, "persisted"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 274
a=0;//     iput-boolean p1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->persisted:Z
a=0;// 
a=0;//     .line 275
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setPersisterClass(Ljava/lang/Class;)V
a=0;//     .locals 0
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "(",
a=0;//             "Ljava/lang/Class",
a=0;//             "<+",
a=0;//             "Lcom/j256/ormlite/field/DataPersister;",
a=0;//             ">;)V"
a=0;//         }
a=0;//     .end annotation
a=0;// 
a=0;//     .prologue
a=0;//     .line 452
a=0;//     .local p1, "persisterClass":Ljava/lang/Class;, "Ljava/lang/Class<+Lcom/j256/ormlite/field/DataPersister;>;"
a=0;//     iput-object p1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->persisterClass:Ljava/lang/Class;
a=0;// 
a=0;//     .line 453
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setThrowIfNull(Z)V
a=0;//     .locals 0
a=0;//     .param p1, "throwIfNull"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 266
a=0;//     iput-boolean p1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->throwIfNull:Z
a=0;// 
a=0;//     .line 267
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setUnique(Z)V
a=0;//     .locals 0
a=0;//     .param p1, "unique"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 290
a=0;//     iput-boolean p1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->unique:Z
a=0;// 
a=0;//     .line 291
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setUniqueCombo(Z)V
a=0;//     .locals 0
a=0;//     .param p1, "uniqueCombo"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 298
a=0;//     iput-boolean p1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->uniqueCombo:Z
a=0;// 
a=0;//     .line 299
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setUniqueIndex(Z)V
a=0;//     .locals 0
a=0;//     .param p1, "uniqueIndex"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 325
a=0;//     iput-boolean p1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->uniqueIndex:Z
a=0;// 
a=0;//     .line 326
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setUniqueIndexName(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "uniqueIndexName"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 336
a=0;//     iput-object p1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->uniqueIndexName:Ljava/lang/String;
a=0;// 
a=0;//     .line 337
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setUnknownEnumValue(Ljava/lang/Enum;)V
a=0;//     .locals 0
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "(",
a=0;//             "Ljava/lang/Enum",
a=0;//             "<*>;)V"
a=0;//         }
a=0;//     .end annotation
a=0;// 
a=0;//     .prologue
a=0;//     .line 258
a=0;//     .local p1, "unknownEnumValue":Ljava/lang/Enum;, "Ljava/lang/Enum<*>;"
a=0;//     iput-object p1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->unknownEnumValue:Ljava/lang/Enum;
a=0;// 
a=0;//     .line 259
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setUseGetSet(Z)V
a=0;//     .locals 0
a=0;//     .param p1, "useGetSet"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 250
a=0;//     iput-boolean p1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->useGetSet:Z
a=0;// 
a=0;//     .line 251
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setVersion(Z)V
a=0;//     .locals 0
a=0;//     .param p1, "version"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 484
a=0;//     iput-boolean p1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->version:Z
a=0;// 
a=0;//     .line 485
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setWidth(I)V
a=0;//     .locals 0
a=0;//     .param p1, "width"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 172
a=0;//     iput p1, p0, Lcom/j256/ormlite/field/DatabaseFieldConfig;->width:I
a=0;// 
a=0;//     .line 173
a=0;//     return-void
a=0;// .end method
}}
