package com.twocloo.com.cn.view; class MyListView { void a() { int a;
a=0;// .class public Lcom/twocloo/com/cn/view/MyListView;
a=0;// .super Landroid/widget/LinearLayout;
a=0;// .source "MyListView.java"
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation build Landroid/annotation/SuppressLint;
a=0;//     value = {
a=0;//         "NewApi"
a=0;//     }
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field private ctx:Landroid/content/Context;
a=0;// 
a=0;// .field private footerview:Landroid/view/View;
a=0;// 
a=0;// .field private headview:Landroid/view/View;
a=0;// 
a=0;// .field private index:I
a=0;// 
a=0;// .field private map:Ljava/util/Map;
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "Ljava/util/Map",
a=0;//             "<",
a=0;//             "Landroid/view/View;",
a=0;//             "Ljava/lang/Integer;",
a=0;//             ">;"
a=0;//         }
a=0;//     .end annotation
a=0;// .end field
a=0;// 
a=0;// .field private onItemClickListener:Landroid/widget/AdapterView$OnItemClickListener;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>(Landroid/content/Context;)V
a=0;//     .locals 1
a=0;//     .param p1, "context"    # Landroid/content/Context;
a=0;// 
a=0;//     .prologue
a=0;//     .line 45
a=0;//     invoke-direct {p0, p1}, Landroid/widget/LinearLayout;-><init>(Landroid/content/Context;)V
a=0;// 
a=0;//     .line 25
a=0;//     #p0=(Reference,Lcom/twocloo/com/cn/view/MyListView;);
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     iput v0, p0, Lcom/twocloo/com/cn/view/MyListView;->index:I
a=0;// 
a=0;//     .line 26
a=0;//     new-instance v0, Ljava/util/HashMap;
a=0;// 
a=0;//     #v0=(UninitRef,Ljava/util/HashMap;);
a=0;//     invoke-direct {v0}, Ljava/util/HashMap;-><init>()V
a=0;// 
a=0;//     #v0=(Reference,Ljava/util/HashMap;);
a=0;//     iput-object v0, p0, Lcom/twocloo/com/cn/view/MyListView;->map:Ljava/util/Map;
a=0;// 
a=0;//     .line 46
a=0;//     invoke-virtual {p0, p1}, Lcom/twocloo/com/cn/view/MyListView;->init(Landroid/content/Context;)V
a=0;// 
a=0;//     .line 47
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public constructor <init>(Landroid/content/Context;Landroid/util/AttributeSet;)V
a=0;//     .locals 1
a=0;//     .param p1, "context"    # Landroid/content/Context;
a=0;//     .param p2, "attrs"    # Landroid/util/AttributeSet;
a=0;// 
a=0;//     .prologue
a=0;//     .line 40
a=0;//     invoke-direct {p0, p1, p2}, Landroid/widget/LinearLayout;-><init>(Landroid/content/Context;Landroid/util/AttributeSet;)V
a=0;// 
a=0;//     .line 25
a=0;//     #p0=(Reference,Lcom/twocloo/com/cn/view/MyListView;);
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     iput v0, p0, Lcom/twocloo/com/cn/view/MyListView;->index:I
a=0;// 
a=0;//     .line 26
a=0;//     new-instance v0, Ljava/util/HashMap;
a=0;// 
a=0;//     #v0=(UninitRef,Ljava/util/HashMap;);
a=0;//     invoke-direct {v0}, Ljava/util/HashMap;-><init>()V
a=0;// 
a=0;//     #v0=(Reference,Ljava/util/HashMap;);
a=0;//     iput-object v0, p0, Lcom/twocloo/com/cn/view/MyListView;->map:Ljava/util/Map;
a=0;// 
a=0;//     .line 41
a=0;//     invoke-virtual {p0, p1}, Lcom/twocloo/com/cn/view/MyListView;->init(Landroid/content/Context;)V
a=0;// 
a=0;//     .line 42
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public constructor <init>(Landroid/content/Context;Landroid/util/AttributeSet;I)V
a=0;//     .locals 1
a=0;//     .param p1, "context"    # Landroid/content/Context;
a=0;//     .param p2, "attrs"    # Landroid/util/AttributeSet;
a=0;//     .param p3, "defStyle"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 35
a=0;//     invoke-direct {p0, p1, p2, p3}, Landroid/widget/LinearLayout;-><init>(Landroid/content/Context;Landroid/util/AttributeSet;I)V
a=0;// 
a=0;//     .line 25
a=0;//     #p0=(Reference,Lcom/twocloo/com/cn/view/MyListView;);
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     iput v0, p0, Lcom/twocloo/com/cn/view/MyListView;->index:I
a=0;// 
a=0;//     .line 26
a=0;//     new-instance v0, Ljava/util/HashMap;
a=0;// 
a=0;//     #v0=(UninitRef,Ljava/util/HashMap;);
a=0;//     invoke-direct {v0}, Ljava/util/HashMap;-><init>()V
a=0;// 
a=0;//     #v0=(Reference,Ljava/util/HashMap;);
a=0;//     iput-object v0, p0, Lcom/twocloo/com/cn/view/MyListView;->map:Ljava/util/Map;
a=0;// 
a=0;//     .line 36
a=0;//     invoke-virtual {p0, p1}, Lcom/twocloo/com/cn/view/MyListView;->init(Landroid/content/Context;)V
a=0;// 
a=0;//     .line 37
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method static synthetic access$0(Lcom/twocloo/com/cn/view/MyListView;)Landroid/widget/AdapterView$OnItemClickListener;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 23
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/view/MyListView;->onItemClickListener:Landroid/widget/AdapterView$OnItemClickListener;
a=0;// 
a=0;//     #v0=(Reference,Landroid/widget/AdapterView$OnItemClickListener;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method static synthetic access$1(Lcom/twocloo/com/cn/view/MyListView;)Ljava/util/Map;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 26
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/view/MyListView;->map:Ljava/util/Map;
a=0;// 
a=0;//     #v0=(Reference,Ljava/util/Map;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public addFooterView(Landroid/view/View;)V
a=0;//     .locals 0
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 86
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/view/MyListView;->footerview:Landroid/view/View;
a=0;// 
a=0;//     .line 87
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public addHeaderView(Landroid/view/View;)V
a=0;//     .locals 0
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 82
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/view/MyListView;->headview:Landroid/view/View;
a=0;// 
a=0;//     .line 83
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public init(Landroid/content/Context;)V
a=0;//     .locals 1
a=0;//     .param p1, "context"    # Landroid/content/Context;
a=0;// 
a=0;//     .prologue
a=0;//     .line 29
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/view/MyListView;->ctx:Landroid/content/Context;
a=0;// 
a=0;//     .line 30
a=0;//     const/4 v0, 0x1
a=0;// 
a=0;//     #v0=(One);
a=0;//     invoke-virtual {p0, v0}, Lcom/twocloo/com/cn/view/MyListView;->setOrientation(I)V
a=0;// 
a=0;//     .line 32
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method protected onMeasure(II)V
a=0;//     .locals 3
a=0;//     .param p1, "widthMeasureSpec"    # I
a=0;//     .param p2, "heightMeasureSpec"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 91
a=0;//     const v1, 0x1fffffff
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     const/high16 v2, -0x80000000
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     invoke-static {v1, v2}, Landroid/view/View$MeasureSpec;->makeMeasureSpec(II)I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     .line 92
a=0;//     .local v0, "expandSpec":I
a=0;//     #v0=(Integer);
a=0;//     invoke-super {p0, p1, v0}, Landroid/widget/LinearLayout;->onMeasure(II)V
a=0;// 
a=0;//     .line 93
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setAdapter(Landroid/widget/BaseAdapter;)V
a=0;//     .locals 6
a=0;//     .param p1, "adapter"    # Landroid/widget/BaseAdapter;
a=0;// 
a=0;//     .prologue
a=0;//     const/4 v5, 0x0
a=0;// 
a=0;//     .line 50
a=0;//     #v5=(Null);
a=0;//     invoke-virtual {p1}, Landroid/widget/BaseAdapter;->getCount()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     .line 51
a=0;//     .local v0, "count":I
a=0;//     #v0=(Integer);
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/view/MyListView;->removeAllViews()V
a=0;// 
a=0;//     .line 52
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/view/MyListView;->map:Ljava/util/Map;
a=0;// 
a=0;//     #v3=(Reference,Ljava/util/Map;);
a=0;//     invoke-interface {v3}, Ljava/util/Map;->clear()V
a=0;// 
a=0;//     .line 54
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/view/MyListView;->headview:Landroid/view/View;
a=0;// 
a=0;//     if-eqz v3, :cond_0
a=0;// 
a=0;//     .line 55
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/view/MyListView;->headview:Landroid/view/View;
a=0;// 
a=0;//     invoke-virtual {p0, v3}, Lcom/twocloo/com/cn/view/MyListView;->addView(Landroid/view/View;)V
a=0;// 
a=0;//     .line 58
a=0;//     :cond_0
a=0;//     const/4 v1, 0x0
a=0;// 
a=0;//     .local v1, "i":I
a=0;//     :goto_0
a=0;//     #v1=(Integer);v2=(Conflicted);v4=(Conflicted);
a=0;//     if-lt v1, v0, :cond_2
a=0;// 
a=0;//     .line 73
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/view/MyListView;->footerview:Landroid/view/View;
a=0;// 
a=0;//     if-eqz v3, :cond_1
a=0;// 
a=0;//     .line 74
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/view/MyListView;->footerview:Landroid/view/View;
a=0;// 
a=0;//     invoke-virtual {p0, v3, v0}, Lcom/twocloo/com/cn/view/MyListView;->addView(Landroid/view/View;I)V
a=0;// 
a=0;//     .line 75
a=0;//     :cond_1
a=0;//     return-void
a=0;// 
a=0;//     .line 59
a=0;//     :cond_2
a=0;//     iput v1, p0, Lcom/twocloo/com/cn/view/MyListView;->index:I
a=0;// 
a=0;//     .line 60
a=0;//     invoke-virtual {p1, v1, v5, v5}, Landroid/widget/BaseAdapter;->getView(ILandroid/view/View;Landroid/view/ViewGroup;)Landroid/view/View;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     .line 61
a=0;//     .local v2, "view":Landroid/view/View;
a=0;//     #v2=(Reference,Landroid/view/View;);
a=0;//     invoke-virtual {p0, v2}, Lcom/twocloo/com/cn/view/MyListView;->addView(Landroid/view/View;)V
a=0;// 
a=0;//     .line 62
a=0;//     iget-object v3, p0, Lcom/twocloo/com/cn/view/MyListView;->map:Ljava/util/Map;
a=0;// 
a=0;//     invoke-static {v1}, Ljava/lang/Integer;->valueOf(I)Ljava/lang/Integer;
a=0;// 
a=0;//     move-result-object v4
a=0;// 
a=0;//     #v4=(Reference,Ljava/lang/Integer;);
a=0;//     invoke-interface {v3, v2, v4}, Ljava/util/Map;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
a=0;// 
a=0;//     .line 63
a=0;//     new-instance v3, Lcom/twocloo/com/cn/view/MyListView$1;
a=0;// 
a=0;//     #v3=(UninitRef,Lcom/twocloo/com/cn/view/MyListView$1;);
a=0;//     invoke-direct {v3, p0}, Lcom/twocloo/com/cn/view/MyListView$1;-><init>(Lcom/twocloo/com/cn/view/MyListView;)V
a=0;// 
a=0;//     #v3=(Reference,Lcom/twocloo/com/cn/view/MyListView$1;);
a=0;//     invoke-virtual {v2, v3}, Landroid/view/View;->setOnClickListener(Landroid/view/View$OnClickListener;)V
a=0;// 
a=0;//     .line 58
a=0;//     add-int/lit8 v1, v1, 0x1
a=0;// 
a=0;//     goto :goto_0
a=0;// .end method
a=0;// 
a=0;// .method public setOnItemClickListener(Landroid/widget/AdapterView$OnItemClickListener;)V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 78
a=0;//     .local p1, "onItemClickListener":Landroid/widget/AdapterView$OnItemClickListener;, "Landroid/widget/AdapterView$OnItemClickListener;"
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/view/MyListView;->onItemClickListener:Landroid/widget/AdapterView$OnItemClickListener;
a=0;// 
a=0;//     .line 79
a=0;//     return-void
a=0;// .end method
}}
