package com.twocloo.com.cn.view; class ResizeLayout { void a() { int a;
a=0;// .class public Lcom/twocloo/com/cn/view/ResizeLayout;
a=0;// .super Landroid/widget/LinearLayout;
a=0;// .source "ResizeLayout.java"
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation system Ldalvik/annotation/MemberClasses;
a=0;//     value = {
a=0;//         Lcom/twocloo/com/cn/view/ResizeLayout$OnResizeListener;
a=0;//     }
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field private mListener:Lcom/twocloo/com/cn/view/ResizeLayout$OnResizeListener;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>(Landroid/content/Context;Landroid/util/AttributeSet;)V
a=0;//     .locals 0
a=0;//     .param p1, "context"    # Landroid/content/Context;
a=0;//     .param p2, "attrs"    # Landroid/util/AttributeSet;
a=0;// 
a=0;//     .prologue
a=0;//     .line 19
a=0;//     invoke-direct {p0, p1, p2}, Landroid/widget/LinearLayout;-><init>(Landroid/content/Context;Landroid/util/AttributeSet;)V
a=0;// 
a=0;//     .line 20
a=0;//     #p0=(Reference,Lcom/twocloo/com/cn/view/ResizeLayout;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method protected onSizeChanged(IIII)V
a=0;//     .locals 1
a=0;//     .param p1, "w"    # I
a=0;//     .param p2, "h"    # I
a=0;//     .param p3, "oldw"    # I
a=0;//     .param p4, "oldh"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 24
a=0;//     invoke-super {p0, p1, p2, p3, p4}, Landroid/widget/LinearLayout;->onSizeChanged(IIII)V
a=0;// 
a=0;//     .line 26
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/view/ResizeLayout;->mListener:Lcom/twocloo/com/cn/view/ResizeLayout$OnResizeListener;
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/view/ResizeLayout$OnResizeListener;);
a=0;//     if-eqz v0, :cond_0
a=0;// 
a=0;//     .line 27
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/view/ResizeLayout;->mListener:Lcom/twocloo/com/cn/view/ResizeLayout$OnResizeListener;
a=0;// 
a=0;//     invoke-interface {v0, p1, p2, p3, p4}, Lcom/twocloo/com/cn/view/ResizeLayout$OnResizeListener;->OnResize(IIII)V
a=0;// 
a=0;//     .line 29
a=0;//     :cond_0
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setOnResizeListener(Lcom/twocloo/com/cn/view/ResizeLayout$OnResizeListener;)V
a=0;//     .locals 0
a=0;//     .param p1, "l"    # Lcom/twocloo/com/cn/view/ResizeLayout$OnResizeListener;
a=0;// 
a=0;//     .prologue
a=0;//     .line 15
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/view/ResizeLayout;->mListener:Lcom/twocloo/com/cn/view/ResizeLayout$OnResizeListener;
a=0;// 
a=0;//     .line 16
a=0;//     return-void
a=0;// .end method
}}
