package com.twocloooo; class ay { void a() { int a;
a=0;// .class public Lcom/twocloooo/ay;
a=0;// .super Ljava/lang/Object;
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field public a:Ljava/lang/String;
a=0;// 
a=0;// .field public b:Ljava/lang/Integer;
a=0;// 
a=0;// .field public c:Ljava/lang/String;
a=0;// 
a=0;// .field public d:Ljava/lang/Integer;
a=0;// 
a=0;// .field public e:Ljava/lang/Integer;
a=0;// 
a=0;// .field public f:Ljava/lang/String;
a=0;// 
a=0;// .field public g:Ljava/lang/String;
a=0;// 
a=0;// .field public h:Ljava/lang/String;
a=0;// 
a=0;// .field public i:Ljava/lang/String;
a=0;// 
a=0;// .field public j:Ljava/lang/String;
a=0;// 
a=0;// .field public k:Ljava/lang/String;
a=0;// 
a=0;// .field public l:Ljava/lang/Integer;
a=0;// 
a=0;// .field public m:Ljava/lang/Integer;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcom/twocloooo/ay;);
a=0;//     return-void
a=0;// .end method
}}
