package com.twocloooo; class DevNativeActivity$2 { void a() { int a;
a=0;// .class Lcom/twocloooo/DevNativeActivity$2;
a=0;// .super Ljava/lang/Object;
a=0;// 
a=0;// # interfaces
a=0;// .implements Landroid/content/DialogInterface$OnClickListener;
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field final synthetic a:Lcom/twocloooo/DevNativeActivity;
a=0;// 
a=0;// .field private final synthetic b:Ljava/lang/String;
a=0;// 
a=0;// .field private final synthetic c:I
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>(Lcom/twocloooo/DevNativeActivity;Ljava/lang/String;I)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-object p1, p0, Lcom/twocloooo/DevNativeActivity$2;->a:Lcom/twocloooo/DevNativeActivity;
a=0;// 
a=0;//     iput-object p2, p0, Lcom/twocloooo/DevNativeActivity$2;->b:Ljava/lang/String;
a=0;// 
a=0;//     iput p3, p0, Lcom/twocloooo/DevNativeActivity$2;->c:I
a=0;// 
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcom/twocloooo/DevNativeActivity$2;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public onClick(Landroid/content/DialogInterface;I)V
a=0;//     .locals 3
a=0;// 
a=0;//     new-instance v0, Landroid/content/Intent;
a=0;// 
a=0;//     #v0=(UninitRef,Landroid/content/Intent;);
a=0;//     new-instance v1, Ljava/lang/StringBuilder;
a=0;// 
a=0;//     #v1=(UninitRef,Ljava/lang/StringBuilder;);
a=0;//     iget-object v2, p0, Lcom/twocloooo/DevNativeActivity$2;->a:Lcom/twocloooo/DevNativeActivity;
a=0;// 
a=0;//     #v2=(Reference,Lcom/twocloooo/DevNativeActivity;);
a=0;//     invoke-virtual {v2}, Lcom/twocloooo/DevNativeActivity;->getPackageName()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-static {v2}, Ljava/lang/String;->valueOf(Ljava/lang/Object;)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     invoke-direct {v1, v2}, Ljava/lang/StringBuilder;-><init>(Ljava/lang/String;)V
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/StringBuilder;);
a=0;//     const-string v2, "."
a=0;// 
a=0;//     invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     const-string v2, "android.intent.action.stop_dowsnloading_app"
a=0;// 
a=0;//     invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v1}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-direct {v0, v1}, Landroid/content/Intent;-><init>(Ljava/lang/String;)V
a=0;// 
a=0;//     #v0=(Reference,Landroid/content/Intent;);
a=0;//     const-string v1, "title"
a=0;// 
a=0;//     iget-object v2, p0, Lcom/twocloooo/DevNativeActivity$2;->b:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1, v2}, Landroid/content/Intent;->putExtra(Ljava/lang/String;Ljava/lang/String;)Landroid/content/Intent;
a=0;// 
a=0;//     const-string v1, "mId"
a=0;// 
a=0;//     iget v2, p0, Lcom/twocloooo/DevNativeActivity$2;->c:I
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     invoke-virtual {v0, v1, v2}, Landroid/content/Intent;->putExtra(Ljava/lang/String;I)Landroid/content/Intent;
a=0;// 
a=0;//     iget-object v1, p0, Lcom/twocloooo/DevNativeActivity$2;->a:Lcom/twocloooo/DevNativeActivity;
a=0;// 
a=0;//     invoke-virtual {v1, v0}, Lcom/twocloooo/DevNativeActivity;->sendBroadcast(Landroid/content/Intent;)V
a=0;// 
a=0;//     iget-object v0, p0, Lcom/twocloooo/DevNativeActivity$2;->a:Lcom/twocloooo/DevNativeActivity;
a=0;// 
a=0;//     invoke-virtual {v0}, Lcom/twocloooo/DevNativeActivity;->finish()V
a=0;// 
a=0;//     return-void
a=0;// .end method
}}
