package com.twocloo.com.cn.beans; class AutoBean { void a() { int a;
a=0;// .class public Lcom/twocloo/com/cn/beans/AutoBean;
a=0;// .super Ljava/lang/Object;
a=0;// .source "AutoBean.java"
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field auto_sub:Ljava/lang/String;
a=0;// 
a=0;// .field verify:Ljava/lang/String;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 3
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcom/twocloo/com/cn/beans/AutoBean;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public getAuto_sub()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 8
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/AutoBean;->auto_sub:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getVerify()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 16
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/AutoBean;->verify:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public setAuto_sub(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "auto_sub"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 12
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/AutoBean;->auto_sub:Ljava/lang/String;
a=0;// 
a=0;//     .line 13
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setVerify(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "verify"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/AutoBean;->verify:Ljava/lang/String;
a=0;// 
a=0;//     .line 21
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public toString()Ljava/lang/String;
a=0;//     .locals 2
a=0;// 
a=0;//     .prologue
a=0;//     .line 25
a=0;//     new-instance v0, Ljava/lang/StringBuilder;
a=0;// 
a=0;//     #v0=(UninitRef,Ljava/lang/StringBuilder;);
a=0;//     const-string v1, "AutoBean [auto_sub="
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-direct {v0, v1}, Ljava/lang/StringBuilder;-><init>(Ljava/lang/String;)V
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/StringBuilder;);
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/beans/AutoBean;->auto_sub:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ", verify="
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/beans/AutoBean;->verify:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, "]"
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     return-object v0
a=0;// .end method
}}
