package com.twocloo.com.cn.beans; class Book { void a() { int a;
a=0;// .class public Lcom/twocloo/com/cn/beans/Book;
a=0;// .super Ljava/lang/Object;
a=0;// .source "Book.java"
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field private bookEditer:Ljava/lang/String;
a=0;// 
a=0;// .field private bookId:Ljava/lang/String;
a=0;// 
a=0;// .field private bookName:Ljava/lang/String;
a=0;// 
a=0;// .field private bookPoint:J
a=0;// 
a=0;// .field private bookType:Ljava/lang/String;
a=0;// 
a=0;// .field private isdelete:I
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>()V
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 13
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     .line 12
a=0;//     #p0=(Reference,Lcom/twocloo/com/cn/beans/Book;);
a=0;//     const/16 v0, 0x8
a=0;// 
a=0;//     #v0=(PosByte);
a=0;//     iput v0, p0, Lcom/twocloo/com/cn/beans/Book;->isdelete:I
a=0;// 
a=0;//     .line 15
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public constructor <init>(Ljava/lang/String;)V
a=0;//     .locals 1
a=0;//     .param p1, "bookName"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 17
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     .line 12
a=0;//     #p0=(Reference,Lcom/twocloo/com/cn/beans/Book;);
a=0;//     const/16 v0, 0x8
a=0;// 
a=0;//     #v0=(PosByte);
a=0;//     iput v0, p0, Lcom/twocloo/com/cn/beans/Book;->isdelete:I
a=0;// 
a=0;//     .line 18
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/Book;->bookName:Ljava/lang/String;
a=0;// 
a=0;//     .line 19
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public getBookEditer()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 45
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/Book;->bookEditer:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getBookId()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 21
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/Book;->bookId:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getBookName()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 29
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/Book;->bookName:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getBookPoint()J
a=0;//     .locals 2
a=0;// 
a=0;//     .prologue
a=0;//     .line 53
a=0;//     iget-wide v0, p0, Lcom/twocloo/com/cn/beans/Book;->bookPoint:J
a=0;// 
a=0;//     #v0=(LongLo);v1=(LongHi);
a=0;//     return-wide v0
a=0;// .end method
a=0;// 
a=0;// .method public getBookType()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 37
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/Book;->bookType:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getIsdelete()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 61
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Book;->isdelete:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public setBookEditer(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "bookEditer"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 49
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/Book;->bookEditer:Ljava/lang/String;
a=0;// 
a=0;//     .line 50
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setBookId(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "bookId"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 25
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/Book;->bookId:Ljava/lang/String;
a=0;// 
a=0;//     .line 26
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setBookName(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "bookName"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 33
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/Book;->bookName:Ljava/lang/String;
a=0;// 
a=0;//     .line 34
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setBookPoint(J)V
a=0;//     .locals 0
a=0;//     .param p1, "bookPoint"    # J
a=0;// 
a=0;//     .prologue
a=0;//     .line 57
a=0;//     iput-wide p1, p0, Lcom/twocloo/com/cn/beans/Book;->bookPoint:J
a=0;// 
a=0;//     .line 58
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setBookType(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "bookType"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 41
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/Book;->bookType:Ljava/lang/String;
a=0;// 
a=0;//     .line 42
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setIsdelete(I)V
a=0;//     .locals 0
a=0;//     .param p1, "isdelete"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 65
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Book;->isdelete:I
a=0;// 
a=0;//     .line 66
a=0;//     return-void
a=0;// .end method
}}
