package com.twocloo.com.cn.beans; class BookType { void a() { int a;
a=0;// .class public Lcom/twocloo/com/cn/beans/BookType;
a=0;// .super Ljava/lang/Object;
a=0;// .source "BookType.java"
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field private sortId:Ljava/lang/String;
a=0;// 
a=0;// .field private title:Ljava/lang/String;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 3
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcom/twocloo/com/cn/beans/BookType;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public getSortId()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 7
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/BookType;->sortId:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getTitle()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 13
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/BookType;->title:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public setSortId(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "sortId"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 10
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/BookType;->sortId:Ljava/lang/String;
a=0;// 
a=0;//     .line 11
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setTitle(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "title"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 16
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/BookType;->title:Ljava/lang/String;
a=0;// 
a=0;//     .line 17
a=0;//     return-void
a=0;// .end method
}}
