package com.twocloo.com.cn.beans; class MsgBean { void a() { int a;
a=0;// .class public Lcom/twocloo/com/cn/beans/MsgBean;
a=0;// .super Ljava/lang/Object;
a=0;// .source "MsgBean.java"
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field private content:Ljava/lang/String;
a=0;// 
a=0;// .field private day_max_send_number:Ljava/lang/String;
a=0;// 
a=0;// .field private is_precise:Ljava/lang/String;
a=0;// 
a=0;// .field private is_verity:Ljava/lang/String;
a=0;// 
a=0;// .field private month_max_send_number:Ljava/lang/String;
a=0;// 
a=0;// .field private net_server:I
a=0;// 
a=0;// .field private sp_type:Ljava/lang/String;
a=0;// 
a=0;// .field private to_number:Ljava/lang/String;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 9
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     .line 10
a=0;//     #p0=(Reference,Lcom/twocloo/com/cn/beans/MsgBean;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public constructor <init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)V
a=0;//     .locals 0
a=0;//     .param p1, "content"    # Ljava/lang/String;
a=0;//     .param p2, "to_number"    # Ljava/lang/String;
a=0;//     .param p3, "is_verity"    # Ljava/lang/String;
a=0;//     .param p4, "sp_type"    # Ljava/lang/String;
a=0;//     .param p5, "day_max_send_number"    # Ljava/lang/String;
a=0;//     .param p6, "month_max_send_number"    # Ljava/lang/String;
a=0;//     .param p7, "is_precise"    # Ljava/lang/String;
a=0;//     .param p8, "net_server"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 19
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     .line 20
a=0;//     #p0=(Reference,Lcom/twocloo/com/cn/beans/MsgBean;);
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/MsgBean;->content:Ljava/lang/String;
a=0;// 
a=0;//     .line 21
a=0;//     iput-object p2, p0, Lcom/twocloo/com/cn/beans/MsgBean;->to_number:Ljava/lang/String;
a=0;// 
a=0;//     .line 22
a=0;//     iput-object p3, p0, Lcom/twocloo/com/cn/beans/MsgBean;->is_verity:Ljava/lang/String;
a=0;// 
a=0;//     .line 23
a=0;//     iput-object p4, p0, Lcom/twocloo/com/cn/beans/MsgBean;->sp_type:Ljava/lang/String;
a=0;// 
a=0;//     .line 24
a=0;//     iput-object p5, p0, Lcom/twocloo/com/cn/beans/MsgBean;->day_max_send_number:Ljava/lang/String;
a=0;// 
a=0;//     .line 25
a=0;//     iput-object p6, p0, Lcom/twocloo/com/cn/beans/MsgBean;->month_max_send_number:Ljava/lang/String;
a=0;// 
a=0;//     .line 26
a=0;//     iput-object p7, p0, Lcom/twocloo/com/cn/beans/MsgBean;->is_precise:Ljava/lang/String;
a=0;// 
a=0;//     .line 27
a=0;//     iput p8, p0, Lcom/twocloo/com/cn/beans/MsgBean;->net_server:I
a=0;// 
a=0;//     .line 28
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public getContent()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 36
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/MsgBean;->content:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getDay_max_send_number()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 68
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/MsgBean;->day_max_send_number:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getIs_precise()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 84
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/MsgBean;->is_precise:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getIs_verity()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 52
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/MsgBean;->is_verity:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getMonth_max_send_number()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 76
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/MsgBean;->month_max_send_number:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getNet_server()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 92
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/MsgBean;->net_server:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getSp_type()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 60
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/MsgBean;->sp_type:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getTo_number()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 44
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/MsgBean;->to_number:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public setContent(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "content"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 40
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/MsgBean;->content:Ljava/lang/String;
a=0;// 
a=0;//     .line 41
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setDay_max_send_number(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "day_max_send_number"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 72
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/MsgBean;->day_max_send_number:Ljava/lang/String;
a=0;// 
a=0;//     .line 73
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setIs_precise(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "is_precise"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 88
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/MsgBean;->is_precise:Ljava/lang/String;
a=0;// 
a=0;//     .line 89
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setIs_verity(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "is_verity"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 56
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/MsgBean;->is_verity:Ljava/lang/String;
a=0;// 
a=0;//     .line 57
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setMonth_max_send_number(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "month_max_send_number"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 80
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/MsgBean;->month_max_send_number:Ljava/lang/String;
a=0;// 
a=0;//     .line 81
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setNet_server(I)V
a=0;//     .locals 0
a=0;//     .param p1, "net_server"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 96
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/MsgBean;->net_server:I
a=0;// 
a=0;//     .line 97
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setSp_type(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "sp_type"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 64
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/MsgBean;->sp_type:Ljava/lang/String;
a=0;// 
a=0;//     .line 65
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setTo_number(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "to_number"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 48
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/MsgBean;->to_number:Ljava/lang/String;
a=0;// 
a=0;//     .line 49
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public toString()Ljava/lang/String;
a=0;//     .locals 2
a=0;// 
a=0;//     .prologue
a=0;//     .line 14
a=0;//     new-instance v0, Ljava/lang/StringBuilder;
a=0;// 
a=0;//     #v0=(UninitRef,Ljava/lang/StringBuilder;);
a=0;//     const-string v1, "MsgBean [content="
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-direct {v0, v1}, Ljava/lang/StringBuilder;-><init>(Ljava/lang/String;)V
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/StringBuilder;);
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/beans/MsgBean;->content:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ", to_number="
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/beans/MsgBean;->to_number:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ", is_verity="
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/beans/MsgBean;->is_verity:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ", sp_type="
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/beans/MsgBean;->sp_type:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ", day_max_send_number="
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/beans/MsgBean;->day_max_send_number:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 15
a=0;//     const-string v1, ", month_max_send_number="
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/beans/MsgBean;->month_max_send_number:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ", is_precise="
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/beans/MsgBean;->is_precise:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ", net_server="
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget v1, p0, Lcom/twocloo/com/cn/beans/MsgBean;->net_server:I
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, "]"
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 14
a=0;//     invoke-virtual {v0}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     return-object v0
a=0;// .end method
}}
