package com.twocloo.com.cn.beans; class NewBook { void a() { int a;
a=0;// .class public Lcom/twocloo/com/cn/beans/NewBook;
a=0;// .super Ljava/lang/Object;
a=0;// .source "NewBook.java"
a=0;// 
a=0;// # interfaces
a=0;// .implements Ljava/io/Serializable;
a=0;// 
a=0;// 
a=0;// # static fields
a=0;// .field private static final serialVersionUID:J = -0x4aaa1c51e53819a1L
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field private articleid:Ljava/lang/String;
a=0;// 
a=0;// .field private author:Ljava/lang/String;
a=0;// 
a=0;// .field private description:Ljava/lang/String;
a=0;// 
a=0;// .field private discount:Ljava/lang/String;
a=0;// 
a=0;// .field private finishflag:Ljava/lang/String;
a=0;// 
a=0;// .field private imgURL:Ljava/lang/String;
a=0;// 
a=0;// .field private is_fence:I
a=0;// 
a=0;// .field private is_zongce:I
a=0;// 
a=0;// .field private sortname:Ljava/lang/String;
a=0;// 
a=0;// .field private source:Ljava/lang/String;
a=0;// 
a=0;// .field private title:Ljava/lang/String;
a=0;// 
a=0;// .field private totalviews:Ljava/lang/String;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 5
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcom/twocloo/com/cn/beans/NewBook;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public getArticleid()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 80
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/NewBook;->articleid:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getAuthor()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 112
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/NewBook;->author:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getDescription()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 48
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/NewBook;->description:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getDiscount()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 64
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/NewBook;->discount:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getFinishflag()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 96
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/NewBook;->finishflag:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getImgURL()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 120
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/NewBook;->imgURL:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getIs_fence()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 37
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/NewBook;->is_fence:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getIs_zongce()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 29
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/NewBook;->is_zongce:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getSortname()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 104
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/NewBook;->sortname:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getSource()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 56
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/NewBook;->source:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getTitle()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 88
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/NewBook;->title:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getTotalviews()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 72
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/NewBook;->totalviews:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public setArticleid(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "articleid"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 84
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/NewBook;->articleid:Ljava/lang/String;
a=0;// 
a=0;//     .line 85
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setAuthor(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "author"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 116
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/NewBook;->author:Ljava/lang/String;
a=0;// 
a=0;//     .line 117
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setDescription(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "description"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 52
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/NewBook;->description:Ljava/lang/String;
a=0;// 
a=0;//     .line 53
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setDiscount(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "discount"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 68
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/NewBook;->discount:Ljava/lang/String;
a=0;// 
a=0;//     .line 69
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setFinishflag(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "finishflag"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 100
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/NewBook;->finishflag:Ljava/lang/String;
a=0;// 
a=0;//     .line 101
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setImgURL(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "imgURL"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 124
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/NewBook;->imgURL:Ljava/lang/String;
a=0;// 
a=0;//     .line 125
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setIs_fence(I)V
a=0;//     .locals 0
a=0;//     .param p1, "is_fence"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 41
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/NewBook;->is_fence:I
a=0;// 
a=0;//     .line 42
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setIs_zongce(I)V
a=0;//     .locals 0
a=0;//     .param p1, "is_zongce"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 33
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/NewBook;->is_zongce:I
a=0;// 
a=0;//     .line 34
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setSortname(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "sortname"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 108
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/NewBook;->sortname:Ljava/lang/String;
a=0;// 
a=0;//     .line 109
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setSource(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "source"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 60
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/NewBook;->source:Ljava/lang/String;
a=0;// 
a=0;//     .line 61
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setTitle(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "title"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 92
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/NewBook;->title:Ljava/lang/String;
a=0;// 
a=0;//     .line 93
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setTotalviews(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "totalviews"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 76
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/NewBook;->totalviews:Ljava/lang/String;
a=0;// 
a=0;//     .line 77
a=0;//     return-void
a=0;// .end method
}}
