package com.twocloo.com.cn.beans; class NoticeCheck { void a() { int a;
a=0;// .class public Lcom/twocloo/com/cn/beans/NoticeCheck;
a=0;// .super Ljava/lang/Object;
a=0;// .source "NoticeCheck.java"
a=0;// 
a=0;// 
a=0;// # static fields
a=0;// .field public static final IS_CLOSE:Ljava/lang/String; = "0"
a=0;// 
a=0;// .field public static final IS_OPEN:Ljava/lang/String; = "1"
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field private aid:Ljava/lang/String;
a=0;// 
a=0;// .field private is_sign:Ljava/lang/String;
a=0;// 
a=0;// .field private sign:Ljava/lang/String;
a=0;// 
a=0;// .field private title:Ljava/lang/String;
a=0;// 
a=0;// .field private url:Ljava/lang/String;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 8
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcom/twocloo/com/cn/beans/NoticeCheck;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public getAid()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 32
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/NoticeCheck;->aid:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getIs_sign()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 24
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/NoticeCheck;->is_sign:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getSign()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 40
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/NoticeCheck;->sign:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getTitle()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 48
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/NoticeCheck;->title:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getUrl()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 56
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/NoticeCheck;->url:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public setAid(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "aid"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 36
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/NoticeCheck;->aid:Ljava/lang/String;
a=0;// 
a=0;//     .line 37
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setIs_sign(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "is_sign"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 28
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/NoticeCheck;->is_sign:Ljava/lang/String;
a=0;// 
a=0;//     .line 29
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setSign(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "sign"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 44
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/NoticeCheck;->sign:Ljava/lang/String;
a=0;// 
a=0;//     .line 45
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setTitle(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "title"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 52
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/NoticeCheck;->title:Ljava/lang/String;
a=0;// 
a=0;//     .line 53
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setUrl(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "url"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 60
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/NoticeCheck;->url:Ljava/lang/String;
a=0;// 
a=0;//     .line 61
a=0;//     return-void
a=0;// .end method
}}
