package com.twocloo.com.cn.beans; class OrderAllMsg { void a() { int a;
a=0;// .class public Lcom/twocloo/com/cn/beans/OrderAllMsg;
a=0;// .super Ljava/lang/Object;
a=0;// .source "OrderAllMsg.java"
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field private chapterList:Ljava/util/ArrayList;
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "Ljava/util/ArrayList",
a=0;//             "<",
a=0;//             "Ljava/lang/String;",
a=0;//             ">;"
a=0;//         }
a=0;//     .end annotation
a=0;// .end field
a=0;// 
a=0;// .field private curtime:J
a=0;// 
a=0;// .field private discountCount:F
a=0;// 
a=0;// .field private discountprice:Ljava/lang/String;
a=0;// 
a=0;// .field private isDiscount:Ljava/lang/Boolean;
a=0;// 
a=0;// .field private overtime:J
a=0;// 
a=0;// .field private price:Ljava/lang/String;
a=0;// 
a=0;// .field private remain:Ljava/lang/String;
a=0;// 
a=0;// .field private total_chapter:Ljava/lang/String;
a=0;// 
a=0;// .field private total_price:Ljava/lang/String;
a=0;// 
a=0;// .field private total_vip_word:Ljava/lang/String;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 5
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcom/twocloo/com/cn/beans/OrderAllMsg;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public getChapterList()Ljava/util/ArrayList;
a=0;//     .locals 1
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "()",
a=0;//             "Ljava/util/ArrayList",
a=0;//             "<",
a=0;//             "Ljava/lang/String;",
a=0;//             ">;"
a=0;//         }
a=0;//     .end annotation
a=0;// 
a=0;//     .prologue
a=0;//     .line 99
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/OrderAllMsg;->chapterList:Ljava/util/ArrayList;
a=0;// 
a=0;//     #v0=(Reference,Ljava/util/ArrayList;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getCurtime()J
a=0;//     .locals 2
a=0;// 
a=0;//     .prologue
a=0;//     .line 43
a=0;//     iget-wide v0, p0, Lcom/twocloo/com/cn/beans/OrderAllMsg;->curtime:J
a=0;// 
a=0;//     #v0=(LongLo);v1=(LongHi);
a=0;//     return-wide v0
a=0;// .end method
a=0;// 
a=0;// .method public getDiscountCount()F
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 27
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/OrderAllMsg;->discountCount:F
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getDiscountprice()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 19
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/OrderAllMsg;->discountprice:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getIsDiscount()Ljava/lang/Boolean;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 35
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/OrderAllMsg;->isDiscount:Ljava/lang/Boolean;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/Boolean;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getOvertime()J
a=0;//     .locals 2
a=0;// 
a=0;//     .prologue
a=0;//     .line 51
a=0;//     iget-wide v0, p0, Lcom/twocloo/com/cn/beans/OrderAllMsg;->overtime:J
a=0;// 
a=0;//     #v0=(LongLo);v1=(LongHi);
a=0;//     return-wide v0
a=0;// .end method
a=0;// 
a=0;// .method public getPrice()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 67
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/OrderAllMsg;->price:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getRemain()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 59
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/OrderAllMsg;->remain:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getTotal_chapter()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 91
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/OrderAllMsg;->total_chapter:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getTotal_price()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 75
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/OrderAllMsg;->total_price:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getTotal_vip_word()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 83
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/OrderAllMsg;->total_vip_word:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public setChapterList(Ljava/util/ArrayList;)V
a=0;//     .locals 0
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "(",
a=0;//             "Ljava/util/ArrayList",
a=0;//             "<",
a=0;//             "Ljava/lang/String;",
a=0;//             ">;)V"
a=0;//         }
a=0;//     .end annotation
a=0;// 
a=0;//     .prologue
a=0;//     .line 103
a=0;//     .local p1, "chapterList":Ljava/util/ArrayList;, "Ljava/util/ArrayList<Ljava/lang/String;>;"
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/OrderAllMsg;->chapterList:Ljava/util/ArrayList;
a=0;// 
a=0;//     .line 104
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setCurtime(J)V
a=0;//     .locals 0
a=0;//     .param p1, "curtime"    # J
a=0;// 
a=0;//     .prologue
a=0;//     .line 47
a=0;//     iput-wide p1, p0, Lcom/twocloo/com/cn/beans/OrderAllMsg;->curtime:J
a=0;// 
a=0;//     .line 48
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setDiscountCount(F)V
a=0;//     .locals 0
a=0;//     .param p1, "discountCount"    # F
a=0;// 
a=0;//     .prologue
a=0;//     .line 31
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/OrderAllMsg;->discountCount:F
a=0;// 
a=0;//     .line 32
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setDiscountprice(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "discountprice"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 23
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/OrderAllMsg;->discountprice:Ljava/lang/String;
a=0;// 
a=0;//     .line 24
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setIsDiscount(Ljava/lang/Boolean;)V
a=0;//     .locals 0
a=0;//     .param p1, "isDiscount"    # Ljava/lang/Boolean;
a=0;// 
a=0;//     .prologue
a=0;//     .line 39
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/OrderAllMsg;->isDiscount:Ljava/lang/Boolean;
a=0;// 
a=0;//     .line 40
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setOvertime(J)V
a=0;//     .locals 0
a=0;//     .param p1, "overtime"    # J
a=0;// 
a=0;//     .prologue
a=0;//     .line 55
a=0;//     iput-wide p1, p0, Lcom/twocloo/com/cn/beans/OrderAllMsg;->overtime:J
a=0;// 
a=0;//     .line 56
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setPrice(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "price"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 71
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/OrderAllMsg;->price:Ljava/lang/String;
a=0;// 
a=0;//     .line 72
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setRemain(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "remain"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 63
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/OrderAllMsg;->remain:Ljava/lang/String;
a=0;// 
a=0;//     .line 64
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setTotal_chapter(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "totalChapter"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 95
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/OrderAllMsg;->total_chapter:Ljava/lang/String;
a=0;// 
a=0;//     .line 96
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setTotal_price(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "totalPrice"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 79
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/OrderAllMsg;->total_price:Ljava/lang/String;
a=0;// 
a=0;//     .line 80
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setTotal_vip_word(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "totalVipWord"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 87
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/OrderAllMsg;->total_vip_word:Ljava/lang/String;
a=0;// 
a=0;//     .line 88
a=0;//     return-void
a=0;// .end method
}}
