package com.twocloo.com.cn.beans; class OrderMsg { void a() { int a;
a=0;// .class public Lcom/twocloo/com/cn/beans/OrderMsg;
a=0;// .super Ljava/lang/Object;
a=0;// .source "OrderMsg.java"
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field private calPrice:Ljava/lang/String;
a=0;// 
a=0;// .field private curtime:J
a=0;// 
a=0;// .field private discount:I
a=0;// 
a=0;// .field private overtime:J
a=0;// 
a=0;// .field private price:Ljava/lang/String;
a=0;// 
a=0;// .field private remain:Ljava/lang/String;
a=0;// 
a=0;// .field private text:Ljava/lang/String;
a=0;// 
a=0;// .field private wordCount:Ljava/lang/String;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 3
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcom/twocloo/com/cn/beans/OrderMsg;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public getCalPrice()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 46
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/OrderMsg;->calPrice:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getCurtime()J
a=0;//     .locals 2
a=0;// 
a=0;//     .prologue
a=0;//     .line 14
a=0;//     iget-wide v0, p0, Lcom/twocloo/com/cn/beans/OrderMsg;->curtime:J
a=0;// 
a=0;//     #v0=(LongLo);v1=(LongHi);
a=0;//     return-wide v0
a=0;// .end method
a=0;// 
a=0;// .method public getDiscount()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 18
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/OrderMsg;->discount:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getOvertime()J
a=0;//     .locals 2
a=0;// 
a=0;//     .prologue
a=0;//     .line 30
a=0;//     iget-wide v0, p0, Lcom/twocloo/com/cn/beans/OrderMsg;->overtime:J
a=0;// 
a=0;//     #v0=(LongLo);v1=(LongHi);
a=0;//     return-wide v0
a=0;// .end method
a=0;// 
a=0;// .method public getPrice()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 62
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/OrderMsg;->price:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getRemain()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 38
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/OrderMsg;->remain:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getText()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 70
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/OrderMsg;->text:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getWordCount()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 54
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/OrderMsg;->wordCount:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public setCalPrice(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "calPrice"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 50
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/OrderMsg;->calPrice:Ljava/lang/String;
a=0;// 
a=0;//     .line 51
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setCurtime(J)V
a=0;//     .locals 0
a=0;//     .param p1, "curtime"    # J
a=0;// 
a=0;//     .prologue
a=0;//     .line 26
a=0;//     iput-wide p1, p0, Lcom/twocloo/com/cn/beans/OrderMsg;->curtime:J
a=0;// 
a=0;//     .line 27
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setDiscount(I)V
a=0;//     .locals 0
a=0;//     .param p1, "discount"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 22
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/OrderMsg;->discount:I
a=0;// 
a=0;//     .line 23
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setOvertime(J)V
a=0;//     .locals 0
a=0;//     .param p1, "overtime"    # J
a=0;// 
a=0;//     .prologue
a=0;//     .line 34
a=0;//     iput-wide p1, p0, Lcom/twocloo/com/cn/beans/OrderMsg;->overtime:J
a=0;// 
a=0;//     .line 35
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setPrice(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "price"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 66
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/OrderMsg;->price:Ljava/lang/String;
a=0;// 
a=0;//     .line 67
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setRemain(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "remain"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 42
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/OrderMsg;->remain:Ljava/lang/String;
a=0;// 
a=0;//     .line 43
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setText(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "text"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 74
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/OrderMsg;->text:Ljava/lang/String;
a=0;// 
a=0;//     .line 75
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setWordCount(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "wordCount"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 58
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/OrderMsg;->wordCount:Ljava/lang/String;
a=0;// 
a=0;//     .line 59
a=0;//     return-void
a=0;// .end method
}}
