package com.twocloo.com.cn.beans; class OtherFenceInfo { void a() { int a;
a=0;// .class public Lcom/twocloo/com/cn/beans/OtherFenceInfo;
a=0;// .super Ljava/lang/Object;
a=0;// .source "OtherFenceInfo.java"
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field private fence_articleid:Ljava/lang/String;
a=0;// 
a=0;// .field private fence_num:I
a=0;// 
a=0;// .field private fence_title:Ljava/lang/String;
a=0;// 
a=0;// .field private is_buy:I
a=0;// 
a=0;// .field private price:I
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 3
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcom/twocloo/com/cn/beans/OtherFenceInfo;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public getFence_articleid()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 12
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/OtherFenceInfo;->fence_articleid:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getFence_num()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 28
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/OtherFenceInfo;->fence_num:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getFence_title()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/OtherFenceInfo;->fence_title:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getIs_buy()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 44
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/OtherFenceInfo;->is_buy:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getPrice()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 36
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/OtherFenceInfo;->price:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public setFence_articleid(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "fence_articleid"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 16
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/OtherFenceInfo;->fence_articleid:Ljava/lang/String;
a=0;// 
a=0;//     .line 17
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setFence_num(I)V
a=0;//     .locals 0
a=0;//     .param p1, "fence_num"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 32
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/OtherFenceInfo;->fence_num:I
a=0;// 
a=0;//     .line 33
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setFence_title(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "fence_title"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 24
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/OtherFenceInfo;->fence_title:Ljava/lang/String;
a=0;// 
a=0;//     .line 25
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setIs_buy(I)V
a=0;//     .locals 0
a=0;//     .param p1, "is_buy"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 48
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/OtherFenceInfo;->is_buy:I
a=0;// 
a=0;//     .line 49
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setPrice(I)V
a=0;//     .locals 0
a=0;//     .param p1, "price"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 40
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/OtherFenceInfo;->price:I
a=0;// 
a=0;//     .line 41
a=0;//     return-void
a=0;// .end method
}}
