package com.twocloo.com.cn.beans; class Parter { void a() { int a;
a=0;// .class public Lcom/twocloo/com/cn/beans/Parter;
a=0;// .super Ljava/lang/Object;
a=0;// .source "Parter.java"
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field private ALIPAY_PLUGIN_NAME:Ljava/lang/String;
a=0;// 
a=0;// .field private PARTNER:Ljava/lang/String;
a=0;// 
a=0;// .field private RSA_ALIPAY_PUBLIC:Ljava/lang/String;
a=0;// 
a=0;// .field private RSA_PRIVATE:Ljava/lang/String;
a=0;// 
a=0;// .field private SELLER:Ljava/lang/String;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 3
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcom/twocloo/com/cn/beans/Parter;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public getALIPAY_PLUGIN_NAME()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 12
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/Parter;->ALIPAY_PLUGIN_NAME:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getPARTNER()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/Parter;->PARTNER:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getRSA_ALIPAY_PUBLIC()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 36
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/Parter;->RSA_ALIPAY_PUBLIC:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getRSA_PRIVATE()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 44
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/Parter;->RSA_PRIVATE:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getSELLER()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 28
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/Parter;->SELLER:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public setALIPAY_PLUGIN_NAME(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "aLIPAY_PLUGIN_NAME"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 16
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/Parter;->ALIPAY_PLUGIN_NAME:Ljava/lang/String;
a=0;// 
a=0;//     .line 17
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setPARTNER(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "pARTNER"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 24
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/Parter;->PARTNER:Ljava/lang/String;
a=0;// 
a=0;//     .line 25
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setRSA_ALIPAY_PUBLIC(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "rSA_ALIPAY_PUBLIC"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 40
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/Parter;->RSA_ALIPAY_PUBLIC:Ljava/lang/String;
a=0;// 
a=0;//     .line 41
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setRSA_PRIVATE(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "rSA_PRIVATE"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 48
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/Parter;->RSA_PRIVATE:Ljava/lang/String;
a=0;// 
a=0;//     .line 49
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setSELLER(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "sELLER"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 32
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/Parter;->SELLER:Ljava/lang/String;
a=0;// 
a=0;//     .line 33
a=0;//     return-void
a=0;// .end method
}}
