package com.twocloo.com.cn.beans; class PayedChapterInfo { void a() { int a;
a=0;// .class public Lcom/twocloo/com/cn/beans/PayedChapterInfo;
a=0;// .super Lcom/twocloo/com/cn/beans/Chapterinfo;
a=0;// .source "PayedChapterInfo.java"
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field private isPayed:Z
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>(Lcom/twocloo/com/cn/beans/Chapterinfo;Z)V
a=0;//     .locals 1
a=0;//     .param p1, "info"    # Lcom/twocloo/com/cn/beans/Chapterinfo;
a=0;//     .param p2, "isPayed"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 8
a=0;//     invoke-direct {p0}, Lcom/twocloo/com/cn/beans/Chapterinfo;-><init>()V
a=0;// 
a=0;//     .line 9
a=0;//     #p0=(Reference,Lcom/twocloo/com/cn/beans/PayedChapterInfo;);
a=0;//     invoke-virtual {p1}, Lcom/twocloo/com/cn/beans/Chapterinfo;->getId()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {p0, v0}, Lcom/twocloo/com/cn/beans/PayedChapterInfo;->setId(Ljava/lang/String;)V
a=0;// 
a=0;//     .line 10
a=0;//     invoke-virtual {p1}, Lcom/twocloo/com/cn/beans/Chapterinfo;->getSubhead()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {p0, v0}, Lcom/twocloo/com/cn/beans/PayedChapterInfo;->setSubhead(Ljava/lang/String;)V
a=0;// 
a=0;//     .line 11
a=0;//     invoke-virtual {p1}, Lcom/twocloo/com/cn/beans/Chapterinfo;->getIs_vip()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     invoke-virtual {p0, v0}, Lcom/twocloo/com/cn/beans/PayedChapterInfo;->setIs_vip(I)V
a=0;// 
a=0;//     .line 12
a=0;//     invoke-virtual {p1}, Lcom/twocloo/com/cn/beans/Chapterinfo;->getWord_count()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     invoke-virtual {p0, v0}, Lcom/twocloo/com/cn/beans/PayedChapterInfo;->setWord_count(I)V
a=0;// 
a=0;//     .line 13
a=0;//     invoke-virtual {p1}, Lcom/twocloo/com/cn/beans/Chapterinfo;->getCreate_time()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {p0, v0}, Lcom/twocloo/com/cn/beans/PayedChapterInfo;->setCreate_time(Ljava/lang/String;)V
a=0;// 
a=0;//     .line 14
a=0;//     invoke-virtual {p1}, Lcom/twocloo/com/cn/beans/Chapterinfo;->getUpdate_time()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {p0, v0}, Lcom/twocloo/com/cn/beans/PayedChapterInfo;->setUpdate_time(Ljava/lang/String;)V
a=0;// 
a=0;//     .line 15
a=0;//     invoke-virtual {p1}, Lcom/twocloo/com/cn/beans/Chapterinfo;->getStatus()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     invoke-virtual {p0, v0}, Lcom/twocloo/com/cn/beans/PayedChapterInfo;->setStatus(I)V
a=0;// 
a=0;//     .line 16
a=0;//     invoke-virtual {p1}, Lcom/twocloo/com/cn/beans/Chapterinfo;->getDisplayorder()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     invoke-virtual {p0, v0}, Lcom/twocloo/com/cn/beans/PayedChapterInfo;->setDisplayorder(I)V
a=0;// 
a=0;//     .line 17
a=0;//     invoke-virtual {p1}, Lcom/twocloo/com/cn/beans/Chapterinfo;->getPosi()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     invoke-virtual {p0, v0}, Lcom/twocloo/com/cn/beans/PayedChapterInfo;->setPosi(I)V
a=0;// 
a=0;//     .line 18
a=0;//     invoke-virtual {p1}, Lcom/twocloo/com/cn/beans/Chapterinfo;->getLen()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     invoke-virtual {p0, v0}, Lcom/twocloo/com/cn/beans/PayedChapterInfo;->setLen(I)V
a=0;// 
a=0;//     .line 19
a=0;//     invoke-virtual {p1}, Lcom/twocloo/com/cn/beans/Chapterinfo;->getNextid()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {p0, v0}, Lcom/twocloo/com/cn/beans/PayedChapterInfo;->setNextid(Ljava/lang/String;)V
a=0;// 
a=0;//     .line 20
a=0;//     invoke-virtual {p1}, Lcom/twocloo/com/cn/beans/Chapterinfo;->getNextvip()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     invoke-virtual {p0, v0}, Lcom/twocloo/com/cn/beans/PayedChapterInfo;->setNextvip(I)V
a=0;// 
a=0;//     .line 21
a=0;//     invoke-virtual {p1}, Lcom/twocloo/com/cn/beans/Chapterinfo;->getPreid()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {p0, v0}, Lcom/twocloo/com/cn/beans/PayedChapterInfo;->setPreid(Ljava/lang/String;)V
a=0;// 
a=0;//     .line 22
a=0;//     invoke-virtual {p0}, Lcom/twocloo/com/cn/beans/PayedChapterInfo;->getTextjj()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {p0, v0}, Lcom/twocloo/com/cn/beans/PayedChapterInfo;->setTextjj(Ljava/lang/String;)V
a=0;// 
a=0;//     .line 23
a=0;//     invoke-virtual {p1}, Lcom/twocloo/com/cn/beans/Chapterinfo;->getPrevip()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     invoke-virtual {p0, v0}, Lcom/twocloo/com/cn/beans/PayedChapterInfo;->setPrevip(I)V
a=0;// 
a=0;//     .line 24
a=0;//     invoke-virtual {p1}, Lcom/twocloo/com/cn/beans/Chapterinfo;->getCurF()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     invoke-virtual {p0, v0}, Lcom/twocloo/com/cn/beans/PayedChapterInfo;->setCurF(I)V
a=0;// 
a=0;//     .line 25
a=0;//     invoke-virtual {p0, p2}, Lcom/twocloo/com/cn/beans/PayedChapterInfo;->setPayed(Z)V
a=0;// 
a=0;//     .line 26
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public isPayed()Z
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 31
a=0;//     iget-boolean v0, p0, Lcom/twocloo/com/cn/beans/PayedChapterInfo;->isPayed:Z
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public setPayed(Z)V
a=0;//     .locals 0
a=0;//     .param p1, "isPayed"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 35
a=0;//     iput-boolean p1, p0, Lcom/twocloo/com/cn/beans/PayedChapterInfo;->isPayed:Z
a=0;// 
a=0;//     .line 36
a=0;//     return-void
a=0;// .end method
}}
