package com.twocloo.com.cn.beans; class RDBook { void a() { int a;
a=0;// .class public Lcom/twocloo/com/cn/beans/RDBook;
a=0;// .super Ljava/lang/Object;
a=0;// .source "RDBook.java"
a=0;// 
a=0;// # interfaces
a=0;// .implements Ljava/io/Serializable;
a=0;// 
a=0;// 
a=0;// # static fields
a=0;// .field private static final serialVersionUID:J = 0x3e549023229d6384L
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field private articleId:Ljava/lang/String;
a=0;// 
a=0;// .field private bookFile:Ljava/lang/String;
a=0;// 
a=0;// .field private bookName:Ljava/lang/String;
a=0;// 
a=0;// .field private code:Ljava/lang/String;
a=0;// 
a=0;// .field private discount:I
a=0;// 
a=0;// .field private finishflag:I
a=0;// 
a=0;// .field private id:J
a=0;// 
a=0;// .field private index_:I
a=0;// 
a=0;// .field private isOL:I
a=0;// 
a=0;// .field private isVip:I
a=0;// 
a=0;// .field private is_discount_book:I
a=0;// 
a=0;// .field private nextId:Ljava/lang/String;
a=0;// 
a=0;// .field private nextVip:I
a=0;// 
a=0;// .field private order:I
a=0;// 
a=0;// .field private orderMsg:Lcom/twocloo/com/cn/beans/OrderMsg;
a=0;// 
a=0;// .field private posi:I
a=0;// 
a=0;// .field private preId:Ljava/lang/String;
a=0;// 
a=0;// .field private preVip:I
a=0;// 
a=0;// .field private text:Ljava/lang/String;
a=0;// 
a=0;// .field private textId:Ljava/lang/String;
a=0;// 
a=0;// .field private textTitle:Ljava/lang/String;
a=0;// 
a=0;// .field private totalprice:D
a=0;// 
a=0;// .field private wordCount:I
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 5
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcom/twocloo/com/cn/beans/RDBook;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public getArticleId()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 104
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/RDBook;->articleId:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getBookFile()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 208
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/RDBook;->bookFile:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getBookName()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 184
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/RDBook;->bookName:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getCode()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 120
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/RDBook;->code:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getDiscount()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 76
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/RDBook;->discount:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getFinishflag()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 224
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/RDBook;->finishflag:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getId()J
a=0;//     .locals 2
a=0;// 
a=0;//     .prologue
a=0;//     .line 192
a=0;//     iget-wide v0, p0, Lcom/twocloo/com/cn/beans/RDBook;->id:J
a=0;// 
a=0;//     #v0=(LongLo);v1=(LongHi);
a=0;//     return-wide v0
a=0;// .end method
a=0;// 
a=0;// .method public getIndex_()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 232
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/RDBook;->index_:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getIsOL()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 200
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/RDBook;->isOL:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getIsVip()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 128
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/RDBook;->isVip:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getIs_discount_book()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 68
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/RDBook;->is_discount_book:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getNextId()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 144
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/RDBook;->nextId:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getNextVip()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 160
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/RDBook;->nextVip:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getOrder()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 216
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/RDBook;->order:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getOrderMsg()Lcom/twocloo/com/cn/beans/OrderMsg;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 168
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/RDBook;->orderMsg:Lcom/twocloo/com/cn/beans/OrderMsg;
a=0;// 
a=0;//     #v0=(Reference,Lcom/twocloo/com/cn/beans/OrderMsg;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getPosi()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 176
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/RDBook;->posi:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getPreId()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 136
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/RDBook;->preId:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getPreVip()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 152
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/RDBook;->preVip:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getText()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 112
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/RDBook;->text:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getTextId()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 64
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/RDBook;->textId:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getTextTitle()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 88
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/RDBook;->textTitle:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getTotalprice()D
a=0;//     .locals 2
a=0;// 
a=0;//     .prologue
a=0;//     .line 56
a=0;//     iget-wide v0, p0, Lcom/twocloo/com/cn/beans/RDBook;->totalprice:D
a=0;// 
a=0;//     #v0=(DoubleLo);v1=(DoubleHi);
a=0;//     return-wide v0
a=0;// .end method
a=0;// 
a=0;// .method public getWordCount()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 96
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/RDBook;->wordCount:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public setArticleId(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "articleId"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 108
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/RDBook;->articleId:Ljava/lang/String;
a=0;// 
a=0;//     .line 109
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setBookFile(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "bookFile"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 212
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/RDBook;->bookFile:Ljava/lang/String;
a=0;// 
a=0;//     .line 213
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setBookName(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "bookName"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 188
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/RDBook;->bookName:Ljava/lang/String;
a=0;// 
a=0;//     .line 189
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setCode(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "code"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 124
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/RDBook;->code:Ljava/lang/String;
a=0;// 
a=0;//     .line 125
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setDiscount(I)V
a=0;//     .locals 0
a=0;//     .param p1, "discount"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 80
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/RDBook;->discount:I
a=0;// 
a=0;//     .line 81
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setFinishflag(I)V
a=0;//     .locals 0
a=0;//     .param p1, "finishflag"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 228
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/RDBook;->finishflag:I
a=0;// 
a=0;//     .line 229
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setId(J)V
a=0;//     .locals 0
a=0;//     .param p1, "id"    # J
a=0;// 
a=0;//     .prologue
a=0;//     .line 196
a=0;//     iput-wide p1, p0, Lcom/twocloo/com/cn/beans/RDBook;->id:J
a=0;// 
a=0;//     .line 197
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setIndex_(I)V
a=0;//     .locals 0
a=0;//     .param p1, "index_"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 236
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/RDBook;->index_:I
a=0;// 
a=0;//     .line 237
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setIsOL(I)V
a=0;//     .locals 0
a=0;//     .param p1, "isOL"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 204
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/RDBook;->isOL:I
a=0;// 
a=0;//     .line 205
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setIsVip(I)V
a=0;//     .locals 0
a=0;//     .param p1, "isVip"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 132
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/RDBook;->isVip:I
a=0;// 
a=0;//     .line 133
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setIs_discount_book(I)V
a=0;//     .locals 0
a=0;//     .param p1, "is_discount_book"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 72
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/RDBook;->is_discount_book:I
a=0;// 
a=0;//     .line 73
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setNextId(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "nextId"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 148
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/RDBook;->nextId:Ljava/lang/String;
a=0;// 
a=0;//     .line 149
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setNextVip(I)V
a=0;//     .locals 0
a=0;//     .param p1, "nextVip"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 164
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/RDBook;->nextVip:I
a=0;// 
a=0;//     .line 165
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setOrder(I)V
a=0;//     .locals 0
a=0;//     .param p1, "order"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 220
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/RDBook;->order:I
a=0;// 
a=0;//     .line 221
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setOrderMsg(Lcom/twocloo/com/cn/beans/OrderMsg;)V
a=0;//     .locals 0
a=0;//     .param p1, "orderMsg"    # Lcom/twocloo/com/cn/beans/OrderMsg;
a=0;// 
a=0;//     .prologue
a=0;//     .line 172
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/RDBook;->orderMsg:Lcom/twocloo/com/cn/beans/OrderMsg;
a=0;// 
a=0;//     .line 173
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setPosi(I)V
a=0;//     .locals 0
a=0;//     .param p1, "posi"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 180
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/RDBook;->posi:I
a=0;// 
a=0;//     .line 181
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setPreId(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "preId"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 140
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/RDBook;->preId:Ljava/lang/String;
a=0;// 
a=0;//     .line 141
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setPreVip(I)V
a=0;//     .locals 0
a=0;//     .param p1, "preVip"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 156
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/RDBook;->preVip:I
a=0;// 
a=0;//     .line 157
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setText(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "text"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 116
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/RDBook;->text:Ljava/lang/String;
a=0;// 
a=0;//     .line 117
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setTextId(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "textId"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 84
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/RDBook;->textId:Ljava/lang/String;
a=0;// 
a=0;//     .line 85
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setTextTitle(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "textTitle"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 92
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/RDBook;->textTitle:Ljava/lang/String;
a=0;// 
a=0;//     .line 93
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setTotalprice(D)V
a=0;//     .locals 0
a=0;//     .param p1, "totalprice"    # D
a=0;// 
a=0;//     .prologue
a=0;//     .line 60
a=0;//     iput-wide p1, p0, Lcom/twocloo/com/cn/beans/RDBook;->totalprice:D
a=0;// 
a=0;//     .line 61
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setWordCount(I)V
a=0;//     .locals 0
a=0;//     .param p1, "wordCount"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 100
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/RDBook;->wordCount:I
a=0;// 
a=0;//     .line 101
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public toString()Ljava/lang/String;
a=0;//     .locals 3
a=0;// 
a=0;//     .prologue
a=0;//     .line 14
a=0;//     new-instance v0, Ljava/lang/StringBuilder;
a=0;// 
a=0;//     #v0=(UninitRef,Ljava/lang/StringBuilder;);
a=0;//     const-string v1, "RDBook [id="
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-direct {v0, v1}, Ljava/lang/StringBuilder;-><init>(Ljava/lang/String;)V
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/StringBuilder;);
a=0;//     iget-wide v1, p0, Lcom/twocloo/com/cn/beans/RDBook;->id:J
a=0;// 
a=0;//     #v1=(LongLo);v2=(LongHi);
a=0;//     invoke-virtual {v0, v1, v2}, Ljava/lang/StringBuilder;->append(J)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ", articleId="
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/beans/RDBook;->articleId:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ", textId="
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/beans/RDBook;->textId:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ", textTitle="
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/beans/RDBook;->textTitle:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ", bookFile="
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 15
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/beans/RDBook;->bookFile:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ", wordCount="
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget v1, p0, Lcom/twocloo/com/cn/beans/RDBook;->wordCount:I
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ", order="
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget v1, p0, Lcom/twocloo/com/cn/beans/RDBook;->order:I
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ", text="
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/beans/RDBook;->text:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ", code="
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/beans/RDBook;->code:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ", isVip="
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget v1, p0, Lcom/twocloo/com/cn/beans/RDBook;->isVip:I
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 16
a=0;//     const-string v1, ", preId="
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/beans/RDBook;->preId:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ", preVip="
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget v1, p0, Lcom/twocloo/com/cn/beans/RDBook;->preVip:I
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ", nextId="
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/beans/RDBook;->nextId:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ", nextVip="
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget v1, p0, Lcom/twocloo/com/cn/beans/RDBook;->nextVip:I
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ", orderMsg="
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/beans/RDBook;->orderMsg:Lcom/twocloo/com/cn/beans/OrderMsg;
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/Object;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 17
a=0;//     const-string v1, ", posi="
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget v1, p0, Lcom/twocloo/com/cn/beans/RDBook;->posi:I
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ", bookName="
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/beans/RDBook;->bookName:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ", isOL="
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget v1, p0, Lcom/twocloo/com/cn/beans/RDBook;->isOL:I
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ", finishflag="
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget v1, p0, Lcom/twocloo/com/cn/beans/RDBook;->finishflag:I
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ", is_discount_book="
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 18
a=0;//     iget v1, p0, Lcom/twocloo/com/cn/beans/RDBook;->is_discount_book:I
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ", totalprice="
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-wide v1, p0, Lcom/twocloo/com/cn/beans/RDBook;->totalprice:D
a=0;// 
a=0;//     #v1=(DoubleLo);v2=(DoubleHi);
a=0;//     invoke-virtual {v0, v1, v2}, Ljava/lang/StringBuilder;->append(D)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ", discount="
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget v1, p0, Lcom/twocloo/com/cn/beans/RDBook;->discount:I
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, "]"
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 14
a=0;//     invoke-virtual {v0}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     return-object v0
a=0;// .end method
}}
