package com.twocloo.com.cn.beans; class RecordContent { void a() { int a;
a=0;// .class public Lcom/twocloo/com/cn/beans/RecordContent;
a=0;// .super Ljava/lang/Object;
a=0;// .source "RecordContent.java"
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field private record_content:Ljava/lang/String;
a=0;// 
a=0;// .field private time:Ljava/lang/String;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 4
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcom/twocloo/com/cn/beans/RecordContent;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public getRecord_content()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 10
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/RecordContent;->record_content:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getTime()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 18
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/RecordContent;->time:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public setRecord_content(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "record_content"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 14
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/RecordContent;->record_content:Ljava/lang/String;
a=0;// 
a=0;//     .line 15
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setTime(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "time"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 22
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/RecordContent;->time:Ljava/lang/String;
a=0;// 
a=0;//     .line 23
a=0;//     return-void
a=0;// .end method
}}
