package com.twocloo.com.cn.beans; class SearchHistroyBean { void a() { int a;
a=0;// .class public Lcom/twocloo/com/cn/beans/SearchHistroyBean;
a=0;// .super Ljava/lang/Object;
a=0;// .source "SearchHistroyBean.java"
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field private content:Ljava/lang/String;
a=0;// 
a=0;// .field private id:J
a=0;// 
a=0;// .field private time:Ljava/lang/String;
a=0;// 
a=0;// .field private uid:Ljava/lang/String;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>()V
a=0;//     .locals 2
a=0;// 
a=0;//     .prologue
a=0;//     .line 7
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     .line 8
a=0;//     #p0=(Reference,Lcom/twocloo/com/cn/beans/SearchHistroyBean;);
a=0;//     const-wide/16 v0, -0x1
a=0;// 
a=0;//     #v0=(LongLo);v1=(LongHi);
a=0;//     iput-wide v0, p0, Lcom/twocloo/com/cn/beans/SearchHistroyBean;->id:J
a=0;// 
a=0;//     .line 7
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public getContent()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 30
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/SearchHistroyBean;->content:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getId()J
a=0;//     .locals 2
a=0;// 
a=0;//     .prologue
a=0;//     .line 14
a=0;//     iget-wide v0, p0, Lcom/twocloo/com/cn/beans/SearchHistroyBean;->id:J
a=0;// 
a=0;//     #v0=(LongLo);v1=(LongHi);
a=0;//     return-wide v0
a=0;// .end method
a=0;// 
a=0;// .method public getTime()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 38
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/SearchHistroyBean;->time:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getUid()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 22
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/SearchHistroyBean;->uid:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public setContent(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "content"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 34
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/SearchHistroyBean;->content:Ljava/lang/String;
a=0;// 
a=0;//     .line 35
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setId(J)V
a=0;//     .locals 0
a=0;//     .param p1, "id"    # J
a=0;// 
a=0;//     .prologue
a=0;//     .line 18
a=0;//     iput-wide p1, p0, Lcom/twocloo/com/cn/beans/SearchHistroyBean;->id:J
a=0;// 
a=0;//     .line 19
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setTime(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "time"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 42
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/SearchHistroyBean;->time:Ljava/lang/String;
a=0;// 
a=0;//     .line 43
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setUid(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "uid"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 26
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/SearchHistroyBean;->uid:Ljava/lang/String;
a=0;// 
a=0;//     .line 27
a=0;//     return-void
a=0;// .end method
}}
