package com.twocloo.com.cn.beans; class Shubenxinxiye { void a() { int a;
a=0;// .class public Lcom/twocloo/com/cn/beans/Shubenxinxiye;
a=0;// .super Ljava/lang/Object;
a=0;// .source "Shubenxinxiye.java"
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field private articleid:Ljava/lang/String;
a=0;// 
a=0;// .field private author:Ljava/lang/String;
a=0;// 
a=0;// .field private authorid:Ljava/lang/String;
a=0;// 
a=0;// .field private baoyueStatue:I
a=0;// 
a=0;// .field private book_logo:Ljava/lang/String;
a=0;// 
a=0;// .field private chapter_title:Ljava/lang/String;
a=0;// 
a=0;// .field private dashang:I
a=0;// 
a=0;// .field private description:Ljava/lang/String;
a=0;// 
a=0;// .field private fence_price:Ljava/lang/String;
a=0;// 
a=0;// .field private finishflag:I
a=0;// 
a=0;// .field private first_chapter_id:Ljava/lang/String;
a=0;// 
a=0;// .field private first_chapter_is_vip:I
a=0;// 
a=0;// .field private first_vip_chapter_displayorder:I
a=0;// 
a=0;// .field private free_textcount:I
a=0;// 
a=0;// .field private hasfavor:I
a=0;// 
a=0;// .field private hasrecommend:I
a=0;// 
a=0;// .field private is_buy:I
a=0;// 
a=0;// .field private is_fence:I
a=0;// 
a=0;// .field private is_vip:I
a=0;// 
a=0;// .field private is_ykj:Ljava/lang/String;
a=0;// 
a=0;// .field private is_zongce:I
a=0;// 
a=0;// .field private laiyuan:Ljava/lang/String;
a=0;// 
a=0;// .field private order:Ljava/lang/String;
a=0;// 
a=0;// .field private other_fence_info:Ljava/util/ArrayList;
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "Ljava/util/ArrayList",
a=0;//             "<",
a=0;//             "Lcom/twocloo/com/cn/beans/OtherFenceInfo;",
a=0;//             ">;"
a=0;//         }
a=0;//     .end annotation
a=0;// .end field
a=0;// 
a=0;// .field private sortname:Ljava/lang/String;
a=0;// 
a=0;// .field private textcount:I
a=0;// 
a=0;// .field private textid:Ljava/lang/String;
a=0;// 
a=0;// .field private title:Ljava/lang/String;
a=0;// 
a=0;// .field private totalfavor:I
a=0;// 
a=0;// .field private totalviews:I
a=0;// 
a=0;// .field private update_str:Ljava/lang/String;
a=0;// 
a=0;// .field private update_time:Ljava/lang/String;
a=0;// 
a=0;// .field private voters:I
a=0;// 
a=0;// .field private wordtotal:I
a=0;// 
a=0;// .field private zhekou:Ljava/lang/String;
a=0;// 
a=0;// .field private zongce_articleid:Ljava/lang/String;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 11
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcom/twocloo/com/cn/beans/Shubenxinxiye;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public getArticleid()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 117
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->articleid:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getAuthor()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 245
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->author:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getAuthorid()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 165
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->authorid:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getBaoyueStatue()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 189
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->baoyueStatue:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getBook_logo()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 285
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->book_logo:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getChapter_title()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 333
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->chapter_title:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getDashang()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 53
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->dashang:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getDescription()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 237
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->description:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getFence_price()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 125
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->fence_price:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getFinishflag()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 277
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->finishflag:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getFirst_chapter_id()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 229
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->first_chapter_id:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getFirst_chapter_is_vip()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 77
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->first_chapter_is_vip:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getFirst_vip_chapter_displayorder()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 201
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->first_vip_chapter_displayorder:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getFree_textcount()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 317
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->free_textcount:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getHasfavor()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 61
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->hasfavor:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getHasrecommend()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 69
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->hasrecommend:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getIs_buy()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 109
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->is_buy:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getIs_fence()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 157
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->is_fence:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getIs_vip()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 217
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->is_vip:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getIs_ykj()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 141
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->is_ykj:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getIs_zongce()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 149
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->is_zongce:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getLaiyuan()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 181
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->laiyuan:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getOrder()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 325
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->order:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getOther_fence_info()Ljava/util/ArrayList;
a=0;//     .locals 1
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "()",
a=0;//             "Ljava/util/ArrayList",
a=0;//             "<",
a=0;//             "Lcom/twocloo/com/cn/beans/OtherFenceInfo;",
a=0;//             ">;"
a=0;//         }
a=0;//     .end annotation
a=0;// 
a=0;//     .prologue
a=0;//     .line 133
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->other_fence_info:Ljava/util/ArrayList;
a=0;// 
a=0;//     #v0=(Reference,Ljava/util/ArrayList;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getSortname()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 253
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->sortname:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getTextcount()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 309
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->textcount:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getTextid()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 197
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->textid:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getTitle()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 293
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->title:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getTotalfavor()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 93
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->totalfavor:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getTotalviews()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 269
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->totalviews:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getUpdate_str()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 85
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->update_str:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getUpdate_time()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 341
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->update_time:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getVoters()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 301
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->voters:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getWordtotal()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 261
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->wordtotal:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getZhekou()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 173
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->zhekou:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getZongce_articleid()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 101
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->zongce_articleid:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public setArticleid(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "articleid"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 121
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->articleid:Ljava/lang/String;
a=0;// 
a=0;//     .line 122
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setAuthor(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "author"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 249
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->author:Ljava/lang/String;
a=0;// 
a=0;//     .line 250
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setAuthorid(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "authorid"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 169
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->authorid:Ljava/lang/String;
a=0;// 
a=0;//     .line 170
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setBaoyueStatue(I)V
a=0;//     .locals 0
a=0;//     .param p1, "baoyueStatue"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 193
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->baoyueStatue:I
a=0;// 
a=0;//     .line 194
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setBook_logo(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "book_logo"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 289
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->book_logo:Ljava/lang/String;
a=0;// 
a=0;//     .line 290
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setChapter_title(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "chapter_title"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 337
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->chapter_title:Ljava/lang/String;
a=0;// 
a=0;//     .line 338
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setDashang(I)V
a=0;//     .locals 0
a=0;//     .param p1, "dashang"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 57
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->dashang:I
a=0;// 
a=0;//     .line 58
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setDescription(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "description"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 241
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->description:Ljava/lang/String;
a=0;// 
a=0;//     .line 242
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setFence_price(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "fence_price"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 129
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->fence_price:Ljava/lang/String;
a=0;// 
a=0;//     .line 130
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setFinishflag(I)V
a=0;//     .locals 0
a=0;//     .param p1, "finishflag"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 281
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->finishflag:I
a=0;// 
a=0;//     .line 282
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setFirst_chapter_id(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "first_chapter_id"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 233
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->first_chapter_id:Ljava/lang/String;
a=0;// 
a=0;//     .line 234
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setFirst_chapter_is_vip(I)V
a=0;//     .locals 0
a=0;//     .param p1, "first_chapter_is_vip"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 81
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->first_chapter_is_vip:I
a=0;// 
a=0;//     .line 82
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setFirst_vip_chapter_displayorder(I)V
a=0;//     .locals 0
a=0;//     .param p1, "first_vip_chapter_displayorder"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 205
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->first_vip_chapter_displayorder:I
a=0;// 
a=0;//     .line 206
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setFree_textcount(I)V
a=0;//     .locals 0
a=0;//     .param p1, "free_textcount"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 321
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->free_textcount:I
a=0;// 
a=0;//     .line 322
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setHasfavor(I)V
a=0;//     .locals 0
a=0;//     .param p1, "hasfavor"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 65
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->hasfavor:I
a=0;// 
a=0;//     .line 66
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setHasrecommend(I)V
a=0;//     .locals 0
a=0;//     .param p1, "hasrecommend"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 73
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->hasrecommend:I
a=0;// 
a=0;//     .line 74
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setIs_buy(I)V
a=0;//     .locals 0
a=0;//     .param p1, "is_buy"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 113
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->is_buy:I
a=0;// 
a=0;//     .line 114
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setIs_fence(I)V
a=0;//     .locals 0
a=0;//     .param p1, "is_fence"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 161
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->is_fence:I
a=0;// 
a=0;//     .line 162
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setIs_vip(I)V
a=0;//     .locals 0
a=0;//     .param p1, "is_vip"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 221
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->is_vip:I
a=0;// 
a=0;//     .line 222
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setIs_ykj(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "is_ykj"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 145
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->is_ykj:Ljava/lang/String;
a=0;// 
a=0;//     .line 146
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setIs_zongce(I)V
a=0;//     .locals 0
a=0;//     .param p1, "is_zongce"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 153
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->is_zongce:I
a=0;// 
a=0;//     .line 154
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setLaiyuan(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "laiyuan"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 185
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->laiyuan:Ljava/lang/String;
a=0;// 
a=0;//     .line 186
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setOrder(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "order"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 329
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->order:Ljava/lang/String;
a=0;// 
a=0;//     .line 330
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setOther_fence_info(Ljava/util/ArrayList;)V
a=0;//     .locals 0
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "(",
a=0;//             "Ljava/util/ArrayList",
a=0;//             "<",
a=0;//             "Lcom/twocloo/com/cn/beans/OtherFenceInfo;",
a=0;//             ">;)V"
a=0;//         }
a=0;//     .end annotation
a=0;// 
a=0;//     .prologue
a=0;//     .line 137
a=0;//     .local p1, "other_fence_info":Ljava/util/ArrayList;, "Ljava/util/ArrayList<Lcom/twocloo/com/cn/beans/OtherFenceInfo;>;"
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->other_fence_info:Ljava/util/ArrayList;
a=0;// 
a=0;//     .line 138
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setSortname(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "sortname"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 257
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->sortname:Ljava/lang/String;
a=0;// 
a=0;//     .line 258
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setTextcount(I)V
a=0;//     .locals 0
a=0;//     .param p1, "textcount"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 313
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->textcount:I
a=0;// 
a=0;//     .line 314
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setTextid(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "textid"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 225
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->textid:Ljava/lang/String;
a=0;// 
a=0;//     .line 226
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setTitle(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "title"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 297
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->title:Ljava/lang/String;
a=0;// 
a=0;//     .line 298
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setTotalfavor(I)V
a=0;//     .locals 0
a=0;//     .param p1, "totalfavor"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 97
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->totalfavor:I
a=0;// 
a=0;//     .line 98
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setTotalviews(I)V
a=0;//     .locals 0
a=0;//     .param p1, "totalviews"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 273
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->totalviews:I
a=0;// 
a=0;//     .line 274
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setUpdate_str(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "update_str"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 89
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->update_str:Ljava/lang/String;
a=0;// 
a=0;//     .line 90
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setUpdate_time(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "update_time"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 345
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->update_time:Ljava/lang/String;
a=0;// 
a=0;//     .line 346
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setVoters(I)V
a=0;//     .locals 0
a=0;//     .param p1, "voters"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 305
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->voters:I
a=0;// 
a=0;//     .line 306
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setWordtotal(I)V
a=0;//     .locals 0
a=0;//     .param p1, "wordtotal"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 265
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->wordtotal:I
a=0;// 
a=0;//     .line 266
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setZhekou(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "zhekou"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 177
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->zhekou:Ljava/lang/String;
a=0;// 
a=0;//     .line 178
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setZongce_articleid(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "zongce_articleid"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 105
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/Shubenxinxiye;->zongce_articleid:Ljava/lang/String;
a=0;// 
a=0;//     .line 106
a=0;//     return-void
a=0;// .end method
}}
