package com.twocloo.com.cn.beans; class Shuping_huifuinfo { void a() { int a;
a=0;// .class public Lcom/twocloo/com/cn/beans/Shuping_huifuinfo;
a=0;// .super Ljava/lang/Object;
a=0;// .source "Shuping_huifuinfo.java"
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field private anonymous:I
a=0;// 
a=0;// .field private attachment:I
a=0;// 
a=0;// .field private author:Ljava/lang/String;
a=0;// 
a=0;// .field private authorid:I
a=0;// 
a=0;// .field private bbcodeoff:I
a=0;// 
a=0;// .field private dateline:Ljava/lang/String;
a=0;// 
a=0;// .field private fid:I
a=0;// 
a=0;// .field private first:I
a=0;// 
a=0;// .field private htmlon:I
a=0;// 
a=0;// .field private invisible:I
a=0;// 
a=0;// .field private message:Ljava/lang/String;
a=0;// 
a=0;// .field private parseurloff:I
a=0;// 
a=0;// .field private pid:I
a=0;// 
a=0;// .field private rate:I
a=0;// 
a=0;// .field private ratetimes:I
a=0;// 
a=0;// .field private smileyoff:I
a=0;// 
a=0;// .field private status:I
a=0;// 
a=0;// .field private subject:Ljava/lang/String;
a=0;// 
a=0;// .field private tid:I
a=0;// 
a=0;// .field private useip:Ljava/lang/String;
a=0;// 
a=0;// .field private usesig:I
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 3
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcom/twocloo/com/cn/beans/Shuping_huifuinfo;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public getAnonymous()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 115
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shuping_huifuinfo;->anonymous:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getAttachment()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 163
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shuping_huifuinfo;->attachment:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getAuthor()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 59
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/Shuping_huifuinfo;->author:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getAuthorid()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 67
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shuping_huifuinfo;->authorid:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getBbcodeoff()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 139
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shuping_huifuinfo;->bbcodeoff:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getDateline()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 83
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/Shuping_huifuinfo;->dateline:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getFid()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 35
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shuping_huifuinfo;->fid:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getFirst()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 51
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shuping_huifuinfo;->first:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getHtmlon()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 131
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shuping_huifuinfo;->htmlon:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getInvisible()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 107
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shuping_huifuinfo;->invisible:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getMessage()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 91
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/Shuping_huifuinfo;->message:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getParseurloff()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 155
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shuping_huifuinfo;->parseurloff:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getPid()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 27
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shuping_huifuinfo;->pid:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getRate()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 171
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shuping_huifuinfo;->rate:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getRatetimes()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 179
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shuping_huifuinfo;->ratetimes:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getSmileyoff()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 147
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shuping_huifuinfo;->smileyoff:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getStatus()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 187
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shuping_huifuinfo;->status:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getSubject()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 75
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/Shuping_huifuinfo;->subject:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getTid()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 43
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shuping_huifuinfo;->tid:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getUseip()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 99
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/Shuping_huifuinfo;->useip:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getUsesig()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 123
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shuping_huifuinfo;->usesig:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public setAnonymous(I)V
a=0;//     .locals 0
a=0;//     .param p1, "anonymous"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 119
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shuping_huifuinfo;->anonymous:I
a=0;// 
a=0;//     .line 120
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setAttachment(I)V
a=0;//     .locals 0
a=0;//     .param p1, "attachment"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 167
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shuping_huifuinfo;->attachment:I
a=0;// 
a=0;//     .line 168
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setAuthor(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "author"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 63
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/Shuping_huifuinfo;->author:Ljava/lang/String;
a=0;// 
a=0;//     .line 64
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setAuthorid(I)V
a=0;//     .locals 0
a=0;//     .param p1, "authorid"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 71
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shuping_huifuinfo;->authorid:I
a=0;// 
a=0;//     .line 72
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setBbcodeoff(I)V
a=0;//     .locals 0
a=0;//     .param p1, "bbcodeoff"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 143
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shuping_huifuinfo;->bbcodeoff:I
a=0;// 
a=0;//     .line 144
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setDateline(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "dateline"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 87
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/Shuping_huifuinfo;->dateline:Ljava/lang/String;
a=0;// 
a=0;//     .line 88
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setFid(I)V
a=0;//     .locals 0
a=0;//     .param p1, "fid"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 39
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shuping_huifuinfo;->fid:I
a=0;// 
a=0;//     .line 40
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setFirst(I)V
a=0;//     .locals 0
a=0;//     .param p1, "first"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 55
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shuping_huifuinfo;->first:I
a=0;// 
a=0;//     .line 56
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setHtmlon(I)V
a=0;//     .locals 0
a=0;//     .param p1, "htmlon"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 135
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shuping_huifuinfo;->htmlon:I
a=0;// 
a=0;//     .line 136
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setInvisible(I)V
a=0;//     .locals 0
a=0;//     .param p1, "invisible"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 111
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shuping_huifuinfo;->invisible:I
a=0;// 
a=0;//     .line 112
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setMessage(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "message"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 95
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/Shuping_huifuinfo;->message:Ljava/lang/String;
a=0;// 
a=0;//     .line 96
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setParseurloff(I)V
a=0;//     .locals 0
a=0;//     .param p1, "parseurloff"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 159
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shuping_huifuinfo;->parseurloff:I
a=0;// 
a=0;//     .line 160
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setPid(I)V
a=0;//     .locals 0
a=0;//     .param p1, "pid"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 31
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shuping_huifuinfo;->pid:I
a=0;// 
a=0;//     .line 32
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setRate(I)V
a=0;//     .locals 0
a=0;//     .param p1, "rate"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 175
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shuping_huifuinfo;->rate:I
a=0;// 
a=0;//     .line 176
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setRatetimes(I)V
a=0;//     .locals 0
a=0;//     .param p1, "ratetimes"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 183
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shuping_huifuinfo;->ratetimes:I
a=0;// 
a=0;//     .line 184
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setSmileyoff(I)V
a=0;//     .locals 0
a=0;//     .param p1, "smileyoff"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 151
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shuping_huifuinfo;->smileyoff:I
a=0;// 
a=0;//     .line 152
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setStatus(I)V
a=0;//     .locals 0
a=0;//     .param p1, "status"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 191
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shuping_huifuinfo;->status:I
a=0;// 
a=0;//     .line 192
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setSubject(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "subject"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 79
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/Shuping_huifuinfo;->subject:Ljava/lang/String;
a=0;// 
a=0;//     .line 80
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setTid(I)V
a=0;//     .locals 0
a=0;//     .param p1, "tid"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 47
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shuping_huifuinfo;->tid:I
a=0;// 
a=0;//     .line 48
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setUseip(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "useip"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 103
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/Shuping_huifuinfo;->useip:Ljava/lang/String;
a=0;// 
a=0;//     .line 104
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setUsesig(I)V
a=0;//     .locals 0
a=0;//     .param p1, "usesig"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 127
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shuping_huifuinfo;->usesig:I
a=0;// 
a=0;//     .line 128
a=0;//     return-void
a=0;// .end method
}}
