package com.twocloo.com.cn.beans; class Shuping_maininfo { void a() { int a;
a=0;// .class public Lcom/twocloo/com/cn/beans/Shuping_maininfo;
a=0;// .super Ljava/lang/Object;
a=0;// .source "Shuping_maininfo.java"
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field private attachment:I
a=0;// 
a=0;// .field private author:Ljava/lang/String;
a=0;// 
a=0;// .field private author_replied:I
a=0;// 
a=0;// .field private authorid:I
a=0;// 
a=0;// .field private blog:I
a=0;// 
a=0;// .field private closed:I
a=0;// 
a=0;// .field private dateline:Ljava/lang/String;
a=0;// 
a=0;// .field private digest:I
a=0;// 
a=0;// .field private displayorder:I
a=0;// 
a=0;// .field private fid:I
a=0;// 
a=0;// .field private highlight:I
a=0;// 
a=0;// .field private iconid:I
a=0;// 
a=0;// .field private itemid:I
a=0;// 
a=0;// .field private lastpost:Ljava/lang/String;
a=0;// 
a=0;// .field private lastposter:Ljava/lang/String;
a=0;// 
a=0;// .field private lastposterid:Ljava/lang/String;
a=0;// 
a=0;// .field private logo:Ljava/lang/String;
a=0;// 
a=0;// .field private message:Ljava/lang/String;
a=0;// 
a=0;// .field private moderated:I
a=0;// 
a=0;// .field private pid:I
a=0;// 
a=0;// .field private price:I
a=0;// 
a=0;// .field private rate:I
a=0;// 
a=0;// .field private readperm:I
a=0;// 
a=0;// .field private replies:I
a=0;// 
a=0;// .field private special:I
a=0;// 
a=0;// .field private subject:Ljava/lang/String;
a=0;// 
a=0;// .field private subscribed:I
a=0;// 
a=0;// .field private supe_pushstatus:I
a=0;// 
a=0;// .field private tid:I
a=0;// 
a=0;// .field private totalnumber:Ljava/lang/String;
a=0;// 
a=0;// .field private typeid:I
a=0;// 
a=0;// .field private upcount:I
a=0;// 
a=0;// .field private views:I
a=0;// 
a=0;// .field private vip_level:Ljava/lang/String;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 11
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcom/twocloo/com/cn/beans/Shuping_maininfo;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public getAttachment()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 232
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->attachment:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getAuthor()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 120
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->author:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getAuthor_replied()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 280
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->author_replied:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getAuthorid()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 128
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->authorid:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getBlog()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 216
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->blog:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getClosed()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 256
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->closed:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getDateline()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 144
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->dateline:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getDigest()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 200
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->digest:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getDisplayorder()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 184
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->displayorder:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getFid()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 80
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->fid:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getHighlight()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 192
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->highlight:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getIconid()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 88
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->iconid:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getItemid()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 264
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->itemid:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getLastpost()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 152
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->lastpost:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getLastposter()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 160
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->lastposter:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getLastposterid()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 312
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->lastposterid:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getLogo()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 56
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->logo:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getMessage()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 296
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->message:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getModerated()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 248
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->moderated:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getPid()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 288
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->pid:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getPrice()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 112
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->price:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getRate()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 208
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->rate:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getReadperm()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 104
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->readperm:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getReplies()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 176
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->replies:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getSpecial()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 224
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->special:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getSubject()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 136
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->subject:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getSubscribed()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 240
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->subscribed:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getSupe_pushstatus()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 272
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->supe_pushstatus:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getTid()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 72
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->tid:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getTotalnumber()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 64
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->totalnumber:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getTypeid()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 96
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->typeid:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getUpcount()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 48
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->upcount:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getViews()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 168
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->views:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getVip_level()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 304
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->vip_level:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public setAttachment(I)V
a=0;//     .locals 0
a=0;//     .param p1, "attachment"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 236
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->attachment:I
a=0;// 
a=0;//     .line 237
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setAuthor(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "author"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 124
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->author:Ljava/lang/String;
a=0;// 
a=0;//     .line 125
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setAuthor_replied(I)V
a=0;//     .locals 0
a=0;//     .param p1, "author_replied"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 284
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->author_replied:I
a=0;// 
a=0;//     .line 285
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setAuthorid(I)V
a=0;//     .locals 0
a=0;//     .param p1, "authorid"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 132
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->authorid:I
a=0;// 
a=0;//     .line 133
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setBlog(I)V
a=0;//     .locals 0
a=0;//     .param p1, "blog"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 220
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->blog:I
a=0;// 
a=0;//     .line 221
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setClosed(I)V
a=0;//     .locals 0
a=0;//     .param p1, "closed"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 260
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->closed:I
a=0;// 
a=0;//     .line 261
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setDateline(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "dateline"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 148
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->dateline:Ljava/lang/String;
a=0;// 
a=0;//     .line 149
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setDigest(I)V
a=0;//     .locals 0
a=0;//     .param p1, "digest"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 204
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->digest:I
a=0;// 
a=0;//     .line 205
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setDisplayorder(I)V
a=0;//     .locals 0
a=0;//     .param p1, "displayorder"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 188
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->displayorder:I
a=0;// 
a=0;//     .line 189
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setFid(I)V
a=0;//     .locals 0
a=0;//     .param p1, "fid"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 84
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->fid:I
a=0;// 
a=0;//     .line 85
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setHighlight(I)V
a=0;//     .locals 0
a=0;//     .param p1, "highlight"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 196
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->highlight:I
a=0;// 
a=0;//     .line 197
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setIconid(I)V
a=0;//     .locals 0
a=0;//     .param p1, "iconid"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 92
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->iconid:I
a=0;// 
a=0;//     .line 93
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setItemid(I)V
a=0;//     .locals 0
a=0;//     .param p1, "itemid"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 268
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->itemid:I
a=0;// 
a=0;//     .line 269
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setLastpost(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "lastpost"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 156
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->lastpost:Ljava/lang/String;
a=0;// 
a=0;//     .line 157
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setLastposter(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "lastposter"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 164
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->lastposter:Ljava/lang/String;
a=0;// 
a=0;//     .line 165
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setLastposterid(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "lastposterid"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 316
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->lastposterid:Ljava/lang/String;
a=0;// 
a=0;//     .line 317
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setLogo(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "logo"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 60
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->logo:Ljava/lang/String;
a=0;// 
a=0;//     .line 61
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setMessage(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "message"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 300
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->message:Ljava/lang/String;
a=0;// 
a=0;//     .line 301
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setModerated(I)V
a=0;//     .locals 0
a=0;//     .param p1, "moderated"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 252
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->moderated:I
a=0;// 
a=0;//     .line 253
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setPid(I)V
a=0;//     .locals 0
a=0;//     .param p1, "pid"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 292
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->pid:I
a=0;// 
a=0;//     .line 293
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setPrice(I)V
a=0;//     .locals 0
a=0;//     .param p1, "price"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 116
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->price:I
a=0;// 
a=0;//     .line 117
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setRate(I)V
a=0;//     .locals 0
a=0;//     .param p1, "rate"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 212
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->rate:I
a=0;// 
a=0;//     .line 213
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setReadperm(I)V
a=0;//     .locals 0
a=0;//     .param p1, "readperm"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 108
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->readperm:I
a=0;// 
a=0;//     .line 109
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setReplies(I)V
a=0;//     .locals 0
a=0;//     .param p1, "replies"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 180
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->replies:I
a=0;// 
a=0;//     .line 181
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setSpecial(I)V
a=0;//     .locals 0
a=0;//     .param p1, "special"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 228
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->special:I
a=0;// 
a=0;//     .line 229
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setSubject(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "subject"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 140
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->subject:Ljava/lang/String;
a=0;// 
a=0;//     .line 141
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setSubscribed(I)V
a=0;//     .locals 0
a=0;//     .param p1, "subscribed"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 244
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->subscribed:I
a=0;// 
a=0;//     .line 245
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setSupe_pushstatus(I)V
a=0;//     .locals 0
a=0;//     .param p1, "supe_pushstatus"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 276
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->supe_pushstatus:I
a=0;// 
a=0;//     .line 277
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setTid(I)V
a=0;//     .locals 0
a=0;//     .param p1, "tid"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 76
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->tid:I
a=0;// 
a=0;//     .line 77
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setTotalnumber(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "totalnumber"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 68
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->totalnumber:Ljava/lang/String;
a=0;// 
a=0;//     .line 69
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setTypeid(I)V
a=0;//     .locals 0
a=0;//     .param p1, "typeid"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 100
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->typeid:I
a=0;// 
a=0;//     .line 101
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setUpcount(I)V
a=0;//     .locals 0
a=0;//     .param p1, "upcount"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 52
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->upcount:I
a=0;// 
a=0;//     .line 53
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setViews(I)V
a=0;//     .locals 0
a=0;//     .param p1, "views"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 172
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->views:I
a=0;// 
a=0;//     .line 173
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setVip_level(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "vip_level"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 308
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->vip_level:Ljava/lang/String;
a=0;// 
a=0;//     .line 309
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public toString()Ljava/lang/String;
a=0;//     .locals 2
a=0;// 
a=0;//     .prologue
a=0;//     .line 321
a=0;//     new-instance v0, Ljava/lang/StringBuilder;
a=0;// 
a=0;//     #v0=(UninitRef,Ljava/lang/StringBuilder;);
a=0;//     const-string v1, "Shuping_maininfo [tid="
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-direct {v0, v1}, Ljava/lang/StringBuilder;-><init>(Ljava/lang/String;)V
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/StringBuilder;);
a=0;//     iget v1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->tid:I
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ", fid="
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget v1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->fid:I
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ", iconid="
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget v1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->iconid:I
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ", typeid="
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget v1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->typeid:I
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ", readperm="
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget v1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->readperm:I
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ", price="
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 322
a=0;//     iget v1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->price:I
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ", author="
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->author:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ", authorid="
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget v1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->authorid:I
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ", subject="
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->subject:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ", dateline="
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->dateline:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ", lastpost="
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 323
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->lastpost:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ", lastposter="
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->lastposter:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ", views="
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget v1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->views:I
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ", replies="
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget v1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->replies:I
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ", displayorder="
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget v1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->displayorder:I
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 324
a=0;//     const-string v1, ", highlight="
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget v1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->highlight:I
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ", digest="
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget v1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->digest:I
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ", rate="
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget v1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->rate:I
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ", blog="
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget v1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->blog:I
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ", special="
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget v1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->special:I
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ", attachment="
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 325
a=0;//     iget v1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->attachment:I
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ", subscribed="
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget v1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->subscribed:I
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ", moderated="
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget v1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->moderated:I
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ", closed="
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget v1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->closed:I
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ", itemid="
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget v1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->itemid:I
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 326
a=0;//     const-string v1, ", supe_pushstatus="
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget v1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->supe_pushstatus:I
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ", author_replied="
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget v1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->author_replied:I
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ", pid="
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget v1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->pid:I
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ", message="
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->message:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 327
a=0;//     const-string v1, ", vip_level="
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->vip_level:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ", lastposterid="
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/beans/Shuping_maininfo;->lastposterid:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, "]"
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 321
a=0;//     invoke-virtual {v0}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     return-object v0
a=0;// .end method
}}
