package com.twocloo.com.cn.beans; class Shuping_huifu { void a() { int a;
a=0;// .class public Lcom/twocloo/com/cn/beans/Shuping_huifu;
a=0;// .super Ljava/lang/Object;
a=0;// .source "Shuping_huifu.java"
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field private HFlist:Ljava/util/ArrayList;
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "Ljava/util/ArrayList",
a=0;//             "<",
a=0;//             "Lcom/twocloo/com/cn/beans/Shuping_huifuinfo;",
a=0;//             ">;"
a=0;//         }
a=0;//     .end annotation
a=0;// .end field
a=0;// 
a=0;// .field private cur_page_number:I
a=0;// 
a=0;// .field private total_number:I
a=0;// 
a=0;// .field private total_page_number:I
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>()V
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 5
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     .line 9
a=0;//     #p0=(Reference,Lcom/twocloo/com/cn/beans/Shuping_huifu;);
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     iput-object v0, p0, Lcom/twocloo/com/cn/beans/Shuping_huifu;->HFlist:Ljava/util/ArrayList;
a=0;// 
a=0;//     .line 5
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public getCur_page_number()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 28
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shuping_huifu;->cur_page_number:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getHFlist()Ljava/util/ArrayList;
a=0;//     .locals 1
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "()",
a=0;//             "Ljava/util/ArrayList",
a=0;//             "<",
a=0;//             "Lcom/twocloo/com/cn/beans/Shuping_huifuinfo;",
a=0;//             ">;"
a=0;//         }
a=0;//     .end annotation
a=0;// 
a=0;//     .prologue
a=0;//     .line 36
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/Shuping_huifu;->HFlist:Ljava/util/ArrayList;
a=0;// 
a=0;//     #v0=(Reference,Ljava/util/ArrayList;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getTotal_number()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 12
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shuping_huifu;->total_number:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getTotal_page_number()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/Shuping_huifu;->total_page_number:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public setCur_page_number(I)V
a=0;//     .locals 0
a=0;//     .param p1, "cur_page_number"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 32
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shuping_huifu;->cur_page_number:I
a=0;// 
a=0;//     .line 33
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setHFlist(Ljava/util/ArrayList;)V
a=0;//     .locals 0
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "(",
a=0;//             "Ljava/util/ArrayList",
a=0;//             "<",
a=0;//             "Lcom/twocloo/com/cn/beans/Shuping_huifuinfo;",
a=0;//             ">;)V"
a=0;//         }
a=0;//     .end annotation
a=0;// 
a=0;//     .prologue
a=0;//     .line 40
a=0;//     .local p1, "hFlist":Ljava/util/ArrayList;, "Ljava/util/ArrayList<Lcom/twocloo/com/cn/beans/Shuping_huifuinfo;>;"
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/Shuping_huifu;->HFlist:Ljava/util/ArrayList;
a=0;// 
a=0;//     .line 41
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setTotal_number(I)V
a=0;//     .locals 0
a=0;//     .param p1, "total_number"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 16
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shuping_huifu;->total_number:I
a=0;// 
a=0;//     .line 17
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setTotal_page_number(I)V
a=0;//     .locals 0
a=0;//     .param p1, "total_page_number"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 24
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/Shuping_huifu;->total_page_number:I
a=0;// 
a=0;//     .line 25
a=0;//     return-void
a=0;// .end method
}}
