package com.twocloo.com.cn.beans; class SynMyfavorResultBean { void a() { int a;
a=0;// .class public Lcom/twocloo/com/cn/beans/SynMyfavorResultBean;
a=0;// .super Ljava/lang/Object;
a=0;// .source "SynMyfavorResultBean.java"
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field private add:Ljava/lang/String;
a=0;// 
a=0;// .field private del:Ljava/lang/String;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 7
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcom/twocloo/com/cn/beans/SynMyfavorResultBean;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public getAdd()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 12
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/SynMyfavorResultBean;->add:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getDel()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 20
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/SynMyfavorResultBean;->del:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public setAdd(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "add"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 16
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/SynMyfavorResultBean;->add:Ljava/lang/String;
a=0;// 
a=0;//     .line 17
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setDel(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "del"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 24
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/SynMyfavorResultBean;->del:Ljava/lang/String;
a=0;// 
a=0;//     .line 25
a=0;//     return-void
a=0;// .end method
}}
