package com.twocloo.com.cn.beans; class UnLoginRecode { void a() { int a;
a=0;// .class public Lcom/twocloo/com/cn/beans/UnLoginRecode;
a=0;// .super Ljava/lang/Object;
a=0;// .source "UnLoginRecode.java"
a=0;// 
a=0;// # interfaces
a=0;// .implements Ljava/io/Serializable;
a=0;// 
a=0;// 
a=0;// # static fields
a=0;// .field private static final serialVersionUID:J = 0x64945db2f4ed1819L
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field private _id:I
a=0;// 
a=0;// .field private bookId:Ljava/lang/String;
a=0;// 
a=0;// .field private hasSync:I
a=0;// 
a=0;// .field private textId:Ljava/lang/String;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 33
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     .line 34
a=0;//     #p0=(Reference,Lcom/twocloo/com/cn/beans/UnLoginRecode;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public constructor <init>(ILjava/lang/String;Ljava/lang/String;I)V
a=0;//     .locals 0
a=0;//     .param p1, "_id"    # I
a=0;//     .param p2, "bookId"    # Ljava/lang/String;
a=0;//     .param p3, "textId"    # Ljava/lang/String;
a=0;//     .param p4, "hasSync"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 16
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     .line 17
a=0;//     #p0=(Reference,Lcom/twocloo/com/cn/beans/UnLoginRecode;);
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/UnLoginRecode;->_id:I
a=0;// 
a=0;//     .line 18
a=0;//     iput-object p2, p0, Lcom/twocloo/com/cn/beans/UnLoginRecode;->bookId:Ljava/lang/String;
a=0;// 
a=0;//     .line 19
a=0;//     iput-object p3, p0, Lcom/twocloo/com/cn/beans/UnLoginRecode;->textId:Ljava/lang/String;
a=0;// 
a=0;//     .line 20
a=0;//     iput p4, p0, Lcom/twocloo/com/cn/beans/UnLoginRecode;->hasSync:I
a=0;// 
a=0;//     .line 21
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public getBookId()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 37
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/UnLoginRecode;->bookId:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getHasSync()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 53
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/UnLoginRecode;->hasSync:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getTextId()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 45
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/UnLoginRecode;->textId:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public get_id()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 61
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/UnLoginRecode;->_id:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public setBookId(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "bookId"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 41
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/UnLoginRecode;->bookId:Ljava/lang/String;
a=0;// 
a=0;//     .line 42
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setHasSync(I)V
a=0;//     .locals 0
a=0;//     .param p1, "hasSync"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 57
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/UnLoginRecode;->hasSync:I
a=0;// 
a=0;//     .line 58
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setTextId(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "textId"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 49
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/UnLoginRecode;->textId:Ljava/lang/String;
a=0;// 
a=0;//     .line 50
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public set_id(I)V
a=0;//     .locals 0
a=0;//     .param p1, "_id"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 65
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/UnLoginRecode;->_id:I
a=0;// 
a=0;//     .line 66
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public toString()Ljava/lang/String;
a=0;//     .locals 2
a=0;// 
a=0;//     .prologue
a=0;//     .line 25
a=0;//     new-instance v0, Ljava/lang/StringBuilder;
a=0;// 
a=0;//     #v0=(UninitRef,Ljava/lang/StringBuilder;);
a=0;//     const-string v1, "UnLoginRecode [_id="
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-direct {v0, v1}, Ljava/lang/StringBuilder;-><init>(Ljava/lang/String;)V
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/StringBuilder;);
a=0;//     iget v1, p0, Lcom/twocloo/com/cn/beans/UnLoginRecode;->_id:I
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ", bookId="
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/beans/UnLoginRecode;->bookId:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ", textId="
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lcom/twocloo/com/cn/beans/UnLoginRecode;->textId:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ", hasSync="
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget v1, p0, Lcom/twocloo/com/cn/beans/UnLoginRecode;->hasSync:I
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, "]"
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     return-object v0
a=0;// .end method
}}
