package com.twocloo.com.cn.beans; class UserCenterNewbean { void a() { int a;
a=0;// .class public Lcom/twocloo/com/cn/beans/UserCenterNewbean;
a=0;// .super Ljava/lang/Object;
a=0;// .source "UserCenterNewbean.java"
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field private age:Ljava/lang/String;
a=0;// 
a=0;// .field private birth_day:Ljava/lang/String;
a=0;// 
a=0;// .field private birth_month:Ljava/lang/String;
a=0;// 
a=0;// .field private birth_year:Ljava/lang/String;
a=0;// 
a=0;// .field private code:Ljava/lang/String;
a=0;// 
a=0;// .field private email:Ljava/lang/String;
a=0;// 
a=0;// .field private gender:Ljava/lang/String;
a=0;// 
a=0;// .field private logoUrl:Ljava/lang/String;
a=0;// 
a=0;// .field private mark:Ljava/lang/String;
a=0;// 
a=0;// .field private message_count:I
a=0;// 
a=0;// .field private mobile:Ljava/lang/String;
a=0;// 
a=0;// .field private nickname:Ljava/lang/String;
a=0;// 
a=0;// .field private show_assignment:Ljava/lang/String;
a=0;// 
a=0;// .field private show_offers:Ljava/lang/String;
a=0;// 
a=0;// .field private shuquan_count:Ljava/lang/String;
a=0;// 
a=0;// .field private sign:Ljava/lang/String;
a=0;// 
a=0;// .field private star:Ljava/lang/String;
a=0;// 
a=0;// .field private tuijianpiao_count:Ljava/lang/String;
a=0;// 
a=0;// .field private username:Ljava/lang/String;
a=0;// 
a=0;// .field private yuedubi_count:Ljava/lang/String;
a=0;// 
a=0;// .field private yuepiao_count:Ljava/lang/String;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 9
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcom/twocloo/com/cn/beans/UserCenterNewbean;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public getAge()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 99
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->age:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getBirth_day()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 67
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->birth_day:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getBirth_month()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 35
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->birth_month:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getBirth_year()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 59
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->birth_year:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getCode()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 171
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->code:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getEmail()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 91
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->email:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getGender()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 115
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->gender:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getLogoUrl()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 147
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->logoUrl:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getMark()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 123
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->mark:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getMessage_count()I
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 107
a=0;//     iget v0, p0, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->message_count:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getMobile()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 139
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->mobile:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getNickname()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 51
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->nickname:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getShow_assignment()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 187
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->show_assignment:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getShow_offers()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 131
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->show_offers:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getShuquan_count()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 195
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->shuquan_count:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getSign()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 75
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->sign:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getStar()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 43
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->star:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getTuijianpiao_count()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 163
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->tuijianpiao_count:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getUsername()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 83
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->username:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getYuedubi_count()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 179
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->yuedubi_count:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getYuepiao_count()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 155
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->yuepiao_count:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public setAge(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "age"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 103
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->age:Ljava/lang/String;
a=0;// 
a=0;//     .line 104
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setBirth_day(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "birth_day"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 71
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->birth_day:Ljava/lang/String;
a=0;// 
a=0;//     .line 72
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setBirth_month(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "birth_month"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 39
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->birth_month:Ljava/lang/String;
a=0;// 
a=0;//     .line 40
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setBirth_year(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "birth_year"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 63
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->birth_year:Ljava/lang/String;
a=0;// 
a=0;//     .line 64
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setCode(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "code"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 175
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->code:Ljava/lang/String;
a=0;// 
a=0;//     .line 176
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setEmail(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "email"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 95
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->email:Ljava/lang/String;
a=0;// 
a=0;//     .line 96
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setGender(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "gender"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 119
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->gender:Ljava/lang/String;
a=0;// 
a=0;//     .line 120
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setLogoUrl(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "logoUrl"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 151
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->logoUrl:Ljava/lang/String;
a=0;// 
a=0;//     .line 152
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setMark(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "mark"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 127
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->mark:Ljava/lang/String;
a=0;// 
a=0;//     .line 128
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setMessage_count(I)V
a=0;//     .locals 0
a=0;//     .param p1, "message_count"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 111
a=0;//     iput p1, p0, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->message_count:I
a=0;// 
a=0;//     .line 112
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setMobile(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "mobile"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 143
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->mobile:Ljava/lang/String;
a=0;// 
a=0;//     .line 144
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setNickname(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "nickname"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 55
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->nickname:Ljava/lang/String;
a=0;// 
a=0;//     .line 56
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setShow_assignment(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "show_assignment"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 191
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->show_assignment:Ljava/lang/String;
a=0;// 
a=0;//     .line 192
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setShow_offers(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "show_offers"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 135
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->show_offers:Ljava/lang/String;
a=0;// 
a=0;//     .line 136
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setShuquan_count(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "shuquan_count"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 199
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->shuquan_count:Ljava/lang/String;
a=0;// 
a=0;//     .line 200
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setSign(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "sign"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 79
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->sign:Ljava/lang/String;
a=0;// 
a=0;//     .line 80
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setStar(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "star"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 47
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->star:Ljava/lang/String;
a=0;// 
a=0;//     .line 48
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setTuijianpiao_count(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "tuijianpiao_count"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 167
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->tuijianpiao_count:Ljava/lang/String;
a=0;// 
a=0;//     .line 168
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setUsername(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "username"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 87
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->username:Ljava/lang/String;
a=0;// 
a=0;//     .line 88
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setYuedubi_count(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "yuedubi_count"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 183
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->yuedubi_count:Ljava/lang/String;
a=0;// 
a=0;//     .line 184
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setYuepiao_count(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "yuepiao_count"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 159
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/UserCenterNewbean;->yuepiao_count:Ljava/lang/String;
a=0;// 
a=0;//     .line 160
a=0;//     return-void
a=0;// .end method
}}
