package com.twocloo.com.cn.beans; class UserCoinDetailbean { void a() { int a;
a=0;// .class public Lcom/twocloo/com/cn/beans/UserCoinDetailbean;
a=0;// .super Ljava/lang/Object;
a=0;// .source "UserCoinDetailbean.java"
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field private code:Ljava/lang/String;
a=0;// 
a=0;// .field private rc:Ljava/util/ArrayList;
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "Ljava/util/ArrayList",
a=0;//             "<",
a=0;//             "Lcom/twocloo/com/cn/beans/RecordContent;",
a=0;//             ">;"
a=0;//         }
a=0;//     .end annotation
a=0;// .end field
a=0;// 
a=0;// .field private youxiaoqi:Ljava/lang/String;
a=0;// 
a=0;// .field private yuedubi_count:Ljava/lang/String;
a=0;// 
a=0;// .field private zengbi_count:Ljava/lang/String;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 5
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcom/twocloo/com/cn/beans/UserCoinDetailbean;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public getCode()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 38
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/UserCoinDetailbean;->code:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getRc()Ljava/util/ArrayList;
a=0;//     .locals 1
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "()",
a=0;//             "Ljava/util/ArrayList",
a=0;//             "<",
a=0;//             "Lcom/twocloo/com/cn/beans/RecordContent;",
a=0;//             ">;"
a=0;//         }
a=0;//     .end annotation
a=0;// 
a=0;//     .prologue
a=0;//     .line 30
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/UserCoinDetailbean;->rc:Ljava/util/ArrayList;
a=0;// 
a=0;//     #v0=(Reference,Ljava/util/ArrayList;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getYouxiaoqi()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 14
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/UserCoinDetailbean;->youxiaoqi:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getYuedubi_count()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 46
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/UserCoinDetailbean;->yuedubi_count:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getZengbi_count()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 22
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/UserCoinDetailbean;->zengbi_count:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public setCode(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "code"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 42
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/UserCoinDetailbean;->code:Ljava/lang/String;
a=0;// 
a=0;//     .line 43
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setRc(Ljava/util/ArrayList;)V
a=0;//     .locals 0
a=0;//     .annotation system Ldalvik/annotation/Signature;
a=0;//         value = {
a=0;//             "(",
a=0;//             "Ljava/util/ArrayList",
a=0;//             "<",
a=0;//             "Lcom/twocloo/com/cn/beans/RecordContent;",
a=0;//             ">;)V"
a=0;//         }
a=0;//     .end annotation
a=0;// 
a=0;//     .prologue
a=0;//     .line 34
a=0;//     .local p1, "rc":Ljava/util/ArrayList;, "Ljava/util/ArrayList<Lcom/twocloo/com/cn/beans/RecordContent;>;"
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/UserCoinDetailbean;->rc:Ljava/util/ArrayList;
a=0;// 
a=0;//     .line 35
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setYouxiaoqi(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "youxiaoqi"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 18
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/UserCoinDetailbean;->youxiaoqi:Ljava/lang/String;
a=0;// 
a=0;//     .line 19
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setYuedubi_count(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "yuedubi_count"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 50
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/UserCoinDetailbean;->yuedubi_count:Ljava/lang/String;
a=0;// 
a=0;//     .line 51
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setZengbi_count(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "zengbi_count"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 26
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/UserCoinDetailbean;->zengbi_count:Ljava/lang/String;
a=0;// 
a=0;//     .line 27
a=0;//     return-void
a=0;// .end method
}}
