package com.twocloo.com.cn.beans; class Version { void a() { int a;
a=0;// .class public Lcom/twocloo/com/cn/beans/Version;
a=0;// .super Ljava/lang/Object;
a=0;// .source "Version.java"
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field private appname:Ljava/lang/String;
a=0;// 
a=0;// .field private appurl:Ljava/lang/String;
a=0;// 
a=0;// .field private subver:Ljava/lang/String;
a=0;// 
a=0;// .field private versionCode:Ljava/lang/String;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 3
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcom/twocloo/com/cn/beans/Version;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public getAppname()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 21
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/Version;->appname:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getAppurl()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 27
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/Version;->appurl:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getSubver()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 15
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/Version;->subver:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getVersionCode()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     .prologue
a=0;//     .line 9
a=0;//     iget-object v0, p0, Lcom/twocloo/com/cn/beans/Version;->versionCode:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public setAppname(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "appname"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 24
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/Version;->appname:Ljava/lang/String;
a=0;// 
a=0;//     .line 25
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setAppurl(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "appurl"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 30
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/Version;->appurl:Ljava/lang/String;
a=0;// 
a=0;//     .line 31
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setSubver(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "subver"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 18
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/Version;->subver:Ljava/lang/String;
a=0;// 
a=0;//     .line 19
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setVersionCode(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;//     .param p1, "versionCode"    # Ljava/lang/String;
a=0;// 
a=0;//     .prologue
a=0;//     .line 12
a=0;//     iput-object p1, p0, Lcom/twocloo/com/cn/beans/Version;->versionCode:Ljava/lang/String;
a=0;// 
a=0;//     .line 13
a=0;//     return-void
a=0;// .end method
}}
